<?php

namespace App\Console\Commands;

use App\Models\ArchiveRecord;
use Illuminate\Console\Command;

/**
 * Register every available issue of The Black Panther: Black
 * Community News Service (1967-1970) as its own ArchiveRecord. PDFs
 * are mirrored locally at /pdfs/bpp-newspaper/ — 69 individual issue
 * scans totaling ~2.4 GB, sourced from the jadelin.mcleod Internet
 * Archive uploads plus the 1967-1968 bulk-collection scans for the
 * five issues only available there.
 *
 * Supersedes the earlier "ia-full-run" external-link record from #477,
 * which is deleted here so each issue has a single canonical record.
 *
 * Idempotent — re-runs update by slug.
 */
final class AddBppNewspaperIndividualIssues extends Command {
    protected $signature = 'archive:add-bpp-newspaper-individual';
    protected $description = 'Register all individual issues of The Black Panther newspaper (1967-1970) as their own ArchiveRecord rows';

    public function handle(): int {
        // Remove the obsolete "external IA full-run link" record from #477
        // so it doesn't duplicate the per-issue rows now being created.
        $obsolete = ArchiveRecord::where('slug', 'the-black-panther-newspaper-1967-1970-ia-full-run')->first();
        if ($obsolete) {
            $obsolete->delete();
            $this->info('Deleted obsolete record: the-black-panther-newspaper-1967-1970-ia-full-run');
        }

        $records = [
            [
                'slug' => 'the-black-panther-vol-1-no-1-1967-04-25',
                'title' => "The Black Panther: Black Community News Service — Vol. 1 No. 1 (April 25, 1967)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 1, Number 1, published April 25, 1967. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: the-black-panther-newspaper-1967-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-01-no-01-1967-04-25.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1967,
                'date' => '1967-04-25',
                'volume' => 'Vol. 1 No. 1',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-1-no-2-1967-05-15',
                'title' => "The Black Panther: Black Community News Service — Vol. 1 No. 2 (May 15, 1967)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 1, Number 2, published May 15, 1967. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: the-black-panther-newspaper-1967-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-01-no-02-1967-05-15.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1967,
                'date' => '1967-05-15',
                'volume' => 'Vol. 1 No. 2',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-1-no-3-1967-06-20',
                'title' => "The Black Panther: Black Community News Service — Vol. 1 No. 3 (June 20, 1967)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 1, Number 3, published June 20, 1967. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: the-black-panther-newspaper-1967-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-01-no-03-1967-06-20.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1967,
                'date' => '1967-06-20',
                'volume' => 'Vol. 1 No. 3',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-1-no-4-1967-07-03',
                'title' => "The Black Panther: Black Community News Service — Vol. 1 No. 4 (July 3, 1967)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 1, Number 4, published July 3, 1967. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 01-no-4-1-11-jul-3-1967.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-01-no-04-1967-07-03.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1967,
                'date' => '1967-07-03',
                'volume' => 'Vol. 1 No. 4',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-1-no-5-1967-09-20',
                'title' => "The Black Panther: Black Community News Service — Vol. 1 No. 5 (September 20, 1967)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 1, Number 5, published September 20, 1967. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: the-black-panther-newspaper-1967-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-01-no-05-1967-09-20.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1967,
                'date' => '1967-09-20',
                'volume' => 'Vol. 1 No. 5',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-1-1968-03-16',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 1 (March 16, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 1, published March 16, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-1-1-24-mar-16-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-01-1968-03-16.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-03-16',
                'volume' => 'Vol. 2 No. 1',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-2-1968-05-04',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 2 (May 4, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 2, published May 4, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-2-1-28-may-4-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-02-1968-05-04.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-05-04',
                'volume' => 'Vol. 2 No. 2',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-3-1968-05-18',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 3 (May 18, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 3, published May 18, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-3-1-28-may-18-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-03-1968-05-18.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-05-18',
                'volume' => 'Vol. 2 No. 3',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-5-1968-09-07',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 5 (September 7, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 5, published September 7, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-5-1-16-sep-7-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-05-1968-09-07.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-09-07',
                'volume' => 'Vol. 2 No. 5',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-6-1968-09-14',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 6 (September 14, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 6, published September 14, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-6-1-14-sep-14-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-06-1968-09-14.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-09-14',
                'volume' => 'Vol. 2 No. 6',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-7-1968-09-28',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 7 (September 28, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 7, published September 28, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-7-1-23-sep-28-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-07-1968-09-28.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-09-28',
                'volume' => 'Vol. 2 No. 7',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-8-1968-10-05',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 8 (October 5, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 8, published October 5, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-8-1-16-oct-5-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-08-1968-10-05.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-10-05',
                'volume' => 'Vol. 2 No. 8',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-9-1968-10-12',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 9 (October 12, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 9, published October 12, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-9-1-24-oct-12-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-09-1968-10-12.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-10-12',
                'volume' => 'Vol. 2 No. 9',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-9-1968-10-19',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 9 (October 19, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 9, published October 19, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-9-1-20-oct-19-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-09-1968-10-19.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-10-19',
                'volume' => 'Vol. 2 No. 9',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-10-1968-10-26',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 10 (October 26, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 10, published October 26, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-10-1-24-oct-26-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-10-1968-10-26.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-10-26',
                'volume' => 'Vol. 2 No. 10',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-11-1968-11-02',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 11 (November 2, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 11, published November 2, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-11-1-24-nov-2-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-11-1968-11-02.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-11-02',
                'volume' => 'Vol. 2 No. 11',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-15-1968-12-07',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 15 (December 7, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 15, published December 7, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-15-17-1-16-dec-7-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-15-1968-12-07.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-12-07',
                'volume' => 'Vol. 2 No. 15',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-18-1968-12-21',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 18 (December 21, 1968)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 18, published December 21, 1968. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-18-1-24-dec-21-1968.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-18-1968-12-21.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1968,
                'date' => '1968-12-21',
                'volume' => 'Vol. 2 No. 18',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-19-1969-01-04',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 19 (January 4, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 19, published January 4, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-19-1-24-jan-4-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-19-1969-01-04.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-01-04',
                'volume' => 'Vol. 2 No. 19',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-20-1969-01-15',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 20 (January 15, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 20, published January 15, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-20-1-16-jan-15-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-20-1969-01-15.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-01-15',
                'volume' => 'Vol. 2 No. 20',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-21-1969-01-25',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 21 (January 25, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 21, published January 25, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-21-1-24-jan-25-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-21-1969-01-25.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-01-25',
                'volume' => 'Vol. 2 No. 21',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-21-1969-02-02',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 21 (February 2, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 21, published February 2, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-21-1-24-feb-2-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-21-1969-02-02.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-02-02',
                'volume' => 'Vol. 2 No. 21',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-23-1969-02-17',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 23 (February 17, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 23, published February 17, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-23-1-24-feb-17-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-23-1969-02-17.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-02-17',
                'volume' => 'Vol. 2 No. 23',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-24-1969-03-03',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 24 (March 3, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 24, published March 3, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-24-1-20-mar-3-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-24-1969-03-03.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-03-03',
                'volume' => 'Vol. 2 No. 24',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-25-1969-03-09',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 25 (March 9, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 25, published March 9, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-25-1-20-mar-9-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-25-1969-03-09.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-03-09',
                'volume' => 'Vol. 2 No. 25',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-26-1969-03-16',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 26 (March 16, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 26, published March 16, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-26-1-24-mar-16-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-26-1969-03-16.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-03-16',
                'volume' => 'Vol. 2 No. 26',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-27-1969-03-23',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 27 (March 23, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 27, published March 23, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-27-1-24-mar-23-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-27-1969-03-23.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-03-23',
                'volume' => 'Vol. 2 No. 27',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-28-1969-03-31',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 28 (March 31, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 28, published March 31, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-28-1-24-mar-31-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-28-1969-03-31.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-03-31',
                'volume' => 'Vol. 2 No. 28',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-29-1969-04-06',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 29 (April 6, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 29, published April 6, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-29-1-24-apr-6-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-29-1969-04-06.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-04-06',
                'volume' => 'Vol. 2 No. 29',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-2-no-30-1969-04-20',
                'title' => "The Black Panther: Black Community News Service — Vol. 2 No. 30 (April 20, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 2, Number 30, published April 20, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 02-no-30-1-24-apr-20-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-02-no-30-1969-04-20.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-04-20',
                'volume' => 'Vol. 2 No. 30',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-1-1969-04-27',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 1 (April 27, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 1, published April 27, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-1-1-20-apr-27-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-01-1969-04-27.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-04-27',
                'volume' => 'Vol. 3 No. 1',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-2-1969-05-04',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 2 (May 4, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 2, published May 4, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-2-1-22-may-4-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-02-1969-05-04.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-05-04',
                'volume' => 'Vol. 3 No. 2',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-3-1969-05-11',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 3 (May 11, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 3, published May 11, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-3-1-24-may-11-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-03-1969-05-11.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-05-11',
                'volume' => 'Vol. 3 No. 3',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-4-1969-05-19',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 4 (May 19, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 4, published May 19, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-4-1-22-may-19-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-04-1969-05-19.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-05-19',
                'volume' => 'Vol. 3 No. 4',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-5-1969-05-25',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 5 (May 25, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 5, published May 25, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-5-1-20-may-25-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-05-1969-05-25.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-05-25',
                'volume' => 'Vol. 3 No. 5',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-6-1969-05-31',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 6 (May 31, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 6, published May 31, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-6-1-18-may-31-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-06-1969-05-31.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-05-31',
                'volume' => 'Vol. 3 No. 6',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-7-1969-06-07',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 7 (June 7, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 7, published June 7, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-7-1-23-jun-7-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-07-1969-06-07.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-06-07',
                'volume' => 'Vol. 3 No. 7',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-8-1969-06-14',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 8 (June 14, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 8, published June 14, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-8-1-22-jun-14-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-08-1969-06-14.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-06-14',
                'volume' => 'Vol. 3 No. 8',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-9-1969-06-21',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 9 (June 21, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 9, published June 21, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-9-1-24-jun-21-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-09-1969-06-21.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-06-21',
                'volume' => 'Vol. 3 No. 9',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-10-1969-06-28',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 10 (June 28, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 10, published June 28, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-10-1-24-jun-28-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-10-1969-06-28.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-06-28',
                'volume' => 'Vol. 3 No. 10',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-11-1969-07-05',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 11 (July 5, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 11, published July 5, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-11-1-24-jul-5-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-11-1969-07-05.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-07-05',
                'volume' => 'Vol. 3 No. 11',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-12-1969-07-12',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 12 (July 12, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 12, published July 12, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-12-1-24-jul-12-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-12-1969-07-12.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-07-12',
                'volume' => 'Vol. 3 No. 12',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-13-1969-07-19',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 13 (July 19, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 13, published July 19, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-13-1-28-jul-19-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-13-1969-07-19.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-07-19',
                'volume' => 'Vol. 3 No. 13',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-14-1969-07-26',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 14 (July 26, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 14, published July 26, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-14-1-24-jul-26-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-14-1969-07-26.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-07-26',
                'volume' => 'Vol. 3 No. 14',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-14-1969-08-02',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 14 (August 2, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 14, published August 2, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-14-1-24-aug-2-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-14-1969-08-02.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-08-02',
                'volume' => 'Vol. 3 No. 14',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-16-1969-08-09',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 16 (August 9, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 16, published August 9, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-16-1-28-aug-9-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-16-1969-08-09.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-08-09',
                'volume' => 'Vol. 3 No. 16',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-17-1969-08-16',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 17 (August 16, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 17, published August 16, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-17-1-33-aug-16-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-17-1969-08-16.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-08-16',
                'volume' => 'Vol. 3 No. 17',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-19-1969-08-30',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 19 (August 30, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 19, published August 30, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-19-1-23-aug-30-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-19-1969-08-30.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-08-30',
                'volume' => 'Vol. 3 No. 19',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-20-1969-09-06',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 20 (September 6, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 20, published September 6, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-20-1-20-sep-6-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-20-1969-09-06.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-09-06',
                'volume' => 'Vol. 3 No. 20',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-21-1969-09-13',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 21 (September 13, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 21, published September 13, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-21-1-20-sep-13-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-21-1969-09-13.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-09-13',
                'volume' => 'Vol. 3 No. 21',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-22-1969-09-20',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 22 (September 20, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 22, published September 20, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-22-1-20-sep-20-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-22-1969-09-20.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-09-20',
                'volume' => 'Vol. 3 No. 22',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-23-1969-09-27',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 23 (September 27, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 23, published September 27, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-23-1-20-sep-27-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-23-1969-09-27.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-09-27',
                'volume' => 'Vol. 3 No. 23',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-24-1969-10-04',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 24 (October 4, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 24, published October 4, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-24-1-20-oct-4-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-24-1969-10-04.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-10-04',
                'volume' => 'Vol. 3 No. 24',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-25-1969-10-11',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 25 (October 11, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 25, published October 11, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-25-1-20-ot-11-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-25-1969-10-11.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-10-11',
                'volume' => 'Vol. 3 No. 25',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-26-1969-10-18',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 26 (October 18, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 26, published October 18, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-26-1-11-oct-18-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-26-1969-10-18.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-10-18',
                'volume' => 'Vol. 3 No. 26',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-27-1969-10-25',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 27 (October 25, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 27, published October 25, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-27-1-23-oct-25-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-27-1969-10-25.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-10-25',
                'volume' => 'Vol. 3 No. 27',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-28-1969-11-01',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 28 (November 1, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 28, published November 1, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-28-1-24-nov-1-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-28-1969-11-01.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-11-01',
                'volume' => 'Vol. 3 No. 28',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-29-1969-11-08',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 29 (November 8, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 29, published November 8, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-29-1-24-nov-8-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-29-1969-11-08.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-11-08',
                'volume' => 'Vol. 3 No. 29',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-30-1969-11-15',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 30 (November 15, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 30, published November 15, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-30-1-20-nov-15-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-30-1969-11-15.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-11-15',
                'volume' => 'Vol. 3 No. 30',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-31-1969-11-22',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 31 (November 22, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 31, published November 22, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-31-1-16-nov-22-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-31-1969-11-22.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-11-22',
                'volume' => 'Vol. 3 No. 31',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-3-no-32-1969-11-29',
                'title' => "The Black Panther: Black Community News Service — Vol. 3 No. 32 (November 29, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 3, Number 32, published November 29, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 03-no-32-1-20-nov-29-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-03-no-32-1969-11-29.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-11-29',
                'volume' => 'Vol. 3 No. 32',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-1-1969-12-06',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 1 (December 6, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 1, published December 6, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-1-1-20-dec-6-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-01-1969-12-06.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-12-06',
                'volume' => 'Vol. 4 No. 1',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-2-1969-12-13',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 2 (December 13, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 2, published December 13, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-2-1-20-dec-13-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-02-1969-12-13.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-12-13',
                'volume' => 'Vol. 4 No. 2',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-4-1969-12-27',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 4 (December 27, 1969)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 4, published December 27, 1969. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-4-1-20-dec-27-1969.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-04-1969-12-27.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1969,
                'date' => '1969-12-27',
                'volume' => 'Vol. 4 No. 4',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-5-1970-01-03',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 5 (January 3, 1970)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 5, published January 3, 1970. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-5-1-24-jan-3-1970.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-05-1970-01-03.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1970,
                'date' => '1970-01-03',
                'volume' => 'Vol. 4 No. 5',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-6-1970-01-10',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 6 (January 10, 1970)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 6, published January 10, 1970. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-6-1-20-jan-10-1970.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-06-1970-01-10.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1970,
                'date' => '1970-01-10',
                'volume' => 'Vol. 4 No. 6',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-7-1970-01-17',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 7 (January 17, 1970)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 7, published January 17, 1970. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-7-1-20-jan-17-1970.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-07-1970-01-17.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1970,
                'date' => '1970-01-17',
                'volume' => 'Vol. 4 No. 7',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-8-1970-01-24',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 8 (January 24, 1970)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 8, published January 24, 1970. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-8-1-16-jan-24-1970.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-08-1970-01-24.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1970,
                'date' => '1970-01-24',
                'volume' => 'Vol. 4 No. 8',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
            [
                'slug' => 'the-black-panther-vol-4-no-3-1970-07-25',
                'title' => "The Black Panther: Black Community News Service — Vol. 4 No. 3 (July 25, 1970)",
                'description' => "Issue of The Black Panther: Black Community News Service, the official newspaper of the Black Panther Party for Self-Defense — Volume 4, Number 3, published July 25, 1970. Part of NPPC's complete-as-available 1967-1970 BPP newspaper run mirrored from the Internet Archive uploads of jadelin.mcleod. The Black Panther was the largest-circulation U.S. Black radical newspaper of the twentieth century, peaking at a claimed 150,000+ national and international circulation in 1970. Internet Archive source identifier: 04-no-3-1-20-jul-25-1970.",
                'record_type' => 'newspaper',
                'source_format' => 'newspaper',
                'file' => '/pdfs/bpp-newspaper/the-black-panther-vol-04-no-03-1970-07-25.pdf',
                'collection' => 'The Black Panther Newspaper',
                'authors' => 'Black Panther Party for Self-Defense',
                'publisher' => 'Black Panther Party for Self-Defense',
                'year' => 1970,
                'date' => '1970-07-25',
                'volume' => 'Vol. 4 No. 3',
                'subjects' => ['Black Panther Party', 'BPP', 'The Black Panther', 'Black Liberation'],
            ],
        ];

        $base = [
            'is_digitized' => true,
            'published' => true,
        ];

        $added = 0; $updated = 0;
        foreach ($records as $r) {
            $slug = $r['slug']; unset($r['slug']);
            $payload = $r + $base;
            $existing = ArchiveRecord::where('slug', $slug)->first();
            if ($existing) {
                $existing->update($payload);
                $updated++;
            } else {
                ArchiveRecord::create(['slug' => $slug] + $payload);
                $added++;
            }
        }
        $this->info("Done — added {$added}, updated {$updated}.");
        return self::SUCCESS;
    }
}
