<?php

namespace App\Console\Commands;

use App\Models\Prisoner;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;

/**
 * Add political prisoners surfaced by reviewing every NPPC news article
 * published BEFORE the "Remembering Ed Mead" memorial (2023-11-26). Those
 * 47 articles are largely imported Civil Liberties Defense Center (CLDC)
 * case coverage from 2012–2023.
 *
 * Behaviour:
 *   - Creates each prisoner (with cases) via the canonical `prisoner:add`
 *     pipeline, which skips anyone already present by exact name.
 *   - For prisoners that ALREADY exist, applies the release date from the
 *     source article to their case when the case has none yet (so the
 *     "someone was released" articles update existing records too).
 *
 * Idempotent — safe to re-run.
 *
 * CAVEATS (verify before relying on specifics):
 *   - Where a field was not stated in the article it is omitted. A few
 *     well-documented facts for famous figures (Manning's 35-yr sentence
 *     and 2017 commutation; Peltier's two life terms; Stewart's 2005
 *     conviction and 2017 death; Marius Mason's ~22-yr sentence; the
 *     death/release dates for Wallace and Buck) are drawn from public
 *     record, NOT from the articles.
 *   - Disposition unverified for: Loren Reed (article predates his trial),
 *     Sam Jessup (verdict not stated), George Sexton (statute voided; no
 *     standing conviction stated), F. Emily Semple (charges dismissed).
 *   - Many entries (MN valve turners, Line 3 water protectors, Springfield
 *     BLM, Eugene cases) were CHARGED for political acts but acquitted or
 *     had charges dismissed — included as requested; `convicted` reflects
 *     that.
 */
final class AddCldcArchivePrisoners extends Command {
    protected $signature = 'prisoners:add-cldc-archive';
    protected $description = 'Add political prisoners mined from pre-2023-11-26 CLDC news coverage (idempotent; updates release dates on existing records)';

    public function handle(): int {
        $entries = json_decode($this->entriesJson(), true);
        if (! is_array($entries)) {
            $this->error('Internal error: entry JSON failed to decode.');
            return self::FAILURE;
        }

        $created = 0; $existing = 0; $releaseUpdated = 0;

        foreach ($entries as $e) {
            $name = $e['name'];
            $found = Prisoner::where('name', $name)->first();

            if ($found) {
                $existing++;
                $this->warn("Exists: {$name}");
                if ($this->applyReleaseDate($found, $e)) {
                    $releaseUpdated++;
                }
                continue;
            }

            Artisan::call('prisoner:add', [
                'json' => json_encode($e, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            ]);
            $out = trim(Artisan::output());
            $this->line($out !== '' ? $out : "Added {$name}");
            $created++;
        }

        $this->info("\nDone. Created {$created}, already-present {$existing} (release date set on {$releaseUpdated}).");
        return self::SUCCESS;
    }

    /**
     * For an already-existing prisoner, copy the article's release date onto
     * a case that has none yet, and flag them released. Never overwrites an
     * existing release date. Returns true if it changed anything.
     */
    private function applyReleaseDate(Prisoner $prisoner, array $entry): bool {
        $release = $entry['cases'][0]['release_date'] ?? null;
        if (! $release) {
            return false;
        }

        // Prefer a case that has no release date recorded.
        $case = $prisoner->cases()->whereNull('release_date')->first()
            ?? $prisoner->cases()->first();

        if (! $case) {
            $this->line("  (no case on record — left unchanged)");
            return false;
        }
        if (! empty($case->release_date)) {
            $this->line("  release date already set — left unchanged");
            return false;
        }

        $case->release_date = $release;
        $case->save();
        $prisoner->released = true;
        $prisoner->in_custody = false;
        $prisoner->save();
        $this->info("  set release date {$release} on existing record");
        return true;
    }

    /** All entries as one JSON document (literal — no PHP escaping). */
    private function entriesJson(): string {
        return <<<'JSON'
[
  {"name":"Chelsea Manning","first_name":"Chelsea","last_name":"Manning","description":"U.S. Army intelligence analyst who in 2010 disclosed hundreds of thousands of classified military and State Department documents to WikiLeaks, exposing abuses during the Iraq and Afghanistan wars. Convicted under the Espionage Act in 2013 and sentenced to 35 years; her sentence was commuted by President Obama in 2017. Featured in early CLDC/NPPC coverage as a soldier facing life in prison for revealing the truth.","gender":"Female","ideologies":["Anti-war","Transparency","Whistleblower"],"era":"War on Terror","in_custody":false,"released":true,"cases":[{"institution_name":"United States Disciplinary Barracks, Fort Leavenworth","institution_state":"Kansas","charges":"Espionage Act violations; theft of government property (disclosure of classified records to WikiLeaks)","incarceration_date":"2010-05-27","release_date":"2017-05-17","sentence":"35 years (commuted by President Obama in 2017)","convicted":"Yes — court-martial, 2013"}]},
  {"name":"Leonard Peltier","first_name":"Leonard","last_name":"Peltier","description":"Longtime Native American activist and member of the American Indian Movement (AIM), convicted in 1977 for the 1975 deaths of two FBI agents at the Pine Ridge Reservation after a trial widely condemned by human-rights groups. Imprisoned for over four decades; granted home confinement in 2025. NPPC/CLDC coverage notes prosecutors later conceded they could not prove who killed the agents.","race":"Native American","gender":"Male","ideologies":["Indigenous rights","American Indian Movement"],"affiliation":["American Indian Movement"],"era":"Black liberation","in_custody":false,"released":true,"cases":[{"institution_name":"USP Coleman","institution_state":"Florida","charges":"First-degree murder of two FBI agents (Pine Ridge, 1975)","incarceration_date":"1976-02-06","sentence":"Two consecutive life terms; home confinement granted 2025","convicted":"Yes — 1977"}]},
  {"name":"Lynne Stewart","first_name":"Lynne","last_name":"Stewart","description":"Radical civil-rights and movement-defense attorney convicted in 2005 of providing material support to terrorism for relaying messages from her client to the press. Imprisoned at FMC Carswell, she waged a public fight for compassionate release while terminally ill with cancer, granted in late 2013/early 2014. She died in 2017. NPPC/CLDC coverage reproduced her appeal denouncing the Bureau of Prisons for holding political prisoners until near death.","gender":"Female","state":"New York","ideologies":["Civil rights","Movement lawyering"],"in_custody":false,"released":true,"death_date":"2017-03-07","cases":[{"institution_name":"FMC Carswell","institution_state":"Texas","charges":"Conspiracy and providing material support to terrorism (relaying client communications)","incarceration_date":"2009-11-19","release_date":"2014-01-01","sentence":"10 years (compassionate release granted Dec 2013/Jan 2014)","convicted":"Yes — 2005"}]},
  {"name":"Joseph Dibee","first_name":"Joseph","last_name":"Dibee","description":"Earth Liberation Front / Animal Liberation Front activist indicted in 2006 in the federal Operation Backfire (\"Green Scare\") roundup for a string of 1990s–2001 economic-sabotage arsons. He evaded capture for 12 years until arrested in 2018, was held in Portland, and released on conditions in January 2021. In April 2022 he pleaded guilty to three counts including conspiracy and the arson of the Cavel West horse slaughterhouse.","state":"Oregon","ideologies":["Earth Liberation Front","Animal Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front","Animal Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"U.S. District Court, District of Oregon","institution_state":"Oregon","charges":"Conspiracy to destroy property by fire; arson (Cavel West horse slaughterhouse); conspiracy to commit arson","arrest_date":"2018-08-09","incarceration_date":"2018-08-10","release_date":"2021-01-08","sentence":"Plea deal April 2022; advisory range 87–108 months","convicted":"Yes — guilty plea, 2022"}]},
  {"name":"Daniel McGowan","first_name":"Daniel","last_name":"McGowan","description":"Earth Liberation Front activist and Operation Backfire (\"Green Scare\") defendant who pleaded guilty to arson-related charges for two 2001 ELF actions in Oregon. A non-cooperating defendant, he served roughly seven years, much of it in a restrictive federal Communication Management Unit, and was released in December 2012. In April 2013 he was briefly re-jailed over a Huffington Post blog post under a prison regulation later found unconstitutional, then returned to his halfway house.","state":"Oregon","ideologies":["Earth Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communication Management Unit)","charges":"Arson and conspiracy (ELF actions, 2001)","release_date":"2012-12-11","sentence":"~7 years (released Dec 2012; sentence ended June 2013)","convicted":"Yes — guilty plea"}]},
  {"name":"Marius Mason","first_name":"Marius","last_name":"Mason","description":"Earth Liberation Front / Animal Liberation Front activist and Operation Backfire (\"Green Scare\") defendant. A non-cooperating defendant, he pleaded guilty to eco-sabotage including a 1999 arson at a Michigan State University genetic-engineering lab and received the longest sentence of any Green Scare defendant. NPPC coverage (2018) noted he was the only Green Scare defendant still imprisoned at the time of Joseph Dibee's arrest. A transgender man, his case has drawn extensive solidarity organizing.","gender":"Male","ideologies":["Earth Liberation Front","Animal Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front","Animal Liberation Front"],"era":"Green Scare","in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Arson and destruction of property (ELF/ALF eco-sabotage, incl. 1999 Michigan State University lab arson)","sentence":"Nearly 22 years (public record; not stated in article)","convicted":"Yes — guilty plea, 2009"}]},
  {"name":"Jonathan Paul","first_name":"Jonathan","last_name":"Paul","description":"Animal Liberation Front / Earth Liberation Front activist and Operation Backfire (\"Green Scare\") defendant. One of the non-cooperating defendants who refused to inform on co-defendants and served additional prison time for his role in 1990s–2001 eco-sabotage actions.","ideologies":["Animal Liberation Front","Earth Liberation Front","Eco-anarchism"],"affiliation":["Animal Liberation Front","Earth Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Conspiracy / arson (ELF–ALF eco-sabotage)","convicted":"Yes — guilty plea"}]},
  {"name":"Joyanna Zacher","first_name":"Joyanna","last_name":"Zacher","description":"Earth Liberation Front activist and Operation Backfire (\"Green Scare\") defendant; one of the non-cooperating defendants who refused to inform on co-defendants and served additional prison time for ELF eco-sabotage in the Pacific Northwest (1996–2001).","ideologies":["Earth Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Conspiracy / arson (ELF eco-sabotage)","convicted":"Yes — guilty plea"}]},
  {"name":"Nathan Block","first_name":"Nathan","last_name":"Block","description":"Earth Liberation Front activist and Operation Backfire (\"Green Scare\") defendant; one of the non-cooperating defendants who refused to inform on co-defendants and served additional prison time for ELF eco-sabotage in the Pacific Northwest (1996–2001).","ideologies":["Earth Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Conspiracy / arson (ELF eco-sabotage)","convicted":"Yes — guilty plea"}]},
  {"name":"Rebecca Rubin","first_name":"Rebecca","last_name":"Rubin","description":"Earth Liberation Front / Animal Liberation Front activist and Operation Backfire (\"Green Scare\") defendant. After years as a fugitive she surrendered and was prosecuted; listed among the non-cooperating Green Scare defendants who served prison time for 1990s–2001 eco-sabotage actions.","gender":"Female","ideologies":["Earth Liberation Front","Animal Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front","Animal Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Conspiracy / arson (ELF/ALF eco-sabotage)","convicted":"Yes — guilty plea"}]},
  {"name":"Justin Solondz","first_name":"Justin","last_name":"Solondz","description":"Earth Liberation Front activist and Operation Backfire (\"Green Scare\") defendant. Captured abroad years after the original indictment, he was prosecuted for his role in ELF eco-sabotage including a 2001 arson at a University of Washington horticulture center; listed among the non-cooperating Green Scare defendants.","ideologies":["Earth Liberation Front","Eco-anarchism"],"affiliation":["Earth Liberation Front"],"era":"Green Scare","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"Arson / conspiracy (ELF eco-sabotage, incl. 2001 University of Washington arson)","convicted":"Yes"}]},
  {"name":"Ken Ward","first_name":"Ken","last_name":"Ward","description":"Veteran climate activist from Corbett, Oregon and one of the five \"valve turners\" who on October 11, 2016 simultaneously shut off valves on pipelines carrying Canadian tar sands oil into the U.S. Ward closed the Kinder Morgan / Trans Mountain pipeline near Anacortes, Washington. His first trial ended in a hung jury (Feb 2017); a burglary conviction was reversed on appeal in 2019, and the Washington Supreme Court established a state precedent allowing the climate necessity defense.","state":"Oregon","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Skagit County Superior Court (Mount Vernon, WA)","institution_state":"Washington","charges":"Sabotage and burglary (shutting a Kinder Morgan / Trans Mountain pipeline valve, Oct 11 2016)","arrest_date":"2016-10-11","sentence":"240 hours community service; no jail, no fine (per CLDC reporting)","convicted":"Burglary conviction at retrial, later reversed on appeal (2019)"}]},
  {"name":"Leonard Higgins","first_name":"Leonard","last_name":"Higgins","description":"Retired Oregon state employee (age 65 at sentencing) and one of the five climate \"valve turners\" of October 11, 2016. Higgins cut chains and shut off an Enbridge tar sands pipeline valve in Chouteau County, Montana. Convicted of a felony after the judge denied his climate necessity defense, he was sentenced in March 2018 to a three-year deferred imposition of sentence with no jail time and $3,755 in restitution.","state":"Oregon","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Chouteau County District Court (Fort Benton, MT)","institution_state":"Montana","charges":"Felony criminal mischief (shutting an Enbridge tar sands pipeline valve, Oct 11 2016)","arrest_date":"2016-10-11","sentence":"3-year deferred imposition of sentence; no jail; $3,755 restitution","convicted":"Yes — jury (necessity defense denied), 2017"}]},
  {"name":"Michael Foster","first_name":"Michael","last_name":"Foster","description":"Climate activist and one of the five \"valve turners\" of October 11, 2016, who shut off the TransCanada Keystone pipeline valve in Pembina County, North Dakota. Tried in Cavalier, ND in October 2017 after the judge refused to allow the necessity defense, he was convicted of felony charges and served jail time before being released; his case was on appeal as of 2018.","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Pembina County District Court (Cavalier, ND)","institution_state":"North Dakota","charges":"Felony criminal mischief / conspiracy (shutting the Keystone pipeline valve, Oct 11 2016)","arrest_date":"2016-10-11","convicted":"Yes — jury (necessity defense denied), 2017; served jail time"}]},
  {"name":"Sam Jessup","first_name":"Sam","last_name":"Jessup","description":"Climate activist who filmed and livestreamed Michael Foster shutting the Keystone pipeline valve in North Dakota on October 11, 2016. He was charged with felonies as an accomplice/conspirator and tried alongside Foster in Cavalier, ND in October 2017 after the court refused to allow the climate necessity defense. (Final disposition not stated in the article.)","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Pembina County District Court (Cavalier, ND)","institution_state":"North Dakota","charges":"Felony conspiracy / accomplice charges (filming the Keystone valve-turning action, Oct 11 2016)","arrest_date":"2016-10-11","convicted":"Tried Oct 2017 (necessity defense denied)"}]},
  {"name":"Emily Johnston","first_name":"Emily","last_name":"Johnston","description":"Seattle poet and climate activist, one of the five \"valve turners\" of October 11, 2016, who closed Enbridge tar sands pipeline valves in Clearwater County, Minnesota. Charged with felony criminal damage to critical energy infrastructure, she won the right to present a climate necessity defense at the Minnesota Supreme Court and was acquitted of all charges in October 2018.","state":"Washington","gender":"Female","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Clearwater County District Court","institution_state":"Minnesota","charges":"Felony criminal damage to critical energy infrastructure (closing Enbridge pipeline valves, Oct 11 2016)","arrest_date":"2016-10-11","convicted":"No — acquitted October 2018"}]},
  {"name":"Annette Klapstein","first_name":"Annette","last_name":"Klapstein","description":"Retired attorney and climate activist, one of the five \"valve turners\" of October 11, 2016, who closed Enbridge tar sands pipeline valves in Clearwater County, Minnesota alongside Emily Johnston. Charged with felony criminal damage to critical energy infrastructure, she was acquitted of all charges in October 2018.","gender":"Female","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Clearwater County District Court","institution_state":"Minnesota","charges":"Felony criminal damage to critical energy infrastructure (closing Enbridge pipeline valves, Oct 11 2016)","arrest_date":"2016-10-11","convicted":"No — acquitted October 2018"}]},
  {"name":"Ben Joldersma","first_name":"Ben","last_name":"Joldersma","description":"Climate activist who served as a support person for the Minnesota \"valve turners\" during the October 11, 2016 coordinated pipeline shut-down in Clearwater County, Minnesota. Charged as a co-defendant with Annette Klapstein and Emily Johnston, he was acquitted of all charges in October 2018.","ideologies":["Climate justice","Civil disobedience"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"Clearwater County District Court","institution_state":"Minnesota","charges":"Aiding/abetting criminal damage to critical energy infrastructure (support role, Oct 11 2016)","arrest_date":"2016-10-11","convicted":"No — acquitted October 2018"}]},
  {"name":"Loren Reed","first_name":"Loren","last_name":"Reed","description":"A Dine (Navajo) man and rapper from Page, Arizona, jailed in federal pretrial detention for more than ten months without bail over heated and satirical Facebook posts in a private chat organizing a local police-brutality protest. After an acquaintance reported him and an undercover FBI agent infiltrated the group, he was charged with the federal offense of threatening to damage a building by fire — speech the CLDC argued was First Amendment-protected and never a true threat. (Article predates his 2021 trial; final disposition not stated.)","state":"Arizona","race":"Native American","gender":"Male","ideologies":["Indigenous rights","Free speech","Black Lives Matter solidarity"],"era":"2020 racial justice uprising","in_custody":false,"released":true,"cases":[{"institution_name":"CoreCivic detention center, Florence, Arizona","institution_state":"Arizona","charges":"Threats to damage and destroy a building by means of fire (18 U.S.C.) over Facebook posts about a BLM protest","arrest_date":"2020-06-02","incarceration_date":"2020-06-02"}]},
  {"name":"Eric Jackson","first_name":"Eric","last_name":"Jackson","description":"Houseless-rights activist in Eugene, Oregon, convicted by a jury in March 2021 after being arrested for protesting overnight at the Wayne Morse Free Speech Plaza in violation of a county plaza curfew. Represented by the CLDC, he appealed, arguing the curfew violated the First Amendment and the Oregon Constitution.","state":"Oregon","ideologies":["Houseless rights","Free speech","Anti-poverty"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Lane County Circuit Court (Eugene, OR)","institution_state":"Oregon","charges":"Unlawful overnight protest / plaza curfew violation (Wayne Morse Free Speech Plaza)","convicted":"Yes — jury, March 2021 (on appeal)"}]},
  {"name":"Hedin Brugh","first_name":"Hedin","last_name":"Brugh","description":"Longtime SLEEPS (Safe Legally Entitled Emergency Places to Sleep) activist in Eugene, Oregon who advocated for unhoused people. Arrested by Eugene police for asserting his right to assemble at the Wayne Morse Free Speech Plaza, he was criminally prosecuted by the city for two years before the City Attorney abruptly dismissed the case in July 2015 rather than face an adverse constitutional ruling.","state":"Oregon","ideologies":["Houseless rights","Free speech"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Lane County Circuit Court (Eugene, OR)","institution_state":"Oregon","charges":"Criminal charge arising from protest at the Wayne Morse Free Speech Plaza","convicted":"No — charges dismissed July 2015"}]},
  {"name":"F. Emily Semple","first_name":"Emily","last_name":"Semple","description":"Occupy Eugene activist arrested at the federal plaza in Eugene, Oregon while protesting in 2012. The U.S. Attorney's office voluntarily dismissed her federal criminal case after CLDC argued the GSA had unconstitutionally evicted Occupy from the plaza; she later became a plaintiff in a federal civil-rights suit over protest restrictions and was elected to the Eugene City Council.","state":"Oregon","ideologies":["Occupy movement","Free speech","Economic justice"],"era":"Occupy","in_custody":false,"released":true,"cases":[{"institution_name":"U.S. District Court, Eugene, OR","institution_state":"Oregon","charges":"Federal charge for protesting at the Federal Plaza (Occupy Eugene)","convicted":"No — charges dismissed by U.S. Attorney"}]},
  {"name":"George Sexton","first_name":"George","last_name":"Sexton","description":"Conservation director and forest-defense activist arrested at the Biscuit timber sales in Oregon and prosecuted under ORS 164.886 (\"Interfering with Agricultural Operations\"), a law used against dozens of nonviolent forest defenders. As an appellant represented by the CLDC, he helped win a 2014 Oregon Court of Appeals ruling that struck down the entire statute as unconstitutional. (No standing conviction stated; the law was voided.)","state":"Oregon","ideologies":["Environmental","Forest defense","Free speech"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Oregon Court of Appeals","institution_state":"Oregon","charges":"Interfering with Agricultural Operations (ORS 164.886) — nonviolent protest at the Biscuit timber sales","convicted":"Statute struck down as unconstitutional, 2014"}]},
  {"name":"Nancy Beaulieu","first_name":"Nancy","last_name":"Beaulieu","description":"Anishinaabe (Ojibwe) water protector and organizer charged with criminal trespass for the eight-day Fire Light ceremonial camp at the Mississippi River headwaters in June 2021, opposing Enbridge's Line 3 tar sands pipeline. White Earth Tribal Court dismissed her case in 2022, ruling the action was a lawful exercise of sovereign Indigenous treaty rights.","state":"Minnesota","race":"Native American","gender":"Female","ideologies":["Indigenous rights","Climate justice","Water protection"],"affiliation":["Line 3 resistance"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"White Earth Tribal Court","institution_state":"Minnesota","charges":"Criminal trespass (Fire Light Camp, Line 3 resistance, June 2021)","convicted":"No — dismissed 2022 on Indigenous sovereignty grounds"}]},
  {"name":"Justin Keezer","first_name":"Justin","last_name":"Keezer","description":"Anishinaabe (Ojibwe) water protector charged with criminal trespass for the June 2021 Fire Light ceremonial camp opposing Enbridge's Line 3 tar sands pipeline. White Earth Tribal Court dismissed his case in 2022, holding that Anishinaabe people retain sovereign treaty rights including the right to hold ceremony and protect the water.","state":"Minnesota","race":"Native American","gender":"Male","ideologies":["Indigenous rights","Climate justice","Water protection"],"affiliation":["Line 3 resistance"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"White Earth Tribal Court","institution_state":"Minnesota","charges":"Criminal trespass (Fire Light Camp, Line 3 resistance, June 2021)","convicted":"No — dismissed 2022 on Indigenous sovereignty grounds"}]},
  {"name":"Todd Thompson","first_name":"Todd","last_name":"Thompson","description":"Anishinaabe (Ojibwe) water protector charged with criminal trespass for the June 2021 Fire Light ceremonial camp opposing Enbridge's Line 3 tar sands pipeline. His case was dismissed by White Earth Tribal Court in 2022 on Indigenous-sovereignty and treaty-rights grounds.","state":"Minnesota","race":"Native American","gender":"Male","ideologies":["Indigenous rights","Climate justice","Water protection"],"affiliation":["Line 3 resistance"],"era":"Climate movement","in_custody":false,"released":true,"cases":[{"institution_name":"White Earth Tribal Court","institution_state":"Minnesota","charges":"Criminal trespass (Fire Light Camp, Line 3 resistance, June 2021)","convicted":"No — dismissed 2022 on Indigenous sovereignty grounds"}]},
  {"name":"Tyshawn Ford","first_name":"Tyshawn","last_name":"Ford","description":"Black Unity leader and Lane Community College student arrested at a peaceful Black Lives Matter march through Springfield, Oregon's Thurston Hills neighborhood on July 29, 2020, organized in response to a noose displayed near a Black family's home. Punched in the head by a Springfield officer and arrested, his criminal case was later dismissed and he became a plaintiff in CLDC's civil-rights suit against the police.","state":"Oregon","race":"Black","gender":"Male","ideologies":["Black Lives Matter","Racial justice","Abolition"],"affiliation":["Black Unity"],"era":"2020 racial justice uprising","in_custody":false,"released":true,"cases":[{"institution_name":"Lane County Circuit Court (Springfield, OR)","institution_state":"Oregon","charges":"Protest-related charges from the July 29, 2020 Black Unity march","arrest_date":"2020-07-29","convicted":"No — charges dismissed"}]},
  {"name":"Jazmine Jourdan","first_name":"Jazmine","last_name":"Jourdan","description":"Racial-justice activist and Black Unity leader pushed to the ground and beaten by Springfield, Oregon police at the July 29, 2020 Black Unity march, then charged with assault of an officer, interfering, and felony riot. After two years of prosecution, all charges were dismissed mid-trial in June 2022 — the last of the Springfield BLM criminal cases to end — and she joined CLDC's civil-rights suit against the police.","state":"Oregon","race":"Black","gender":"Female","ideologies":["Black Lives Matter","Racial justice","Abolition"],"affiliation":["Black Unity"],"era":"2020 racial justice uprising","in_custody":false,"released":true,"cases":[{"institution_name":"Lane County Circuit Court (Springfield, OR)","institution_state":"Oregon","charges":"Assault of a public safety officer; interfering with a police officer; felony riot (July 29, 2020 Black Unity march)","arrest_date":"2020-07-29","convicted":"No — all charges dismissed mid-trial June 2022"}]},
  {"name":"Jessica Reznicek","first_name":"Jessica","last_name":"Reznicek","description":"Catholic Worker and climate activist who, with Ruby Montoya, carried out a 2016–2017 campaign of sabotage against the Dakota Access Pipeline in Iowa. She pleaded guilty in 2021 to conspiracy to damage an energy facility and was sentenced to 8 years in federal prison after the court applied a domestic-terrorism enhancement. Named in passing in CLDC climate coverage (facts from public record).","state":"Iowa","gender":"Female","ideologies":["Climate justice","Catholic Worker","Anti-pipeline"],"era":"Climate movement","in_custody":true,"released":false,"cases":[{"institution_name":"U.S. District Court, Southern District of Iowa","institution_state":"Iowa","charges":"Conspiracy to damage an energy facility (Dakota Access Pipeline sabotage, 2016–2017)","sentenced_date":"2021-06-30","sentence":"8 years in federal prison (terrorism enhancement applied)","convicted":"Yes — guilty plea, 2021"}]},
  {"name":"Herman Wallace","first_name":"Herman","last_name":"Wallace","description":"One of the \"Angola 3.\" A Black Panther Party member at the Louisiana State Penitentiary (Angola), he was convicted of the 1972 killing of prison guard Brent Miller and held in solitary confinement for roughly 41 years — among the longest in U.S. history. His conviction was overturned and he was released on October 1, 2013; he died of cancer three days later. Cited in NPPC/CLDC coverage as a political prisoner held until near death (facts from public record).","state":"Louisiana","race":"Black","gender":"Male","ideologies":["Black liberation","Prison abolition"],"affiliation":["Black Panther Party"],"era":"Black liberation","in_custody":false,"released":true,"death_date":"2013-10-04","cases":[{"institution_name":"Louisiana State Penitentiary (Angola)","institution_state":"Louisiana","charges":"Murder of prison guard Brent Miller (1972)","release_date":"2013-10-01","sentence":"Life; held ~41 years in solitary confinement","convicted":"Conviction overturned, 2013"}]},
  {"name":"Marilyn Buck","first_name":"Marilyn","last_name":"Buck","description":"Revolutionary, anti-imperialist, and poet who worked in support of the Black Liberation Army. Convicted for her role in the 1979 prison escape of Assata Shakur and the 1981 Brink's robbery, she was sentenced to 80 years in federal prison. Released on parole in July 2010 after a terminal cancer diagnosis, she died weeks later. Cited in NPPC/CLDC coverage among political prisoners held until near death (facts from public record).","gender":"Female","ideologies":["Anti-imperialist","Black liberation solidarity","Revolutionary"],"affiliation":["Black Liberation Army"],"era":"Black liberation","in_custody":false,"released":true,"death_date":"2010-08-03","cases":[{"institution_name":"FMC Carswell","institution_state":"Texas","charges":"Conspiracy; role in the 1979 liberation of Assata Shakur and the 1981 Brink's robbery","release_date":"2010-07-15","sentence":"80 years (paroled July 2010)","convicted":"Yes"}]}
]
JSON;
    }
}
