<?php

namespace App\Console\Commands;

use App\Models\DashboardLink;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

/**
 * Adds protest-related cases that were initially set aside on the nonviolence
 * bar (allegations of assault, thrown objects, weapons, arson, threats, or
 * doxxing). They are included here at the user's request and stated FACTUALLY
 * and NEUTRALLY: each title gives the actual charge and, where known, the
 * CURRENT disposition (many were dismissed, dropped, or ended in acquittal).
 * Presumption of innocence applies to all pending matters; convictions are
 * stated plainly without valorizing the underlying conduct. In-window
 * (on/after May 7, 2025); sourced from public reporting; matched on URL so the
 * command is idempotent.
 */
class AddFlaggedDashboardCases extends Command {
    protected $signature = 'dashboard:add-flagged-cases';
    protected $description = 'Add violence/threats-flagged protest cases (stated factually, with current dispositions)';

    public function handle(): int {
        $cases = [
            [
                'title'          => 'Three Los Angeles activists were charged with stalking a federal agent for following him home and livestreaming while posting his address; two were convicted of stalking and a third was acquitted',
                'url'            => 'https://ktla.com/news/local-news/2-women-found-guilty-of-stalking-ice-officer-home-in-l-a-livestreaming-pursuit/',
                'source'         => 'KTLA',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-26',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0500,
                'lng'            => -118.2500,
            ],
            [
                'title'          => 'San Diego man Gregory Curcio was arrested on a federal doxxing charge for posting an ICE attorney home address online and urging others to harass her; the case is pending',
                'url'            => 'https://www.ice.gov/news/releases/california-man-accused-doxxing-ice-employee-now-custody',
                'source'         => 'ICE',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-22',
                'location_label' => 'San Diego, CA',
                'lat'            => 32.7157,
                'lng'            => -117.1611,
            ],
            [
                'title'          => 'Eight people were arrested on assault and obstruction charges at an anti-ICE protest at the Henry M. Jackson Federal Building in Seattle, where police cited thrown objects, a dumpster fire, and flag-burning',
                'url'            => 'https://www.fox13seattle.com/news/arrests-seattle-anti-ice-protest',
                'source'         => 'FOX 13 Seattle',
                'category'       => 'arrest',
                'published_at'   => '2025-06-11',
                'location_label' => 'Seattle, WA',
                'lat'            => 47.6046,
                'lng'            => -122.3349,
            ],
            [
                'title'          => 'Thirty-four people were arrested (86 taken into custody) at an anti-ICE protest near 26 Federal Plaza in Manhattan, where police reported bottles and objects thrown',
                'url'            => 'https://www.thecity.nyc/2025/06/10/ice-protests-arrests-nypd-trump-immigration/',
                'source'         => 'THE CITY',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'New York, NY',
                'lat'            => 40.7160,
                'lng'            => -74.0035,
            ],
            [
                'title'          => 'Four people were arrested after a protest against an ICE raid at Glenn Valley Foods in Omaha; one, a US-citizen plant worker, was charged with assaulting officers and breaking a vehicle window with a rock',
                'url'            => 'https://omaha.com/news/local/crime-courts/article_2a0733ed-8b2d-4b4d-b01d-36156d0841c5.html',
                'source'         => 'Omaha World-Herald',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'Omaha, NE',
                'lat'            => 41.2565,
                'lng'            => -95.9345,
            ],
            [
                'title'          => 'About six people were arrested on charges of assaulting officers during multi-night clashes outside the Delaney Hall ICE facility in Newark, where some used umbrellas and trash cans as shields',
                'url'            => 'https://abc7ny.com/post/delaney-hall-protests-6-arrests-protesters-clash-ice-agents-outside-newark-nj/19192526/',
                'source'         => 'ABC7 New York',
                'category'       => 'arrest',
                'published_at'   => '2026-05-27',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7290,
                'lng'            => -74.2095,
            ],
            [
                'title'          => 'Six people were arrested at an anti-ICE protest on Buford Highway in Brookhaven, Georgia on obstruction and unlawful-assembly charges, with one also charged with aggravated assault on an officer',
                'url'            => 'https://www.atlantanewsfirst.com/2025/06/11/brookhaven-police-identify-suspects-arrested-during-anti-ice-protest-buford-highway/',
                'source'         => 'Atlanta News First',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'Brookhaven, GA',
                'lat'            => 33.8651,
                'lng'            => -84.3366,
            ],
            [
                'title'          => 'About 74 people were arrested for failure to disperse at a "No Kings" protest near a downtown Los Angeles federal detention center; DHS said some threw concrete and injured officers',
                'url'            => 'https://abc7.com/post/no-kings-protest-los-angeles-2026-police-say-9-juveniles-arrested-officers-suffered-minor-during-saturdays-rally-downtown/18801910/',
                'source'         => 'ABC7 Los Angeles',
                'category'       => 'arrest',
                'published_at'   => '2026-03-28',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0440,
                'lng'            => -118.2400,
            ],
            [
                'title'          => 'Five Quakertown, Pennsylvania high-school students were charged after an anti-ICE walkout; the most serious felony assault counts were later dismissed or reduced',
                'url'            => 'https://www.nbcphiladelphia.com/news/local/most-serious-charges-axed-for-2nd-teen-involved-in-quakertown-anti-ice-protest/4380878/',
                'source'         => 'NBC Philadelphia',
                'category'       => 'prosecution',
                'published_at'   => '2026-02-20',
                'location_label' => 'Quakertown, PA',
                'lat'            => 40.4418,
                'lng'            => -75.3413,
            ],
            [
                'title'          => 'Detroit man Roman Gomez-Ocadiz was federally charged with impeding officers for using his truck to block an ICE vehicle during an arrest; he was released on bond pending the case',
                'url'            => 'https://www.detroitnews.com/story/news/local/detroit-city/2025/07/01/feds-charge-protester-accused-of-interferring-with-detroit-ice-arrest/84432260007/',
                'source'         => 'The Detroit News',
                'category'       => 'arrest',
                'published_at'   => '2025-06-30',
                'location_label' => 'Detroit, MI',
                'lat'            => 42.3690,
                'lng'            => -83.1530,
            ],
            [
                'title'          => 'Virginia Beach woman Jessica Pinsky was charged with disorderly conduct for kicking a "Trump Train" pickup at a "No Kings" rally; the case is pending',
                'url'            => 'https://www.wtkr.com/news/in-the-community/virginia-beach/woman-arrested-at-vb-no-kings-rally-in-town-center-for-disorderly-conduct',
                'source'         => 'WTKR',
                'category'       => 'arrest',
                'published_at'   => '2026-03-28',
                'location_label' => 'Virginia Beach, VA',
                'lat'            => 36.8420,
                'lng'            => -76.1370,
            ],
            [
                'title'          => 'Chicago teacher Marimar Martinez was shot five times by a Border Patrol agent and charged with ramming his vehicle; prosecutors later dropped the charges after conceding the account was contradicted',
                'url'            => 'https://www.cnn.com/2025/11/20/us/chicago-marimar-martinez-shooting-charges',
                'source'         => 'CNN',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-04',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8230,
                'lng'            => -87.7050,
            ],
            [
                'title'          => 'Conservative journalist Nick Sortor was arrested on a disorderly-conduct charge at the Portland ICE-facility protests; the district attorney dropped it, finding he appeared to have acted in self-defense',
                'url'            => 'https://www.cnn.com/2025/10/03/us/portland-ice-facility-nick-sortor-arrest',
                'source'         => 'CNN',
                'category'       => 'arrest',
                'published_at'   => '2025-10-02',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4985,
                'lng'            => -122.6715,
            ],
            [
                'title'          => 'Nine people were convicted on terrorism-related charges over a July 4, 2025 ambush at the Prairieland ICE detention center in Alvarado, Texas, in which an officer was shot; others pleaded guilty earlier',
                'url'            => 'https://www.cnn.com/2026/03/13/us/immigration-detention-center-shooting',
                'source'         => 'CNN',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Alvarado, TX',
                'lat'            => 32.4060,
                'lng'            => -97.2120,
            ],
            [
                'title'          => 'A "No Kings" event safety volunteer, Matthew Alder, was charged with manslaughter after fatally shooting bystander Arthur Ah Loo while firing at a man with a rifle at the Salt Lake City march; the case is pending',
                'url'            => 'https://www.nbcnews.com/news/us-news/safety-volunteer-charged-manslaughter-shooting-salt-lake-city-no-kings-rcna247333',
                'source'         => 'NBC News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-14',
                'location_label' => 'Salt Lake City, UT',
                'lat'            => 40.7608,
                'lng'            => -111.8910,
            ],
            [
                'title'          => 'Trenten Barker was sentenced to 18 months in federal prison after pleading guilty to arson for igniting a fire at the Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-pleads-guilty-arson-immigration-and-customs-enforcement-building',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-11',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4980,
                'lng'            => -122.6710,
            ],
            [
                'title'          => 'A pro-Palestinian protester arrested at the Elbit Systems weapons plant in Ladson, South Carolina was acquitted of charges that he damaged an employee vehicle with a flagpole',
                'url'            => 'https://fightbacknews.org/articles/charleston-pro-palestine-organizer-wins-not-guilty-verdict',
                'source'         => 'Fight Back News',
                'category'       => 'prosecution',
                'published_at'   => '2025-08-07',
                'location_label' => 'Ladson, SC',
                'lat'            => 32.9857,
                'lng'            => -80.1098,
            ],
            [
                'title'          => 'Two of the nine Spokane ICE-protest defendants, Bobbi Silva and Mikki Hatfield, were charged with assaulting officers; under plea deals they pleaded guilty to conspiracy and the assault charges are set to be dismissed',
                'url'            => 'https://www.spokesman.com/stories/2025/dec/09/five-of-nine-spokane-ice-protesters-have-pleaded-g/',
                'source'         => 'The Spokesman-Review',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-11',
                'location_label' => 'Spokane, WA',
                'lat'            => 47.6635,
                'lng'            => -117.4280,
            ],
            [
                'title'          => 'Portland protester Robert Hoopes pleaded guilty to aggravated assault of a federal officer for throwing a rock that struck an ICE officer in the eye during a protest at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-pleads-guilty-assaulting-federal-law-enforcement-officer',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-14',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4975,
                'lng'            => -122.6700,
            ],
            [
                'title'          => 'Portland protester Riley Freeman was charged with assaulting a federal officer with a dangerous weapon and possessing an unregistered destructive device, accused of throwing an incendiary device at officers at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4985,
                'lng'            => -122.6720,
            ],
            [
                'title'          => 'Two anti-ICE protesters, Erin Escobar and Nick Gutierrez, were indicted on charges of assaulting a federal officer outside the Roybal Federal Building in Los Angeles',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/grand-jury-returns-4-count-indictment-charging-two-defendants-assaulting-federal',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-08-07',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0530,
                'lng'            => -118.2430,
            ],
            [
                'title'          => 'Chicago man Diego Reyes was indicted on a charge of assaulting an ICE officer with his SUV during an Operation Midway Blitz protest in Brighton Park',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/federal-grand-jury-chicago-returns-indictment-against-operation-midway-blitz-defendant',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-20',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8230,
                'lng'            => -87.7060,
            ],
            [
                'title'          => 'Brooklyn man Nicholas Scelfo was charged with threatening to assault and murder an ICE officer and his family after a confrontation at the Delaney Hall facility in Newark',
                'url'            => 'https://www.justice.gov/opa/pr/brooklyn-man-charged-threatening-assault-and-murder-ice-officer-and-his-family',
                'source'         => 'U.S. Department of Justice',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-30',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7295,
                'lng'            => -74.2100,
            ],
            [
                'title'          => 'Two men, Frank Waszut and Anthony Noto, were indicted for transmitting online threats to injure an ICE deportation officer and his wife',
                'url'            => 'https://www.justice.gov/usao-ndga/pr/social-media-provocateurs-charged-threatening-harm-federal-agent-and-his-wife',
                'source'         => 'U.S. Attorney (N.D. Ga.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-23',
                'location_label' => 'Atlanta, GA',
                'lat'            => 33.7490,
                'lng'            => -84.3880,
            ],
            [
                'title'          => 'Skiatook, Oklahoma man Logan Murfin was convicted by a federal jury on ten counts of threatening to assault and murder federal agents in posts on X targeting ICE officers',
                'url'            => 'https://www.justice.gov/usao-ndok/pr/skiatook-man-found-guilty-federal-jury-threatening-kill-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Okla.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-24',
                'location_label' => 'Skiatook, OK',
                'lat'            => 36.3690,
                'lng'            => -96.0070,
            ],
            [
                'title'          => 'Independent photographer Shane Bollman was indicted on a felony civil-rights conspiracy and a FACE Act charge over his coverage of an anti-ICE protest at a St. Paul church; press-freedom groups called for the charges to be dropped',
                'url'            => 'https://cpj.org/2026/03/independent-photographer-among-30-more-arrested-charged-in-connection-with-minnesota-ice-protest-following-lemon-and-fort-cases/',
                'source'         => 'CPJ',
                'category'       => 'prosecution',
                'published_at'   => '2026-02-26',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.9537,
                'lng'            => -93.0900,
            ],
            // ---- Press Freedom Tracker (journalists) ----
            [
                'title'          => 'New York Post photographer Toby Canham was shot in the forehead with a rubber bullet by a California Highway Patrol officer while filming an immigration protest in Los Angeles',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photographer-shot-in-forehead-with-rubber-bullet-while-covering-la-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0600,
                'lng'            => -118.2360,
            ],
            [
                'title'          => 'Los Angeles Daily News reporter Ryanne Mena was shot in the head with a munition and suffered a concussion while covering anti-deportation protests; she later sued DHS',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/reporter-struck-in-head-with-munition-by-federal-officers-at-la-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-06-07',
                'location_label' => 'Compton, CA',
                'lat'            => 33.8958,
                'lng'            => -118.2201,
            ],
            [
                'title'          => 'Chicago Reader journalist Shawn Mulcahy was shot with a crowd-control munition by federal officers while filming outside the Broadview ICE facility',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/chicago-journalist-shot-with-crowd-control-munition-by-federal-officers/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-09-26',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8538,
                'lng'            => -87.8558,
            ],
            [
                'title'          => 'Cincinnati CityBeat journalist Madeline Fening was arrested and charged with felony rioting and other counts while covering an anti-deportation protest; the felony was later dropped',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/cincinnati-photojournalist-arrested-as-protest-spills-across-bridge-to-kentucky/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-17',
                'location_label' => 'Cincinnati, OH',
                'lat'            => 39.0950,
                'lng'            => -84.5110,
            ],
            [
                'title'          => 'Independent photojournalist Avery Craig was slammed against a wall, arrested, and charged with obstruction while documenting immigration protests in New York; the charge was dropped',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photojournalist-slammed-against-wall-arrested-amid-nyc-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2025-11-29',
                'location_label' => 'New York, NY',
                'lat'            => 40.7140,
                'lng'            => -74.0020,
            ],
            [
                'title'          => 'Independent photographer John Abernathy was tackled, pepper-sprayed, and cited by federal officers while documenting a protest at the Whipple Federal Building near Minneapolis',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photographer-arrested-pepper-sprayed-and-tear-gassed-by-federal-officers/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2026-01-15',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.8930,
                'lng'            => -93.1990,
            ],
            [
                'title'          => 'Independent photojournalist Nick Stern was jabbed with police batons and arrested at a Los Angeles May Day protest, then released without charges',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photojournalist-arrested-at-la-protest-after-being-prodded-with-police-batons/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2026-05-01',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0490,
                'lng'            => -118.2480,
            ],
            // ---- Portland ICE facility (D. Oregon) ----
            [
                'title'          => 'Portland protester Katherine Vogel was charged with assaulting a federal officer, accused of punching an officer in the jaw at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-woman-charged-assaulting-federal-law-enforcement-officer-near-local-ice-office',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-30',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4968,
                'lng'            => -122.6705,
            ],
            [
                'title'          => 'Portland protester Alexander Boyce was charged with felony assault of a federal officer, accused of spitting on an officer at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-charged-felony-assault-federal-law-enforcement-officer-near-local-ice',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-05',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4990,
                'lng'            => -122.6695,
            ],
            [
                'title'          => 'Aziel Chambers was charged with assaulting a federal officer and other offenses, accused of pointing a laser at an officer at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/three-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-24',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4972,
                'lng'            => -122.6718,
            ],
            [
                'title'          => 'Portland protester Ian McCarthy was charged with assaulting a federal officer and destruction of property, accused of cutting a fiber-optic cable with bolt cutters and kicking and punching officers at the South Portland ICE facility on July 4, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4983,
                'lng'            => -122.6713,
            ],
            [
                'title'          => 'Portland protester Andrew Marcum was charged with assaulting a federal officer, accused of tripping and kicking an officer chasing a tagger at the South Portland ICE facility on July 4, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4985,
                'lng'            => -122.6709,
            ],
            [
                'title'          => 'Portland protester Jeremy Hummel was charged with misdemeanor depredation of government property for spray-painting the South Portland ICE building on July 4, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4980,
                'lng'            => -122.6716,
            ],
            [
                'title'          => 'Portland protester Samuel Berry was charged with misdemeanor assault of a federal officer and failure to comply during a June 18, 2025 protest at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/six-defendants-charge-assaulting-federal-offices-other-offenses-during-protests-near',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-18',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4977,
                'lng'            => -122.6723,
            ],
            [
                'title'          => 'Protester Juniper Weed was charged with misdemeanor assault of a federal officer and failure to comply during a June 18, 2025 protest at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/six-defendants-charge-assaulting-federal-offices-other-offenses-during-protests-near',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-18',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4979,
                'lng'            => -122.6720,
            ],
            [
                'title'          => 'Protester Edwardo Diaz Guardado was charged with misdemeanor assault of a federal officer, accused of pointing a high-powered laser at an officer eye at the South Portland ICE facility on June 18, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/six-defendants-charge-assaulting-federal-offices-other-offenses-during-protests-near',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-18',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4976,
                'lng'            => -122.6725,
            ],
            [
                'title'          => 'Protester Liam Houpis was charged with creating a hazard on federal property, accused of drilling screws into plywood to trap officers inside the South Portland ICE facility on June 18, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/six-defendants-charge-assaulting-federal-offices-other-offenses-during-protests-near',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-18',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4981,
                'lng'            => -122.6718,
            ],
            // ---- Los Angeles area (C.D. California) ----
            [
                'title'          => 'Compton man Elpidio Reyna pleaded guilty to assaulting a federal officer for throwing concrete at and injuring an officer during the June 2025 Paramount immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/compton-man-pleads-guilty-assaulting-and-injuring-federal-officer-during-anti',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-07',
                'location_label' => 'Paramount, CA',
                'lat'            => 33.8895,
                'lng'            => -118.1598,
            ],
            [
                'title'          => 'Paramount man Emiliano Garduno Galvez was charged with possessing an unregistered destructive device, accused of throwing a Molotov cocktail toward deputies during the June 2025 immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/federal-complaints-charge-socal-residents-assault-throwing-molotov-cocktails-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-07',
                'location_label' => 'Paramount, CA',
                'lat'            => 33.8902,
                'lng'            => -118.1605,
            ],
            [
                'title'          => 'Long Beach man Wrackkie Quiogue was charged with possessing an unregistered destructive device, accused of carrying a Molotov cocktail during the June 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/federal-complaints-charge-socal-residents-assault-throwing-molotov-cocktails-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0540,
                'lng'            => -118.2450,
            ],
            [
                'title'          => 'Boyle Heights man Yovany Canil was charged with assaulting a federal officer, accused of pepper-spraying into a vehicle carrying FBI SWAT members during the June 2025 Los Angeles protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-06',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0420,
                'lng'            => -118.2360,
            ],
            [
                'title'          => 'Adam Palermo pleaded guilty to felony assault with a dangerous weapon for throwing projectiles at California Highway Patrol officers trapped under a freeway overpass during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0512,
                'lng'            => -118.2438,
            ],
            [
                'title'          => 'Ismael Vega pleaded guilty to felony civil disorder for throwing projectiles at California Highway Patrol officers during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0514,
                'lng'            => -118.2442,
            ],
            [
                'title'          => 'Yachua Flores pleaded guilty to felony civil disorder for throwing projectiles at California Highway Patrol officers during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0508,
                'lng'            => -118.2444,
            ],
            [
                'title'          => 'Balton Montion pleaded guilty to felony civil disorder for throwing projectiles at California Highway Patrol officers during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0516,
                'lng'            => -118.2436,
            ],
            [
                'title'          => 'Junior Roldan pleaded guilty to misdemeanor simple assault on a person assisting a federal officer during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0506,
                'lng'            => -118.2446,
            ],
            [
                'title'          => 'Ronald Coreas pleaded guilty to misdemeanor simple assault on a person assisting a federal officer during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0518,
                'lng'            => -118.2434,
            ],
            [
                'title'          => 'Christian Garcia was charged with misdemeanor assault on a federal officer, accused of throwing objects at officers during a June 9, 2025 immigration protest outside the HSI office in Santa Ana',
                'url'            => 'https://www.cbsnews.com/losangeles/news/los-angeles-santa-ana-protests-charges-molotov-cocktails/',
                'source'         => 'CBS News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-09',
                'location_label' => 'Santa Ana, CA',
                'lat'            => 33.7454,
                'lng'            => -117.8678,
            ],
            [
                'title'          => 'Rene Luna was charged with misdemeanor assault on a federal officer, accused of throwing water bottles and cans at officers during a June 9, 2025 immigration protest outside the HSI office in Santa Ana',
                'url'            => 'https://www.cbsnews.com/losangeles/news/los-angeles-santa-ana-protests-charges-molotov-cocktails/',
                'source'         => 'CBS News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-09',
                'location_label' => 'Santa Ana, CA',
                'lat'            => 33.7456,
                'lng'            => -117.8675,
            ],
            [
                'title'          => 'Oxnard man Isai Carrillo was charged with conspiracy to impede federal officers, accused of throwing rocks at government vehicles during the July 2025 Glass House cannabis-farm immigration raid',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-10',
                'location_label' => 'Camarillo, CA',
                'lat'            => 34.2164,
                'lng'            => -119.0376,
            ],
            // ---- Chicago area (N.D. Illinois) ----
            [
                'title'          => 'Ray Collins was charged with felony assault of a federal officer at the Broadview ICE facility; a grand jury returned a no bill and the complaint was dismissed',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8546,
                'lng'            => -87.8549,
            ],
            [
                'title'          => 'Jocelyne Robledo was charged with felony assault of a federal officer at the Broadview ICE facility; a grand jury returned a no bill and the complaint was dismissed',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8544,
                'lng'            => -87.8551,
            ],
            [
                'title'          => 'Paul Ivery was charged with felony assault of a federal officer at the Broadview ICE facility, accused of grabbing an agent helmet',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8548,
                'lng'            => -87.8547,
            ],
            [
                'title'          => 'Dana Briggs, a 70-year-old Air Force veteran, was charged with felony assault of a federal officer at the Broadview ICE facility',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8542,
                'lng'            => -87.8553,
            ],
            [
                'title'          => 'Hubert Mazur was charged with misdemeanor resisting a federal officer at the Broadview ICE facility; the charge was later dropped',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8549,
                'lng'            => -87.8545,
            ],
            [
                'title'          => 'Widman Lopez Funes was charged with felony assault of a federal officer and destruction of property, accused of striking an ICE vehicle during Operation Midway Blitz near Chicago',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/three-individuals-charged-federal-court-chicago-using-their-vehicles-impede-and',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-01',
                'location_label' => 'Bensenville, IL',
                'lat'            => 41.9550,
                'lng'            => -87.9400,
            ],
            [
                'title'          => 'Miguel Escareno De Loera was charged with felony assault of a federal officer, accused of striking an ICE vehicle during Operation Midway Blitz near Chicago',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/three-individuals-charged-federal-court-chicago-using-their-vehicles-impede-and',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-02',
                'location_label' => 'Woodridge, IL',
                'lat'            => 41.7470,
                'lng'            => -88.0270,
            ],
            [
                'title'          => 'Joel Gonzalez was charged with misdemeanor impeding a federal officer, accused of rear-ending a CBP vehicle during Operation Midway Blitz in Chicago',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/three-individuals-charged-federal-court-chicago-using-their-vehicles-impede-and',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-02',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8252,
                'lng'            => -87.7042,
            ],
            [
                'title'          => 'Anthony Ruiz was charged with impeding a federal officer, accused of using his vehicle against a CBP vehicle in Chicago; the charges were later dropped',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/federal-complaint-charges-two-individuals-using-their-vehicles-assault-impede-and',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-05',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8230,
                'lng'            => -87.7048,
            ],
            [
                'title'          => 'Lyons, Illinois man Anthony Gonzalez Alvarez pleaded guilty to misprision of a felony, admitting he rammed a federal agents vehicle during Operation Midway Blitz — the first guilty plea of the Chicago operation',
                'url'            => 'https://www.cbsnews.com/chicago/news/man-admits-ramming-federal-agents-chicago/',
                'source'         => 'CBS News Chicago',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-03',
                'location_label' => 'Lyons, IL',
                'lat'            => 41.8136,
                'lng'            => -87.8178,
            ],
            // ---- Newark / Delaney Hall (D. New Jersey) ----
            [
                'title'          => 'New Jersey man Brendan Geier was charged with assaulting federal officers, accused of kicking and biting ICE deportation officers during crowd-control at the Delaney Hall facility in Newark',
                'url'            => 'https://www.justice.gov/usao-nj/pr/morris-county-man-arrested-kicking-and-biting-ice-deportation-officers',
                'source'         => 'U.S. Attorney (D.N.J.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-28',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7288,
                'lng'            => -74.2098,
            ],
            // ---- Long-tail: Portland (D. Oregon) ----
            [
                'title'          => 'Portland protester Julie Winters pleaded guilty to intimidating a federal officer, accused of waving and throwing knives at officers at the South Portland ICE facility on June 24, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/three-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-24',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4974,
                'lng'            => -122.6707,
            ],
            [
                'title'          => 'Portland protester Rachel Pope was charged with misdemeanor assault of a federal officer, accused of throwing a metal canister that hit an officer at the South Portland ICE facility on June 24, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/three-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-24',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4986,
                'lng'            => -122.6702,
            ],
            // ---- Long-tail: downtown LA June 8 civil-disorder complaint (C.D. Cal.) ----
            [
                'title'          => 'Elmore Cage was charged with felony civil disorder for impeding officers during the June 8, 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0522,
                'lng'            => -118.2428,
            ],
            [
                'title'          => 'Hector Ramos was charged with felony civil disorder for impeding officers during the June 8, 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0524,
                'lng'            => -118.2432,
            ],
            [
                'title'          => 'Stefano Green was charged with felony civil disorder for impeding officers during the June 8, 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0519,
                'lng'            => -118.2425,
            ],
            [
                'title'          => 'Jesus Hernandez was charged with felony civil disorder for impeding officers during the June 8, 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0526,
                'lng'            => -118.2436,
            ],
            // ---- Long-tail: Newark / Delaney Hall (state charges + detainee escapes) ----
            [
                'title'          => 'Thomas Clemens was charged by New Jersey with aggravated assault on an officer, rioting, and obstruction during the Delaney Hall ICE-facility protests in Newark',
                'url'            => 'https://patch.com/new-jersey/newarknj/arrests-continue-delaney-hall-after-ice-drawdown-they-re-slowing-down-nj-mayor',
                'source'         => 'Patch',
                'category'       => 'prosecution',
                'published_at'   => '2026-06-03',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7283,
                'lng'            => -74.2102,
            ],
            [
                'title'          => 'Aida Riddle was charged by New Jersey with aggravated assault on an officer, rioting, and obstruction during the Delaney Hall ICE-facility protests in Newark',
                'url'            => 'https://patch.com/new-jersey/newarknj/arrests-continue-delaney-hall-after-ice-drawdown-they-re-slowing-down-nj-mayor',
                'source'         => 'Patch',
                'category'       => 'prosecution',
                'published_at'   => '2026-06-03',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7286,
                'lng'            => -74.2104,
            ],
            [
                'title'          => 'Samuel Becker was charged by New Jersey with rioting, disorderly conduct, and criminal mischief over a dumpster fire during the Delaney Hall ICE-facility protests in Newark',
                'url'            => 'https://patch.com/new-jersey/newarknj/arrests-continue-delaney-hall-after-ice-drawdown-they-re-slowing-down-nj-mayor',
                'source'         => 'Patch',
                'category'       => 'prosecution',
                'published_at'   => '2026-06-03',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7290,
                'lng'            => -74.2106,
            ],
            [
                'title'          => 'Four ICE detainees — Franklin Bautista Reyes, Joan Castaneda Lozada, Andres Pineda Mogollon, and Joel Sandoval-Lopez — were charged with escaping from the Delaney Hall facility in Newark during a June 2025 uprising over detention conditions',
                'url'            => 'https://www.justice.gov/usao-nj/pr/four-ice-detainees-charged-escaping-detention-facility-delaney-hall-newark',
                'source'         => 'U.S. Attorney (D.N.J.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-12',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7284,
                'lng'            => -74.2090,
            ],
            // ---- Counter-protesters (opposite valence; labeled as such) ----
            [
                'title'          => 'A counter-protester was arrested for disorderly conduct at the "No Kings" rally in Hot Springs, Arkansas',
                'url'            => 'https://www.hotsr.com/news/2025/jun/15/watch-hot-springs-no-kings-rally-draws-500/',
                'source'         => 'Hot Springs Sentinel Record',
                'category'       => 'arrest',
                'published_at'   => '2025-06-14',
                'location_label' => 'Hot Springs, AR',
                'lat'            => 34.5037,
                'lng'            => -93.0552,
            ],
            [
                'title'          => 'A tractor-trailer driver was charged with disorderly conduct after driving toward "No Kings" protesters in Bozeman, Montana and getting out with a hammer',
                'url'            => 'https://www.kbzk.com/news/local-news/man-arrested-by-bozeman-police-during-no-kings-protest',
                'source'         => 'KBZK',
                'category'       => 'arrest',
                'published_at'   => '2025-06-14',
                'location_label' => 'Bozeman, MT',
                'lat'            => 45.6796,
                'lng'            => -111.0448,
            ],
            // ---- Brooklyn hospital ICE clash ----
            [
                'title'          => 'Eight people were charged by the NYPD after a clash outside Wyckoff Heights Medical Center in Brooklyn, where about 200 gathered after ICE detained a man and took him to the hospital; charges ranged from resisting arrest to criminal mischief',
                'url'            => 'https://gothamist.com/news/nyc-officials-criticize-ice-after-clash-outside-brooklyn-hospital-leads-to-8-arrests',
                'source'         => 'Gothamist',
                'category'       => 'arrest',
                'published_at'   => '2026-05-02',
                'location_label' => 'Brooklyn, NY',
                'lat'            => 40.7029,
                'lng'            => -73.9120,
            ],
            // ---- Minneapolis "Operation Metro Surge" protest defendants (D. Minn.) ----
            [
                'title'          => 'Christina Rank was charged with assaulting a federal officer, accused of a vehicle collision with ICE agents during the January 2026 Operation Metro Surge protests in the Twin Cities',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-16',
                'location_label' => 'Inver Grove Heights, MN',
                'lat'            => 44.8480,
                'lng'            => -93.0426,
            ],
            [
                'title'          => 'Madeline Tschida was charged with assaulting a federal officer, accused of kicking a transport-vehicle door into an officer during the January 2026 Operation Metro Surge protests in Minnesota',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-16',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9712,
                'lng'            => -93.2588,
            ],
            [
                'title'          => 'Quentin Williams was charged with assaulting a federal officer, accused of shoving and grabbing officers near Roosevelt High School during the January 2026 Operation Metro Surge in Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-07',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9228,
                'lng'            => -93.2480,
            ],
            [
                'title'          => 'Nitzana Flores was charged with assaulting a federal officer, accused of colliding with Border Patrol agents near Roosevelt High School during the January 2026 Operation Metro Surge in Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-07',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9232,
                'lng'            => -93.2476,
            ],
            [
                'title'          => 'Gillian Etherington was charged with assaulting a federal officer during the January 2026 Operation Metro Surge in Minneapolis; a federal judge later called the supporting affidavit perplexing and false',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-07',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9236,
                'lng'            => -93.2472,
            ],
            [
                'title'          => 'Helicity Borowska was charged with assaulting a federal officer, accused of spitting on officers at the Whipple Federal Building during the January 2026 Operation Metro Surge near Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-16',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.8932,
                'lng'            => -93.1992,
            ],
            [
                'title'          => 'William Vermie was charged with assaulting a federal officer, accused of striking an officer on Park Avenue during the January 2026 Operation Metro Surge in Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-13',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9588,
                'lng'            => -93.2620,
            ],
            [
                'title'          => 'Paul Johnson was charged with assaulting a federal officer, accused of approaching Border Patrol agents with a baseball bat and pepper spray during the January 2026 Operation Metro Surge in Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-22',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9760,
                'lng'            => -93.2650,
            ],
            [
                'title'          => 'Joshua Doyle was charged with assaulting a federal officer, accused of kicking an agent near Dupont and Colfax during the January 2026 Operation Metro Surge in Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-21',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9540,
                'lng'            => -93.2940,
            ],
            [
                'title'          => 'Nasra Ahmed was charged with assaulting a federal officer, accused of throwing an egg and spitting at officers during the January 2026 Operation Metro Surge in St. Paul',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-14',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.9498,
                'lng'            => -93.0937,
            ],
            [
                'title'          => 'Matrim Charlebois was charged with assaulting a federal officer, accused of swinging a metal cane at an officer at the Whipple Federal Building during the January 2026 Operation Metro Surge near Minneapolis',
                'url'            => 'https://www.justice.gov/usao-mn/pr/sixteen-defendants-charged-violently-assaulting-federal-officers-and-property',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-13',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.8928,
                'lng'            => -93.1988,
            ],
            // ---- Ostroushko trio (St. Paul, anti-ICE protest) ----
            [
                'title'          => 'Christopher Ostroushko was charged with assault and interfering with a federally protected activity for surrounding and shoving a Turning Point USA journalist at an anti-ICE protest outside the Whipple Federal Building near St. Paul',
                'url'            => 'https://www.justice.gov/usao-mn/pr/three-individuals-federally-charged-assault-and-intimidating-turning-point-usa',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-11',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.8930,
                'lng'            => -93.1996,
            ],
            [
                'title'          => 'Deyanna Ostroushko was charged with assault for surrounding and shoving a Turning Point USA journalist at an anti-ICE protest outside the Whipple Federal Building near St. Paul',
                'url'            => 'https://www.justice.gov/usao-mn/pr/three-individuals-federally-charged-assault-and-intimidating-turning-point-usa',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-11',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.8934,
                'lng'            => -93.1990,
            ],
            [
                'title'          => 'Paige Ostroushko was charged with assault and interfering with a federally protected activity for shoving a Turning Point USA journalist at an anti-ICE protest outside the Whipple Federal Building near St. Paul',
                'url'            => 'https://www.justice.gov/usao-mn/pr/three-individuals-federally-charged-assault-and-intimidating-turning-point-usa',
                'source'         => 'U.S. Attorney (D. Minn.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-11',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.8926,
                'lng'            => -93.2002,
            ],
            // ---- Minneapolis assault charges dismissed as false ----
            [
                'title'          => 'Alfredo Aljorna was charged with assaulting an ICE officer in Minneapolis; the charges were dismissed with prejudice after city camera footage was found materially inconsistent with the allegations',
                'url'            => 'https://www.pbs.org/newshour/politics/prosecutors-to-dismiss-charges-against-men-accused-of-assaulting-ice-officer-in-minneapolis',
                'source'         => 'PBS NewsHour',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-14',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9482,
                'lng'            => -93.2670,
            ],
            [
                'title'          => 'Julio Cesar Sosa-Celis, who was shot through a door by an ICE officer, was charged with assault in Minneapolis; the charges were dismissed with prejudice after video contradicted the allegations',
                'url'            => 'https://www.pbs.org/newshour/politics/prosecutors-to-dismiss-charges-against-men-accused-of-assaulting-ice-officer-in-minneapolis',
                'source'         => 'PBS NewsHour',
                'category'       => 'prosecution',
                'published_at'   => '2026-01-14',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.9486,
                'lng'            => -93.2666,
            ],
        ];

        $created = 0;
        foreach ($cases as $case) {
            // Several individuals can share one press-release URL (a single
            // complaint naming multiple defendants), so match on url+title to
            // keep each named person distinct while staying idempotent.
            $link = DashboardLink::firstOrCreate(
                ['url' => $case['url'], 'title' => $case['title']],
                array_merge($case, ['published_at' => Carbon::parse($case['published_at'])]),
            );

            if ($link->wasRecentlyCreated) {
                $created++;
                $this->info("Added: {$case['title']}");
            } else {
                $this->line("Skipped (already present): {$case['title']}");
            }
        }

        $this->info("Done. {$created} new case(s) added; ".(count($cases) - $created).' already present.');

        return self::SUCCESS;
    }
}
