<?php

namespace App\Console\Commands;

use App\Models\DashboardLink;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

/**
 * Adds protest-related cases that were initially set aside on the nonviolence
 * bar (allegations of assault, thrown objects, weapons, arson, threats, or
 * doxxing). They are included here at the user's request and stated FACTUALLY
 * and NEUTRALLY: each title gives the actual charge and, where known, the
 * CURRENT disposition (many were dismissed, dropped, or ended in acquittal).
 * Presumption of innocence applies to all pending matters; convictions are
 * stated plainly without valorizing the underlying conduct. In-window
 * (on/after May 7, 2025); sourced from public reporting; matched on URL so the
 * command is idempotent.
 */
class AddFlaggedDashboardCases extends Command {
    protected $signature = 'dashboard:add-flagged-cases';
    protected $description = 'Add violence/threats-flagged protest cases (stated factually, with current dispositions)';

    public function handle(): int {
        $cases = [
            [
                'title'          => 'Three Los Angeles activists were charged with stalking a federal agent for following him home and livestreaming while posting his address; two were convicted of stalking and a third was acquitted',
                'url'            => 'https://ktla.com/news/local-news/2-women-found-guilty-of-stalking-ice-officer-home-in-l-a-livestreaming-pursuit/',
                'source'         => 'KTLA',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-26',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0500,
                'lng'            => -118.2500,
            ],
            [
                'title'          => 'San Diego man Gregory Curcio was arrested on a federal doxxing charge for posting an ICE attorney home address online and urging others to harass her; the case is pending',
                'url'            => 'https://www.ice.gov/news/releases/california-man-accused-doxxing-ice-employee-now-custody',
                'source'         => 'ICE',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-22',
                'location_label' => 'San Diego, CA',
                'lat'            => 32.7157,
                'lng'            => -117.1611,
            ],
            [
                'title'          => 'Eight people were arrested on assault and obstruction charges at an anti-ICE protest at the Henry M. Jackson Federal Building in Seattle, where police cited thrown objects, a dumpster fire, and flag-burning',
                'url'            => 'https://www.fox13seattle.com/news/arrests-seattle-anti-ice-protest',
                'source'         => 'FOX 13 Seattle',
                'category'       => 'arrest',
                'published_at'   => '2025-06-11',
                'location_label' => 'Seattle, WA',
                'lat'            => 47.6046,
                'lng'            => -122.3349,
            ],
            [
                'title'          => 'Thirty-four people were arrested (86 taken into custody) at an anti-ICE protest near 26 Federal Plaza in Manhattan, where police reported bottles and objects thrown',
                'url'            => 'https://www.thecity.nyc/2025/06/10/ice-protests-arrests-nypd-trump-immigration/',
                'source'         => 'THE CITY',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'New York, NY',
                'lat'            => 40.7160,
                'lng'            => -74.0035,
            ],
            [
                'title'          => 'Four people were arrested after a protest against an ICE raid at Glenn Valley Foods in Omaha; one, a US-citizen plant worker, was charged with assaulting officers and breaking a vehicle window with a rock',
                'url'            => 'https://omaha.com/news/local/crime-courts/article_2a0733ed-8b2d-4b4d-b01d-36156d0841c5.html',
                'source'         => 'Omaha World-Herald',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'Omaha, NE',
                'lat'            => 41.2565,
                'lng'            => -95.9345,
            ],
            [
                'title'          => 'About six people were arrested on charges of assaulting officers during multi-night clashes outside the Delaney Hall ICE facility in Newark, where some used umbrellas and trash cans as shields',
                'url'            => 'https://abc7ny.com/post/delaney-hall-protests-6-arrests-protesters-clash-ice-agents-outside-newark-nj/19192526/',
                'source'         => 'ABC7 New York',
                'category'       => 'arrest',
                'published_at'   => '2026-05-27',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7290,
                'lng'            => -74.2095,
            ],
            [
                'title'          => 'Six people were arrested at an anti-ICE protest on Buford Highway in Brookhaven, Georgia on obstruction and unlawful-assembly charges, with one also charged with aggravated assault on an officer',
                'url'            => 'https://www.atlantanewsfirst.com/2025/06/11/brookhaven-police-identify-suspects-arrested-during-anti-ice-protest-buford-highway/',
                'source'         => 'Atlanta News First',
                'category'       => 'arrest',
                'published_at'   => '2025-06-10',
                'location_label' => 'Brookhaven, GA',
                'lat'            => 33.8651,
                'lng'            => -84.3366,
            ],
            [
                'title'          => 'About 74 people were arrested for failure to disperse at a "No Kings" protest near a downtown Los Angeles federal detention center; DHS said some threw concrete and injured officers',
                'url'            => 'https://abc7.com/post/no-kings-protest-los-angeles-2026-police-say-9-juveniles-arrested-officers-suffered-minor-during-saturdays-rally-downtown/18801910/',
                'source'         => 'ABC7 Los Angeles',
                'category'       => 'arrest',
                'published_at'   => '2026-03-28',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0440,
                'lng'            => -118.2400,
            ],
            [
                'title'          => 'Five Quakertown, Pennsylvania high-school students were charged after an anti-ICE walkout; the most serious felony assault counts were later dismissed or reduced',
                'url'            => 'https://www.nbcphiladelphia.com/news/local/most-serious-charges-axed-for-2nd-teen-involved-in-quakertown-anti-ice-protest/4380878/',
                'source'         => 'NBC Philadelphia',
                'category'       => 'prosecution',
                'published_at'   => '2026-02-20',
                'location_label' => 'Quakertown, PA',
                'lat'            => 40.4418,
                'lng'            => -75.3413,
            ],
            [
                'title'          => 'Detroit man Roman Gomez-Ocadiz was federally charged with impeding officers for using his truck to block an ICE vehicle during an arrest; he was released on bond pending the case',
                'url'            => 'https://www.detroitnews.com/story/news/local/detroit-city/2025/07/01/feds-charge-protester-accused-of-interferring-with-detroit-ice-arrest/84432260007/',
                'source'         => 'The Detroit News',
                'category'       => 'arrest',
                'published_at'   => '2025-06-30',
                'location_label' => 'Detroit, MI',
                'lat'            => 42.3690,
                'lng'            => -83.1530,
            ],
            [
                'title'          => 'Virginia Beach woman Jessica Pinsky was charged with disorderly conduct for kicking a "Trump Train" pickup at a "No Kings" rally; the case is pending',
                'url'            => 'https://www.wtkr.com/news/in-the-community/virginia-beach/woman-arrested-at-vb-no-kings-rally-in-town-center-for-disorderly-conduct',
                'source'         => 'WTKR',
                'category'       => 'arrest',
                'published_at'   => '2026-03-28',
                'location_label' => 'Virginia Beach, VA',
                'lat'            => 36.8420,
                'lng'            => -76.1370,
            ],
            [
                'title'          => 'Chicago teacher Marimar Martinez was shot five times by a Border Patrol agent and charged with ramming his vehicle; prosecutors later dropped the charges after conceding the account was contradicted',
                'url'            => 'https://www.cnn.com/2025/11/20/us/chicago-marimar-martinez-shooting-charges',
                'source'         => 'CNN',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-04',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8230,
                'lng'            => -87.7050,
            ],
            [
                'title'          => 'Conservative journalist Nick Sortor was arrested on a disorderly-conduct charge at the Portland ICE-facility protests; the district attorney dropped it, finding he appeared to have acted in self-defense',
                'url'            => 'https://www.cnn.com/2025/10/03/us/portland-ice-facility-nick-sortor-arrest',
                'source'         => 'CNN',
                'category'       => 'arrest',
                'published_at'   => '2025-10-02',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4985,
                'lng'            => -122.6715,
            ],
            [
                'title'          => 'Nine people were convicted on terrorism-related charges over a July 4, 2025 ambush at the Prairieland ICE detention center in Alvarado, Texas, in which an officer was shot; others pleaded guilty earlier',
                'url'            => 'https://www.cnn.com/2026/03/13/us/immigration-detention-center-shooting',
                'source'         => 'CNN',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Alvarado, TX',
                'lat'            => 32.4060,
                'lng'            => -97.2120,
            ],
            [
                'title'          => 'A "No Kings" event safety volunteer, Matthew Alder, was charged with manslaughter after fatally shooting bystander Arthur Ah Loo while firing at a man with a rifle at the Salt Lake City march; the case is pending',
                'url'            => 'https://www.nbcnews.com/news/us-news/safety-volunteer-charged-manslaughter-shooting-salt-lake-city-no-kings-rcna247333',
                'source'         => 'NBC News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-14',
                'location_label' => 'Salt Lake City, UT',
                'lat'            => 40.7608,
                'lng'            => -111.8910,
            ],
            [
                'title'          => 'Trenten Barker was sentenced to 18 months in federal prison after pleading guilty to arson for igniting a fire at the Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-pleads-guilty-arson-immigration-and-customs-enforcement-building',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-11',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4980,
                'lng'            => -122.6710,
            ],
            [
                'title'          => 'A pro-Palestinian protester arrested at the Elbit Systems weapons plant in Ladson, South Carolina was acquitted of charges that he damaged an employee vehicle with a flagpole',
                'url'            => 'https://fightbacknews.org/articles/charleston-pro-palestine-organizer-wins-not-guilty-verdict',
                'source'         => 'Fight Back News',
                'category'       => 'prosecution',
                'published_at'   => '2025-08-07',
                'location_label' => 'Ladson, SC',
                'lat'            => 32.9857,
                'lng'            => -80.1098,
            ],
            [
                'title'          => 'Two of the nine Spokane ICE-protest defendants, Bobbi Silva and Mikki Hatfield, were charged with assaulting officers; under plea deals they pleaded guilty to conspiracy and the assault charges are set to be dismissed',
                'url'            => 'https://www.spokesman.com/stories/2025/dec/09/five-of-nine-spokane-ice-protesters-have-pleaded-g/',
                'source'         => 'The Spokesman-Review',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-11',
                'location_label' => 'Spokane, WA',
                'lat'            => 47.6635,
                'lng'            => -117.4280,
            ],
            [
                'title'          => 'Portland protester Robert Hoopes pleaded guilty to aggravated assault of a federal officer for throwing a rock that struck an ICE officer in the eye during a protest at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-pleads-guilty-assaulting-federal-law-enforcement-officer',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-14',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4975,
                'lng'            => -122.6700,
            ],
            [
                'title'          => 'Portland protester Riley Freeman was charged with assaulting a federal officer with a dangerous weapon and possessing an unregistered destructive device, accused of throwing an incendiary device at officers at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4985,
                'lng'            => -122.6720,
            ],
            [
                'title'          => 'Two anti-ICE protesters, Erin Escobar and Nick Gutierrez, were indicted on charges of assaulting a federal officer outside the Roybal Federal Building in Los Angeles',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/grand-jury-returns-4-count-indictment-charging-two-defendants-assaulting-federal',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-08-07',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0530,
                'lng'            => -118.2430,
            ],
            [
                'title'          => 'Chicago man Diego Reyes was indicted on a charge of assaulting an ICE officer with his SUV during an Operation Midway Blitz protest in Brighton Park',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/federal-grand-jury-chicago-returns-indictment-against-operation-midway-blitz-defendant',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-20',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8230,
                'lng'            => -87.7060,
            ],
            [
                'title'          => 'Brooklyn man Nicholas Scelfo was charged with threatening to assault and murder an ICE officer and his family after a confrontation at the Delaney Hall facility in Newark',
                'url'            => 'https://www.justice.gov/opa/pr/brooklyn-man-charged-threatening-assault-and-murder-ice-officer-and-his-family',
                'source'         => 'U.S. Department of Justice',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-30',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7295,
                'lng'            => -74.2100,
            ],
            [
                'title'          => 'Two men, Frank Waszut and Anthony Noto, were indicted for transmitting online threats to injure an ICE deportation officer and his wife',
                'url'            => 'https://www.justice.gov/usao-ndga/pr/social-media-provocateurs-charged-threatening-harm-federal-agent-and-his-wife',
                'source'         => 'U.S. Attorney (N.D. Ga.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-23',
                'location_label' => 'Atlanta, GA',
                'lat'            => 33.7490,
                'lng'            => -84.3880,
            ],
            [
                'title'          => 'Skiatook, Oklahoma man Logan Murfin was convicted by a federal jury on ten counts of threatening to assault and murder federal agents in posts on X targeting ICE officers',
                'url'            => 'https://www.justice.gov/usao-ndok/pr/skiatook-man-found-guilty-federal-jury-threatening-kill-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Okla.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-24',
                'location_label' => 'Skiatook, OK',
                'lat'            => 36.3690,
                'lng'            => -96.0070,
            ],
            [
                'title'          => 'Independent photographer Shane Bollman was indicted on a felony civil-rights conspiracy and a FACE Act charge over his coverage of an anti-ICE protest at a St. Paul church; press-freedom groups called for the charges to be dropped',
                'url'            => 'https://cpj.org/2026/03/independent-photographer-among-30-more-arrested-charged-in-connection-with-minnesota-ice-protest-following-lemon-and-fort-cases/',
                'source'         => 'CPJ',
                'category'       => 'prosecution',
                'published_at'   => '2026-02-26',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.9537,
                'lng'            => -93.0900,
            ],
            // ---- Press Freedom Tracker (journalists) ----
            [
                'title'          => 'New York Post photographer Toby Canham was shot in the forehead with a rubber bullet by a California Highway Patrol officer while filming an immigration protest in Los Angeles',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photographer-shot-in-forehead-with-rubber-bullet-while-covering-la-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0600,
                'lng'            => -118.2360,
            ],
            [
                'title'          => 'Los Angeles Daily News reporter Ryanne Mena was shot in the head with a munition and suffered a concussion while covering anti-deportation protests; she later sued DHS',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/reporter-struck-in-head-with-munition-by-federal-officers-at-la-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-06-07',
                'location_label' => 'Compton, CA',
                'lat'            => 33.8958,
                'lng'            => -118.2201,
            ],
            [
                'title'          => 'Chicago Reader journalist Shawn Mulcahy was shot with a crowd-control munition by federal officers while filming outside the Broadview ICE facility',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/chicago-journalist-shot-with-crowd-control-munition-by-federal-officers/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'other',
                'published_at'   => '2025-09-26',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8538,
                'lng'            => -87.8558,
            ],
            [
                'title'          => 'Cincinnati CityBeat journalist Madeline Fening was arrested and charged with felony rioting and other counts while covering an anti-deportation protest; the felony was later dropped',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/cincinnati-photojournalist-arrested-as-protest-spills-across-bridge-to-kentucky/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-17',
                'location_label' => 'Cincinnati, OH',
                'lat'            => 39.0950,
                'lng'            => -84.5110,
            ],
            [
                'title'          => 'Independent photojournalist Avery Craig was slammed against a wall, arrested, and charged with obstruction while documenting immigration protests in New York; the charge was dropped',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photojournalist-slammed-against-wall-arrested-amid-nyc-protest/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2025-11-29',
                'location_label' => 'New York, NY',
                'lat'            => 40.7140,
                'lng'            => -74.0020,
            ],
            [
                'title'          => 'Independent photographer John Abernathy was tackled, pepper-sprayed, and cited by federal officers while documenting a protest at the Whipple Federal Building near Minneapolis',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photographer-arrested-pepper-sprayed-and-tear-gassed-by-federal-officers/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2026-01-15',
                'location_label' => 'Minneapolis, MN',
                'lat'            => 44.8930,
                'lng'            => -93.1990,
            ],
            [
                'title'          => 'Independent photojournalist Nick Stern was jabbed with police batons and arrested at a Los Angeles May Day protest, then released without charges',
                'url'            => 'https://pressfreedomtracker.us/all-incidents/photojournalist-arrested-at-la-protest-after-being-prodded-with-police-batons/',
                'source'         => 'U.S. Press Freedom Tracker',
                'category'       => 'arrest',
                'published_at'   => '2026-05-01',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0490,
                'lng'            => -118.2480,
            ],
            // ---- Portland ICE facility (D. Oregon) ----
            [
                'title'          => 'Portland protester Katherine Vogel was charged with assaulting a federal officer, accused of punching an officer in the jaw at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-woman-charged-assaulting-federal-law-enforcement-officer-near-local-ice-office',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-30',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4968,
                'lng'            => -122.6705,
            ],
            [
                'title'          => 'Portland protester Alexander Boyce was charged with felony assault of a federal officer, accused of spitting on an officer at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/portland-man-charged-felony-assault-federal-law-enforcement-officer-near-local-ice',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-05',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4990,
                'lng'            => -122.6695,
            ],
            [
                'title'          => 'Aziel Chambers was charged with assaulting a federal officer and other offenses, accused of pointing a laser at an officer at the South Portland ICE facility',
                'url'            => 'https://www.justice.gov/usao-or/pr/three-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-17',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4972,
                'lng'            => -122.6718,
            ],
            [
                'title'          => 'Three more protesters — Ian McCarthy, Andrew Marcum, and Jeremy Hummel — were charged with assaulting federal officers or damaging property at the South Portland ICE facility on July 4, 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/four-defendants-charged-assaulting-federal-law-enforcement-officers-other-offenses',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-04',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4982,
                'lng'            => -122.6712,
            ],
            [
                'title'          => 'Six protesters, including Samuel Berry, Juniper Weed, Edwardo Diaz Guardado, and Liam Houpis, were charged with assaulting federal officers and other offenses at the South Portland ICE facility in mid-June 2025',
                'url'            => 'https://www.justice.gov/usao-or/pr/six-defendants-charge-assaulting-federal-offices-other-offenses-during-protests-near',
                'source'         => 'U.S. Attorney (D. Oregon)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-18',
                'location_label' => 'Portland, OR',
                'lat'            => 45.4978,
                'lng'            => -122.6722,
            ],
            // ---- Los Angeles area (C.D. California) ----
            [
                'title'          => 'Compton man Elpidio Reyna pleaded guilty to assaulting a federal officer for throwing concrete at and injuring an officer during the June 2025 Paramount immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/compton-man-pleads-guilty-assaulting-and-injuring-federal-officer-during-anti',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-07',
                'location_label' => 'Paramount, CA',
                'lat'            => 33.8895,
                'lng'            => -118.1598,
            ],
            [
                'title'          => 'Paramount man Emiliano Garduno Galvez was charged with possessing an unregistered destructive device, accused of throwing a Molotov cocktail toward deputies during the June 2025 immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/federal-complaints-charge-socal-residents-assault-throwing-molotov-cocktails-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-07',
                'location_label' => 'Paramount, CA',
                'lat'            => 33.8902,
                'lng'            => -118.1605,
            ],
            [
                'title'          => 'Long Beach man Wrackkie Quiogue was charged with possessing an unregistered destructive device, accused of carrying a Molotov cocktail during the June 2025 downtown Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/federal-complaints-charge-socal-residents-assault-throwing-molotov-cocktails-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0540,
                'lng'            => -118.2450,
            ],
            [
                'title'          => 'Boyle Heights man Yovany Canil was charged with assaulting a federal officer, accused of pepper-spraying into a vehicle carrying FBI SWAT members during the June 2025 Los Angeles protests',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-06',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0420,
                'lng'            => -118.2360,
            ],
            [
                'title'          => 'Six men, including Ismael Vega, Balton Montion, and Ronald Coreas, pleaded guilty to felony civil disorder for throwing projectiles at California Highway Patrol officers during the June 8, 2025 Los Angeles immigration protests',
                'url'            => 'https://www.justice.gov/usao-cdca/pr/six-california-men-plead-guilty-federal-charges-stemming-violence-against-chp-officers',
                'source'         => 'U.S. Attorney (C.D. Cal.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-08',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0510,
                'lng'            => -118.2440,
            ],
            [
                'title'          => 'Two men, Christian Garcia and Rene Luna, were charged with misdemeanor assault for throwing objects at officers during a June 2025 immigration protest outside the HSI office in Santa Ana',
                'url'            => 'https://www.cbsnews.com/losangeles/news/los-angeles-santa-ana-protests-charges-molotov-cocktails/',
                'source'         => 'CBS News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-09',
                'location_label' => 'Santa Ana, CA',
                'lat'            => 33.7455,
                'lng'            => -117.8677,
            ],
            [
                'title'          => 'Oxnard man Isai Carrillo was charged with conspiracy to impede federal officers, accused of throwing rocks at government vehicles during the July 2025 Glass House cannabis-farm immigration raid',
                'url'            => 'https://kesq.com/news/california/2025/10/29/dozen-defendants-charged-with-impeding-ice-operations-in-la/',
                'source'         => 'KESQ',
                'category'       => 'prosecution',
                'published_at'   => '2025-07-10',
                'location_label' => 'Camarillo, CA',
                'lat'            => 34.2164,
                'lng'            => -119.0376,
            ],
            // ---- Chicago area (N.D. Illinois) ----
            [
                'title'          => 'Five people — including Ray Collins, Jocelyne Robledo, Paul Ivery, and 70-year-old Air Force veteran Dana Briggs — were charged with assaulting or resisting federal agents at the Broadview ICE facility; the Collins and Robledo felonies were later no-billed and dismissed',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/five-individuals-charged-federal-court-chicago-assaulting-or-resisting-federal-agents',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-09-27',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8545,
                'lng'            => -87.8550,
            ],
            [
                'title'          => 'Several Operation Midway Blitz protesters — including Widman Lopez Funes, Miguel Escareno De Loera, and Anthony Ruiz — were charged with using vehicles against federal agents near Chicago; the charges against Ruiz were later dropped',
                'url'            => 'https://www.justice.gov/usao-ndil/pr/three-individuals-charged-federal-court-chicago-using-their-vehicles-impede-and',
                'source'         => 'U.S. Attorney (N.D. Ill.)',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-02',
                'location_label' => 'Chicago, IL',
                'lat'            => 41.8250,
                'lng'            => -87.7040,
            ],
            [
                'title'          => 'Lyons, Illinois man Anthony Gonzalez Alvarez pleaded guilty to misprision of a felony, admitting he rammed a federal agents vehicle during Operation Midway Blitz — the first guilty plea of the Chicago operation',
                'url'            => 'https://www.cbsnews.com/chicago/news/man-admits-ramming-federal-agents-chicago/',
                'source'         => 'CBS News Chicago',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-03',
                'location_label' => 'Lyons, IL',
                'lat'            => 41.8136,
                'lng'            => -87.8178,
            ],
            // ---- Newark / Delaney Hall (D. New Jersey) ----
            [
                'title'          => 'New Jersey man Brendan Geier was charged with assaulting federal officers, accused of kicking and biting ICE deportation officers during crowd-control at the Delaney Hall facility in Newark',
                'url'            => 'https://www.justice.gov/usao-nj/pr/morris-county-man-arrested-kicking-and-biting-ice-deportation-officers',
                'source'         => 'U.S. Attorney (D.N.J.)',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-28',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7288,
                'lng'            => -74.2098,
            ],
        ];

        $created = 0;
        foreach ($cases as $case) {
            $link = DashboardLink::firstOrCreate(
                ['url' => $case['url']],
                array_merge($case, ['published_at' => Carbon::parse($case['published_at'])]),
            );

            if ($link->wasRecentlyCreated) {
                $created++;
                $this->info("Added: {$case['title']}");
            } else {
                $this->line("Skipped (already present): {$case['title']}");
            }
        }

        $this->info("Done. {$created} new case(s) added; ".(count($cases) - $created).' already present.');

        return self::SUCCESS;
    }
}
