<?php

namespace App\Console\Commands;

use App\Models\ArchiveRecord;
use Illuminate\Console\Command;

/**
 * Register 32 archive records surfaced by the archive.org fulltext sweep
 * for "Prairie Fire Organizing Committee" — the source documents behind
 * the Breakthrough prisoner-sweep (#490) that aren't yet in the archive.
 *
 * Each record is sourced directly from archive.org (file field points to
 * the IA item URL or the canonical PDF download URL). Self-hosting can be
 * done in a follow-up pass.
 *
 * Idempotent — re-runs update by slug.
 */
final class AddPfocAdjacentArchive extends Command
{
    protected $signature = 'archive:add-pfoc-adjacent';
    protected $description = 'Add 32 archive.org PFOC-adjacent records (movement publications, government docs, books)';

    public function handle(): int
    {
        $records = [
            // ─── Government / investigative documents ───
            [
                'slug' => 'senate-bicentennial-threats-hearing-1976',
                'title' => 'Threats to the Peaceful Observance of the Bicentennial — Senate Subcommittee Hearing, June 18, 1976',
                'description' => "Hearing before the Senate Subcommittee to Investigate the Administration of the Internal Security Act and Other Internal Security Laws (the 'Eastland Subcommittee') of the Committee on the Judiciary, 94th Congress, 2nd Session. One of the most extensive government documents on the Weather Underground Organization and the newly above-ground Prairie Fire Organizing Committee, treating both as a continuing 'internal security' threat to the 1976 Bicentennial. Includes the subcommittee staff's narrative of PFOC's 1974 emergence from the WUO's Prairie Fire manifesto.",
                'record_type' => 'document',
                'source_format' => 'government_hearing',
                'file' => 'https://archive.org/details/threatstopeacefu00unit',
                'collection' => 'U.S. Senate Internal Security Subcommittee',
                'authors' => 'U.S. Senate Committee on the Judiciary, Subcommittee to Investigate the Administration of the Internal Security Act',
                'publisher' => 'U.S. Government Printing Office',
                'year' => 1976,
                'date' => '1976-06-18',
                'subjects' => ['Weather Underground', 'Prairie Fire Organizing Committee', 'PFOC', 'Senate Internal Security Subcommittee', 'Eastland Subcommittee', 'Bicentennial', 'COINTELPRO Successor'],
            ],
            [
                'slug' => 'senate-erosion-law-enforcement-intelligence-1978',
                'title' => 'Erosion of Law Enforcement Intelligence and its Impact on the Public Security — Senate Hearings, 1978',
                'description' => "1978 Senate Subcommittee hearings (95th Congress) lamenting the post-Church Committee curtailment of FBI domestic intelligence. PFOC, the Weather Underground, the FALN, and the BLA are repeatedly cited as the threats the committee believed the FBI was no longer monitoring adequately. A key document for understanding the political backlash that fed the FBI's renewed 1980s counter-intelligence push.",
                'record_type' => 'document',
                'source_format' => 'government_hearing',
                'file' => 'https://archive.org/details/erosionoflawenfo00unit',
                'collection' => 'U.S. Senate Internal Security Subcommittee',
                'authors' => 'U.S. Senate Committee on the Judiciary, Subcommittee to Investigate the Administration of the Internal Security Act',
                'publisher' => 'U.S. Government Printing Office',
                'year' => 1978,
                'date' => '1978-01-01',
                'subjects' => ['FBI', 'Domestic Intelligence', 'Church Committee Aftermath', 'Prairie Fire Organizing Committee', 'PFOC', 'FALN', 'Weather Underground'],
            ],
            [
                'slug' => 'senate-erosion-law-enforcement-intelligence-1977',
                'title' => 'The Erosion of Law Enforcement Intelligence and its Impact on the Public Security — Senate Hearings (Part 4), 1977',
                'description' => "Earlier (1977) volume of the same Senate Subcommittee hearings on the post-Church Committee retrenchment of FBI domestic intelligence. Discusses PFOC, the Weather Underground, and the broader 'radical left' as targets the FBI no longer had clear authority to investigate.",
                'record_type' => 'document',
                'source_format' => 'government_hearing',
                'file' => 'https://archive.org/details/erosionoflawenfo04unit',
                'collection' => 'U.S. Senate Internal Security Subcommittee',
                'authors' => 'U.S. Senate Committee on the Judiciary, Subcommittee to Investigate the Administration of the Internal Security Act',
                'publisher' => 'U.S. Government Printing Office',
                'year' => 1977,
                'date' => '1977-01-01',
                'subjects' => ['FBI', 'Domestic Intelligence', 'Church Committee Aftermath', 'Prairie Fire Organizing Committee', 'PFOC'],
            ],
            [
                'slug' => 'fbi-file-clayton-van-lydegraf',
                'title' => 'Clayton Van Lydegraf — FBI File',
                'description' => "FBI file on Clayton Van Lydegraf (1915–1992), the veteran Communist Party USA member turned Weather Underground / PFOC theorist who was the political mentor of the post-1976 PFOC. Arrested in November 1977 as part of the 'LA 5' on conspiracy/explosives charges. The file documents decades of FBI surveillance from the Smith Act era through the Weather Underground period.",
                'record_type' => 'document',
                'source_format' => 'fbi_file',
                'file' => 'https://archive.org/details/clayton-van-lydegraf',
                'collection' => 'FBI Files',
                'authors' => 'Federal Bureau of Investigation',
                'publisher' => 'Federal Bureau of Investigation',
                'subjects' => ['FBI File', 'Clayton Van Lydegraf', 'Prairie Fire Organizing Committee', 'PFOC', 'Weather Underground', 'LA 5'],
            ],
            [
                'slug' => 'fbi-file-gerald-doeden-gino-perente',
                'title' => 'FBI File on Gerald William Doeden (aka Gino Perente)',
                'description' => "FBI file on Gerald William Doeden, better known by his nom-de-guerre Gino Perente, founder of the National Labor Federation (NATLFED) and its associated cadre formation the Communist Party USA (Provisional). PFOC and NATLFED were contemporaneous post-New-Left cadre formations operating in some of the same milieus; the file's references to PFOC are part of FBI assessments of the broader post-1970s 'New Communist Movement.'",
                'record_type' => 'document',
                'source_format' => 'fbi_file',
                'file' => 'https://archive.org/details/FBI_file_100_459234',
                'collection' => 'FBI Files',
                'authors' => 'Federal Bureau of Investigation',
                'publisher' => 'Federal Bureau of Investigation',
                'subjects' => ['FBI File', 'Gino Perente', 'NATLFED', 'Communist Party USA Provisional', 'New Communist Movement'],
            ],

            // ─── Puerto Rican independence movement publications ───
            [
                'slug' => 'la-patria-radical-april-may-1992',
                'title' => 'La Patria Radical — April/May 1992 (Vol. 4 No. 9/10)',
                'description' => "Issue of *La Patria Radical*, the bulletin of the Movimiento de Liberación Nacional (MLN) — the U.S.-based above-ground Puerto Rican independence organization in close political alignment with PFOC throughout the 1970s–90s. Carries POW updates from the Macheteros and FALN prisoners, movement news, and analysis of the Puerto Rican plebiscite debate.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/la-patria-radical-april-may-1992',
                'collection' => 'Movimiento de Liberación Nacional — La Patria Radical',
                'authors' => 'Movimiento de Liberación Nacional (MLN)',
                'publisher' => 'Movimiento de Liberación Nacional',
                'year' => 1992,
                'date' => '1992-04-01',
                'volume' => 'Vol. 4 No. 9/10',
                'subjects' => ['Puerto Rican Independence', 'MLN', 'Movimiento de Liberación Nacional', 'FALN', 'Macheteros', 'Political Prisoners'],
            ],
            [
                'slug' => 'la-patria-radical-august-1989',
                'title' => 'La Patria Radical — August 1989 (Vol. 2 No. 1)',
                'description' => "Issue of *La Patria Radical*, the bulletin of the Movimiento de Liberación Nacional (MLN). Carries movement news and POW updates from the Puerto Rican independentista prisoners then concentrated at FCI Lexington's High Security Unit and other federal facilities.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/la-patria-radical-vol-2-no-1-august-1989-compresse',
                'collection' => 'Movimiento de Liberación Nacional — La Patria Radical',
                'authors' => 'Movimiento de Liberación Nacional (MLN)',
                'publisher' => 'Movimiento de Liberación Nacional',
                'year' => 1989,
                'date' => '1989-08-01',
                'volume' => 'Vol. 2 No. 1',
                'subjects' => ['Puerto Rican Independence', 'MLN', 'FALN', 'Political Prisoners'],
            ],
            [
                'slug' => 'libertad-may-1985',
                'title' => 'Libertad — May 1985',
                'description' => "Issue of *Libertad*, the newspaper of the National Committee to Free Puerto Rican Prisoners of War (NCFPRPOW). The principal English/Spanish-language publication of the U.S. solidarity movement with the FALN/Macheteros POWs from the late 1970s through the late 1990s. Closely aligned politically with PFOC and the MLN.",
                'record_type' => 'newspaper',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/libertad-may-1985',
                'collection' => 'National Committee to Free Puerto Rican POWs — Libertad',
                'authors' => 'National Committee to Free Puerto Rican Prisoners of War',
                'publisher' => 'National Committee to Free Puerto Rican Prisoners of War',
                'year' => 1985,
                'date' => '1985-05-01',
                'subjects' => ['Puerto Rican Independence', 'FALN', 'Political Prisoners', 'POW Solidarity'],
            ],
            [
                'slug' => 'libertad-july-august-1987',
                'title' => 'Libertad — July/August 1987 (No. 8)',
                'description' => "Issue 8 of *Libertad*, the newspaper of the National Committee to Free Puerto Rican Prisoners of War. Coverage from the period of the Hartford 13 / Wells Fargo trial of the Macheteros and the parallel federal prosecution of the FALN POWs.",
                'record_type' => 'newspaper',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/libertad-july-august-1987',
                'collection' => 'National Committee to Free Puerto Rican POWs — Libertad',
                'authors' => 'National Committee to Free Puerto Rican Prisoners of War',
                'publisher' => 'National Committee to Free Puerto Rican Prisoners of War',
                'year' => 1987,
                'date' => '1987-07-01',
                'subjects' => ['Puerto Rican Independence', 'FALN', 'Macheteros', 'Hartford 13', 'Political Prisoners'],
            ],
            [
                'slug' => 'libertad-update-january-1986',
                'title' => 'Libertad Update — January 25, 1986',
                'description' => "Local bulletin of the National Committee to Free Puerto Rican Prisoners of War, dated January 25, 1986 — written in the immediate aftermath of the August 1985 Hartford 13 / Wells Fargo arrests of the Macheteros leadership and the parallel sweep of the FALN POWs.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/libertad-update-january-251986',
                'collection' => 'National Committee to Free Puerto Rican POWs — Libertad',
                'authors' => 'National Committee to Free Puerto Rican Prisoners of War',
                'publisher' => 'National Committee to Free Puerto Rican Prisoners of War',
                'year' => 1986,
                'date' => '1986-01-25',
                'subjects' => ['Puerto Rican Independence', 'Macheteros', 'Hartford 13', 'FALN', 'Political Prisoners'],
            ],
            [
                'slug' => 'libertad-no-7-may-1985-alt',
                'title' => 'Libertad — No. 7 (May 1985) — alternate scan',
                'description' => "Alternate Internet Archive scan of *Libertad* No. 7, May 1985 — the newspaper of the National Committee to Free Puerto Rican Prisoners of War.",
                'record_type' => 'newspaper',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/Libertad_7_May1985_3325',
                'collection' => 'National Committee to Free Puerto Rican POWs — Libertad',
                'authors' => 'National Committee to Free Puerto Rican Prisoners of War',
                'publisher' => 'National Committee to Free Puerto Rican Prisoners of War',
                'year' => 1985,
                'date' => '1985-05-01',
                'subjects' => ['Puerto Rican Independence', 'FALN', 'Political Prisoners'],
            ],
            [
                'slug' => 'libertad-no-8-july-august-1987-alt',
                'title' => 'Libertad — No. 8 (July/August 1987) — alternate scan',
                'description' => "Alternate Internet Archive scan of *Libertad* No. 8, July/August 1987 — the newspaper of the National Committee to Free Puerto Rican Prisoners of War.",
                'record_type' => 'newspaper',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/Libertad_8_July-August1987_6597',
                'collection' => 'National Committee to Free Puerto Rican POWs — Libertad',
                'authors' => 'National Committee to Free Puerto Rican Prisoners of War',
                'publisher' => 'National Committee to Free Puerto Rican Prisoners of War',
                'year' => 1987,
                'date' => '1987-07-01',
                'subjects' => ['Puerto Rican Independence', 'FALN', 'Political Prisoners'],
            ],

            // ─── Movement publications / periodicals ───
            [
                'slug' => 'wimmin-prisoners-survival-network-no-2-winter-1988',
                'title' => 'Wimmin Prisoners Survival Network — No. 2, Winter 1988',
                'description' => "Second issue of the Wimmin Prisoners Survival Network newsletter — one of the most consistent late-1980s vehicles for women prisoner-of-war and political-prisoner support work, in close political alignment with PFOC's prisoner-support tradition and the Lexington High Security Unit campaign.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/wimmin-prisoners-survival-network-issue-2-winter-8',
                'collection' => 'Wimmin Prisoners Survival Network',
                'publisher' => 'Wimmin Prisoners Survival Network',
                'year' => 1988,
                'date' => '1988-01-01',
                'subjects' => ['Women Political Prisoners', 'Lexington HSU', 'Prisoner Support', 'Feminist Prisoner Solidarity'],
            ],
            [
                'slug' => 'urgent-tasks-no-1-1977',
                'title' => 'Urgent Tasks — Issue 1, May 1977',
                'description' => "Inaugural issue of *Urgent Tasks*, the theoretical journal of the Sojourner Truth Organization (STO) — the Chicago-based independent Marxist-Leninist cadre group founded by Noel Ignatiev, Don Hamerquist, and others. STO operated in the same milieu as PFOC through the 1970s and engaged in substantive (and sometimes sharp) polemics with PFOC over questions of white-skin privilege and 'whiteness' as a political category.",
                'record_type' => 'journal',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/urgent-tasks-issue-1-1977_202203',
                'collection' => 'Sojourner Truth Organization — Urgent Tasks',
                'authors' => 'Sojourner Truth Organization (STO)',
                'publisher' => 'Sojourner Truth Organization',
                'year' => 1977,
                'date' => '1977-05-01',
                'volume' => 'No. 1',
                'subjects' => ['Sojourner Truth Organization', 'STO', 'Noel Ignatiev', 'Don Hamerquist', 'Whiteness', 'New Communist Movement'],
            ],
            [
                'slug' => 'love-and-rage-vol-4-no-1-feb-march-1993',
                'title' => 'Love and Rage — Vol. 4 No. 1, February/March 1993',
                'description' => "Issue of *Love and Rage*, the newspaper of the Love and Rage Revolutionary Anarchist Federation — one of the principal 1990s North American anti-authoritarian formations that picked up parts of the PFOC tradition of anti-imperialist solidarity work with national liberation movements and political-prisoner support.",
                'record_type' => 'newspaper',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/love-and-ragevol-4-no-1-february-march-1993',
                'collection' => 'Love and Rage Revolutionary Anarchist Federation',
                'publisher' => 'Love and Rage Revolutionary Anarchist Federation',
                'year' => 1993,
                'date' => '1993-02-01',
                'volume' => 'Vol. 4 No. 1',
                'subjects' => ['Love and Rage', 'Anarchism', 'Political Prisoners', 'Anti-Imperialism'],
            ],
            [
                'slug' => 'planted-by-the-waters-fall-1995',
                'title' => 'Planted by the Waters — Fall 1995',
                'description' => "Issue of *Planted by the Waters*, a mid-1990s political-prisoner support publication. Carries PP/POW updates from the same constellation Breakthrough covered in its concurrent issues.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/planted-by-the-waters_fall-1995_0',
                'collection' => 'Planted by the Waters',
                'publisher' => 'Planted by the Waters',
                'year' => 1995,
                'date' => '1995-09-01',
                'subjects' => ['Political Prisoners', 'Prisoner Support'],
            ],
            [
                'slug' => 'lns-755-1976',
                'title' => 'Liberation News Service Packet No. 755 — 1976',
                'description' => "Packet No. 755 of the Liberation News Service (LNS), the cooperative wire service that fed New Left and movement publications across North America from 1967 through 1981. The packet carries movement coverage from the same 1976 moment as PFOC's first Breakthrough issues.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/lns-755',
                'collection' => 'Liberation News Service',
                'authors' => 'Liberation News Service',
                'publisher' => 'Liberation News Service',
                'year' => 1976,
                'date' => '1976-01-01',
                'subjects' => ['Liberation News Service', 'LNS', 'New Left', 'Movement Media'],
            ],
            [
                'slug' => 'la-pena-newsletter-october-1980',
                'title' => 'La Peña Newsletter — October 1980',
                'description' => "Newsletter of La Peña Cultural Center in Berkeley, California, October 1980. La Peña — founded in 1975 by Chilean exiles and U.S. Latin American solidarity activists — was one of the principal Bay Area sites of the cross-movement organizing milieu that PFOC, the Puerto Rican independence movement, and Central American solidarity worked through.",
                'record_type' => 'newsletter',
                'source_format' => 'periodical',
                'file' => 'https://archive.org/details/cabepcc_000044',
                'collection' => 'La Peña Cultural Center',
                'publisher' => 'La Peña Cultural Center',
                'year' => 1980,
                'date' => '1980-10-01',
                'subjects' => ['La Peña', 'Chilean Solidarity', 'Latin American Solidarity', 'Berkeley'],
            ],

            // ─── Pamphlets / Communiques ───
            [
                'slug' => 'ohio-7-defeat-us-imperialism-pamphlet',
                'title' => 'Ohio 7 / On Trial For Seditious Conspiracy / Defeat US Imperialism',
                'description' => "Defense pamphlet for the Ohio 7 — Raymond Luc Levasseur, Patricia Gros Levasseur, Thomas Manning, Carol Manning, Richard Williams, Jaan Laaman, and Barbara Curzi-Laaman — the United Freedom Front clandestine cell prosecuted in the late 1980s on federal seditious-conspiracy and RICO charges for a series of 1976–1984 bombings of U.S. military and corporate targets. PFOC was one of the principal above-ground organizations that supported the Ohio 7 through their trials.",
                'record_type' => 'pamphlet',
                'source_format' => 'pamphlet',
                'file' => 'https://archive.org/details/ohio-7-defeat-us-imperialism-049',
                'collection' => 'Movement Pamphlets',
                'subjects' => ['Ohio 7', 'United Freedom Front', 'Ray Luc Levasseur', 'Seditious Conspiracy', 'Political Prisoners'],
            ],
            [
                'slug' => 'demonstrate-iwd-1983-flyer',
                'title' => 'Demonstrate — International Women\'s Day 1983, In Solidarity With All Freedom Fighters',
                'description' => "1983 International Women's Day demonstration flyer in solidarity with women political prisoners and freedom fighters, in the political tradition of PFOC's solidarity work with the Black Liberation Army, the FALN, and the New Afrikan Independence Movement.",
                'record_type' => 'pamphlet',
                'source_format' => 'flyer',
                'file' => 'https://archive.org/details/demonstrate-iwd-1983',
                'collection' => 'Movement Pamphlets',
                'year' => 1983,
                'date' => '1983-03-08',
                'subjects' => ['International Women\'s Day', 'Women Political Prisoners', 'Solidarity'],
            ],
            [
                'slug' => 'armed-forces-recruiting-station-bombings-communiques',
                'title' => 'Armed Forces Recruiting Station Bombings — Communiques',
                'description' => "Compilation of communiques from a 1980s campaign of bombings against U.S. Armed Forces recruiting stations — actions of the kind for which the Ohio 7 / United Freedom Front and other contemporaneous clandestine formations were prosecuted, and which PFOC covered in Breakthrough's 'armed actions' section.",
                'record_type' => 'document',
                'source_format' => 'communique',
                'file' => 'https://archive.org/details/recruitment-ofc_bombing',
                'collection' => 'Movement Communiques',
                'subjects' => ['Armed Struggle', 'Anti-Imperialism', 'United Freedom Front', 'Communiques'],
            ],
            [
                'slug' => 'war-on-the-war-makers-german-left',
                'title' => 'War On The War Makers — Documents and Communiques From The West German Left',
                'description' => "Compilation of documents and communiques from the West German radical left (Red Army Faction, Revolutionary Cells, etc.), translated for U.S. distribution. PFOC reprinted and analyzed RAF / Revolutionary Cells material throughout the 1980s as part of its internationalist anti-imperialist line.",
                'record_type' => 'document',
                'source_format' => 'compilation',
                'file' => 'https://archive.org/details/war-on-the-war-makers',
                'collection' => 'International Solidarity Documents',
                'subjects' => ['Red Army Faction', 'RAF', 'West German Left', 'International Solidarity', 'Anti-Imperialism'],
            ],
            [
                'slug' => 'split-of-weather-underground-organization',
                'title' => 'The Split Of The Weather Underground Organization',
                'description' => "Movement document on the 1976–77 split of the Weather Underground Organization that produced both the Prairie Fire Organizing Committee and the John Brown Anti-Klan Committee tendency on one side, and the 'Revolutionary Committee' that issued the 1976 self-criticism on the other. Essential context for the political conditions under which PFOC consolidated itself as the post-WUO above-ground formation.",
                'record_type' => 'document',
                'source_format' => 'internal_document',
                'file' => 'https://archive.org/details/thesplitoftheweatherundergroundorganization_202004',
                'collection' => 'Weather Underground / PFOC Internal Documents',
                'subjects' => ['Weather Underground', 'WUO', 'Prairie Fire Organizing Committee', 'PFOC', '1976 Split', 'Self-Criticism'],
            ],
            [
                'slug' => 'peoples-response-popeyes-murder-anvil-1975',
                'title' => 'The People\'s Response To Popeye\'s Murder — The Anvil, September 1975',
                'description' => "Article from *The Anvil*, September 1975, on the people's response to the police killing of 'Popeye' Jackson — the Bay Area prisoner-rights organizer killed in 1975 in a still-unsolved attack widely attributed to police or right-wing forces. One of the early mobilizations that the founding PFOC cadre worked through in the immediate post-WUO period.",
                'record_type' => 'document',
                'source_format' => 'periodical_article',
                'file' => 'https://archive.org/details/the-peoples-response-to-popeyes-murder',
                'collection' => 'The Anvil',
                'publisher' => 'The Anvil',
                'year' => 1975,
                'date' => '1975-09-01',
                'subjects' => ['Popeye Jackson', 'Prisoner Rights', 'Police Killings', 'Bay Area Movement'],
            ],

            // ─── Books / Monographs ───
            [
                'slug' => 'arm-the-spirit-diana-block-2009',
                'title' => 'Arm the Spirit: A Woman\'s Journey Underground and Back — Diana Block (2009)',
                'description' => "Memoir by Diana Block — a longtime PFOC member and one of the four women (with Donna Willmott, Claude Marks, and Robert McBride) who lived underground in the 1980s after being named as material witnesses in the 1986 Chicago grand jury investigating the FALN-PRO/PFOC alleged conspiracy to free Oscar López Rivera. The most detailed first-person account of PFOC's late-1980s underground period.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/armspiritwomansj0000bloc',
                'collection' => 'Movement Memoirs',
                'authors' => 'Diana Block',
                'publisher' => 'AK Press',
                'year' => 2009,
                'date' => '2009-01-01',
                'subjects' => ['Diana Block', 'Prairie Fire Organizing Committee', 'PFOC', 'White Anti-Imperialist', 'FALN Solidarity', 'Underground', 'Memoir'],
            ],
            [
                'slug' => 'truth-and-revolution-sto-history-2012',
                'title' => 'Truth and Revolution: A History of the Sojourner Truth Organization, 1969–1986 — Michael Staudenmaier (2012)',
                'description' => "Michael Staudenmaier's definitive history of the Sojourner Truth Organization (STO), the Chicago-based Marxist-Leninist cadre group that operated alongside and in polemic with PFOC throughout the 1970s on questions of whiteness, white-skin privilege, and the strategic role of white workers in anti-imperialist struggle.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/isbn_9781849350983',
                'collection' => 'Movement History',
                'authors' => 'Michael Staudenmaier',
                'publisher' => 'AK Press',
                'year' => 2012,
                'date' => '2012-01-01',
                'subjects' => ['Sojourner Truth Organization', 'STO', 'New Communist Movement', 'Noel Ignatiev', 'Whiteness'],
            ],
            [
                'slug' => 'way-the-wind-blew-jacobs-1997',
                'title' => 'The Way the Wind Blew: A History of the Weather Underground — Ron Jacobs (1997)',
                'description' => "Ron Jacobs's history of the Weather Underground Organization — the immediate political predecessor of PFOC. Covers the 1969 founding through the 1976–77 split that produced PFOC and the May 19th Communist Organization.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/waywindblewhisto00jaco',
                'collection' => 'Movement History',
                'authors' => 'Ron Jacobs',
                'publisher' => 'Verso',
                'year' => 1997,
                'date' => '1997-01-01',
                'subjects' => ['Weather Underground', 'WUO', 'Prairie Fire Organizing Committee', 'PFOC', 'May 19th Communist Organization'],
            ],
            [
                'slug' => 'outlaws-of-america-berger-2006',
                'title' => 'Outlaws of America: The Weather Underground and the Politics of Solidarity — Dan Berger (2006)',
                'description' => "Dan Berger's history of the Weather Underground and its post-1976 successor formations, including extensive treatment of PFOC's role as the above-ground political organization of the anti-imperialist white left. Indispensable for understanding PFOC's place in the broader anti-imperialist solidarity tradition.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/outlawsofamerica0000berg',
                'collection' => 'Movement History',
                'authors' => 'Dan Berger',
                'publisher' => 'AK Press',
                'year' => 2006,
                'date' => '2006-01-01',
                'subjects' => ['Weather Underground', 'Prairie Fire Organizing Committee', 'PFOC', 'White Anti-Imperialist', 'Solidarity Politics'],
            ],
            [
                'slug' => 'bad-moon-rising-eckstein-2016',
                'title' => 'Bad Moon Rising: How the Weather Underground Beat the FBI and Lost the Revolution — Arthur Eckstein (2016)',
                'description' => "Arthur Eckstein's history of the Weather Underground, drawing heavily on FBI files. Covers the 1976 split and the emergence of PFOC, the May 19th Communist Organization, and the Resistance Conspiracy formation.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/badmoonrisinghow0000ecks',
                'collection' => 'Movement History',
                'authors' => 'Arthur Eckstein',
                'publisher' => 'Yale University Press',
                'year' => 2016,
                'date' => '2016-01-01',
                'subjects' => ['Weather Underground', 'WUO', 'PFOC', 'FBI', 'COINTELPRO'],
            ],
            [
                'slug' => 'lavender-and-red-hobson-2016',
                'title' => 'Lavender and Red: Liberation and Solidarity in the Gay and Lesbian Left — Emily K. Hobson (2016)',
                'description' => "Emily Hobson's history of the U.S. gay and lesbian left from the 1970s through the 1990s, with substantial treatment of the Lesbians Against Police Violence, the Lavender & Red Union, and the gay-and-lesbian organizing inside PFOC and the broader white anti-imperialist solidarity movement.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/lavenderredliber0000hobs',
                'collection' => 'Movement History',
                'authors' => 'Emily K. Hobson',
                'publisher' => 'University of California Press',
                'year' => 2016,
                'date' => '2016-01-01',
                'subjects' => ['LGBT Left', 'Lavender and Red Union', 'PFOC', 'Lesbians Against Police Violence', 'Solidarity Politics'],
            ],
            [
                'slug' => 'no-fascist-usa-moore-2020',
                'title' => 'No Fascist USA! The John Brown Anti-Klan Committee and Lessons for Today\'s Movements — Hilary Moore & James Tracy (2020)',
                'description' => "Hilary Moore and James Tracy's history of the John Brown Anti-Klan Committee (JBAKC) — the late-1970s through 1990s anti-fascist formation that grew out of PFOC's tradition of anti-imperialist solidarity work and that became one of the most consistent U.S. anti-Klan and anti-Nazi organizing vehicles of the period.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/nofascistusajohn0000moor',
                'collection' => 'Movement History',
                'authors' => 'Hilary Moore and James Tracy',
                'publisher' => 'PM Press',
                'year' => 2020,
                'date' => '2020-01-01',
                'subjects' => ['John Brown Anti-Klan Committee', 'JBAKC', 'PFOC', 'Anti-Fascism', 'Anti-Klan Organizing'],
            ],
            [
                'slug' => 'captive-nation-berger-2014',
                'title' => 'Captive Nation: Black Prison Organizing in the Civil Rights Era — Dan Berger (2014)',
                'description' => "Dan Berger's history of Black prison organizing from the 1950s through the 1980s — the political base of the political-prisoner support tradition that PFOC's *Breakthrough* magazine covered most consistently. Includes substantial treatment of the BLA, the RNA, the Black Panther Party prisoner support work, and the Attica uprising.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/captivenationbla0000berg',
                'collection' => 'Movement History',
                'authors' => 'Dan Berger',
                'publisher' => 'University of North Carolina Press',
                'year' => 2014,
                'date' => '2014-01-01',
                'subjects' => ['Black Prison Organizing', 'Attica', 'BLA', 'Black Panther Party', 'New Afrikan Independence Movement'],
            ],
            [
                'slug' => 'struggle-within-berger-2014',
                'title' => 'The Struggle Within: Prisons, Political Prisoners, and Mass Movements in the United States — Dan Berger (2014)',
                'description' => "Dan Berger's overview of U.S. political-prisoner support work from the 1960s onward. PFOC's *Breakthrough* and the parallel publications archived alongside this record are core primary sources for the period the book covers.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/strugglewithinpr0000berg',
                'collection' => 'Movement History',
                'authors' => 'Dan Berger',
                'publisher' => 'PM Press',
                'year' => 2014,
                'date' => '2014-01-01',
                'subjects' => ['Political Prisoners', 'Prison Movements', 'PFOC', 'Breakthrough'],
            ],
            [
                'slug' => 'co-conspirator-for-justice-alan-berkman-2020',
                'title' => 'Co-Conspirator for Justice: The Revolutionary Life of Dr. Alan Berkman — Susan M. Reverby (2020)',
                'description' => "Susan Reverby's biography of Dr. Alan Berkman — the May 19th Communist Organization / Resistance Conspiracy defendant, longtime PFOC ally, and movement physician who treated Marilyn Buck after the 1981 Brink's/Nyack action and went underground himself before being captured in 1985. One of the most detailed accounts of the political world Breakthrough magazine reported from.",
                'record_type' => 'book',
                'source_format' => 'book',
                'file' => 'https://archive.org/details/coconspiratorfor0000reve',
                'collection' => 'Movement Biographies',
                'authors' => 'Susan M. Reverby',
                'publisher' => 'University of North Carolina Press',
                'year' => 2020,
                'date' => '2020-01-01',
                'subjects' => ['Alan Berkman', 'May 19th Communist Organization', 'Resistance Conspiracy', 'PFOC', 'Marilyn Buck'],
            ],
        ];

        $base = [
            'is_digitized' => true,
            'published' => true,
        ];

        $added = 0;
        $updated = 0;
        foreach ($records as $rec) {
            $slug = $rec['slug'];
            unset($rec['slug']);
            $payload = $base + $rec;

            $existing = ArchiveRecord::where('slug', $slug)->first();
            if ($existing) {
                $existing->update($payload);
                $this->info("UPDATE: {$slug}");
                $updated++;
            } else {
                ArchiveRecord::create(['slug' => $slug] + $payload);
                $this->info("ADD:    {$slug}");
                $added++;
            }
        }

        $this->info("\nDone — added {$added}, updated {$updated}.");

        return self::SUCCESS;
    }
}
