<?php

namespace App\Console\Commands;

use App\Models\DashboardLink;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

/**
 * Adds miscellaneous free-speech / protest arrest cases to the dashboard as
 * DashboardLink markers (map pins + newswire). Each is an arrest or charge over
 * expressive conduct — a joke, a post, sidewalk chalk, a protest. Sourced from
 * public reporting; matched on URL so the command is idempotent and re-runnable.
 */
class AddSpeechArrestDashboardCases extends Command {
    protected $signature = 'dashboard:add-speech-cases';
    protected $description = 'Add miscellaneous free-speech / protest arrest cases to the dashboard';

    public function handle(): int {
        $cases = [
            [
                'title'          => 'FIU student Gabriela Saldana charged with a felony "written threat" over a WhatsApp joke about Netanyahu',
                'url'            => 'https://wsvn.com/news/local/miami-dade/fiu-student-arrested-for-wanting-israels-netanyahu-to-drop-bombs-on-school-event-arena-police-say/',
                'source'         => 'WSVN',
                'category'       => 'arrest',
                'published_at'   => '2026-04-16',
                'location_label' => 'Miami, FL',
                'lat'            => 25.7563,
                'lng'            => -80.3736,
            ],
            [
                'title'          => 'Protesters arrested (charges later dropped) for chalking the rainbow back onto Orlando\'s Pulse memorial crosswalk',
                'url'            => 'https://www.orlandoweekly.com/news/pulse/state-attorney-drops-charges-for-pulse-crosswalk-arrests/',
                'source'         => 'Orlando Weekly',
                'category'       => 'protest',
                'published_at'   => '2025-08-31',
                'location_label' => 'Orlando, FL',
                'lat'            => 28.5306,
                'lng'            => -81.3766,
            ],
            [
                'title'          => 'Julian Pecora Cardenas charged with conspiracy for livestreaming a Border Patrol convoy in San Pedro, CA',
                'url'            => 'https://www.pbs.org/wgbh/frontline/article/caught-in-crackdown-ice-cbp-immigration-protests-arrests-convictions/',
                'source'         => 'PBS FRONTLINE',
                'category'       => 'arrest',
                'published_at'   => '2025-07-05',
                'location_label' => 'San Pedro, CA',
                'lat'            => 33.7361,
                'lng'            => -118.2922,
            ],
            [
                'title'          => 'Army veteran Jay Carey arrested for burning a U.S. flag in protest near the White House; charges later dropped',
                'url'            => 'https://www.nbcnews.com/politics/justice-department/drops-case-veteran-carey-arrested-burning-american-flag-white-house-rcna263438',
                'source'         => 'NBC News',
                'category'       => 'protest',
                'published_at'   => '2025-08-25',
                'location_label' => 'Washington, DC',
                'lat'            => 38.9000,
                'lng'            => -77.0365,
            ],
            [
                'title'          => 'SEIU California president David Huerta arrested and charged over an LA anti-ICE protest (felony later reduced to a misdemeanor)',
                'url'            => 'https://www.cbsnews.com/news/david-huerta-california-labor-felony-charge-immigration-protest-reduced/',
                'source'         => 'CBS News',
                'category'       => 'arrest',
                'published_at'   => '2025-06-06',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0522,
                'lng'            => -118.2437,
            ],
            [
                'title'          => 'Journalist Mario Guevara arrested while livestreaming an Atlanta "No Kings" protest; charges dropped, then deported by ICE',
                'url'            => 'https://www.cnn.com/2025/10/03/media/mario-guevara-journalist-deported-ice-el-salvador',
                'source'         => 'CNN',
                'category'       => 'arrest',
                'published_at'   => '2025-06-14',
                'location_label' => 'Atlanta, GA',
                'lat'            => 33.7490,
                'lng'            => -84.3880,
            ],
            [
                'title'          => 'Student journalist Lucas Griffith arrested covering an anti-ICE march in Covington, KY (felony rioting count dropped; convicted of failure to disperse)',
                'url'            => 'https://cpj.org/2025/10/ohio-journalist-convicted-after-arrest-while-covering-kentucky-protest/',
                'source'         => 'CPJ',
                'category'       => 'arrest',
                'published_at'   => '2025-07-17',
                'location_label' => 'Covington, KY',
                'lat'            => 39.0837,
                'lng'            => -84.5086,
            ],
            [
                'title'          => 'Katherine Hinds arrested over anti-Trump banners on Connecticut highway overpasses; all charges later dropped',
                'url'            => 'https://www.ctpublic.org/news/investigative/2025-10-28/charges-dropped-against-ct-woman-arrested-for-protesting-on-highway-bridges',
                'source'         => 'CT Public',
                'category'       => 'protest',
                'published_at'   => '2025-07-19',
                'location_label' => 'Hamden, CT',
                'lat'            => 41.3959,
                'lng'            => -72.8968,
            ],
            [
                'title'          => 'Arden Wells charged with felony "terrorizing" over a Facebook post critical of the Tangipahoa Parish sheriff (DA rejected all counts)',
                'url'            => 'https://www.fox8live.com/2026/02/04/tangipahoa-prosecutors-refuse-charge-man-arrested-over-facebook-post/',
                'source'         => 'FOX 8',
                'category'       => 'arrest',
                'published_at'   => '2025-07-25',
                'location_label' => 'Amite City, LA',
                'lat'            => 30.7299,
                'lng'            => -90.5126,
            ],
            [
                'title'          => 'Jeana Gamble arrested in a costume at an Alabama "No Kings" protest; acquitted of all charges',
                'url'            => 'https://reason.com/2026/04/16/62-year-old-protester-acquitted-on-all-charges-for-wearing-penis-costume/',
                'source'         => 'Reason',
                'category'       => 'protest',
                'published_at'   => '2025-10-18',
                'location_label' => 'Fairhope, AL',
                'lat'            => 30.5230,
                'lng'            => -87.9033,
            ],
            [
                'title'          => 'Navy veteran Kolton Krottinger charged with felony online impersonation over a satirical Facebook post (charge later declined)',
                'url'            => 'https://www.cbsnews.com/texas/news/hood-county-veteran-facebook-impersonation-arrest-free-speech-case/',
                'source'         => 'CBS Texas',
                'category'       => 'arrest',
                'published_at'   => '2025-11-05',
                'location_label' => 'Granbury, TX',
                'lat'            => 32.4421,
                'lng'            => -97.7942,
            ],
            [
                'title'          => 'Journalists Don Lemon and Georgia Fort arrested on federal charges over filming an anti-ICE protest at a St. Paul church',
                'url'            => 'https://www.pbs.org/newshour/politics/don-lemon-pleads-not-guilty-to-civil-rights-charges-in-anti-ice-minnesota-church-protest',
                'source'         => 'PBS NewsHour',
                'category'       => 'arrest',
                'published_at'   => '2026-01-30',
                'location_label' => 'St. Paul, MN',
                'lat'            => 44.9537,
                'lng'            => -93.0900,
            ],
            [
                'title'          => 'Three "No Kings" protesters arrested in Memphis (charges later dropped)',
                'url'            => 'https://wreg.com/news/charges-dropped-against-three-arrested-during-no-kings-protest/',
                'source'         => 'WREG',
                'category'       => 'protest',
                'published_at'   => '2026-03-28',
                'location_label' => 'Memphis, TN',
                'lat'            => 35.1495,
                'lng'            => -90.0490,
            ],
            [
                'title'          => 'NYC Council Member Chi Osse arrested while protesting a Brooklyn eviction',
                'url'            => 'https://www.thecity.nyc/2026/04/22/brooklyn-eviction-chi-osse-arrest-police-deed-theft/',
                'source'         => 'THE CITY',
                'category'       => 'protest',
                'published_at'   => '2026-04-22',
                'location_label' => 'Brooklyn, NY',
                'lat'            => 40.6782,
                'lng'            => -73.9442,
            ],
            [
                'title'          => 'Charges against the "Broadview Six" anti-ICE protesters (incl. Kat Abughazaleh) dismissed after admitted grand-jury misconduct',
                'url'            => 'https://chicago.suntimes.com/immigration/2026/05/21/broadview-ice-protest-grand-jury-transcript-kat-abughazaleh-trump',
                'source'         => 'Chicago Sun-Times',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-21',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8639,
                'lng'            => -87.8534,
            ],
            [
                'title'          => 'Spokane 3 (Jac Archer, Justice Forral, Bajun Mavalwalla II) convicted of federal conspiracy for blocking an ICE detainee transfer',
                'url'            => 'https://www.spokesman.com/stories/2026/may/28/3-spokane-ice-protesters-found-guilty-in-conspirac/',
                'source'         => 'Spokesman-Review',
                'category'       => 'prosecution',
                'published_at'   => '2026-05-28',
                'location_label' => 'Spokane, WA',
                'lat'            => 47.6588,
                'lng'            => -117.4260,
            ],
            [
                'title'          => 'Newark Mayor Ras Baraka arrested on a federal trespassing charge at the Delaney Hall ICE facility; charge later dropped',
                'url'            => 'https://www.cbsnews.com/newyork/news/ras-baraka-charge-dropped-alina-habba/',
                'source'         => 'CBS News',
                'category'       => 'arrest',
                'published_at'   => '2025-05-09',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7203,
                'lng'            => -74.1490,
            ],
            [
                'title'          => 'U.S. Rep. LaMonica McIver indicted on federal charges over a congressional oversight visit to a Newark ICE facility',
                'url'            => 'https://www.nbcnews.com/politics/justice-department/lamonica-mciver-ras-baraka-alina-habba-ice-new-jersey-newark-rcna207842',
                'source'         => 'NBC News',
                'category'       => 'prosecution',
                'published_at'   => '2025-05-19',
                'location_label' => 'Newark, NJ',
                'lat'            => 40.7357,
                'lng'            => -74.1724,
            ],
            [
                'title'          => 'NYC Comptroller Brad Lander arrested at immigration court while escorting a migrant; released without charges',
                'url'            => 'https://www.thecity.nyc/2025/06/17/brad-lander-arrest-ice-immigration-court/',
                'source'         => 'THE CITY',
                'category'       => 'arrest',
                'published_at'   => '2025-06-17',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7160,
                'lng'            => -74.0035,
            ],
            [
                'title'          => 'Alejandro Orellana federally charged for handing out face shields and water at an LA anti-ICE protest; case dismissed',
                'url'            => 'https://www.cbsnews.com/losangeles/news/justice-department-moves-to-dismiss-charges-against-la-man-accused-of-giving-ice-protesters-face-shields/',
                'source'         => 'CBS News',
                'category'       => 'prosecution',
                'published_at'   => '2025-06-12',
                'location_label' => 'Los Angeles, CA',
                'lat'            => 34.0239,
                'lng'            => -118.2068,
            ],
            [
                'title'          => 'More than a dozen NYC and New York State elected officials arrested in an ICE sit-in at 26 Federal Plaza',
                'url'            => 'https://www.thecity.nyc/2025/09/18/dhs-arrests-brad-lander-democratic-lawmakers-26-federal-plaza/',
                'source'         => 'THE CITY',
                'category'       => 'protest',
                'published_at'   => '2025-09-18',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7146,
                'lng'            => -74.0049,
            ],
            [
                'title'          => 'Faith leaders incl. Rev. Michael Woolf arrested at a clergy-led protest outside the Broadview ICE facility; charges later dropped',
                'url'            => 'https://chicago.suntimes.com/immigration/2026/02/09/cook-county-prosecutors-drop-charges-against-19-arrested-during-clergy-led-protest-broadview-ice-facility',
                'source'         => 'Chicago Sun-Times',
                'category'       => 'protest',
                'published_at'   => '2025-11-14',
                'location_label' => 'Broadview, IL',
                'lat'            => 41.8600,
                'lng'            => -87.8500,
            ],
            [
                'title'          => 'Former FBI Director James Comey indicted on federal threat charges over an "86 47" seashell Instagram post',
                'url'            => 'https://www.cnbc.com/2026/04/28/james-comey-indicted-trump-seashell-8647.html',
                'source'         => 'CNBC',
                'category'       => 'prosecution',
                'published_at'   => '2026-04-28',
                'location_label' => 'Alexandria, VA',
                'lat'            => 38.8048,
                'lng'            => -77.0469,
            ],
            [
                'title'          => 'About 78 people arrested in the Columbia University "Butler Library" pro-Palestinian occupation',
                'url'            => 'https://time.com/7283786/columbia-university-protests-butler-library-police-arrests-politics-trump-explainer/',
                'source'         => 'TIME',
                'category'       => 'arrest',
                'published_at'   => '2025-05-07',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.8068,
                'lng'            => -73.9637,
            ],
            [
                'title'          => 'Thirty-four arrested, including ADAPT wheelchair users, protesting Medicaid cuts at the Russell Senate building',
                'url'            => 'https://www.cnbc.com/2025/06/25/capitol-police-medicaid-protests-.html',
                'source'         => 'CNBC',
                'category'       => 'protest',
                'published_at'   => '2025-06-25',
                'location_label' => 'Washington, DC',
                'lat'            => 38.8927,
                'lng'            => -77.0080,
            ],
            [
                'title'          => 'Nine climate activists arrested in a sit-in at the office of Connecticut Gov. Ned Lamont over a gas-pipeline expansion',
                'url'            => 'https://ctmirror.org/2025/11/17/ct-climate-natural-gas-expansion-protest/',
                'source'         => 'CT Mirror',
                'category'       => 'protest',
                'published_at'   => '2025-11-17',
                'location_label' => 'Hartford, CT',
                'lat'            => 41.7637,
                'lng'            => -72.6851,
            ],
            [
                'title'          => 'Photojournalist Dave Decker arrested covering an anti-ICE protest in Miami; charges later dropped',
                'url'            => 'https://www.tampabay.com/news/tampa/2025/12/16/dave-decker-arrest-charges-dropped-miami-ice-protest-immigration/',
                'source'         => 'Tampa Bay Times',
                'category'       => 'arrest',
                'published_at'   => '2025-11-22',
                'location_label' => 'Miami, FL',
                'lat'            => 25.7617,
                'lng'            => -80.1918,
            ],
            [
                'title'          => 'About 15 people arrested in sit-ins at the Idaho Capitol protesting a new transgender bathroom-ban law (HB 752)',
                'url'            => 'https://www.boisestatepublicradio.org/news/2026-04-01/protestors-arrested-office-idaho-governor-brad-little',
                'source'         => 'Boise State Public Radio',
                'category'       => 'protest',
                'published_at'   => '2026-04-02',
                'location_label' => 'Boise, ID',
                'lat'            => 43.6178,
                'lng'            => -116.1996,
            ],
            [
                'title'          => 'Sixteen Extinction Rebellion climate activists arrested blocking Fifth Avenue at Trump Tower on Earth Day',
                'url'            => 'https://www.amny.com/news/climate-activists-arrested-trump-tower-protest-04222026/',
                'source'         => 'amNewYork',
                'category'       => 'protest',
                'published_at'   => '2026-04-22',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7625,
                'lng'            => -73.9740,
            ],
            [
                'title'          => 'Georgia judge dismisses RICO racketeering charges against all 61 "Stop Cop City" forest-defender defendants',
                'url'            => 'https://www.fox5atlanta.com/news/rico-charges-stop-cop-city-dismissed-attorney-general-chris-carr',
                'source'         => 'FOX 5 Atlanta',
                'category'       => 'prosecution',
                'published_at'   => '2025-12-30',
                'location_label' => 'Atlanta, GA',
                'lat'            => 33.7490,
                'lng'            => -84.3880,
            ],
            [
                'title'          => 'Climate activist Timothy Martin sentenced to 18 months for a paint protest on the case of a Degas sculpture at the National Gallery',
                'url'            => 'https://www.theartnewspaper.com/2025/10/31/climate-activist-timothy-martin-national-gallery-art-degas-sculpture-sentenced',
                'source'         => 'The Art Newspaper',
                'category'       => 'prosecution',
                'published_at'   => '2025-10-27',
                'location_label' => 'Washington, DC',
                'lat'            => 38.8913,
                'lng'            => -77.0200,
            ],
            [
                'title'          => 'Eighteen Climate Defiance activists arrested at the New York Capitol protesting a rollback of the state climate law',
                'url'            => 'https://www.news10.com/capitol/ny-capitol-climate-protest-arrests/',
                'source'         => 'News10',
                'category'       => 'protest',
                'published_at'   => '2026-04-21',
                'location_label' => 'Albany, NY',
                'lat'            => 42.6526,
                'lng'            => -73.7562,
            ],
            [
                'title'          => 'DxE activist Zoe Rosenberg convicted and sentenced to 90 days over a "right to rescue" chicken removal at Petaluma Poultry',
                'url'            => 'https://www.pressdemocrat.com/2025/12/03/zoe-rosenberg-sonoma-county-sentence/',
                'source'         => 'Press Democrat',
                'category'       => 'prosecution',
                'published_at'   => '2025-12-03',
                'location_label' => 'Petaluma, CA',
                'lat'            => 38.2324,
                'lng'            => -122.6367,
            ],
            [
                'title'          => 'Wayne Hsiung and three activists charged with four felonies each over an "open rescue" of 22 beagles from Ridglan Farms',
                'url'            => 'https://wisconsinexaminer.com/2026/05/01/1500-ridglan-beagles-purchased-by-animal-welfare-groups-lead-activist-in-court/',
                'source'         => 'Wisconsin Examiner',
                'category'       => 'arrest',
                'published_at'   => '2026-03-15',
                'location_label' => 'Blue Mounds, WI',
                'lat'            => 43.0181,
                'lng'            => -89.8443,
            ],
            [
                'title'          => 'Two UNITE HERE organizers arrested for trespassing while protesting Aramark dining-worker pay at an ASU commencement',
                'url'            => 'https://www.statepress.com/article/2026/05/asu-pd-arrests-aramark-protesters',
                'source'         => 'Arizona State Press',
                'category'       => 'protest',
                'published_at'   => '2026-05-11',
                'location_label' => 'Tempe, AZ',
                'lat'            => 33.4242,
                'lng'            => -111.9281,
            ],
            [
                'title'          => 'Thirteen striking NYSNA nurses arrested in a Midtown civil-disobedience action during the longest nurses strike in NYC history',
                'url'            => 'https://www.amny.com/news/nurses-strike-nyc-arrested-civil-disobedience/',
                'source'         => 'amNewYork',
                'category'       => 'protest',
                'published_at'   => '2026-02-05',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7700,
                'lng'            => -73.9880,
            ],
            [
                'title'          => 'Twelve striking Starbucks baristas arrested blocking the Empire State Building during the "Red Cup Rebellion" strike',
                'url'            => 'https://abc7ny.com/post/12-starbucks-workers-arrested-protesting-outside-empire-state-building-manhattan/18253341/',
                'source'         => 'ABC7 New York',
                'category'       => 'protest',
                'published_at'   => '2025-12-04',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7484,
                'lng'            => -73.9857,
            ],
            [
                'title'          => 'About two dozen Culinary Union members arrested in a civil-disobedience road blockade near the Las Vegas airport over stalled contracts',
                'url'            => 'https://lasvegassun.com/news/2025/dec/03/las-vegas-airport-workers-arrested-in-civil-disobe/',
                'source'         => 'Las Vegas Sun',
                'category'       => 'protest',
                'published_at'   => '2025-12-03',
                'location_label' => 'Las Vegas, NV',
                'lat'            => 36.0840,
                'lng'            => -115.1537,
            ],
            [
                'title'          => 'Jewish Voice for Peace activists arrested occupying the lobby of arms maker Day & Zimmermann in Philadelphia over weapons for Gaza',
                'url'            => 'https://www.inquirer.com/news/philadelphia/philadelphia-protest-day-zimmerman-gaza-20250702.html',
                'source'         => 'Philadelphia Inquirer',
                'category'       => 'protest',
                'published_at'   => '2025-07-02',
                'location_label' => 'Philadelphia, PA',
                'lat'            => 39.9612,
                'lng'            => -75.1620,
            ],
            [
                'title'          => 'Five elder women cited for a human blockade at Travis Air Force Base protesting U.S. weapons shipments to Israel',
                'url'            => 'https://www.abc10.com/article/news/local/fairfield/5-cited-and-released-after-protest-travis-afb/103-c8ac9556-7aa1-41f8-b56a-c7457c7a3d44',
                'source'         => 'ABC10',
                'category'       => 'protest',
                'published_at'   => '2025-06-24',
                'location_label' => 'Fairfield, CA',
                'lat'            => 38.2494,
                'lng'            => -122.0400,
            ],
            [
                'title'          => 'Ten activists arrested blockading an arms shipment to Israel at the Port Newark-Elizabeth marine terminal',
                'url'            => 'https://wagingnonviolence.org/2026/05/pro-palestine-activists-arrested-blockading-new-jersey-port/',
                'source'         => 'Waging Nonviolence',
                'category'       => 'protest',
                'published_at'   => '2026-05-22',
                'location_label' => 'Elizabeth, NJ',
                'lat'            => 40.6776,
                'lng'            => -74.1399,
            ],
            [
                'title'          => 'Nearly 100 arrested, including Chelsea Manning, at a Jewish Voice for Peace sit-in at the offices of Sens. Schumer and Gillibrand over arms to Israel',
                'url'            => 'https://www.commondreams.org/news/anti-israel-protesters-arrested',
                'source'         => 'Common Dreams',
                'category'       => 'protest',
                'published_at'   => '2026-04-13',
                'location_label' => 'Manhattan, NY',
                'lat'            => 40.7570,
                'lng'            => -73.9690,
            ],
        ];

        $created = 0;
        foreach ($cases as $case) {
            $link = DashboardLink::firstOrCreate(
                ['url' => $case['url']],
                array_merge($case, ['published_at' => Carbon::parse($case['published_at'])]),
            );

            if ($link->wasRecentlyCreated) {
                $created++;
                $this->info("Added: {$case['title']}");
            } else {
                $this->line("Skipped (already present): {$case['title']}");
            }
        }

        $this->info("Done. {$created} new case(s) added; ".(count($cases) - $created).' already present.');

        return self::SUCCESS;
    }
}
