<?php

namespace App\Console\Commands;

use App\Models\CalendarEntry;
use App\Models\Prisoner;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;

/**
 * Eugene Debs cleanup + "on this day" calendar entry for his June 30, 1918
 * arrest.
 *
 *  1) Folds the duplicate record: both `eugene-debs` (photo, 3 cases) and
 *     `eugene-v-debs` (no photo, 1 case) exist. The richer `eugene-debs` is
 *     kept; the duplicate is deleted.
 *  2) Fixes the kept record's 1918 Espionage Act case dates: Debs was arrested
 *     June 30, 1918 in Cleveland (two weeks after the Canton speech), remained
 *     FREE pending his Supreme Court appeal, entered Moundsville prison on
 *     April 13, 1919, and was released from Atlanta on December 25, 1921 when
 *     President Harding commuted his sentence. (The record wrongly showed him
 *     jailed from his September 1918 conviction, and released Dec 24.)
 *  3) Deletes the boilerplate third case (a bulk-import "Espionage Act of 1917
 *     and/or Sedition Act" stub, arrest 1918-07-10) that duplicates the real
 *     1918 prosecution.
 *  4) Adds a June 30 calendar entry for the arrest, linked to the prisoner,
 *     with the committed graphic (skips if a Debs entry already exists on
 *     June 30 — including one auto-generated by calendar:generate).
 *
 * Idempotent.
 */
final class FixDebsAddCalendarEntry extends Command
{
    protected $signature = 'prisoners:fix-debs-add-calendar';

    protected $description = 'Fold the duplicate Eugene Debs record, fix his 1918 case dates, add the June 30 arrest calendar entry';

    private const IMAGE_SOURCE = 'images/calendar/debs-arrest-1918.png';

    private const IMAGE_DEST = 'calendar/debs-arrest-1918.png';

    public function handle(): int
    {
        $keep = Prisoner::withoutGlobalScopes()->where('slug', 'eugene-debs')->first();
        $dupe = Prisoner::withoutGlobalScopes()->where('slug', 'eugene-v-debs')->first();

        // ---- 1) Fold the duplicate ----
        if ($dupe) {
            $dupe->cases()->delete();
            $dupe->podcastEpisodes()->delete();
            $dupe->calendarEntries()->delete();
            $dupe->delete();
            $this->info('Removed duplicate record eugene-v-debs.');
        }

        if (! $keep) {
            $this->warn('No eugene-debs record found — skipping case fixes.');
        } else {
            // ---- 2) Fix the 1918 Espionage Act case dates ----
            $case1918 = $keep->cases()
                ->whereYear('arrest_date', 1918)
                ->where('charges', 'not like', '%and/or%')
                ->first();
            if ($case1918) {
                $case1918->arrest_date = '1918-06-30';        // Cleveland arrest
                $case1918->incarceration_date = '1919-04-13'; // entered Moundsville after appeal lost
                $case1918->release_date = '1921-12-25';       // Harding commutation, walked out Christmas Day
                $case1918->save();
                $case1918->refresh();
                $this->info("Fixed 1918 case dates ({$case1918->imprisoned_for_days} days served).");
            }

            // ---- 3) Delete the boilerplate stub case ----
            $deleted = $keep->cases()
                ->where('charges', 'like', '%Espionage Act of 1917 and/or%')
                ->delete();
            if ($deleted) {
                $this->info('Deleted bulk-import stub case.');
            }
        }

        // ---- 4) Calendar entry for the June 30, 1918 arrest ----
        $exists = CalendarEntry::where('month', 6)->where('day', 30)
            ->where('title', 'like', '%Debs%')->exists();
        if ($exists) {
            $this->info('June 30 Debs calendar entry already present — not duplicating.');

            return self::SUCCESS;
        }

        $image = null;
        $source = public_path(self::IMAGE_SOURCE);
        if (is_file($source)) {
            Storage::disk('public')->put(self::IMAGE_DEST, file_get_contents($source));
            $image = self::IMAGE_DEST;
        } else {
            $this->warn('Committed image missing: public/'.self::IMAGE_SOURCE.' — entry created without image.');
        }

        CalendarEntry::create([
            'month' => 6,
            'day' => 30,
            'year' => 1918,
            'title' => 'Eugene Debs arrested for denouncing World War I',
            'description' => 'On this day in 1918, Socialist Party leader Eugene V. Debs was arrested in Cleveland, Ohio, two weeks after his Canton speech denouncing World War I and capitalist war-making. Convicted under the Espionage Act as amended by the Sedition Act and sentenced to ten years, he entered prison in April 1919, ran for president from his Atlanta cell in 1920 — winning nearly a million votes — and was released on December 25, 1921, when President Harding commuted his sentence.',
            'image' => $image,
            'published' => true,
            'prisoner_id' => $keep?->id,
        ]);
        $this->info('Added June 30, 1918 calendar entry for the Debs arrest.');

        return self::SUCCESS;
    }
}
