#!/usr/bin/env bash
#
# Strip a large batch of affiliation values from every prisoner's affiliation
# list (other affiliations kept; no records deleted). The exact list of 197
# values is in database/data/affiliation-remove.json (generated by matching the
# requested names to the exact affiliation strings in the database).
#
# Case-insensitive, whitespace-trimmed. Idempotent. Run from the repo root:
#   bash database/data/remove-affiliations-round1.sh

set -euo pipefail
cd "$(dirname "$0")/../.."

php artisan tinker --execute='
$remove = array_map(fn ($v) => strtolower(trim((string) $v)),
    (array) json_decode(file_get_contents(base_path("database/data/affiliation-remove.json")), true));
$removeSet = array_flip($remove);

$changed = 0;
\App\Models\Prisoner::withoutGlobalScopes()
    ->select("id", "affiliation")
    ->chunk(500, function ($chunk) use (&$changed, $removeSet) {
        foreach ($chunk as $p) {
            $aff = (array) $p->affiliation;
            $kept = array_values(array_filter($aff, fn ($v) => ! isset($removeSet[strtolower(trim((string) $v))])));
            if (count($kept) !== count($aff)) {
                $p->affiliation = $kept ?: null;
                $p->save();
                $changed++;
            }
        }
    });

echo "Removed listed affiliations from {$changed} record(s).\n";
\Illuminate\Support\Facades\Cache::forget(\App\Http\Controllers\Api\PrisonerApiController::cacheKey());
echo "Done.\n";
'

echo
echo "Done. Affiliation removals applied."
