#!/usr/bin/env bash
# Political-prisoner cases extracted from The Black Panther newspaper, Vol. 14 (Sept. 1975 - Apr. 1976),
# read page-by-page (all 28 issues, ~1,090 pages) from the marxists.org archive.
# RUN ON THE SERVER after review. Idempotent: prisoner:add de-dupes by name, so any of these
# figures already in the database (e.g. from the Vol. 15-19 imports) are simply skipped.
# Continue-on-error so duplicates/failures don't abort the batch:
set +e

# ===== GROUP A -- U.S. political-prisoner cases (62) =====

# Alex Poindexter (NE)
php artisan prisoner:add '{"name": "Alex Poindexter", "first_name": "Alex", "last_name": "Poindexter", "description": "Omaha activist and member of the National Committee to Combat Fascism (a BPP affiliate), convicted with David Rice of the 1970 bombing death of a policeman on the testimony of a 15-year-old who admitted planting the bomb; The Black Panther Vol. 14 no.23 (1976). One of the '\''Omaha Two,'\'' he (Ed Poindexter) remained imprisoned for decades. [Source: The Black Panther (Black Panther Party newspaper), v14 no.23; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NE", "affiliation": ["National Committee to Combat Fascism"]}'

# Alfonso Ross (NY)
php artisan prisoner:add '{"name": "Alfonso Ross", "first_name": "Alfonso", "last_name": "Ross", "description": "One of the '\''Attica Brothers'\'' charged with kidnapping and unlawful imprisonment for allegedly taking hostages in the 1971 Attica rebellion; The Black Panther Vol. 14 no.12 (1975) reports New York State dropped the charges for lack of evidence. [Source: The Black Panther (Black Panther Party newspaper), v14 no.12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Rahiem Gamba Banga", "state": "NY"}'

# Arthur Barber (NY)
php artisan prisoner:add '{"name": "Arthur Barber", "first_name": "Arthur", "last_name": "Barber", "description": "Bronx man ordered released or retried after nearly 10 years when Judge Constance Baker Motley ruled his murder confession had been obtained through severe police beatings amid '\''a pattern of lawlessness'\''; The Black Panther Vol. 14 no.1 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.1; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Bernard Stroble (NY)
php artisan prisoner:add '{"name": "Bernard Stroble", "first_name": "Bernard", "last_name": "Stroble", "description": "One of the '\''Attica Brothers,'\'' tried on murder and kidnapping charges arising from the 1971 Attica rebellion; The Black Panther Vol. 14 (1975) reports he was acquitted after the court found the alleged kidnapping never took place. [Source: The Black Panther (Black Panther Party newspaper), v14 no.1,10; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Shango", "state": "NY"}'

# Billy Dean Smith ()
php artisan prisoner:add '{"name": "Billy Dean Smith", "first_name": "Billy", "last_name": "Smith", "description": "Black U.S. Army private court-martialed for '\''fragging'\'' (the grenade killing of two white officers) at a Vietnam base, a prosecution the antiwar and Black movements rallied around; The Black Panther Vol. 14 no.9 (1975), in a Black-history note, records his 1972 acquittal after months of pretrial confinement. [Source: The Black Panther (Black Panther Party newspaper), v14 no.9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]"}'

# Carlos Feliciano (NY)
php artisan prisoner:add '{"name": "Carlos Feliciano", "first_name": "Carlos", "last_name": "Feliciano", "description": "Puerto Rican independence figure who, The Black Panther Vol. 14 no.4 (1975) reports, recently won his freedom from a bomb-plot frame-up; he joined the U.S. delegation to the international solidarity conference for Puerto Rican independence in Havana. [Source: The Black Panther (Black Panther Party newspaper), v14 no.4; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY", "affiliation": ["Puerto Rican independence movement"]}'

# Cheryl Todd (GA)
php artisan prisoner:add '{"name": "Cheryl Todd", "first_name": "Cheryl", "last_name": "Todd", "description": "Black Georgia woman charged with Dessie Woods in the June 1975 death of a white insurance salesman the two women said had kidnapped and sexually threatened them; The Black Panther Vol. 14 no.6 (1975) reports they were first falsely arrested for public drunkenness by the highway patrol. [Source: The Black Panther (Black Panther Party newspaper), v14 no.6; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "GA"}'

# Darryl King (NY)
php artisan prisoner:add '{"name": "Darryl King", "first_name": "Darryl", "last_name": "King", "description": "Black ex-serviceman arrested in 1970 and convicted of killing a New York policeman during a robbery, sentenced to 25 years to life; The Black Panther Vol. 14 no.1 (1975) reports he was beaten and identified through suggestive lineups, that a recanting witness admitted lying, and that his defense committee sought a new trial. [Source: The Black Panther (Black Panther Party newspaper), v14 no.1; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# David Rice (NE)
php artisan prisoner:add '{"name": "David Rice", "first_name": "David", "last_name": "Rice", "description": "Omaha activist (NCCF, the BPP'\''s affiliate) convicted in the 1970 bombing death of a policeman on the coerced testimony of a 16-year-old; The Black Panther Vol. 14 (1975) reports his politically motivated prosecution, the illegal search of his home, and his appeal. One of the '\''Omaha Two,'\'' he was imprisoned until his death in 2016. [Source: The Black Panther (Black Panther Party newspaper), v14 no.3,4; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Mondo we Langa", "state": "NE", "affiliation": ["National Committee to Combat Fascism"]}'

# DeWayne Williams (CA)
php artisan prisoner:add '{"name": "DeWayne Williams", "first_name": "DeWayne", "last_name": "Williams", "description": "Cal State Northridge student beaten by LAPD officers and then convicted, by an 11-white jury, of interfering with a police officer; The Black Panther Vol. 14 no.17 (1976) reports he faced up to a year in jail and set up an appeal fund, calling the arrest a racist frame-up. [Source: The Black Panther (Black Panther Party newspaper), v14 no.17; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Waheeb", "state": "CA"}'

# Dessie Woods (GA)
php artisan prisoner:add '{"name": "Dessie Woods", "first_name": "Dessie", "last_name": "Woods", "description": "Black Georgia woman charged, with Cheryl Todd, in the June 1975 death of a white insurance salesman whom the Woods-Todd Defense Committee says had kidnapped and tried to rape the two women; The Black Panther Vol. 14 no.6 (1975) reports she faced a possible death penalty and became a national self-defense cause. She was later convicted and imprisoned. [Source: The Black Panther (Black Panther Party newspaper), v14 no.6; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Dessie X. Woods", "state": "GA"}'

# Earnest Ball (AL)
php artisan prisoner:add '{"name": "Earnest Ball", "first_name": "Earnest", "last_name": "Ball", "description": "Alabama prisoner and Inmates For Action (IFA) activist convicted of murdering a policeman he says he shot in self-defense during a raid on his ex-wife'\''s home; The Black Panther Vol. 14 no.7 (1975) reports he was beaten, held in a refrigerated cell and denied medical care at Atmore-Holman, and had appealed to the U.S. Supreme Court. [Source: The Black Panther (Black Panther Party newspaper), v14 no.7; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "AL", "affiliation": ["Inmates For Action"]}'

# Elton Rankin (TX)
php artisan prisoner:add '{"name": "Elton Rankin", "first_name": "Elton", "last_name": "Rankin", "description": "Houston youth grazed by a bullet and beaten by police after a car chase, then charged with five counts of attempted capital murder of a police officer though he fired no shots; The Black Panther Vol. 14 no.26 (1976) presents the charges against the surviving youths as a frame-up. [Source: The Black Panther (Black Panther Party newspaper), v14 no.26; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "TX"}'

# Ernest Graham (CA)
php artisan prisoner:add '{"name": "Ernest Graham", "first_name": "Ernest", "last_name": "Graham", "description": "Black prison activist ('\''Shujaa'\'') charged with Eugene Allen in the 1973 death of a Tracy prison guard and facing a mandatory death sentence in what The Black Panther Vol. 14 (1976) calls a political frame-up; the two said prosecution witnesses were promised parole for their testimony. Graham was ultimately acquitted after repeated trials. [Source: The Black Panther (Black Panther Party newspaper), v14 no.29,30; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Shujaa", "state": "CA"}'

# Ethel Rosenberg (NY)
php artisan prisoner:add '{"name": "Ethel Rosenberg", "first_name": "Ethel", "last_name": "Rosenberg", "description": "Executed in 1953 with her husband Julius after conviction for conspiracy to commit espionage, in a case long protested as a political prosecution; The Black Panther Vol. 14 no.13 (1975) covers the release of the secret Rosenberg files. [Source: The Black Panther (Black Panther Party newspaper), v14 no.13; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Eugene Allen (CA)
php artisan prisoner:add '{"name": "Eugene Allen", "first_name": "Eugene", "last_name": "Allen", "description": "Young Black '\''life prisoner'\'' and prison activist charged, with Ernest Graham, in the 1973 killing of a guard at the Deuel Vocational Institution (Tracy) and facing a mandatory death sentence; The Black Panther Vol. 14 (1976) reports a first trial ended in a hung jury and that the two say they were scapegoated for being young, Black and political. [Source: The Black Panther (Black Panther Party newspaper), v14 no.29,30; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Federico Cintron Fiallo (PR)
php artisan prisoner:add '{"name": "Federico Cintron Fiallo", "first_name": "Federico", "last_name": "Fiallo", "description": "Executive secretary of Puerto Rico'\''s United Workers Movement (MOU) labor federation, arrested in Aug. 1975 by FBI and undercover agents on bank-robbery charges as he prepared to attend a solidarity conference in Havana; The Black Panther Vol. 14 no.6 (1975) reports his attorneys called it an attempt to cripple organized labor and the independence movement. [Source: The Black Panther (Black Panther Party newspaper), v14 no.6; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "PR", "affiliation": ["Puerto Rican independence movement"]}'

# Frank Gaskins (IL)
php artisan prisoner:add '{"name": "Frank Gaskins", "first_name": "Frank", "last_name": "Gaskins", "description": "Black prisoner held two and a half years in the Marion federal penitentiary'\''s behavior-modification unit, taken to St. Louis in Sept. 1975 to be arraigned on charges of assaulting four guards; The Black Panther Vol. 14 no.3 (1975) reports supporters called it a frame-up, since the handcuffed prisoner could not have assaulted four guards. [Source: The Black Panther (Black Panther Party newspaper), v14 no.3; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Comrade Ko-Jo", "state": "IL"}'

# Frank Shuford (CA)
php artisan prisoner:add '{"name": "Frank Shuford", "first_name": "Frank", "last_name": "Shuford", "description": "22-year-old Black community activist in Santa Ana convicted in a 1972 police frame-up of shooting two market clerks after he had organized against alcohol sales to minors; The Black Panther Vol. 14 no.2 (1975) reports his own attorney betrayed and testified against him, his first trial hung, and he drew a 30-year sentence and appealed. [Source: The Black Panther (Black Panther Party newspaper), v14 no.2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Frank Smith (NY)
php artisan prisoner:add '{"name": "Frank Smith", "first_name": "Frank", "last_name": "Smith", "description": "'\''Big Black,'\'' one of the '\''Attica Brothers'\'' leaders of the 1971 Attica rebellion; The Black Panther Vol. 14 no.10 (1975) reports that after murder charges were dropped he remained among 11 inmates charged with 34 counts of kidnapping for allegedly holding hostages. He was himself tortured during the retaking of the prison. [Source: The Black Panther (Black Panther Party newspaper), v14 no.10; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Big Black", "state": "NY"}'

# Freddie Pitts (FL)
php artisan prisoner:add '{"name": "Freddie Pitts", "first_name": "Freddie", "last_name": "Pitts", "description": "Black man who spent 12 years on Florida'\''s death row, convicted by an all-white jury of the 1963 murders of two white service-station operators — a crime another (white) man confessed to; The Black Panther Vol. 14 (1975) reports he and Wilbert Lee were freed and pardoned by Gov. Reubin Askew. [Source: The Black Panther (Black Panther Party newspaper), v14 no.1,2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "FL"}'

# Gamba Mani (AL)
php artisan prisoner:add '{"name": "Gamba Mani", "first_name": "Gamba", "last_name": "Mani", "description": "Chairman of the Alabama prison group Inmates For Action (IFA), repeatedly retried on charges arising from a January 1974 Atmore protest against beatings and segregation; The Black Panther Vol. 14 no.9 (1975) reports he sought to move his trial to federal court, arguing the state violated his rights by denying him William Kunstler as counsel. [Source: The Black Panther (Black Panther Party newspaper), v14 no.9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Oscar Johnson", "state": "AL", "affiliation": ["Inmates For Action"]}'

# Gerald Bernard Best (TX)
php artisan prisoner:add '{"name": "Gerald Bernard Best", "first_name": "Gerald", "last_name": "Best", "description": "18-year-old wounded when Houston police riddled a car with bullets, then charged with five counts of attempted capital murder of a police officer despite firing no shots (the gun had been thrown from the car before the chase); The Black Panther Vol. 14 no.26 (1976). [Source: The Black Panther (Black Panther Party newspaper), v14 no.26; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "TX"}'

# Henry Dee (IL)
php artisan prisoner:add '{"name": "Henry Dee", "first_name": "Henry", "last_name": "Dee", "description": "Chicago man convicted with James Sayles and sentenced to death (May 1972), then resentenced to two consecutive 220-to-440-year terms, for a murder he says he did not commit; The Black Panther Vol. 14 no.2 (1975) reports the Yaki Yakubu-Henry Dee Defense Fund'\''s plea for support. [Source: The Black Panther (Black Panther Party newspaper), v14 no.2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "IL"}'

# Herman Blyden (NY)
php artisan prisoner:add '{"name": "Herman Blyden", "first_name": "Herman", "last_name": "Blyden", "description": "One of the '\''Attica Brothers'\'' rebellion leaders charged with kidnapping and murder of hostages during the 1971 Attica uprising; The Black Panther Vol. 14 no.10 (1975) reports his indictments were dismissed for insufficient evidence. [Source: The Black Panther (Black Panther Party newspaper), v14 no.10; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Hosea Williams (GA)
php artisan prisoner:add '{"name": "Hosea Williams", "first_name": "Hosea", "last_name": "Williams", "description": "SCLC leader and Georgia state representative whom The Black Panther Vol. 14 no.7 (1975) reports the Fulton County DA was seeking to imprison and remove from the legislature via a felony charge over an alleged traffic violation; a National Defense Committee headed by Ralph Abernathy, Julian Bond and Dick Gregory formed. [Source: The Black Panther (Black Panther Party newspaper), v14 no.7; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "GA", "affiliation": ["SCLC"]}'

# Inez Garcia (CA)
php artisan prisoner:add '{"name": "Inez Garcia", "first_name": "Inez", "last_name": "Garcia", "description": "Young woman of Puerto Rican and Cuban descent convicted of second-degree murder for killing a man who helped rape her; The Black Panther Vol. 14 (1975-76) reports the California Court of Appeal overturned her five-years-to-life conviction and ordered a new trial, in a case that became a landmark of the women'\''s self-defense movement. [Source: The Black Panther (Black Panther Party newspaper), v14 no.17,19; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Irving Flores (PR)
php artisan prisoner:add '{"name": "Irving Flores", "first_name": "Irving", "last_name": "Flores", "description": "Puerto Rican Nationalist imprisoned 22 years for the March 1, 1954 armed protest at the U.S. Capitol; The Black Panther Vol. 14 (1976) names him (Irving Flores Rodriguez) among the longest-held political prisoners in the Western Hemisphere. [Source: The Black Panther (Black Panther Party newspaper), v14 no.26,28; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "PR", "affiliation": ["Puerto Rican Nationalist Party"]}'

# James Sayles (IL)
php artisan prisoner:add '{"name": "James Sayles", "first_name": "James", "last_name": "Sayles", "description": "Chicago man convicted with Henry Dee and sentenced to death (May 1972), then to two consecutive 220-to-440-year terms, in what supporters called a wrongful conviction; The Black Panther Vol. 14 no.2 (1975). Known as Yaki Yakubu, he became a New Afrikan liberation theorist. [Source: The Black Panther (Black Panther Party newspaper), v14 no.2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Yaki Yakubu", "state": "IL"}'

# Jim Grant (NC)
php artisan prisoner:add '{"name": "Jim Grant", "first_name": "Jim", "last_name": "Grant", "description": "Charlotte, N.C. civil-rights activist imprisoned in connection with the anti-racist school struggles of the period; The Black Panther Vol. 14 no.28 (1976) names him among the jailed Southern activists a national campaign sought to free. [Source: The Black Panther (Black Panther Party newspaper), v14 no.28; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NC"}'

# JoAnne Little (NC)
php artisan prisoner:add '{"name": "JoAnne Little", "first_name": "JoAnne", "last_name": "Little", "description": "Black North Carolina woman who killed a white jailer, Clarence Alligood, as he tried to rape her in her Beaufort County cell; The Black Panther Vol. 14 (1975) covers her historic 1975 acquittal on self-defense grounds after a massive national defense campaign, and the continuing Klan threats against her supporters. [Source: The Black Panther (Black Panther Party newspaper), v14 no.3,4,5,6,15; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NC"}'

# John Cluchette (CA)
php artisan prisoner:add '{"name": "John Cluchette", "first_name": "John", "last_name": "Cluchette", "description": "One of the three '\''Soledad Brothers,'\'' charged with George Jackson and Fleeta Drumgo in the 1970 death of a Soledad prison guard after a guard killed three Black inmates; The Black Panther Vol. 14 no.4 (1975) reports the three were found not guilty by an all-white jury in March 1972. [Source: The Black Panther (Black Panther Party newspaper), v14 no.4; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# John Hill (NY)
php artisan prisoner:add '{"name": "John Hill", "first_name": "John", "last_name": "Hill", "description": "Native American '\''Attica Brother'\'' (Dacajeweiah) who, The Black Panther Vol. 14 no.26 (1976) reports, was the only person imprisoned for an Attica-rebellion '\''crime'\'' — convicted of murdering a guard during the 1971 uprising and serving 20 years-to-life — even as the prosecutor recommended dropping all other inmate indictments. [Source: The Black Panther (Black Panther Party newspaper), v14 no.26; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Dacajeweiah", "state": "NY"}'

# Johnnie Harris (AL)
php artisan prisoner:add '{"name": "Johnnie Harris", "first_name": "Johnnie", "last_name": "Harris", "description": "One of the Atmore-Holman prisoners tried after the January 1974 Alabama prison rebellion; The Black Panther Vol. 14 (1975) reports he was convicted by an all-white jury of killing a guard and sentenced to death, and that his lawyers appealed on grounds of jury discrimination and the cruelty of the death penalty. [Source: The Black Panther (Black Panther Party newspaper), v14 no.4,9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Johnny Imani Harris", "state": "AL", "affiliation": ["Inmates For Action"]}'

# Jomo Joka Omowale (NY)
php artisan prisoner:add '{"name": "Jomo Joka Omowale", "first_name": "Jomo", "last_name": "Omowale", "description": "One of the '\''Attica Brothers,'\'' indicted after the September 1971 Attica prison rebellion; The Black Panther Vol. 14 (1975) reports he was shot five times in the back during the state'\''s retaking of the yard, then charged with the murder of a hostage in a case built on discredited witnesses. He ultimately pleaded to a token '\''coercion'\'' count for time served. [Source: The Black Panther (Black Panther Party newspaper), v14 no.1,5,6,12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Eric Thompson", "state": "NY"}'

# Julius Rosenberg (NY)
php artisan prisoner:add '{"name": "Julius Rosenberg", "first_name": "Julius", "last_name": "Rosenberg", "description": "Convicted of conspiracy to commit espionage for allegedly passing atomic secrets to the Soviet Union and executed with his wife Ethel in 1953 amid worldwide protest; The Black Panther Vol. 14 no.13 (1975) reports on the long-delayed release of the secret Rosenberg case files. [Source: The Black Panther (Black Panther Party newspaper), v14 no.13; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Larry Little (NC)
php artisan prisoner:add '{"name": "Larry Little", "first_name": "Larry", "last_name": "Little", "description": "Coordinator of the Winston-Salem Black Panther Party chapter and a target of FBI COINTELPRO forged-letter smears; The Black Panther Vol. 14 (1975) reports police raided the chapter headquarters and arrested him on trumped-up meat-truck robbery charges that were later dropped after the defense challenged the jury selection. [Source: The Black Panther (Black Panther Party newspaper), v14 no.5,15; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NC", "affiliation": ["Black Panther Party"]}'

# Lehman Brightman (CA)
php artisan prisoner:add '{"name": "Lehman Brightman", "first_name": "Lehman", "last_name": "Brightman", "description": "Leader of United Native Americans, Inc., charged with '\''harboring'\'' AIM leader Dennis Banks (the charges were later dropped) after 40 FBI agents armed with shotguns and M-16s surrounded his El Cerrito home hunting for Banks; The Black Panther Vol. 14 (1976). [Source: The Black Panther (Black Panther Party newspaper), v14 no.26,27; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA", "affiliation": ["United Native Americans"]}'

# Leonard Crow Dog (SD)
php artisan prisoner:add '{"name": "Leonard Crow Dog", "first_name": "Leonard", "last_name": "Dog", "description": "American Indian Movement spiritual leader whose Rosebud Reservation home was raided by some 80 FBI agents in Sept. 1975; The Black Panther Vol. 14 no.3 (1975) reports he was charged with assault with a deadly weapon and jailed in Pierre, one of the AIM figures the movement'\''s lawyers were working to free. [Source: The Black Panther (Black Panther Party newspaper), v14 no.3; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "SD", "affiliation": ["American Indian Movement"]}'

# Marvin Patrick (NC)
php artisan prisoner:add '{"name": "Marvin Patrick", "first_name": "Marvin", "last_name": "Patrick", "description": "One of the '\''Wilmington 10,'\'' convicted with Rev. Ben Chavis in the 1971 Wilmington, N.C. racial disturbances; The Black Panther Vol. 14 no.30 (1976) reports the group, serving a combined 282 years, faced intimidation in prison and sought immediate release. [Source: The Black Panther (Black Panther Party newspaper), v14 no.30; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NC"}'

# Michael ZinZun (CA)
php artisan prisoner:add '{"name": "Michael ZinZun", "first_name": "Michael", "last_name": "ZinZun", "description": "Black Southern California community activist described by The Black Panther Vol. 14 no.4 (1975) as facing trumped-up assault charges amid a conference exposing police repression; he later co-founded the Coalition Against Police Abuse. [Source: The Black Panther (Black Panther Party newspaper), v14 no.4; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Morris White (WA)
php artisan prisoner:add '{"name": "Morris White", "first_name": "Morris", "last_name": "White", "description": "Seattle Black Panther Party member arrested and charged with false solicitation, disorderly conduct and resisting arrest while selling The Black Panther and running the Free Breakfast program; The Black Panther Vol. 14 no.19 (1976) reports the charges were cleared on appeal after an officer admitted arresting him to make him change his soliciting. [Source: The Black Panther (Black Panther Party newspaper), v14 no.19; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "WA", "affiliation": ["Black Panther Party"]}'

# Olga Talamante (CA)
php artisan prisoner:add '{"name": "Olga Talamante", "first_name": "Olga", "last_name": "Talamante", "description": "UC Santa Cruz graduate from Gilroy, California, imprisoned 16 months in Argentina on false charges of political subversion and tortured with cattle prods until she signed a confession; The Black Panther Vol. 14 no.30 (1976) reports her release and return home after a Bay Area defense campaign. [Source: The Black Panther (Black Panther Party newspaper), v14 no.30; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Ormistan Spencer (NY)
php artisan prisoner:add '{"name": "Ormistan Spencer", "first_name": "Ormistan", "last_name": "Spencer", "description": "Rosedale, Queens man arrested and charged with reckless endangerment and weapons offenses after defending his family'\''s home from a racist mob that had repeatedly firebombed it; The Black Panther Vol. 14 no.7 (1975) reports police arrested him rather than the attackers and a rally demanded the charges be dropped. [Source: The Black Panther (Black Panther Party newspaper), v14 no.7; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Tony Spencer", "state": "NY"}'

# Oscar Collazo (PR)
php artisan prisoner:add '{"name": "Oscar Collazo", "first_name": "Oscar", "last_name": "Collazo", "description": "Puerto Rican Nationalist imprisoned about 25 years for the 1950 armed attack on Blair House; The Black Panther Vol. 14 (1976) describes him, held at Leavenworth, as among the longest-held political prisoners in the Western Hemisphere, with the PSP campaigning for the nationalists'\'' unconditional release. [Source: The Black Panther (Black Panther Party newspaper), v14 no.26,28; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "PR", "affiliation": ["Puerto Rican Nationalist Party"]}'

# Philip Allen (CA)
php artisan prisoner:add '{"name": "Philip Allen", "first_name": "Philip", "last_name": "Allen", "description": "Young Black Los Angeles college student convicted in what The Black Panther Vol. 14 (1975) calls a police-murder frame-up; the paper reports his appeal-bond was revoked after he spoke at rallies for himself and the San Quentin 6, and that the ACLU entered his case. [Source: The Black Panther (Black Panther Party newspaper), v14 no.4,9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Rafael Cancel Miranda (PR)
php artisan prisoner:add '{"name": "Rafael Cancel Miranda", "first_name": "Rafael", "last_name": "Miranda", "description": "Puerto Rican Nationalist imprisoned 22 years for the March 1, 1954 armed protest at the U.S. Capitol; The Black Panther Vol. 14 (1976) names him among the longest-held political prisoners in the Western Hemisphere. [Source: The Black Panther (Black Panther Party newspaper), v14 no.26,28; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "PR", "affiliation": ["Puerto Rican Nationalist Party"]}'

# Raymond Sumter (NY)
php artisan prisoner:add '{"name": "Raymond Sumter", "first_name": "Raymond", "last_name": "Sumter", "description": "One of the '\''Attica Brothers'\'' whose kidnapping/unlawful-imprisonment charges from the 1971 rebellion were dropped by New York State; The Black Panther Vol. 14 no.12 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Fish Samabi", "state": "NY"}'

# Robert F. Williams (NC)
php artisan prisoner:add '{"name": "Robert F. Williams", "first_name": "Robert", "last_name": "Williams", "description": "Former Monroe, N.C. NAACP president and pioneer of armed Black self-defense (author of '\''Negroes with Guns'\''), who spent years in exile over 1961 '\''kidnapping'\'' charges he called an FBI-driven frame-up; The Black Panther Vol. 14 (1975-76) reports the Michigan Supreme Court refused to extradite him as he returned to face the charges. [Source: The Black Panther (Black Panther Party newspaper), v14 no.13,16; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NC"}'

# Roger Champen (NY)
php artisan prisoner:add '{"name": "Roger Champen", "first_name": "Roger", "last_name": "Champen", "description": "One of the '\''Attica Brothers'\'' leaders of the 1971 Attica rebellion; The Black Panther Vol. 14 no.10 (1975) reports that after murder charges were dropped he remained among 11 inmates charged with 34 counts of kidnapping. [Source: The Black Panther (Black Panther Party newspaper), v14 no.10; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Rommie Loudd (FL)
php artisan prisoner:add '{"name": "Rommie Loudd", "first_name": "Rommie", "last_name": "Loudd", "description": "Pro football'\''s first Black owner (of the WFL'\''s Florida Blazers), jailed in Orlando on drug and embezzlement charges under a bond he could not pay; The Black Panther Vol. 14 no.21 (1976) reports his lawyer and Black Sports magazine called it a racist plot to drive him out of the business. [Source: The Black Panther (Black Panther Party newspaper), v14 no.21; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "FL"}'

# Ronald Lyons (NY)
php artisan prisoner:add '{"name": "Ronald Lyons", "first_name": "Ronald", "last_name": "Lyons", "description": "One of the '\''Attica Brothers'\'' whose kidnapping/unlawful-imprisonment charges from the 1971 rebellion were dismissed before trial; The Black Panther Vol. 14 no.12 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "NY"}'

# Roy Lee Patterson (GA)
php artisan prisoner:add '{"name": "Roy Lee Patterson", "first_name": "Roy", "last_name": "Patterson", "description": "25-year-old Black Marine sergeant sentenced to natural life by a majority-white Cordele, Georgia jury for the shooting deaths of a state trooper and a policeman after a trooper attacked him, his wife and baby; The Black Panther Vol. 14 no.12 (1975) reports he was denied defense funds and that the Southern Poverty Law Center was appealing. [Source: The Black Panther (Black Panther Party newspaper), v14 no.12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "GA"}'

# Sarah Bad Heart Bull (SD)
php artisan prisoner:add '{"name": "Sarah Bad Heart Bull", "first_name": "Sarah", "last_name": "Bull", "description": "Mother of a slain Sioux youth who was choked and beaten by a state trooper when she was denied entry to the 1973 Custer, S.D. courthouse; The Black Panther Vol. 14 no.27 (1976) reports she was sentenced to one-to-three years and served six months while her son'\''s white killer got probation. [Source: The Black Panther (Black Panther Party newspaper), v14 no.27; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "SD", "affiliation": ["American Indian Movement"]}'

# Terry Phillips (CA)
php artisan prisoner:add '{"name": "Terry Phillips", "first_name": "Terry", "last_name": "Phillips", "description": "White Panther Party member convicted with Tom Stevens and sentenced to 5½ years-to-life over the July 1974 police raid on the party'\''s San Francisco food-program office; The Black Panther Vol. 14 (1975) reports a 5,000-signature petition demanded an appeal bond. [Source: The Black Panther (Black Panther Party newspaper), v14 no.17,20; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA", "affiliation": ["White Panther Party"]}'

# Tom Stevens (CA)
php artisan prisoner:add '{"name": "Tom Stevens", "first_name": "Tom", "last_name": "Stevens", "description": "White Panther Party member sentenced to 5½ years-to-life for assault with a deadly weapon after firing warning shots during a July 1974 San Francisco police raid on the party'\''s Page Street food-program office (which police then set afire); The Black Panther Vol. 14 (1975) reports he was denied bail pending appeal in what supporters called a trumped-up prosecution. [Source: The Black Panther (Black Panther Party newspaper), v14 no.17,20; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA", "affiliation": ["White Panther Party"]}'

# Vernon Benton (TX)
php artisan prisoner:add '{"name": "Vernon Benton", "first_name": "Vernon", "last_name": "Benton", "description": "Black Panther Party member held at the Harris County Rehabilitation Center in Houston after a July 1974 police frame-up on unsolved robbery charges; The Black Panther Vol. 14 (1975) reports his life was threatened and that he survived an administration-instigated assault by '\''building tenders'\'' before being put in solitary. [Source: The Black Panther (Black Panther Party newspaper), v14 no.3,4,6,16; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "T.C. Benton", "state": "TX", "affiliation": ["Black Panther Party"]}'

# Wesley Robert Wells (CA)
php artisan prisoner:add '{"name": "Wesley Robert Wells", "first_name": "Wesley", "last_name": "Wells", "description": "California'\''s longest-held prisoner, who spent 47 of his 66 years behind bars — including years on San Quentin'\''s death row after a 1944 death sentence for throwing a spittoon at a guard — before his sentence was commuted and he was released in 1974; The Black Panther Vol. 14 no.19 (1976) honored him on his death, calling him a prison-movement pioneer. [Source: The Black Panther (Black Panther Party newspaper), v14 no.19; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "CA"}'

# Wilbert Lee (FL)
php artisan prisoner:add '{"name": "Wilbert Lee", "first_name": "Wilbert", "last_name": "Lee", "description": "Imprisoned 12 years with Freddie Pitts for the 1963 Florida service-station murders another man confessed to; convicted by an all-white jury and sentenced to death before being pardoned by Gov. Askew; The Black Panther Vol. 14 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.1,2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "FL"}'

# William Ortiz (NY)
php artisan prisoner:add '{"name": "William Ortiz", "first_name": "William", "last_name": "Ortiz", "description": "One of the '\''Attica Brothers'\'' whose kidnapping and unlawful-imprisonment charges from the 1971 rebellion were dismissed as prosecutors conceded insufficient evidence; The Black Panther Vol. 14 no.12 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.12; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "aka": "Toriano", "state": "NY"}'

# Willie Burnett (KY)
php artisan prisoner:add '{"name": "Willie Burnett", "first_name": "Willie", "last_name": "Burnett", "description": "Black Kentucky man convicted in 1974 and sentenced to life without parole for the rape of a white woman he says he did not commit; The Black Panther Vol. 14 no.9 (1975) reports the state appeals court overturned the conviction for insufficient evidence and freed him on bond, and that he refused to plea-bargain. [Source: The Black Panther (Black Panther Party newspaper), v14 no.9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "KY"}'

# Yvonne Wanrow (WA)
php artisan prisoner:add '{"name": "Yvonne Wanrow", "first_name": "Yvonne", "last_name": "Wanrow", "description": "Colville Indian mother sentenced to up to 25 years for the self-defense shooting of a white convicted child molester who had assaulted her children; The Black Panther Vol. 14 no.15 (1975) reports an all-white jury convicted her after the man'\''s record was ruled inadmissible, and that her landmark conviction was overturned on appeal. [Source: The Black Panther (Black Panther Party newspaper), v14 no.15; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "state": "WA"}'

# ===== GROUP B -- INTERNATIONAL, commented out (9) =====
# NPPC is a U.S. (National) coalition; these foreign cases (Congo, Rhodesia/Zimbabwe, Chile,
# Dominica, U.K.) are left commented for you to include or skip.

# Anthony Munroe (United Kingdom)
# php artisan prisoner:add '{"name": "Anthony Munroe", "first_name": "Anthony", "last_name": "Munroe", "description": "One of the London '\''Spaghetti House Three,'\'' Black Power activists who withstood a week-long police siege in 1975; The Black Panther Vol. 14 no.20 (1976) reports their defense committee insisted they were political activists in Britain'\''s Black movement, not common criminals. [Source: The Black Panther (Black Panther Party newspaper), v14 no.20; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["Black Liberation Front"]}'

# Desmond Trotter (Dominica)
# php artisan prisoner:add '{"name": "Desmond Trotter", "first_name": "Desmond", "last_name": "Trotter", "description": "22-year-old radical journalist and leader of the Black revolutionary group the Dreads, falsely convicted of the 1974 murder of a white American tourist and facing execution; The Black Panther Vol. 14 no.29 (1976) reports the British Privy Council refused to review his case as activists campaigned to save his life. [Source: The Black Panther (Black Panther Party newspaper), v14 no.29; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["The Dreads"]}'

# Edson Sithole (Rhodesia)
# php artisan prisoner:add '{"name": "Edson Sithole", "first_name": "Edson", "last_name": "Sithole", "description": "Publicity secretary of the African National Council of Rhodesia, kidnapped with his secretary in Salisbury in Oct. 1975 in what trade unionists called a '\''gangster act'\'' by the Ian Smith regime; The Black Panther Vol. 14 no.9 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["African National Council"]}'

# Frank Davies (United Kingdom)
# php artisan prisoner:add '{"name": "Frank Davies", "first_name": "Frank", "last_name": "Davies", "description": "One of the London '\''Spaghetti House Three'\''; The Black Panther Vol. 14 no.20 (1976) describes him as a Black Power activist active in Black Liberation Front community projects whom police wrongly portrayed as a criminal. [Source: The Black Panther (Black Panther Party newspaper), v14 no.20; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["Black Liberation Front"]}'

# Herbert Chitepo (Zimbabwe)
# php artisan prisoner:add '{"name": "Herbert Chitepo", "first_name": "Herbert", "last_name": "Chitepo", "description": "Chairman of the Zimbabwe African National Union (ZANU), assassinated by car bombing in Zambia in March 1975 amid the liberation struggle; The Black Panther Vol. 14 no.16 (1976) reports other ZANU leaders were arrested and detained. [Source: The Black Panther (Black Panther Party newspaper), v14 no.16; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["Zimbabwe African National Union"]}'

# Miriam Mhlango (Rhodesia)
# php artisan prisoner:add '{"name": "Miriam Mhlango", "first_name": "Miriam", "last_name": "Mhlango", "description": "Secretary to African National Council official Edson Sithole, kidnapped alongside him in Salisbury in Oct. 1975 by the Rhodesian regime; The Black Panther Vol. 14 no.9 (1975). [Source: The Black Panther (Black Panther Party newspaper), v14 no.9; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["African National Council"]}'

# Patrice Lumumba (Congo)
# php artisan prisoner:add '{"name": "Patrice Lumumba", "first_name": "Patrice", "last_name": "Lumumba", "description": "First elected prime minister of the Congo, deposed with CIA backing in 1960, taken prisoner and killed in 1961; The Black Panther Vol. 14 no.2 (1975) reports the U.S. Senate Select Committee'\''s revelation of a CIA plot to poison him. [Source: The Black Panther (Black Panther Party newspaper), v14 no.2; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]"}'

# Sheila Cassidy (Chile)
# php artisan prisoner:add '{"name": "Sheila Cassidy", "first_name": "Sheila", "last_name": "Cassidy", "description": "British surgeon held nearly two months as a political prisoner by Chile'\''s junta after she treated a wounded revolutionary; The Black Panther Vol. 14 no.18 (1976) reports she was stripped, given severe electric shocks and held in solitary before her release. [Source: The Black Panther (Black Panther Party newspaper), v14 no.18; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]"}'

# Westley Dick (United Kingdom)
# php artisan prisoner:add '{"name": "Westley Dick", "first_name": "Westley", "last_name": "Dick", "description": "One of the London '\''Spaghetti House Three'\''; The Black Panther Vol. 14 no.20 (1976) describes him as a Black Power activist involved in educational and cultural projects who represented Britain'\''s Black movement at a Pan-African Congress in Tanzania. [Source: The Black Panther (Black Panther Party newspaper), v14 no.20; digitized at marxists.org — https://www.marxists.org/history/usa/pubs/black-panther/index.htm]", "affiliation": ["Black Liberation Front"]}'

