<?php

declare(strict_types=1);

/**
 * Bulk-add Part 2 of the Summer 2020 / George Floyd uprising
 * defendants from the user-supplied 200-row spreadsheet (rows 101-200).
 *
 * Skipped here:
 *   - Raekwon Dac Blankenship (already in the live DB).
 *
 * Per the dataset, several rows have a sentence of 0 months because
 * the case was dismissed, dropped, or "charged but not tried" — the
 * prisoner record is still created (the charge happened) but
 * incarceration_date and release_date are left null and the sentence
 * text reflects the disposition.
 *
 * Idempotent — Prisoner is matched by name and skipped if it exists.
 */

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Prisoner;
use App\Models\PrisonerCase;
use App\Models\Institution;
use Carbon\Carbon;

// Tab-separated columns:
// name | first | last | aka | state | city | age | race | gender | arrest_date(Y-m-d) | sentence_months | jurisdiction(Federal|Non-Federal) | charges | narrative | extra_ideologies (comma-sep, optional) | extra_affiliations (comma-sep, optional) | disposition (optional: dismissed|dropped|nottried)
$DATA = <<<'TSV'
Alejandro Avalos	Alejandro	Avalos		Nevada	Las Vegas	28	Latino	Male	2020-05-30	21	Federal	18 U.S.C. § 1361 and § 2 — Depredation against property of the United States and aiding and abetting.	Alejandro Avalos, 28, was charged with depredation against U.S. property after a May 30, 2020 demonstration in Las Vegas, NV decrying George Floyd's death. As the night progressed protesters faced off against officers; some vandalized buildings and threw bottles, fireworks, and rocks; others gathered at the federal building and threw items to gain entry. A federal security guard was threatened. Sentenced to 21 months federal prison plus 2 years supervised release and $71,335.72 restitution.
Lateesha Richards	Lateesha	Richards	Lateesha Kahryn Ritchards	Utah	Salt Lake City	24	Black	Female	2020-05-30	20	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Lateesha Richards, 24, of Salt Lake City was charged as a fourth person in the burning of a Salt Lake police car during the violent demonstration over the death of George Floyd in May 2020. Sentenced to 20 months federal prison.
Desmond David-Pitts	Desmond	David-Pitts		Washington	Seattle	19	Black	Male	2020-08-24	20	Federal	18 U.S.C. § 844(f) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson.	On August 24, 2020 Desmond David-Pitts, 19, allegedly set fire to the Seattle Police Department East Precinct. He had flown from Alaska to Seattle three days earlier to participate in protests because his younger brother had been killed by police after being pulled over for a traffic stop. Surveillance video captured him piling trash against the sally-port door over 11 minutes, repeatedly lighting it and feeding the flames. While he was setting fires, others were attempting to disable the door with crowbars and cement-like materials. He was identified by his distinctive pink camouflage trousers. Sentenced to 20 months federal prison.
Brendan Hunt	Brendan	Hunt	X-Ray Ultra	New York	Ridgewood, Queens	37	White	Male	2021-01-08	19	Federal	18 U.S.C. § 115(a)(1)(B) — Threat to murder U.S. officials.	On January 18, 2021 Brendan Hunt, 37, was arrested in Queens, NY for threatening to murder United States officials. He was pursued by the FBI's New York Joint Terrorism Task Force following a January 8, 2021 video he posted calling for an effort to "go back to the U.S. Capitol when all of the Senators and a lot of the Representatives are back there, and this time we have to show up with our guns. And we need to slaughter these motherfuckers" in order to "take America back". Sentenced to 19 months federal prison.
Adrian Wood	Adrian	Wood		Delaware	Wilmington	21	Unknown	Male	2020-06-15	18	Federal	18 U.S.C. § 231(a)(3) — Interfering with law enforcement.	Adrian Wood, 21, was charged with one count of civil disorder in Wilmington, DE. Wood threw a brick through the back window of an occupied Wilmington police cruiser during an evening of protests and looting in the city's downtown area. Sentenced to time served (~18.6 months between arrest June 15, 2020 and judgment January 3, 2022).
Kenyatta Sheire Huggins	Kenyatta Sheire	Huggins		Louisiana	Baton Rouge	22	Black	Female	2020-05-31	18	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson affecting interstate commerce; 18 U.S.C. § 844(i) — Arson affecting interstate commerce (4 counts).	From May 31 to June 1, 2020 in Baton Rouge, LA, Kenyatta Sheire Huggins, 22, was charged with co-defendants Terry Dorsey and Shamyrin Johnson with conspiracy to maliciously damage by fire buildings used in interstate commerce. Four separate fires occurred at Tai Industries, AutoZone, Tiger Tire Shop, and AAA Tire Shop. Surveillance footage identified Dorsey, who admitted to starting the fires with Huggins and Johnson. Their motive related to anti-police tensions: Dorsey said he was "angry about what was going on and wanted to attack who was attacking us." Sentenced to 18 months federal prison.
Terry Lemond Dorsey	Terry Lemond	Dorsey		Louisiana	Baton Rouge	21	Black	Male	2020-05-31	18	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson affecting interstate commerce (4 counts).	Terry Lemond Dorsey, 21, was charged in Baton Rouge, LA with co-defendants Kenyatta Huggins and Shamyrin Johnson for the May 31 - June 1, 2020 arsons at four area businesses. He admitted to starting the fires; the motive related to anti-police tensions: he said he was "angry about what was going on and wanted to attack who was attacking us." Sentenced to 18 months federal prison.
Shamyrin Djhodi Johnson	Shamyrin Djhodi	Johnson		Louisiana	Baton Rouge	22	Black	Male	2020-05-31	18	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson affecting interstate commerce (4 counts).	Shamyrin Djhodi Johnson, 22, was charged in Baton Rouge, LA with co-defendants Terry Dorsey and Kenyatta Huggins for the May 31 - June 1, 2020 arsons at Tai Industries, AutoZone, Tiger Tire Shop, and AAA Tire Shop. Sentenced to 18 months federal prison.
Jeremy Trapp	Jeremy	Trapp		New York	Brooklyn	24	White	Male	2020-07-17	18	Federal	18 U.S.C. § 33 — Destruction of motor vehicles or motor vehicle facilities.	On July 17, 2020 Jeremy Trapp, 24, was observed by an informant and NYPD officers attempting to cut the brake line of an NYPD van. He had been communicating with an undercover informant about wanting to cut brake lines on police vehicles, and participated in reconnaissance for a bridge he expressed wanting to set on fire — saying current protests weren't violent enough. He stated he wanted to harm police officers and supporters because they were racist and wanted to burn the bridge so that "white supremacists could not use it to get to Brooklyn from Staten Island." Sentenced to 18 months federal prison.
Jordan Coyne	Jordan	Coyne		Pennsylvania	Pittsburgh	25	Latino	Male	2020-05-30	18	Federal	18 U.S.C. § 2 and § 231(a)(3) — Obstruction of law enforcement during civil disorder.	On May 30, 2020 Jordan Coyne, 25, threw multiple pieces of concrete at a vehicle occupied by Pittsburgh police officers. He was caught on video throwing rocks, bricks, pieces of concrete, and a tear gas canister at officers; the canister struck an officer in the hand, causing the officer's thumb to bleed and swell. Sentenced to 18 months federal prison.
Marcello Earle Woods	Marcello Earle	Woods		South Carolina	Columbia	28	Black	Male	2020-05-30	18	Federal	18 U.S.C. § 844(f) and § 2 — Damaging government property by fire.	Marcello Woods, 28, of Columbia, SC was charged with destroying a Columbia Police Department vehicle by fire for riot-related conduct on May 30, 2020. Sentenced to 18 months federal prison.
Abraham Elijah Jenkins	Abraham Elijah	Jenkins	AJ	South Carolina	Charleston	26	Black	Male	2020-05-30	18	Federal	18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 231(a)(3) — Obstruction of law enforcement during civil disorder.	Abraham Jenkins, 26, of Charleston, SC pled guilty to civil disorder charges related to the violence and destruction on May 30, 2020. Sentenced to 18 months federal prison plus 36 months supervised release.
Emily Nowlin	Emily	Nowlin		Arkansas	Little Rock	27	Unknown	Female	2020-08-25	18	Federal	18 U.S.C. § 844(f) — Malicious destruction of property belonging to a federally-funded entity; 18 U.S.C. § 844(n) — Conspiracy; 26 U.S.C. § 5861(d) — Possession of destructive devices.	Emily Nowlin, 27, of Little Rock, AR was charged with co-defendants Brittany Jeffrey, Renea Goddard, Aline Espinosa-Villegas, and Mujera Lung'aho for fire bombings of police vehicles in Little Rock and North Little Rock in August 2020. On August 25, 2020 protestors held a demonstration at the Little Rock PD 12th Street Substation; the next morning officers saw two glass bottles smelling of gasoline (Molotov cocktails) consistent with surveillance footage of two individuals near the parking lot. The Molotovs were assembled at Brittany Jeffrey's residence. On August 28 an Arkansas State Police vehicle was burned at headquarters. Sentenced to 18 months federal prison plus $35,956.31 restitution.	Antifa
Renea Goddard	Renea	Goddard		Arkansas	Little Rock	22	Asian	Female	2020-08-25	18	Federal	18 U.S.C. § 844(f) — Malicious destruction; § 844(n) — Conspiracy; 26 U.S.C. § 5861(d) — Possession of destructive devices.	Renea Goddard, 22, of Little Rock, AR was charged in conspiracy with Brittany Jeffrey, Emily Nowlin, Aline Espinosa-Villegas, and Mujera Lung'aho for the August 2020 firebombings of Little Rock and North Little Rock police vehicles, including the August 28 burning of an Arkansas State Police vehicle at headquarters. Cell-site data placed her cell phone at the State Police HQ on August 28. Sentenced to 18 months federal prison plus $35,956.31 restitution.	Antifa
Aline A. Espinosa-Villegas	Aline	Espinosa-Villegas	Loba Espinoza-Villegas	Arkansas	Little Rock	24	Latino	Male	2020-08-25	18	Federal	18 U.S.C. § 844(f) — Malicious destruction; § 844(n) — Conspiracy; 26 U.S.C. § 5861(d) — Possession of destructive devices.	Aline A. Espinosa-Villegas, 24, of Little Rock, AR was charged in conspiracy with Brittany Jeffrey, Emily Nowlin, Renea Goddard, and Mujera Lung'aho for the August 2020 firebombings of Little Rock and North Little Rock police vehicles. Sentenced to 18 months federal prison plus $34,356.31 restitution.	Antifa
Dashun Martin	Dashun	Martin		Georgia	Gainesville	23	Black	Male	2020-05-30	17	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Dashun Martin, 23, was indicted in Gainesville, GA in June 2020 with co-defendants Smallwood, Waller, Thompson, and Bailey for conspiring to commit and committing arson of a police car after a protest sparked by George Floyd's death. The defendants allegedly sought out and burned the police vehicle using the protests as cover. Sentenced to 17 months federal prison plus 3 years supervised release and $3,678.17 restitution.
Brittany Dawn Jeffrey	Brittany Dawn	Jeffrey	Dawn	Arkansas	Little Rock	31	Black	Female	2020-08-25	17	Federal	18 U.S.C. § 844(f) — Malicious destruction; § 844(n) — Conspiracy; 26 U.S.C. § 5861(d) — Possession of destructive devices.	Brittany Dawn Jeffrey, 31, of Little Rock, AR was the alleged organizer in the August 2020 conspiracy to firebomb Little Rock police vehicles; the Molotov cocktails were assembled at her residence. She was charged alongside Emily Nowlin, Renea Goddard, Aline Espinosa-Villegas, and Mujera Lung'aho. Sentenced to 17 months federal prison plus $529.30 restitution.	Antifa
Miguel Ramos	Miguel	Ramos		New York	Rochester	26	Black	Male	2020-05-30	16	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	Miguel Ramos, 26, was charged with co-defendant Dyshika McFadden for using an aerosol can and open flame to set fire to a Rochester Police Department vehicle during the May 30, 2020 demonstrations in Rochester, NY. The destroyed RPD car was broadcast and recorded on Facebook Live in real-time. Ramos took photos of himself at the riot and sent them to others by text to encourage further participation. Convicted of rioting February 24, 2022; sentenced to 16 months federal prison plus $4,287 restitution.
Jacob D. Little	Jacob D.	Little		Washington	Seattle	24	White	Male	2020-05-30	16	Federal	18 U.S.C. § 922(j) — Possession of a stolen firearm.	Jacob D. Little, 24, was charged with possession of a stolen firearm — accused of stealing a Colt M4 rifle with suppressor from a Seattle Police patrol car during a riot-declared protest in downtown Seattle on May 30, 2020. Officers with the SPD photo unit abandoned their patrol vehicle when they were overwhelmed by protesters and took refuge in nearby Nordstrom. Among other equipment, five firearms disappeared from police vehicles. Sentenced to 16 months federal prison plus 3 years supervised release and $4,446.12 restitution.
Preston Huteson	Preston	Huteson	Preston Alookhai Huteson	California	Los Angeles	30	Black	Male	2020-06-01	16	Non-Federal	Cal. Penal Code § 463(a) — Looting; § 496(a) — Receipt of stolen property.	On June 1, 2020 Preston Huteson, 30, of Pasadena, CA was arrested in Compton, Los Angeles by the "Safe LA Task Force" after the George Floyd Protests. He was charged with looting; pled "no contest" to an amended count of receipt of stolen property. Sentenced to 16 months county jail; currently held in a federal California prison for other charges.
Edward Thomas Schinzing	Edward Thomas	Schinzing		Oregon	Portland	32	White	Male	2020-05-29	15	Federal	18 U.S.C. § 844(f)(1) — Damaging government property by fire.	Edward Thomas Schinzing, 32, was charged with using fire to maliciously damage the Justice Center in downtown Portland, OR on May 29, 2020. Approximately 30 individuals entered the Justice Center through broken windows; they spray-painted the office, damaged computers and office equipment, and started fires. Schinzing was identified by comparison with a jail booking photo and a distinctive tattoo of his last name across his upper back. Sentenced to 15 months federal prison plus 3 years supervised release.
Alexander Charles Pridgen	Alexander Charles	Pridgen		North Carolina	Greenville	18	White	Male	2020-05-31	15	Federal	18 U.S.C. § 1361 — Destruction of government property; 18 U.S.C. § 922(n) — Receipt of a firearm while under felony indictment.	Alexander Pridgen, 18, of Greenville, NC was charged with willfully damaging government property during a demonstration over George Floyd's death. On May 31, 2020 he picked up a brick and hurled it through a ground floor window of the federal bankruptcy court at 150 Reade Circle in Greenville. The vandalism was captured on a peaceful protester's Facebook Live. Officers identified him from his involvement in another act of vandalism at the Greenville Police Station the same evening, captured on surveillance. Sentenced to 15 months federal prison.
Peter James Yeager	Peter James	Yeager		Washington	Spokane	45	White	Male	2020-12-09	15	Federal	18 U.S.C. § 844(i) — Damage by fire to a building used in interstate commerce.	Peter James Yeager, 45, of Grand Coulee, WA, a Marine Corps veteran, was indicted in connection with arson at the Teamsters Building in Spokane, WA. On December 9, 2020 he drove to Spokane with a preconceived plan to burn down the Spokane County Democrats office at 1912 N. Division Street. He entered the building and told multiple individuals he had a "bomb" — though investigators determined the items he carried did not constitute a completed device. The federal trial judge found him not guilty by reason of insanity (released March 2024).	Anti-Democratic Party
Urooj Rahman	Urooj	Rahman		New York	Brooklyn	31	Asian	Female	2020-05-31	15	Federal	18 U.S.C. § 844(f)(1), § 844(i), § 844(h)(1), § 844(n) — Use/conspiracy of explosives, arson; § 924(c)(l)(B)(ii) — Use of a destructive device; § 231(a)(3) — Civil disorder; 26 U.S.C. § 5861(d), (f) — Possessing/making a destructive device.	Urooj Rahman, 31, of Brooklyn, NY (an attorney at the time of arrest) was arrested on May 31, 2020 with co-defendant Colinford Mattis after attempts to use Molotov cocktails to damage NYPD vehicles during George Floyd protests. They pleaded guilty under a federal plea agreement. Sentenced to 15 months federal prison plus 2 years probation and $30,137 restitution.
Bruce Thompson	Bruce	Thompson		Georgia	Gainesville	22	Black	Male	2020-05-30	14	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Bruce Thompson, 22, was indicted in Gainesville, GA in June 2020 with co-defendants Smallwood, Waller, Bailey, and Martin for conspiring to commit and committing arson of a police car during a protest sparked by George Floyd's death. Sentenced to 14 months federal prison plus 3 years supervised release and $3,678.17 restitution.
Latroi Devon Newbins	Latroi Devon	Newbins		Utah	Salt Lake City	28	Black	Male	2020-05-30	13	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Latroi Devon Newbins, 28, of Salt Lake City was charged with arson in interstate commerce after the May 30, 2020 protests in Salt Lake City over George Floyd's death. He was seen running toward a police car that had been lit on fire and throwing combustible material into the flames as kindling, increasing them. Sentenced to 13 months federal prison.
Christopher Isidro Rojas	Christopher Isidro	Rojas		Utah	Salt Lake City	28	Latino	Male	2020-05-30	13	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	On May 30, 2020 Christopher Isidro Rojas, 28, was involved in the burning of a Salt Lake City Police Department patrol car in downtown SLC. Video shows him using a cigarette lighter to ignite a piece of fabric, which he threw toward an overturned police car; it landed partially in the interior. He said on video, "I put the cop car on fire. It didn't blow up." Sentenced to 13 months federal prison.
Dontario J. Stephens	Dontario J.	Stephens		Florida	Tampa	27	Black	Male	2020-05-30	13	Non-Federal	Fla. Stat. § 810.02(1)(b)(4)(a) — Burglary of an unoccupied structure during state of emergency; § 812.014(2)(c)(3) — Grand theft.	Dontario J. Stephens, 27, of Tampa, FL was charged with grand theft and burglary during a state of emergency following his participation in a Black Lives Matter protest over Memorial Day weekend 2020. Stephens allegedly took $50,000 worth of property from a local Gold N Diamond store. Pled guilty to reduced charges; sentenced to 13 months in Florida state prison.
George Allen	George	Allen		Pennsylvania	Pittsburgh	31	Black	Male	2020-05-30	12	Federal	18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 231(a)(3) — Civil disorder.	George Allen, 31, of Pittsburgh, PA was charged with one count of obstruction of law enforcement during civil disorder. On May 30, 2020 he caused damage to a police officer's vehicle by throwing a projectile through the front passenger window of the vehicle. Sentenced to 12 months federal prison plus 3 years supervised release.
Mackenzie Drechsler	Mackenzie	Drechsler		New York	Rochester	19	Biracial	Female	2020-05-30	12	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	Mackenzie Drechsler, 19, of Ontario, NY, was charged with arson for her alleged role in burning two vehicles — one belonging to the New York State Attorney General's Office and one belonging to the City of Rochester Family Crisis Intervention Team — both parked in the vicinity of 144 Exchange Boulevard in Rochester on May 30, 2020. Sentenced to 12 months and 1 day federal prison plus 2 years supervised release and $8,674 restitution.
Shelby Ligons	Shelby	Ligons		Tennessee	Nashville	22	Black	Female	2020-05-30	12	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Shelby Ligons, 22, of Nashville, TN was charged with malicious destruction of property using fire. On the afternoon of May 30, 2020 protesters gathered in front of the Nashville City Hall (Metro Courthouse) following George Floyd's death. Using crowbars and other objects they smashed windows and sprayed graffiti; one or more fires were set inside. Ligons was depicted in video clips holding a white poster board with "F--k The Police" and "We Will Not Be Silent" written on it; she was depicted setting fire to the poster and placing it inside a Courthouse window. Sentenced to 12 months and 1 day federal prison plus 3 years supervised release and $500 restitution.
Mario Ernesto Alvarado	Mario Ernesto	Alvarado		California	Los Angeles	42	Latino	Male	2020-05-30	12	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Mario Ernesto Alvarado, 42, of Los Angeles, CA was charged with arson during civil disturbances on May 30, 2020. Alvarado walked into a commercial building in Hollywood that housed Pizzeria Mozza and Mozza2Go, poured a flammable liquid on the restaurant floor, and set it on fire. The fire caused $500,000 in structural damage and $50,000 in fire damage to merchandise. Sentenced to 12 months and 1 day federal prison plus 3 years supervised release.
Javon Hardy	Javon	Hardy		New York	Rochester	24	Black	Male	2020-05-30	12	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2101 — Travel to incite riots.	On May 30, 2020 protests at the Public Safety Building in Rochester, NY in response to the death of George Floyd turned violent. A 32-foot mobile office on the property was set on fire. Facebook Live video showed a male in a black hoodie with a blue bandana — later identified as Javon Hardy, 24 — carrying a milk jug at the back door of the trailer. Hardy walked down the trailer steps and yelled "Let that bitch burn" and "If it's not on fire, I didn't do my job." The mobile office burned. Sentenced to 12 months federal prison plus $14,504 restitution.
Colinford Mattis	Colinford	Mattis		New York	Brooklyn	32	Black	Male	2020-05-31	12	Federal	18 U.S.C. § 844(f)(1), § 844(i), § 844(h)(1), § 844(n) — Use/conspiracy of explosives and arson; § 924(c)(l)(B)(ii) — Use of a destructive device; § 231(a)(3) — Civil disorder; 26 U.S.C. § 5861(d), (f) — Possessing/making a destructive device.	Colinford Mattis, 32, of Brooklyn, NY (an attorney at the time of arrest) was arrested with co-defendant Urooj Rahman after attempts to use Molotov cocktails to damage NYPD vehicles during George Floyd protests on May 31, 2020. They pleaded guilty under a federal plea agreement. Sentenced to 12 months federal prison.
Julian Renee Mejia	Julian Renee	Mejia		California	Los Angeles	35	Latino	Male	2020-09-10	12	Non-Federal	Cal. Penal Code § 451(c) — Arson; § 463(a) — Looting.	On September 10, 2020 Julian Renee Mejia, 35, of Los Angeles, CA pled "no contest" to a charge of looting. He was arrested in Los Angeles by the "Safe LA Task Force" after the George Floyd Protests. Sentenced to 12 months county jail.
Michele Alfaro	Michele	Alfaro		California	Los Angeles	24	Latino	Female	2021-05-13	12	Non-Federal	Cal. Penal Code § 463(a) — Looting.	On May 13, 2021 Michele Alfaro, 24, pled "no contest" to a charge of looting and was sentenced to 1 year county jail. Alfaro was arrested in Los Angeles by the "Safe LA Task Force" after the George Floyd Protests.
Raphael Shaw	Raphael	Shaw		Pennsylvania	Philadelphia	20	Black	Male	2020-05-31	12	Federal	18 U.S.C. § 2113(a) — Entering a bank with intent to commit a felony; § 2113(b) and § 2 — Taking and carrying away more than $1,000 from a bank, and aiding and abetting.	On May 31, 2020 amid widespread looting along Philadelphia's 52nd Street corridor, surveillance footage showed Raphael Shaw, 20, in a blond wig and surgical mask guiding a stolen Lowe's forklift hauling a vault from a Wells Fargo bank branch. Prosecutors named Shaw as the "wig-wearing bandit" who made off with $104,000. Co-defendant Xavier Nolley-Hall was with him and entered the ransacked bank intending to steal money. Sentenced to time served plus 15 months supervised release and $104,000 restitution.
Anthony David Ale Smith	Anthony David Ale	Smith	Ant	Pennsylvania	Philadelphia	29	Black	Male	2020-05-30	12	Federal	18 U.S.C. § 844(f)(1), (f)(2) — Arson of property belonging to a federally-funded agency; § 844(i) — Arson; § 231(a)(3) — Obstruction of law enforcement during civil disorder; § 2 — Aiding and abetting (3 counts).	Anthony David Ale Smith, 29, of Philadelphia was charged with co-defendants Carlos Matchett and Khalif Miller for the May 30, 2020 arson of a Philadelphia PD vehicle. They allegedly placed combustible materials into the police vehicle after a road flare started a fire; the PPD vehicle was destroyed. Smith pled guilty 6/6/23 to one count of obstructing law enforcement during a civil disorder, several months after the city of Philadelphia announced a $9.25M settlement over lawsuits filed by Smith and other activists challenging the police response to protests. Sentenced to 12 months federal prison.		Philadelphia Coalition for Racial Economic and Legal Justice
Kyle Robert Tornow	Kyle Robert	Tornow	Chester Wildwood	Washington	Seattle	36	White	Male	2020-07-24	11	Federal	18 U.S.C. § 875(c) — Interstate threats.	Kyle Robert Tornow, 36, of Seattle was arrested for making a threat to damage or destroy a Portland, OR police precinct. On July 24, 2020 Tornow used the Portland Police TrackIT system to send a message claiming he had planted an explosive at a city precinct, "undetectable" to canine searchers, and that if he were caught "others will take my place and immediately detonate the bomb." FBI agents traced the communications back to him. Sentenced to time served (~11 months) plus 3 years supervised release.
Errick Steven Toa	Errick Steven	Toa		North Dakota	Fargo	33	Black	Male	2020-05-30	10	Federal	18 U.S.C. § 231(a)(3) — Interfering with law enforcement.	Errick Steven Toa, 33, was charged with civil disorder for inciting violence by jumping on top of an occupied police car and breaking the windshield during the May 30, 2020 riots in Fargo, ND. Sentenced to time served (~10.6 months between arrest May 30, 2020 and judgment April 13, 2021) plus 2 years supervised release and $390 restitution.
Ronald T. Green	Ronald T.	Green		Ohio	Youngstown	24	Biracial	Male	2020-05-31	10	Federal	18 U.S.C. § 922(g)(1) — Felon in possession of a firearm.	Ronald T. Green, 24, pleaded guilty in U.S. District Court in Cleveland to being a felon in possession of ammunition. He also faced state charges in Youngstown Municipal Court for felony vandalism, obstructing official business, and throwing something through the rear window of a Youngstown police cruiser during the May 31, 2020 protest. Green has prior burglary convictions in Texas and Mahoning County. Sentenced to 10 months federal prison.
Ryan David Lucero	Ryan David	Lucero		Utah	Salt Lake City	33	White	Male	2020-06-07	9	Federal	18 U.S.C. § 115(a)(1)(B) — Influencing federal official by threat.	Ryan David Lucero, 33, of Magna, UT was charged with influencing a federal officer by threat for threatening to assault and murder a Department of Veterans Affairs police officer in retaliation for the officer's official duties. The officer's teenage daughter found the threat in the victim's mailbox on June 7, 2020 — about a week after a May 30, 2020 riot in Salt Lake City destroyed a police vehicle and damaged the SLC Police Department building. Sentenced to time served (~9 months); BOP for time served, no supervised release imposed.
Jhajuan Sabb	Jhajuan	Sabb	Jhumoney Tvshow	New York	Troy	20	Black	Male	2020-06-06	8	Federal	18 U.S.C. § 875(c) — Interstate threatening communications; 18 U.S.C. § 842(p)(2)(A) — Distribution of information relating to explosives, destructive devices, and weapons of mass destruction.	Jhajuan Sabb, 20, of Troy, NY was charged with interstate threats to injure another person and teaching the making/use of an explosive device. He made several Facebook Live videos threatening to throw bricks at the Troy Police Department, Troy police vehicles, and Troy City Hall during a demonstration. He also offered instructions on how to make firebombs with the intent that they be used during the demonstration. Sentenced to 8 months federal prison plus 3 years supervised release.
Corey Cardale Gee	Corey Cardale	Gee		Florida	Tampa	28	Black	Male	2020-05-31	8	Non-Federal	Fla. Stat. § 870.048 — Unlawful violation of established emergency measures; § 810.02(1)(b)(4)(a) — Burglary of an unoccupied structure.	On May 31, 2020 Corey Cardale Gee, 28, of Tampa, FL was arrested for unlawful violation of emergency measures and burglary of an unoccupied structure during protests for George Floyd. He was seen breaking into a Marathon gas station. Sentenced to 8 months in Florida state prison.
Tearra Na'Asia Guthrie	Tearra Na'Asia	Guthrie		South Carolina	Charleston	23	Black	Female	2020-05-30	7	Federal	18 U.S.C. § 231(a)(3) and § 2 — Civil disorder.	Tearra Guthrie, 23, of Charleston, SC pled guilty to civil disorder related to the violence and destruction on May 30, 2020. The presentence report contained a recommendation to add a "federal crime of terrorism" enhancement, increasing her guideline range to a statutory cap of five years. Sentenced to 7 months federal prison. She died in May 2022.
Andrew Steven Faulkner	Andrew Steven	Faulkner		Oregon	Portland	24	White	Male	2020-07-05	6	Federal	18 U.S.C. § 111(a)(1) — Forcibly interfering with a federal officer while performing official duties.	On July 5-6, 2020, during ongoing protests in downtown Portland, Faulkner, Christopher Fellini, Cody Porter, and Taimane Teo were accused of assaulting federal officers with high-intensity lasers. At the time of his arrest, Faulkner also possessed a sheathed machete. Sentenced to 6 months federal prison plus 3 years probation and 40 hours community service.
Corey Smith	Corey	Smith		New York	Brooklyn	24	Black	Other	2020-07-15	6	Federal	18 U.S.C. § 844(F)(n) and § 2 — Conspiracy to commit arson; arson.	On July 15, 2020 around 4:35 a.m., Corey Smith, 24 (gender non-conforming), and co-defendant Elaine Carberry used ignitable liquid to set fire to a marked NYPD Homeless Outreach Unit van on the NW corner of 12th Street and University Place in Manhattan. Surveillance footage shows the van igniting in flames; Smith handed Carberry a bottle which she put in her purse. The pair returned and a larger fire ignited. An undercover officer who had interacted with both suspects identified them as Smith and Carberry. Sentenced to 6 months federal prison.
Elaine Carberry	Elaine	Carberry		New York	Brooklyn	36	White	Female	2020-07-15	6	Federal	18 U.S.C. § 844(F)(n) and § 2 — Conspiracy to commit arson; arson.	Elaine Carberry, 36, was charged with co-defendant Corey Smith for using ignitable liquid to set fire to an NYPD Homeless Outreach Unit van in Manhattan on July 15, 2020. Surveillance footage and an undercover officer's identification linked the pair. Sentenced to 6 months federal prison.
Jeffrey Richard Singer	Jeffrey Richard	Singer		Oregon	Portland	33	White	Male	2020-10-04	6	Federal	18 U.S.C. § 231(a)(3) — Civil disorder; 18 U.S.C. § 641 — Theft of government property.	On October 4, 2020 Jeffrey Richard Singer, 33, was protesting near Portland City Hall. He charged at two officers with his shoulder lowered, slamming into them and injuring an officer's hands. In a separate incident on September 19, 2020, he stole the U.S. flag from the Gus Solomon Courthouse flagpole during a protest. Sentenced to 6 months federal prison.
Hampton Milton McCoy III	Hampton Milton III	McCoy		Florida	Tampa	29	Black	Male	2020-05-30	6	Non-Federal	Fla. Stat. § 810.02(1)(b)(4)(a) — Burglary of an unoccupied structure; § 812.014(2)(c)(3) — Grand theft.	Hampton Milton McCoy III, 29, of Tampa, FL was charged following his involvement in a Black Lives Matter protest over Memorial Day weekend 2020 — initially with burglary of an unoccupied structure and grand theft after allegedly breaking into a Gold and Diamond Source store. He pled no contest to burglary in exchange for the grand theft charge being dropped. Sentenced to 180 days in Florida state prison plus 24 months probation and 50 hours community service.
Kareem Dewayne Jefferson	Kareem Dewayne	Jefferson		California	Los Angeles	20	Black	Male	2020-08-24	6	Non-Federal	Cal. Penal Code § 463(a) — Looting.	On August 24, 2020 Kareem Dewayne Jefferson, 20, of Los Angeles, CA pled "no contest" to a charge of looting and was sentenced to 6 months county jail. He was arrested in Los Angeles by the "Safe LA Task Force" after the George Floyd Protests.
Andrew Moore Stegner	Andrew Moore	Stegner		Virginia	Lynchburg	19	White	Male	2020-05-30	6	Non-Federal	Va. Code § 18.2-279 — Throwing projectile into an occupied building; § 18.2-405 — Participating in a riot.	Andrew Stegner, 19, of Lynchburg, VA was charged with throwing a projectile into an occupied building (felony) and rioting (misdemeanor) after his participation in a Lynchburg Black Lives Matter protest in May 2020. He was allegedly part of a group that threw rocks at a restaurant after it was accused of publishing a racist tweet. Acquitted of the felony but found guilty of misdemeanor rioting; sentenced to 6 months prison with a 5-month suspended sentence.
Shakell Sanks	Shakell	Sanks		New York	Rochester	26	Black	Male	2020-05-30	5	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	On May 30, 2020 Shakell Sanks, 26, of Rochester, NY assisted others in attempting to light fabric on fire. The fabric was stuffed into the gas tank of a Rochester FACIT (Family Crisis Intervention Team) car parked at 144 Exchange Boulevard. The car began smoking and became engulfed in flames. Sentenced to 5 months federal prison.
Isaiah Bryant	Isaiah	Bryant		California	Los Angeles	24	Black	Male	2020-06-30	5	Non-Federal	Cal. Penal Code § 463(a) — Looting.	On June 30, 2020 Isaiah Bryant, 24, was arrested in Los Angeles, CA by the "Safe LA Task Force" after the George Floyd Protests. He was found guilty of looting; sentenced to 5 months county jail. Currently held at the 77th Division Jail on other charges.
Abdimanan Bana Habib	Abdimanan Bana	Habib		North Dakota	Fargo	21	Black	Male	2020-05-30	4	Federal	18 U.S.C. § 231(a)(3) — Civil disorder.	Abdimanan Habib, of Fargo, ND admitted to throwing rocks at police and attempting to light a Molotov cocktail during May 2020 protests sparked by George Floyd's murder. Arrested October 2020; pled guilty in January 2021. At sentencing in February 2021, the judge released him with time served. Sentenced to 4 months federal prison plus 3 years supervised release and $2,500 restitution.
Simon Habonimana	Simon	Habonimana		North Dakota	Fargo	22	Black	Male	2020-05-30	3	Non-Federal	N.D. Cent. Code § 12.1-25-02(1)(c) — Arming rioters; § 12.1-17-01(1)(a) — Attempted simple assault on a peace officer; § 12.1-25-03(1) — Engaging in a riot; § 12.1-25-04 — Disobedience of public safety orders under riot conditions.	Simon Habonimana, 22, was charged in Fargo, ND with arming rioters, attempting to commit assault, rioting, and disobedience of public safety orders after he was arrested in connection with a protest related to the murder of George Floyd on May 30, 2020. Sentenced to 3.4 months in North Dakota state prison.
Jeremy J. Ryan	Jeremy J.	Ryan	Segway, Segway Jeremy	Wisconsin	Madison	31	White	Male	2020-06-26	3	Non-Federal	Wis. Stat. § 940.32(2) — Stalking; § 947.019(1) — Make terrorist threats.	On June 26, 2020 Jeremy J. Ryan, 31, of Madison, WI was charged with making terrorist threats and stalking (both felonies) plus other misdemeanors for allegedly threatening to release personal information about Dane County Sheriff Dave Mahoney and his family and calling on protestors to harass Mahoney's family home. Sentenced to 3 months in Wisconsin state prison.
Loren Reed	Loren	Reed		Arizona	Page	26	American Indian	Male	2020-06-02	2	Federal	18 U.S.C. § 844(e) — Using instruments of interstate commerce, the internet and telephone, to willfully threaten to unlawfully damage or destroy a building by fire.	Loren Reed, 26, of Page, AZ was charged after Page police were alerted to a private Facebook group he was using to organize a riot and plan to burn down buildings including the Page Magistrate Courthouse and Page Police Department office. Sentenced to 2 months federal prison.
Anthony Richard Couse III	Anthony Richard III	Couse		Florida	West Palm Beach	51	White	Male	2020-05-31	2	Non-Federal	Fla. Stat. § 784.07(2A) — Assault on a police officer; § 843.01 — Resisting an officer with violence; § 877.03 — Disorderly conduct.	Anthony Richard Couse III, 51, of West Palm Beach, FL (homeless at time of arrest) was charged with two felonies and two misdemeanors following his participation in a West Palm Beach BLM protest on May 31, 2020. He allegedly challenged Deputy Police Chief Rick Morris to a fight and egged on demonstrators. Pled guilty to lesser charges of felony resisting arrest with violence and misdemeanor disorderly conduct; sentenced to 2 months Florida state prison plus 18 months probation.
Vincent Hamer	Vincent	Hamer		Tennessee	Nashville	18	Black	Male	2020-05-30	2	Non-Federal	Tenn. Code § 39-17-303 — Aggravated riot; § 39-14-408 — Vandalism.	On June 3, 2020 Vincent Hamer, 18, was arrested in connection with vandalism at the Nashville Historic Courthouse. Police say video and photographs show Hamer using objects to break at least two windows at the courthouse on May 30, 2020 after a peaceful protest over George Floyd's death. Sentenced to 1.6 months in Tennessee state prison plus supervised probation.
Raul Guzman	Raul	Guzman		Florida	Lakeland	24	Latino	Male	2020-05-31	2	Non-Federal	Fla. Stat. § 870.01(2) — Inciting or encouraging a riot.	Raul Guzman, 24, of Lakeland, FL was charged with inciting a riot following his participation in a Black Lives Matter protest at Munn Park on May 31, 2020. According to a witness, Guzman encouraged people to go into the streets and that he wanted to "riot" and "storm" the police department. Sentenced to 1.5 months in Florida state prison plus 18 months probation.
Andrew Darnell Carlisle	Andrew Darnell	Carlisle		Georgia	Atlanta	29	Black	Male	2020-07-25	1	Non-Federal	Ga. Code — Criminal interference with government property (2 counts); riot (misdemeanor).	Andrew Darnell Carlisle, 29, of Atlanta was arrested on two counts of felony criminal interference with government property and one count of misdemeanor rioting after state investigators accused him of vandalizing the Georgia Department of Public Safety headquarters during a racial justice protest in July 2020. He was among a group throwing stones and incendiary devices through windows and spray-painting graffiti. As of September 2023 he was also charged in the Stop Cop City RICO case with 61 others. Sentenced to 1 month in Georgia state prison.	Stop Cop City
Christian Rea	Christian	Rea		Illinois	Naperville	19	Latino	Male	2020-06-01	1	Federal	18 U.S.C. § 231(a)(3) — Civil disorder.	On June 1, 2020 during demonstrations in response to George Floyd's death, Christian Rea, 19, threw an explosive or incendiary device near a Naperville, IL PD Special Response team vehicle and officers. The device exploded; officers were temporarily stunned with several suffering momentary blindness and hearing loss for several minutes. Panic ensued in the crowd. Sentenced to 1 month federal prison.
Chelsie Leann Eggers	Chelsie Leann	Eggers		North Dakota	Fargo	27	White	Female	2020-05-30	1	Non-Federal	N.D. Cent. Code § 12.1-25-02(1)(c) — Arming rioters; § 12.1-17-01(1)(a) — Attempted simple assault on a peace officer; § 12.1-25-03(1) — Engaging in a riot; § 12.1-25-04 — Disobedience of public safety orders under riot conditions.	Chelsie Eggers, 27, of Fargo, ND was charged with arming rioters, attempting to commit assault, rioting, and disobedience of public safety orders after she was arrested in connection with a protest related to the murder of George Floyd on May 30, 2020. Sentenced to 1 month in North Dakota state prison plus 1 year probation.
Carlos Alfredo Fugarte	Carlos Alfredo	Fugarte	Woodboy Los	Florida	Lakeland	28	Latino	Male	2020-05-31	1	Non-Federal	Fla. Stat. § 836.10 — Written threat to kill or do bodily injury.	Carlos Fugarte, 28, of Lakeland, FL was charged with written threat to kill after making comments encouraging people to blow up the local courthouse on a Facebook livestream of a Lakeland Black Lives Matter protest on May 31, 2020. Posting under the username "Woodboy Los," he issued a call to "Go to Bartow and blow up the courthouse." Sentenced to 1 month in Florida state prison plus 24 months probation.
Xavier Nolley-Hall	Xavier	Nolley-Hall		Pennsylvania	Philadelphia	20	Black	Male	2020-05-31	1	Federal	18 U.S.C. § 2113(a) — Entering a bank with intent to commit a felony; 18 U.S.C. § 1001(a)(2) — Knowingly and willfully made materially false, fictitious, and fraudulent statements.	On May 31, 2020 Xavier Nolley-Hall, 20, of Philadelphia was with co-defendant Raphael Shaw during the Wells Fargo bank robbery on the 1500 block of N. 52nd Street. He entered the ransacked bank intending to steal money. Sentenced to 45 days federal prison.
Isaiah JK Lindsey-Salinas	Isaiah JK	Lindsey-Salinas		Oregon	Eugene	23	White	Male	2020-05-31	1	Non-Federal	Or. Rev. Stat. § 164.215 — Burglary in the second degree; § 164.055 — Theft in the first degree; § 166.015 — Riot.	Isaiah Lindsey-Salinas, 23, of Eugene, OR was indicted on charges of rioting, burglary, and theft after being arrested in connection with a May 2020 George Floyd protest in Eugene that turned violent — people damaging property, robbing businesses, and setting a fire in the middle of an intersection. Felony charges dropped; found guilty of misdemeanors. Sentenced to about 5 days in Oregon state prison.
Edward William Carubis	Edward William	Carubis		Oregon	Portland	25	White	Male	2020-07-13	1	Federal	18 U.S.C. § 111(a) — Forcibly interfering with a federal officer while performing official duties.	Edward William Carubis, 25, of Portland, OR was charged with assault on federal officers after shining a green laser into three officers' eyes during protests at the federal courthouse. Sentenced to 2 days time served.
Josie Robotin	Josie	Robotin	Jacob Dean Robotin	Pennsylvania	Philadelphia	25	White	Other	2021-08-15	1	Federal	26 U.S.C. § 5861(d) — Knowingly possessed an unregistered firearm.	In 2021 Josie Robotin, 25 (gender non-conforming), of Willow Grove, PA was charged with knowingly possessing an unregistered firearm after a Molotov cocktail was found in her backpack amid a protest for the rights of trans prisoners. Robotin and two others were seen vandalizing buildings in downtown Philadelphia with spray paint and breaking windows. She accepted a plea deal; sentenced to time served plus 3 years probation and $100 fine. Court documents use the name "Jacob Dean Robotin," her birth name, but she uses the chosen name "Josie Robotin."	Trans rights
Brian Jordan Bartels	Brian Jordan	Bartels		Pennsylvania	Pittsburgh	20	White	Male	2020-05-30	1	Federal	18 U.S.C. § 231(a)(3) and § 2 — Obstruction of law enforcement during civil disorder; 18 Pa. § 3304(a)(2) — Criminal mischief; § 3307(a)(5) — Institutional vandalism; § 5501(1) — Riot; § 2705 — Recklessly endangering another person.	On May 30, 2020 Brian Jordan Bartels, 20, of Pittsburgh, PA, incited a riot when he attacked and vandalized a police car during a peaceful protest in Pittsburgh following the killing of George Floyd. Sentenced to 1 day in U.S. custody plus 6 months in a halfway house.
Cornelius C. Allen	Cornelius C.	Allen		Florida	Tampa	45	Black	Male	2020-05-31	1	Non-Federal	Fla. Stat. § 870.01(2) — Riot; § 810.02(1)(b)(4)(a) — Burglary of an unoccupied structure; § 812.014(3)(a) — Theft.	Cornelius C. Allen, 45, of Tampa, FL was charged with burglary of an unoccupied structure, felony rioting, and one misdemeanor count of petty theft following his involvement in a May 31, 2020 BLM protest. He was observed removing approximately $50.00 worth of merchandise from a local Walgreens and attempting to leave. Pleaded no contest to theft and burglary; rioting charge dismissed. Sentenced to 1 day confinement (effective January 12, 2021).
Gabriela Brigitte Jimenez	Gabriela Brigitte	Jimenez		California	Los Angeles	33	Latino	Female	2020-05-30	1	Non-Federal	Cal. Penal Code § 463(a) — Looting.	On March 24, 2022 Gabriela Brigitte Jimenez, 33, of Los Angeles, CA pled "no contest" to a charge of looting. She was arrested in Los Angeles by the "Safe LA Task Force" after the George Floyd Protests. Sentenced to 1 day in county jail.
Marcus Marlvin Hunt	Marcus Marlvin	Hunt		Missouri	St. Louis	29	Black	Male	2020-05-31	0	Federal	18 U.S.C. § 842(p)(2)(A) — Distribution of information relating to explosives, destructive devices, and weapons of mass destruction.	In May 2020 in St. Louis, MO, Marcus Marlvin Hunt, 29, was charged with distribution of information relating to explosives after providing a recipe for napalm on Facebook. He said in a Facebook live video, "I am trying to give y'all good information on weapons, armaments that you might need later on." The St. Louis Joint Terrorism Task Force treated this as evidence of imminent acts of violence. Case dropped.
Michael J. Avery	Michael J.	Avery	Mike Avery	Missouri	St. Louis	28	Black	Male	2020-05-31	0	Federal	18 U.S.C. § 2101(f) — Rioting.	On May 25-29, 2020 Michael J. Avery, 28, was charged with rioting after posting calls to action on Facebook under "Mike Avery" regarding Black Lives Matter protests in Minnesota. Posts included "CALLING OUT ALL THE SHOOTERS, ALL THE PEOPLE WHO DON'T GIVE AF" and "level RED ACTION." On May 30 he traveled to St. Louis to continue protesting, posting about how looting occurred in Minneapolis and encouraging "the masses" to participate. Case dropped.
Ca'Quintez Gibson	Ca'Quintez	Gibson		Illinois	Peoria	26	Black	Male	2020-06-04	0	Federal	18 U.S.C. § 2101 — Use of a facility of interstate commerce to incite a riot.	Ca'Quintez Gibson, 26, was charged with using the internet to incite a riot. He made a series of Facebook Live posts encouraging looting at Northwoods Mall and other locations in Peoria, IL: "It's going up tonight. Long as you all at Northwoods Mall. It's going up. Period... We ain't with that peaceful s---." Sentenced to 12 months probation; no incarceration.
Tyshaun T. Smith	Tyshaun T.	Smith		Wisconsin	Milwaukee	26	Black	Male	2020-06-04	0	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 26 U.S.C. § 5861(c) — Possession of a destructive device.	In June 2020 in Milwaukee, WI, Tyshaun T. Smith, 26, was charged with attempted arson and possession of a destructive device after throwing a Molotov cocktail through the window of a Boost Mobile store. He was given conditions of release; if he does not adhere he would face up to 10 years federal prison or $250,000 fine.
Jaywuan Peavy	Jaywuan	Peavy		Ohio	Cleveland	19	Black	Male	2020-06-05	0	Federal	18 U.S.C. § 2101(a)(1)(2) — Using interstate commerce to incite a riot.	In June 2020 in Cleveland, OH, Jaywuan Peavy, 19, was charged with using a facility of interstate commerce to organize, promote, encourage, participate in, or carry on a riot after posting numerous calls to riot on Facebook. Case dismissed.
Bailey Marie Baldus	Bailey Marie	Baldus		Minnesota	St. Paul	19	White	Female	2020-05-28	0	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	On the night of May 28, 2020 Bailey Marie Baldus, 19, was caught on surveillance camera with co-defendants Mckenzy Ann Degidio Dunn and Samuel Elliot Frey at a St. Paul, MN health and nutrition store during the unrest after George Floyd's death. Charges against Baldus were dropped after her defense attorney argued she was in the building but did not participate.
Matthew E. Madden	Matthew E.	Madden		Missouri	Kansas City	22	Black	Male	2020-05-30	0	Federal	18 U.S.C. § 922(g)(3) and § 924(a)(2) — Drug user in possession of a firearm.	In June 2020 in Kansas City, MO, Matthew E. Madden, 22, was charged with possession of a firearm by an unlawful user of a controlled substance. Madden was seen throwing water bottles at officers during protests; in pursuit, officers found a gun and marijuana in his fanny pack.
Ivan Jacob Zecher	Ivan Jacob	Zecher		Florida	Jacksonville	27	White	Male	2020-06-10	0	Federal	18 U.S.C. § 922(g)(1) — Felon in possession of a firearm; 26 U.S.C. § 5861(d) — Unlawful possession of an unregistered destructive device.	On June 10, 2020 in Jacksonville, FL, Ivan Jacob Zecher, 27, was charged with felon in possession of a firearm and unlawful possession of an unregistered firearm. During a protest, a group blocking traffic was reportedly throwing rocks and water bottles at officers. Officers arrested Zecher; his backpack was leaking — they found a liquor bottle full of gasoline, a lighter, balloons full of liquid, and a hatchet. Case dropped (illegal arrest).
Brandon Michael Althof Long	Brandon Michael Althof	Long		Ohio	Cleveland	23	White	Male	2020-05-30	0	Federal	18 U.S.C. § 371 — Conspiracy to riot and cause civil disorder; 18 U.S.C. § 844(h)(1) and (m) — Conspiracy to use fire to commit any felony; 18 U.S.C. § 2101(a) — Interstate travel to riot; 18 U.S.C. § 231(a)(2) — Transporting any firearm in furtherance of civil disorder.	In Cleveland, OH, Brandon Michael Althof Long, 23, and Devon Bryce Poland, 22, were both charged with conspiracy to riot, conspiracy to use fire to commit a felony, interstate travel to riot, and transporting a firearm in furtherance of civil disorder following arrest after a curfew. Texts showed they made arrangements to travel from PA to participate in Cleveland riots; weapons in their vehicle included a hammer, fire-starter containers, a glass liquor bottle, and a Glock semi-automatic with ammunition. Case dismissed March 2021.
Devon Bryce Poland	Devon Bryce	Poland		Ohio	Cleveland	22	White	Male	2020-05-30	0	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(h)(1) — Use fire to commit any felony; 18 U.S.C. § 2101(a) — Interstate travel to riot; 18 U.S.C. § 231(a)(2) — Transporting any firearm in furtherance of civil disorder.	Devon Bryce Poland, 22, was charged in Cleveland, OH with co-defendant Brandon Michael Althof Long for the same conspiracy — they traveled from PA to participate in Cleveland riots with a vehicle containing a hammer, fire-starters, a glass liquor bottle, and a Glock. Case dismissed March 2021.
Michael Rodriguez	Michael	Rodriguez		New York	Brooklyn	32	Latino	Male	2020-06-15	0	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire.	In 2020 in Brooklyn, NY, Michael Rodriguez, 32, a homeless man, was charged with attempting to damage government property by fire — accused of setting fire to a vehicle with an NYPD placard on a residential block. Charges later dropped; Rodriguez was misidentified as the perpetrator by police.
Victor A. Sanchez-Santa	Victor A.	Sanchez-Santa		New York	Manhattan	19	Unknown	Male	2020-06-18	0	Federal	18 U.S.C. § 844(f) — Damaging government property by fire; 18 U.S.C. § 2 — Aiding and abetting.	In Manhattan, NY, Victor A. Sanchez-Santa, 19, was charged with one count of arson for attempting to set a police car on fire — he lit a cloth glove on fire, placed it under the police car, and left. Prosecutors said the matter could be prosecuted in federal court because the NYPD receives federal funds. Charged but not tried.
Jessica Lynn White	Jessica Lynn	White		Minnesota	Minneapolis	33	White	Female	2020-05-28	0	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 371 — Conspiracy.	Jessica Lynn White, 33, was arrested with co-defendant Matthew Scott White in connection with a fire set at an Enterprise Rent-A-Car building in St. Paul, MN on May 28, 2020. Surveillance video showed her standing outside while Matthew White entered the building; flames were visible behind him as he exited. Case dismissed.
Lashawn L. Wilks	Lashawn L.	Wilks		Illinois	Centralia	31	Black	Male	2020-06-04	0	Federal	18 U.S.C. § 922(g)(9) and § 924(a)(2) — Possession of a firearm by a prohibited person.	Lashawn L. Wilks, 31, of Centralia, IL was charged by federal complaint with unlawful possession of a firearm by a prohibited person after multiple sources reported he had guns at a May 23, 2020 house party and threatened to "kill a cop." After George Floyd's death he allegedly posted on Facebook threatening violence to police. On June 2, 2020 law enforcement learned he was discussing plans to organize a protest and cause a riot in Centralia, with a list of officers to shoot. A federal search of his residence found a 9mm pistol, a rifle, and a 12-gauge shotgun. Charges later dropped.
Timothy James Goodner	Timothy James	Goodner		Ohio	Cleveland	19	White	Male	2020-05-30	0	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Timothy James Goodner, 19, was involved in an act of arson concerning the Shaia's Parking Lot attendant booth on May 30, 2020 as part of the George Floyd protests. Government dismissed the indictment and supplemental information without prejudice.
Keith Leroy Moreno	Keith Leroy	Moreno		Nevada	Reno	27	White	Male	2020-05-30	0	Federal	18 U.S.C. § 1361 — Destruction of government property.	On May 30, 2020 in Reno, NV, Keith Leroy Moreno, 27, threw a cigarette receptacle and rocks at the first floor windows of the Bruce R. Thompson Federal Courthouse during the George Floyd Protests. Charged but not tried.
Marquis Frasier	Marquis	Frasier		New York	Rochester	27	Black	Male	2020-05-30	0	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	Marquis Frasier, 27, said he was at the Public Safety Building "when the riots occurred" on May 30, 2020 in Rochester, NY. He allegedly admitted to spray painting, smashing the windows of a truck, breaking glass at the Court Exchange Building, and stealing drinks from a vending machine. He admitted to having a Molotov cocktail (a Cuervo bottle) which he tried unsuccessfully to light, then threw into the back window of a trailer. Frasier was already charged in Rochester City Court on June 22 with first-degree arson and other state charges. Charged but not tried federally.
Mustafah Omar Hawkins	Mustafah Omar	Hawkins	Majic Jordan	Ohio	Cleveland	27	Black	Male	2020-05-30	0	Federal	18 U.S.C. § 875(c) — Interstate threatening communications.	In June 2020 in Cleveland, OH, Mustafah Omar Hawkins, 27, was charged with Interstate Threatening Communications after using Facebook to threaten officers. Sentenced to 2 years probation; no incarceration.
Travis Glendon Martin III	Travis Glendon III	Martin		Texas	Houston	32	White	Male	2020-06-12	0	Federal	18 U.S.C. § 231(a)(3) — Civil disorder.	Travis Glendon Martin III was arrested on June 12, 2020 after engaging in civil disorder activities and assaulting a police officer at a Black Lives Matter protest in Houston, TX. He was charged with shattering the windows on cars belonging to the police department during the George Floyd uprising. In February 2022, the defendant's charges were dismissed by the judge.
Rudy Alvarez	Rudy	Alvarez		California	San Diego	24	White	Male	2020-07-02	0	Federal	18 U.S.C. § 39A — Aiming a laser pointer at an aircraft.	On July 2, 2020 Rudy Alvarez, 24, was charged with aiming a laser pointer at a San Diego Police Department aircraft during a Black Lives Matter protest. No prison time imposed; 5 years probation.
Rowan M. Olsen	Rowan M.	Olsen	Kiefer Alan Moore	Oregon	Portland	19	White	Male	2020-07-04	0	Federal	41 C.F.R. § 102-74.380(d) — Creating a hazard on federal property; § 102-74.390 — Disorderly conduct on federal property; § 102-74.385 — Failing to obey a lawful order.	Rowan M. Olsen, 19, interfered with FPS and U.S. Marshals at protests around the Hatfield Federal Courthouse in Portland, OR. Olsen entered the building and used his body to push on and hold a door closed, preventing officers from exiting; the glass door broke, injuring a deputy U.S. Marshal. He gave authorities a fake name ("Kiefer Alan Moore") and fake age and was already on probation for an earlier officer-attack conviction. Charged but not tried.
Theodore Adriaan Matthee-O'Brien	Theodore Adriaan	Matthee-O'Brien	Theodore Adriaan Matthee-O'Brian	Oregon	Portland	21	White	Male	2020-07-05	0	Federal	18 U.S.C. § 111(a)(1) — Misdemeanor assault on a federal officer.	Theodore Adriaan Matthee-O'Brien, 21, was charged with assaulting a federal officer on July 5, 2020 during ongoing Portland, OR protests after George Floyd's murder. He was arrested at a violent protest on July 6 — a student at the private liberal arts university Reed College. Found not guilty.
Taimane Jame Teo	Taimane Jame	Teo	Zouk	Oregon	Portland	24	White	Male	2020-07-06	0	Federal	18 U.S.C. § 111(a)(1) — Misdemeanor forcibly interfering with a federal officer.	On July 5-6, 2020 Taimane Jame Teo, 24, of Eugene, OR was accused of assaulting federal officers with high-intensity lasers during ongoing Portland protests after George Floyd's murder. Charged but not tried.
Shant Singh Ahuja	Shant Singh	Ahuja	Shanti	Oregon	Portland	28	Asian	Male	2020-07-04	0	Federal	18 U.S.C. § 1361 — Destruction of government property.	On July 4, 2020 Shant Singh Ahuja, 28, of Oceanside, CA was accused of willfully destroying a closed-circuit video camera mounted on the exterior of the Hatfield Federal Courthouse in Portland, OR. Charged but not tried.
Jerritt Jeremy Pace	Jerritt Jeremy	Pace		District of Columbia	Washington	39	White	Male	2020-06-01	0	Federal	28 U.S.C. § 5861(f) — Unlawful making or manufacturing of a firearm subject to the National Firearms Act.	In 2020 in Washington, DC, Jerritt Jeremy Pace, 39, was charged with receiving an explosive in interstate commerce, willfully threatening to damage a building by fire, and attempted arson. Pace announced on Facebook his intent to burn down a police station: "I WILL BURN A 12 STATION DOWN SO QUICK IF THIS COMES TO MY TOWN....PLEASE COME ON DC AND LETS RIOT." He filled a plastic laundry detergent container with gasoline and a wick and ignited it in front of the Fourth District Station; no damage to the building, but the container exploded and burned on the sidewalk. Pleaded guilty to one count of unlawful firearm manufacture; sentenced to time served plus 3 years supervised release.
Benjamin Wood-Pavich	Benjamin	Wood-Pavich	Miriam Eagles Wood-Pavicich	Oregon	Portland	21	White	Other	2020-07-06	0	Federal	18 U.S.C. § 111(a)(1) — Misdemeanor forcibly interfering with a federal officer.	On or about July 6, 2020 in Portland, OR, Benjamin Wood-Pavich, 21 (gender non-conforming), forcibly assaulted a federal officer engaged in official duties. Charged but not tried.
Cody Beau Porter	Cody Beau	Porter	Cody Porter, John Doe	Oregon	Portland	28	White	Male	2020-07-06	0	Federal	18 U.S.C. § 111(a)(1) — Misdemeanor forcibly interfering with a federal officer.	In July 2020 in Portland, OR, Cody Beau Porter, 28, was charged with forcibly interfering with a federal officer for allegedly assaulting officers with a high-intensity laser during a protest related to police brutality and the murder of George Floyd. Case dismissed as part of a deferred resolution agreement.
TSV;

$rows = array_filter(array_map('trim', explode("\n", $DATA)));

$today = Carbon::today();
$created = 0;
$skipped = 0;

foreach ($rows as $line) {
    $parts = explode("\t", $line);
    if (count($parts) < 14) continue;
    [$name, $first, $last, $aka, $state, $city, $age, $race, $gender,
     $arrest, $months, $jurisdiction, $charges, $narrative] = array_pad($parts, 16, '');
    $extraIdeologies   = $parts[14] ?? '';
    $extraAffiliations = $parts[15] ?? '';

    if (Prisoner::where('name', $name)->exists()) {
        echo "  [skip] {$name} — already in DB\n";
        $skipped++;
        continue;
    }

    $arrestC = Carbon::parse($arrest);
    $monthsF = (float) $months;

    if ($monthsF <= 0) {
        $inCustody    = false;
        $incarcDate   = null;
        $releaseDate  = null;
        $sentenceText = 'Charged but not tried / case dismissed or dropped — no incarceration imposed.';
    } else {
        $releaseC = $arrestC->copy()->addDays((int) round($monthsF * 30.44));
        $inCustody = $releaseC->gt($today);
        $incarcDate = $arrestC->format('Y-m-d');
        $releaseDate = $inCustody ? null : $releaseC->format('Y-m-d');
        $sentenceText = rtrim(rtrim(number_format($monthsF, 2), '0'), '.') . ' months '
                      . ($jurisdiction === 'Federal' ? 'federal' : 'state') . ' prison'
                      . ' (incarceration ' . $arrestC->format('Y-m-d')
                      . ($inCustody ? '; still in custody as of ' . $today->format('Y-m-d') : ' → projected release ' . $releaseC->format('Y-m-d'))
                      . ').';
    }

    $instName = ($jurisdiction === 'Federal' ? 'Federal Bureau of Prisons' : 'State prison')
              . ' (' . $state . ')';

    $ideologies = ['Black Lives Matter', 'Police Accountability', 'Summer 2020 protests'];
    if ($extraIdeologies) {
        foreach (preg_split('/\s*,\s*/', $extraIdeologies) as $i) {
            if ($i !== '') $ideologies[] = $i;
        }
    }
    $ideologies = array_values(array_unique($ideologies));

    $affiliations = [];
    if ($extraAffiliations) {
        foreach (preg_split('/\s*,\s*/', $extraAffiliations) as $a) {
            if ($a !== '') $affiliations[] = $a;
        }
    }

    $birth = $today->copy()->subYears((int) $age)->format('Y-m-d');

    $genderVal = match (strtolower($gender)) {
        'male'                => 'Male',
        'female'              => 'Female',
        'other', 'non-binary',
        'gender non-conforming' => 'Other',
        default               => $gender ?: null,
    };

    $raceVal = $race === 'Unknown' ? null : ($race ?: null);

    $prisoner = Prisoner::create([
        'name'                => $name,
        'first_name'          => $first,
        'last_name'           => $last,
        'aka'                 => $aka ?: null,
        'description'         => $narrative,
        'state'               => $state,
        'race'                => $raceVal,
        'gender'              => $genderVal,
        'birthdate'           => $birth,
        'ideologies'          => $ideologies,
        'affiliation'         => $affiliations ?: null,
        'era'                 => '2020s',
        'in_custody'          => $inCustody,
        'released'            => ! $inCustody,
    ]);

    $inst = Institution::firstOrCreate(
        ['name' => $instName],
        ['city' => $city, 'state' => $state]
    );

    PrisonerCase::create([
        'prisoner_id'        => $prisoner->id,
        'institution_id'     => $inst->id,
        'charges'            => $charges,
        'arrest_date'        => $arrestC->format('Y-m-d'),
        'incarceration_date' => $incarcDate,
        'release_date'       => $releaseDate,
        'sentence'           => $sentenceText,
        'convicted'          => $monthsF > 0 ? 'Yes' : 'No — case dismissed/dropped or charged but not tried',
    ]);

    echo "  [add]  {$name}  ({$months} mo, {$jurisdiction})\n";
    $created++;
}

echo "\nDone. created={$created}, skipped={$skipped}\n";
