#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_contempt_of_congress_prisoners.sh
#
# Adds 7 political prisoners imprisoned for contempt of Congress, plus
# amends the existing Eugene Dennis entry with his earlier 1947 case.
set -e

# ============================================================
# JAFRC defendants (1950)
# ============================================================

php artisan prisoner:add '{"name":"Howard Fast","first_name":"Howard","last_name":"Fast","description":"Howard Melvin Fast was an American novelist whose books — including Citizen Tom Paine, Freedom Road, and Spartacus — made him one of the best-selling political authors of his era. A member of the Communist Party USA from 1944 to 1957, he served on the board of the Joint Anti-Fascist Refugee Committee, the U.S. organization that raised money for Spanish Civil War refugees and other anti-fascist causes. In 1946, the House Un-American Activities Committee subpoenaed JAFRCs records; the boards officers, including Fast, refused on First Amendment grounds. They were cited for contempt of Congress and convicted at trial in 1947.\n\nAfter exhausting appeals, Fast served three months in 1950 at the federal prison camp at Mill Point, West Virginia, alongside Hollywood Ten members Albert Maltz and Edward Dmytryk. He spent his time inside drafting the novel that would become Spartacus (1951), which the major U.S. publishers refused to print because of his political record; he self-published it through the Blue Heron Press, and it sold more than 50,000 copies. Stanley Kubricks 1960 film adaptation, with a screenplay by fellow Hollywood Ten alumnus Dalton Trumbo, helped break the Hollywood blacklist. Fast was awarded the Stalin Peace Prize in 1953 and publicly broke with the Communist Party in 1957 after Khrushchevs revelations about Stalin.","state":"West Virginia","race":"White","gender":"Male","birthdate":"1914-11-11","death_date":"2003-03-12","ideologies":["Communism","Anti-fascist","First Amendment"],"affiliation":["Communist Party USA","Joint Anti-Fascist Refugee Committee"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Prison Camp, Mill Point","institution_city":"Mill Point","institution_state":"West Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to turn over Joint Anti-Fascist Refugee Committee records to the House Un-American Activities Committee","arrest_date":"1947-04-04","incarceration_date":"1950-06-09","release_date":"1950-09-09","sentence":"3 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, June 1947"}]}'

php artisan prisoner:add '{"name":"Edward K. Barsky","first_name":"Edward","middle_name":"K.","last_name":"Barsky","description":"Dr. Edward K. Barsky was a New York surgeon, Spanish Civil War veteran, and chairman of the Joint Anti-Fascist Refugee Committee — the U.S. organization that raised funds for Spanish Republican refugees and later European anti-fascists displaced by Nazi occupation. Barsky himself had organized the American Medical Bureau to Aid Spanish Democracy in 1937 and led volunteer surgeons attached to the Abraham Lincoln Brigade, performing battlefield surgery at the front during the Spanish Civil War.\n\nIn 1946, the House Un-American Activities Committee subpoenaed JAFRCs records; Barsky and other officers refused on First Amendment grounds. They were cited for contempt of Congress, convicted at trial in 1947, and after exhausting appeals served their sentences in 1950. Barsky received the longest of the JAFRC sentences — six months at the Federal Correctional Institution at Petersburg, Virginia. After his release the New York State Board of Regents revoked his medical license for six months as a further punishment, a decision the U.S. Supreme Court upheld 6–3 in Barsky v. Board of Regents (1954). He continued to practice and to organize for anti-fascist and progressive causes until his death in 1975.","state":"New York","race":"White","gender":"Male","birthdate":"1895-06-14","death_date":"1975-02-11","ideologies":["Communism","Anti-fascist","First Amendment"],"affiliation":["Joint Anti-Fascist Refugee Committee","Abraham Lincoln Brigade","American Medical Bureau to Aid Spanish Democracy"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Petersburg","institution_city":"Petersburg","institution_state":"Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to turn over Joint Anti-Fascist Refugee Committee records to the House Un-American Activities Committee","arrest_date":"1947-04-04","incarceration_date":"1950-06-09","release_date":"1950-12-09","sentence":"6 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, June 1947"}]}'

php artisan prisoner:add '{"name":"Helen R. Bryan","first_name":"Helen","middle_name":"R.","last_name":"Bryan","description":"Helen Reid Bryan was the executive secretary of the Joint Anti-Fascist Refugee Committee. She was cited for contempt of Congress in 1946 along with the rest of the JAFRC board for refusing on First Amendment grounds to hand over the organizations records to the House Un-American Activities Committee. After exhausting appeals she served three months in 1950 at the Alderson Federal Reformatory for Women in West Virginia. While there she taught literacy classes to other incarcerated women and later wrote one of the earliest first-person accounts of life inside a U.S. womens federal prison, Inside (1953).","state":"New York","race":"White","gender":"Female","birthdate":"1898-01-01","death_date":"1976-08-23","ideologies":["Anti-fascist","First Amendment"],"affiliation":["Joint Anti-Fascist Refugee Committee"],"in_custody":false,"released":true,"cases":[{"institution_name":"Alderson Federal Reformatory for Women","institution_city":"Alderson","institution_state":"West Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to turn over Joint Anti-Fascist Refugee Committee records to the House Un-American Activities Committee","arrest_date":"1947-04-04","incarceration_date":"1950-06-09","release_date":"1950-09-09","sentence":"3 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, June 1947"}]}'

# ============================================================
# Earliest HUAC contempt prisoner — preceded the Hollywood Ten
# ============================================================

php artisan prisoner:add '{"name":"Leon Josephson","first_name":"Leon","last_name":"Josephson","description":"Leon Josephson was a New York lawyer, Communist Party member, and the first person imprisoned for refusing to cooperate with the House Un-American Activities Committee. Subpoenaed in March 1947 in connection with HUACs investigation of an alleged passport-fraud ring, Josephson refused even to be sworn in as a witness, asserting that the committee was unconstitutional and that compelled testimony before it would violate the First Amendment.\n\nHe was indicted, tried, and convicted of contempt of Congress in 1947 — months before the more famous Hollywood Ten citations of November 1947. After exhausting appeals he served ten months at the Federal Correctional Institution at Danbury, Connecticut, beginning June 1948. His case set the legal template that the Hollywood Ten and the Joint Anti-Fascist Refugee Committee defendants would later follow into prison: a First Amendment refusal, conviction by a Washington jury, affirmance by the D.C. Circuit, and denial of certiorari by a Supreme Court still unwilling to confront the new HUAC machinery. He died in 1962.","state":"New York","race":"White","gender":"Male","birthdate":"1903-12-30","death_date":"1962-10-07","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Contempt of Congress — refusing on First Amendment grounds to be sworn in as a witness before the House Un-American Activities Committee","arrest_date":"1947-03-05","incarceration_date":"1948-06-15","release_date":"1949-04-15","sentence":"10 months federal prison — the first prison sentence imposed for HUAC contempt, predating the Hollywood Ten by a year","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1947"}]}'

# ============================================================
# Late McCarthy era — the SCOTUS contempt cases
# ============================================================

php artisan prisoner:add '{"name":"Frank Wilkinson","first_name":"Frank","last_name":"Wilkinson","description":"Frank Wilkinson was a Los Angeles public-housing administrator who in 1952 was destroyed professionally for refusing on First Amendment grounds to answer the House Un-American Activities Committees questions about his political associations. He went on to found the National Committee Against Repressive Legislation in 1960 and to lead the most sustained campaign of the 1960s and 1970s to abolish HUAC, which Congress finally renamed and gradually defunded.\n\nIn 1958, while organizing in Atlanta to build opposition to a HUAC field hearing on civil rights, Wilkinson was again subpoenaed and again refused on First Amendment grounds. He was cited for contempt of Congress alongside Carl Braden, who was organizing in the same campaign. The two men were tried separately, convicted, and lost their parallel Supreme Court appeals on the same day in 1961 — Wilkinson v. United States, 365 U.S. 399, decided 5–4 — over a vigorous Black/Douglas dissent that the conviction was retaliation for political organizing and a violation of the First Amendment. Wilkinson served nine months at the United States Penitentiary in Atlanta in 1961. After his release the FBI maintained surveillance on him for another twenty years; FOIA litigation later revealed that his FBI file ran to 132,000 pages, the largest political-surveillance file ever opened on an individual American.","state":"California","race":"White","gender":"Male","birthdate":"1914-08-16","death_date":"2006-01-02","ideologies":["First Amendment","Civil rights","Anti-HUAC"],"affiliation":["National Committee Against Repressive Legislation"],"in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Atlanta","institution_city":"Atlanta","institution_state":"Georgia","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about political associations","arrest_date":"1958-07-30","incarceration_date":"1961-05-01","release_date":"1962-02-01","sentence":"9 months federal prison","convicted":"Yes — federal jury verdict; affirmed by U.S. Supreme Court 5–4 in Wilkinson v. United States, 365 U.S. 399 (1961)"}]}'

php artisan prisoner:add '{"name":"Lloyd Barenblatt","first_name":"Lloyd","last_name":"Barenblatt","description":"Lloyd Barenblatt was a psychology instructor at Vassar College who in June 1954 was subpoenaed by the House Un-American Activities Committee, sitting in Albany, to answer questions about Communist activity at the University of Michigan, where he had been a graduate student. He refused on First Amendment grounds, citing the principles laid down by the Hollywood Ten. He was cited for contempt of Congress, convicted in federal court in Washington, and after exhausting appeals lost 5–4 at the Supreme Court in Barenblatt v. United States, 360 U.S. 109 (1959). Justice Hugo Black wrote a sweeping dissent — joined by Chief Justice Warren and Justices Douglas and Brennan — accusing the majority of approving naked political punishment of dissenting professors. Barenblatt served six months at the Federal Correctional Institution at Lewisburg, Pennsylvania in 1961, the same year Wilkinson and Braden served their parallel HUAC contempt sentences. Vassar fired him; he never taught again.","state":"New York","race":"White","gender":"Male","birthdate":"1926-01-01","death_date":null,"ideologies":["First Amendment","Anti-HUAC"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Lewisburg","institution_city":"Lewisburg","institution_state":"Pennsylvania","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party associations at the University of Michigan","arrest_date":"1954-06-28","incarceration_date":"1961-05-15","release_date":"1961-11-15","sentence":"6 months federal prison","convicted":"Yes — federal jury verdict; affirmed by U.S. Supreme Court 5–4 in Barenblatt v. United States, 360 U.S. 109 (1959)"}]}'

# ============================================================
# Adjacent: last Smith Act membership-clause prisoner
# ============================================================

php artisan prisoner:add '{"name":"Junius Scales","first_name":"Junius","middle_name":"Irving","last_name":"Scales","description":"Junius Irving Scales was a North Carolina-born organizer who became chairman of the Communist Party USAs Carolinas District and the only American ever sent to federal prison under the membership clause of the Smith Act of 1940 — the provision that made it a crime to be a member of any organization that advocated the overthrow of the U.S. government, even without any underlying act. He was indicted in 1954, convicted in 1955, won reversal at the Supreme Court in 1957, and was retried and reconvicted in 1958. The Supreme Court affirmed the second conviction 5–4 in Scales v. United States, 367 U.S. 203 (1961) — the same docket as Wilkinson and Braden — and he began serving a six-year sentence at the U.S. Penitentiary in Lewisburg in October 1961.\n\nBy this point Scales had publicly resigned from the Communist Party (in 1957, after Khrushchevs revelations about Stalin) and made clear that he would not testify against former comrades. He spent fifteen months at Lewisburg before President Kennedy commuted his sentence on Christmas Eve 1962. He spent the remainder of his life as a printers union proofreader at the New York Times and as the author of Cause at Heart (1987), one of the most widely read first-person accounts of the McCarthy-era left.","state":"North Carolina","race":"White","gender":"Male","birthdate":"1920-03-26","death_date":"2002-08-05","ideologies":["Communism (former)","First Amendment"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Lewisburg","institution_city":"Lewisburg","institution_state":"Pennsylvania","charges":"Membership in an organization advocating the violent overthrow of the United States (Smith Act of 1940 membership clause)","arrest_date":"1954-11-18","incarceration_date":"1961-10-02","release_date":"1962-12-24","sentence":"6 years federal prison; sentence commuted by President Kennedy on Christmas Eve 1962 after 15 months served","convicted":"Yes — federal jury verdict 1958 (after 1957 Supreme Court reversal of his 1955 conviction); affirmed by U.S. Supreme Court 5–4 in Scales v. United States, 367 U.S. 203 (1961). The only American ever imprisoned under the Smith Acts membership clause."}]}'

# ============================================================
# Amend existing Eugene Dennis entry: add the 1947 contempt case
# ============================================================

php artisan tinker --execute='
$prisoner = App\Models\Prisoner::where("name","Eugene Dennis")->first();
if (!$prisoner) { echo "Eugene Dennis not found\n"; exit; }
$inst = App\Models\Institution::firstOrCreate(
  ["name" => "Federal Correctional Institution, Petersburg"],
  ["city" => "Petersburg", "state" => "Virginia"]
);
App\Models\PrisonerCase::create([
  "prisoner_id" => $prisoner->id,
  "institution_id" => $inst->id,
  "charges" => "Contempt of Congress — refusing on First Amendment grounds to be sworn in as a witness before the House Un-American Activities Committee",
  "incarceration_date" => "1947-07-01",
  "release_date" => "1948-07-01",
  "sentence" => "1 year federal prison — his first imprisonment, before the more famous 1949 Smith Act conspiracy case",
  "convicted" => "Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1947",
]);
echo "Added 1947 contempt case to Eugene Dennis\n";
'

echo
echo "All 7 prisoner adds + Eugene Dennis amendment complete."
