#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round3_anti_repression_sources.sh
#
# Adds 12 more prisoners cross-referenced from the Anarchist Black Cross
# Federation "Illustrated Guide to Political Prisoners and POWs" v19.3
# (April 2026), the Uprising Support post-2020 defendant compilation,
# and the Williamsburg 4 stragglers documented in the Salih Ali Abdullah
# and Dawud Abdur Rahman Jericho profiles.
set -e

# ============================================================
# Williamsburg 4 stragglers
# ============================================================

php artisan prisoner:add '{"name":"Shuaib Abdur Raheem","first_name":"Shuaib","last_name":"Abdur Raheem","description":"Shuaib Abdur Raheem was the eldest of the four young Sunni Muslim men known as the Williamsburg Four. On January 18, 1973 — the same day members of the Nation of Islam murdered seven Sunni Muslims, including children, in the Washington, D.C. home of Hamaas Abdul Khaalis (the Hanafi Massacre) — he led Dawud Abdur Rahman, Yusuf A. Mussadiq, and Salih Ali Abdullah into John and Als Sporting Goods at Broadway and Melrose Street in Bushwick, Brooklyn, intending to acquire weapons to defend Sunni Muslim communities in New York from anticipated attack. A patron alerted the NYPD; the four attempted to surrender almost immediately but were fired on at the back door and forced back inside. The forty-eight-hour police siege that followed killed NYPD Officer Stephen Gilroy, who the defense and witnesses inside the store later confirmed had been shot by NYPD gunfire, not by the defendants.\n\nThe four were convicted in June 1974 of Officer Gilroys murder and sentenced to twenty-five years to life. Shuaib was granted parole in 2007 after serving 32 years; the parole grant was rescinded after a campaign by the NYPD and its supporters. He was finally released on parole on July 2, 2010, after 35 years in New York state prison.","state":"New York","race":"Black","gender":"Male","ideologies":["Sunni Islam","Black community self-defense"],"affiliation":["Williamsburg 4"],"in_custody":false,"released":true,"cases":[{"institution_name":"Eastern New York Correctional Facility","institution_city":"Napanoch","institution_state":"New York","charges":"Murder of NYPD Officer Stephen Gilroy during the January 1973 Bushwick police siege","arrest_date":"1973-01-19","incarceration_date":"1973-01-19","release_date":"2010-07-02","sentence":"25 years to life; paroled July 2010 after 35 years (initial 2007 parole grant rescinded after NYPD campaign)","convicted":"Yes — New York state jury verdict, June 1974"}]}'

php artisan prisoner:add '{"name":"Yusuf A. Mussadiq","first_name":"Yusuf","middle_name":"A.","last_name":"Mussadiq","description":"Yusuf A. Mussadiq was one of the four young Sunni Muslim men known as the Williamsburg Four. On January 18, 1973 he, with Shuaib Abdur Raheem, Dawud Abdur Rahman, and Salih Ali Abdullah, entered John and Als Sporting Goods at Broadway and Melrose Street in Bushwick, Brooklyn intending to acquire weapons to defend Sunni Muslim communities in New York after that days murders of seven Sunni Muslims by members of the Nation of Islam in Washington, D.C. (the Hanafi Massacre). The forty-eight-hour police siege that followed killed NYPD Officer Stephen Gilroy in police gunfire that the defense argued and inside-store witnesses later confirmed had not come from the defendants.\n\nThe four were convicted in June 1974 of Officer Gilroys murder and sentenced to twenty-five years to life. Mussadiq served twenty-five years before suffering a massive stroke that left him partially incapacitated. He was released on medical parole in 1998 and died on January 1, 2003.","state":"New York","race":"Black","gender":"Male","death_date":"2003-01-01","ideologies":["Sunni Islam","Black community self-defense"],"affiliation":["Williamsburg 4"],"in_custody":false,"released":true,"cases":[{"institution_name":"New York State Department of Corrections","institution_state":"New York","charges":"Murder of NYPD Officer Stephen Gilroy during the January 1973 Bushwick police siege","arrest_date":"1973-01-19","incarceration_date":"1973-01-19","release_date":"1998-12-01","sentence":"25 years to life; medical parole in 1998 after a stroke; died January 2003","convicted":"Yes — New York state jury verdict, June 1974"}]}'

# ============================================================
# ABCF v19.3 gaps
# ============================================================

php artisan prisoner:add '{"name":"Hridindu Roychowdhury","first_name":"Hridindu","last_name":"Roychowdhury","description":"Hridindu Roychowdhury is an anarchist and former PhD student who in May 2022 — in the days following the leak of the U.S. Supreme Court draft opinion in Dobbs v. Jackson Womens Health Organization, which would overturn Roe v. Wade — set fire to the Madison, Wisconsin headquarters of Wisconsin Family Action, an anti-abortion lobbying group. Care was taken that no one was inside, and the only injuries were to the building. The graffiti left at the scene read: IF ABORTIONS ARENT SAFE, THEN YOU ARENT EITHER.\n\nThe FBI built its case against him by recovering DNA from a discarded burrito he had thrown out near the scene. He was indicted on federal arson and use-of-fire charges. In a non-cooperating plea agreement he pleaded guilty and accepted responsibility, and was sentenced to 90 months in federal prison. He is held at FCI Thomson, Illinois, federal inmate number 51111-510. The Anarchist Black Cross Federation lists him among its current anarchist movement political prisoners.","state":"Wisconsin","race":"Asian","gender":"Male","ideologies":["Anarchism","Reproductive rights"],"affiliation":[],"inmate_number":"51111-510","in_custody":true,"released":false,"cases":[{"institution_name":"FCI Thomson","institution_city":"Thomson","institution_state":"Illinois","charges":"Federal arson and use of fire to commit a federal felony — May 2022 attempted arson of the Wisconsin Family Action headquarters in Madison, in protest of the Supreme Courts pending Dobbs decision","arrest_date":"2023-03-29","incarceration_date":"2023-12-15","sentence":"90 months federal prison","convicted":"Yes — guilty plea (non-cooperating), 2023"}]}'

php artisan prisoner:add '{"name":"Andrew Mickel","first_name":"Andrew","last_name":"Mickel","description":"Andrew Hampton McCrae Mickel shot and killed Red Bluff, California police officer David Mobilio at a gas station on November 19, 2002. There were no eyewitnesses to the killing and the case might have gone unsolved had Mickel not posted to an internet anti-government discussion site six days later: Hello Everyone, my name’s Andy. I killed a Police Officer in Red Bluff, California in a motion to bring attention to, and halt, the police-state tactics that have come to be used throughout our country. He surrendered to authorities in Olympia, Washington shortly afterward.\n\nHe represented himself at trial in Tehama County in 2005 and presented a political defense, arguing the killing had been a justified act of resistance against the U.S. police state. The jury convicted him of one count of first-degree murder. He was sentenced to death in November 2005 and is held on Death Row at San Quentin State Prison, California Department of Corrections inmate number V77400. The Anarchist Black Cross Federation lists him among its current anti-police political prisoners.","state":"California","race":"White","gender":"Male","birthdate":"1979-01-01","ideologies":["Anti-police","Anti-government"],"inmate_number":"V77400","in_custody":true,"released":false,"cases":[{"institution_name":"San Quentin State Prison (Death Row)","institution_city":"San Quentin","institution_state":"California","charges":"First-degree murder of Red Bluff, California police officer David Mobilio (November 19, 2002)","arrest_date":"2002-11-26","incarceration_date":"2005-11-01","sentence":"Death — held on Death Row at San Quentin","convicted":"Yes — Tehama County, California jury verdict, April 2005"}]}'

# ============================================================
# Post-2020 Uprising Support defendants
# ============================================================

php artisan prisoner:add '{"name":"Christopher Tindal","first_name":"Christopher","last_name":"Tindal","description":"Christopher Tindal is a Rochester, New York father who was arrested in May 2020 in connection with the arson of a Rochester police car during the protests that followed the police murder of George Floyd. He pleaded guilty to a riot charge, which carried a lesser sentence than the underlying arson charge, and was sentenced to five years in federal prison. He is held at the United States Penitentiary at Big Sandy, Inez, Kentucky, federal inmate number 04392-509.\n\nIn his own words: What led up to me protesting George Floyd’s murder in 2020 was that all my life I’ve had run-ins with the police. I know what its like to be pinned under legs and knees, yelling I can’t breathe while foolish cops go stop yelling, then you’ll be able to breathe.","state":"New York","race":"Black","gender":"Male","ideologies":["Anti-police"],"inmate_number":"04392-509","in_custody":true,"released":false,"cases":[{"institution_name":"USP Big Sandy","institution_city":"Inez","institution_state":"Kentucky","charges":"Riot — arson of a Rochester, New York police car during the protests following the police murder of George Floyd","arrest_date":"2020-05-30","incarceration_date":"2020-05-30","sentence":"5 years federal prison","convicted":"Yes — guilty plea to riot count"}]}'

php artisan prisoner:add '{"name":"Khalif Miller","first_name":"Khalif","last_name":"Miller","description":"Khalif Miller is a North Philadelphia father and small business owner indicted in October 2020 by Trump U.S. Attorney General William Barrs Department of Justice on federal charges arising from the May–June 2020 protests in Philadelphia following the police murder of George Floyd. He was one of five Philadelphians charged in a coordinated indictment alongside Ant Smith. He was held on pretrial detention for two years before pleading and was sentenced to five years in federal prison. Because he was on probation at the time of his indictment, he was given an additional 1 to 10 year Pennsylvania state sentence for probation violation, to which he is now serving after completing his federal time. The Uprising Support project documented his case as one of the most aggressive examples of federal prosecution of 2020 uprising defendants.","state":"Pennsylvania","race":"Black","gender":"Male","ideologies":["Anti-police"],"inmate_number":"QQ9287","in_custody":true,"released":false,"cases":[{"institution_name":"SCI Forest","institution_city":"Marienville","institution_state":"Pennsylvania","charges":"Federal indictment by Trump AG William Barr arising from the 2020 Philadelphia protests following the police murder of George Floyd; subsequent Pennsylvania state probation violation sentence","arrest_date":"2020-10-15","incarceration_date":"2020-10-15","sentence":"5 years federal prison + 1 to 10 years Pennsylvania state for probation violation","convicted":"Yes — federal guilty plea after 2 years of pretrial detention; subsequent state probation violation"}]}'

php artisan prisoner:add '{"name":"Mujera Benjamin Lunga’ho","first_name":"Mujera","middle_name":"Benjamin","last_name":"Lunga’ho","description":"Mujera Benjamin Lunga’ho is a Little Rock, Arkansas defendant in the federal prosecution of the 2020 Little Rock uprising defendants — four people federally charged for the torching of Little Rock police vehicles during the protests that followed the police murder of George Floyd. He was incarcerated from September 2021 onward, and after pleading guilty to arson in August 2023 he was sentenced to five and a half years in federal prison. He is held at FCI Beaumont Medium in Texas, federal inmate number 08572-509. His three co-defendants — Renea Goddard, Cody Nowlin, and Angel Espinosa-Villegas — each received 18-month sentences on lesser explosives or conspiracy counts.","state":"Arkansas","race":"Black","gender":"Male","ideologies":["Anti-police"],"inmate_number":"08572-509","in_custody":true,"released":false,"cases":[{"institution_name":"FCI Beaumont Medium","institution_city":"Beaumont","institution_state":"Texas","charges":"Federal arson — torching of Little Rock, Arkansas police vehicles during the 2020 protests following the police murder of George Floyd","arrest_date":"2021-09-15","incarceration_date":"2021-09-15","sentence":"5.5 years federal prison","convicted":"Yes — guilty plea, August 2023"}]}'

php artisan prisoner:add '{"name":"Angel Espinosa-Villegas","first_name":"Angel","last_name":"Espinosa-Villegas","aka":"Loba","description":"Angel Espinosa-Villegas is a Chilean-born trans butch lesbian organizer who came to the United States at age seven and built her life in Chicago. She was one of the four Little Rock, Arkansas defendants — alongside Mujera Benjamin Lunga’ho, Renea Goddard, and Cody Nowlin — federally prosecuted for the torching of Little Rock police vehicles during the protests following the police murder of George Floyd. In September 2022 she pleaded guilty to possession of a Molotov cocktail and was sentenced to 18 months in federal prison, which she served at the Federal Medical Center at Carswell in Fort Worth, Texas.\n\nOn April 1, 2025, at the end of her federal sentence, she was taken into ICE custody for deportation to Chile. After several months in immigration detention she was deported and reunited with family in Chile, separated from her partner, family, and community in the United States.","state":"Arkansas","race":"Hispanic","gender":"Female","ideologies":["Anti-police","LGBTQ rights"],"in_custody":false,"released":true,"in_exile":true,"cases":[{"institution_name":"Federal Medical Center, Carswell","institution_city":"Fort Worth","institution_state":"Texas","charges":"Possession of a Molotov cocktail — Little Rock, Arkansas police-vehicle arsons during 2020 George Floyd protests","incarceration_date":"2024-01-01","release_date":"2025-04-01","sentence":"18 months federal prison + ICE detention pending deportation to Chile","convicted":"Yes — guilty plea, September 2022"}]}'

php artisan prisoner:add '{"name":"Alvin Joseph","first_name":"Alvin","last_name":"Joseph","description":"Alvin Joseph is a Gwinnett County, Georgia defendant who was arrested in June 2020 on federal charges of attempted arson of police vehicles during the protests that followed the police murder of George Floyd. He was held without bond at the Robert A. Deyton Detention Facility for nearly two years pretrial. After pleading guilty to attempted arson he was sentenced on March 8, 2022. He served his sentence in the federal Bureau of Prisons and was released in summer 2025.","state":"Georgia","race":"Black","gender":"Male","ideologies":["Anti-police"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Attempted arson of police vehicles in Gwinnett County, Georgia during the 2020 George Floyd protests","arrest_date":"2020-06-01","incarceration_date":"2020-06-01","release_date":"2025-08-01","sentence":"Federal sentence imposed March 2022; released summer 2025","convicted":"Yes — guilty plea, 2022"}]}'

php artisan prisoner:add '{"name":"Tyre Means","first_name":"Tyre","last_name":"Means","description":"Tyre Means was a Seattle defendant in the May 30, 2020 downtown Seattle protests following the police murder of George Floyd. He pleaded guilty in March 2021 to one count of arson and one count of possession of a stolen firearm, and was sentenced to five years in federal prison. At his sentencing he told the judge: the days of just rolling over to police brutality are over. He served his sentence and was released in August 2025.","state":"Washington","race":"Black","gender":"Male","ideologies":["Anti-police"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Washington","charges":"Federal arson and possession of a stolen firearm — May 30, 2020 Seattle protests following the police murder of George Floyd","arrest_date":"2020-06-15","incarceration_date":"2020-06-15","release_date":"2025-08-01","sentence":"5 years federal prison","convicted":"Yes — guilty plea, March 2021"}]}'

php artisan prisoner:add '{"name":"Renea Goddard","first_name":"Renea","last_name":"Goddard","description":"Renea Goddard is one of the four Little Rock, Arkansas defendants — alongside Mujera Benjamin Lunga’ho, Cody Nowlin, and Angel Espinosa-Villegas — federally prosecuted for the torching of Little Rock police vehicles during the protests that followed the police murder of George Floyd. In September 2022 she pleaded guilty to conspiracy to possess a Molotov cocktail and was sentenced to 18 months in federal prison. She began her sentence in 2024.","state":"Arkansas","race":"Black","gender":"Female","ideologies":["Anti-police"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to possess a Molotov cocktail — Little Rock, Arkansas police-vehicle arsons during 2020 George Floyd protests","incarceration_date":"2024-01-01","sentence":"18 months federal prison","convicted":"Yes — guilty plea, September 2022"}]}'

php artisan prisoner:add '{"name":"Cody Nowlin","first_name":"Cody","last_name":"Nowlin","description":"Cody Nowlin is one of the four Little Rock, Arkansas defendants — alongside Mujera Benjamin Lunga’ho, Renea Goddard, and Angel Espinosa-Villegas — federally prosecuted for the torching of Little Rock police vehicles during the protests that followed the police murder of George Floyd. In September 2022 he pleaded guilty to possession of a Molotov cocktail and was sentenced to 18 months in federal prison. He began his sentence in 2024.","state":"Arkansas","race":"White","gender":"Male","ideologies":["Anti-police"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Possession of a Molotov cocktail — Little Rock, Arkansas police-vehicle arsons during 2020 George Floyd protests","incarceration_date":"2024-01-01","sentence":"18 months federal prison","convicted":"Yes — guilty plea, September 2022"}]}'

echo
echo "All 12 round-3 anti-repression-source adds complete."
