#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round4_uprising_postrelease.sh
#
# Source: Uprising Support — https://uprisingsupport.org/postrelease/
# 11 defendants from the 2020 George Floyd uprising who served federal or
# state prison time and have been released between Feb 2022 and late 2024.
# Each is independently documented on the Uprising Support post-release page.
set -e

php artisan prisoner:add '{"name":"Anthony Smith","first_name":"Anthony","last_name":"Smith","aka":"Ant","description":"Anthony \"Ant\" Smith is a Black North Philadelphian indicted in October 2020 by Trump U.S. Attorney General William Barrs Department of Justice on federal charges arising from the May–June 2020 protests in Philadelphia following the police murder of George Floyd. He was one of five Philadelphians charged in a coordinated federal indictment alongside co-defendant Khalif Miller. He served substantial federal prison time and was released in August 2024. His support committee organized under the @FreeAntPHL handle on Twitter and Instagram.","state":"Pennsylvania","race":"Black","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal charges arising from the 2020 Philadelphia protests following the police murder of George Floyd; one of five Philadelphians indicted by Trump AG William Barr","arrest_date":"2020-10-15","incarceration_date":"2020-10-15","release_date":"2024-08-31","sentence":"Federal prison; full sentence and release facility pending verification against primary source","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Richard Hunsinger","first_name":"Richard","last_name":"Hunsinger","description":"Richard Hunsinger is an Atlanta-area protester who was arrested and federally charged in connection with a 2020 demonstration at the Department of Homeland Security office in Atlanta during the George Floyd uprising. He served years in federal prison and was released in late November 2024. His support committee organized a post-release fundraiser; Uprising Support documents his case on the post-release page.","state":"Georgia","race":"Unknown","gender":"Male","ideologies":["Anti-police","Anti-ICE"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal charges arising from a 2020 demonstration at the Department of Homeland Security office in Atlanta during the George Floyd uprising","arrest_date":"2020-01-01","incarceration_date":"2020-01-01","release_date":"2024-11-30","sentence":"Federal prison; full sentence and release facility pending verification against primary source","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"John Wade","first_name":"John","last_name":"Wade","description":"John Wade is a Georgia community organizer who was incarcerated for years on charges arising from the 2020 George Floyd uprising in Georgia. He was released in June 2024 alongside co-defendant Ellie Brett. After release he intended to continue community organizing with interests in food justice, animal rights advocacy, and veganism. He was re-arrested in October 2024; the Atlanta IWOC and a community GoFundMe organized to free him again. The Uprising Support project documents his case on the post-release page.","state":"Georgia","race":"Unknown","gender":"Male","ideologies":["Anti-police"],"affiliation":["Atlanta IWOC"],"in_custody":true,"released":false,"cases":[{"institution_name":"Georgia Department of Corrections","institution_state":"Georgia","charges":"Charges arising from the 2020 George Floyd uprising in Georgia; re-arrested October 2024","arrest_date":"2020-01-01","incarceration_date":"2020-01-01","release_date":"2024-06-30","sentence":"Years incarcerated, released June 2024, re-arrested October 2024","convicted":"Yes"}]}'

php artisan prisoner:add '{"name":"Ellie Brett","first_name":"Ellie","last_name":"Brett","description":"Ellie Brett is a Georgia uprising defendant who was incarcerated for years on charges arising from the 2020 George Floyd uprising in Georgia and released in June 2024 alongside co-defendant John Wade. After release Ellie hoped to start a barber shop, reconnect with his child, and get back involved with community organizing. The Uprising Support project documents his case on the post-release page.","state":"Georgia","race":"Unknown","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Georgia Department of Corrections","institution_state":"Georgia","charges":"Charges arising from the 2020 George Floyd uprising in Georgia","arrest_date":"2020-01-01","incarceration_date":"2020-01-01","release_date":"2024-06-30","sentence":"Years incarcerated, released June 2024","convicted":"Yes"}]}'

php artisan prisoner:add '{"name":"Howard Nall","first_name":"Howard","last_name":"Nall","description":"Howard Nall served prison time on charges arising from the 2020 George Floyd uprising and was released in fall 2024. The Uprising Support project documents his case on the post-release page; supporters organized for his post-release reentry through CashApp $cominghome1053.","state":"Unknown","race":"Unknown","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Unknown","charges":"Charges arising from the 2020 George Floyd uprising","release_date":"2024-10-31","sentence":"Released fall 2024; full sentence and incarceration facility pending verification against primary source","convicted":"Yes"}]}'

php artisan prisoner:add '{"name":"Hassan Muhammad","first_name":"Hassan","last_name":"Muhammad","aka":"Vibez","description":"Hassan Muhammad, also known as Vibez, is an African American antifascist activist, poet, songwriter, and promoter from Portland, Oregon. He was incarcerated on charges connected to the 2020 George Floyd uprising and antifascist organizing in Portland. He was released in May 2024. After release he organized a GoFundMe for his mother, who experienced significant financial and medical hardship during his incarceration. He has continued writing publicly, including essays for the RIOT Revolt blog. The Uprising Support project documents his case on the post-release page.","state":"Oregon","race":"Black","gender":"Male","ideologies":["Anti-fascism","Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Charges arising from the 2020 George Floyd uprising and antifascist organizing in Portland, Oregon","release_date":"2024-05-31","sentence":"Federal prison; full sentence and release facility pending verification against primary source","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Adam Walton","first_name":"Adam","last_name":"Walton","description":"Adam Walton is a Black father of two from Chicago who was arrested in May 2020 during the George Floyd Uprising for Black lives. He was held in pretrial detention for over 18 months at Cook County Jail and the federal Metropolitan Correctional Center, Chicago. In December 2021 he was sentenced to 43 months in federal prison. He was released to a halfway house in summer 2023. His mother, with whom he was very close, passed away before his release. The Uprising Support project documents his case on the post-release page.","state":"Illinois","race":"Black","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (released to halfway house)","institution_state":"Illinois","charges":"Federal charges arising from a May 2020 George Floyd uprising protest in Chicago","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","sentenced_date":"2021-12-01","release_date":"2023-08-31","sentence":"43 months in federal prison","convicted":"Yes — sentenced December 2021 in U.S. District Court for the Northern District of Illinois"}]}'

php artisan prisoner:add '{"name":"Dajon Lengyel","first_name":"Dajon","last_name":"Lengyel","aka":"Da Jon Lengyel","description":"Dajon Lengyel is a young African American man from Pittsburgh who was 25 years old at the time of his arrest in connection with the George Floyd protests in Pittsburgh. Despite no clear evidence that he started the fire, he was convicted of conspiracy to commit arson on a police vehicle and sentenced to 27 months in federal prison. His support fundraiser noted that he was standing up against police brutality and unfair treatment of African Americans, and felt he could no longer be a bystander to the injustices on his people. He was released in summer 2023. The Uprising Support project documents his case on the post-release page.","state":"Pennsylvania","race":"Black","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Pennsylvania","charges":"Federal conspiracy to commit arson on a Pittsburgh police vehicle during 2020 George Floyd uprising protests","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","release_date":"2023-08-31","sentence":"27 months federal prison","convicted":"Yes — federal conspiracy-to-commit-arson conviction"}]}'

php artisan prisoner:add '{"name":"Jacob Gaines","first_name":"Jacob","last_name":"Gaines","description":"Jacob Gaines is a Texas-born nomadic musician who was active in Portland, Oregon during the 2020 George Floyd uprising and protests against the deployment of federal officers in downtown Portland. In July 2020, during one of the federal-officer confrontations in Downtown Portland, he was arrested and charged with assaulting a federal officer with a deadly or dangerous weapon. He pleaded guilty in September 2021. He was released from federal custody in spring 2023. The Uprising Support project documents his case on the post-release page.","state":"Oregon","race":"Unknown","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal assault on a federal officer with a deadly or dangerous weapon during a July 2020 protest in Downtown Portland","arrest_date":"2020-07-31","incarceration_date":"2020-07-31","sentenced_date":"2021-09-01","release_date":"2023-05-31","sentence":"Federal prison; full sentence pending verification against primary source","convicted":"Yes — federal guilty plea, September 2021"}]}'

php artisan prisoner:add '{"name":"Isaiah Willoughby","first_name":"Isaiah","last_name":"Willoughby","description":"Isaiah Willoughby was arrested and federally charged with one count of arson in connection with a fire at the Seattle Police Department East Precinct during the June 2020 Capitol Hill protests after the police murder of George Floyd. He served federal prison time and was released in March 2022. He was interviewed about his case on the Kite Line prison radio program. He and others facing repression in the Pacific Northwest are supported by Puget Sound Prisoner Support. The Uprising Support project documents his case on the post-release page.","state":"Washington","race":"Black","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Washington","charges":"Federal arson — fire at the Seattle Police Department East Precinct, June 2020 Capitol Hill protests","arrest_date":"2020-06-30","incarceration_date":"2020-06-30","release_date":"2022-03-31","sentence":"Federal arson sentence; full sentence pending verification against primary source","convicted":"Yes — federal arson conviction"}]}'

php artisan prisoner:add '{"name":"Shawn Sutton","first_name":"Shawn","last_name":"Sutton","description":"Shawn Sutton served prison time in North Carolina on charges arising from her participation in 2020 George Floyd uprising protests in Greenville, North Carolina. She was released in February 2022. She was interviewed about her experience and background by Its Going Down for the piece \"The World Was Not At Peace: A Timeline And Interview With A Former Prisoner Of George Floyd Uprising In North Carolina.\" The Uprising Support project documents her case on the post-release page.","state":"North Carolina","race":"Unknown","gender":"Female","ideologies":["Anti-police"],"affiliation":[],"in_custody":false,"released":true,"cases":[{"institution_name":"North Carolina Department of Public Safety","institution_state":"North Carolina","charges":"Charges arising from 2020 George Floyd uprising protests in Greenville, North Carolina","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","release_date":"2022-02-28","sentence":"State prison; full sentence pending verification against primary source","convicted":"Yes — North Carolina state conviction"}]}'

echo
echo "Round 4 (Uprising Postrelease) adds complete."
