#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_palestine_2025_wave.sh
#
# Additional 2025-wave Palestine-solidarity ICE / immigration-action cases
# beyond the four already added (Khalil, Ozturk, Mahdawi, Suri):
#   - Yunseo Chung (Columbia, Korean green-card, judge blocked ICE detention)
#   - Ranjani Srinivasan (Columbia, Indian, self-exiled to Canada)
#   - Momodou Taal (Cornell, dual UK-Gambian, self-exiled)
#   - Rasha Alawieh (Brown Medicine, Lebanese, deported in violation of
#     federal court order)
#
# Each php artisan call wrapped in `|| true` for safe re-runs.
set -e

# === Yunseo Chung — Columbia (March 2025) ===

php artisan prisoner:add '{"name":"Yunseo Chung","first_name":"Yunseo","last_name":"Chung","description":"Yunseo Chung is a 21-year-old Columbia University undergraduate, a green-card holder who was brought to the United States from South Korea at age 7. She was arrested at and given a citation during a March 5, 2025 sit-in at Barnard College protesting Columbias disciplinary actions against pro-Palestine student organizers. After Mahmoud Khalils March 8 ICE arrest, federal officers attempted twice to detain her — once at her family home in New Jersey and once with a search warrant at her Columbia residence hall. Her attorneys filed a TRO, and Judge Naomi Reice Buchwald of the U.S. District Court for the Southern District of New York granted a temporary restraining order blocking ICE from arresting her. The TRO was extended on June 5, 2025; in October 2025 the court ruled that the State Departments use of the foreign-policy designation against her was unconstitutional retaliation for First Amendment-protected activity. The Department of Homeland Security has confirmed that the designation against her was personally signed by Secretary of State Marco Rubio.","state":"New York","race":"Asian","gender":"Female","ideologies":["Palestine solidarity","First Amendment"],"affiliation":["Columbia University","Columbia University Apartheid Divest"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"(detention blocked by federal court order)","institution_state":"New York","charges":"INA 8 USC 1227(a)(4)(C) - U.S. Secretary of State foreign-policy designation, based on March 5, 2025 Columbia/Barnard pro-Palestine sit-in citation","arrest_date":"2025-03-13","sentence":"Federal court TRO blocked ICE from detaining her; in October 2025 federal court ruled the foreign-policy designation against her was unconstitutional retaliation for protected speech","convicted":"No - civil immigration action; ICE detention blocked by federal court order"}]}' || true

# === Ranjani Srinivasan — Columbia (March 2025) ===

php artisan prisoner:add '{"name":"Ranjani Srinivasan","first_name":"Ranjani","last_name":"Srinivasan","description":"Dr. Ranjani Srinivasan is a 37-year-old Indian-national PhD candidate in Urban Planning at Columbia University and a former Fulbright scholar who had been studying in the United States since 2016. She was given two summonses for her presence at Columbia pro-Palestine protests in spring 2024 (the charges were ultimately dismissed); she did not disclose them on her most recent F-1 visa renewal. On March 5, 2025 the U.S. Department of State revoked her student visa under the foreign-policy designation, citing her alleged support for Hamas. ICE and DHS officers came to her Columbia apartment on March 7, 2025 attempting to arrest her. She fled the apartment, packed a single bag, and on March 11, 2025 boarded a flight from JFK to Toronto, Canada, where she stayed with friends and family.\n\nDHS Secretary Kristi Noem subsequently posted a video on X claiming that Srinivasan had used the U.S. Customs and Border Protection CBP Home app to self-deport — a characterization Srinivasan and her attorneys reject; she had simply left the country to avoid the ICE detention that was clearly imminent. Her departure is among the most prominent cases of pre-emptive flight from the U.S. by an academic Palestine-solidarity organizer in the 2025 wave.","state":"New York","race":"Asian","gender":"Female","ideologies":["Palestine solidarity","First Amendment"],"affiliation":["Columbia University"],"era":"2020s","in_custody":false,"released":false,"in_exile":true,"currently_in_exile":true,"imprisoned_or_exiled":true,"cases":[{"institution_name":"(fled to Canada to avoid ICE detention)","institution_state":"New York","charges":"INA foreign-policy designation by Secretary of State Marco Rubio; alleged failure to disclose Columbia-protest summonses on F-1 visa renewal","arrest_date":"2025-03-07","in_exile_since":"2025-03-11","sentence":"Visa revoked March 5, 2025; ICE attempted arrest March 7; fled to Canada via JFK March 11, 2025","convicted":"No - civil immigration action; never detained"}]}' || true

# === Momodou Taal — Cornell (March 2025) ===

php artisan prisoner:add '{"name":"Momodou Taal","first_name":"Momodou","last_name":"Taal","description":"Momodou Taal is a doctoral candidate in the Department of Africana Studies at Cornell University and a dual citizen of the United Kingdom and the Gambia. He was suspended twice by Cornell in 2024 for participating in pro-Palestine demonstrations; massive student and faculty protest restored his enrollment and visa each time. In March 2025, the U.S. Department of State revoked his student visa under the foreign-policy designation. On March 21, 2025 the Department of Homeland Security ordered him to surrender to ICE. He filed an emergency motion in the U.S. District Court for the Northern District of New York seeking to block his deportation. On March 28 Judge Elizabeth Coombe denied the emergency injunction.\n\nOn March 31, 2025 he announced via X: I have lost faith I could walk the streets without being abducted. He left the United States voluntarily that day rather than wait to be taken into ICE custody. His deportation order remained outstanding. He is the most prominent of the dual-citizen scholars to have left the United States in the 2025 wave.","state":"New York","race":"Black","gender":"Male","ideologies":["Palestine solidarity","Pan-Africanism","First Amendment"],"affiliation":["Cornell University","Cornell Coalition for Mutual Liberation"],"era":"2020s","in_custody":false,"released":false,"in_exile":true,"currently_in_exile":true,"imprisoned_or_exiled":true,"cases":[{"institution_name":"(left US to avoid ICE detention)","institution_state":"New York","charges":"INA foreign-policy designation by Secretary of State Marco Rubio; ICE surrender order","arrest_date":"2025-03-21","in_exile_since":"2025-03-31","sentence":"Visa revoked March 2025; ICE surrender order March 21; emergency injunction denied March 28; left US March 31, 2025","convicted":"No - civil immigration action; never detained"}]}' || true

# === Rasha Alawieh — Brown Medicine (March 2025) ===

php artisan prisoner:add '{"name":"Rasha Alawieh","first_name":"Rasha","last_name":"Alawieh","description":"Dr. Rasha Alawieh is a Lebanese kidney transplant specialist and assistant professor at Brown Medicine who held a valid H-1B work visa for her position at Brown. On March 14, 2025, returning to the United States from a family visit to Lebanon, she was detained on arrival at Logan International Airport in Boston. Customs and Border Protection officers questioned her for over 36 hours. The government cited photographs of Hezbollah leader Hasan Nasrallah, Iranian Supreme Leader Ali Khamenei, and Hezbollah fighters in her phones deleted-items folder. Alawieh acknowledged in the airport interview that she had attended Nasrallahs funeral in February 2025 because of his religious position in the Shia community.\n\nU.S. District Judge Leo Sorokin in the District of Massachusetts issued an emergency order on March 14 barring her removal from Massachusetts without 48 hours notice to the court. CBP officers nonetheless put her on a flight to Paris before the court order was, by their account, received; she was back in Lebanon by March 16, 2025 — deported in apparent violation of a federal court order. The deportation triggered a five-year U.S. re-entry ban. Her case became a leading example of the 2025 administrations willingness to override federal court orders blocking removals. In October 2025 Judge Sorokin dismissed her lawsuit, ruling he lacked authority to remove the five-year ban.","state":"Massachusetts","race":"Arab","gender":"Female","ideologies":["Shia religious solidarity","Palestine solidarity"],"affiliation":["Brown Medicine","Brown University"],"era":"2020s","in_custody":false,"released":false,"in_exile":true,"currently_in_exile":true,"imprisoned_or_exiled":true,"cases":[{"institution_name":"Logan International Airport (CBP detention) → deported to Lebanon","institution_state":"Massachusetts","charges":"H-1B visa revoked at port of entry under INA inadmissibility; deportation in apparent violation of federal court order","arrest_date":"2025-03-14","incarceration_date":"2025-03-14","release_date":"2025-03-16","in_exile_since":"2025-03-16","sentence":"36+ hours airport detention; deported to Lebanon via Paris March 16, 2025; 5-year US re-entry ban","convicted":"No - civil immigration action; deported in apparent violation of federal court order"}]}' || true

echo
echo "2025 Palestine wave additional adds complete."
