#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round6_historical_cases.sh
#
# Sources / case clusters:
#   - MOVE 9 — Aug 8, 1978 Powelton Village raid + 3rd-deg murder convictions
#     for the death of Officer James J. Ramp (each sentenced 30-100 years)
#   - FALN — Fuerzas Armadas de Liberacion Nacional Puertorriquena: 1980
#     Evanston arrests + 1983 Chicago arrests; 11 commuted by Clinton 1999,
#     Carlos Alberto Torres released 2010, Oscar Lopez Rivera released 2017
#     by Obama commutation
#   - Operation Backfire / "The Family" — FBI's 2005-2007 prosecution of
#     the Eugene-based ELF cell for $20M of eco-sabotage arsons 1996-2001;
#     terrorism-enhanced federal sentences 4-13 years
#   - SHAC 7 — first Animal Enterprise Terrorism Act federal prosecution,
#     Trenton NJ March 2006; six humans + the SHAC USA org as the seventh
#     defendant; sentences 1-6 years
#
# Each php artisan call is wrapped in `|| true` so a duplicate-name failure
# (the AddPrisoner command refuses on duplicate) does not halt the script.

# === MOVE 9 — Philadelphia, August 8, 1978 ===

php artisan prisoner:add '{"name":"Debbie Sims Africa","first_name":"Debbie","middle_name":"Sims","last_name":"Africa","description":"Debbie Sims Africa is a member of the MOVE organization, a Black revolutionary back-to-nature group founded in Philadelphia by John Africa. On August 8, 1978, Philadelphia police laid siege to the MOVE compound at 33rd and Powelton in West Philadelphia, attempting to evict its residents. During the gunfire that followed, Officer James J. Ramp was killed. MOVE members and their defense have always argued that the fatal shot came from police, not from any MOVE member. Nine MOVE members — Debbie, Janine, Janet, Phil, Mike, Delbert, Eddie, Charles (Chuck), and Merle Africa — were each convicted of third-degree murder of Officer Ramp and sentenced to 30 to 100 years in Pennsylvania state prison.\n\nDebbie Sims Africa was the first of the MOVE 9 to be paroled, on June 16, 2018, after 39 years and 10 months of imprisonment. Her son Mike Africa Jr., who was born in prison shortly after her arrest in 1978 and raised on the outside, led the post-release support campaign for the surviving MOVE 9.","state":"Pennsylvania","race":"Black","gender":"Female","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Philadelphia Police Officer James J. Ramp during the August 8, 1978 police raid on the MOVE compound at 33rd and Powelton","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2018-06-16","sentence":"30 to 100 years; paroled after 39 years 10 months","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Janine Phillips Africa","first_name":"Janine","middle_name":"Phillips","last_name":"Africa","description":"Janine Phillips Africa is a member of the MOVE organization arrested with eight others in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. The day Officer James J. Ramp was killed in the gunfire of the raid; MOVE has always contended the fatal shot came from police gunfire, not from any MOVE member. The MOVE 9 were each convicted of third-degree murder and sentenced to 30 to 100 years.\n\nJanine and Janet Africa were paroled together on May 25, 2019 after 41 years in Pennsylvania state prison.","state":"Pennsylvania","race":"Black","gender":"Female","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 police raid on the MOVE compound at 33rd and Powelton","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2019-05-25","sentence":"30 to 100 years; paroled after 41 years","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Janet Holloway Africa","first_name":"Janet","middle_name":"Holloway","last_name":"Africa","description":"Janet Holloway Africa is a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. She was convicted along with the rest of the MOVE 9 of the third-degree murder of Officer James J. Ramp, despite the defense argument that police gunfire had killed Ramp. She and Janine Africa were paroled together on May 25, 2019 after 41 years in Pennsylvania state prison.","state":"Pennsylvania","race":"Black","gender":"Female","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2019-05-25","sentence":"30 to 100 years; paroled after 41 years","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Mike Africa Sr","first_name":"Mike","last_name":"Africa","description":"Mike Africa Sr. is a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. He was convicted along with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. He was paroled on October 23, 2018 after 40 years in Pennsylvania state prison. His wife Debbie Sims Africa was also among the MOVE 9; their son Mike Africa Jr., born in prison shortly after his mothers arrest, became one of the central organizers of the campaign that won the parole of all surviving MOVE 9 members.","state":"Pennsylvania","race":"Black","gender":"Male","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2018-10-23","sentence":"30 to 100 years; paroled after 40 years","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Phil Africa","first_name":"Phil","last_name":"Africa","description":"Phil Africa was a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. He was convicted along with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. He died in Pennsylvania state prison on January 10, 2015 at age 59 — the second of the MOVE 9 to die behind bars, after Merle Africas death in 1998.","state":"Pennsylvania","race":"Black","gender":"Male","death_date":"2015-01-10","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":false,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","death_in_custody_date":"2015-01-10","sentence":"30 to 100 years; died in prison January 10, 2015","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Merle Africa","first_name":"Merle","last_name":"Africa","description":"Merle Africa was a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. She was convicted along with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. She died in Pennsylvania state prison in March 1998 at age 47 — the first of the MOVE 9 to die behind bars.","state":"Pennsylvania","race":"Black","gender":"Female","death_date":"1998-03-13","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":false,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","death_in_custody_date":"1998-03-13","sentence":"30 to 100 years; died in prison March 1998","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Delbert Orr Africa","first_name":"Delbert","middle_name":"Orr","last_name":"Africa","description":"Delbert Orr Africa was a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. As police led him out of the compound, three Philadelphia officers were filmed beating him with a rifle butt and a helmet — the assault was captured on television and the officers were later acquitted at a 1981 bench trial in a verdict widely considered a miscarriage of justice. He was convicted with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. He was granted parole on December 20, 2019 and released on January 18, 2020 after 41 years in Pennsylvania state prison. He died of cancer in June 2020, six months after his release.","state":"Pennsylvania","race":"Black","gender":"Male","death_date":"2020-06-13","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2020-01-18","sentence":"30 to 100 years; paroled January 2020 after 41 years; died of cancer June 2020","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Eddie Goodman Africa","first_name":"Eddie","middle_name":"Goodman","last_name":"Africa","description":"Eddie Goodman Africa is a member of the MOVE organization arrested with eight other MOVE members in the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. He was convicted along with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. He was paroled on June 21, 2019 after nearly 41 years in Pennsylvania state prison.","state":"Pennsylvania","race":"Black","gender":"Male","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2019-06-21","sentence":"30 to 100 years; paroled June 2019 after nearly 41 years","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

php artisan prisoner:add '{"name":"Charles Sims Africa","first_name":"Charles","middle_name":"Sims","last_name":"Africa","aka":"Chuck Africa","description":"Charles \"Chuck\" Sims Africa was the youngest of the MOVE 9, only 18 years old at the time of the August 8, 1978 Philadelphia police raid on the MOVE compound at 33rd and Powelton. He was convicted with the rest of the MOVE 9 of third-degree murder of Officer James J. Ramp. He was the last of the MOVE 9 either to be paroled or to die behind bars — released on February 7, 2020 after 41 years in Pennsylvania state prison. He died of cancer in 2021, less than two years after his release.","state":"Pennsylvania","race":"Black","gender":"Male","death_date":"2021-04-30","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Third-degree murder of Officer James J. Ramp — August 8, 1978 raid on the MOVE compound","arrest_date":"1978-08-08","incarceration_date":"1978-08-08","release_date":"2020-02-07","sentence":"30 to 100 years; paroled February 2020 after 41 years; died of cancer 2021","convicted":"Yes — third-degree murder, Philadelphia Court of Common Pleas, 1981"}]}' || true

# === FALN — Fuerzas Armadas de Liberacion Nacional Puertorriquena ===

php artisan prisoner:add '{"name":"Oscar Lopez Rivera","first_name":"Oscar","last_name":"Lopez Rivera","description":"Oscar López Rivera is a Puerto Rican independence leader, decorated U.S. Army Vietnam War veteran (Bronze Star), and one of the longest-held political prisoners in U.S. history. He was a leader of the Fuerzas Armadas de Liberación Nacional Puertorriqueña (FALN), the clandestine organization that conducted bombings of U.S. military, government, and corporate sites between 1974 and 1983 in support of Puerto Rican independence. He was arrested on May 29, 1981 in Glenview, Illinois, and convicted in 1981 of seditious conspiracy. He was sentenced to 55 years in federal prison; an additional 15 years was added in 1988 in connection with an alleged plot to escape from federal prison alongside Black Liberation Army member Kojo Bomani Sababu (Grailing Brown).\n\nIn 1999 President Clinton offered him clemency on the condition that he renounce violence; he refused as long as 11 of his FALN co-defendants remained imprisoned. Those 11 accepted Clintons clemency. He continued to serve. After 35 years in federal prison, on January 17, 2017 — three days before leaving office — President Obama commuted his sentence. He was released on May 17, 2017 to widespread celebration in Puerto Rico and a heros welcome at the Puerto Rican Day parade in New York City.","state":"Illinois","race":"Hispanic","gender":"Male","birthdate":"1943-01-06","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN","U.S. Army (Vietnam)"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy in support of Puerto Rican independence; subsequently 1988 conspiracy to escape from federal prison","arrest_date":"1981-05-29","incarceration_date":"1981-05-29","release_date":"2017-05-17","sentence":"55 years federal prison + 15 years for 1988 conspiracy = 70 years total; commuted by President Obama January 17, 2017 after 35 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Carlos Alberto Torres","first_name":"Carlos","middle_name":"Alberto","last_name":"Torres","description":"Carlos Alberto Torres was one of the leaders of the Fuerzas Armadas de Liberación Nacional Puertorriqueña (FALN). He was arrested in 1980 and convicted of seditious conspiracy in support of Puerto Rican independence. He was sentenced in 1980 to 78 years in federal prison. He refused President Clintons 1999 clemency offer in solidarity with the few FALN prisoners not included in that offer. After 30 years in federal prison he was released on parole on July 26, 2010 and returned to Puerto Rico to a heros welcome.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — leadership of the FALN in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"2010-07-26","sentence":"78 years federal prison; paroled after 30 years","convicted":"Yes — federal seditious conspiracy, 1980"}]}' || true

php artisan prisoner:add '{"name":"Elizam Escobar","first_name":"Elizam","last_name":"Escobar","description":"Elizam Escobar is a Puerto Rican independentista, painter, and political theorist who was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. He refused to participate in his trial, asserting that he did not recognize the authority of the United States over Puerto Rico, and was convicted of seditious conspiracy. He was sentenced to 60 years in federal prison and served 19 years before being released by President Clintons clemency on September 10, 1999. From inside prison he produced an internationally recognized body of paintings that has been exhibited at the Whitney Biennial and other major venues.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"60 years federal prison; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Ricardo Jimenez","first_name":"Ricardo","last_name":"Jimenez","description":"Ricardo Jimenez was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. He was convicted of seditious conspiracy and sentenced to a long federal prison term. He served 19 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Adolfo Matos","first_name":"Adolfo","last_name":"Matos","description":"Adolfo Matos was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. He was convicted of seditious conspiracy in support of Puerto Rican independence. He served 19 years in federal prison before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Dylcia Pagan","first_name":"Dylcia","middle_name":"Noemi","last_name":"Pagan","description":"Dylcia Pagán was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. She was convicted of seditious conspiracy and sentenced to 55 years in federal prison. She served 19 years before being released by President Clintons clemency on September 10, 1999. She was separated from her son for the duration of her imprisonment, and the family-separation aspect of the FALN cases became one of the central organizing themes of the international campaign for clemency.","state":"Illinois","race":"Hispanic","gender":"Female","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"55 years federal prison; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Alicia Rodriguez","first_name":"Alicia","last_name":"Rodriguez","description":"Alicia Rodriguez was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. She was convicted of seditious conspiracy in support of Puerto Rican independence and sentenced to a long federal prison term. She served 19 years before being released by President Clintons clemency on September 10, 1999. Her sister Ida Luz Rodriguez was arrested with her.","state":"Illinois","race":"Hispanic","gender":"Female","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Ida Luz Rodriguez","first_name":"Ida","middle_name":"Luz","last_name":"Rodriguez","description":"Ida Luz Rodriguez was one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. She was convicted of seditious conspiracy and sentenced to a long federal prison term. She served 19 years before being released by President Clintons clemency on September 10, 1999. Her sister Alicia Rodriguez was arrested with her.","state":"Illinois","race":"Hispanic","gender":"Female","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Luis Rosa","first_name":"Luis","last_name":"Rosa","description":"Luis Rosa was 19 years old, just out of high school, when he was arrested with 10 other FALN members on April 4, 1980 in Evanston, Illinois. He was convicted of seditious conspiracy in support of Puerto Rican independence and sentenced to 105 years in federal prison — the longest sentence of any of the 11 defendants. He served 19 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"105 years federal prison; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Carmen Valentin","first_name":"Carmen","last_name":"Valentin","description":"Carmen Valentín was a Chicago Public Schools teacher and one of 11 FALN members arrested on April 4, 1980 in Evanston, Illinois. She was convicted of seditious conspiracy in support of Puerto Rican independence and sentenced to a long federal prison term. She served 19 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Female","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1980-04-04","incarceration_date":"1980-04-04","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 19 years","convicted":"Yes — federal seditious conspiracy, 1981"}]}' || true

php artisan prisoner:add '{"name":"Edwin Cortes","first_name":"Edwin","last_name":"Cortes","description":"Edwin Cortés was arrested on June 29, 1983 in Chicago, in the second wave of FALN arrests, after FBI surveillance documented him allegedly providing bomb-making instruction. He was convicted of seditious conspiracy in support of Puerto Rican independence and sentenced to a long federal prison term. He served 16 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1983-06-29","incarceration_date":"1983-06-29","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 16 years","convicted":"Yes — federal seditious conspiracy, 1985"}]}' || true

php artisan prisoner:add '{"name":"Alberto Rodriguez","first_name":"Alberto","last_name":"Rodriguez","description":"Alberto Rodriguez was arrested on June 29, 1983 in Chicago, in the second wave of FALN arrests, after FBI surveillance documented him allegedly receiving bomb-making instruction from co-defendant Edwin Cortés. He was convicted of seditious conspiracy in support of Puerto Rican independence. He served 16 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Male","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1983-06-29","incarceration_date":"1983-06-29","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 16 years","convicted":"Yes — federal seditious conspiracy, 1985"}]}' || true

php artisan prisoner:add '{"name":"Alejandrina Torres","first_name":"Alejandrina","last_name":"Torres","description":"Alejandrina Torres was arrested on June 29, 1983 in Chicago, in the second wave of FALN arrests. She was convicted of seditious conspiracy in support of Puerto Rican independence. She served 16 years before being released by President Clintons clemency on September 10, 1999.","state":"Illinois","race":"Hispanic","gender":"Female","ideologies":["Puerto Rican Independence","Anti-imperialist"],"affiliation":["FALN"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Seditious conspiracy — FALN, in support of Puerto Rican independence","arrest_date":"1983-06-29","incarceration_date":"1983-06-29","release_date":"1999-09-10","sentence":"Long federal prison term; commuted by President Clinton September 1999 after 16 years","convicted":"Yes — federal seditious conspiracy, 1985"}]}' || true

# === Operation Backfire / The Family — Eugene ELF cell ===

php artisan prisoner:add '{"name":"Daniel McGowan","first_name":"Daniel","middle_name":"Gerard","last_name":"McGowan","description":"Daniel Gerard McGowan is a former environmental and social-justice activist who participated in two Earth Liberation Front arsons in Oregon in 2001 — the burning of Superior Lumber and the burning of Jefferson Poplar Farm — both targeted for their roles in old-growth timber harvest and genetically modified poplar research, respectively.\n\nHe was arrested in December 2005 in the FBIs Operation Backfire roundup of the Eugene-based ELF cell known as The Family. He pleaded guilty to two counts of arson and conspiracy in a non-cooperating plea agreement. On June 4, 2007 he was sentenced by federal Judge Ann Aiken to 84 months (7 years) in federal prison, with the federal terrorism enhancement applied. He served his sentence largely at the federal Communications Management Unit at Marion, Illinois, the most restrictive non-supermax facility in the federal system, and was released to a halfway house in 2012 and home in 2013. The 2011 documentary If a Tree Falls: A Story of the Earth Liberation Front, in which he is the central figure, was nominated for an Academy Award. He has since worked as an organizer with the Center for Constitutional Rights.","state":"Oregon","race":"White","gender":"Male","birthdate":"1974-04-11","ideologies":["Environmental","Anti-capitalist"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal arson and conspiracy — two Earth Liberation Front arsons in Oregon, 2001 (Superior Lumber and Jefferson Poplar Farm)","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","release_date":"2013-06-05","sentence":"84 months (7 years) federal prison with terrorism enhancement","convicted":"Yes — non-cooperating guilty plea, U.S. District Court for the District of Oregon, June 2007"}]}' || true

php artisan prisoner:add '{"name":"Chelsea Gerlach","first_name":"Chelsea","middle_name":"Dawn","last_name":"Gerlach","description":"Chelsea Dawn Gerlach was a member of the Eugene-based Earth Liberation Front cell known as The Family. She was charged in the FBIs December 2005 Operation Backfire roundup with arsons including the 1996 Oakridge Ranger Station fire, the 1998 burning of the Vail ski resort in Colorado (the largest ELF action ever, $12 million in damage), and the 2000 toppling of an Oregon BPA electrical transmission tower. She pleaded guilty in December 2006. On June 4, 2007 she was sentenced by federal Judge Ann Aiken to 108 months (9 years) in federal prison with the federal terrorism enhancement applied.","state":"Oregon","race":"White","gender":"Female","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front arsons including 1998 Vail ski resort, 1996 Oakridge Ranger Station, and 2000 BPA transmission tower","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"108 months (9 years) federal prison with terrorism enhancement","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, December 2006"}]}' || true

php artisan prisoner:add '{"name":"Jonathan Paul","first_name":"Jonathan","last_name":"Paul","description":"Jonathan Paul was a member of the Eugene-based Earth Liberation Front cell known as The Family. He was charged in the FBIs December 2005 Operation Backfire roundup. He pleaded guilty in November 2006 to participation in the 1997 burning of the Cavel West horse-slaughtering plant in Redmond, Oregon. On June 5, 2007 he was sentenced by federal Judge Ann Aiken to 51 months (4 years 3 months) in federal prison with the federal terrorism enhancement applied.","state":"Oregon","race":"White","gender":"Male","ideologies":["Environmental","Animal rights"],"affiliation":["Earth Liberation Front","Animal Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — 1997 burning of the Cavel West horse-slaughtering plant in Redmond, Oregon","arrest_date":"2005-12-07","incarceration_date":"2007-06-05","sentenced_date":"2007-06-05","sentence":"51 months (4 years 3 months) federal prison with terrorism enhancement","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, November 2006"}]}' || true

php artisan prisoner:add '{"name":"Joyanna Zacher","first_name":"Joyanna","last_name":"Zacher","description":"Joyanna Zacher was a member of the Eugene-based Earth Liberation Front cell known as The Family. She was charged in the FBIs Operation Backfire roundup and pleaded guilty in November 2006. On June 4, 2007 she was sentenced by federal Judge Ann Aiken to 92 months (7 years 8 months) in federal prison with the federal terrorism enhancement applied.","state":"Oregon","race":"White","gender":"Female","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front participation in The Family Eugene cell","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"92 months (7 years 8 months) federal prison with terrorism enhancement","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, November 2006"}]}' || true

php artisan prisoner:add '{"name":"Nathan Block","first_name":"Nathan","last_name":"Block","description":"Nathan Block was a member of the Eugene-based Earth Liberation Front cell known as The Family. He was charged in the FBIs Operation Backfire roundup and pleaded guilty in November 2006. On June 4, 2007 he was sentenced by federal Judge Ann Aiken to 92 months (7 years 8 months) in federal prison with the federal terrorism enhancement applied. He was the partner of co-defendant Joyanna Zacher.","state":"Oregon","race":"White","gender":"Male","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front participation in The Family Eugene cell","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"92 months (7 years 8 months) federal prison with terrorism enhancement","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, November 2006"}]}' || true

php artisan prisoner:add '{"name":"Kevin Tubbs","first_name":"Kevin","last_name":"Tubbs","description":"Kevin Tubbs was a member of the Eugene-based Earth Liberation Front cell known as The Family. He was charged in the FBIs December 2005 Operation Backfire roundup and pleaded guilty. On June 4, 2007 he was sentenced by federal Judge Ann Aiken to 151 months (approximately 12.6 years) in federal prison with the federal terrorism enhancement applied — among the longest of the Operation Backfire sentences.","state":"Oregon","race":"White","gender":"Male","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front participation in The Family Eugene cell","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"151 months (approximately 12.6 years) federal prison with terrorism enhancement","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, 2006-2007"}]}' || true

php artisan prisoner:add '{"name":"Suzanne Savoie","first_name":"Suzanne","last_name":"Savoie","description":"Suzanne Savoie was a member of the Eugene-based Earth Liberation Front cell known as The Family. She was charged in the FBIs December 2005 Operation Backfire roundup and pleaded guilty (with cooperation). On June 4, 2007 she was sentenced by federal Judge Ann Aiken to 51 months (4 years 3 months) in federal prison.","state":"Oregon","race":"White","gender":"Female","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front participation in The Family Eugene cell","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"51 months (4 years 3 months) federal prison","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, 2006-2007"}]}' || true

php artisan prisoner:add '{"name":"Briana Waters","first_name":"Briana","last_name":"Waters","description":"Briana Waters was charged with serving as a lookout during the May 21, 2001 Earth Liberation Front arson at the University of Washingtons Center for Urban Horticulture in Seattle, the largest single ELF action in the United States. She maintained her innocence and went to trial in March 2008 — the only Operation Backfire defendant to do so. The first trial ended in conviction on two counts of arson and a 6-year federal sentence, but the conviction was overturned on appeal in 2009 because of suppressed evidence about a government witness. She was retried, pleaded guilty in 2012, and was resentenced. She is also a violinist and music teacher; her young daughter visited her in federal prison throughout her incarceration.","state":"Washington","race":"White","gender":"Female","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Washington","charges":"Federal arson — May 21, 2001 ELF arson at University of Washington Center for Urban Horticulture","arrest_date":"2006-03-15","incarceration_date":"2008-03-06","release_date":"2014-03-31","sentence":"6 years federal prison (2008 conviction); reversed on appeal 2009; resentenced after 2012 plea","convicted":"Yes — federal jury verdict 2008 (reversed); 2012 guilty plea on retrial"}]}' || true

php artisan prisoner:add '{"name":"Rebecca Rubin","first_name":"Rebecca","middle_name":"Jeanette","last_name":"Rubin","description":"Rebecca Jeanette Rubin was a Canadian-American member of the Eugene-based Earth Liberation Front cell known as The Family. She fled to Canada at the time of the December 2005 FBI roundup and remained a fugitive for seven and a half years. She voluntarily surrendered to U.S. authorities in November 2012 and pleaded guilty in 2013 to conspiracy and arson in connection with the 1998 Vail ski resort fire and other ELF actions. On January 27, 2014 she was sentenced to 60 months (5 years) in federal prison.","state":"Oregon","race":"White","gender":"Female","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal conspiracy and arson — Earth Liberation Front participation including 1998 Vail ski resort fire","arrest_date":"2012-11-29","incarceration_date":"2014-01-27","sentenced_date":"2014-01-27","sentence":"60 months (5 years) federal prison","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, 2013"}]}' || true

php artisan prisoner:add '{"name":"Joseph Dibee","first_name":"Joseph","middle_name":"Mahmoud","last_name":"Dibee","description":"Joseph Mahmoud Dibee was a member of the Eugene-based Earth Liberation Front cell known as The Family. Charged in the FBIs December 2005 Operation Backfire indictment, he fled the United States and lived as a fugitive for nearly thirteen years, traveling between Russia, Cuba, Mexico, and Central America. He was apprehended in August 2018 by Cuban authorities and turned over to U.S. agents. He pleaded guilty in 2022 to conspiracy and arson and was sentenced in 2022 to time served plus probation, accepting responsibility for the 1997 burning of the Cavel West horse-slaughtering plant in Redmond, Oregon.","state":"Oregon","race":"Arab","gender":"Male","ideologies":["Environmental","Animal rights"],"affiliation":["Earth Liberation Front","Animal Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal conspiracy and arson — Earth Liberation Front, including 1997 Cavel West horse-slaughtering plant arson; fled abroad as a fugitive 2006-2018","arrest_date":"2018-08-09","incarceration_date":"2018-08-09","sentenced_date":"2022-12-01","sentence":"Time served plus probation","convicted":"Yes — guilty plea, U.S. District Court for the District of Oregon, 2022"}]}' || true

php artisan prisoner:add '{"name":"Stanislas Meyerhoff","first_name":"Stanislas","middle_name":"Gregory","last_name":"Meyerhoff","description":"Stanislas Gregory Meyerhoff was a member of the Eugene-based Earth Liberation Front cell known as The Family. He was charged in the FBIs December 2005 Operation Backfire roundup. He pleaded guilty in December 2006 in a cooperating plea, providing testimony against other defendants. He was sentenced on June 4, 2007 by federal Judge Ann Aiken to 156 months (13 years) in federal prison with the federal terrorism enhancement applied. (Despite his cooperation, his guilty plea was to substantive arson counts and his sentence was the longest of the Operation Backfire defendants other than Tubbs.)","state":"Oregon","race":"White","gender":"Male","ideologies":["Environmental"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Oregon","charges":"Federal arson and conspiracy — Earth Liberation Front participation in The Family Eugene cell, $20M of arsons 1996-2001","arrest_date":"2005-12-07","incarceration_date":"2007-06-04","sentenced_date":"2007-06-04","sentence":"156 months (13 years) federal prison with terrorism enhancement","convicted":"Yes — cooperating guilty plea, U.S. District Court for the District of Oregon, December 2006"}]}' || true

php artisan prisoner:add '{"name":"William Rodgers","first_name":"William","middle_name":"Cottrell","last_name":"Rodgers","aka":"Avalon","description":"William \"Avalon\" Cottrell Rodgers was a Prescott, Arizona bookstore owner and one of the central figures of the Eugene-based Earth Liberation Front cell known as The Family. He was arrested in December 2005 in the FBIs Operation Backfire roundup. He took his own life in the Coconino County Detention Facility in Flagstaff, Arizona on December 21, 2005 while awaiting trial — the first death of any Operation Backfire defendant. His suicide note read in part: I have chosen to leave to my own.","state":"Arizona","race":"White","gender":"Male","death_date":"2005-12-21","ideologies":["Environmental","Anti-capitalist"],"affiliation":["Earth Liberation Front"],"era":"2000s","in_custody":false,"released":false,"cases":[{"institution_name":"Coconino County Detention Facility","institution_city":"Flagstaff","institution_state":"Arizona","charges":"Federal conspiracy and arson — Earth Liberation Front participation in The Family Eugene cell, $20M of arsons 1996-2001","arrest_date":"2005-12-07","incarceration_date":"2005-12-07","death_in_custody_date":"2005-12-21","sentence":"Awaiting trial; took his own life in pretrial detention December 21, 2005","convicted":"No — died awaiting trial"}]}' || true

# === SHAC 7 — Stop Huntingdon Animal Cruelty USA, Trenton NJ March 2006 ===

php artisan prisoner:add '{"name":"Kevin Kjonaas","first_name":"Kevin","last_name":"Kjonaas","description":"Kevin Kjonaas was the President of Stop Huntingdon Animal Cruelty USA (SHAC USA), the U.S. arm of the international campaign to shut down the contract animal-research lab Huntingdon Life Sciences. He was indicted in May 2004 along with five other SHAC USA activists and the SHAC USA organization itself, in the first federal prosecution under the Animal Enterprise Terrorism Act. The defendants were charged with using the SHAC USA website and protests to incite stalking and harassment of HLS personnel and clients — none of the defendants were charged with personally engaging in any threatening communication or vandalism.\n\nA federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. Kjonaas received the longest sentence of the human defendants — 6 years in federal prison.","state":"New Jersey","race":"White","gender":"Male","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"New Jersey","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"6 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

php artisan prisoner:add '{"name":"Lauren Gazzola","first_name":"Lauren","last_name":"Gazzola","description":"Lauren Gazzola was the Campaign Coordinator of Stop Huntingdon Animal Cruelty USA. She was one of six SHAC USA activists indicted in May 2004 in the first federal prosecution under the Animal Enterprise Terrorism Act. A federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. She was sentenced to 4 years and 4 months in federal prison.","state":"New Jersey","race":"White","gender":"Female","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"New Jersey","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"4 years 4 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

php artisan prisoner:add '{"name":"Jacob Conroy","first_name":"Jacob","last_name":"Conroy","description":"Jacob Conroy was one of six SHAC USA activists indicted in May 2004 in the first federal prosecution under the Animal Enterprise Terrorism Act, charged with using the Stop Huntingdon Animal Cruelty USA website and protests to incite stalking and harassment of Huntingdon Life Sciences personnel and clients. A federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. He was sentenced to 4 years in federal prison.","state":"New Jersey","race":"White","gender":"Male","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"New Jersey","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"4 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

php artisan prisoner:add '{"name":"Joshua Harper","first_name":"Joshua","last_name":"Harper","description":"Joshua Harper was one of six SHAC USA activists indicted in May 2004 in the first federal prosecution under the Animal Enterprise Terrorism Act. A federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. He was sentenced to 3 years in federal prison.","state":"New Jersey","race":"White","gender":"Male","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"New Jersey","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

php artisan prisoner:add '{"name":"Andrew Stepanian","first_name":"Andrew","last_name":"Stepanian","description":"Andrew Stepanian was one of six SHAC USA activists indicted in May 2004 in the first federal prosecution under the Animal Enterprise Terrorism Act. A federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. He was sentenced to 3 years in federal prison and held part of his sentence at the federal Communications Management Unit at Marion, Illinois — making him one of the first non-Muslim political prisoners held in the CMU. After his release he became a leading public critic of the CMU regime.","state":"New Jersey","race":"White","gender":"Male","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

php artisan prisoner:add '{"name":"Darius Fullmer","first_name":"Darius","last_name":"Fullmer","description":"Darius Fullmer was one of six SHAC USA activists indicted in May 2004 in the first federal prosecution under the Animal Enterprise Terrorism Act. A federal jury in Trenton, New Jersey convicted the SHAC 7 in March 2006. He was sentenced to 1 year and 1 day in federal prison — the shortest of the human SHAC 7 sentences.","state":"New Jersey","race":"White","gender":"Male","ideologies":["Animal rights","First Amendment"],"affiliation":["Stop Huntingdon Animal Cruelty USA"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"New Jersey","charges":"Federal Animal Enterprise Protection Act and interstate stalking — first federal prosecution under the Animal Enterprise Terrorism Act","arrest_date":"2004-05-26","incarceration_date":"2006-09-12","sentenced_date":"2006-09-12","sentence":"1 year and 1 day federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of New Jersey, March 2006"}]}' || true

echo
echo "Round 6 (MOVE 9 + FALN + Operation Backfire + SHAC 7) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
