#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round11_more_whistleblowers_eco.sh
#
# Source clusters:
#   - Espionage Act whistleblowers (Sterling/CIA, Kiriakou/CIA, Kim/State)
#   - Red Fawn Fallis — Standing Rock DAPL water protector, federal 57-mo
#     sentence; gun belonged to FBI informant Heath Harmon who entered a
#     romantic relationship with her in the weeks before her arrest
#   - Ramona Africa — sole adult survivor of the May 13, 1985 Philadelphia
#     police bombing of MOVE at 6221 Osage Avenue (which killed 11 people
#     including 5 children and burned 61 homes); served 7 yrs PA state
#   - Earth First! / EMETIC "Arizona Five" — May 30, 1989 FBI THERMCON
#     sting against Earth First! organizers in northern Arizona; first
#     "Green Scare" prosecution
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Espionage Act whistleblowers ===

php artisan prisoner:add '{"name":"Jeffrey Sterling","first_name":"Jeffrey","last_name":"Sterling","description":"Jeffrey Sterling is a former CIA case officer and the only African American CIA officer serving in the agencys Iran division at the time of the events that led to his prosecution. After he raised internal concerns about race discrimination at the agency he was forced out of the CIA in 2002. He was indicted in January 2011 under the Espionage Act of 1917 for allegedly providing information to New York Times reporter James Risen about Operation Merlin, a 2000 CIA program that had attempted to feed flawed nuclear-weapons designs to Iran. The prosecution rested entirely on circumstantial telephone-records evidence; no document was ever shown to have passed from him to Risen.\n\nIn January 2015 he was convicted by a federal jury in Alexandria, Virginia, and on May 11, 2015 he was sentenced to 42 months (3.5 years) in federal prison. He served his sentence at the federal Communications Management Unit at Marion, Illinois, and was released in 2018. His memoir Unwanted Spy was published in 2019.","state":"Virginia","race":"Black","gender":"Male","birthdate":"1967-12-02","ideologies":["Whistleblower","First Amendment"],"affiliation":["CIA (former)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal Espionage Act of 1917 — alleged disclosure to New York Times reporter James Risen about CIA Operation Merlin against Iran nuclear-weapons program","arrest_date":"2011-01-06","incarceration_date":"2015-06-19","sentenced_date":"2015-05-11","release_date":"2018-01-19","sentence":"42 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Eastern District of Virginia, January 2015"}]}' || true

php artisan prisoner:add '{"name":"John Kiriakou","first_name":"John","last_name":"Kiriakou","description":"John Kiriakou is a former CIA counterterrorism officer who in December 2007 became the first U.S. government official to publicly confirm that the CIA had used waterboarding to torture detainees in its post-9/11 interrogation program — a confirmation he made on ABC News at a moment when the agency was still publicly denying that waterboarding was used. He was charged in January 2012 under the Espionage Act of 1917 and the Intelligence Identities Protection Act for allegedly identifying a covert CIA officer to a journalist; he pleaded guilty in October 2012 to one IIPA count in exchange for the government dropping the Espionage Act charges. On January 25, 2013 he was sentenced to 30 months in federal prison. He served his sentence at FCI Loretto in Pennsylvania and was released in February 2015. He has been one of the most outspoken U.S. government whistleblowers since.","state":"Virginia","race":"White","gender":"Male","birthdate":"1964-08-09","ideologies":["Whistleblower","First Amendment","Anti-torture"],"affiliation":["CIA (former)","Senate Foreign Relations Committee (former)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"FCI Loretto","institution_city":"Loretto","institution_state":"Pennsylvania","charges":"Federal Intelligence Identities Protection Act — identifying a covert CIA officer to a journalist; underlying disclosure to ABC News in 2007 confirming CIA waterboarding","arrest_date":"2012-01-23","incarceration_date":"2013-02-28","sentenced_date":"2013-01-25","release_date":"2015-02-05","sentence":"30 months federal prison","convicted":"Yes — guilty plea, U.S. District Court for the Eastern District of Virginia, October 2012"}]}' || true

php artisan prisoner:add '{"name":"Stephen Kim","first_name":"Stephen","middle_name":"Jin-Woo","last_name":"Kim","description":"Stephen Jin-Woo Kim is a Korean-American nuclear-proliferation expert and former contractor at the U.S. State Departments Bureau of Verification, Compliance, and Implementation. He was charged in August 2010 under the Espionage Act of 1917 for allegedly disclosing to Fox News reporter James Rosen a classified intelligence assessment that North Korea was likely to respond to UN Security Council sanctions with another nuclear test. He pleaded guilty on February 7, 2014 to one count and was sentenced on April 2, 2014 to 13 months in federal prison. The case was particularly notable for the FBIs warrant against Rosen, which named the Fox News journalist as an aider and abettor of espionage — language that drew major First Amendment criticism.","state":"Virginia","race":"Asian","gender":"Male","ideologies":["Whistleblower","First Amendment"],"affiliation":["U.S. State Department (former contractor)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal Espionage Act of 1917 — alleged disclosure to Fox News reporter James Rosen of classified intelligence assessment about North Korean response to UN sanctions","arrest_date":"2010-08-19","incarceration_date":"2014-04-02","sentenced_date":"2014-04-02","release_date":"2015-05-02","sentence":"13 months federal prison","convicted":"Yes — guilty plea, U.S. District Court for the District of Columbia, February 7, 2014"}]}' || true

# === Red Fawn Fallis — Standing Rock / DAPL ===

php artisan prisoner:add '{"name":"Red Fawn Fallis","first_name":"Red Fawn","last_name":"Fallis","description":"Red Fawn Fallis is an Oglala Sioux water protector and a longtime AIM organizer (her mother Troylyn Yellow Wood was a longtime AIM organizer and Red Fawn was raised in the movement). She traveled to the Standing Rock Sioux Reservation in summer 2016 to participate in the anti-Dakota Access Pipeline mobilization. On October 27, 2016, during the violent Morton County Sheriffs Department-led clearance of the Treaty Camp on disputed Standing Rock Sioux land, she was tackled to the ground by police, and a gun discharged three times during the arrest. She was charged with civil disorder and possession of a firearm by a convicted felon.\n\nIt later emerged that the gun belonged to Heath Harmon, a paid FBI informant assigned to Standing Rock, who had begun a romantic relationship with her in the weeks before her arrest and had given her access to the gun. The defense argued entrapment and FBI misconduct; the federal prosecution rejected it. She accepted a non-cooperating plea in 2018. On July 11, 2018 U.S. District Judge Daniel L. Hovland in Bismarck, North Dakota sentenced her to 57 months in federal prison. She was the most heavily punished of the more than 800 people arrested at Standing Rock. She served her sentence at FCI Waseca in Minnesota and FCI Dublin in California, and was released in 2020.","state":"North Dakota","race":"Native American","gender":"Female","birthdate":"1979-08-21","ideologies":["Indigenous sovereignty","Anti-pipeline","Water protector","American Indian Movement"],"affiliation":["American Indian Movement","Standing Rock"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (FCI Waseca, FCI Dublin)","institution_state":"North Dakota","charges":"Federal civil disorder and possession of a firearm by a convicted felon — October 27, 2016 Morton County Sheriff clearance of the Treaty Camp during the Dakota Access Pipeline standoff at Standing Rock","arrest_date":"2016-10-27","incarceration_date":"2018-07-11","sentenced_date":"2018-07-11","release_date":"2020-12-15","sentence":"57 months federal prison","convicted":"Yes — non-cooperating guilty plea, U.S. District Court for the District of North Dakota, January 2018"}]}' || true

# === Ramona Africa — MOVE ===

php artisan prisoner:add '{"name":"Ramona Africa","first_name":"Ramona","last_name":"Africa","description":"Ramona Africa is the sole surviving adult member of the Philadelphia police bombing of the MOVE compound at 6221 Osage Avenue on May 13, 1985. The Philadelphia Police Department, with FBI-supplied C-4, dropped two bombs from a helicopter on the rowhouse, igniting a fire that the city allowed to burn out of control for 90 minutes; the fire killed eleven MOVE members — six adults and five children — and destroyed 61 neighboring homes, displacing 250 residents. She and the child Birdie Africa were the only two survivors of the rowhouse fire.\n\nOn the basis of the same August 8, 1978 Powelton Village raid for which the MOVE 9 had been convicted, she was charged with riot and conspiracy and convicted in 1986. She served seven years in Pennsylvania state prison at SCI Muncy, refusing to renounce MOVE in exchange for early parole. She was released on May 13, 1992 — the seventh anniversary of the bombing — and has been the principal voice for the survivors and the Free MOVE 9 campaign since.","state":"Pennsylvania","race":"Black","gender":"Female","birthdate":"1956-08-22","ideologies":["Black Liberation","Environmental","MOVE"],"affiliation":["MOVE"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"State Correctional Institution Muncy","institution_city":"Muncy","institution_state":"Pennsylvania","charges":"Pennsylvania state riot and conspiracy in connection with the August 8, 1978 Powelton Village MOVE raid; arrested again at the May 13, 1985 police bombing of the MOVE compound at 6221 Osage Avenue","arrest_date":"1985-05-13","incarceration_date":"1985-05-13","release_date":"1992-05-13","sentence":"7 years Pennsylvania state prison","convicted":"Yes — Pennsylvania state conviction, 1986"}]}' || true

# === Earth First! / EMETIC "Arizona Five" — first Green Scare case ===

php artisan prisoner:add '{"name":"Mark Davis","first_name":"Mark","last_name":"Davis","description":"Mark Davis was an Earth First! activist from Prescott, Arizona and a member of the small affinity group that called itself EMETIC — the Evan Mecham Eco-Terrorist International Conspiracy, named after the impeached Arizona governor. EMETIC carried out a series of nighttime cuts of electrical-transmission-tower bolts in the Arizona desert in protest of nuclear-power infrastructure and federal land policy. On May 30, 1989 he, Peg Millett, and Marc Baker were arrested in the desert by some 50 FBI agents in the THERMCON sting operation, in which an FBI undercover agent (Michael Fain, alias Mike Tait) had infiltrated the group. He pleaded guilty to attempting to destroy an electrical transmission line used in interstate commerce. He was sentenced to 6 years in federal prison and ordered to pay $19,821 in restitution — the longest sentence of the Arizona Five. The Earth First! prosecutions are widely cited as the first U.S. Green Scare case.","state":"Arizona","race":"White","gender":"Male","ideologies":["Environmental","Anti-nuclear"],"affiliation":["Earth First!","EMETIC"],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Arizona","charges":"Federal attempted destruction of an electrical transmission line used in interstate commerce — Earth First! / EMETIC nighttime sabotage of transmission towers in northern Arizona, 1986-89","arrest_date":"1989-05-30","incarceration_date":"1991-09-17","sentenced_date":"1991-09-17","release_date":"1996-09-17","sentence":"6 years federal prison + $19,821 restitution","convicted":"Yes — guilty plea, U.S. District Court for the District of Arizona, 1991"}]}' || true

php artisan prisoner:add '{"name":"Peg Millett","first_name":"Peg","aka":"Margaret Millett","last_name":"Millett","description":"Peg Millett (Margaret Millett) was an Earth First! activist from Prescott, Arizona and a member of the small EMETIC affinity group. On May 30, 1989 she was surrounded with Mark Davis and Marc Baker in the Arizona desert by some 50 FBI agents in the THERMCON sting; she escaped through the underbrush, hitchhiked back to Prescott, and was arrested the next day at the Planned Parenthood clinic where she worked. She pleaded guilty to attempting to destroy an electrical transmission line used in interstate commerce, was sentenced to 3 years in federal prison, and was ordered to pay $19,821 in restitution.","state":"Arizona","race":"White","gender":"Female","ideologies":["Environmental","Anti-nuclear"],"affiliation":["Earth First!","EMETIC"],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Arizona","charges":"Federal attempted destruction of an electrical transmission line used in interstate commerce — Earth First! / EMETIC nighttime sabotage of transmission towers in northern Arizona, 1986-89","arrest_date":"1989-05-31","incarceration_date":"1991-09-17","sentenced_date":"1991-09-17","release_date":"1994-09-17","sentence":"3 years federal prison + $19,821 restitution","convicted":"Yes — guilty plea, U.S. District Court for the District of Arizona, 1991"}]}' || true

php artisan prisoner:add '{"name":"Marc Baker","first_name":"Marc","last_name":"Baker","description":"Marc Baker was an Earth First! activist from Prescott, Arizona and a member of the small EMETIC affinity group. On May 30, 1989 he was arrested with Mark Davis and Peg Millett in the Arizona desert in the FBIs THERMCON sting operation. He pleaded guilty to a lesser charge and was sentenced to 6 months in federal prison.","state":"Arizona","race":"White","gender":"Male","ideologies":["Environmental","Anti-nuclear"],"affiliation":["Earth First!","EMETIC"],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Arizona","charges":"Federal lesser-included offense related to the THERMCON sting against Earth First! / EMETIC","arrest_date":"1989-05-30","incarceration_date":"1991-09-17","sentenced_date":"1991-09-17","release_date":"1992-03-17","sentence":"6 months federal prison","convicted":"Yes — guilty plea, U.S. District Court for the District of Arizona, 1991"}]}' || true

echo
echo "Round 11 (whistleblowers + Standing Rock + Ramona Africa + Earth First!) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
