#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_wwi_delineator_spies.sh
#
# Add WWI-era defendants pictured in the "Huns, Here, There, and
# Everywhere" gallery published in Butterick's Delineator (July 1918).
#
# Already in the NPPC database (skipped here): Kate Richards O'Hare,
# Louise Olivereau, Tom Mooney, Warren Billings.
#
# Skipped: Carl Schmidt of Detroit. Subsequent research (University
# of Michigan Bentley Historical Library finding aid; UM "Michigan
# in the Great War" exhibit) shows the Detroit Carl Schmidt was a
# German-American businessman and anti-war chairman of the American
# Independence Conference. He was harassed and pictured as a "Hun"
# by Delineator but was not actually convicted or imprisoned.
#
# Sources: Wikipedia (Hindu-German Conspiracy Trial; Wilhelm von
# Brincken; Franz von Rintelen; David Lamar; Green Corn Rebellion);
# Encyclopedia of Oklahoma History and Culture (Green Corn Rebellion);
# witness2fashion.wordpress.com (the Delineator gallery itself).
set -e

# === Homer C. Spence — Working Class Union / Green Corn Rebellion (Oklahoma) ===

php artisan prisoner:add '{"name":"Homer C. Spence","first_name":"Homer","last_name":"Spence","description":"Homer C. Spence was a tenant farmer and an organizer for the Working Class Union (WCU), an interracial (white, Black, and Native American) socialist tenant-farmer organization in southeastern Oklahoma. The WCU led the Green Corn Rebellion of August 2-3, 1917 — an armed uprising of mostly young, poor farmers who opposed U.S. entry into World War I and the newly enacted Selective Service Act, and who planned to march on Washington to overthrow the federal government and end the war. The rebellion collapsed within two days under pressure from posses and federal officers, and roughly 450 people were detained. Spence — who was already out on bail for obstructing the 1917 draft — was tried for conspiracy and sentenced to ten years in the federal penitentiary at Leavenworth, Kansas, one of the heaviest sentences imposed on a Green Corn Rebellion organizer. He was pardoned by President Warren G. Harding in 1921. His mug shot ran in Butterick'"'"'s Delineator (July 1918) in the magazine'"'"'s gallery of Huns, Spies and Traitors.","state":"Oklahoma","race":"White","gender":"Male","ideologies":["Socialism","Anti-War","Anti-Draft"],"affiliation":["Working Class Union","Socialist Party of America"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP Leavenworth","institution_city":"Leavenworth","institution_state":"Kansas","charges":"Conspiracy to obstruct the Selective Service Act of 1917 and seditious conspiracy in connection with the Green Corn Rebellion of August 2-3, 1917 in southeastern Oklahoma.","arrest_date":"1917-08-04","sentence":"10 years federal prison at USP Leavenworth; pardoned by President Warren G. Harding in 1921.","release_date":"1921-12-31","convicted":"Yes — convicted in the Green Corn Rebellion prosecutions","judge":"Federal District Court for the Eastern District of Oklahoma"}]}' || true

# === Margaret E. Cornell — Hindu Conspiracy / Espionage Act ===

php artisan prisoner:add '{"name":"Margaret E. Cornell","first_name":"Margaret","last_name":"Cornell","aka":"Margaret W. Cornell","description":"Margaret E. Cornell was an Irish-born office clerk, age 52 at the time of her conviction, who worked at the German Consulate in San Francisco. She was the only woman convicted in the federal Hindu-German Conspiracy trial (formally the Indo-German-Irish plot to ship American weapons to India for an uprising against British rule and to disrupt British and Allied munitions shipping during World War I). Federal prosecutors charged her under Sections 13 and 37 of the U.S. criminal code with espionage and conspiracy for transmitting coded messages between her boss, Consul-General Franz Bopp, and Charles C. Crowley, a private detective hired by the consulate. At trial she testified, I am now a woman without a country. Whether she was a willing participant or a low-level clerical dupe was disputed. Her trial drew heavy press coverage and her mug shot was reproduced in Butterick'"'"'s Delineator (July 1918) in the gallery of Huns, Spies and Traitors. The San Quentin admission record dated February 8, 1918 lists her as Margaret E. Cornell, occupation office clerk, age 52, birthplace Ireland. She had Irish-Republican sympathies, and the 1916 Easter Rising is part of the political context of her case. Cornell told the court she had tuberculosis and feared dying in prison; her ultimate fate is not well documented in surviving newspaper records.","state":"California","race":"White","gender":"Female","birthdate":"1865-01-01","ideologies":["Irish Republicanism","Anti-War"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"San Quentin State Prison","institution_city":"San Quentin","institution_state":"California","charges":"Espionage and conspiracy under Sections 13 and 37 of the U.S. criminal code in connection with the Hindu-German Conspiracy. Alleged to have transmitted coded messages between Consul-General Franz Bopp and private detective Charles C. Crowley.","incarceration_date":"1918-02-08","release_date":"1919-04-24","convicted":"Yes — convicted of espionage and conspiracy in the Hindu-German Conspiracy federal prosecution (April 24, 1918 verdict)","sentence":"Relatively light prison term at San Quentin State Prison; approximate release date one year after federal verdict (no fine; primary records sparse)."}]}' || true

# === Franz Bopp — German Consul-General, San Francisco ===

php artisan prisoner:add '{"name":"Franz Bopp","first_name":"Franz","last_name":"Bopp","description":"Franz Bopp was the German Consul-General in San Francisco from 1914 until his arrest on April 8, 1917. He was the most senior defendant in the Hindu-German Conspiracy trial in the U.S. District Court for the Northern District of California, which ran from November 20, 1917 to April 24, 1918. The trial concerned the Indo-German-Irish plot to ship American weapons to India for an uprising against British rule and to disrupt British and Allied munitions shipping. As Consul-General, Bopp directed the network from his San Francisco office, communicating in coded messages routed through his clerical staff (including Margaret E. Cornell) to operatives such as private detective Charles C. Crowley. He was convicted of conspiracy to violate U.S. neutrality and sentenced to two years federal prison and a $10,000 fine. He was confined at the federal penitentiary on McNeil Island, Washington. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the magazine'"'"'s Huns, Spies and Traitors gallery.","state":"California","race":"White","gender":"Male","ideologies":["German nationalism"],"affiliation":["German Imperial Foreign Service"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP McNeil Island","institution_city":"Steilacoom","institution_state":"Washington","charges":"Conspiracy to violate U.S. neutrality (Section 13 of the U.S. criminal code) and related charges in the Hindu-German Conspiracy.","arrest_date":"1917-04-08","sentenced_date":"1918-04-24","incarceration_date":"1918-04-24","release_date":"1920-04-24","sentence":"2 years federal prison + $10,000 fine.","convicted":"Yes — convicted in the Hindu-German Conspiracy trial (April 24, 1918)"}]}' || true

# === Eckhardt H. von Schack — German Vice-Consul, San Francisco ===

php artisan prisoner:add '{"name":"Eckhardt H. von Schack","first_name":"Eckhardt","last_name":"von Schack","aka":"Baron E.H. von Schack","description":"Baron Eckhardt H. von Schack was the German Vice-Consul in San Francisco. In October 1914, in the early months of World War I, he approved on behalf of the consulate the arrangements for German funds and arms shipments destined for an Indian uprising against British rule — the central plot of the Hindu-German Conspiracy. He was arrested on April 8, 1917 alongside Consul-General Franz Bopp and military attaché Wilhelm von Brincken. At the federal Hindu-German Conspiracy trial (November 20, 1917 - April 24, 1918, U.S. District Court, N.D. Cal.) he was convicted of conspiracy to violate U.S. neutrality and sentenced to two years in federal prison plus a $10,000 fine, the same sentence imposed on Bopp. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the Huns, Spies and Traitors gallery.","state":"California","race":"White","gender":"Male","ideologies":["German nationalism"],"affiliation":["German Imperial Foreign Service"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP McNeil Island","institution_city":"Steilacoom","institution_state":"Washington","charges":"Conspiracy to violate U.S. neutrality (Section 13 of the U.S. criminal code) and related charges in the Hindu-German Conspiracy.","arrest_date":"1917-04-08","sentenced_date":"1918-04-24","incarceration_date":"1918-04-24","release_date":"1920-04-24","sentence":"2 years federal prison + $10,000 fine.","convicted":"Yes — convicted in the Hindu-German Conspiracy trial (April 24, 1918)"}]}' || true

# === Wilhelm von Brincken — German military attaché, San Francisco ===

php artisan prisoner:add '{"name":"Wilhelm von Brincken","first_name":"Wilhelm","last_name":"von Brincken","aka":"Baron Wilhelm von Brinken","description":"Wilhelm von Brincken was a German diplomat and military attaché who in 1915 was assigned to the German Consulate in San Francisco. He was arrested on April 8, 1917 along with Consul-General Franz Bopp and Vice-Consul Eckhardt von Schack. At the Hindu-German Conspiracy trial (November 20, 1917 - April 24, 1918) he was convicted and sentenced to two years in federal prison for plotting to foment an insurrection against British colonial rule in India. The two-year sentence was set to run concurrently with a similar conviction for his alleged participation in bombing and dynamiting plots against the government of Canada. After his release in 1920, he became a naturalized U.S. citizen in 1921 and went on to a long Hollywood career as a character actor specializing in stiff Prussian military officers, appearing in roughly 90 films across the silent and talkie eras and serving as a technical advisor on the Academy Award-winning All Quiet on the Western Front (1930). He died in 1946. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the Huns, Spies and Traitors gallery.","state":"California","race":"White","gender":"Male","birthdate":"1881-01-01","death_date":"1946-12-31","ideologies":["German nationalism"],"affiliation":["German Imperial Foreign Service"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP McNeil Island","institution_city":"Steilacoom","institution_state":"Washington","charges":"Conspiracy to violate U.S. neutrality and to foment an insurrection against British rule in India; also charged with participation in alleged bombing/dynamiting plots against Canada (concurrent conviction).","arrest_date":"1917-04-08","sentenced_date":"1918-04-24","incarceration_date":"1918-04-24","release_date":"1920-04-24","sentence":"2 years federal prison (concurrent with separate Canada-bombing conviction).","convicted":"Yes — convicted in the Hindu-German Conspiracy trial (April 24, 1918)"}]}' || true

# === Charles C. Crowley — private detective for the German Consulate, San Francisco ===

php artisan prisoner:add '{"name":"Charles C. Crowley","first_name":"Charles","last_name":"Crowley","description":"Charles C. Crowley was a San Francisco private detective hired by the German Consulate under Consul-General Franz Bopp during World War I. Federal prosecutors alleged he was the consulate'"'"'s principal field operative in plots to plant bombs aboard Canadian munitions ships docked in U.S. and Canadian ports and to disrupt Allied shipping more broadly. He was a co-defendant in the Hindu-German Conspiracy trial (November 20, 1917 - April 24, 1918, U.S. District Court, N.D. Cal.) and was convicted of conspiracy to violate U.S. neutrality. The coded messages he exchanged with Bopp were transmitted through clerk Margaret E. Cornell, who was also convicted. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the Huns, Spies and Traitors gallery.","state":"California","race":"White","gender":"Male","ideologies":["German nationalism"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP McNeil Island","institution_city":"Steilacoom","institution_state":"Washington","charges":"Conspiracy to violate U.S. neutrality (Section 13 of the U.S. criminal code) in the Hindu-German Conspiracy. Allegations included planting bombs aboard Canadian munitions ships and disrupting Allied shipping out of the Pacific Coast.","arrest_date":"1917-04-08","sentenced_date":"1918-04-24","incarceration_date":"1918-04-24","release_date":"1920-04-24","sentence":"~2 years federal prison in the Hindu-German Conspiracy convictions (approximate release date — primary sentencing record not located in secondary sources).","convicted":"Yes — convicted in the Hindu-German Conspiracy trial (April 24, 1918)"}]}' || true

# === Franz von Rintelen — German Naval Intelligence chief in the U.S. ===

php artisan prisoner:add '{"name":"Franz von Rintelen","first_name":"Franz","last_name":"von Rintelen","aka":"The Dark Invader","description":"Captain Franz von Rintelen was a German Imperial Navy officer who ran German covert operations in the United States from April to August 1915, before U.S. entry into World War I. From his Manhattan headquarters he organized cigar-shaped incendiary bombs (the so-called pencil bombs designed by Walther Scheele) for placement in the holds of Allied munitions ships, financed Labor'"'"'s National Peace Council to foment strikes in U.S. munitions plants supplying the Allies, and tried to draw Mexico into a war with the United States. The Bureau of Investigation broke his cipher; he was recalled by Berlin, captured by the British on his return voyage, interned, and after the U.S. entered the war was extradited to the United States, tried in federal court in New York, and convicted of conspiracy. He was imprisoned for three years at the Atlanta federal penitentiary. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the Huns, Spies and Traitors gallery. After the war he settled in Britain, where he wrote his 1933 memoir The Dark Invader and lived until his death in 1949.","state":"New York","race":"White","gender":"Male","death_date":"1949-05-30","ideologies":["German nationalism"],"affiliation":["German Imperial Navy"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"USP Atlanta","institution_city":"Atlanta","institution_state":"Georgia","charges":"Conspiracy to obstruct U.S. neutrality through munitions-strike plots (Labor'"'"'s National Peace Council), incendiary-bomb attacks on Allied munitions ships in U.S. ports, and related sabotage. Tried in U.S. District Court for the Southern District of New York.","arrest_date":"1917-04-15","sentenced_date":"1917-05-24","incarceration_date":"1917-05-24","release_date":"1920-05-24","sentence":"3 years federal prison at USP Atlanta.","convicted":"Yes — convicted in U.S. federal court in New York"}]}' || true

# === David Lamar — "The Wolf of Wall Street", U.S. agent for von Rintelen ===

php artisan prisoner:add '{"name":"David Lamar","first_name":"David","last_name":"Lamar","aka":"The Wolf of Wall Street","description":"David Lamar was a New York stock manipulator known in the press as the Wolf of Wall Street. During World War I he served as the principal U.S. agent of German Naval Intelligence Captain Franz von Rintelen. Lamar took roughly half of the $500,000 von Rintelen spent on the front group Labor'"'"'s National Peace Council, which was used to finance strikes among U.S. munitions plants supplying Britain and France. He was tried with von Rintelen in federal court in New York for conspiracy. After losing an appeal in 1923 he fled the United States, was apprehended in Mexico eight months later, and served one year at the Essex County Penitentiary in North Caldwell, New Jersey, before his 1924 release. His mug shot was published in Butterick'"'"'s Delineator (July 1918) in the Huns, Spies and Traitors gallery.","state":"New York","race":"White","gender":"Male","ideologies":["Profiteering"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"Essex County Penitentiary","institution_city":"North Caldwell","institution_state":"New Jersey","charges":"Conspiracy to disrupt U.S. munitions production through strike plots financed by Captain Franz von Rintelen (German Naval Intelligence) via Labor'"'"'s National Peace Council. Tried in U.S. District Court for the Southern District of New York.","arrest_date":"1923-12-01","sentenced_date":"1923-12-01","incarceration_date":"1923-12-01","release_date":"1924-12-01","sentence":"1 year at the Essex County Penitentiary, North Caldwell, NJ (served after losing 1923 appeal and being extradited from Mexico; original conviction stems from the 1917 Labor'"'"'s National Peace Council munitions-strike conspiracy).","convicted":"Yes — convicted in the Labor'"'"'s National Peace Council munitions-strike conspiracy"}]}' || true

# === Gustave H. Jacobsen — Chicago WWI conviction ===

php artisan prisoner:add '{"name":"Gustave H. Jacobsen","first_name":"Gustave","last_name":"Jacobsen","description":"Gustave H. Jacobsen of Chicago was convicted in a 1917-1918 federal World War I-era prosecution and pictured in Butterick'"'"'s Delineator (July 1918) in the magazine'"'"'s gallery of Huns, Spies and Traitors. Surviving public records of his case are sparse; he is listed in the magazine alongside the San Francisco Hindu-German Conspiracy defendants and the New York / Labor'"'"'s National Peace Council munitions-strike conspirators, but the specific charges, sentence, and place of incarceration have not been located in readily available secondary sources. This entry is a stub for further research from primary court records (likely U.S. District Court for the Northern District of Illinois) and contemporaneous Chicago newspapers.","state":"Illinois","race":"White","gender":"Male","ideologies":["German nationalism"],"era":"1910s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal prison (WWI-era prosecution)","institution_state":"Illinois","charges":"World War I-era federal conviction (specific charges not yet documented from secondary sources). Pictured in Butterick'"'"'s Delineator (July 1918) Huns, Spies and Traitors gallery.","arrest_date":"1918-01-01","incarceration_date":"1918-01-01","release_date":"1919-01-01","sentence":"~1 year federal prison (approximate; primary sentencing record not located in secondary sources).","convicted":"Yes — convicted in WWI-era federal prosecution (case details to be researched in primary records)"}]}' || true

echo
echo "WWI-era Delineator-pictured prisoner entries added (Spence, Cornell, Bopp, von Schack, von Brincken, Crowley, von Rintelen, Lamar, Jacobsen)."
