#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round5_june11_uprising.sh
#
# Sources:
#   - https://uprisingsupport.org/individual-support/  (currently-incarcerated
#     George Floyd uprising defendants)
#   - https://june11.noblogs.org/prisoners/            (US long-term anarchist
#     prisoners curated by the June 11 international solidarity day)
#
# 13 additions. Marius Mason, Eric King, Michael Kimble are skipped because
# they appear to already be in the database (they did not appear in the
# unsorted-eras listing). Foreign-jurisdiction June 11 prisoners (Italian,
# Chilean, Greek, Russian, Belarusian, etc.) are out of NPPC scope.
set -e

# === Uprising Support — currently-incarcerated George Floyd defendants ===

php artisan prisoner:add '{"name":"David Elmakayes","first_name":"David","last_name":"Elmakayes","description":"David Elmakayes is a Pennsylvania defendant federally prosecuted in connection with the 2020 protests following the police murder of George Floyd. In February 2022 he pleaded guilty to arson and felony possession of a firearm. On June 14, 2022 he was sentenced to 15 years in federal prison and 3 years of supervised release. He is held at USP Lee in Jonesville, Virginia, federal inmate number 77782-066, projected release date July 29, 2033. His writing has been published by Mongoose Distro, including the piece This Land. The Uprising Support project documents his case.","state":"Pennsylvania","race":"Unknown","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"inmate_number":"77782-066","era":"2020s","in_custody":true,"released":false,"cases":[{"institution_name":"USP Lee","institution_city":"Jonesville","institution_state":"Virginia","charges":"Federal arson and felony possession of a firearm in connection with 2020 George Floyd uprising protests in Pennsylvania","incarceration_date":"2022-06-14","sentenced_date":"2022-06-14","sentence":"15 years federal prison + 3 years supervised release","convicted":"Yes — federal guilty plea, February 2022; sentenced June 14, 2022"}]}'

php artisan prisoner:add '{"name":"Jose Felan","first_name":"Jose","last_name":"Felan","description":"Jose Felan is a Minnesota political prisoner who served years in federal prison on charges arising from the 2020 George Floyd uprising in Minneapolis. He was released to a halfway house in Del Rio, Texas on December 3, 2025. The Uprising Support project documented his case as one of the most aggressive examples of federal prosecution of 2020 uprising defendants in Minnesota. His support handle is @freejosefelan on Instagram. Federal inmate number 54146-380.","state":"Minnesota","race":"Hispanic","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"inmate_number":"54146-380","era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (released to halfway house, Del Rio TX)","institution_state":"Minnesota","charges":"Federal charges arising from the 2020 George Floyd uprising in Minneapolis","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","release_date":"2025-12-03","sentence":"Years in federal prison; released to halfway house December 3, 2025","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Malik Muhammad","first_name":"Malik","middle_name":"Farrad","last_name":"Muhammad","aka":"FreeMalikNow","description":"Malik Farrad Muhammad is a Black/Palestinian pansexual Muslim, U.S. Army veteran (tanker), anarchist antifascist, anti-racist abolitionist, and George Floyd uprising defendant. He traveled the country during the 2020 uprising, organizing and participating in protests. He was arrested on federal charges and incarcerated at the Oregon State Penitentiary. In April 2026 he was subjected to a controversial interstate transfer that drew sustained attention from the Final Straw radio program and the @freemaliknow support crew, with him relocated to South Carolina (Kirkland Reception and Evaluation Center). The transfer was widely understood as retaliation for his organizing inside Oregon prisons. He maintains the blog Malik Speaks!","state":"Oregon","race":"Black","gender":"Male","ideologies":["Anarchism","Anti-fascism","Anti-police","Palestine solidarity"],"affiliation":[],"inmate_number":"400523","era":"2020s","in_custody":true,"released":false,"cases":[{"institution_name":"Kirkland Reception and Evaluation Center","institution_city":"Columbia","institution_state":"South Carolina","charges":"Federal charges arising from the 2020 George Floyd uprising; subjected to interstate transfer from Oregon State Penitentiary to South Carolina in April 2026","arrest_date":"2020-08-31","incarceration_date":"2020-08-31","sentence":"Federal prison; full sentence pending verification against primary source","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Margaret Channon","first_name":"Margaret","last_name":"Channon","description":"Margaret Channon is a Washington state defendant who pleaded guilty to setting five Seattle police vehicles on fire during the May 29, 2020 protests in Downtown Seattle following the police murder of George Floyd. She was sentenced to 5 years in federal prison and is held at FCI Tallahassee, federal inmate number 49955-086, projected release date June 5, 2026. The Uprising Support project documents her case.","state":"Washington","race":"White","gender":"Female","ideologies":["Anti-police"],"affiliation":[],"inmate_number":"49955-086","era":"2020s","in_custody":true,"released":false,"cases":[{"institution_name":"FCI Tallahassee","institution_city":"Tallahassee","institution_state":"Florida","charges":"Federal arson — setting five Seattle police vehicles on fire during the May 29, 2020 Downtown Seattle protests after the police murder of George Floyd","arrest_date":"2020-05-30","incarceration_date":"2020-05-30","release_date":"2026-06-05","sentence":"5 years federal prison","convicted":"Yes — federal arson guilty plea"}]}'

php artisan prisoner:add '{"name":"Matthew Rupert","first_name":"Matthew","last_name":"Rupert","description":"Matthew Rupert grew up in Galesburg, Illinois and was federally prosecuted for charges arising from the 2020 George Floyd uprising in Minneapolis. He attended the protests after the police murder of Tyler Smith in his hometown went unprosecuted. The federal prosecution sought 9 to 11 years in prison, well above the statutory presumption. He is held at USP Big Sandy, federal inmate number 55013-424. The Minnesota Uprising Arrestee Support and Uprising Support projects document his case.","state":"Minnesota","race":"White","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"inmate_number":"55013-424","era":"2020s","in_custody":true,"released":false,"cases":[{"institution_name":"USP Big Sandy","institution_city":"Inez","institution_state":"Kentucky","charges":"Federal charges arising from the 2020 George Floyd uprising in Minneapolis","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","sentence":"Federal prison; sentence sought was 9 to 11 years, above statutory presumption","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Matthew White","first_name":"Matthew","last_name":"White","description":"Matthew White is a 32-year-old Native American father of four federally prosecuted for charges arising from the 2020 George Floyd uprising in St. Paul, Minnesota. In a March 2025 letter to Midwest Books to Prisoners, he wrote: I might have lost some years, but George Floyd lost his life. That truth, that perspective, grounds me. He was released to a halfway house in June 2025 after serving years in federal prison. The Uprising Support project documents his case.","state":"Minnesota","race":"Native American","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (released to halfway house)","institution_state":"Minnesota","charges":"Federal charges arising from the 2020 George Floyd uprising in St. Paul, Minnesota","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","release_date":"2025-06-30","sentence":"Years in federal prison; released to halfway house June 2025","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Montez Lee","first_name":"Montez","last_name":"Lee","description":"Montez Lee is a Black father of two from Rochester, Minnesota who was 25 years old at the time of his arrest in connection with the 2020 George Floyd uprising in Minneapolis. He was held without bond after his arrest and faced multiple federal charges. On January 14, 2022 he pleaded guilty to one count of arson and was sentenced to 10 years in federal prison. He is held at FCI Petersburg Medium, federal inmate number 22429-041, projected release date December 21, 2028. In a statement: I am sick of seeing people of color murdered by the same people sworn to serve and protect. I stand with my community and my people. The Minnesota Uprising Arrestee Support and Uprising Support projects document his case.","state":"Minnesota","race":"Black","gender":"Male","ideologies":["Anti-police"],"affiliation":[],"inmate_number":"22429-041","era":"2020s","in_custody":true,"released":false,"cases":[{"institution_name":"FCI Petersburg Medium","institution_city":"Petersburg","institution_state":"Virginia","charges":"Federal arson — 2020 George Floyd uprising in Minneapolis","arrest_date":"2020-05-31","incarceration_date":"2020-05-31","sentenced_date":"2022-01-14","release_date":"2028-12-21","sentence":"10 years federal prison","convicted":"Yes — federal arson guilty plea, January 14, 2022"}]}'

# === June 11 — long-term U.S. anarchist prisoners ===

php artisan prisoner:add '{"name":"Sean Swain","first_name":"Sean","last_name":"Swain","description":"Sean Swain is a long-term anarchist prisoner held in the Ohio Department of Rehabilitation and Correction since 1991. He was originally incarcerated for the killing of an Ohio court officials relative who broke into his home and threatened his life — a killing he and his supporters have always characterized as self-defense. In fall 2012, after a wave of unrest at Mansfield Correctional by prisoners calling themselves the Army of the 12 Monkeys, ODRC officials placed him in supermax isolation on the assumption that he must have been behind the unrest because of his anarchist politics. He has denied any involvement. He has filed federal litigation against ODRC arguing that his treatment in supermax is retaliation for his political ideology and protected speech. He is the only son of a retired auto worker and stay-home mom and is a U.S. military veteran (honorably discharged); before incarceration he worked as a newspaper columnist and a union organizer. He contributes to Fire Ant journal, has books published with Little Black Cart, and is a regular contributor to The Final Straw radio show. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"Ohio","race":"White","gender":"Male","ideologies":["Anarchism"],"affiliation":["Fire Ant journal","The Final Straw radio"],"era":"1990s","in_custody":true,"released":false,"cases":[{"institution_name":"Ohio Department of Rehabilitation and Correction (Mansfield Correctional / supermax)","institution_state":"Ohio","charges":"Killing in defense of his home; subsequently placed in supermax in 2012 after Mansfield Correctional unrest","incarceration_date":"1991-01-01","sentence":"Long state sentence; held in supermax isolation since 2012 on the basis of anarchist political ideology","convicted":"Yes — Ohio state conviction"}]}'

php artisan prisoner:add '{"name":"Bill Dunne","first_name":"Bill","last_name":"Dunne","description":"Bill Dunne is an anti-authoritarian anarchist sentenced to 90 years in federal prison for the 1979 attempted liberation of comrades from the King County Jail in Seattle, and for a 1983 attempt to escape from the United States Penitentiary at Leavenworth. He was charged with possession of an automatic weapon, auto theft, and aiding and abetting the escape; the prosecution further alleged the operation was financed by bank expropriations and facilitated by illegal acquisition of weapons and explosives. He and his co-defendant Larry Giddings were described by police as members of a small, heavily armed group of revolutionaries, associated with the Wellspring Communion.\n\nDunne has been held throughout the federal prison system, including stints at the Marion control unit, Atwater, and Big Sandy, where he has assisted other prisoners with political and academic education. He helps organize the Anarchist Black Cross Federations Running Down the Walls 5K solidarity runs and has written and edited for 4 Struggle magazine. Larry Giddings was paroled in 2004; Dunne was rejected by the parole board in winter 2014 and given a 15-year hit. He is held at FCI Butner Medium II, federal inmate number 10916-086. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"Washington","race":"White","gender":"Male","ideologies":["Anarchism"],"affiliation":["Anarchist Black Cross Federation","4 Struggle magazine"],"inmate_number":"10916-086","era":"1980s","in_custody":true,"released":false,"cases":[{"institution_name":"FCI Butner Medium II","institution_city":"Butner","institution_state":"North Carolina","charges":"Possession of an automatic weapon, auto theft, aiding and abetting an escape — 1979 attempted liberation of comrades from King County Jail in Seattle, plus 1983 attempted escape from USP Leavenworth","arrest_date":"1979-10-15","incarceration_date":"1979-10-15","sentence":"90 years in federal prison","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Alvaro Luna Hernandez","first_name":"Alvaro","middle_name":"Luna","last_name":"Hernandez","aka":"Xinachtli","description":"Alvaro Luna Hernandez, who took the Nahuatl name Xinachtli (meaning seed), is a Chicano community organizer and human rights advocate from Texas. Police informants were used to monitor his organizing in Alpine, Texas, where he was working on police-brutality cases and was nationally and internationally recognized as the national coordinator of the Ricardo Aldape Guerra Defense Committee, the campaign that succeeded in freeing Mexican national Aldape Guerra from Texas death row after he had been framed by Houston police for allegedly killing a police officer.\n\nOn July 18, 1996, Xinachtli disarmed an Alpine police officer who he and his attorneys argued was preparing to draw a weapon on him, in self-defense. He was sentenced on June 2-9, 1997 in Odessa, Texas to 50 years in prison for the disarming. The trial evidence, his defense argued and international human rights observers later confirmed, demonstrated a police-orchestrated frame-up of an organizer the police regarded as dangerous. He has been held in the Texas Department of Criminal Justice ever since, at TDCJ inmate number 00255735. His human rights work was recognized in Italy, France, Spain, Switzerland, Mexico, and other countries. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"Texas","race":"Hispanic","gender":"Male","ideologies":["Chicano liberation","Anti-police","Indigenous"],"affiliation":["Ricardo Aldape Guerra Defense Committee"],"inmate_number":"00255735","era":"1990s","in_custody":true,"released":false,"cases":[{"institution_name":"Texas Department of Criminal Justice","institution_state":"Texas","charges":"Disarming an Alpine, Texas police officer (defense argued self-defense and police frame-up after sustained surveillance of his community organizing)","arrest_date":"1996-07-18","incarceration_date":"1996-07-18","sentenced_date":"1997-06-09","sentence":"50 years in Texas state prison","convicted":"Yes — Ector County, Texas, June 2-9, 1997"}]}'

php artisan prisoner:add '{"name":"Byron Shane Chubbuck","first_name":"Byron","middle_name":"Shane","last_name":"Chubbuck","aka":"Oso Blanco","description":"Byron Shane Chubbuck, known as Oso Blanco (white bear in Spanish; in Cherokee, Yona Unega), is a Cherokee revolutionary serving 55 years in U.S. federal prison for a series of bank robberies, aggravated assault on FBI agents, escape, and firearms charges. On August 13, 1999 he engaged in a gun battle with federal agents at his home in Albuquerque, New Mexico; he initially escaped but was arrested later the same day. After being held at the New Mexico State Penitentiary for slightly more than a year, he escaped from a prison transport van and resumed bank robberies before being recaptured.\n\nThe robberies were carried out without firing a weapon and proceeds were directed in part to support Indigenous resistance, including the Zapatista movement in Chiapas, Mexico. He is now held at USP Victorville, federal inmate number 07909-051. He has consistently said he does not seek monetary support but rather public attention to the conditions of Indigenous peoples. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"New Mexico","race":"Native American","gender":"Male","ideologies":["Indigenous resistance","Anti-imperialist","Zapatista solidarity"],"affiliation":[],"inmate_number":"07909-051","era":"1990s","in_custody":true,"released":false,"cases":[{"institution_name":"USP Victorville","institution_city":"Adelanto","institution_state":"California","charges":"Bank robberies, aggravated assault on FBI agents, escape, firearms charges — proceeds in part directed to Zapatista solidarity","arrest_date":"1999-08-13","incarceration_date":"1999-08-13","sentence":"55 years in federal prison","convicted":"Yes — federal court conviction"}]}'

php artisan prisoner:add '{"name":"Julio Zuniga","first_name":"Julio","last_name":"Zuniga","aka":"Comrade Z","description":"Julio A. Zuniga, known in anarchist circles as Comrade Z, is a long-term anarchist prisoner held in the Texas Department of Criminal Justice at the John B. Connally Unit, inmate number 01961551. He is a frequent contributor to anarchist projects including Mongoose Distro, an artist, and has been interviewed by The Final Straw radio. As of 2025 he was preparing for a parole bid through attorney Mark Morales. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"Texas","race":"Hispanic","gender":"Male","ideologies":["Anarchism"],"affiliation":["Mongoose Distro"],"inmate_number":"01961551","era":"2010s","in_custody":true,"released":false,"cases":[{"institution_name":"John B. Connally Unit","institution_city":"Kenedy","institution_state":"Texas","charges":"Texas state conviction; underlying charge details pending verification against primary source","sentence":"Long-term Texas state sentence; preparing for parole bid as of 2025","convicted":"Yes — Texas state conviction"}]}'

php artisan prisoner:add '{"name":"Noah Coffin","first_name":"Noah","last_name":"Coffin","aka":"Kado","description":"Noah Kado Coffin is an anarchist prison rebel serving a 15-year sentence at the Eastham Unit in Texas, much of it in solitary confinement. He is a poet and artist who writes regularly to outside supporters and movement publications. From a public letter: I am Comrade Kado and you will never be forgotten. Together we stand against the tyranny of oppression, repression, the bonds of conformity, and stand for the ones who cannot. The June 11 international day of solidarity with long-term anarchist prisoners lists him among its current U.S. prisoners.","state":"Texas","race":"White","gender":"Male","ideologies":["Anarchism"],"affiliation":[],"era":"2010s","in_custody":true,"released":false,"cases":[{"institution_name":"Eastham Unit","institution_state":"Texas","charges":"Texas state conviction; underlying charge details pending verification against primary source","sentence":"15 years in Texas state prison","convicted":"Yes — Texas state conviction"}]}'

echo
echo "Round 5 (June 11 + Uprising Individual Support) adds complete."
