#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round12_pentagon_boston_eco_stewart.sh
#
# Source clusters:
#   - Pentagon Papers (1971 disclosure, 1973 indictment, May 11 1973
#     dismissal for governmental misconduct)
#   - Boston Five (Jan 5, 1968 indictment for conspiracy to counsel
#     draft evasion; June 14, 1968 conviction; 1969 reversal)
#   - Eric McDavid - 2007 conviction in FBI eco-entrapment sting against
#     Earth Liberation Front; 9 years served before 2015 Brady reversal
#   - Walter Bond - 2010-2011 federal Animal Liberation Front arson
#     convictions for Colorado Sheepskin Factory + 2 Utah arsons
#   - Lynne Stewart - 2005 conviction for material support based on
#     SAMs-violation press release for client Sheikh Omar Abdel-Rahman;
#     resentenced 10 years; compassionate release 2014; deceased 2017
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Pentagon Papers ===

php artisan prisoner:add '{"name":"Daniel Ellsberg","first_name":"Daniel","last_name":"Ellsberg","description":"Daniel Ellsberg was a former U.S. Marine officer (Vietnam combat veteran), Defense Department analyst, and RAND Corporation consultant who in 1971 disclosed to The New York Times, The Washington Post, and seventeen other newspapers the Pentagon Papers — a 7,000-page top-secret Defense Department history of U.S. decision-making in Vietnam from 1945 to 1968 that documented systematic government deception of the American public about the war. The disclosure prompted the U.S. Supreme Court ruling in New York Times Co. v. United States (1971), the foundational Pentagon Papers prior-restraint decision.\n\nIn January 1973 he was indicted under the Espionage Act of 1917 and other statutes carrying a maximum sentence of 115 years. His four-month trial in U.S. District Court for the Central District of California ended on May 11, 1973 when Judge William Byrne Jr. dismissed all charges with prejudice on grounds of governmental misconduct — the same misconduct that came to be revealed as the Watergate prosecutions: the White House Plumbers break-in at the office of his psychiatrist Dr. Lewis Fielding, illegal NSA wiretaps, and offers of judicial appointments to Judge Byrne by the Nixon administration. He died on June 16, 2023, age 92.","state":"California","race":"White","gender":"Male","birthdate":"1931-04-07","death_date":"2023-06-16","ideologies":["Whistleblower","Anti-war","First Amendment"],"affiliation":["RAND Corporation (former)","U.S. Marine Corps (former)","Department of Defense (former)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"(charges dismissed before trial completion)","charges":"Federal Espionage Act of 1917, theft, and conspiracy — 1971 disclosure of the Pentagon Papers; maximum sentence 115 years","arrest_date":"1971-06-28","indicted":"1973-01-03","release_date":"1973-05-11","sentence":"All charges dismissed with prejudice for governmental misconduct (White House Plumbers break-in at psychiatrists office, illegal wiretaps)","convicted":"No — case dismissed by Judge William Byrne Jr., U.S. District Court for the Central District of California, May 11, 1973"}]}' || true

php artisan prisoner:add '{"name":"Anthony Russo","first_name":"Anthony","last_name":"Russo","description":"Anthony J. (Tony) Russo Jr. was a former RAND Corporation analyst and Daniel Ellsbergs co-defendant in the Pentagon Papers prosecution. He had assisted Ellsberg in copying the 7,000-page top-secret history at RANDs Santa Monica office in 1969-70 in advance of its 1971 disclosure to the press. He was indicted in January 1973 under the Espionage Act of 1917 along with Ellsberg. The prosecution attempted to compel his grand-jury testimony against Ellsberg by granting him immunity; he refused and was held in civil contempt for 47 days at the federal Terminal Island Detention Center in Los Angeles in 1972 — the only Pentagon Papers defendant to actually serve any time. Charges were dismissed with prejudice on May 11, 1973 for governmental misconduct. He died on August 6, 2008.","state":"California","race":"White","gender":"Male","death_date":"2008-08-06","ideologies":["Whistleblower","Anti-war","First Amendment"],"affiliation":["RAND Corporation (former)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Detention Center, Terminal Island","institution_city":"Los Angeles","institution_state":"California","charges":"Civil contempt of grand jury for refusing to testify against Daniel Ellsberg in the Pentagon Papers prosecution; subsequently indicted under Espionage Act of 1917 (charges dismissed)","arrest_date":"1972-08-15","incarceration_date":"1972-08-15","release_date":"1972-10-01","sentence":"47 days for civil contempt; subsequent Espionage Act charges dismissed May 11, 1973","convicted":"Civil contempt only; Espionage Act charges dismissed with prejudice"}]}' || true

# === Boston Five — January 5, 1968 indictment, June 14, 1968 conviction, 1969 reversal ===

php artisan prisoner:add '{"name":"Benjamin Spock","first_name":"Benjamin","last_name":"Spock","description":"Dr. Benjamin McLane Spock was the most famous American pediatrician of the twentieth century, author of the bestselling Common Sense Book of Baby and Child Care (1946, 50 million copies sold), and one of the most prominent public opponents of the Vietnam War. On January 5, 1968 he was indicted in U.S. District Court for the District of Massachusetts along with Yale University Chaplain William Sloane Coffin, Boston University writer Mitchell Goodman, Institute for Policy Studies fellow Marcus Raskin, and Harvard graduate-student Michael Ferber on charges of conspiring to counsel young men to evade the draft — the famous Boston 5 indictment. The defendants had publicly endorsed the October 1967 Resistance turn-in of draft cards and the Confront the Warmakers march on the Pentagon.\n\nOn June 14, 1968 he was convicted with three of his co-defendants (Raskin was acquitted) and sentenced to 2 years in federal prison. The convictions were reversed on appeal by the First Circuit on July 11, 1969, on the grounds that the conspiracy theory ran into First Amendment problems and the trial judge had erred in refusing the defense additional peremptory challenges. He never served the sentence. He died on March 15, 1998, age 94.","state":"Massachusetts","race":"White","gender":"Male","birthdate":"1903-05-02","death_date":"1998-03-15","ideologies":["Anti-war","First Amendment"],"affiliation":["Boston Five"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"(conviction reversed before reporting to prison)","charges":"Federal conspiracy to counsel draft evasion — January 5, 1968 indictment based on public endorsement of October 1967 Resistance draft-card turn-in","arrest_date":"1968-01-05","incarceration_date":"1968-06-14","sentenced_date":"1968-07-10","release_date":"1969-07-11","sentence":"2 years federal prison (sentenced); reversed on appeal by 1st Circuit July 11, 1969","convicted":"Initial conviction by federal jury, June 14, 1968; reversed on appeal 1969"}]}' || true

php artisan prisoner:add '{"name":"William Sloane Coffin","first_name":"William","middle_name":"Sloane","last_name":"Coffin","description":"William Sloane Coffin Jr. was the chaplain of Yale University from 1958 to 1975 and one of the most prominent American Protestant peace ministers of the Vietnam War era. He had previously been a CIA case officer in postwar Germany and a U.S. Army intelligence officer; in 1961 he was a freedom-rider on the Mississippi run with John Lewis. On January 5, 1968 he was indicted with four others in the Boston Five case for conspiring to counsel young men to evade the draft. He was convicted with Spock, Goodman, and Ferber on June 14, 1968 and sentenced to 2 years in federal prison. The conviction was reversed on appeal in July 1969. He never served the sentence. He died on April 12, 2006, age 81.","state":"Massachusetts","race":"White","gender":"Male","birthdate":"1924-06-01","death_date":"2006-04-12","ideologies":["Anti-war","First Amendment","Christian peace"],"affiliation":["Yale University Chaplaincy","Boston Five"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"(conviction reversed before reporting to prison)","charges":"Federal conspiracy to counsel draft evasion — January 5, 1968 Boston Five indictment","arrest_date":"1968-01-05","incarceration_date":"1968-06-14","sentenced_date":"1968-07-10","release_date":"1969-07-11","sentence":"2 years federal prison (sentenced); reversed on appeal 1969","convicted":"Initial conviction by federal jury, June 14, 1968; reversed on appeal 1969"}]}' || true

php artisan prisoner:add '{"name":"Mitchell Goodman","first_name":"Mitchell","last_name":"Goodman","description":"Mitchell Goodman was an American novelist, poet, and Boston University professor who, with his wife the poet Denise Levertov, organized many of the first Resistance draft-card turn-ins of October 1967. He was indicted with four others in the Boston Five case on January 5, 1968 for conspiring to counsel draft evasion. He was convicted with Spock, Coffin, and Ferber on June 14, 1968 and sentenced to 2 years in federal prison. The conviction was reversed on appeal in July 1969. He never served the sentence. He died on February 1, 1997, age 73.","state":"Massachusetts","race":"White","gender":"Male","birthdate":"1923-12-15","death_date":"1997-02-01","ideologies":["Anti-war","First Amendment"],"affiliation":["Boston Five","Resistance"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"(conviction reversed before reporting to prison)","charges":"Federal conspiracy to counsel draft evasion — January 5, 1968 Boston Five indictment","arrest_date":"1968-01-05","incarceration_date":"1968-06-14","sentenced_date":"1968-07-10","release_date":"1969-07-11","sentence":"2 years federal prison (sentenced); reversed on appeal 1969","convicted":"Initial conviction by federal jury, June 14, 1968; reversed on appeal 1969"}]}' || true

php artisan prisoner:add '{"name":"Michael Ferber","first_name":"Michael","middle_name":"K","last_name":"Ferber","description":"Michael K. Ferber was a Harvard graduate student in English literature in 1968, the youngest of the Boston Five defendants, and the only one not previously famous. He had given a sermon at the October 16, 1967 Arlington Street Church in Boston gathering of more than 250 young men turning in their draft cards. He was indicted on January 5, 1968 with four others in the Boston Five case. He was convicted with Spock, Coffin, and Goodman on June 14, 1968 and sentenced to 2 years in federal prison. The conviction was reversed on appeal in July 1969. He never served the sentence. He went on to become a prominent scholar of British Romanticism at the University of New Hampshire.","state":"Massachusetts","race":"White","gender":"Male","birthdate":"1944-02-25","ideologies":["Anti-war","First Amendment"],"affiliation":["Boston Five","Resistance"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"(conviction reversed before reporting to prison)","charges":"Federal conspiracy to counsel draft evasion — January 5, 1968 Boston Five indictment","arrest_date":"1968-01-05","incarceration_date":"1968-06-14","sentenced_date":"1968-07-10","release_date":"1969-07-11","sentence":"2 years federal prison (sentenced); reversed on appeal 1969","convicted":"Initial conviction by federal jury, June 14, 1968; reversed on appeal 1969"}]}' || true

# === Eric McDavid — Earth Liberation Front entrapment case ===

php artisan prisoner:add '{"name":"Eric McDavid","first_name":"Eric","last_name":"McDavid","description":"Eric McDavid was a green anarchist and Earth Liberation Front sympathizer from Foresthill, California. He was arrested on January 13, 2006 along with Lauren Weiner and Zachary Jenson in a cabin near Dutch Flat, California, where the FBI alleged the three had been planning to set fire to the Nimbus Dam, U.S. Forest Service installations, and nearby utilities. The fourth member of the affinity group, who called herself Anna, was a paid FBI informant (real name Zoe Voss) who had been sent to infiltrate radical environmental movements in 2004 and who was paid more than $65,000 by the FBI for her role in the McDavid case. Anna had supplied the bomb-making information, the money for raw materials, the transportation, and the cabin.\n\nWeiner and Jenson took cooperating pleas. McDavid refused and went to trial. He was convicted in September 2007 in U.S. District Court in Sacramento and sentenced on May 8, 2008 to 19 years and 7 months in federal prison. On January 8, 2015 his conviction was overturned after federal prosecutors conceded that the FBI had withheld thousands of pages of potentially exculpatory evidence about Annas role and her relationship with McDavid. He had served 8 years and 360 days of a 20-year sentence. He pleaded to a lesser count of conspiracy and was released to time served the same day.","state":"California","race":"White","gender":"Male","birthdate":"1977-10-09","ideologies":["Anarchism","Environmental"],"affiliation":["Earth Liberation Front (alleged)"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"California","charges":"Federal conspiracy to use fire or explosives to damage corporate and government property — alleged ELF cell directed by FBI informant Anna","arrest_date":"2006-01-13","incarceration_date":"2008-05-08","sentenced_date":"2008-05-08","release_date":"2015-01-08","sentence":"19 years 7 months federal prison; overturned January 2015 after FBI Brady-evidence concession; resentenced to time served","convicted":"Yes (initial federal jury verdict, September 2007); overturned and resentenced 2015"}]}' || true

# === Walter Bond — Animal Liberation Front Lone Wolf ===

php artisan prisoner:add '{"name":"Walter Bond","first_name":"Walter","last_name":"Bond","description":"Walter Bond is a vegan animal-rights activist and Animal Liberation Front Lone Wolf who claimed responsibility through the ALF press office for three arsons of animal-industry targets in 2010: the April 30 Sheepskin Factory in Denver, Colorado; the June 5 Tandy Leather Factory in Salt Lake City, Utah; and the July 3 Tiburon foie gras restaurant in Sandy, Utah. He was arrested on July 23, 2010 in Denver after his brother provided FBI investigators with information.\n\nHe pleaded guilty in both jurisdictions. On February 11, 2011 he was sentenced in U.S. District Court in Denver to 5 years for the Colorado fire; on October 13, 2011 he was sentenced in U.S. District Court in Salt Lake City to 7 years 3 months for the Utah fires, to run consecutive. The combined 12-year sentence was the longest ever imposed at the time on an Animal Liberation Front prisoner. He served substantial portions of his sentence in solitary confinement at the federal Communications Management Unit at Marion, Illinois. He was released in June 2020.","state":"Colorado","race":"White","gender":"Male","ideologies":["Animal rights","Veganism"],"affiliation":["Animal Liberation Front"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Colorado","charges":"Federal arson — three Animal Liberation Front arsons in 2010: Sheepskin Factory (Denver, Colorado), Tandy Leather Factory (Salt Lake City, Utah), and Tiburon foie gras restaurant (Sandy, Utah)","arrest_date":"2010-07-23","incarceration_date":"2011-02-11","sentenced_date":"2011-10-13","release_date":"2020-06-18","sentence":"5 years (Colorado) + 7 years 3 months (Utah) consecutive = 12 years 3 months federal prison","convicted":"Yes — guilty pleas, U.S. District Courts for the District of Colorado and the District of Utah, 2011"}]}' || true

# === Lynne Stewart — Special Administrative Measures press release ===

php artisan prisoner:add '{"name":"Lynne Stewart","first_name":"Lynne","last_name":"Stewart","description":"Lynne Stewart was a New York City civil-rights and criminal-defense attorney with a four-decade record of representing leftists, Black liberation movement defendants, and post-9/11 Muslim defendants. In 1995 she was retained by the Department of Justice to represent Sheikh Omar Abdel-Rahman, the blind Egyptian cleric convicted in the 1993 World Trade Center bombing prosecution; she represented him until her own arrest. As one condition of post-conviction visits with him, she had signed Special Administrative Measures (SAMs) limiting communications between him and outside parties.\n\nIn April 2002 she was charged with material support to terrorism and false statements based on a June 2000 press conference in which she conveyed Sheikh Abdel-Rahmans statement to Reuters that he no longer supported the cease-fire of al-Gama a al-Islamiyya in Egypt. She maintained that the SAMs language was so vague she had not violated it, and that the prosecution criminalized vigorous defense advocacy. She was convicted in February 2005 and on October 16, 2006 sentenced by Judge John G. Koeltl to 28 months in federal prison. The Second Circuit reversed the sentence as unreasonably lenient and ordered re-sentencing; on July 15, 2010 Judge Koeltl resentenced her to 10 years.\n\nShe was diagnosed with stage 4 breast cancer in 2013 and was granted compassionate release on December 31, 2013. She continued public political-prisoner advocacy until her death from breast cancer on March 7, 2017, age 77. Her funeral at the Riverside Church in Manhattan drew thousands.","state":"New York","race":"White","gender":"Female","birthdate":"1939-10-08","death_date":"2017-03-07","ideologies":["Civil rights law","First Amendment","Anti-imperialist"],"affiliation":["Center for Constitutional Rights","National Lawyers Guild"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (FMC Carswell)","institution_city":"Fort Worth","institution_state":"Texas","charges":"Federal material support to terrorism and false statements — June 2000 press conference conveying Sheikh Omar Abdel-Rahmans statement to Reuters in alleged violation of Special Administrative Measures","arrest_date":"2002-04-09","incarceration_date":"2009-11-19","sentenced_date":"2010-07-15","release_date":"2013-12-31","sentence":"Initial 28 months (October 2006); resentenced to 10 years (July 2010); compassionate release December 31, 2013","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, February 2005"}]}' || true

echo
echo "Round 12 (Pentagon Papers + Boston 5 + ELF/ALF + Lynne Stewart) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
