<?php

declare(strict_types=1);

/**
 * Bulk-add Truman-era political prisoners (1945-1953):
 *
 *   1. Foley Square / Dennis Eleven (CPUSA national board, 1949)
 *   2. NY second-string CPUSA / Flynn group (1951-53)
 *   3. California Yates group (1951; reversed by Yates v US 1957)
 *   4. Pittsburgh / Nelson (1953)
 *   5. North Carolina / Junius Scales (1954 indictment)
 *   6. Carl Marzani (first Loyalty-Order prosecution, 1947)
 *   7. Hollywood Ten (1947 contempt)
 *   8. Rosenbergs + atomic spies
 *   9. HUAC contempt: Hammett, Du Bois (acquitted), Emspak
 *  10. Trotskyist 1941 Minneapolis Smith Act (carried into Truman era)
 *  11. Taft-Hartley §9(h) prosecutions: Ben Gold, Hugh Bryson, Maurice
 *      Travis, Harry Bridges
 *  12. Denaturalization: James Matles
 *  13. Espionage-perjury: Alger Hiss, William Remington
 *  14. McCarran Act deportation: Cedric Belfrage
 *  15. Civil Rights Congress: William L. Patterson
 *  16. Black civil-rights cases: Trenton 6, Willie McGee, Martinsville
 *      7, Groveland 4
 *  17. Puerto Rican: Oscar Collazo (Blair House attack 1950)
 *  18. CO: Larry Gara
 *
 * Total: ~85 prisoners.
 */

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Institution;
use App\Models\Prisoner;
use App\Models\PrisonerCase;

function addP(array $p): array {
    $existing = Prisoner::where('name', $p['name'])->first();
    if ($existing) return [$existing, false];
    $prisoner = Prisoner::create(array_filter([
        'name' => $p['name'], 'first_name' => $p['first_name'] ?? null, 'middle_name' => $p['middle_name'] ?? null,
        'last_name' => $p['last_name'] ?? null, 'aka' => $p['aka'] ?? null,
        'gender' => $p['gender'] ?? null, 'race' => $p['race'] ?? null, 'state' => $p['state'] ?? null,
        'birthdate' => $p['birthdate'] ?? null, 'death_date' => $p['death_date'] ?? null,
        'description' => $p['description'] ?? null, 'era' => $p['era'] ?? '1950s',
        'ideologies' => $p['ideologies'] ?? null, 'affiliation' => $p['affiliation'] ?? null,
        'in_custody' => $p['in_custody'] ?? false, 'released' => $p['released'] ?? true,
    ], fn ($v) => $v !== null));
    return [$prisoner, true];
}

function attachC(Prisoner $prisoner, array $c): bool {
    if (! empty($c['arrest_date'])) {
        $exists = $prisoner->cases()->where('arrest_date', $c['arrest_date'])->first();
        if ($exists) return false;
    }
    $institution = Institution::firstOrCreate(['name' => $c['institution']['name']], ['city' => $c['institution']['city'] ?? null, 'state' => $c['institution']['state'] ?? null]);
    PrisonerCase::create([
        'prisoner_id' => $prisoner->id, 'institution_id' => $institution->id,
        'charges' => $c['charges'] ?? null, 'arrest_date' => $c['arrest_date'] ?? null,
        'incarceration_date' => $c['incarceration_date'] ?? null, 'release_date' => $c['release_date'] ?? null,
        'death_in_custody_date' => $c['death_in_custody_date'] ?? null,
        'sentenced_date' => $c['sentenced_date'] ?? null, 'convicted' => $c['convicted'] ?? null,
        'sentence' => $c['sentence'] ?? null, 'prosecutor' => $c['prosecutor'] ?? null, 'judge' => $c['judge'] ?? null,
    ]);
    return true;
}

$tot = ['created' => 0, 'existed' => 0, 'cases' => 0];

$foleyInst = ['name' => 'U.S. Penitentiary Atlanta — Smith Act / Foley Square Trial (Dennis et al.)', 'city' => 'Atlanta', 'state' => 'Georgia'];
$foleyCharges = 'Foley Square Trial / Dennis et al.: 11 CPUSA national board members tried before Judge Harold R. Medina, S.D.N.Y. Indicted July 20, 1948. Convicted October 14, 1949 of conspiracy to advocate violent overthrow of U.S. government and to organize CPUSA as group teaching same (Smith Act, 18 U.S.C. § 2385). 10 of 11 received 5 years + $10,000 fine; Thompson got 3 years (WWII service). Affirmed Dennis v. United States, 341 U.S. 494 (1951, 6-2). Surrender date: July 2, 1951; four jumped bail (Hall, Green, Winston, Thompson).';

$smithActInst = ['name' => 'Federal courts — Smith Act second-string trials', 'city' => null, 'state' => null];
$yatesInst = ['name' => 'U.S. District Court, Central District of California — Smith Act / Yates v. United States', 'city' => 'Los Angeles', 'state' => 'California'];
$yatesCharges = 'California Smith Act prosecution: 14 LA defendants arrested July 26, 1951; convicted; reversed/dismissed by Yates v. United States, 354 U.S. 298 (June 17, 1957) — "Red Monday" — narrowing the Smith Act to specific advocacy of action.';

$hollywoodInst = ['name' => 'U.S. District Court, District of Columbia — Hollywood Ten contempt', 'city' => 'Washington', 'state' => 'District of Columbia'];
$hollywoodCharges = 'Contempt of Congress (2 U.S.C. § 192) for refusing to answer HUAC questions about CPUSA membership at Oct 27-30, 1947 hearings. Cited Nov 24, 1947; indicted Dec 5, 1947. Convicted in DC federal court before Judge Edward M. Curran. SCOTUS denied cert April 1950. Sentences served 1950-51.';

$people = [
    // Foley Square / Dennis 11
    ['name' => 'Eugene Dennis', 'first_name' => 'Eugene', 'last_name' => 'Dennis', 'aka' => 'Francis Xavier Waldron Jr.', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1905-08-10', 'death_date' => '1961-01-31', 'description' => 'CPUSA General Secretary 1945-1959; IWW veteran. Lead defendant of the Foley Square Eleven; sentenced 5 years federal prison + $10,000. Served at USP Atlanta from July 1951 to March 1955.', 'affiliation' => ['Communist Party USA (General Secretary 1945-1959)', 'IWW (former)'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison + $10,000 fine; also served 6 months earlier for HUAC contempt 1947', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'prosecutor' => 'John F.X. McGohey (U.S. Attorney, S.D.N.Y.)', 'charges' => $foleyCharges]]],
    ['name' => 'William Z. Foster', 'first_name' => 'William', 'middle_name' => 'Z.', 'last_name' => 'Foster', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1881-02-25', 'death_date' => '1961-09-01', 'description' => 'CPUSA Chairman 1945-1957; legendary labor organizer (1919 steel strike). Indicted with the Foley Square Eleven but severed July 1948 due to chronic heart disease; never tried. Indictment outstanding at his death; given a state funeral on Red Square in Moscow.', 'affiliation' => ['Communist Party USA (Chairman 1945-1957)'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentence' => 'Indicted but severed for health; never tried', 'convicted' => 'No — case severed', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'John Gates', 'first_name' => 'John', 'last_name' => 'Gates', 'aka' => 'Solomon "Sol" Regenstreif', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1913-09-28', 'death_date' => '1992-05-23', 'description' => 'Editor of the Daily Worker (1947-1958); Spanish Civil War veteran (Lincoln-Washington Battalion political commissar). Foley Square Eleven defendant; 5 years federal prison at USP Atlanta. Led 1956-58 reform faction; left CPUSA 1958.', 'affiliation' => ['Communist Party USA', 'Daily Worker (editor)', 'Abraham Lincoln Brigade'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison + $10,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Henry Winston', 'first_name' => 'Henry', 'last_name' => 'Winston', 'aka' => 'Winnie', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1911-04-02', 'death_date' => '1986-12-13', 'description' => 'CPUSA National Organizational Secretary; later National Chairman 1966-86. Foley Square Eleven defendant; jumped bail July 1951; surrendered March 1956; held at FCI Terre Haute. Lost his eyesight from untreated brain tumor (denied medical care 1958-60); famously said "They robbed me of my sight but not of my vision." Sentence commuted by JFK June 30, 1961 after Castro raised the case in his UN speech.', 'affiliation' => ['Communist Party USA (National Chairman 1966-86)'], 'cases' => [['institution' => ['name' => 'FCI Terre Haute — Smith Act / Foley Square', 'city' => 'Terre Haute', 'state' => 'Indiana'], 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1961-06-30', 'sentence' => '5 years (jumped bail; surrendered 1956); commuted by JFK June 30, 1961 after he lost his eyesight in custody from untreated brain tumor', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Gus Hall', 'first_name' => 'Gus', 'last_name' => 'Hall', 'aka' => 'Arvo Kustaa Halberg', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1910-10-08', 'death_date' => '2000-10-13', 'description' => 'CPUSA leader; General Secretary 1959-2000; 4-time presidential candidate (1972, 1976, 1980, 1984). Foley Square Eleven defendant; jumped bail June 1951; captured Mexico City October 8, 1951; +3 years for bail jumping. ~5.5 years total at USP Leavenworth; released March 1959.', 'affiliation' => ['Communist Party USA (General Secretary 1959-2000)'], 'cases' => [['institution' => ['name' => 'USP Leavenworth — Smith Act / Foley Square', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1959-03-15', 'sentence' => '5 years + $10,000 fine + 3 years bail jumping', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Robert George Thompson', 'first_name' => 'Robert', 'middle_name' => 'George', 'last_name' => 'Thompson', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1915-06-21', 'death_date' => '1965-10-16', 'description' => 'CPUSA NY State chairman; WWII Distinguished Service Cross (New Guinea); Spanish Civil War — Mackenzie-Papineau Battalion commander. Foley Square defendant; 3 years (reduced for WWII service). Jumped bail; captured August 1953 in Sierra Nevada Mountains; +4 years. Brief stint at Alcatraz; skull fractured by Yugoslav fascist inmate wielding a pipe.', 'affiliation' => ['Communist Party USA (NY State chairman)', 'WWII Army (Distinguished Service Cross)'], 'cases' => [['institution' => ['name' => 'Alcatraz / federal prisons — Smith Act / Foley Square', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1960-12-15', 'sentence' => '3 years; jumped bail; +4 years for bail jumping (total ~7)', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Benjamin Jefferson Davis Jr.', 'first_name' => 'Benjamin', 'middle_name' => 'Jefferson', 'last_name' => 'Davis Jr.', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1903-09-08', 'death_date' => '1964-08-22', 'description' => 'NYC Councilmember (Harlem) 1943-49; Harvard Law-trained attorney; CPUSA National Committee. Foley Square Eleven defendant; 5 years at FCI Terre Haute; ~3 years 4 months served; released 1955. Editor of The Worker post-release.', 'affiliation' => ['Communist Party USA (National Committee)', 'NYC Council (Harlem) 1943-49'], 'cases' => [['institution' => ['name' => 'FCI Terre Haute — Smith Act / Foley Square', 'city' => 'Terre Haute', 'state' => 'Indiana'], 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'John Williamson', 'first_name' => 'John', 'last_name' => 'Williamson', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1903-08-08', 'death_date' => '1974-11-16', 'description' => 'Glasgow-born CPUSA Labor Secretary; National Organization Secretary. Foley Square Eleven defendant; 5 years; deported to UK 1955 upon release (was never naturalized); rejoined CPGB.', 'affiliation' => ['Communist Party USA (Labor Secretary)', 'Communist Party of Great Britain'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison; deported to UK 1955', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Carl Winter', 'first_name' => 'Carl', 'last_name' => 'Winter', 'gender' => 'Male', 'race' => 'White', 'state' => 'Michigan', 'birthdate' => '1906-01-01', 'death_date' => '1991-12-15', 'description' => 'Chairman CPUSA Michigan; later editor of the Daily Worker (1966). Foley Square Eleven defendant; 5 years federal prison.', 'affiliation' => ['Communist Party USA (Michigan chairman)'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Gilbert Green', 'first_name' => 'Gilbert', 'last_name' => 'Green', 'aka' => 'Gil Green', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1906-09-26', 'death_date' => '1997-05-04', 'description' => 'CPUSA Illinois/NY chairman; National Board. Foley Square Eleven defendant; jumped bail July 1951; surrendered February 27, 1956 in NYC; +3 years for bail jumping; released July 29, 1961.', 'affiliation' => ['Communist Party USA (Illinois/NY chairman)'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1961-07-29', 'sentence' => '5 years + 3 years bail jumping', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Jacob Stachel', 'first_name' => 'Jacob', 'last_name' => 'Stachel', 'aka' => 'Jack Stachel', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1900-01-18', 'death_date' => '1965-12-31', 'description' => 'CPUSA Labor Secretary; head of Trade Union Unity League. Foley Square Eleven defendant; 5 years at FCI Danbury (July 1951 - March 1955).', 'affiliation' => ['Communist Party USA (Labor Secretary)', 'Trade Union Unity League'], 'cases' => [['institution' => ['name' => 'FCI Danbury — Smith Act / Foley Square', 'city' => 'Danbury', 'state' => 'Connecticut'], 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],
    ['name' => 'Irving Potash', 'first_name' => 'Irving', 'last_name' => 'Potash', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1902-01-01', 'death_date' => '1985-12-15', 'description' => 'International Fur and Leather Workers Union VP; CPUSA NY. Foley Square Eleven defendant; 5 years; injured at 1949 Peekskill anti-Robeson riot during trial recess. Deported/moved to Poland after release; re-entered US illegally 1957; +2 years for immigration violation.', 'affiliation' => ['Communist Party USA', 'International Fur and Leather Workers Union'], 'cases' => [['institution' => $foleyInst, 'arrest_date' => '1948-07-20', 'sentenced_date' => '1949-10-21', 'release_date' => '1955-03-01', 'sentence' => '5 years federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Harold R. Medina', 'charges' => $foleyCharges]]],

    // Smith Act second-string (Flynn group / California Yates / Pittsburgh / NC)
    ['name' => 'Elizabeth Gurley Flynn', 'first_name' => 'Elizabeth', 'middle_name' => 'Gurley', 'last_name' => 'Flynn', 'aka' => 'Rebel Girl', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1890-08-07', 'death_date' => '1964-09-05', 'description' => 'IWW founder/organizer; ACLU co-founder (expelled 1940 for CP membership); CPUSA National Chairwoman 1961-64. Smith Act 1951 NY group; sentenced 3 years; served 28 months at FPC Alderson, WV (Jan 1955 - May 1957). Memoir: "The Alderson Story: My Life as a Political Prisoner." Died in Moscow with state funeral.', 'affiliation' => ['Industrial Workers of the World (founder)', 'Communist Party USA (National Chairwoman 1961-64)', 'ACLU (co-founder)'], 'cases' => [['institution' => ['name' => 'Federal Prison Camp, Alderson — Smith Act 1951 NY group', 'city' => 'Alderson', 'state' => 'West Virginia'], 'arrest_date' => '1951-06-20', 'sentenced_date' => '1953-01-21', 'release_date' => '1957-05-15', 'sentence' => '3 years federal prison; served 28 months', 'convicted' => 'Yes', 'judge' => 'Hon. Edward J. Dimock (S.D.N.Y.)', 'charges' => 'Smith Act 1951 NY second-string trial — conspiracy under 18 U.S.C. § 2385.']]],
    ['name' => 'Claudia Vera Jones', 'first_name' => 'Claudia', 'middle_name' => 'Vera', 'last_name' => 'Jones', 'aka' => 'Claudia Cumberbatch', 'gender' => 'Female', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1915-02-21', 'death_date' => '1964-12-24', 'description' => 'Trinidadian-born; CPUSA Negro Affairs Commission; founder of Notting Hill Carnival. Smith Act 1951 NY group; 1 year + 1 day at FPC Alderson 1955. Deported to UK Dec 1955 (Trinidad refused entry); buried beside Marx in Highgate.', 'affiliation' => ['Communist Party USA (Negro Affairs Commission)'], 'cases' => [['institution' => ['name' => 'Federal Prison Camp, Alderson — Smith Act 1951 NY group', 'city' => 'Alderson', 'state' => 'West Virginia'], 'arrest_date' => '1951-06-20', 'sentenced_date' => '1953-01-21', 'release_date' => '1955-10-23', 'sentence' => '1 year + 1 day federal prison; deported to UK Dec 1955', 'convicted' => 'Yes', 'judge' => 'Hon. Edward J. Dimock', 'charges' => 'Smith Act NY second-string — conspiracy under 18 U.S.C. § 2385.']]],
    ['name' => 'Pettis Perry', 'first_name' => 'Pettis', 'last_name' => 'Perry', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1897-01-04', 'death_date' => '1965-07-24', 'description' => 'CPUSA Negro Commission Secretary; Farm Commission chair; alternate executive committee. Smith Act 1951 NY group; 3 years + $6,000 fine; served. Later fled US as fugitive; died of heart attack in Moscow.', 'affiliation' => ['Communist Party USA (Negro Commission Secretary)'], 'cases' => [['institution' => $smithActInst, 'arrest_date' => '1951-06-20', 'sentenced_date' => '1953-01-21', 'release_date' => '1956-12-15', 'sentence' => '3 years federal prison + $6,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward J. Dimock', 'charges' => 'Smith Act NY second-string — conspiracy under 18 U.S.C. § 2385.']]],
    ['name' => 'Oleta O\'Connor Yates', 'first_name' => 'Oleta', 'middle_name' => 'O\'Connor', 'last_name' => 'Yates', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1908-01-01', 'death_date' => '1980-12-15', 'description' => 'California CPUSA chair; lead named defendant in Yates v. United States, 354 U.S. 298 (1957). Sentenced 5 years + $10,000; conviction reversed by Yates "Red Monday" decision.', 'affiliation' => ['Communist Party USA (California chair)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'sentenced_date' => '1952-08-15', 'release_date' => '1957-06-17', 'sentence' => '5 years + $10,000; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Dorothy Ray Healey', 'first_name' => 'Dorothy', 'middle_name' => 'Ray', 'last_name' => 'Healey', 'aka' => 'Dorothy Rosenblum', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1914-09-22', 'death_date' => '2006-08-06', 'description' => 'Southern California CPUSA chair; "Red Queen"; later DSA VP. Yates defendant; 5 years; conviction reversed by Yates 1957.', 'affiliation' => ['Communist Party USA (Southern California chair)', 'Democratic Socialists of America (later VP)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'sentenced_date' => '1952-08-15', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'William V. Schneiderman', 'first_name' => 'William', 'middle_name' => 'V.', 'last_name' => 'Schneiderman', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1905-12-14', 'death_date' => '1985-01-29', 'description' => 'Romanovo, Russian Empire-born; California CPUSA State Secretary 1938-57. Subject of earlier Schneiderman v. US (1943) denaturalization win. Yates defendant; 5 years; reversed.', 'affiliation' => ['Communist Party USA (California State Secretary)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'sentenced_date' => '1952-08-15', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Albert Jason Lima', 'first_name' => 'Albert', 'middle_name' => 'Jason', 'last_name' => 'Lima', 'aka' => 'Mickey Lima', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'description' => 'Northern California CPUSA chairman. Yates defendant; conviction reversed via Yates.', 'affiliation' => ['Communist Party USA (Northern California)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Loretta Starvus Stack', 'first_name' => 'Loretta', 'middle_name' => 'Starvus', 'last_name' => 'Stack', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1913-01-01', 'description' => 'California State Organizing Secretary CPUSA; trained in Moscow; married longshoreman Walter Stack. Yates defendant; conviction reversed. The Stack v. Boyle (1951) bail-reduction Supreme Court case bears her name.', 'affiliation' => ['Communist Party USA (California State Organizing Secretary)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges . ' Stack v. Boyle, 342 U.S. 1 (1951) — bail-reduction case named for her.']]],
    ['name' => 'Frank Spector', 'first_name' => 'Frank', 'last_name' => 'Spector', 'aka' => 'Frank Efroim Spector', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1900-01-01', 'death_date' => '1982-10-15', 'description' => 'Russian Jewish immigrant 1913. International Labor Defense district organizer; Imperial Valley agricultural strike organizer. Prior 1930 California Criminal Syndicalism conviction (3-42 years San Quentin). Smith Act / Yates defendant; 5 years; reversed.', 'affiliation' => ['Communist Party USA', 'International Labor Defense'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Henry Steinberg', 'first_name' => 'Henry', 'last_name' => 'Steinberg', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'description' => 'LA Smith Act defendant; arrested August 1951; conviction reversed in Yates — SCOTUS held no evidence of conspiracy participation, only CP membership/officership. Represented by Leo Branton Jr.', 'affiliation' => ['Communist Party USA (Los Angeles)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Rose Chernin', 'first_name' => 'Rose', 'last_name' => 'Chernin', 'aka' => 'Rose Kusnitz; née Chasnik', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1901-01-01', 'death_date' => '1995-09-08', 'description' => 'Russian Jewish immigrant 1913. LA CPUSA leader. Yates defendant; arrested August 1951; released December 8, 1951; conviction reversed by Yates 1957. Mother of memoirist Kim Chernin.', 'affiliation' => ['Communist Party USA (Los Angeles)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],
    ['name' => 'Ben Dobbs', 'first_name' => 'Ben', 'last_name' => 'Dobbs', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1909-01-01', 'death_date' => '1992-12-15', 'description' => 'Southern California CPUSA organizer; WWII Army infantry vet. Yates defendant; conviction reversed; later ran for Congress on Peace and Freedom; co-founded New American Movement / DSA.', 'affiliation' => ['Communist Party USA (Southern California)', 'New American Movement (later)'], 'cases' => [['institution' => $yatesInst, 'arrest_date' => '1951-07-26', 'release_date' => '1957-06-17', 'sentence' => '5 years; reversed by Yates v. US 1957', 'convicted' => 'Yes; reversed', 'charges' => $yatesCharges]]],

    // Pittsburgh + NC
    ['name' => 'Steve Nelson', 'first_name' => 'Steve', 'last_name' => 'Nelson', 'aka' => 'Stjepan Mesaroš', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1903-01-01', 'death_date' => '1993-12-11', 'description' => 'Croatian immigrant; Western PA CPUSA District Secretary; Spanish Civil War — Lincoln Battalion political commissar; XV International Brigade commissar. Two prosecutions: PA Sedition Act August 1950 (20 years + $10,000); federal Smith Act 1953 (5 years + $10,000). Pennsylvania v. Nelson, 350 U.S. 497 (1956) invalidated state sedition laws (federal preemption).', 'affiliation' => ['Communist Party USA (Western PA District Secretary)', 'Abraham Lincoln Brigade'], 'cases' => [['institution' => ['name' => 'Allegheny County / federal Pittsburgh courts — Smith Act + PA Sedition', 'city' => 'Pittsburgh', 'state' => 'Pennsylvania'], 'arrest_date' => '1950-08-15', 'sentenced_date' => '1953-08-01', 'release_date' => '1957-06-17', 'sentence' => '20 years PA state (vacated by Pennsylvania v. Nelson 1956); 5 years federal Smith Act (reversed by Yates 1957)', 'convicted' => 'Yes (both); both vacated', 'charges' => 'PA Sedition Act 1950 (vacated by federal preemption Pennsylvania v. Nelson, 350 U.S. 497 (1956)); Smith Act §2385 1953 (reversed Yates 1957).']]],
    ['name' => 'Junius Irving Scales', 'first_name' => 'Junius', 'middle_name' => 'Irving', 'last_name' => 'Scales', 'gender' => 'Male', 'race' => 'White', 'state' => 'North Carolina', 'birthdate' => '1920-03-26', 'death_date' => '2002-08-05', 'description' => 'Born in Greensboro, NC; great-uncle was NC Governor Alfred Moore Scales. Chair Carolinas District CPUSA; UNC Chapel Hill student/grad. US Army 4 years. Arrested 1954; convicted 1955 Greensboro federal court; reversed; retried & re-convicted 1958; Scales v. United States, 367 U.S. 203 (1961) — 5-4 affirmed (only conviction under Smith Act membership clause to stand). 6 years; entered USP Lewisburg October 1961. Sentence commuted by JFK Christmas Eve 1962 — last Smith Act prisoner released. Left CPUSA 1957 over Khrushchev Secret Speech.', 'affiliation' => ['Communist Party USA (Carolinas chair)'], 'cases' => [['institution' => ['name' => 'USP Lewisburg — Smith Act / Scales v. US', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1954-11-18', 'sentenced_date' => '1958-12-15', 'release_date' => '1962-12-24', 'sentence' => '6 years federal prison; commuted by JFK Christmas Eve 1962', 'convicted' => 'Yes; affirmed Scales v. US 367 U.S. 203 (1961)', 'charges' => 'Smith Act 1940 § 2385 — membership clause (only conviction under that clause to stand). Scales v. United States, 367 U.S. 203 (1961). Last Smith Act prisoner.']]],

    // First Truman case
    ['name' => 'Carl Aldo Marzani', 'first_name' => 'Carl', 'middle_name' => 'Aldo', 'last_name' => 'Marzani', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1912-03-04', 'death_date' => '1994-12-11', 'description' => 'Italian immigrant 1924; OSS officer (WWII); briefly State Department; CPUSA NYC organizer; documentary filmmaker; Antonio Gramsci\'s first English translator/publisher. The first Truman-era political prosecution: indicted January 1947; convicted June 22, 1947 in DC federal court — 11 counts of fraud/false statements (concealing CP membership while on government payroll under EO 9835 Loyalty Order). 36 months; served 32 months. Wrote We Can Be Friends: Origins of the Cold War (1952) in prison.', 'affiliation' => ['OSS (former)', 'State Department (former)', 'Communist Party USA', 'Marzani & Munsell Press (publisher)'], 'cases' => [['institution' => ['name' => 'FCI Danbury — first Loyalty Order prosecution', 'city' => 'Danbury', 'state' => 'Connecticut'], 'arrest_date' => '1947-01-15', 'sentenced_date' => '1947-06-22', 'release_date' => '1950-08-15', 'sentence' => '36 months federal prison; served 32 months', 'convicted' => 'Yes', 'judge' => 'Hon. James M. Proctor (D.D.C.)', 'charges' => 'False statements to a federal agency (18 U.S.C. § 80, predecessor to § 1001), 11 counts — concealing CPUSA membership while on government payroll under President Truman\'s Loyalty Order EO 9835. First conviction under Truman Loyalty Program.']]],

    // Hollywood Ten
    ['name' => 'John Howard Lawson', 'first_name' => 'John', 'middle_name' => 'Howard', 'last_name' => 'Lawson', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1894-09-25', 'death_date' => '1977-08-11', 'description' => 'Playwright and screenwriter who helped found the Screen Writers Guild in 1933 and served as its first president. The de facto cultural commissar of CPUSA in Hollywood. As the first "unfriendly witness" called before HUAC October 27, 1947, he became lead defendant of the Hollywood Ten. Served 1 year at FCI Ashland, KY.', 'affiliation' => ['Communist Party USA', 'Screen Writers Guild (founder)'], 'cases' => [['institution' => ['name' => 'FCI Ashland — Hollywood Ten', 'city' => 'Ashland', 'state' => 'Kentucky'], 'arrest_date' => '1947-10-27', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-06-15', 'sentence' => '1 year + $1,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran (D.D.C.)', 'charges' => $hollywoodCharges]]],
    ['name' => 'Dalton Trumbo', 'first_name' => 'Dalton', 'last_name' => 'Trumbo', 'aka' => 'James Dalton Trumbo', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1905-12-09', 'death_date' => '1976-09-10', 'description' => 'One of Hollywood\'s highest-paid screenwriters. Served 11 months federal prison; later won 2 Oscars under pseudonyms (Roman Holiday; The Brave One); broke the blacklist publicly in 1960 when Otto Preminger and Kirk Douglas credited him for Exodus and Spartacus.', 'affiliation' => ['Communist Party USA (1943-1948)', 'Screen Writers Guild'], 'cases' => [['institution' => ['name' => 'FCI Ashland — Hollywood Ten', 'city' => 'Ashland', 'state' => 'Kentucky'], 'arrest_date' => '1947-10-28', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-04-15', 'sentence' => '1 year + $1,000 fine; served 11 months', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Albert Maltz', 'first_name' => 'Albert', 'last_name' => 'Maltz', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1908-10-28', 'death_date' => '1985-04-26', 'description' => 'Brooklyn-born playwright, novelist, and screenwriter (Phi Beta Kappa, Columbia 1930). Joined CPUSA 1935; wrote uncredited material on Casablanca and the Oscar-winning short The House I Live In (1945). Entered Mill Point Federal Prison July 17, 1950. Blacklisted; wrote through fronts (Two Mules for Sister Sara, 1970).', 'affiliation' => ['Communist Party USA', 'Screen Writers Guild'], 'cases' => [['institution' => ['name' => 'Mill Point Federal Prison — Hollywood Ten', 'city' => 'Mill Point', 'state' => 'West Virginia'], 'arrest_date' => '1947-10-28', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-06-15', 'sentence' => '1 year + $1,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Alvah Cecil Bessie', 'first_name' => 'Alvah', 'middle_name' => 'Cecil', 'last_name' => 'Bessie', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1904-06-04', 'death_date' => '1985-07-21', 'description' => 'Columbia-educated novelist; Spanish Civil War — Lincoln Brigade machine-gunner sergeant-adjutant (1938 Ebro offensive); chronicled it in Men in Battle (1939). Earned an Oscar nomination for Objective, Burma! (1945). Hollywood Ten member; 1 year at FCI Texarkana, TX. Post-release: ILWU Dispatcher editor.', 'affiliation' => ['Communist Party USA (1936-1954)', 'Abraham Lincoln Brigade', 'Hollywood Ten'], 'cases' => [['institution' => ['name' => 'FCI Texarkana — Hollywood Ten', 'city' => 'Texarkana', 'state' => 'Texas'], 'arrest_date' => '1947-10-28', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-06-15', 'sentence' => '1 year + $1,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Samuel Ornitz', 'first_name' => 'Samuel', 'last_name' => 'Ornitz', 'aka' => 'Samuel Badisch Ornitz', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1890-11-15', 'death_date' => '1957-03-10', 'description' => 'Screenwriter; novelist (Haunch Paunch and Jowl, 1923); SWG co-founder. Hollywood Ten; 1 year at FCI Springfield, MO (medical facility — health issues). Died of cancer 1957.', 'affiliation' => ['Communist Party USA', 'Screen Writers Guild (co-founder)'], 'cases' => [['institution' => ['name' => 'Federal Medical Center, Springfield — Hollywood Ten', 'city' => 'Springfield', 'state' => 'Missouri'], 'arrest_date' => '1947-10-28', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-06-15', 'sentence' => '1 year + $1,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Ring Lardner Jr.', 'first_name' => 'Ringgold', 'middle_name' => 'Wilmer', 'last_name' => 'Lardner Jr.', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1915-08-19', 'death_date' => '2000-10-31', 'description' => '2-time Oscar-winning screenwriter (Woman of the Year 1942; M*A*S*H 1970). Famous quip "I could answer the question exactly the way you want… but if I did I would hate myself in the morning" got him cited for contempt. Last surviving Hollywood Ten member.', 'affiliation' => ['Communist Party USA', 'Screen Writers Guild', 'Hollywood Ten'], 'cases' => [['institution' => ['name' => 'FCI Danbury — Hollywood Ten', 'city' => 'Danbury', 'state' => 'Connecticut'], 'arrest_date' => '1947-10-30', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-04-15', 'sentence' => '12 months + $1,000 fine; served ~10 months', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Adrian Scott', 'first_name' => 'Adrian', 'last_name' => 'Scott', 'aka' => 'Robert Adrian Scott', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1911-02-06', 'death_date' => '1972-12-25', 'description' => 'RKO producer (Murder My Sweet 1944, Crossfire 1947 — anti-antisemitism Best Picture nominee that drew HUAC\'s ire). Hollywood Ten; 1 year. Wrote television under his wife\'s name and pseudonyms during blacklist.', 'affiliation' => ['Communist Party USA (joined 1944)', 'RKO Pictures', 'Hollywood Ten'], 'cases' => [['institution' => ['name' => 'FCI Ashland — Hollywood Ten', 'city' => 'Ashland', 'state' => 'Kentucky'], 'arrest_date' => '1947-10-29', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-06-15', 'sentence' => '1 year + $1,000 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Edward Dmytryk', 'first_name' => 'Edward', 'last_name' => 'Dmytryk', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1908-09-04', 'death_date' => '1999-07-01', 'description' => 'Director (Crossfire 1947, The Caine Mutiny 1954). The only Hollywood Ten member who recanted: served ~4.5 months at Mill Point before reversing course; in April 1951 testified again before HUAC and named 26 names including fellow Ten member Herbert Biberman. Reinstated in Hollywood.', 'affiliation' => ['Communist Party USA (1944-1945, briefly)', 'Hollywood Ten', 'later HUAC cooperator'], 'cases' => [['institution' => ['name' => 'Mill Point Federal Prison — Hollywood Ten', 'city' => 'Mill Point', 'state' => 'West Virginia'], 'arrest_date' => '1947-10-29', 'sentenced_date' => '1950-06-09', 'release_date' => '1950-11-15', 'sentence' => '6 months + $500 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Lester Cole', 'first_name' => 'Lester', 'last_name' => 'Cole', 'aka' => 'Lester Cohn', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1904-06-19', 'death_date' => '1985-08-15', 'description' => 'Son of a Polish-Jewish Marxist garment-union organizer; wrote 40+ produced screenplays 1932-1947; helped Lawson and Ornitz found the Screen Writers Guild in 1933. Hollywood Ten; ~10 months at FCI Danbury. Born Free (1966) under pseudonym Gerald L.C. Copley.', 'affiliation' => ['Communist Party USA (joined 1934)', 'Screen Writers Guild (co-founder)'], 'cases' => [['institution' => ['name' => 'FCI Danbury — Hollywood Ten', 'city' => 'Danbury', 'state' => 'Connecticut'], 'arrest_date' => '1947-10-30', 'sentenced_date' => '1950-06-09', 'release_date' => '1951-04-15', 'sentence' => '12 months + $1,000 fine; served 10 months', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],
    ['name' => 'Herbert Biberman', 'first_name' => 'Herbert', 'middle_name' => 'J.', 'last_name' => 'Biberman', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1900-03-04', 'death_date' => '1971-06-30', 'description' => 'Yale-trained theater director; CPUSA member; married to actress Gale Sondergaard. Hollywood Ten; 6 months at FCI Texarkana. Co-founded Independent Productions Corporation with other blacklistees and directed Salt of the Earth (1954) about a New Mexico zinc-miners\' strike — suppressed in U.S. theaters.', 'affiliation' => ['Communist Party USA', 'Hollywood Ten', 'Independent Productions Corporation'], 'cases' => [['institution' => ['name' => 'FCI Texarkana — Hollywood Ten', 'city' => 'Texarkana', 'state' => 'Texas'], 'arrest_date' => '1947-10-29', 'sentenced_date' => '1950-06-09', 'release_date' => '1950-12-15', 'sentence' => '6 months + $500 fine', 'convicted' => 'Yes', 'judge' => 'Hon. Edward M. Curran', 'charges' => $hollywoodCharges]]],

    // Rosenbergs / atomic spies
    ['name' => 'Julius Rosenberg', 'first_name' => 'Julius', 'last_name' => 'Rosenberg', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1918-05-12', 'death_date' => '1953-06-19', 'released' => false, 'description' => 'CCNY-trained electrical engineer who joined the Young Communist League at City College and recruited a wartime espionage network for Soviet intelligence while a civilian inspector at the Army Signal Corps lab at Fort Monmouth. Arrested July 17, 1950; tried jointly with Ethel and Morton Sobell; convicted March 29, 1951; sentenced to death April 5, 1951; executed at Sing Sing June 19, 1953 — the only American civilian executed for espionage during peacetime, alongside Ethel.', 'affiliation' => ['Communist Party USA', 'Young Communist League', 'U.S. Army Signal Corps (civilian engineer)'], 'cases' => [['institution' => ['name' => 'Sing Sing Prison — Rosenberg trial', 'city' => 'Ossining', 'state' => 'New York'], 'arrest_date' => '1950-07-17', 'sentenced_date' => '1951-04-05', 'death_in_custody_date' => '1953-06-19', 'sentence' => 'Death — executed June 19, 1953 at Sing Sing', 'convicted' => 'Yes', 'judge' => 'Hon. Irving R. Kaufman (S.D.N.Y.)', 'prosecutor' => 'Irving Saypol; Roy M. Cohn (asst.)', 'charges' => 'Conspiracy to commit espionage (50 U.S.C. § 32(a), Espionage Act of 1917).']]],
    ['name' => 'Ethel Greenglass Rosenberg', 'first_name' => 'Ethel', 'middle_name' => 'Greenglass', 'last_name' => 'Rosenberg', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1915-09-28', 'death_date' => '1953-06-19', 'released' => false, 'description' => 'Grew up in a poor Jewish tenement family on Manhattan\'s Lower East Side; labor activist and aspiring singer. Married Julius Rosenberg 1939. Arrested August 11, 1950 — largely as leverage to compel Julius\'s confession. Convicted on the testimony of her brother David Greenglass and his wife Ruth that she typed espionage notes. Greenglass admitted in 2001 that he perjured himself about Ethel. Executed at Sing Sing June 19, 1953; case widely viewed as a grave miscarriage of justice.', 'affiliation' => ['Communist Party USA', 'Young Communist League'], 'cases' => [['institution' => ['name' => 'Sing Sing Prison — Rosenberg trial', 'city' => 'Ossining', 'state' => 'New York'], 'arrest_date' => '1950-08-11', 'sentenced_date' => '1951-04-05', 'death_in_custody_date' => '1953-06-19', 'sentence' => 'Death — executed June 19, 1953 at Sing Sing', 'convicted' => 'Yes', 'judge' => 'Hon. Irving R. Kaufman', 'prosecutor' => 'Irving Saypol; Roy M. Cohn (asst.)', 'charges' => 'Conspiracy to commit espionage (50 U.S.C. § 32(a)).']]],
    ['name' => 'Morton Sobell', 'first_name' => 'Morton', 'last_name' => 'Sobell', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1917-04-11', 'death_date' => '2018-12-26', 'description' => 'CCNY engineering classmate of Julius Rosenberg\'s who worked on military radar and ordnance contracts. Fled with his family to Mexico City June 22, 1950; on August 16 was abducted by armed men (likely Mexican secret police acting at FBI behest) and arrested at the Texas border. Convicted with the Rosenbergs March 1951; served 17 years 9 months at Alcatraz (1952-1958), Atlanta, and Lewisburg before parole January 14, 1969. In 2008 he admitted to the New York Times that he had passed military secrets to the Soviets during WWII.', 'affiliation' => ['Communist Party USA (alleged)', 'General Electric (former)', 'Reeves Electronics'], 'cases' => [['institution' => ['name' => 'Alcatraz / federal prisons — Rosenberg trial', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1950-08-18', 'sentenced_date' => '1951-04-05', 'release_date' => '1969-01-14', 'sentence' => '30 years; served 17 years 9 months', 'convicted' => 'Yes', 'judge' => 'Hon. Irving R. Kaufman', 'prosecutor' => 'Irving Saypol; Roy M. Cohn', 'charges' => 'Conspiracy to commit espionage (50 U.S.C. § 32(a)).']]],
    ['name' => 'David Greenglass', 'first_name' => 'David', 'last_name' => 'Greenglass', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1922-03-02', 'death_date' => '2014-07-01', 'description' => 'Ethel Rosenberg\'s younger brother; Army machinist at Los Alamos who passed plutonium-bomb sketches to Soviet courier Harry Gold in 1945. Arrested June 15, 1950; turned state\'s evidence — admitted in a 2001 interview with Sam Roberts that he perjured himself about Ethel typing notes to keep his wife Ruth out of prison. Sentenced to 15 years April 6, 1951; paroled after about 9.5 years; lived under an assumed name until his death.', 'affiliation' => ['U.S. Army (Manhattan Project machinist at Los Alamos)', 'Young Communist League (briefly)'], 'cases' => [['institution' => ['name' => 'USP Lewisburg — Rosenberg trial', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1950-06-15', 'sentenced_date' => '1951-04-06', 'release_date' => '1960-11-15', 'sentence' => '15 years federal prison; served ~9.5 years', 'convicted' => 'Yes — guilty plea / cooperator', 'judge' => 'Hon. Irving R. Kaufman', 'prosecutor' => 'Irving Saypol', 'charges' => 'Conspiracy to commit espionage (50 U.S.C. § 32(a)).']]],
    ['name' => 'Harry Gold', 'first_name' => 'Harry', 'last_name' => 'Gold', 'aka' => 'Heinrich Golodnitsky', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1910-12-11', 'death_date' => '1972-08-28', 'description' => 'Philadelphia industrial chemist who began passing Soviet intelligence economic and chemical secrets in 1934. As courier "Raymond" he received atomic-weapons data from Klaus Fuchs and David Greenglass during 1944-45. Arrested May 22, 1950 after Fuchs identified him from a photo; pled guilty. Sentenced to 30 years December 9, 1950 by Judge James P. McGranery. Served at USP Lewisburg; paroled May 18, 1966.', 'affiliation' => ['NKVD/Soviet intelligence (1934-1950)', 'Pennsylvania Sugar Co.'], 'cases' => [['institution' => ['name' => 'USP Lewisburg — atomic spy case', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1950-05-22', 'sentenced_date' => '1950-12-09', 'release_date' => '1966-05-18', 'sentence' => '30 years federal prison', 'convicted' => 'Yes — guilty plea', 'judge' => 'Hon. James P. McGranery (E.D. Pa.)', 'prosecutor' => 'Gerald A. Gleeson', 'charges' => 'Conspiracy to commit espionage (50 U.S.C. § 32(a)).']]],

    // HUAC contempt
    ['name' => 'Dashiell Hammett', 'first_name' => 'Samuel', 'middle_name' => 'Dashiell', 'last_name' => 'Hammett', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1894-05-27', 'death_date' => '1961-01-10', 'description' => 'Inventor of hard-boiled detective fiction (The Maltese Falcon, The Thin Man); volunteered for the U.S. Army in both world wars; joined the CPUSA in the late 1930s. As a trustee of the Civil Rights Congress bail fund, refused on July 9, 1951 to identify the fund\'s contributors after four CRC defendants jumped bail. Judge Sylvester Ryan immediately convicted him of criminal contempt; six months at FCI Ashland, KY. The IRS then pursued him for back taxes; he died penniless of lung cancer.', 'affiliation' => ['Communist Party USA', 'Civil Rights Congress (bail-fund trustee)', 'U.S. Army (WWI and WWII)'], 'cases' => [['institution' => ['name' => 'FCI Ashland — Hammett HUAC/CRC contempt', 'city' => 'Ashland', 'state' => 'Kentucky'], 'arrest_date' => '1951-07-09', 'sentenced_date' => '1951-07-09', 'release_date' => '1951-12-09', 'sentence' => '6 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Sylvester J. Ryan (S.D.N.Y.)', 'charges' => 'Criminal contempt of court (18 U.S.C. § 401) for refusing to identify Civil Rights Congress bail-fund contributors.']]],
    ['name' => 'W. E. B. Du Bois', 'first_name' => 'William', 'middle_name' => 'Edward Burghardt', 'last_name' => 'Du Bois', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Massachusetts', 'birthdate' => '1868-02-23', 'death_date' => '1963-08-27', 'description' => 'Harvard\'s first Black PhD; NAACP co-founder; sociologist; editor of The Crisis. Chaired the Peace Information Center, which circulated the Stockholm Peace Appeal calling for nuclear disarmament. The Justice Department indicted him February 9, 1951 for failing to register as a foreign agent under FARA. Tried November 1951 before Judge James M. McGuire; the case was dismissed for lack of evidence after defense attorney Vito Marcantonio moved for acquittal at the close of the prosecution\'s case (November 20, 1951). Passport revoked 1952-58. Died in Ghana 1963 at 95.', 'affiliation' => ['NAACP (co-founder)', 'Peace Information Center', 'Communist Party USA (joined 1961)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, District of Columbia — U.S. v. Du Bois', 'city' => 'Washington', 'state' => 'District of Columbia'], 'arrest_date' => '1951-02-09', 'release_date' => '1951-11-20', 'sentence' => 'Acquitted; charges dismissed', 'convicted' => 'No — acquitted', 'judge' => 'Hon. James M. McGuire', 'charges' => 'Foreign Agents Registration Act (22 U.S.C. § 611 et seq.) — failure to register as agent of foreign principal (Stockholm Peace Appeal).']]],
    ['name' => 'Julius Emspak', 'first_name' => 'Julius', 'last_name' => 'Emspak', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1904-08-06', 'death_date' => '1962-04-26', 'description' => 'Founding General Secretary-Treasurer of the United Electrical, Radio and Machine Workers of America (UE) 1936-1962. Phi Beta Kappa Union College. Authored the UE\'s preamble; central to its policies of refusing Taft-Hartley affidavits and resisting Cold War anti-Communism. July 1950, HUAC cited him and five other UE leaders for contempt of Congress. Convicted; conviction reversed in Emspak v. United States, 349 U.S. 190 (1955), holding his Fifth Amendment invocation was sufficient.', 'affiliation' => ['United Electrical, Radio and Machine Workers of America (founding General Secretary-Treasurer)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, D.C. — Emspak HUAC contempt', 'city' => 'Washington', 'state' => 'District of Columbia'], 'arrest_date' => '1950-07-15', 'sentenced_date' => '1952-06-15', 'release_date' => '1955-05-30', 'sentence' => 'Conviction reversed by SCOTUS Emspak v. US 349 U.S. 190 (1955)', 'convicted' => 'Yes; reversed', 'charges' => 'Contempt of Congress (2 U.S.C. § 192) for refusing to answer HUAC about UE membership.']]],

    // Trotskyist 1941 Minneapolis
    ['name' => 'James P. Cannon', 'first_name' => 'James', 'middle_name' => 'P.', 'last_name' => 'Cannon', 'aka' => 'James Patrick Cannon', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1890-02-11', 'death_date' => '1974-08-21', 'description' => 'National Secretary of the Socialist Workers Party (SWP); leading figure in American Trotskyism. Born in Rosedale, Kansas; founded CPUSA before being expelled in 1928 for supporting Trotsky. Co-founded the SWP in 1938. Convicted under the Smith Act in 1941 for opposing US entry into WWII; testimony published as the classic "Socialism on Trial" (1942). 16 months federal prison.', 'affiliation' => ['Socialist Workers Party (National Secretary)', 'Communist League of America', 'IWW (former)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'prosecutor' => 'Victor E. Anderson', 'charges' => 'Conspiracy to advocate the overthrow of the U.S. government by force; advocating insubordination in the armed forces (Smith Act / Alien Registration Act of 1940, 18 U.S.C. § 2385). First Smith Act prosecution.']]],
    ['name' => 'Vincent Raymond Dunne', 'first_name' => 'Vincent', 'middle_name' => 'Raymond', 'last_name' => 'Dunne', 'aka' => 'V.R. Dunne; Ray Dunne', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1889-04-17', 'death_date' => '1970-02-17', 'description' => 'Central leader of the 1934 Minneapolis Teamsters strike; co-founder of American Trotskyism. Joined the IWW in Montana lumber camps before settling in Minneapolis. Expelled from the Communist Party in 1928 with Cannon for Trotskyism. Trotsky called him "the most effective labor leader in America." 16 months at FCI Sandstone. Remained an SWP leader until his death.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544', 'IWW (former)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'prosecutor' => 'Victor E. Anderson', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Farrell Dobbs', 'first_name' => 'Farrell', 'last_name' => 'Dobbs', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1907-07-25', 'death_date' => '1983-10-31', 'description' => 'Teamsters organizer who led the 1938-41 over-the-road truck driver organizing drives bringing a quarter-million Midwestern drivers into the union. Trotskyist under the Dunne brothers and Carl Skoglund. SWP National Secretary after Cannon; SWP presidential candidate in 1948, 1952, 1956, and 1960. 16 months at FCI Sandstone.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'prosecutor' => 'Victor E. Anderson', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Albert Goldman', 'first_name' => 'Albert', 'last_name' => 'Goldman', 'aka' => 'Albert Verblen', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1897-01-01', 'death_date' => '1960-12-15', 'description' => 'Belarusian-Jewish-born Chicago lawyer who served as Leon Trotsky\'s American attorney and represented him at the 1937 Dewey Commission hearings in Mexico City. Originally a CP legal-defense attorney, expelled 1933 for Trotskyism. In the 1941 Minneapolis trial was both chief defense counsel and a defendant; made the closing argument for the SWP. Disbarred after his conviction. 16 months federal prison.', 'affiliation' => ['Socialist Workers Party', 'Workers Party (post-1946)', 'Illinois Bar (disbarred)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'prosecutor' => 'Victor E. Anderson', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Felix Morrow', 'first_name' => 'Felix', 'last_name' => 'Morrow', 'aka' => 'Felix Mayrowitz', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1906-06-03', 'death_date' => '1988-05-28', 'description' => 'Trotskyist editor and theoretician. Edited the SWP\'s newspaper The Militant and its theoretical journal Fourth International from 1940. His book "Revolution and Counter-Revolution in Spain" (1938) is a classic Trotskyist analysis of the Spanish Civil War. After his Smith Act sentence, expelled from SWP 1946. Later became VP at Schocken Books.', 'affiliation' => ['Socialist Workers Party', 'Workers Party (post-1946)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Carl Skoglund', 'first_name' => 'Carl', 'last_name' => 'Skoglund', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1884-04-10', 'death_date' => '1960-12-11', 'description' => 'Swedish-born Teamster organizer; co-founder of American Trotskyism. Emigrated 1911; joined the IWW; founding CPUSA. Expelled 1928 with Cannon for Trotskyism. President of Teamsters Local 544; central leader of 1934 Minneapolis truckers\' strike. After serving 16 months for Smith Act conviction, U.S. government tried to deport him for the rest of his life. Died in 1960 still under deportation order.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544', 'IWW (former)', 'Communist Party USA (former)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison; subjected to repeated deportation proceedings 1949-1960', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385); subsequent McCarran Act deportation proceedings.']]],
    ['name' => 'Harry DeBoer', 'first_name' => 'Harry', 'last_name' => 'DeBoer', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1903-01-01', 'death_date' => '1992-12-15', 'description' => 'Minneapolis coal-yard Teamster; leader of the 1934 Minneapolis Teamsters Strike, credited with developing the "cruising picket" tactic. Wounded by police gunfire on Bloody Friday during the 1934 strike. SWP labor activist for decades; authored the 1987 essay "How to Win Strikes: Lessons from the 1934 Minneapolis Truckers Strike."', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '12 months and a day', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Grace Holmes Carlson', 'first_name' => 'Grace', 'middle_name' => 'Holmes', 'last_name' => 'Carlson', 'gender' => 'Female', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1906-11-14', 'death_date' => '1992-07-07', 'description' => 'The only woman convicted in the 1941 Minneapolis Smith Act trial. PhD University of Minnesota 1933. Delegate to the SWP\'s founding 1938 convention; Minnesota state organizer; SWP\'s vice-presidential candidate 1948. Served 16 months alone at the federal women\'s prison at Alderson, WV. In 1952 abruptly left the SWP, returned to Catholicism, became a psychology professor advocating social justice as a "Catholic Marxist."', 'affiliation' => ['Socialist Workers Party (Minnesota state organizer)'], 'cases' => [['institution' => ['name' => 'Federal Prison Camp, Alderson — 1941 Minneapolis Smith Act', 'city' => 'Alderson', 'state' => 'West Virginia'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Jake Cooper', 'first_name' => 'Jake', 'last_name' => 'Cooper', 'aka' => 'Jacob Cooper', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1916-01-01', 'death_date' => '1990-12-15', 'description' => 'Minneapolis Teamster who served as one of Leon Trotsky\'s bodyguards at Coyoacán, Mexico for four months in 1940. Participant in 1934 Minneapolis Teamsters Strike. Following 16-month Smith Act sentence, lifelong Trotskyist; when Jack Barnes\'s SWP leadership abandoned Trotskyism in the 1980s, Cooper joined the expelled faction that formed Socialist Action.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544', 'Socialist Action (later)'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Max Geldman', 'first_name' => 'Max', 'last_name' => 'Geldman', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'birthdate' => '1905-01-01', 'description' => 'Polish-Jewish-born Trotskyist organizer of WPA workers in Minneapolis. Born in Warsaw and brought to America as a child. Joined the Trotskyist movement in 1931. Led the July 1939 WPA workers\' strike. Notably, had previously been imprisoned at Sandstone for that 1939 strike — his second time there in 1944 was for the Smith Act. Remained in SWP for over 50 years.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544 Federal Workers Section'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1945-01-15', 'sentence' => '12-16 months federal prison', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],
    ['name' => 'Carlos Hudson', 'first_name' => 'Carlos', 'last_name' => 'Hudson', 'gender' => 'Male', 'race' => 'White', 'state' => 'Minnesota', 'description' => 'Secretary of the Minneapolis branch of the Socialist Workers Party; editor of "544 Weekly," the newspaper of Teamsters Local 544.', 'affiliation' => ['Socialist Workers Party', 'Teamsters Local 544'], 'cases' => [['institution' => ['name' => 'FCI Sandstone — 1941 Minneapolis Smith Act', 'city' => 'Sandstone', 'state' => 'Minnesota'], 'arrest_date' => '1941-07-15', 'sentenced_date' => '1941-12-08', 'incarceration_date' => '1943-12-31', 'release_date' => '1944-12-15', 'sentence' => '12 months and a day', 'convicted' => 'Yes', 'judge' => 'Hon. Matthew M. Joyce', 'charges' => 'Smith Act conspiracy (18 U.S.C. § 2385).']]],

    // Taft-Hartley + Bridges
    ['name' => 'Ben Gold', 'first_name' => 'Ben', 'last_name' => 'Gold', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1898-01-01', 'death_date' => '1985-12-15', 'description' => 'Bessarabia-born; longtime Communist president of the International Fur and Leather Workers Union. Resigned publicly from CPUSA on August 24, 1950 to be able to sign the Taft-Hartley non-Communist affidavit. Indicted in August 1953, one day before the statute of limitations ran, charging the resignation was a sham. Convicted of perjury in 1954; sentenced 1-3 years; conviction reversed by SCOTUS 1957.', 'affiliation' => ['International Fur and Leather Workers Union (President)', 'Communist Party USA (until Aug 1950)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, S.D.N.Y. — Taft-Hartley §9(h) prosecution', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1953-08-15', 'sentenced_date' => '1954-01-15', 'release_date' => '1957-06-15', 'sentence' => '1 to 3 years federal prison; reversed by SCOTUS 1957', 'convicted' => 'Yes; reversed', 'charges' => 'Perjury under 18 U.S.C. § 1621 in connection with non-Communist affidavit filed under §9(h), Taft-Hartley Act / LMRA 1947 (29 U.S.C. § 159(h)).']]],
    ['name' => 'Hugh Bryson', 'first_name' => 'Hugh', 'last_name' => 'Bryson', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'description' => 'President of the National Union of Marine Cooks and Stewards, a left-led maritime union expelled from the CIO in 1950 for Communist domination. CPUSA member from at least 1937. Signed Taft-Hartley non-Communist affidavits in April 1951; tried and convicted 1955 under 18 U.S.C. § 1001 of falsely denying CPUSA affiliation. Conviction upheld at Bryson v. United States, 396 U.S. 64 (1969).', 'affiliation' => ['National Union of Marine Cooks and Stewards (President)', 'Communist Party USA'], 'cases' => [['institution' => ['name' => 'U.S. District Court, N.D. Cal. — Taft-Hartley §9(h)', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1954-06-15', 'sentenced_date' => '1955-06-15', 'release_date' => '1960-06-15', 'sentence' => '5 years federal prison + $10,000 fine', 'convicted' => 'Yes', 'charges' => 'False statement (18 U.S.C. § 1001) in non-Communist affidavit under Taft-Hartley §9(h). Affirmed Bryson v. United States, 396 U.S. 64 (1969).']]],
    ['name' => 'Maurice E. Travis', 'first_name' => 'Maurice', 'middle_name' => 'E.', 'last_name' => 'Travis', 'gender' => 'Male', 'race' => 'White', 'state' => 'Colorado', 'description' => 'CPUSA member who became secretary-treasurer and then president (1947) of the International Union of Mine, Mill and Smelter Workers (IUMMSW). Publicly renounced his CP membership to sign Taft-Hartley affidavits, then was indicted for perjury/false statement on the basis that the renunciation was fraudulent. Convicted in U.S. District Court for Colorado, but the Supreme Court reversed in Travis v. United States, 364 U.S. 631 (1961), holding that venue lay only in the District of Columbia where the affidavits were filed.', 'affiliation' => ['International Union of Mine, Mill and Smelter Workers (President)', 'Communist Party USA'], 'cases' => [['institution' => ['name' => 'U.S. District Court, District of Colorado — Taft-Hartley §9(h)', 'city' => 'Denver', 'state' => 'Colorado'], 'arrest_date' => '1956-06-15', 'sentenced_date' => '1959-06-15', 'release_date' => '1961-06-15', 'sentence' => 'Federal prison sentence; reversed on venue grounds by SCOTUS 1961', 'convicted' => 'Yes; reversed', 'charges' => 'False statement (18 U.S.C. § 1001) in Taft-Hartley §9(h) affidavit. Reversed Travis v. United States, 364 U.S. 631 (1961).']]],
    ['name' => 'Harry Bridges', 'first_name' => 'Harry', 'last_name' => 'Bridges', 'aka' => 'Alfred Renton Bridges', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1901-07-28', 'death_date' => '1990-03-30', 'description' => 'Australian-born president of the International Longshore and Warehouse Union (ILWU) for 40 years. Led the 1934 West Coast Waterfront Strike; founded the ILWU in 1937. The U.S. government pursued him in four major proceedings (1939, 1941, 1948-55) attempting to deport him as a Communist. In 1949 indicted for perjury and conspiracy for denying CP membership in his 1945 naturalization. Convicted 1950, sentenced 5 years; jailed 3 weeks August 1950 before bail. Reversed by SCOTUS Bridges v. United States, 346 U.S. 209 (1953).', 'affiliation' => ['International Longshore and Warehouse Union (President)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, N.D. Cal. — Bridges denaturalization/perjury', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1949-05-25', 'sentenced_date' => '1950-04-04', 'release_date' => '1953-06-15', 'sentence' => '5 years federal prison; conviction reversed by SCOTUS 1953; ~3 weeks served August 1950', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. George B. Harris', 'prosecutor' => 'F. Joseph Donohue (DOJ Special Prosecutor)', 'charges' => 'Perjury (18 U.S.C. § 1621) and conspiracy to defraud the U.S. (18 U.S.C. § 371) in 1945 naturalization. Reversed Bridges v. United States, 346 U.S. 209 (1953).']]],

    // Espionage-perjury
    ['name' => 'Alger Hiss', 'first_name' => 'Alger', 'last_name' => 'Hiss', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1904-11-11', 'death_date' => '1996-11-15', 'description' => 'Harvard-trained State Department official who served as Secretary-General of the founding UN Conference at San Francisco in 1945; with FDR at Yalta. In 1948, Whittaker Chambers told HUAC that Hiss had been a secret CPUSA member who passed classified documents to the Soviets in the 1930s. The espionage statute of limitations had run; Hiss was indicted for perjury for denying Chambers\' allegations. After a hung jury in his first trial, convicted in January 1950; two concurrent 5-year terms. Maintained his innocence for 46 years until his death.', 'affiliation' => ['U.S. State Department (former)', 'Carnegie Endowment for International Peace (former)'], 'cases' => [['institution' => ['name' => 'USP Lewisburg — Hiss perjury trial', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1948-12-15', 'sentenced_date' => '1950-01-25', 'incarceration_date' => '1951-03-22', 'release_date' => '1954-11-27', 'sentence' => 'Two concurrent 5-year federal sentences; served 44 months', 'convicted' => 'Yes', 'judge' => 'Hon. Henry W. Goddard (S.D.N.Y.)', 'prosecutor' => 'Thomas F. Murphy', 'charges' => 'Two counts of perjury, 18 U.S.C. § 1621 (denying passing documents to Chambers; denying seeing Chambers after Jan 1, 1937).']]],
    ['name' => 'William Walter Remington', 'first_name' => 'William', 'middle_name' => 'Walter', 'last_name' => 'Remington', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1917-10-25', 'death_date' => '1954-11-24', 'released' => false, 'description' => 'Phi Beta Kappa, magna cum laude Dartmouth economist (1939) who held senior posts at OPA, the War Production Board, and the Department of Commerce. In 1948 Elizabeth Bentley named him to HUAC as a Soviet source; in 1950 indicted for perjury for denying CPUSA membership. First conviction reversed; retried 1953 on two perjury counts; 3 years. Murdered in his cell at Lewisburg Federal Penitentiary in November 1954 by fellow inmates — frequently cited as one of the few homicides directly attributable to McCarthyism.', 'affiliation' => ['U.S. Department of Commerce (former)', 'OPA / War Production Board (former)'], 'cases' => [['institution' => ['name' => 'USP Lewisburg — Remington perjury trial', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1950-06-08', 'sentenced_date' => '1953-03-15', 'incarceration_date' => '1953-04-15', 'death_in_custody_date' => '1954-11-24', 'sentence' => '3 years federal prison; murdered in custody Nov 24, 1954', 'convicted' => 'Yes', 'judge' => 'Hon. Vincent L. Leibell (S.D.N.Y., second trial)', 'prosecutor' => 'Thomas F. Murphy; later Roy Cohn', 'charges' => 'Perjury, 18 U.S.C. § 1621 (denying YCL membership at Dartmouth; denying providing information to Elizabeth Bentley).']]],

    // McCarran Act deportation
    ['name' => 'Cedric Belfrage', 'first_name' => 'Cedric', 'middle_name' => 'Henning', 'last_name' => 'Belfrage', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1904-11-08', 'death_date' => '1990-06-21', 'description' => 'British-born film critic and journalist who co-founded the radical U.S. weekly National Guardian in 1948 with James Aronson and John T. McManus. Served in British Security Coordination in New York during WWII. Summoned by HUAC and the McCarran Subcommittee in 1953; invoked the Fifth Amendment. Deported under the McCarran Act on August 15, 1955; edited the National Guardian in exile from Mexico and Britain until 1967. Author of "The Frightened Giant" (1956).', 'affiliation' => ['National Guardian (co-founder, editor)', 'British Security Coordination (WWII)', 'Communist Party USA (1937-1945, alleged under alias)'], 'cases' => [['institution' => ['name' => 'Ellis Island Detention — Belfrage McCarran Act deportation', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1953-04-15', 'sentenced_date' => '1955-08-15', 'release_date' => '1955-08-15', 'sentence' => 'Deportation to United Kingdom August 15, 1955', 'convicted' => 'Deportation order', 'charges' => 'Deportation under Internal Security Act of 1950 (McCarran Act, 8 U.S.C. § 1251) for alleged former CPUSA membership.']]],

    // Civil Rights Congress
    ['name' => 'William Lorenzo Patterson', 'first_name' => 'William', 'middle_name' => 'Lorenzo', 'last_name' => 'Patterson', 'aka' => 'Pat', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1891-08-27', 'death_date' => '1980-03-05', 'description' => 'Hastings-trained lawyer who defended Sacco and Vanzetti, led the International Labor Defense\'s Scottsboro Boys campaign, and as executive secretary of the Civil Rights Congress co-authored and presented the petition "We Charge Genocide" to the United Nations in Paris on December 17, 1951. The State Department forced him to surrender his passport. Subpoenaed by HUAC and SISS multiple times in 1950; held in contempt of Congress and served two consecutive 90-day federal sentences in 1954-55 for refusing to disclose CRC donor lists.', 'affiliation' => ['Communist Party USA (joined 1927)', 'International Labor Defense (head)', 'Civil Rights Congress (executive secretary)'], 'cases' => [['institution' => ['name' => 'FCI Danbury — Patterson HUAC contempt', 'city' => 'Danbury', 'state' => 'Connecticut'], 'arrest_date' => '1954-05-15', 'sentenced_date' => '1954-06-15', 'release_date' => '1955-03-15', 'sentence' => 'Two consecutive 90-day federal sentences', 'convicted' => 'Yes', 'charges' => 'Contempt of Congress (2 U.S.C. § 192) for refusing to produce CRC donor lists / bail-fund records.']]],

    // Trenton Six
    ['name' => 'Collis English', 'first_name' => 'Collis', 'last_name' => 'English', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'birthdate' => '1925-01-01', 'death_date' => '1952-12-15', 'released' => false, 'description' => 'One of the Trenton Six. The Trenton Six were six young Black men arrested February 11, 1948 and charged with the murder of William Horner, a 73-year-old white second-hand shop owner, on the basis of confessions extracted during 60+ hours of interrogation without counsel. After a 55-day trial in Mercer County Court, an all-white jury convicted all six on August 6, 1948 and sentenced them to death — a verdict the Civil Rights Congress and NAACP called a "Northern lynching." NJ Supreme Court reversed 1949; on retrial four were acquitted, Cooper pleaded guilty, and English was convicted with a life-sentence recommendation. English died in prison late 1952.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'death_in_custody_date' => '1952-12-15', 'sentence' => 'Death; commuted to life on retrial; died in prison late 1952', 'convicted' => 'Yes', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder of William Horner (Jan 27, 1948).']]],
    ['name' => 'McKinley Forrest', 'first_name' => 'McKinley', 'last_name' => 'Forrest', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'description' => 'Trenton Six defendant. Acquitted on retrial 1951.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'release_date' => '1951-06-15', 'sentence' => 'Death (acquitted on retrial 1951)', 'convicted' => 'Yes (initial); acquitted on retrial', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder.']]],
    ['name' => 'John MacKenzie', 'first_name' => 'John', 'last_name' => 'MacKenzie', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'description' => 'Trenton Six defendant. Acquitted on retrial 1951.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'release_date' => '1951-06-15', 'sentence' => 'Death (acquitted on retrial 1951)', 'convicted' => 'Yes (initial); acquitted on retrial', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder.']]],
    ['name' => 'Ralph Cooper', 'first_name' => 'Ralph', 'last_name' => 'Cooper', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'description' => 'Trenton Six defendant. Pleaded guilty at retrial — life imprisonment; paroled 1954.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'release_date' => '1954-06-15', 'sentence' => 'Death; pleaded guilty at retrial — life imprisonment; paroled 1954', 'convicted' => 'Yes — guilty plea on retrial', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder.']]],
    ['name' => 'Horace Wilson', 'first_name' => 'Horace', 'last_name' => 'Wilson', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'description' => 'Trenton Six defendant. Acquitted on retrial 1951.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'release_date' => '1951-06-15', 'sentence' => 'Death (acquitted on retrial 1951)', 'convicted' => 'Yes (initial); acquitted on retrial', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder.']]],
    ['name' => 'James H. Thorpe Jr.', 'first_name' => 'James', 'middle_name' => 'H.', 'last_name' => 'Thorpe Jr.', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New Jersey', 'description' => 'Trenton Six defendant. Acquitted on retrial 1951.', 'affiliation' => ['Trenton Six'], 'cases' => [['institution' => ['name' => 'New Jersey State Prison, Trenton — Trenton Six', 'city' => 'Trenton', 'state' => 'New Jersey'], 'arrest_date' => '1948-02-11', 'sentenced_date' => '1948-08-06', 'release_date' => '1951-06-15', 'sentence' => 'Death (acquitted on retrial 1951)', 'convicted' => 'Yes (initial); acquitted on retrial', 'judge' => 'Hon. Charles P. Hutchinson', 'prosecutor' => 'Mario Volpe', 'charges' => 'New Jersey state murder.']]],

    // Willie McGee
    ['name' => 'Willie McGee', 'first_name' => 'Willie', 'last_name' => 'McGee', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Mississippi', 'birthdate' => '1915-01-01', 'death_date' => '1951-05-08', 'released' => false, 'description' => 'Black laborer from Laurel, Mississippi accused November 1945 of raping Willette Hawkins, a white housewife — a charge his defense (led by young Bella Abzug for the Civil Rights Congress) argued masked a long-running consensual relationship and was a frame-up. Convicted three times before all-white juries (the first jury deliberated only 2½ minutes). Case became a global cause célèbre with appeals from Albert Einstein, William Faulkner, Josephine Baker, and Jessica Mitford. Executed in Mississippi\'s portable electric chair on May 8, 1951 in the Laurel courthouse before a cheering white crowd.', 'affiliation' => ['Defended by Civil Rights Congress'], 'cases' => [['institution' => ['name' => 'Hinds County Jail / Laurel Courthouse — Willie McGee execution', 'city' => 'Laurel', 'state' => 'Mississippi'], 'arrest_date' => '1945-11-02', 'sentenced_date' => '1945-12-15', 'death_in_custody_date' => '1951-05-08', 'sentence' => 'Death by electrocution May 8, 1951', 'convicted' => 'Yes (3 trials)', 'judge' => 'Hon. John C. Stennis (later U.S. Senator)', 'prosecutor' => 'Paul Swartzfager (Jones County DA)', 'charges' => 'Mississippi state rape (alleged of Willette Hawkins).']]],
];

// Martinsville Seven (compact)
foreach ([
    ['Joe Henry Hampton', '1951-02-02'],
    ['Booker T. Millner', '1951-02-02'],
    ['Frank Hairston Jr.', '1951-02-02'],
    ['Howard Lee Hairston', '1951-02-02'],
    ['James Luther Hairston', '1951-02-05'],
    ['John Clabon Taylor', '1951-02-05'],
    ['Francis DeSales Grayson', '1951-02-05'],
] as $row) {
    [$name, $execDate] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts); $middle = count($parts) >= 3 ? $parts[1] : null;
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => 'Male', 'race' => 'Black', 'state' => 'Virginia',
        'death_date' => $execDate, 'released' => false,
        'description' => 'One of the Martinsville Seven — seven Black Virginia men arrested January 1949 for the alleged gang rape of Ruby Stroud Floyd, a white Jehovah\'s Witness, in Martinsville. In six separate one-day trials before Judge Kennon C. Whittle and all-white juries (the prosecution struck every Black potential juror), all seven were convicted within hours and sentenced to death. The Civil Rights Congress and NAACP mounted dueling defense campaigns; Eleanor Roosevelt and figures across the world appealed for clemency. Four were electrocuted at the Virginia State Penitentiary on February 2, 1951 and the remaining three on February 5, 1951 — the largest mass execution for a single non-capital-murder crime in U.S. history. Posthumously pardoned by Governor Ralph Northam, August 31, 2021.',
        'affiliation' => ['Martinsville Seven'],
        'cases' => [['institution' => ['name' => 'Virginia State Penitentiary — Martinsville Seven', 'city' => 'Richmond', 'state' => 'Virginia'], 'arrest_date' => '1949-01-08', 'sentenced_date' => '1949-04-21', 'death_in_custody_date' => $execDate, 'sentence' => 'Death by electrocution', 'convicted' => 'Yes', 'judge' => 'Hon. Kennon C. Whittle', 'charges' => 'Virginia state rape (alleged gang rape of Ruby Stroud Floyd, Jan 8, 1949).']],
    ];
}

// Groveland Four
$people[] = ['name' => 'Charles Lee Greenlee Sr.', 'first_name' => 'Charles', 'middle_name' => 'Lee', 'last_name' => 'Greenlee Sr.', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Florida', 'birthdate' => '1933-06-04', 'death_date' => '2012-04-18', 'description' => 'One of the Groveland Four — four Black men accused on July 16, 1949 of raping 17-year-old Norma Padgett, a white woman, in Lake County, Florida — an accusation later proven false. Greenlee was 16 at arrest; sentenced to life imprisonment as a juvenile; paroled 1962. Officially exonerated by Florida courts in 2021.', 'affiliation' => ['Groveland Four'], 'cases' => [['institution' => ['name' => 'Raiford State Prison — Groveland Four', 'city' => 'Raiford', 'state' => 'Florida'], 'arrest_date' => '1949-07-16', 'sentenced_date' => '1949-09-15', 'release_date' => '1962-12-15', 'sentence' => 'Life imprisonment (juvenile); paroled 1962', 'convicted' => 'Yes', 'judge' => 'Hon. Truman G. Futch', 'prosecutor' => 'Jesse Hunter', 'charges' => 'Florida state rape (alleged of Norma Padgett, July 16, 1949).']]];
$people[] = ['name' => 'Walter Lee Irvin', 'first_name' => 'Walter', 'middle_name' => 'Lee', 'last_name' => 'Irvin', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Florida', 'birthdate' => '1928-01-01', 'death_date' => '1969-02-15', 'description' => 'One of the Groveland Four. WWII Army veteran. Sentenced to death; commuted to life by Gov. LeRoy Collins 1955; paroled 1968. Defended on retrial by Thurgood Marshall. Shot point-blank by Sheriff Willis V. McCall on November 6, 1951 while handcuffed during transport; survived by playing dead.', 'affiliation' => ['Groveland Four'], 'cases' => [['institution' => ['name' => 'Raiford State Prison — Groveland Four', 'city' => 'Raiford', 'state' => 'Florida'], 'arrest_date' => '1949-07-16', 'sentenced_date' => '1949-09-15', 'release_date' => '1968-06-15', 'sentence' => 'Death (commuted to life 1955); paroled 1968', 'convicted' => 'Yes', 'judge' => 'Hon. Truman G. Futch', 'prosecutor' => 'Jesse Hunter', 'charges' => 'Florida state rape (alleged).']]];
$people[] = ['name' => 'Samuel Shepherd', 'first_name' => 'Samuel', 'last_name' => 'Shepherd', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Florida', 'birthdate' => '1925-04-07', 'death_date' => '1951-11-06', 'released' => false, 'description' => 'One of the Groveland Four. WWII Army veteran. Sentenced to death; killed by Sheriff Willis V. McCall on November 6, 1951 while handcuffed in transport.', 'affiliation' => ['Groveland Four'], 'cases' => [['institution' => ['name' => 'Raiford State Prison — Groveland Four', 'city' => 'Raiford', 'state' => 'Florida'], 'arrest_date' => '1949-07-16', 'sentenced_date' => '1949-09-15', 'death_in_custody_date' => '1951-11-06', 'sentence' => 'Death; killed by Sheriff McCall in transport November 6, 1951', 'convicted' => 'Yes', 'judge' => 'Hon. Truman G. Futch', 'prosecutor' => 'Jesse Hunter', 'charges' => 'Florida state rape (alleged).']]];
$people[] = ['name' => 'Ernest Thomas', 'first_name' => 'Ernest', 'last_name' => 'Thomas', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Florida', 'birthdate' => '1923-01-01', 'death_date' => '1949-07-26', 'released' => false, 'description' => 'One of the Groveland Four. Tracked down and shot more than 400 times by a 1,000-strong posse led by Sheriff Willis McCall while sleeping under a tree in Madison County, Florida on July 26, 1949 — never charged.', 'affiliation' => ['Groveland Four'], 'cases' => [['institution' => ['name' => 'Madison County, Florida — Groveland Four', 'city' => 'Madison', 'state' => 'Florida'], 'death_in_custody_date' => '1949-07-26', 'sentence' => 'Killed in extrajudicial posse July 26, 1949', 'convicted' => 'Killed before charges', 'charges' => 'Never charged — killed by sheriff\'s posse.']]];

// Oscar Collazo
$people[] = ['name' => 'Oscar Collazo', 'first_name' => 'Oscar', 'last_name' => 'Collazo', 'gender' => 'Male', 'race' => 'Latino/Hispanic', 'state' => 'New York', 'birthdate' => '1914-01-20', 'death_date' => '1994-02-21', 'description' => 'Puerto Rican Nationalist Party member who, with Griselio Torresola, attempted to assassinate President Harry S. Truman at Blair House on November 1, 1950, in response to U.S. suppression of the Jayuya Uprising in Puerto Rico the day before. White House Police Officer Leslie Coffelt was killed; Coffelt killed Torresola; Secret Service agents wounded Collazo. Tried before Judge T. Alan Goldsborough; convicted March 7, 1951; sentenced to death — commuted to life by Truman July 1952. Carter commuted to time served and released him September 6, 1979.', 'affiliation' => ['Puerto Rican Nationalist Party (Partido Nacionalista de Puerto Rico)'], 'ideologies' => ['Puerto Rican independence', 'Anti-colonialism'], 'cases' => [['institution' => ['name' => 'USP Leavenworth — Truman Blair House attack', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1950-11-01', 'sentenced_date' => '1951-03-22', 'release_date' => '1979-09-06', 'sentence' => 'Death — commuted to life imprisonment by Truman July 24, 1952; commuted to time served by Carter September 6, 1979', 'convicted' => 'Yes', 'judge' => 'Hon. T. Alan Goldsborough', 'prosecutor' => 'George Morris Fay (U.S. Atty., D.C.)', 'charges' => 'Murder of Officer Leslie Coffelt; attempted assassination of the President.']]];

// CO
$people[] = ['name' => 'Larry Gara', 'first_name' => 'Larry', 'last_name' => 'Gara', 'aka' => 'Lawrence Gara', 'gender' => 'Male', 'race' => 'White', 'state' => 'Ohio', 'birthdate' => '1922-07-25', 'death_date' => '2019-11-22', 'description' => 'Quaker pacifist, historian, and lifelong war resister. Served three years in federal prison as a WWII conscientious objector. In 1948, while teaching at Bluffton College in Ohio, was prosecuted under the Selective Service Act of 1948 for allegedly counseling a student, Charles Rickert, not to register for the Korean War-era draft — a high-profile prosecution intended to deter draft counselors. Conviction upheld in Gara v. United States, 340 U.S. 857 (1950). Bluffton College apologized in 2015. Later prominent Underground Railroad scholar at Wilmington College.', 'affiliation' => ['Religious Society of Friends (Quakers)', 'War Resisters League'], 'ideologies' => ['Pacifism', 'Quakerism'], 'cases' => [['institution' => ['name' => 'Federal prison — Gara v. US (Korean War CO counseling)', 'city' => null, 'state' => 'Ohio'], 'arrest_date' => '1949-01-15', 'sentenced_date' => '1949-03-15', 'release_date' => '1950-12-15', 'sentence' => '18 months federal prison (served ~7 months)', 'convicted' => 'Yes; affirmed Gara v. United States, 340 U.S. 857 (1950)', 'charges' => 'Counseling another to refuse Selective Service registration (Selective Service Act of 1948).']]];

// ===== Apply =====
foreach ($people as $p) {
    $p['ideologies'] = $p['ideologies'] ?? ['Communism / Trotskyism / Pacifism / Civil rights (Truman-era leftist prosecution)'];
    $p['affiliation'] = $p['affiliation'] ?? ['Communist Party USA'];
    $p['era'] = $p['era'] ?? '1950s';
    [$prisoner, $created] = addP($p);
    echo ($created ? '  CREATED' : '  EXISTS ') . " {$p['name']} (id={$prisoner->id})\n";
    $created ? $tot['created']++ : $tot['existed']++;
    foreach ($p['cases'] ?? [] as $c) {
        if (attachC($prisoner, $c)) { echo "    + case ({$c['arrest_date']})\n"; $tot['cases']++; }
    }
}

echo "\nDone. created={$tot['created']}, existed={$tot['existed']}, cases={$tot['cases']}\n";
