#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_missing_prisoners_2026_05.sh
set -e

# ============================================================
# Recent (2024-2026) — already drafted in chat but included here for completeness
# ============================================================

php artisan prisoner:add '{"name":"Casey Goonan","first_name":"Casey","last_name":"Goonan","description":"Casey Goonan is a Palestine-solidarity activist who on July 2, 2024 set fire to a University of California Police Department vehicle parked on the UC Berkeley campus, in protest of UC investments in companies tied to Israel and the role of campus police in suppressing pro-Palestinian protest during the war in Gaza. He claimed the action publicly. He was arrested by federal authorities and pleaded guilty in 2025 to federal arson and use of fire to commit a federal felony. He was sentenced to approximately seven years in federal prison with the federal terrorism enhancement applied — among the longest sentences imposed on a U.S. anti-war activist in the post-October 7 Palestine solidarity wave.","state":"California","gender":"Male","ideologies":["Anti-war","Palestine solidarity","Anti-imperialist"],"in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons","institution_state":"California","charges":"Federal arson; use of fire to commit a federal felony — July 2, 2024 firebombing of a UC Berkeley police vehicle in protest of UC investments in Israel and U.S. support for the war in Gaza","arrest_date":"2024-07-02","incarceration_date":"2024-07-02","sentence":"~84 months federal prison with terrorism enhancement","convicted":"Yes — guilty plea, 2025"}]}'

php artisan prisoner:add '{"name":"Ruby Montoya","first_name":"Ruby","last_name":"Montoya","description":"Ruby Montoya is an environmental and Indigenous-solidarity activist and the co-defendant of Jessica Reznicek (also in this database) in the federal prosecution of the 2016-2017 Dakota Access Pipeline sabotage campaign in Iowa. The two used oxyacetylene torches to burn through exposed pipeline valves and disable construction equipment at multiple sites, in an attempt to halt completion of the pipeline that crosses Standing Rock Sioux water sources. They publicly claimed the actions in a 2017 press conference at the Iowa Utilities Board. Montoya pleaded guilty in 2021 to conspiracy to damage an energy facility. She was sentenced in August 2022 to 72 months in federal prison with the federal terrorism enhancement applied, plus restitution of approximately three million dollars jointly with Reznicek.","state":"Iowa","gender":"Female","ideologies":["Environmental","Indigenous solidarity","Anti-pipeline"],"affiliation":["Catholic Worker"],"in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons","institution_state":"Iowa","charges":"Conspiracy to damage an energy facility; arson — 2016-2017 Dakota Access Pipeline sabotage in Iowa","incarceration_date":"2022-08-15","sentence":"72 months federal prison with terrorism enhancement; ~$3M restitution joint with Jessica Reznicek","convicted":"Yes — guilty plea, 2021"}]}'

php artisan prisoner:add '{"name":"Leqaa Kordia","first_name":"Leqaa","last_name":"Kordia","description":"Leqaa Kordia is a Palestinian woman and longtime New Jersey resident who was detained by ICE in March 2025 as part of the Trump administrations campaign of immigration enforcement against participants in pro-Palestinian campus protests. She had attended demonstrations in the Columbia University area. She was arrested in Newark and transferred to the Prairieland Detention Center in Texas, where she was held for months. Federal authorities cited an alleged visa overstay rather than any criminal charge, but the targeting was widely understood as retaliation for her protest activity.","state":"New Jersey","race":"Arab","gender":"Female","ideologies":["Palestine solidarity","Anti-War"],"in_custody":false,"released":true,"cases":[{"institution_name":"Prairieland Detention Center","institution_city":"Alvarado","institution_state":"Texas","charges":"Immigration detention — ICE arrest framed as visa overstay; widely understood as targeting for Columbia-area pro-Palestinian protest activity. No criminal charges.","arrest_date":"2025-03-14","incarceration_date":"2025-03-14","sentence":"Held in immigration detention for several months at Prairieland","convicted":"No — immigration detention, no criminal charges"}]}'

php artisan prisoner:add '{"name":"Alireza Doroudi","first_name":"Alireza","last_name":"Doroudi","description":"Alireza Doroudi is an Iranian PhD student in mechanical engineering at the University of Alabama who was arrested at his home in Tuscaloosa by ICE on March 25, 2025, as part of the Trump administrations wave of visa revocations and detentions targeting international students associated with pro-Palestinian campus activism. The U.S. State Department revoked his student visa. He was held in immigration detention at the LaSalle ICE Processing Center in Jena, Louisiana. Rather than continue fighting the case from detention, he chose to self-deport to Iran in April 2025.","state":"Alabama","race":"Arab","gender":"Male","ideologies":["Palestine solidarity","Anti-War"],"in_custody":false,"released":true,"in_exile":true,"cases":[{"institution_name":"LaSalle ICE Processing Center","institution_city":"Jena","institution_state":"Louisiana","charges":"Immigration detention — student visa revoked by U.S. State Department in March 2025 in connection with the Trump administrations targeting of pro-Palestinian international students. No criminal charges.","arrest_date":"2025-03-25","incarceration_date":"2025-03-25","release_date":"2025-04-15","sentence":"Held approximately three weeks in ICE detention; self-deported to Iran","convicted":"No — immigration detention, no criminal charges"}]}'

# ============================================================
# Foundational Black liberation
# ============================================================

php artisan prisoner:add '{"name":"George Jackson","first_name":"George","last_name":"Jackson","description":"George Lester Jackson was a Black revolutionary, author, and Field Marshal of the Black Panther Party — and the most influential Black political prisoner of his generation. Sentenced in 1961 at age 18 to one year to life for his alleged role in a $70 gas station robbery, he served the remaining ten years of his life behind bars, much of it in solitary confinement at Soledad and San Quentin. From inside, he co-founded the Black Guerrilla Family in 1966 and became a Field Marshal of the BPP in 1970. His prison letters, published in 1970 as Soledad Brother, became one of the foundational texts of the Black liberation movement, selling hundreds of thousands of copies and translated worldwide. His second book, Blood in My Eye, was completed days before his death and published posthumously in 1972.\n\nIn January 1970, after a white guard at Soledad shot and killed three Black prisoners during a yard fight, another guard, John Mills, was beaten to death and thrown from a tier. Jackson, along with Fleeta Drumgo and John Cluchette — known as the Soledad Brothers — were charged with the killing despite no physical evidence connecting them to it. The case became an international cause. On August 7, 1970, Jacksons 17-year-old brother Jonathan Jackson stormed the Marin County Courthouse in an attempt to free his brother, taking a judge and three jurors hostage; Jonathan, the judge, and two prisoners died in the resulting shootout.\n\nOn August 21, 1971, three days before he was scheduled to stand trial for the Mills killing, George Jackson was killed by guards at San Quentin in an alleged escape attempt that has been widely disputed in the decades since. He was 29 years old. The killing triggered the Attica prison rebellion three weeks later. Drumgo and Cluchette were acquitted at trial in 1972.","state":"California","race":"Black","gender":"Male","birthdate":"1941-09-23","death_date":"1971-08-21","ideologies":["Black Liberation","Marxist","Revolutionary"],"affiliation":["Black Panther Party","Black Guerrilla Family","Soledad Brothers"],"in_custody":false,"released":false,"cases":[{"institution_name":"San Quentin State Prison","institution_state":"California","charges":"Originally one year to life for $70 gas station robbery (1961); later charged in January 1970 with the murder of Soledad guard John Mills (Soledad Brothers case); killed by guards at San Quentin August 21, 1971 in alleged escape attempt before trial","arrest_date":"1960-09-15","incarceration_date":"1961-01-01","release_date":"1971-08-21","sentence":"One year to life on the original 1961 conviction; killed in custody at San Quentin August 21, 1971 at age 29","convicted":"Yes — 1961 California state conviction; never tried on the Mills killing"}]}'

# ============================================================
# Cold War — the Rosenbergs
# ============================================================

php artisan prisoner:add '{"name":"Julius Rosenberg","first_name":"Julius","last_name":"Rosenberg","description":"Julius Rosenberg was an American electrical engineer and member of the Communist Party USA who, with his wife Ethel Rosenberg, was convicted in 1951 of conspiracy to commit espionage on behalf of the Soviet Union, and executed at Sing Sing Prison on June 19, 1953. The case was the most prominent capital prosecution of American Communists in U.S. history and remains one of the defining political trials of the early Cold War.\n\nThe government alleged that Julius Rosenberg had recruited his brother-in-law David Greenglass, a U.S. Army machinist at Los Alamos, to pass technical information about the atomic bomb to Soviet intelligence. Greenglass and his wife Ruth received immunity in exchange for his testimony, in which he claimed his sister Ethel had typed up his notes — testimony Greenglass admitted in 2001 he had fabricated to protect his wife. The trial was presided over by Judge Irving Kaufman, who imposed the death sentence over the recommendation of the prosecution and the FBI. The Supreme Court refused to hear the case after multiple stays and appeals. Pope Pius XII, Albert Einstein, Jean-Paul Sartre, and millions of demonstrators around the world appealed for clemency; President Eisenhower refused.\n\nThey left two young sons, Michael and Robert, who were adopted and raised under the surname Meeropol and have spent their adult lives advocating for their parents posthumous exoneration.","state":"New York","race":"White","gender":"Male","birthdate":"1918-05-12","death_date":"1953-06-19","ideologies":["Communism"],"affiliation":["Communist Party USA"],"in_custody":false,"released":false,"cases":[{"institution_name":"Sing Sing Prison","institution_city":"Ossining","institution_state":"New York","charges":"Conspiracy to commit espionage on behalf of the Soviet Union (50 U.S.C. § 32 — Espionage Act of 1917)","arrest_date":"1950-07-17","incarceration_date":"1951-04-05","release_date":"1953-06-19","sentence":"Death by electrocution; executed at Sing Sing on June 19, 1953","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, March 29, 1951"}]}'

php artisan prisoner:add '{"name":"Ethel Rosenberg","first_name":"Ethel","last_name":"Rosenberg","description":"Ethel Greenglass Rosenberg was an American Communist Party member, wife of Julius Rosenberg, and the only American woman executed for a crime other than murder in the twentieth century. She was put to death at Sing Sing Prison on June 19, 1953, alongside her husband, after their conviction for conspiracy to commit espionage on behalf of the Soviet Union.\n\nThe federal prosecution against Ethel rested almost entirely on the testimony of her brother David Greenglass, who claimed she had typed up notes containing atomic bomb information that her husband then passed to Soviet intelligence. In 2001, Greenglass admitted publicly to journalist Sam Roberts that he had fabricated this testimony in order to protect his own wife, Ruth, who had received immunity from prosecution in exchange for his cooperation. Grand jury transcripts unsealed in 2008 confirmed that Greenglass had originally told prosecutors his sister had nothing to do with the alleged espionage — and that the FBI and the U.S. Attorneys office had pressured him to change his story to secure her conviction.\n\nThe death sentence imposed by Judge Irving Kaufman over the recommendation of the prosecution and the FBI drew worldwide condemnation. Her execution required five separate jolts of electricity. She left two young sons, Michael and Robert Meeropol, who have campaigned for her posthumous exoneration; in 2015 they formally petitioned President Obama for an exoneration, which was not granted.","state":"New York","race":"White","gender":"Female","birthdate":"1915-09-28","death_date":"1953-06-19","ideologies":["Communism"],"affiliation":["Communist Party USA"],"in_custody":false,"released":false,"cases":[{"institution_name":"Sing Sing Prison","institution_city":"Ossining","institution_state":"New York","charges":"Conspiracy to commit espionage on behalf of the Soviet Union (50 U.S.C. § 32 — Espionage Act of 1917)","arrest_date":"1950-08-11","incarceration_date":"1951-04-05","release_date":"1953-06-19","sentence":"Death by electrocution; executed at Sing Sing on June 19, 1953","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, March 29, 1951; conviction widely regarded as a miscarriage of justice in light of David Greenglass 2001 admission that his trial testimony against her was fabricated"}]}'

# ============================================================
# Hollywood Ten — McCarthy era
# ============================================================

php artisan prisoner:add '{"name":"Dalton Trumbo","first_name":"Dalton","last_name":"Trumbo","description":"James Dalton Trumbo was one of the most prolific and successful screenwriters in Hollywood history (Roman Holiday, Spartacus, Exodus, Johnny Got His Gun) and the most public face of the Hollywood Ten — the ten Hollywood writers, directors, and producers cited for contempt of Congress in November 1947 after refusing on First Amendment grounds to answer the House Un-American Activities Committees demand to know whether they were members of the Communist Party USA. He was a member at the time he was called to testify and made no secret of it after the fact.\n\nAfter exhausting appeals, Trumbo served 11 months at the federal prison camp in Ashland, Kentucky beginning June 1950, alongside fellow Hollywood Ten member John Howard Lawson. While imprisoned he encountered J. Parnell Thomas, the very HUAC chairman who had cited him for contempt, who was serving his own sentence at Danbury for embezzlement.\n\nReleased in 1951, Trumbo was blacklisted from Hollywood for the next decade and continued working under pseudonyms and front writers, winning two Academy Awards under names other than his own (Roman Holiday in 1953, The Brave One in 1956). His public hiring by Otto Preminger in 1960 for Exodus and Kirk Douglas for Spartacus is generally considered the moment that broke the Hollywood blacklist.","state":"California","race":"White","gender":"Male","birthdate":"1905-12-09","death_date":"1976-09-10","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Screen Writers Guild"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Ashland","institution_city":"Ashland","institution_state":"Kentucky","charges":"Contempt of Congress — refusing on First Amendment grounds to answer the House Un-American Activities Committees questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-05-01","sentence":"11 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948; conviction affirmed on appeal in 1949"}]}'

php artisan prisoner:add '{"name":"John Howard Lawson","first_name":"John","middle_name":"Howard","last_name":"Lawson","description":"John Howard Lawson was a screenwriter, the first president of the Screen Writers Guild, and the leading Marxist theorist among Hollywood writers. As the most senior member of the Hollywood Ten, he was the first witness called before the House Un-American Activities Committee in October 1947 and the first to refuse on First Amendment grounds to answer questions about Communist Party membership. He was cited for contempt of Congress on November 24, 1947, exhausted his appeals, and served one year at the federal prison camp in Ashland, Kentucky beginning June 1950 alongside Dalton Trumbo. After his release he was permanently blacklisted from Hollywood and lived the rest of his life as a Marxist theatre critic and historian.","state":"California","race":"White","gender":"Male","birthdate":"1894-09-25","death_date":"1977-08-11","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Screen Writers Guild"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Ashland","institution_city":"Ashland","institution_state":"Kentucky","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-06-09","sentence":"1 year federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Ring Lardner Jr.","first_name":"Ring","middle_name":"Wilmer","last_name":"Lardner Jr.","description":"Ringgold Wilmer Lardner Jr. was an Academy Award-winning screenwriter (Woman of the Year, M*A*S*H) and one of the Hollywood Ten. Asked by the House Un-American Activities Committee in October 1947 whether he was a member of the Communist Party, he gave the most famous of all the Tens responses: I could answer the way you want, Mr. Chairman, but I would hate myself in the morning. He was cited for contempt of Congress on November 24, 1947 and after exhausting appeals served nine months at the federal prison camp in Danbury, Connecticut beginning 1950, alongside fellow Hollywood Ten member Lester Cole. He was blacklisted for the next thirteen years and worked under pseudonyms and fronts during that time.","state":"California","race":"White","gender":"Male","birthdate":"1915-08-19","death_date":"2000-10-31","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Screen Writers Guild"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-03-09","sentence":"9 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Albert Maltz","first_name":"Albert","last_name":"Maltz","description":"Albert Maltz was a novelist, short-story writer, and screenwriter (This Gun for Hire, Pride of the Marines, Destination Tokyo) and one of the Hollywood Ten. Cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served nine months at the federal prison camp in Mill Point, West Virginia beginning June 1950 alongside Edward Dmytryk. He was blacklisted for the rest of his Hollywood career and worked under pseudonyms; he later wrote the Frank Sinatra short film The House I Live In, which won an honorary Academy Award in 1946 — before the blacklist — for its plea against anti-Semitism. He lived in Mexico for many years to escape the blacklist.","state":"California","race":"White","gender":"Male","birthdate":"1908-10-28","death_date":"1985-04-26","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Mill Point","institution_city":"Mill Point","institution_state":"West Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-03-09","sentence":"9 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Alvah Bessie","first_name":"Alvah","last_name":"Bessie","description":"Alvah Cecil Bessie was a novelist, screenwriter (Objective, Burma!), and Spanish Civil War veteran (he had fought in the Abraham Lincoln Brigade against Franco) who became one of the Hollywood Ten. Cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served ten months at the federal prison camp in Texarkana, Texas beginning June 1950 alongside Hollywood Ten director Herbert Biberman. After his release he was permanently blacklisted from Hollywood and worked the rest of his life in San Francisco as a writer and as a stage manager at the hungry i nightclub. His memoir of the blacklist period, Inquisition in Eden, appeared in 1965.","state":"California","race":"White","gender":"Male","birthdate":"1904-06-04","death_date":"1985-07-21","ideologies":["Communism","Anti-fascist","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Abraham Lincoln Brigade"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Texarkana","institution_city":"Texarkana","institution_state":"Texas","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-04-09","sentence":"10 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Herbert Biberman","first_name":"Herbert","last_name":"Biberman","description":"Herbert J. Biberman was a film director and one of the Hollywood Ten. Cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served six months at the federal prison camp in Texarkana, Texas beginning June 1950 alongside Hollywood Ten member Alvah Bessie. After his release and despite the blacklist, he directed the 1954 independent film Salt of the Earth — a sympathetic portrait of a New Mexico zinc miners strike — which was one of the most suppressed films in U.S. history; the projectionists union refused to handle it, theaters refused to screen it, and the lead actress, Rosaura Revueltas, was deported to Mexico mid-shoot. Salt of the Earth is now in the U.S. National Film Registry of the Library of Congress. Biberman was married to Academy Award-winning actress Gale Sondergaard, who was also blacklisted.","state":"California","race":"White","gender":"Male","birthdate":"1900-03-04","death_date":"1971-06-30","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Texarkana","institution_city":"Texarkana","institution_state":"Texas","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1950-12-09","sentence":"6 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Lester Cole","first_name":"Lester","last_name":"Cole","description":"Lester Cole was a screenwriter (Born Free, the credit pseudonymously written from the blacklist) and one of the original founders of the Screen Writers Guild. Cited for contempt of Congress on November 24, 1947 as one of the Hollywood Ten for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served one year at the federal prison camp in Danbury, Connecticut beginning June 1950 alongside Ring Lardner Jr. He was blacklisted for the rest of his Hollywood career and continued writing under pseudonyms. He spent his last decades teaching screenwriting at the San Francisco Art Institute and at the University of California, Berkeley.","state":"California","race":"White","gender":"Male","birthdate":"1904-06-19","death_date":"1985-08-15","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Screen Writers Guild"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-06-09","sentence":"1 year federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Edward Dmytryk","first_name":"Edward","last_name":"Dmytryk","description":"Edward Dmytryk was a film director (Murder, My Sweet; Crossfire; The Caine Mutiny) and one of the Hollywood Ten. Cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served six months at the federal prison camp in Mill Point, West Virginia beginning June 1950 alongside Albert Maltz. Unlike the other nine, Dmytryk reversed his position after his release: in April 1951 he gave a second appearance before HUAC in which he named twenty-six Communists and former Communists in the film industry. His decision broke the unity of the Hollywood Ten and made him a deeply divisive figure in Hollywood for the rest of his life. He resumed his directorial career and continued working through the 1980s.","state":"California","race":"White","gender":"Male","birthdate":"1908-09-04","death_date":"1999-07-01","ideologies":["Communism (former)","First Amendment"],"affiliation":["Hollywood Ten"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Mill Point","institution_city":"Mill Point","institution_state":"West Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1950-12-09","sentence":"6 months federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Adrian Scott","first_name":"Adrian","last_name":"Scott","description":"Adrian Scott was a film producer (Murder, My Sweet; Crossfire) and one of the Hollywood Ten. Cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership, he served one year at the federal prison camp in Ashland, Kentucky beginning June 1950 alongside Dalton Trumbo and John Howard Lawson. He was permanently blacklisted from Hollywood production and spent the rest of his life unable to work openly in his field. Scott was the producing partner of co-Hollywood Ten member Edward Dmytryk; the two had together made the Academy Award-nominated 1947 anti-anti-Semitism drama Crossfire shortly before being subpoenaed.","state":"California","race":"White","gender":"Male","birthdate":"1911-02-06","death_date":"1972-12-25","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Ashland","institution_city":"Ashland","institution_state":"Kentucky","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-06-09","sentence":"1 year federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

php artisan prisoner:add '{"name":"Samuel Ornitz","first_name":"Samuel","last_name":"Ornitz","description":"Samuel Badisch Ornitz was a screenwriter (Hell Ship Morgan, Three Faces West) and a founding member of the Screen Writers Guild. He was the oldest of the Hollywood Ten and was already in poor health when he was cited for contempt of Congress on November 24, 1947 for refusing on First Amendment grounds to answer HUACs questions about Communist Party membership. He served his nine-month sentence at the U.S. Medical Center for Federal Prisoners in Springfield, Missouri beginning June 1950, where he was held in the prison hospital throughout. He died of cancer in 1957 at age 66, never having worked in Hollywood again.","state":"California","race":"White","gender":"Male","birthdate":"1890-11-15","death_date":"1957-03-10","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Hollywood Ten","Screen Writers Guild"],"in_custody":false,"released":true,"cases":[{"institution_name":"U.S. Medical Center for Federal Prisoners","institution_city":"Springfield","institution_state":"Missouri","charges":"Contempt of Congress — refusing on First Amendment grounds to answer HUACs questions about Communist Party membership (Hollywood Ten)","arrest_date":"1947-11-24","incarceration_date":"1950-06-09","release_date":"1951-03-09","sentence":"9 months federal prison; served in the prison hospital due to advanced illness","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, 1948"}]}'

# ============================================================
# Soledad Brothers (acquitted, but held in pretrial)
# ============================================================

php artisan prisoner:add '{"name":"Fleeta Drumgo","first_name":"Fleeta","last_name":"Drumgo","description":"Fleeta Drumgo was a Black prisoner at Soledad Prison in California and one of the three men known as the Soledad Brothers — alongside George Jackson and John Cluchette — who in February 1970 were charged with the murder of Soledad guard John Mills. Mills had been beaten to death and thrown from a tier days after a white guard in the Soledad yard shot and killed three Black prisoners during a fight. There was no physical evidence connecting any of the three men to the killing. The case became an international cause and the focus of the Soledad Brothers Defense Committee, with Angela Davis as one of its central organizers. After George Jackson was killed by guards at San Quentin on August 21, 1971, three days before the trial was set to begin, Drumgo and Cluchette were tried together. On March 27, 1972, the jury acquitted both men of all charges. Drumgo was released and continued political organizing in Oakland. He was killed in an unrelated 1979 shooting at age 33.","state":"California","race":"Black","gender":"Male","birthdate":"1945-12-27","death_date":"1979-06-27","ideologies":["Black Liberation"],"affiliation":["Soledad Brothers"],"in_custody":false,"released":true,"cases":[{"institution_name":"San Quentin State Prison","institution_state":"California","charges":"Murder of Soledad guard John Mills (Soledad Brothers prosecution)","arrest_date":"1970-02-16","incarceration_date":"1970-02-16","release_date":"1972-03-27","sentence":"Acquitted by jury after more than two years held in pretrial custody at San Quentin","convicted":"No — acquitted by California state jury on March 27, 1972"}]}'

php artisan prisoner:add '{"name":"John Cluchette","first_name":"John","last_name":"Cluchette","description":"John Cluchette was a Black prisoner at Soledad Prison in California and one of the three Soledad Brothers — alongside George Jackson and Fleeta Drumgo — charged in February 1970 with the murder of Soledad guard John Mills. The charge was based on no physical evidence; the case was widely understood as retaliation against politically active Black prisoners. The Soledad Brothers Defense Committee, with Angela Davis as one of its central organizers, made the case an international cause. After George Jackson was killed by guards at San Quentin on August 21, 1971, three days before the trial was set to begin, Cluchette and Drumgo were tried together. On March 27, 1972, the jury acquitted both men of all charges. Cluchette completed an unrelated earlier sentence and was released in the late 1970s.","state":"California","race":"Black","gender":"Male","birthdate":"1944-04-26","ideologies":["Black Liberation"],"affiliation":["Soledad Brothers"],"in_custody":false,"released":true,"cases":[{"institution_name":"San Quentin State Prison","institution_state":"California","charges":"Murder of Soledad guard John Mills (Soledad Brothers prosecution)","arrest_date":"1970-02-16","incarceration_date":"1970-02-16","release_date":"1972-03-27","sentence":"Acquitted by jury after more than two years held in pretrial custody at San Quentin","convicted":"No — acquitted by California state jury on March 27, 1972"}]}'

# ============================================================
# Reproductive rights / Cold War
# ============================================================

php artisan prisoner:add '{"name":"Margaret Sanger","first_name":"Margaret","last_name":"Sanger","description":"Margaret Higgins Sanger was an American nurse, sex educator, and birth control activist who founded the first birth control clinic in the United States. On October 16, 1916, she opened the clinic in a storefront at 46 Amboy Street in the Brownsville neighborhood of Brooklyn, New York. Within ten days, undercover police arrested Sanger, her sister Ethel Byrne, and clinic worker Fania Mindell for distributing contraceptives and contraceptive information in violation of New Yorks Comstock-era anti-obscenity statutes. Sanger was tried in early 1917 and sentenced to 30 days in the Queens County Penitentiary, which she served. The arrests catalyzed national press coverage and a sustained legal campaign that gradually weakened state-level Comstock restrictions. Sanger went on to found what became the Planned Parenthood Federation of America. Her broader record included support for eugenics policies common in the Progressive Era — a serious and well-documented part of her history that the modern Planned Parenthood organization has formally repudiated.","state":"New York","race":"White","gender":"Female","birthdate":"1879-09-14","death_date":"1966-09-06","ideologies":["Reproductive rights","Feminism"],"affiliation":["American Birth Control League","Planned Parenthood"],"in_custody":false,"released":true,"cases":[{"institution_name":"Queens County Penitentiary","institution_state":"New York","charges":"Distributing contraceptives and contraceptive information in violation of New York anti-obscenity statutes (Comstock-era law)","arrest_date":"1916-10-26","incarceration_date":"1917-02-05","release_date":"1917-03-06","sentence":"30 days at the Queens County Penitentiary","convicted":"Yes — New York state court, 1917"}]}'

# ============================================================
# Cold War espionage / national security overreach
# ============================================================

php artisan prisoner:add '{"name":"Wen Ho Lee","first_name":"Wen Ho","last_name":"Lee","description":"Wen Ho Lee is a Taiwanese-American nuclear scientist who worked at Los Alamos National Laboratory in New Mexico for two decades and became the central figure in one of the most discredited espionage prosecutions in U.S. history. In December 1999, after a year of leaks portraying him as a Chinese spy who had stolen the United States most sensitive nuclear weapons design data, he was indicted on 59 felony counts. He was held in solitary confinement at the Santa Fe County Detention Center for nine months — most of it shackled when out of his cell, including for family visits — without bond and without ever being charged with espionage.\n\nThe governments case collapsed in the summer of 2000. On September 13, 2000, Lee pleaded guilty to a single felony count of mishandling classified information and was released for time served. The other 58 counts were dropped. Federal District Judge James A. Parker took the extraordinary step of issuing an apology from the bench, telling Lee that the government had embarrassed our entire nation and led me into ordering your detention last December. Lee later won a $1.65 million settlement from the federal government and several news organizations whose reporting had been driven by anonymous leaks from prosecutors.","state":"New Mexico","race":"Asian","gender":"Male","birthdate":"1939-12-21","ideologies":["Targeted by national security prosecution"],"in_custody":false,"released":true,"cases":[{"institution_name":"Santa Fe County Detention Center","institution_city":"Santa Fe","institution_state":"New Mexico","charges":"Originally 59 felony counts under the Atomic Energy Act and related statutes; ultimately pleaded guilty to one count of mishandling classified information (18 U.S.C. § 798)","arrest_date":"1999-12-10","incarceration_date":"1999-12-10","release_date":"2000-09-13","sentence":"Time served (approximately 9 months in solitary confinement); the other 58 counts dropped","convicted":"Pleaded guilty to one count; federal judge James A. Parker apologized from the bench for the governments conduct"}]}'

echo
echo "All 17 prisoner adds complete."
