<?php

declare(strict_types=1);

/**
 * Bulk-add Wilson-era political prisoners (1913-1921):
 *
 *   1. Espionage Act / Sedition Act Socialist defendants (12)
 *   2. IWW Chicago 101 + Sacramento 46 named figures (8)
 *   3. Wilson-era anarchists & Soviet Ark deportees (8)
 *   4. WWI Conscientious Objectors (Hofer brothers, Baldwin, Salmon,
 *      Watchtower 8 / "Rutherford 8", Evan Thomas, Howard Moore,
 *      Harold Gray, Philip Grosser, Erling Lunde) (~17)
 *   5. Houston Riot 1917 court-martialed soldiers (17)
 *   6. Silent Sentinels suffragists (12 + Inez Milholland memorial)
 *   7. Mooney-Billings Preparedness Day Bombing (2)
 *   8. Whitney/Gitlow criminal-syndicalism cases (2)
 *   9. Black militants & editors (Garvey, Randolph, Harrison, Briggs)
 *  10. East St. Louis (Bundy), Margaret Sanger, Viereck
 *
 * Bulk: ~85 prisoners.
 *
 * Idempotent. Run on production:
 *   cd /var/www/NPPC-Website && php scripts/add_wilson_era_prisoners.php
 */

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Institution;
use App\Models\Prisoner;
use App\Models\PrisonerCase;

function addP(array $p): array {
    $existing = Prisoner::where('name', $p['name'])->first();
    if ($existing) return [$existing, false];
    $prisoner = Prisoner::create(array_filter([
        'name' => $p['name'], 'first_name' => $p['first_name'] ?? null, 'middle_name' => $p['middle_name'] ?? null,
        'last_name' => $p['last_name'] ?? null, 'aka' => $p['aka'] ?? null,
        'gender' => $p['gender'] ?? null, 'race' => $p['race'] ?? null, 'state' => $p['state'] ?? null,
        'birthdate' => $p['birthdate'] ?? null, 'death_date' => $p['death_date'] ?? null,
        'description' => $p['description'] ?? null,
        'era' => $p['era'] ?? '1910s', 'ideologies' => $p['ideologies'] ?? null,
        'affiliation' => $p['affiliation'] ?? null,
        'in_custody' => $p['in_custody'] ?? false, 'released' => $p['released'] ?? true,
    ], fn ($v) => $v !== null));
    return [$prisoner, true];
}

function attachC(Prisoner $prisoner, array $c): bool {
    if (! empty($c['arrest_date'])) {
        $exists = $prisoner->cases()->where('arrest_date', $c['arrest_date'])->first();
        if ($exists) return false;
    }
    $institution = Institution::firstOrCreate(
        ['name' => $c['institution']['name']],
        ['city' => $c['institution']['city'] ?? null, 'state' => $c['institution']['state'] ?? null]
    );
    PrisonerCase::create([
        'prisoner_id' => $prisoner->id, 'institution_id' => $institution->id,
        'charges' => $c['charges'] ?? null,
        'arrest_date' => $c['arrest_date'] ?? null, 'incarceration_date' => $c['incarceration_date'] ?? null,
        'release_date' => $c['release_date'] ?? null, 'death_in_custody_date' => $c['death_in_custody_date'] ?? null,
        'sentenced_date' => $c['sentenced_date'] ?? null, 'convicted' => $c['convicted'] ?? null,
        'sentence' => $c['sentence'] ?? null, 'prosecutor' => $c['prosecutor'] ?? null,
        'judge' => $c['judge'] ?? null,
    ]);
    return true;
}

$tot = ['created' => 0, 'existed' => 0, 'cases' => 0];

$people = [
    // ===== 1. Socialist Party defendants =====
    ['name' => 'Eugene Victor Debs', 'first_name' => 'Eugene', 'middle_name' => 'Victor', 'last_name' => 'Debs', 'aka' => 'Gene Debs', 'gender' => 'Male', 'race' => 'White', 'state' => 'Indiana', 'birthdate' => '1855-11-05', 'death_date' => '1926-10-20', 'description' => 'The foremost American socialist of his era — locomotive fireman, founder of the American Railway Union (1893), leader of the 1894 Pullman Strike, IWW co-founder (1905), five-time Socialist presidential candidate. On June 16, 1918 he delivered an anti-war speech in Canton, Ohio condemning U.S. involvement in WWI; convicted under the Espionage Act on Sept 12, 1918 and sentenced to 10 years. Served at Moundsville (WV) and Atlanta Federal Penitentiary, where in 1920 he received nearly 920,000 votes for president as "Convict No. 9653." Harding commuted his sentence to time served on Dec 23, 1921; he walked out of Atlanta on Christmas Day. Died Oct 20, 1926 of cardiovascular disease aggravated by imprisonment.', 'affiliation' => ['Socialist Party of America', 'American Railway Union', 'Industrial Workers of the World (founder)'], 'cases' => [['institution' => ['name' => 'Atlanta Federal Penitentiary', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-06-30', 'sentenced_date' => '1918-09-14', 'release_date' => '1921-12-25', 'sentence' => '10 years federal prison', 'convicted' => 'Yes — Sept 14, 1918', 'judge' => 'Hon. David C. Westenhaver', 'prosecutor' => 'Edwin S. Wertz (U.S. Attorney, N.D. Ohio)', 'charges' => '10 counts under Espionage Act of 1917 §3 (as amended by Sedition Act of 1918): obstructing recruitment, attempting to cause insubordination, uttering disloyal language. Affirmed Debs v. United States, 249 U.S. 211 (1919, Holmes, J.).']]],
    ['name' => 'Charles T. Schenck', 'first_name' => 'Charles', 'last_name' => 'Schenck', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1877-01-01', 'death_date' => '1964-12-15', 'description' => 'General Secretary of the Socialist Party of Philadelphia. In August 1917 the local printed ~15,000 antidraft leaflets ("Long Live the Constitution... Wake Up, America!") urging draftees to assert their Thirteenth Amendment rights. Arrested in a raid on the SP Philadelphia office, convicted in late 1917. His unanimous SCOTUS appeal produced Schenck v. United States, 249 U.S. 47 (1919) — Justice Holmes\'s landmark "clear and present danger" / "fire in a crowded theatre" dictum. Served six months in federal prison.', 'affiliation' => ['Socialist Party of America (Philadelphia)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Eastern District of Pennsylvania', 'city' => 'Philadelphia', 'state' => 'Pennsylvania'], 'arrest_date' => '1917-08-15', 'sentenced_date' => '1918-01-15', 'release_date' => '1919-07-15', 'sentence' => '6 months federal prison', 'convicted' => 'Yes', 'charges' => 'Conspiracy to violate Espionage Act §3 — obstructing recruitment via mailed antidraft leaflets. Affirmed Schenck v. United States, 249 U.S. 47 (1919).']]],
    ['name' => 'Kate Richards O\'Hare', 'first_name' => 'Kate', 'middle_name' => 'Richards', 'last_name' => 'O\'Hare', 'aka' => 'Carrie Katherine Richards', 'gender' => 'Female', 'race' => 'White', 'state' => 'Missouri', 'birthdate' => '1876-03-26', 'death_date' => '1948-01-10', 'description' => 'Leading Socialist Party orator, journalist (National Rip-Saw, St. Louis), and prison-reform advocate, born in Ottawa County, Kansas. On July 17, 1917 she delivered her standard anti-war stump speech in Bowman, North Dakota; federal agents alleged she said women who gave their sons to the war were "brood sows." Convicted Dec 14, 1917 by Judge Martin J. Wade, who imposed an unusually harsh five-year sentence. Entered the Missouri State Penitentiary at Jefferson City April 15, 1919. Wilson commuted her sentence May 29, 1920 after ~14 months; her experience made her a national prison-reform leader.', 'affiliation' => ['Socialist Party of America'], 'cases' => [['institution' => ['name' => 'Missouri State Penitentiary, Jefferson City', 'city' => 'Jefferson City', 'state' => 'Missouri'], 'arrest_date' => '1917-07-17', 'sentenced_date' => '1917-12-14', 'release_date' => '1920-05-29', 'sentence' => '5 years federal prison; commuted by Wilson after ~14 months served', 'convicted' => 'Yes', 'judge' => 'Hon. Martin J. Wade', 'prosecutor' => 'Melvin A. Hildreth (U.S. Attorney, D.N.D.)', 'charges' => 'Espionage Act of 1917 §3 — uttering disloyal/seditious language and attempting to cause insubordination.']]],
    ['name' => 'Rose Pastor Stokes', 'first_name' => 'Rose', 'middle_name' => 'Pastor', 'last_name' => 'Stokes', 'aka' => 'Rose Wieslander', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1879-07-18', 'death_date' => '1933-06-20', 'description' => 'Born to an Orthodox Jewish family in Augustów, Russian Empire; rolled cigars in Cleveland from age eleven before her 1905 "Cinderella" marriage to millionaire socialist J.G. Phelps Stokes drew national attention. Wrote a March 1918 letter to the Kansas City Star — "No government which is for the profiteers can also be for the people" — and was indicted on three counts under the Espionage Act, convicted June 1, 1918 and sentenced to 10 years. Free on $10,000 bond pending appeal; conviction reversed by Eighth Circuit on March 9, 1920; indictment dismissed November 1921. Co-founded CPUSA in 1919.', 'affiliation' => ['Socialist Party of America', 'Communist Party USA (founding member)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Western District of Missouri', 'city' => 'Kansas City', 'state' => 'Missouri'], 'arrest_date' => '1918-03-20', 'sentenced_date' => '1918-06-01', 'release_date' => '1920-03-09', 'sentence' => '10 years federal prison (free on bond throughout; conviction reversed)', 'convicted' => 'Yes; reversed by 8th Circuit (March 9, 1920); indictment dismissed Nov 1921', 'judge' => 'Hon. Arba S. Van Valkenburgh', 'prosecutor' => 'Francis M. Wilson (U.S. Attorney, W.D. Mo.)', 'charges' => 'Three counts under Espionage Act of 1917 §3 — Kansas City Star letter alleging interference with recruitment.']]],
    ['name' => 'Charles Emil Ruthenberg', 'first_name' => 'Charles', 'middle_name' => 'Emil', 'last_name' => 'Ruthenberg', 'aka' => 'C.E. Ruthenberg', 'gender' => 'Male', 'race' => 'White', 'state' => 'Ohio', 'birthdate' => '1882-07-09', 'death_date' => '1927-03-01', 'description' => 'Born to Prussian Lutheran immigrants in Cleveland; joined the SP in 1909 and edited the Cleveland Socialist. After the U.S. entered WWI he organized antiwar rallies; on May 17, 1917 he gave a Cleveland speech for which he, Alfred Wagenknecht, and Charles Baker were arrested for obstructing the draft — the first such Espionage Act convictions in the United States. Sentenced to one year, served roughly 10 months at the Stark County Workhouse in Canton, Ohio. Re-arrested repeatedly through the 1920s; founded the Communist Party USA in Chicago in September 1919 and became its first National Secretary. Died March 1, 1927; ashes interred in the Kremlin Wall Necropolis.', 'affiliation' => ['Socialist Party of America', 'Communist Party USA (founder)'], 'cases' => [['institution' => ['name' => 'Stark County Workhouse', 'city' => 'Canton', 'state' => 'Ohio'], 'arrest_date' => '1917-05-28', 'sentenced_date' => '1917-07-15', 'release_date' => '1918-04-01', 'sentence' => '1 year (~10 months served)', 'convicted' => 'Yes', 'judge' => 'Hon. John M. Killits', 'charges' => 'Espionage Act of 1917 §3 — obstructing the draft.']]],
    ['name' => 'Victor Luitpold Berger', 'first_name' => 'Victor', 'middle_name' => 'Luitpold', 'last_name' => 'Berger', 'gender' => 'Male', 'race' => 'White', 'state' => 'Wisconsin', 'birthdate' => '1860-02-28', 'death_date' => '1929-08-07', 'description' => 'Born in Nieder-Rehbach, Austria-Hungary; emigrated 1878. Edited the Milwaukee Leader (1911–29) and built the "Sewer Socialist" machine that made him in 1910 the first Socialist elected to the U.S. House. Indicted Feb 2, 1918 in the Chicago "Trial of Five" before Judge Kenesaw Mountain Landis; convicted Jan 8, 1919 and sentenced to 20 years. The House twice refused to seat him (1919, 1920). SCOTUS reversed in Berger v. United States, 255 U.S. 22 (1921), holding Landis should have recused. Re-elected 1922; served three more terms (1923–29). Died Aug 7, 1929 of streetcar-accident injuries.', 'affiliation' => ['Socialist Party of America (founding member)', 'U.S. House of Representatives (D-Soc., WI-5)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago Trial of Five', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1918-03-09', 'sentenced_date' => '1919-02-20', 'release_date' => '1921-01-31', 'sentence' => '20 years (free on bond; conviction reversed 1921)', 'convicted' => 'Yes (Jan 8, 1919); reversed by SCOTUS Jan 31, 1921', 'judge' => 'Hon. Kenesaw Mountain Landis', 'prosecutor' => 'Charles F. Clyne (U.S. Attorney, N.D. Ill.)', 'charges' => 'Conspiracy to violate Espionage Act §§3, 4. Conviction vacated by Berger v. United States, 255 U.S. 22 (1921).']]],
    ['name' => 'Adolph Frank Germer', 'first_name' => 'Adolph', 'middle_name' => 'Frank', 'last_name' => 'Germer', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1881-01-15', 'death_date' => '1966-05-26', 'description' => 'Born in Welan, East Prussia; emigrated 1888 and entered Illinois coal mines at age eleven. As National Executive Secretary of the Socialist Party (1916–1919) he was the chief enforcer of the party\'s St. Louis antiwar platform. Co-defendant in the Chicago Trial of Five before Judge Landis; convicted Jan 8, 1919 and sentenced to 20 years. Conviction vacated by Berger v. United States (Jan 31, 1921). Later led the SP "loyalist" faction, broke with the SP in 1923, and in 1935 became John L. Lewis\'s first CIO field representative.', 'affiliation' => ['Socialist Party of America (National Executive Secretary 1916–1919)', 'CIO (later)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago Trial of Five', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1918-03-09', 'sentenced_date' => '1919-02-20', 'release_date' => '1921-01-31', 'sentence' => '20 years (free on bond; conviction reversed)', 'convicted' => 'Yes; reversed by SCOTUS', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act §§3, 4.']]],
    ['name' => 'J. Louis Engdahl', 'first_name' => 'John', 'middle_name' => 'Louis', 'last_name' => 'Engdahl', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1884-11-11', 'death_date' => '1932-11-21', 'description' => 'Born in Minneapolis to Swedish immigrant parents. From 1914 edited the SP\'s national weekly The American Socialist (Chicago) — suppressed by postal authorities in 1917 — and successor The Eye Opener. Youngest of the Chicago Trial of Five defendants. Joined the Communist movement in 1921, becoming first editor of the Daily Worker, and as ILD general secretary led the Scottsboro Boys campaign. Died in Moscow Nov 21, 1932; buried at the Kremlin Wall.', 'affiliation' => ['Socialist Party of America', 'Communist Party USA', 'International Labor Defense'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago Trial of Five', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1918-03-09', 'sentenced_date' => '1919-02-20', 'release_date' => '1921-01-31', 'sentence' => '20 years (free on bond; conviction reversed)', 'convicted' => 'Yes; reversed by SCOTUS', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act §§3, 4.']]],
    ['name' => 'Irwin St. John Tucker', 'first_name' => 'Irwin', 'middle_name' => 'St. John', 'last_name' => 'Tucker', 'aka' => 'Friar Tuck', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1886-01-10', 'death_date' => '1982-01-08', 'description' => 'Born in Mobile, Alabama; Episcopal priest (ordained 1913, General Theological Seminary), Socialist Party member from 1912. Director of the SP National Office Literature Department in summer 1917, where he authored the antiwar pamphlet "The Price We Pay." Co-defendant in the Chicago Trial of Five. Conviction vacated by Berger v. US (1921). Served as priest-in-charge of St. Stephen\'s, Chicago (1927–1954); reinstated as Episcopal priest in 1970 at age 84.', 'affiliation' => ['Socialist Party of America', 'Episcopal Church'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago Trial of Five', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1918-03-09', 'sentenced_date' => '1919-02-20', 'release_date' => '1921-01-31', 'sentence' => '20 years (free on bond; conviction reversed)', 'convicted' => 'Yes; reversed by SCOTUS', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act §§3, 4 — pamphlet "The Price We Pay".']]],
    ['name' => 'William F. Kruse', 'first_name' => 'William', 'middle_name' => 'F.', 'last_name' => 'Kruse', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1894-01-01', 'death_date' => '1979-12-15', 'description' => 'Appointed at age 21 by the SP National Executive Committee in July 1915 to direct the Young People\'s Socialist League; held that post through June 1918 and edited Young Socialists\' Magazine. Youngest defendant in the Chicago Trial of Five; conviction vacated by Berger v. US (1921). Later worked in labor and film distribution (Amkino, importing Soviet films) and Communist Party-aligned organizations.', 'affiliation' => ['Socialist Party of America', 'Young People\'s Socialist League (National Director 1915–1918)'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago Trial of Five', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1918-03-09', 'sentenced_date' => '1919-02-20', 'release_date' => '1921-01-31', 'sentence' => '20 years (free on bond; conviction reversed)', 'convicted' => 'Yes; reversed by SCOTUS', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act §§3, 4.']]],

    // ===== 2. IWW Chicago 101 =====
    ['name' => 'William Dudley Haywood', 'first_name' => 'William', 'middle_name' => 'Dudley', 'last_name' => 'Haywood', 'aka' => 'Big Bill Haywood', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1869-02-04', 'death_date' => '1928-05-18', 'description' => 'Co-founder and General Secretary-Treasurer of the IWW (Wobblies). One-eyed former Western miner; led the Western Federation of Miners and was acquitted in the 1907 Steunenberg murder trial defended by Clarence Darrow. As lead defendant in the 1918 Chicago trial of 101 IWW members before Judge Landis, convicted under the Espionage Act and sentenced to 20 years. While free on bail pending appeal, jumped bail in 1921, fled to Soviet Russia, and died in Moscow in 1928; ashes divided between the Kremlin Wall and Chicago\'s Haymarket Martyrs Monument.', 'affiliation' => ['Industrial Workers of the World (General Secretary-Treasurer)', 'Western Federation of Miners'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Leavenworth — Chicago IWW 101 trial', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1917-09-05', 'sentenced_date' => '1918-08-30', 'sentence' => '20 years federal prison + $20,000 fine (jumped bail to USSR 1921)', 'convicted' => 'Yes — Aug 30, 1918', 'judge' => 'Hon. Kenesaw Mountain Landis', 'prosecutor' => 'Frank K. Nebeker (special prosecutor); Charles F. Clyne', 'charges' => 'Conspiracy to violate Espionage Act of 1917 — conspiring to hinder the draft, encourage desertion, and obstruct the war effort. United States v. Haywood et al., N.D. Ill., the largest political trial in U.S. history at the time (101 defendants).', 'release_date' => '1921-04-01']]],
    ['name' => 'Vincent Saint John', 'first_name' => 'Vincent', 'last_name' => 'Saint John', 'aka' => 'The Saint', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1876-07-16', 'death_date' => '1929-06-01', 'description' => 'IWW General Secretary-Treasurer 1908–1914; widely credited with shaping the union into a fighting industrial organization. Former metal miner and WFM organizer; crippled by gunshot wounds during the 1907 Goldfield, Nevada strike. Although retired from IWW office by 1915, swept up in the blanket 1917 federal indictment and convicted in the 1918 Chicago trial. Sentenced to 10 years; imprisoned at Leavenworth until commuted by President Harding in 1923.', 'affiliation' => ['Industrial Workers of the World (former General Secretary)'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Leavenworth — Chicago IWW 101 trial', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1917-09-28', 'sentenced_date' => '1918-08-30', 'release_date' => '1923-12-15', 'sentence' => '10 years federal prison; commuted by Harding 1923', 'convicted' => 'Yes', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act of 1917.']]],
    ['name' => 'Ralph Hosea Chaplin', 'first_name' => 'Ralph', 'middle_name' => 'Hosea', 'last_name' => 'Chaplin', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1887-08-30', 'death_date' => '1961-03-23', 'description' => 'IWW\'s leading songwriter, poet, and propagandist; wrote "Solidarity Forever" on January 17, 1915, set to "John Brown\'s Body." Joined IWW 1913; in 1916 became editor of the union\'s eastern paper Solidarity. Convicted in the 1918 Chicago mass trial; sentenced to 20 years and a $30,000 fine. Served roughly four years at Leavenworth before Harding\'s December 1923 amnesty. Chronicled prison years in "Bars and Shadows" (1922) and autobiography "Wobbly" (1948).', 'affiliation' => ['Industrial Workers of the World'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Leavenworth — Chicago IWW 101 trial', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1917-09-28', 'sentenced_date' => '1918-08-30', 'release_date' => '1923-06-15', 'sentence' => '20 years federal prison + $30,000 fine; commuted by Harding 1923', 'convicted' => 'Yes', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act of 1917.']]],
    ['name' => 'Walter T. Nef', 'first_name' => 'Walter', 'middle_name' => 'T.', 'last_name' => 'Nef', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1882-01-01', 'description' => 'Swiss-immigrant IWW organizer who in 1915 founded the Agricultural Workers Organization (AWO 400), the IWW\'s most successful affiliate, which organized harvest hands across the wheat belt. Later led Marine Transport Workers Local 8 in Philadelphia. Convicted in the 1918 Chicago trial; sentenced to 20 years at Leavenworth. Released by Harding\'s 1923 amnesty.', 'affiliation' => ['Industrial Workers of the World', 'Agricultural Workers Organization (founder)'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Leavenworth — Chicago IWW 101 trial', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1917-09-28', 'sentenced_date' => '1918-08-30', 'release_date' => '1923-12-15', 'sentence' => '20 years federal prison; commuted by Harding 1923', 'convicted' => 'Yes', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Conspiracy to violate Espionage Act of 1917.']]],
    ['name' => 'Charles Ashleigh', 'first_name' => 'Charles', 'last_name' => 'Ashleigh', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1888-11-25', 'death_date' => '1974-12-25', 'description' => 'English-born IWW poet, journalist, and orator who delivered the eulogy at the 1916 funeral of the Everett Massacre martyrs and authored the poem "Everett, November Fifth." Convicted in the 1918 Chicago IWW trial; sentenced to 10 years at Leavenworth. Released in the December 1921 amnesty; deported to Britain in April 1922. Attended the Fourth Comintern Congress; remained a lifelong activist with the Communist Party of Great Britain.', 'affiliation' => ['Industrial Workers of the World', 'Communist Party of Great Britain (later)'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Leavenworth — Chicago IWW 101 trial', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1917-09-28', 'sentenced_date' => '1918-09-07', 'release_date' => '1921-12-15', 'sentence' => '10 years federal prison; commuted; deported to UK April 1922', 'convicted' => 'Yes', 'judge' => 'Hon. Kenesaw Mountain Landis', 'charges' => 'Seditious conspiracy; conspiracy to obstruct military service.']]],
    ['name' => 'Theodora Pollok', 'first_name' => 'Theodora', 'last_name' => 'Pollok', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'description' => 'Social worker and the only woman among the "Sacramento 46" IWW defendants tried in early 1919 in the Northern District of California. The defendants had been arrested in late 1917 in the wake of the December 17, 1917 bombing of the California governor\'s mansion (which they were not charged with). 46 convicted of Espionage Act conspiracy after a one-hour jury deliberation. Pollok received a suspended sentence.', 'affiliation' => ['Industrial Workers of the World', 'Social workers'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of California — Sacramento 46', 'city' => 'Sacramento', 'state' => 'California'], 'arrest_date' => '1917-12-15', 'sentenced_date' => '1919-01-15', 'sentence' => 'Suspended sentence', 'convicted' => 'Yes', 'charges' => 'Conspiracy to violate Espionage Act of 1917 — Sacramento 46 trial.']]],

    // ===== 3. Anarchists & Soviet Ark =====
    ['name' => 'Emma Goldman', 'first_name' => 'Emma', 'last_name' => 'Goldman', 'aka' => 'Red Emma', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1869-06-27', 'death_date' => '1940-05-14', 'description' => 'The most prominent anarchist in Wilson-era America: fiery orator, editor of Mother Earth (1906–1917), tireless advocate for free speech, birth control, women\'s emancipation, and labor militancy. Born to Orthodox Jewish family in Kaunas, Lithuania; emigrated 1885; radicalized by 1887 Haymarket executions. With Alexander Berkman co-founded the No-Conscription League in May 1917; arrested June 15, 1917; convicted by Judge Julius M. Mayer; sentenced to 2 years federal prison and $10,000 fines. Served at Missouri State Penitentiary in Jefferson City. Stripped of derivative citizenship and deported on the USAT Buford ("Soviet Ark") to Soviet Russia on December 21, 1919. Broke with Bolshevism after Kronstadt (1921); died in Toronto 1940.', 'affiliation' => ['No-Conscription League', 'Mother Earth (publisher)', 'Anarchist movement'], 'cases' => [['institution' => ['name' => 'Missouri State Penitentiary, Jefferson City', 'city' => 'Jefferson City', 'state' => 'Missouri'], 'arrest_date' => '1917-06-15', 'sentenced_date' => '1917-07-09', 'release_date' => '1919-09-27', 'sentence' => '2 years federal prison + $10,000 fine; deported on Soviet Ark Dec 21, 1919', 'convicted' => 'Yes', 'judge' => 'Hon. Julius Marshuetz Mayer', 'charges' => 'Conspiracy to obstruct the draft (Selective Service Act of 1917 / Espionage Act of 1917).']]],
    ['name' => 'Alexander Berkman', 'first_name' => 'Alexander', 'last_name' => 'Berkman', 'aka' => 'Sasha; Ovsei Osipovich Berkman', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1870-11-21', 'death_date' => '1936-06-28', 'description' => 'Emma Goldman\'s lifelong comrade and one of the foremost American anarchists. Born to wealthy Lithuanian-Jewish family; immigrated ~1887. In 1892 carried out a propaganda-of-the-deed attentat against Henry Clay Frick during the Homestead steel strike, serving 14 years in Pennsylvania\'s Western Penitentiary. With Goldman co-founded the No-Conscription League in 1917; convicted with her under Judge Mayer; served two years at Atlanta, including seven months in solitary for protesting beatings. Released Oct 1, 1919; deported on USAT Buford Dec 21, 1919. Wrote "The Bolshevik Myth" (1925); committed suicide in Nice 1936.', 'affiliation' => ['No-Conscription League', 'Mother Earth', 'The Blast (editor)'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1917-06-15', 'sentenced_date' => '1917-07-09', 'release_date' => '1919-10-01', 'sentence' => '2 years federal prison + $10,000 fine; deported on Soviet Ark Dec 21, 1919', 'convicted' => 'Yes', 'judge' => 'Hon. Julius Marshuetz Mayer', 'charges' => 'Conspiracy to obstruct the draft.']]],
    ['name' => 'Jacob Abrams', 'first_name' => 'Jacob', 'last_name' => 'Abrams', 'aka' => 'Jack Abrams', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1886-01-01', 'death_date' => '1953-12-15', 'description' => 'Russian-Jewish anarchist bookbinder and lead defendant in the landmark First Amendment case Abrams v. United States, 250 U.S. 616 (1919). On August 22-23, 1918 he and four others were arrested in New York for throwing Yiddish and English leaflets from a Lower East Side rooftop denouncing Wilson\'s deployment of U.S. troops to Soviet Russia. Convicted Oct 23, 1918 under the Sedition Act; sentenced to 20 years and $1,000 fine. SCOTUS upheld 7-2 (famous Holmes/Brandeis "marketplace of ideas" dissent). Served roughly 3 years at Atlanta; deported to Soviet Russia aboard SS Estonia Nov 24, 1921; later left USSR for Mexico, where he died 1953.', 'affiliation' => ['Frayhayt anarchist group'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Abrams trial (S.D.N.Y.)', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-08-23', 'sentenced_date' => '1918-10-25', 'release_date' => '1921-11-24', 'sentence' => '20 years federal prison + $1,000 fine; deported to USSR Nov 24, 1921', 'convicted' => 'Yes; affirmed Abrams v. US 250 U.S. 616 (1919)', 'judge' => 'Hon. Henry DeLamar Clayton Jr.', 'charges' => 'Conspiracy to violate Sedition Act of 1918 (amending Espionage Act of 1917) — 4 counts.']]],
    ['name' => 'Mollie Steimer', 'first_name' => 'Mollie', 'last_name' => 'Steimer', 'aka' => 'Marthe Alperine', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1897-11-21', 'death_date' => '1980-07-23', 'description' => 'Immigrated from Ukraine to New York at age 15 in 1913; worked in a garment factory; joined the Yiddish-anarchist Frayhayt group by 1917. Twenty years old at her arrest; the youngest and only female defendant in Abrams v. United States. Convicted Oct 25, 1918; sentenced to 15 years federal prison plus $500 fine. Refused to flee with her co-defendants out of solidarity with workers who had raised her bond. Deported to Soviet Russia Nov 24, 1921; expelled from USSR 1923 for protesting Bolshevik repression of anarchists. Lived in Berlin and Paris before fleeing to Mexico City in 1942.', 'affiliation' => ['Frayhayt anarchist group'], 'cases' => [['institution' => ['name' => 'Missouri State Penitentiary — Abrams trial (S.D.N.Y.)', 'city' => 'Jefferson City', 'state' => 'Missouri'], 'arrest_date' => '1918-08-23', 'sentenced_date' => '1918-10-25', 'release_date' => '1921-11-24', 'sentence' => '15 years federal prison + $500 fine; deported to USSR Nov 24, 1921; expelled to Germany 1923; later Mexico 1942', 'convicted' => 'Yes; affirmed Abrams v. US 250 U.S. 616 (1919)', 'judge' => 'Hon. Henry DeLamar Clayton Jr.', 'charges' => 'Conspiracy to violate Sedition Act of 1918.']]],
    ['name' => 'Hyman Lachowsky', 'first_name' => 'Hyman', 'last_name' => 'Lachowsky', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1885-01-01', 'death_date' => '1944-06-15', 'description' => 'Russian-Jewish bookbinder and Frayhayt-group anarchist convicted alongside Jacob Abrams. Eyewitnesses testified he was severely beaten by police during interrogation. Convicted Oct 23, 1918 under the Sedition Act; sentenced to 20 years and $1,000 fine. Deported to Soviet Russia Nov 24, 1921 aboard SS Estonia. Returned to his hometown in present-day Belarus; reported to have perished under Nazi occupation during the Holocaust.', 'affiliation' => ['Frayhayt anarchist group'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Abrams trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-08-23', 'sentenced_date' => '1918-10-23', 'release_date' => '1921-11-24', 'sentence' => '20 years federal prison + $1,000 fine; deported Nov 1921', 'convicted' => 'Yes', 'judge' => 'Hon. Henry DeLamar Clayton Jr.', 'charges' => 'Conspiracy to violate Sedition Act of 1918.']]],
    ['name' => 'Samuel Lipman', 'first_name' => 'Samuel', 'last_name' => 'Lipman', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1898-01-01', 'death_date' => '1937-12-15', 'description' => '21 at the time of his arrest; the lone Marxist socialist (rather than anarchist) among the Abrams defendants and a worker in the fur trade. Authored the English-language leaflet — the milder of the two leaflets at issue. Convicted Oct 23, 1918 under the Sedition Act; sentenced to 20 years and $1,000 fine. Deported to Soviet Russia Nov 24, 1921. There became a Communist Party member and economist; arrested in Stalin\'s Great Purge and reportedly executed in 1937.', 'affiliation' => ['Frayhayt group'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Abrams trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-08-23', 'sentenced_date' => '1918-10-23', 'release_date' => '1921-11-24', 'sentence' => '20 years federal prison + $1,000 fine; deported Nov 1921', 'convicted' => 'Yes', 'judge' => 'Hon. Henry DeLamar Clayton Jr.', 'charges' => 'Conspiracy to violate Sedition Act of 1918.']]],
    ['name' => 'Carlo Tresca', 'first_name' => 'Carlo', 'last_name' => 'Tresca', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1879-03-09', 'death_date' => '1943-01-11', 'description' => 'Born in Sulmona, Italy 1879; emigrated to U.S. 1904; became prominent IWW organizer (Lawrence 1912, Paterson 1913, Mesabi Range 1916), longtime editor of anti-fascist Italian-language paper Il Martello, and partner of Elizabeth Gurley Flynn. Repeatedly prosecuted during the Wilson era under the Espionage Act and federal obscenity statutes; faced multiple deportation proceedings he successfully resisted. A relentless opponent of Mussolini, Stalin, and Mafia infiltration of unions; assassinated on a Manhattan street corner Jan 11, 1943.', 'affiliation' => ['Industrial Workers of the World', 'Italian Socialist Federation', 'Il Martello (editor)'], 'cases' => [['institution' => ['name' => 'Federal courts (multiple Wilson-era prosecutions of Carlo Tresca)', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1917-06-15', 'sentence' => 'Multiple Espionage Act prosecutions and deportation proceedings, all successfully resisted.', 'convicted' => 'Multiple charges; not deported', 'charges' => 'Various Espionage Act and federal obscenity prosecutions, deportation proceedings.']]],
    ['name' => 'Luigi Galleani', 'first_name' => 'Luigi', 'last_name' => 'Galleani', 'gender' => 'Male', 'race' => 'White', 'state' => 'Massachusetts', 'birthdate' => '1861-08-12', 'death_date' => '1931-11-04', 'description' => 'Leading insurrectionary anarchist theorist among Italian immigrants in early 20th-century America. From June 6, 1903 edited Cronaca Sovversiva ("Subversive Chronicle") in Barre, Vermont and later Lynn, Massachusetts. His followers, the Galleanisti, carried out the 1919 anarchist bombings and the Wall Street bombing of 1920; Sacco and Vanzetti were Galleanisti. Federal agents shut down Cronaca Sovversiva June 17, 1917. Deported to Italy June 24, 1919 along with eight followers (the "Galleani 9"). In Italy repeatedly imprisoned and exiled under Mussolini until his death 1931.', 'affiliation' => ['Cronaca Sovversiva (editor)', 'Galleanisti'], 'cases' => [['institution' => ['name' => 'Immigration Bureau, Ellis Island — Galleani 9 deportation', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1917-06-17', 'release_date' => '1919-06-24', 'sentence' => 'Deported to Italy June 24, 1919 along with 8 followers (the "Galleani 9")', 'convicted' => 'Deported under Immigration Act of 1918 (Anarchist Exclusion)', 'charges' => 'Espionage Act / Immigration Act anarchist deportation proceedings.']]],

    // ===== 4. WWI Conscientious Objectors =====
    ['name' => 'Joseph J. Hofer', 'first_name' => 'Joseph', 'middle_name' => 'J.', 'last_name' => 'Hofer', 'gender' => 'Male', 'race' => 'White', 'state' => 'South Dakota', 'birthdate' => '1894-10-24', 'death_date' => '1918-11-29', 'released' => false, 'description' => 'Hutterite communal farmer from the Rockport Colony in South Dakota, drafted in May 1918 along with his brothers Michael and David and his brother-in-law Jacob Wipf. Refusing on Anabaptist grounds to don the military uniform, court-martialed and sentenced to 20 years hard labor at Alcatraz. After four months of solitary confinement on bread and water and "high cuffing" chains, transferred to Fort Leavenworth on Nov 19, 1918, and died ten days later. The Hutterite Church regards him as a martyr.', 'affiliation' => ['Hutterite', 'Rockport Colony'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-05-25', 'incarceration_date' => '1918-07-27', 'death_in_custody_date' => '1918-11-29', 'sentence' => '20 years hard labor; died in custody', 'convicted' => 'Yes — court-martialed under Articles of War', 'charges' => 'Court-martialed for refusing to obey orders / refusing to wear military uniform.']]],
    ['name' => 'Michael Hofer', 'first_name' => 'Michael', 'last_name' => 'Hofer', 'gender' => 'Male', 'race' => 'White', 'state' => 'South Dakota', 'birthdate' => '1893-07-13', 'death_date' => '1918-12-02', 'released' => false, 'description' => 'Hutterite communal farmer drafted with his brothers Joseph and David and brother-in-law Jacob Wipf in May 1918. After refusing all forms of military service, sentenced to 20 years and shipped in chains to Alcatraz, where the four men endured solitary confinement, dim cells with rationed water, and chained suspension. Transferred to Fort Leavenworth Nov 19, 1918, died Dec 2 — three days after Joseph — officially of pneumonia, but Hutterite tradition holds it was the result of mistreatment. Buried at Rockport Colony beside his brother.', 'affiliation' => ['Hutterite', 'Rockport Colony'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-05-25', 'incarceration_date' => '1918-07-27', 'death_in_custody_date' => '1918-12-02', 'sentence' => '20 years hard labor; died in custody', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed for refusing to obey orders.']]],
    ['name' => 'David Hofer', 'first_name' => 'David', 'last_name' => 'Hofer', 'gender' => 'Male', 'race' => 'White', 'state' => 'South Dakota', 'birthdate' => '1890-01-01', 'description' => 'Eldest of the four Hutterites drafted from the Rockport Colony in South Dakota in May 1918, was 28 years old when sentenced alongside his younger brothers and brother-in-law to 20 years of hard labor for refusing military duty. Survived Alcatraz and Fort Leavenworth; released shortly after his brothers died in late November/early December 1918, allowed to accompany the bodies home for burial. Joined the migration of Hutterite colonies to Canada to escape American persecution.', 'affiliation' => ['Hutterite', 'Rockport Colony'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-05-25', 'incarceration_date' => '1918-07-27', 'release_date' => '1918-12-15', 'sentence' => '20 years hard labor (released early after brothers\' deaths)', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed for refusing to obey orders.']]],
    ['name' => 'Jacob Wipf', 'first_name' => 'Jacob', 'last_name' => 'Wipf', 'gender' => 'Male', 'race' => 'White', 'state' => 'South Dakota', 'birthdate' => '1888-01-01', 'description' => 'Brother-in-law of Joseph Hofer; 30 years old, married with three children, when drafted from the Rockport Hutterite Colony in South Dakota May 25, 1918. As the eldest of the four-man Hutterite group sent to Alcatraz, bore the brunt of ordering refusals on behalf of the others; after his three companions were transferred to Leavenworth and the Hofer brothers died, he alone remained imprisoned for an additional five months. Released April 13, 1919.', 'affiliation' => ['Hutterite', 'Rockport Colony'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-05-25', 'incarceration_date' => '1918-07-27', 'release_date' => '1919-04-13', 'sentence' => '20 years hard labor (released early)', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed for refusing to obey orders.']]],
    ['name' => 'Roger Nash Baldwin', 'first_name' => 'Roger', 'middle_name' => 'Nash', 'last_name' => 'Baldwin', 'gender' => 'Male', 'race' => 'White', 'state' => 'New Jersey', 'birthdate' => '1884-01-21', 'death_date' => '1981-08-26', 'description' => 'Harvard-educated social worker who, after the U.S. entered WWI, became director of the American Union Against Militarism\'s Civil Liberties Bureau — soon spun off as the National Civil Liberties Bureau, the direct predecessor of the ACLU. Refused induction October 1918, read his celebrated statement "The Individual and the State" in court; sentenced to eleven months in prison, served nine before his release in July 1919. Co-founded ACLU January 1920; led it for three decades; awarded Presidential Medal of Freedom by Carter 1981.', 'affiliation' => ['National Civil Liberties Bureau', 'ACLU (co-founder, 1920)'], 'cases' => [['institution' => ['name' => 'Essex County Jail', 'city' => 'Newark', 'state' => 'New Jersey'], 'arrest_date' => '1918-10-20', 'incarceration_date' => '1918-10-30', 'release_date' => '1919-07-15', 'sentence' => '11 months (served 9)', 'convicted' => 'Yes', 'charges' => 'Violation of the Selective Service Act — refusing induction.']]],
    ['name' => 'Evan Welling Thomas', 'first_name' => 'Evan', 'middle_name' => 'Welling', 'last_name' => 'Thomas', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1890-01-01', 'death_date' => '1974-12-15', 'description' => 'Younger brother of Norman Thomas; Princeton seminary student studying in Edinburgh when the U.S. entered WWI; returned home and refused induction as an absolutist conscientious objector. After leading a hunger strike at Fort Riley, Kansas in August 1918, court-martialed, sentenced to life imprisonment, transferred to Fort Leavenworth, where held in solitary confinement and chained handcuffed to his cell door for 14 days. Sentence commuted; released 1919. Later trained as a physician, chaired the War Resisters League for many years.', 'affiliation' => ['Christian pacifist', 'War Resisters League (later)'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-08-15', 'incarceration_date' => '1918-09-15', 'release_date' => '1919-09-15', 'sentence' => 'Life imprisonment (commuted)', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed under the Articles of War — refusing orders / leading hunger strike.']]],
    ['name' => 'Howard Wilbur Moore', 'first_name' => 'Howard', 'middle_name' => 'Wilbur', 'last_name' => 'Moore', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1889-01-01', 'death_date' => '1993-07-15', 'description' => 'New York farm laborer drafted in 1918 and sent to Camp Upton on April 29; refusing the uniform, was among about fifty-five "absolutists" transferred through Fort Riley and Camp Funston before arriving at Fort Leavenworth Disciplinary Barracks Armistice Day, November 11, 1918. Court-martialed and sentenced to five years\' hard labor; beaten, hung by his thumbs, locked in vermin-infested cells, fed garbage, personally berated by visiting General John J. Pershing. Last absolutist released in late 1920. At age 95 wrote the lyrical memoir "Plowing My Own Furrow" (1985).', 'affiliation' => ['Absolutist conscientious objector'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-04-29', 'incarceration_date' => '1918-11-11', 'release_date' => '1920-12-15', 'sentence' => '5 years hard labor', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed under the Articles of War — refusing orders / refusing the uniform.']]],
    ['name' => 'Harold Studley Gray', 'first_name' => 'Harold', 'middle_name' => 'Studley', 'last_name' => 'Gray', 'gender' => 'Male', 'race' => 'White', 'state' => 'Michigan', 'birthdate' => '1894-01-01', 'death_date' => '1972-12-15', 'description' => 'Son of a wealthy Detroit family, left Harvard in his sophomore year to serve as a YMCA secretary in England, but resigned in 1917 when YMCA was militarized. Court-martialed for disobedience, sentenced to 25 years (later reduced to three), held first at Fort Leavenworth and then at Alcatraz, where he participated in a publicized hunger strike and was force-fed. Sentence remitted Aug 19, 1919 on the basis of "sincere" objection. Prison letters published 1934 as "Character Bad": The Story of a Conscientious Objector.', 'affiliation' => ['Religious Society of Friends (Quaker)', 'YMCA (former)'], 'cases' => [['institution' => ['name' => 'Alcatraz Military Prison', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1918-06-15', 'incarceration_date' => '1918-07-18', 'release_date' => '1919-08-19', 'sentence' => '25 years (reduced to 3; remitted)', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed under the Articles of War — disobedience of orders.']]],
    ['name' => 'Benjamin Joseph Salmon', 'first_name' => 'Benjamin', 'middle_name' => 'Joseph', 'last_name' => 'Salmon', 'aka' => 'Ben Salmon', 'gender' => 'Male', 'race' => 'White', 'state' => 'Colorado', 'birthdate' => '1889-10-15', 'death_date' => '1932-02-15', 'description' => 'Denver-born Catholic clerk and early activist for the Knights of Columbus and Catholic labor causes who, on June 5, 1917, wrote directly to President Wilson refusing to register for the draft on the grounds that all war was incompatible with the teachings of Christ. As one of only a handful of identifiable Catholic absolutists, charged with desertion and "spreading propaganda," sentenced to death (commuted to 25 years hard labor). Spent six months in "the hole" — a windowless 5×9 cell over the prison sewer; endured beatings, force-feeding, and a 135-day hunger strike. Released in Thanksgiving 1920 clemency. His ordeal permanently broke his health; died of pneumonia 1932 at age 43; cause for sainthood opened by Catholic Diocese of Denver in 2017.', 'affiliation' => ['Roman Catholic Church'], 'cases' => [['institution' => ['name' => 'United States Disciplinary Barracks, Fort Leavenworth', 'city' => 'Leavenworth', 'state' => 'Kansas'], 'arrest_date' => '1918-01-15', 'incarceration_date' => '1918-07-15', 'release_date' => '1920-11-26', 'sentence' => 'Death (commuted to 25 years hard labor)', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed under the Articles of War — desertion and spreading propaganda.']]],
    ['name' => 'Philip Grosser', 'first_name' => 'Philip', 'last_name' => 'Grosser', 'gender' => 'Male', 'race' => 'White', 'state' => 'Massachusetts', 'birthdate' => '1890-01-01', 'death_date' => '1933-10-15', 'description' => 'Born in Slavuta, Ukraine 1890; established anarchist activist in Boston by 1917; among the first to refuse the draft on political — rather than religious — grounds. Court-martialed and sent to Alcatraz; refused the uniform, refused to stand in formation, and refused "hard labor"; retaliated against with extended solitary, beatings, being dragged on a rope, denial of toilet facilities, and confinement in Alcatraz\'s "iron maidens" (upright iron cages). After release wrote one of the earliest published exposés of conditions at Alcatraz, the 32-page pamphlet "Alcatraz – Uncle Sam\'s Devil\'s Island" (1933). Took his own life in Boston Oct 1933.', 'affiliation' => ['Anarchist movement (Boston)'], 'cases' => [['institution' => ['name' => 'Alcatraz Military Prison', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1917-08-15', 'incarceration_date' => '1918-01-15', 'release_date' => '1920-12-15', 'sentence' => 'Multi-year hard labor at Alcatraz', 'convicted' => 'Yes — court-martialed', 'charges' => 'Court-martialed under the Articles of War — refusing orders / refusing the uniform.']]],
    ['name' => 'Joseph Franklin Rutherford', 'first_name' => 'Joseph', 'middle_name' => 'Franklin', 'last_name' => 'Rutherford', 'aka' => 'Judge Rutherford', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1869-11-08', 'death_date' => '1942-01-08', 'description' => 'Missouri-born lawyer; successor to Charles Taze Russell as president of the Watch Tower Bible and Tract Society. Lead defendant in the May 1918 federal indictment of eight Watch Tower directors known as the "Rutherford 8" — charged under the Espionage Act of 1917 with attempting to cause insubordination by distributing the millenarian book The Finished Mystery. After trial in EDNY (Brooklyn), jury convicted June 20, 1918; Judge Harland B. Howe imposed 20-year sentences June 21. Defendants entered the U.S. Penitentiary at Atlanta; served roughly nine months, released on bail March 1919 after Justice Brandeis granted relief. Convictions reversed on appeal 1919; charges dropped 1920. Renamed the movement "Jehovah\'s Witnesses" in 1931.', 'affiliation' => ['Watch Tower Society / Jehovah\'s Witnesses (President)'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; conviction reversed on appeal 1919; charges dropped 1920', 'convicted' => 'Yes; reversed on appeal', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917 — conspiring to cause insubordination, disloyalty, and refusal of duty in the armed forces (publication of The Finished Mystery).']]],
    ['name' => 'William E. Van Amburgh', 'first_name' => 'William', 'middle_name' => 'E.', 'last_name' => 'Van Amburgh', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1864-01-01', 'death_date' => '1947-12-15', 'description' => 'Secretary-treasurer of the Watch Tower Bible and Tract Society and one of eight Watch Tower directors indicted May 7, 1918 under the Espionage Act for the publication of The Finished Mystery. Tried alongside Joseph Rutherford in Brooklyn; convicted June 20, 1918; sentenced to 20 years; incarcerated at U.S. Penitentiary Atlanta. Released on bail March 1919 after Justice Brandeis intervened; conviction reversed on appeal 1919.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917 — distribution of The Finished Mystery.']]],
    ['name' => 'Clayton J. Woodworth', 'first_name' => 'Clayton', 'middle_name' => 'J.', 'last_name' => 'Woodworth', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1870-01-01', 'death_date' => '1951-12-15', 'description' => 'Primary co-author of The Finished Mystery (1917). Indicted with Joseph Rutherford and six other Watch Tower leaders May 1918 for the very book he had helped write. Convicted Espionage Act June 20, 1918; received 20-year sentence; sent to federal penitentiary in Atlanta; served nine months before being released on bail March 1919. Founding editor of the Watch Tower magazine The Golden Age (later Awake!) which he edited 1919-1946.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917 — co-authorship and distribution of The Finished Mystery.']]],
    ['name' => 'Frederick H. Robison', 'first_name' => 'Frederick', 'middle_name' => 'H.', 'last_name' => 'Robison', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1879-01-01', 'death_date' => '1932-12-15', 'description' => 'One of the seven Watch Tower directors indicted in May 1918 under the Espionage Act for distributing The Finished Mystery. Convicted in Brooklyn federal court June 20, 1918; sentenced to 20 years; confined at U.S. Penitentiary Atlanta until released on bail March 1919. Convictions reversed on appeal 1919; charges dropped 1920.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917 — distribution of The Finished Mystery.']]],
    ['name' => 'George H. Fisher', 'first_name' => 'George', 'middle_name' => 'H.', 'last_name' => 'Fisher', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1870-01-01', 'death_date' => '1926-12-15', 'description' => 'Co-author with Clayton Woodworth of The Finished Mystery; one of the eight Watch Tower defendants indicted May 1918. Convicted June 20, 1918; sentenced to 20 years; held at U.S. Penitentiary Atlanta until March 1919 bail release; convictions reversed on appeal 1919.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917.']]],
    ['name' => 'Giovanni De Cecca', 'first_name' => 'Giovanni', 'last_name' => 'De Cecca', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'description' => 'Italian-American Bible Student responsible for foreign-language distribution of Watch Tower literature; the eighth defendant in the 1918 Rutherford 8 Espionage Act prosecution. Convicted June 20, 1918; received 10-year sentence — the lightest of the group. Served at U.S. Penitentiary Atlanta until March 1919 bail release; convictions reversed on appeal 1919.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '10 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917 — distribution of The Finished Mystery.']]],
    ['name' => 'Alexander H. Macmillan', 'first_name' => 'Alexander', 'middle_name' => 'H.', 'last_name' => 'Macmillan', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1877-01-01', 'death_date' => '1966-12-15', 'description' => 'Canadian-born senior Watch Tower official; one of eight defendants indicted May 7, 1918 under the Espionage Act. Convicted June 20, 1918; sentenced to 20 years on each of four counts (concurrent); imprisoned at U.S. Penitentiary Atlanta until released on bail March 1919; convictions reversed on appeal 1919. His 1957 memoir "Faith on the March" is a key first-person account of the case.', 'affiliation' => ['Watch Tower Society'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Rutherford 8 Watch Tower trial', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1918-05-08', 'sentenced_date' => '1918-06-21', 'release_date' => '1919-03-26', 'sentence' => '20 years federal prison; reversed on appeal', 'convicted' => 'Yes; reversed', 'judge' => 'Hon. Harland B. Howe', 'charges' => 'Espionage Act of 1917.']]],
];

// Continue people array — Houston Riot soldiers, Silent Sentinels, etc.
$houstonInst = ['name' => 'Fort Sam Houston Disciplinary Barracks — Houston Riot 1917 court-martials', 'city' => 'San Antonio', 'state' => 'Texas'];
$houstonChargesBase = 'Houston Riot of 1917: Aug 23, 1917 march of 24th Infantry Regiment soldiers on Houston after sustained Jim Crow harassment of Cpl. Charles Baltimore by Houston police. Three court-martials at Fort Sam Houston: "Nesbit" (Nov 1, 1917 - 63 tried), "Washington" (Dec 17-22, 1917 - 15 tried), "Tillman" (Feb 18 - Mar 26, 1918 - 40 tried). Total 110 convicted; 19 hanged; 63 sentenced to life at Leavenworth. Convictions formally set aside by U.S. Army November 2023 (posthumous). Trial Judge Advocate: Col. John A. Hull.';

$houstonHanged13 = [
    ['William Cleveland Nesbit', 'Sergeant', '1887-01-01', 'Sgt. William C. Nesbit was a senior NCO of Company I, 3rd Battalion, 24th Infantry, born in Blair County, Pennsylvania. As one of the highest-ranking Black NCOs in the unit, identified by prosecutors as a leader of the August 23, 1917 march on Houston. Tried in the first "Nesbit" court-martial; hanged at sunrise December 11, 1917. Conviction set aside November 2023.'],
    ['Charles W. Baltimore', 'Corporal', null, 'Military policeman whose beating and arrest by Houston police on August 23, 1917 — and the false rumor that police had killed him — was the immediate catalyst for the soldiers\' march. Pistol-whipped and shot at by police when he went to inquire about Pvt. Alonzo Edwards. Hanged at sunrise December 11, 1917.'],
    ['Frank Johnson', 'Private', null, 'Private of the 24th Infantry among the soldiers who took up arms on the night of August 23, 1917. Convicted in the first "Nesbit" court-martial; hanged at sunrise December 11, 1917 at Salado Creek outside Fort Sam Houston, Texas.'],
    ['Thomas Coleman Hawkins', 'Private', null, 'Soldier of the 24th Infantry hanged with twelve others at sunrise on December 11, 1917, at Fort Sam Houston, after conviction in the first court-martial for mutiny and murder.'],
    ['Larnon J. Brown', 'Corporal', null, 'Cpl. of the 24th Infantry among the 13 soldiers convicted on December 1, 1917 and secretly hanged 10 days later at Fort Sam Houston without War Department review.'],
    ['James Wheatley', 'Corporal', null, 'Cpl. James Wheatley was hanged with twelve fellow 24th Infantry soldiers at sunrise on December 11, 1917, after the largest court-martial in U.S. military history convicted him of mutiny and murder.'],
    ['Jesse Ball Moore', 'Corporal', null, 'Cpl. Jesse Ball Moore was a 24th Infantry NCO hanged December 11, 1917 at Fort Sam Houston following conviction in the first Houston court-martial.'],
    ['William Brackenridge', 'Private', null, 'Pvt. William Brackenridge of the 24th Infantry was among the 13 hanged at Salado Creek on December 11, 1917 after the first Houston court-martial. Executions were carried out in secret without notification of the War Department.'],
    ['Carlos Snodgrass', 'Private', null, 'Pvt. Carlos Snodgrass was a 24th Infantry soldier hanged at sunrise on December 11, 1917 at Fort Sam Houston after conviction in the first Houston riot court-martial.'],
    ['Ira B. Davis', 'Private', null, 'Pvt. Ira B. Davis of the 24th Infantry was among the soldiers convicted of mutiny and murder in the largest court-martial in U.S. military history and hanged December 11, 1917.'],
    ['James Divine', 'Private', null, 'Pvt. James Divine was hanged with the 13 soldiers at Salado Creek on December 11, 1917 after secret pre-dawn executions ordered by the Commanding General without the customary appellate review.'],
    ['Risley W. Young', 'Private', null, 'Pvt. Risley W. Young of the 24th Infantry was hanged at sunrise December 11, 1917 at Fort Sam Houston for his alleged role in the August 23 march on Houston.'],
    ['Pat MacWharter', 'Private', null, 'Pvt. Pat MacWharter of the 24th Infantry was the thirteenth soldier hanged on the morning of December 11, 1917 at Salado Creek outside Fort Sam Houston. The executions were carried out so quickly and secretly that newspapers learned of them only after they were complete.'],
];

foreach ($houstonHanged13 as $row) {
    $parts = explode(' ', $row[0]);
    $first = $parts[0];
    $last = end($parts);
    $middle = count($parts) >= 3 ? implode(' ', array_slice($parts, 1, -1)) : null;
    $people[] = [
        'name' => $row[0], 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas',
        'birthdate' => $row[2], 'death_date' => '1917-12-11', 'released' => false,
        'description' => "{$row[1]} of the 24th Infantry Regiment. " . $row[3] . ' Conviction formally set aside by U.S. Army November 2023 (posthumous).',
        'affiliation' => ['U.S. Army 24th Infantry Regiment, 3rd Battalion'],
        'cases' => [['institution' => $houstonInst, 'arrest_date' => '1917-08-25', 'sentenced_date' => '1917-12-01', 'death_in_custody_date' => '1917-12-11', 'sentence' => 'Death by hanging (Dec 11, 1917)', 'convicted' => 'Yes — court-martial; conviction set aside Nov 2023', 'prosecutor' => 'Col. John A. Hull (Trial Judge Advocate)', 'charges' => $houstonChargesBase]],
    ];
}

$people[] = ['name' => 'William D. Boone', 'first_name' => 'William', 'middle_name' => 'D.', 'last_name' => 'Boone', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas', 'death_date' => '1918-09-24', 'released' => false, 'description' => 'Pvt. William D. Boone of the 24th Infantry was sentenced to death in the second/third Houston court-martial. After clemency petitions, President Wilson commuted 10 of 16 condemned men in this round but approved Boone\'s execution. Hanged at Fort Sam Houston September 24, 1918, one week after five other condemned soldiers were executed there. Conviction set aside November 2023.', 'affiliation' => ['U.S. Army 24th Infantry Regiment'], 'cases' => [['institution' => $houstonInst, 'arrest_date' => '1917-08-25', 'sentenced_date' => '1918-03-26', 'death_in_custody_date' => '1918-09-24', 'sentence' => 'Death by hanging (Sept 24, 1918)', 'convicted' => 'Yes — court-martial; conviction set aside Nov 2023', 'charges' => $houstonChargesBase]]];

$people[] = ['name' => 'Roy Tyler', 'first_name' => 'Roy', 'last_name' => 'Tyler', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas', 'description' => 'Pvt. Roy Tyler of the 24th Infantry was sentenced to life imprisonment at Fort Leavenworth following conviction in one of the Houston riot court-martials. Paroled December 14, 1924 along with three other Houston rioters; went on to play in the Negro baseball leagues. Conviction set aside November 2023.', 'affiliation' => ['U.S. Army 24th Infantry Regiment'], 'cases' => [['institution' => $houstonInst, 'arrest_date' => '1917-08-25', 'sentenced_date' => '1918-03-26', 'release_date' => '1924-12-14', 'sentence' => 'Life imprisonment (paroled 1924)', 'convicted' => 'Yes — court-martial', 'charges' => $houstonChargesBase]]];

$people[] = ['name' => 'LeRoy Pinkett', 'first_name' => 'LeRoy', 'last_name' => 'Pinkett', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas', 'description' => 'Pvt. LeRoy Pinkett, age 23 at conviction, was found guilty of murder, mutiny, and assault with intent to murder in one of the Houston court-martials and was imprisoned at Fort Leavenworth. Conviction set aside November 2023.', 'affiliation' => ['U.S. Army 24th Infantry Regiment'], 'cases' => [['institution' => $houstonInst, 'arrest_date' => '1917-08-25', 'sentenced_date' => '1918-03-26', 'sentence' => 'Life imprisonment', 'convicted' => 'Yes — court-martial', 'charges' => $houstonChargesBase]]];

$people[] = ['name' => 'Albert D. Wright', 'first_name' => 'Albert', 'middle_name' => 'D.', 'last_name' => 'Wright', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas', 'description' => 'Pvt. Albert D. Wright of the 24th Infantry was sentenced to death in one of the later Houston court-martials. President Wilson commuted his death sentence to life imprisonment after national clemency petitions. Served at Fort Leavenworth.', 'affiliation' => ['U.S. Army 24th Infantry Regiment'], 'cases' => [['institution' => $houstonInst, 'arrest_date' => '1917-08-25', 'sentenced_date' => '1918-03-26', 'sentence' => 'Death (commuted to life imprisonment by President Wilson)', 'convicted' => 'Yes — court-martial', 'charges' => $houstonChargesBase]]];

// ===== 6. Silent Sentinels =====
$nwpInst = ['name' => 'Occoquan Workhouse / DC Jail — Silent Sentinels', 'city' => 'Lorton', 'state' => 'Virginia'];
$nwpChargesBase = 'National Woman\'s Party "Silent Sentinels" picketing of the Wilson White House (Jan 10, 1917 - June 1919). ~2,000 women picketed; ~500 arrested; 168 jailed at Occoquan Workhouse (Lorton VA) and DC Jail. Charges typically "obstructing sidewalk traffic" — pretextual misdemeanor. The "Night of Terror" Nov 14, 1917 saw guards beat 33 newly arrived suffragists. Many were force-fed during hunger strikes.';

$sentinels = [
    ['Alice Stokes Paul', '1885-01-11', '1977-07-09', '1917-10-20', '7 months', '1917-11-27', 'Founder of the National Woman\'s Party and chief strategist of the militant U.S. suffrage movement. A Hicksite Quaker from Mount Laurel, New Jersey; PhD in economics (Penn 1912); apprenticed in militant tactics with Emmeline Pankhurst\'s WSPU in Britain. Beginning January 10, 1917, organized the "Silent Sentinels" picketing. After Oct 20, 1917 arrest, sentenced to seven months and led hunger strikes at the District Jail; authorities transferred her to a psychiatric ward and force-fed her raw eggs through a feeding tube three times daily. Authored the original Equal Rights Amendment in 1923.', ['National Woman\'s Party (founder)', 'Religious Society of Friends']],
    ['Lucy Burns', '1879-07-28', '1966-12-22', '1917-09-04', '6 months (max on third arrest)', null, 'Alice Paul\'s closest collaborator in the National Woman\'s Party; suffragist who served the most prison time of any American woman in the campaign. Vassar 1902; born in Brooklyn to an Irish Catholic family. On the November 14, 1917 "Night of Terror" she was beaten at Occoquan and chained by her wrists to her cell bars overnight; later force-fed via nasal tube by five guards. After ratification she retired to Brooklyn.', ['National Woman\'s Party']],
    ['Vida Milholland', '1888-01-17', '1952-06-15', '1917-07-04', '3 days', null, 'Younger sister of Inez Milholland; Vassar-trained singer who abandoned her musical career after Inez\'s death to take up full-time suffrage work. Picketed the White House on July 4, 1917, was arrested, served three days in DC Jail singing every night for the morale of fellow prisoners. In 1919 joined the NWP\'s "Prison Special" national tour.', ['National Woman\'s Party']],
    ['Lavinia Lloyd Dock', '1858-02-26', '1956-04-17', '1917-08-15', null, null, 'Pioneer of American nursing — co-founder of what became the National League for Nursing, author of the first nurses\' drug manual (1890). In 1917 moved to Washington and joined the advisory council of the National Woman\'s Party. First arrested in 1896 attempting to vote. As a Silent Sentinel arrested at least three times in 1917 and served sentences at Occoquan. In her late 50s, among the older suffragists imprisoned.', ['National Woman\'s Party', 'American Nurses Association']],
    ['Doris Stevens', '1888-10-26', '1963-03-22', '1917-07-14', '60 days (pardoned after 3)', '1917-07-17', 'Oberlin-trained organizer (1911); served as executive secretary of the Congressional Union and a key NWP strategist. Born in Omaha to a pastor and a Dutch immigrant mother. Picketed the White House on Bastille Day July 14, 1917 with fifteen others; sentenced to 60 days at Occoquan; served three days before President Wilson pardoned the group. Her 1920 book "Jailed for Freedom" is the principal firsthand account of NWP imprisonment.', ['National Woman\'s Party', 'Congressional Union for Woman Suffrage']],
    ['Helena Hill Weed', '1875-08-16', '1958-04-20', '1917-07-04', '3 days (1917); 24 hours (Jan 1918); 15 days (Aug 1918)', null, 'Daughter of U.S. Congressman Ebenezer J. Hill; Vassar graduate (1896); one of the first women geologists in the United States. On July 4, 1917 picketed the White House with a banner reading "Governments derive their just powers from the consent of the governed"; sentenced to three days in jail. Arrested again in January 1918 (24-hour sentence for applauding in court) and August 1918 (15 days for the Lafayette Square meeting where Wilson\'s words were ceremonially burned).', ['National Woman\'s Party']],
    ['Annie Melvin Arniel', '1873-05-15', '1924-02-09', '1917-06-27', 'Multiple, totaling 103 days', null, 'Wilmington factory worker recruited to the NWP by Mabel Vernon and Alice Paul; one of Delaware\'s most-jailed suffragists. Among the first six suffragists arrested at the White House on June 27, 1917; served eight separate jail terms totaling 103 days, including 60 days at Occoquan in 1917, 15 days for the Lafayette Square meeting in 1918, and five 5-day sentences during the 1919 "watchfire" demonstrations.', ['National Woman\'s Party']],
    ['Edith Mary Ainge', '1873-09-10', '1948-10-25', '1917-09-04', null, null, 'English-born Jamestown, NY suffragist who served as treasurer of the National Woman\'s Party. First arrested September 4, 1917 — the "March of Draftees" day — for unfurling a banner reading "How Long Must Woman Be Denied a Voice in a Government Which is Conscripting Their Sons." Arrested approximately five times between September 1917 and January 1919.', ['National Woman\'s Party']],
    ['Mary A. Nolan', '1842-01-15', '1925-05-19', '1917-11-10', '6 days', null, '73-year-old Jacksonville suffragist — the oldest known prisoner of the campaign and the only Floridian imprisoned for suffrage. Born in Martinsburg, Virginia (later WV) in 1842; joined the NWP in 1917; arrested November 10, 1917 along with 30 other picketers. Given the lightest sentence (six days) on account of her age; sent to Occoquan and witnessed the Night of Terror. Her published narrative "That Night of Terror" triggered the firing of Superintendent W.H. Whittaker.', ['National Woman\'s Party']],
    ['Dora Kelly Lewis', '1862-10-13', '1928-01-31', '1917-11-10', '60 days (Night of Terror cohort)', null, 'Philadelphia widow from a prominent family who became one of Alice Paul\'s earliest and most steadfast supporters, joining the Congressional Union at its 1913 founding. On the November 14, 1917 Night of Terror, thrown into a tiny Occoquan cell, struck her head on an iron bedstead and lost consciousness; her cellmate Alice Cosu suffered a heart attack believing Lewis was dead. With Lucy Burns led the prisoners\' hunger strike and endured force-feeding "gasping and suffocating with the agony of it."', ['National Woman\'s Party']],
    ['Pauline Forstall Adams', '1874-06-29', '1957-09-10', '1917-09-04', '60 days', '1917-11-04', 'Dublin-born suffragist who emigrated to the U.S. in 1898 and founded the Norfolk Equal Suffrage League at her home in 1910. On September 4, 1917 was one of thirteen NWP picketers arrested in front of Wilson\'s reviewing stand at the Selective Service parade. Refusing the $25 fine, chose 60 days at Occoquan; released November 4, 1917. After ratification became the second woman to practice law in Norfolk (1921).', ['National Woman\'s Party', 'Norfolk Equal Suffrage League (founder)']],
    ['Elizabeth Selden Rogers', '1868-07-23', '1950-12-18', '1917-07-14', '60 days (pardoned by Wilson within days)', null, 'New York civic reformer and Putnam County NWP leader. On Bastille Day July 14, 1917 was one of 16 Silent Sentinels arrested at the White House carrying a banner with the French motto "Liberty, Equality, Fraternity." Told the judge, "We know full well that we stand here because the President of the United States refuses to give liberty to American women." Sentenced to 60 days; pardoned by Wilson within days.', ['National Woman\'s Party', 'Women\'s Political Union']],
];

foreach ($sentinels as $row) {
    [$name, $birth, $death, $arrest, $sentence, $release, $bio, $affil] = $row;
    $parts = explode(' ', $name);
    $first = $parts[0];
    $last = end($parts);
    $middle = count($parts) >= 3 ? implode(' ', array_slice($parts, 1, -1)) : null;
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => 'Female', 'race' => 'White', 'state' => 'District of Columbia',
        'birthdate' => $birth, 'death_date' => $death,
        'description' => $bio,
        'affiliation' => $affil,
        'ideologies' => ['Women\'s suffrage', 'Feminism'],
        'cases' => [['institution' => $nwpInst, 'arrest_date' => $arrest, 'release_date' => $release, 'sentence' => $sentence, 'convicted' => 'Yes — misdemeanor', 'judge' => 'Hon. Alexander R. Mullowney (DC Police Court)', 'charges' => $nwpChargesBase]],
    ];
}

// ===== 7. Mooney-Billings + Whitney + Gitlow =====
$people[] = ['name' => 'Thomas Joseph Mooney', 'first_name' => 'Thomas', 'middle_name' => 'Joseph', 'last_name' => 'Mooney', 'aka' => 'Tom Mooney', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1882-12-08', 'death_date' => '1942-03-06', 'description' => 'San Francisco labor organizer and IWW militant — son of an Irish coal-miner Knights of Labor organizer — who along with Warren K. Billings was framed for the July 22, 1916 Preparedness Day Parade bombing on Market Street that killed ten and injured forty. Convicted of first-degree murder in 1917 on perjured testimony; sentenced to death. President Wilson, alarmed that Mooney\'s execution might trigger Russian-style worker revolt, personally interceded with California Governor William Stephens, who in 1918 commuted the sentence to life. The case became a 22-year international cause célèbre. Pardoned by Governor Culbert L. Olson on January 7, 1939.', 'affiliation' => ['Industrial Workers of the World', 'Socialist Party'], 'cases' => [['institution' => ['name' => 'San Quentin State Prison', 'city' => 'San Quentin', 'state' => 'California'], 'arrest_date' => '1916-07-26', 'sentenced_date' => '1917-02-24', 'release_date' => '1939-01-07', 'sentence' => 'Death (commuted 1918 to life by Gov. Stephens at Wilson\'s urging); pardoned 1939 by Gov. Olson', 'convicted' => 'Yes', 'judge' => 'Hon. Franklin Griffin (Superior Court, San Francisco)', 'prosecutor' => 'Charles Fickert (San Francisco DA)', 'charges' => 'First-degree murder (Preparedness Day bombing) — frame-up by Pinkerton-style detective Martin Swanson on perjured testimony.']]];

$people[] = ['name' => 'Warren Knox Billings', 'first_name' => 'Warren', 'middle_name' => 'Knox', 'last_name' => 'Billings', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1893-07-04', 'death_date' => '1972-08-05', 'description' => 'Born in Middletown, New York on Independence Day 1893; young shoe-workers\' organizer convicted before Mooney to provide a "predicate" conspirator. Sentenced to life for second-degree murder in the 1916 San Francisco Preparedness Day bombing. Held at Folsom State Prison, where he learned watchmaking. After 23 years, 2 months and 20 days of imprisonment — the longest of any Wilson-era political prisoner in the United States — California Governor Culbert L. Olson commuted his sentence to time served in 1939. Full pardon from Governor Edmund G. "Pat" Brown in 1961.', 'affiliation' => ['Shoe Workers union', 'Socialist Party'], 'cases' => [['institution' => ['name' => 'Folsom State Prison', 'city' => 'Folsom', 'state' => 'California'], 'arrest_date' => '1916-07-26', 'sentenced_date' => '1916-09-23', 'release_date' => '1939-10-16', 'sentence' => 'Life imprisonment (second-degree murder); commuted to time served 1939; pardoned 1961', 'convicted' => 'Yes', 'judge' => 'Hon. Franklin Dunn (Superior Court, San Francisco)', 'prosecutor' => 'Charles Fickert (San Francisco DA)', 'charges' => 'Second-degree murder (Preparedness Day bombing).']]];

$people[] = ['name' => 'Charlotte Anita Whitney', 'first_name' => 'Charlotte', 'middle_name' => 'Anita', 'last_name' => 'Whitney', 'aka' => 'Anita Whitney', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1867-07-07', 'death_date' => '1955-02-04', 'description' => 'Wellesley-educated heiress (great-niece of Supreme Court Justice Stephen J. Field), social worker, and California suffrage and NAACP organizer who became a charter member of the Communist Labor Party in 1919. Arrested November 28, 1919 after a speech to the Oakland Civic Club; charged with five counts under California\'s brand-new Criminal Syndicalism Act. Conviction unanimously upheld in Whitney v. California, 274 U.S. 357 (1927) — most famous for Justice Brandeis\'s concurring opinion articulating the "clear and present danger" standard. June 20, 1927 California Governor C.C. Young granted her an unconditional pardon.', 'affiliation' => ['Communist Labor Party of America (charter member)', 'NAACP (co-founder San Francisco branch)'], 'cases' => [['institution' => ['name' => 'San Quentin / California state courts — Whitney v. California', 'city' => 'San Francisco', 'state' => 'California'], 'arrest_date' => '1919-11-28', 'sentenced_date' => '1920-02-15', 'release_date' => '1927-06-20', 'sentence' => '1-14 years criminal-syndicalism felony (free on bail; pardoned by Gov. C.C. Young June 20, 1927)', 'convicted' => 'Yes; affirmed 274 U.S. 357 (1927); pardoned same year', 'charges' => 'California Criminal Syndicalism Act (1919), 5 counts.']]];

$people[] = ['name' => 'Benjamin Gitlow', 'first_name' => 'Benjamin', 'last_name' => 'Gitlow', 'aka' => 'Ben Gitlow', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1891-12-22', 'death_date' => '1965-07-19', 'description' => 'Son of Russian-Jewish immigrants and a former New York State assemblyman; founding member of the Communist Labor Party of America in 1919 and business manager of The Revolutionary Age, which published "The Left Wing Manifesto" in July 1919. Arrested by NYPD November 1919 along with Alan Larkin under New York\'s Criminal Anarchy Law of 1902. Convicted February 11, 1920; sentenced 5-10 years at Sing Sing. Conviction famously upheld 7-2 in Gitlow v. New York, 268 U.S. 652 (1925) — the case that "incorporated" the First Amendment against the states. Pardoned by Governor Al Smith December 1925.', 'affiliation' => ['Communist Labor Party of America (founding member)', 'Communist Party USA (founding member)'], 'cases' => [['institution' => ['name' => 'Sing Sing Correctional Facility', 'city' => 'Ossining', 'state' => 'New York'], 'arrest_date' => '1919-11-08', 'sentenced_date' => '1920-02-11', 'release_date' => '1925-12-15', 'sentence' => '5-10 years state prison; pardoned by Gov. Al Smith Dec 1925', 'convicted' => 'Yes; affirmed Gitlow v. New York, 268 U.S. 652 (1925)', 'judge' => 'Hon. Bartow S. Weeks', 'charges' => 'Criminal anarchy under New York Criminal Anarchy Law of 1902.']]];

// ===== 8. Black militants + Sanger + East St Louis =====
$people[] = ['name' => 'Marcus Mosiah Garvey Jr.', 'first_name' => 'Marcus', 'middle_name' => 'Mosiah', 'last_name' => 'Garvey Jr.', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1887-08-17', 'death_date' => '1940-06-10', 'description' => 'Jamaican-born founder of the Universal Negro Improvement Association (1914) and Black Star Line steamship company (1919). From 1918 the UNIA was a primary target of J. Edgar Hoover\'s Bureau of Investigation. Federal mail-fraud trial in New York May 18 - June 18, 1923 before Judge Julian W. Mack with Maxwell Mattuck as chief prosecutor. Garvey defended himself; convicted while three co-defendants were acquitted; sentenced to 5 years and $1,000 fine. Served 33 months at U.S. Penitentiary Atlanta before his sentence was commuted by President Calvin Coolidge in November 1927 and he was deported to Jamaica. Posthumously pardoned by President Biden 2025.', 'affiliation' => ['Universal Negro Improvement Association (founder)', 'Black Star Line'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary Atlanta — Garvey mail fraud', 'city' => 'Atlanta', 'state' => 'Georgia'], 'arrest_date' => '1922-01-12', 'sentenced_date' => '1923-06-21', 'release_date' => '1927-12-02', 'sentence' => '5 years federal prison + $1,000 fine; commuted 1927 by Coolidge; deported to Jamaica', 'convicted' => 'Yes', 'judge' => 'Hon. Julian W. Mack', 'prosecutor' => 'Maxwell S. Mattuck (AUSA)', 'charges' => 'Mail fraud (using U.S. mails to defraud in connection with Black Star Line stock sales). Wilson-era Bureau of Investigation surveillance built the case.']]];

$people[] = ['name' => 'A. Philip Randolph', 'first_name' => 'Asa', 'middle_name' => 'Philip', 'last_name' => 'Randolph', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1889-04-15', 'death_date' => '1979-05-16', 'description' => 'Born in Crescent City, Florida; edited (with Chandler Owen) The Messenger — "the only radical Negro magazine in America" — beginning November 1917. The July 1918 issue\'s anti-war content placed him in the Wilson Espionage Act crosshairs. On August 4, 1918 in Cleveland, after he and Owen addressed a Socialist Party rally, an undercover Justice Department agent broke up the meeting and arrested both men. Held overnight under Espionage Act charges; released the next day when the federal judge — disbelieving someone so young could have written the offending material — dismissed charges. Founded the Brotherhood of Sleeping Car Porters (1925).', 'affiliation' => ['Socialist Party of America', 'The Messenger magazine', 'Brotherhood of Sleeping Car Porters'], 'cases' => [['institution' => ['name' => 'Cleveland city jail', 'city' => 'Cleveland', 'state' => 'Ohio'], 'arrest_date' => '1918-08-04', 'release_date' => '1918-08-05', 'sentence' => 'Charges dismissed; held overnight', 'convicted' => 'No — charges dismissed', 'charges' => 'Espionage Act of 1917 / sedition (charges dismissed by federal judge).']]];

$people[] = ['name' => 'Margaret Higgins Sanger', 'first_name' => 'Margaret', 'middle_name' => 'Higgins', 'last_name' => 'Sanger', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1879-09-14', 'death_date' => '1966-09-06', 'description' => 'Opened the first U.S. birth-control clinic at 46 Amboy Street, Brownsville, Brooklyn on October 16, 1916, with her sister Ethel Byrne and interpreter Fania Mindell. The clinic served some 400 women in 10 days before an undercover policewoman shut it down on October 26, 1916, arresting all three. Charged under New York\'s Comstock obscenity statute, tried in early 1917 before a three-judge panel and sentenced to 30 days in Queens County Penitentiary. The 1918 New York Court of Appeals "Crane decision" upheld her conviction but for the first time permitted physicians to prescribe contraceptives.', 'affiliation' => ['American Birth Control League (founder)', 'Brownsville Clinic'], 'cases' => [['institution' => ['name' => 'Queens County Penitentiary', 'city' => 'Queens', 'state' => 'New York'], 'arrest_date' => '1916-10-26', 'sentenced_date' => '1917-02-02', 'release_date' => '1917-03-15', 'sentence' => '30 days', 'convicted' => 'Yes', 'judge' => 'Hon. John J. Freschi (presiding three-judge panel)', 'charges' => 'Violation of New York Penal Code §1142 (Comstock — distribution of contraceptive information).']]];

$people[] = ['name' => 'LeRoy Nathaniel Bundy', 'first_name' => 'LeRoy', 'middle_name' => 'Nathaniel', 'last_name' => 'Bundy', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Illinois', 'birthdate' => '1879-01-01', 'death_date' => '1943-12-15', 'description' => 'Dentist and the principal Black political organizer in East St. Louis, Illinois at the time of the July 2, 1917 race massacre. The state authorities, declining to prosecute most white attackers, charged Bundy with conspiring to lead a Black "mob" that allegedly sparked the riot. Convicted March 28, 1919 in Waterloo, Illinois on testimony from Edward Wilson who himself admitted Bundy had not participated; sentenced to life imprisonment. Served one year, working as a dentist inside the prison, before the Illinois Supreme Court reversed his conviction (one juror declared insane; coercion of witnesses; insufficient evidence). Moved to Cleveland, earned law degree at Western Reserve, became prominent UNIA leader.', 'affiliation' => ['Republican Party (East St. Louis Black political organizer)', 'UNIA (later)'], 'cases' => [['institution' => ['name' => 'Illinois state prison — East St. Louis race riot prosecution', 'city' => 'Waterloo', 'state' => 'Illinois'], 'arrest_date' => '1917-07-15', 'sentenced_date' => '1919-03-28', 'release_date' => '1920-06-15', 'sentence' => 'Life imprisonment (reversed on appeal by Illinois Supreme Court)', 'convicted' => 'Yes; reversed on appeal', 'charges' => 'Conspiracy / inciting to riot / murder (state).']]];

// ===== Apply =====
foreach ($people as $p) {
    $p['ideologies'] = $p['ideologies'] ?? ['Anti-militarism', 'Pacifism / Socialism / Anarchism'];
    $p['era'] = $p['era'] ?? '1910s';
    [$prisoner, $created] = addP($p);
    echo ($created ? '  CREATED' : '  EXISTS ') . " {$p['name']} (id={$prisoner->id})\n";
    $created ? $tot['created']++ : $tot['existed']++;
    foreach ($p['cases'] ?? [] as $c) {
        if (attachC($prisoner, $c)) { echo "    + case ({$c['arrest_date']})\n"; $tot['cases']++; }
    }
}

echo "\nDone.\n";
echo "  prisoners created:        {$tot['created']}\n";
echo "  prisoners already existed: {$tot['existed']}\n";
echo "  cases added:              {$tot['cases']}\n";
