#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_smith_act_prisoners.sh
#
# Adds 15 Smith Act conspiracy-clause prisoners who served substantial
# federal time, beyond the original Dennis 11 (already in the DB).
# Focuses on the Foley Square Second String (NY 1952-53), the
# Pittsburgh Six, the Baltimore Six, and the Detroit Six. Most of these
# convictions stood until the 1957 Yates v. United States ruling forced
# the government to abandon the campaign; many of these defendants
# served between 18 months and 4 years before that point.
set -e

# ============================================================
# Foley Square Second String — New York, 1951-1957
# Indicted June 1951; tried 1952-53; sentenced January 1953.
# 13 defendants; sentences ranged from 1 to 3 years. Most served
# their full sentences at Alderson (women) or at Atlanta, Lewisburg,
# or Danbury (men) before Yates.
# ============================================================

php artisan prisoner:add '{"name":"Elizabeth Gurley Flynn","first_name":"Elizabeth","middle_name":"Gurley","last_name":"Flynn","description":"Elizabeth Gurley Flynn was one of the most consequential American radicals of the twentieth century. As a teenage organizer in the early 1900s she became a leading figure of the Industrial Workers of the World, leading textile, silk, and miners strikes from Lawrence, Massachusetts to Paterson, New Jersey to the Mesabi iron range — Joe Hills 1915 song The Rebel Girl was written for her. She was a co-founder of the American Civil Liberties Union in 1920 and remained on its board until 1940, when she was expelled in a closed vote because of her membership in the Communist Party USA, a vote the ACLU formally apologized for in 1976.\n\nIn June 1951 she was indicted in the Foley Square Second String — the federal governments second wave of Smith Act prosecutions, which targeted thirteen members of the CPUSA national board after the original Dennis 11. Convicted at trial in early 1953, she was sentenced to three years in federal prison and began her sentence at the Federal Reformatory for Women at Alderson, West Virginia, in January 1955 at age 64. She served 28 months and was released in May 1957. Her prison memoir The Alderson Story: My Life as a Political Prisoner appeared in 1963. She became national chairwoman of the Communist Party USA in 1961, a position she held until her death in Moscow in 1964.","state":"New York","race":"White","gender":"Female","birthdate":"1890-08-07","death_date":"1964-09-05","ideologies":["Communism","Labor","First Amendment"],"affiliation":["Communist Party USA","Industrial Workers of the World","American Civil Liberties Union"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Reformatory for Women, Alderson","institution_city":"Alderson","institution_state":"West Virginia","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-01-25","release_date":"1957-05-25","sentence":"3 years federal prison; served 28 months at Alderson","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Pettis Perry","first_name":"Pettis","last_name":"Perry","description":"Pettis Perry was the highest-ranking Black member of the Communist Party USA at the time of his Smith Act prosecution and one of the partys most influential theorists on Black liberation. Born to sharecroppers in Alabama in 1897, he came to Communist politics through his work with the International Labor Defense in the Scottsboro Boys defense campaign and rose through the partys ranks during the 1930s and 1940s. By the time of his 1951 indictment in the Foley Square Second String he was a member of the partys Secretariat and the head of its National Negro Commission.\n\nConvicted in early 1953 alongside Elizabeth Gurley Flynn and the rest of the second string, he was sentenced to three years in federal prison. He served his time at the United States Penitentiary in Atlanta, where the conditions in the segregated Black wing severely damaged his health. After his release he traveled to the Soviet Union for medical treatment and died there in 1965.","state":"New York","race":"Black","gender":"Male","birthdate":"1897-01-04","death_date":"1965-07-26","ideologies":["Communism","Black Liberation"],"affiliation":["Communist Party USA","International Labor Defense"],"in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Atlanta","institution_city":"Atlanta","institution_state":"Georgia","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-09-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Alexander Trachtenberg","first_name":"Alexander","last_name":"Trachtenberg","description":"Alexander Trachtenberg was the founder and longtime publisher of International Publishers, the principal U.S. publishing house of Marxist literature for most of the twentieth century. International Publishers issued the first English-language collected edition of Marx and Engels, the works of Lenin, the writings of W. E. B. Du Bois on Reconstruction, and a wide range of American radical and labor history.\n\nTrachtenberg was indicted in the Foley Square Second String in June 1951 and convicted alongside Elizabeth Gurley Flynn and the rest of the CPUSA national board in January 1953. He was sentenced to three years and served two years at the federal prison camp at Danbury, Connecticut, before being released on bond pending appeal. After the Supreme Courts 1957 Yates decision the government retried him; the second jury hung, and the prosecution was abandoned in 1958. He continued to run International Publishers until his death in 1966.","state":"New York","race":"White","gender":"Male","birthdate":"1885-01-17","death_date":"1966-12-15","ideologies":["Communism"],"affiliation":["Communist Party USA","International Publishers"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"3 years federal prison; served 2 years before release on bond pending appeal; second prosecution after Yates ended in a hung jury and was abandoned","convicted":"Yes — federal jury verdict, January 1953; second prosecution after Yates v. United States (1957) ended in hung jury and was abandoned"}]}'

php artisan prisoner:add '{"name":"Betty Gannett","first_name":"Betty","last_name":"Gannett","description":"Betty Gannett was a Communist Party USA organizer and a member of the partys National Education Department. She was indicted in the Foley Square Second String in June 1951 and convicted alongside Elizabeth Gurley Flynn and the rest of the CPUSA national board in January 1953. She was sentenced to two years in federal prison and served at the Federal Reformatory for Women at Alderson, West Virginia, alongside Flynn.","state":"New York","race":"White","gender":"Female","birthdate":"1907-12-21","death_date":"1970-04-21","ideologies":["Communism"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Reformatory for Women, Alderson","institution_city":"Alderson","institution_state":"West Virginia","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-01-25","release_date":"1957-01-25","sentence":"2 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"George Blake Charney","first_name":"George","middle_name":"Blake","last_name":"Charney","description":"George Blake Charney was a New York labor lawyer and a leading Communist Party USA figure in the postwar period. Born in Russia in 1905 and brought to New York as a child, he organized for the National Maritime Union and the New York State CIO before joining the partys national board. He was indicted in the Foley Square Second String in June 1951 and convicted alongside Elizabeth Gurley Flynn and the rest of the second string in January 1953. He was sentenced to three years in federal prison and served at Lewisburg.\n\nAfter his release Charney became one of the leading dissident voices inside the CPUSA over Khrushchevs 1956 secret speech denouncing Stalin. He left the party in 1958 and in 1968 published A Long Journey, one of the canonical first-person accounts of the American communist experience and its disintegration after 1956.","state":"New York","race":"White","gender":"Male","birthdate":"1905-07-15","death_date":"1975-05-20","ideologies":["Communism (former)"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Lewisburg","institution_city":"Lewisburg","institution_state":"Pennsylvania","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"V. J. Jerome","first_name":"Victor","middle_name":"Jeremy","last_name":"Jerome","aka":"V. J. Jerome","description":"Victor Jeremy Jerome was the longtime cultural commissar of the Communist Party USA and the editor of the partys cultural and theoretical magazine Political Affairs from 1937 to 1956. He was the partys leading public theorist on questions of art, film, and literature, and the author of The Negro in Hollywood Films (1950) and the autobiographical novel A Lantern for Jeremy (1952).\n\nIndicted in the Foley Square Second String in June 1951 and convicted alongside the rest of the CPUSA national board in January 1953, he was sentenced to three years in federal prison and served at the Federal Correctional Institution at Danbury, Connecticut. After his release he resumed editing Political Affairs and remained in the party until his death in London in 1965.","state":"New York","race":"White","gender":"Male","birthdate":"1896-04-09","death_date":"1965-05-08","ideologies":["Communism","Cultural criticism"],"affiliation":["Communist Party USA","Political Affairs (magazine)"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Albert Lannon","first_name":"Albert","last_name":"Lannon","description":"Albert Lannon was an Irish-American longshoreman, organizer for the National Maritime Union, and a member of the Communist Party USA national board. He was indicted in the Foley Square Second String in June 1951 and convicted alongside the rest of the second string in January 1953. He was sentenced to two years in federal prison.","state":"New York","race":"White","gender":"Male","birthdate":"1907-01-01","death_date":"1969-01-01","ideologies":["Communism","Labor"],"affiliation":["Communist Party USA","National Maritime Union"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"2 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Jacob Mindel","first_name":"Jacob","last_name":"Mindel","description":"Jacob Mindel was the senior member of the Foley Square Second String, the Communist Party USAs internal educator, and director of the partys Workers School in New York City for many years. He was 70 years old at the time of his 1951 indictment. Convicted alongside the rest of the second string in January 1953, he was sentenced to two years in federal prison. Because of his age and frail health he served a substantial portion of his sentence at the U.S. Medical Center for Federal Prisoners at Springfield, Missouri.","state":"New York","race":"White","gender":"Male","birthdate":"1882-01-01","death_date":"1969-01-01","ideologies":["Communism"],"affiliation":["Communist Party USA","Workers School (NYC)"],"in_custody":false,"released":true,"cases":[{"institution_name":"U.S. Medical Center for Federal Prisoners","institution_city":"Springfield","institution_state":"Missouri","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"2 years federal prison; served at the federal prison hospital due to age and ill health","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Louis Weinstock","first_name":"Louis","last_name":"Weinstock","description":"Louis Weinstock was a Brooklyn house-painter, longtime organizer for the painters union, and treasurer of the Communist Party USA. He was indicted in the Foley Square Second String in June 1951 and convicted with the rest of the second string in January 1953. He was sentenced to three years in federal prison.","state":"New York","race":"White","gender":"Male","birthdate":"1903-01-01","death_date":"1995-01-01","ideologies":["Communism","Labor"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1958-03-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Arnold Johnson","first_name":"Arnold","last_name":"Johnson","description":"Arnold Johnson was the Communist Party USAs longtime legislative director and its principal liaison with sympathetic members of Congress and with the broader peace and civil-rights movements. Indicted in the Foley Square Second String in June 1951 and convicted with the rest of the second string in January 1953, he was sentenced to three years in federal prison.","state":"New York","race":"White","gender":"Male","birthdate":"1904-01-01","death_date":"1989-01-01","ideologies":["Communism"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1958-03-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"Alexander Bittelman","first_name":"Alexander","last_name":"Bittelman","description":"Alexander Bittelman was one of the founding members of the Communist Party USA in 1919 and the partys leading internal theorist for more than three decades. Born in Berdichev in 1890, he emigrated to New York in 1912 and helped found the Workers Party of America in 1921, which became the CPUSA. He was the partys most senior intellectual at the time of his 1951 indictment in the Foley Square Second String.\n\nConvicted with the rest of the second string in January 1953, he was sentenced to three years in federal prison. After his release he became one of the most influential voices urging the party to confront the implications of Khrushchevs 1956 speech, and was expelled from the CPUSA in 1960 after publicly arguing for democratic reform of the party. He died in 1982.","state":"New York","race":"White","gender":"Male","birthdate":"1890-01-09","death_date":"1982-07-19","ideologies":["Communism (former)"],"affiliation":["Communist Party USA","Workers Party of America"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1958-03-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

php artisan prisoner:add '{"name":"William W. Weinstone","first_name":"William","middle_name":"W.","last_name":"Weinstone","description":"William Wolf Weinstone was a founding member of the Communist Party USA in 1919 and a longtime member of its national board. Indicted in the Foley Square Second String in June 1951 and convicted with the rest of the second string in January 1953, he was sentenced to two years in federal prison.","state":"New York","race":"White","gender":"Male","birthdate":"1898-12-12","death_date":"1985-04-25","ideologies":["Communism"],"affiliation":["Communist Party USA"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-06-20","incarceration_date":"1955-03-01","release_date":"1957-03-01","sentence":"2 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, January 1953"}]}'

# ============================================================
# Pittsburgh Six (1953)
# ============================================================

php artisan prisoner:add '{"name":"Steve Nelson","first_name":"Steve","last_name":"Nelson","description":"Steve Nelson was one of the most prominent American Communists of the twentieth century. Born Stjepan Mesaroš in Croatia in 1903, he emigrated to the United States as a teenager and became a CPUSA organizer in the steel and coal towns of western Pennsylvania. In 1937 he joined the Abraham Lincoln Brigade in Spain, was wounded twice, and rose to become commissar of the brigade — making him one of the most senior surviving American veterans of the Spanish Civil War. After Spain he organized for the CPUSA in California, where the FBI later alleged he had been part of the Soviet effort to obtain information from the Manhattan Project.\n\nNelson was prosecuted in three parallel cases in the early 1950s. In 1952 he was convicted in Pennsylvania state court of sedition and sentenced to 20 years; that conviction was reversed by the U.S. Supreme Court in 1956 in Pennsylvania v. Nelson, the landmark ruling that federal sedition law preempted state prosecutions. In 1953 he was convicted in federal court in Pittsburgh under the Smith Act and sentenced to five years in federal prison; he served until that conviction was reversed in light of Yates v. United States in 1957. After his release he wrote one of the canonical American Communist memoirs, Steve Nelson, American Radical (1981, with James R. Barrett and Rob Ruck).","state":"Pennsylvania","race":"White","gender":"Male","birthdate":"1903-12-25","death_date":"1993-12-13","ideologies":["Communism","Anti-fascist"],"affiliation":["Communist Party USA","Abraham Lincoln Brigade"],"in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Lewisburg","institution_city":"Lewisburg","institution_state":"Pennsylvania","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-08-22","incarceration_date":"1953-08-01","release_date":"1957-06-17","sentence":"5 years federal prison; served until reversal under Yates v. United States in 1957","convicted":"Yes — federal jury verdict, U.S. District Court for the Western District of Pennsylvania, August 1953; reversed on remand after Yates v. United States, 354 U.S. 298 (1957)"}]}'

# ============================================================
# Baltimore Six (1952)
# ============================================================

php artisan prisoner:add '{"name":"Maurice Braverman","first_name":"Maurice","last_name":"Braverman","description":"Maurice L. Braverman was a Baltimore labor and civil-liberties lawyer who became one of the most prominent legal-aid attorneys in Maryland after his Smith Act conviction was reversed and his bar membership was finally restored. Indicted with five other Baltimore-area Communists in 1951 (the Frankfeld case), he was convicted at trial in 1952 and sentenced to three years in federal prison; the Maryland Court of Appeals disbarred him on the basis of the conviction. He served his sentence — much of it at the federal prison camp at Allenwood, Pennsylvania — and was released in 1955. After Yates v. United States in 1957 the underlying conviction was effectively erased, but the Maryland bar refused to readmit him for another seventeen years. He was finally readmitted in 1974, became one of the founders of the Maryland Legal Aid Bureaus expansion into rural counties, and practiced civil-rights and prisoners-rights law in Baltimore until his death in 2003.","state":"Maryland","race":"White","gender":"Male","birthdate":"1916-06-30","death_date":"2003-02-15","ideologies":["Communism","Civil liberties"],"affiliation":["Communist Party USA","Maryland Legal Aid Bureau"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Prison Camp, Allenwood","institution_city":"Allenwood","institution_state":"Pennsylvania","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1951-04-01","incarceration_date":"1952-08-01","release_date":"1955-08-01","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, 1952; underlying conviction effectively erased by Yates v. United States (1957) on appellate remand"}]}'

# ============================================================
# Detroit Six (1954)
# ============================================================

php artisan prisoner:add '{"name":"Saul Wellman","first_name":"Saul","last_name":"Wellman","description":"Saul Wellman was a Spanish Civil War veteran of the Abraham Lincoln Brigade, a wounded U.S. Army veteran of the Battle of the Bulge in World War II, and the postwar chairman of the Michigan district of the Communist Party USA. The combination of Lincoln Brigade and Bronze Star paratrooper made him one of the most decorated American veterans the Smith Act prosecutions would target.\n\nIndicted in 1952 with five other Michigan-area Communists in the Detroit case, he was convicted at trial in 1954 and sentenced to five years in federal prison and a $10,000 fine. He served at Lewisburg and at the Federal Correctional Institution at Milan, Michigan, before being released on bond pending appeal. The conviction was vacated in 1957 in light of Yates v. United States and the indictment was dismissed in 1958 when the government declined to retry. After his release Wellman remained a left organizer in Detroit and worked as a printer; in 1979 he won a federal lawsuit against the Veterans Administration for the medical care it had refused him during his prison years on the grounds that he was a Communist.","state":"Michigan","race":"White","gender":"Male","birthdate":"1913-06-25","death_date":"2003-04-19","ideologies":["Communism","Anti-fascist"],"affiliation":["Communist Party USA","Abraham Lincoln Brigade","U.S. Army (101st Airborne)"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Milan","institution_city":"Milan","institution_state":"Michigan","charges":"Conspiracy to teach and advocate the violent overthrow of the U.S. government (Smith Act of 1940)","arrest_date":"1952-09-17","incarceration_date":"1954-10-01","release_date":"1957-06-17","sentence":"5 years federal prison and $10,000 fine; conviction vacated under Yates v. United States in 1957","convicted":"Yes — federal jury verdict, U.S. District Court for the Eastern District of Michigan, October 1954; vacated under Yates v. United States, 354 U.S. 298 (1957); indictment dismissed 1958"}]}'

echo
echo "All 15 Smith Act prisoner adds complete."
