#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round18_rna_bla_vieques.sh
#
# Source clusters:
#   - RNA-11 (Aug 18, 1971 Mississippi raid; founder Imari Obadele +
#     Mississippi state and federal convictions)
#   - BLA elders not yet in DB (Robert Seth Hayes, Kamau Sadiki / Freddie
#     Hilton, Maliki Shakur Latine, Veronza Bowers)
#   - Vieques (US Navy bombing range protests, 1999-2003) - Ruben Berrios
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Imari Obadele (RNA founder) ===

php artisan prisoner:add '{"name":"Imari Obadele","first_name":"Richard","middle_name":"Bullock","last_name":"Henry","aka":"Imari Abubakari Obadele","description":"Imari Abubakari Obadele I, born Richard Bullock Henry in Philadelphia in 1930, was a co-founder and Provisional President of the Republic of New Afrika (PGRNA), the New Afrikan independence formation that proclaimed the establishment of an independent Black nation in 1968 across the five U.S. southern states of Mississippi, Alabama, Georgia, Louisiana, and South Carolina. He was the principal theorist of the New Afrikan Independence Movement, the original architect of the modern Black reparations campaign, and a co-founder of the National Coalition of Blacks for Reparations in America (N COBRA).\n\nOn August 18, 1971, the FBI and Jackson, Mississippi police raided the PGRNA headquarters at 1148 Lewis Street in Jackson; in the ensuing gunfight Jackson police lieutenant William Skinner was killed and an FBI agent was wounded. Obadele was not present at the raid. He and ten others — the RNA-11 — were arrested and prosecuted in Mississippi state court for murder and sedition; he was acquitted in state court but was subsequently convicted in U.S. District Court for the Southern District of Mississippi of conspiracy to assault a federal officer. He was sentenced to 12 years in federal prison and served five years before release in 1980. The federal conviction, like much of the post-COINTELPRO era prosecution of Black liberation organizers, drew on FBI surveillance later revealed under FOIA to have been a sustained COINTELPRO operation against the RNA. He died on January 18, 2010, age 79.","state":"Mississippi","race":"Black","gender":"Male","birthdate":"1930-05-02","death_date":"2010-01-18","ideologies":["New Afrikan Independence","Black reparations","Black Liberation"],"affiliation":["Provisional Government of the Republic of New Afrika","National Coalition of Blacks for Reparations in America"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Mississippi","charges":"Federal conspiracy to assault a federal officer - August 18, 1971 FBI raid on the Republic of New Afrika headquarters in Jackson MS; Mississippi state murder and sedition charges acquitted","arrest_date":"1971-08-18","incarceration_date":"1975-04-15","release_date":"1980-04-15","sentence":"12 years federal prison; served 5 years","convicted":"Yes - U.S. District Court for the Southern District of Mississippi"}]}' || true

# === Robert Seth Hayes ===

php artisan prisoner:add '{"name":"Robert Seth Hayes","first_name":"Robert","middle_name":"Seth","last_name":"Hayes","description":"Robert Seth Hayes was a member of the New York chapter of the Black Panther Party and the Black Liberation Army. He was arrested on October 28, 1973 in connection with the June 5, 1973 killing of NYPD transit police officer Sidney Thompson at the West 4th Street station in lower Manhattan. He was convicted in 1974 of first-degree murder of a police officer and eight counts of attempted murder, weapons possession, grand theft, and collective association, and sentenced to 25 years to life in New York state prison.\n\nHe was repeatedly denied parole — eleven times across four decades — despite an exemplary disciplinary record. The Jericho Movement, of which he was a longtime board member, made his parole one of its central campaigns. He was finally released on December 5, 2018 after 45 years in New York state prison. He died on December 30, 2019, just over a year after his release, age 71.","state":"New York","race":"Black","gender":"Male","birthdate":"1948-12-15","death_date":"2019-12-30","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Black Liberation Army","Jericho Movement"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"New York Department of Corrections","institution_state":"New York","charges":"New York state first-degree murder of NYPD transit police officer Sidney Thompson, June 5, 1973","arrest_date":"1973-10-28","incarceration_date":"1973-10-28","release_date":"2018-12-05","sentence":"25 years to life; paroled after 45 years","convicted":"Yes - New York state jury verdict, 1974"}]}' || true

# === Kamau Sadiki ===

php artisan prisoner:add '{"name":"Kamau Sadiki","first_name":"Freddie","last_name":"Hilton","aka":"Kamau Sadiki","description":"Freddie Hilton, who took the New Afrikan name Kamau Sadiki, was a member of the New York chapter of the Black Panther Party and the Black Liberation Army. He went underground after the 1971 BPP-East/West split. The 1971 killing of Atlanta police officer James Green during the BLA underground period was federally cold-cased for thirty years. He was identified by reopened-cold-case investigators only after his 2002 New York City arrest on an unrelated weapons charge and was extradited to Georgia.\n\nOn November 10, 2003 a Fulton County Superior Court jury convicted him of the November 3, 1971 murder of Officer James Green; Judge Stephanie Manis sentenced him to life imprisonment plus 10 consecutive years for armed robbery. He has also faced extreme medical neglect during his Georgia state imprisonment - chronic kidney failure, advanced hepatitis C, and severe medical decline. He is held at the Augusta State Medical Prison in Grovetown, Georgia and has been a central focus of the contemporary Free Mumia / Free the Panthers prisoner-support movement. The Jericho Movement lists him among its current political prisoners.","state":"Georgia","race":"Black","gender":"Male","birthdate":"1953-06-15","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Black Liberation Army"],"era":"2000s","in_custody":true,"released":false,"cases":[{"institution_name":"Augusta State Medical Prison","institution_city":"Grovetown","institution_state":"Georgia","charges":"Georgia state murder of Atlanta police officer James Green, November 3, 1971 (cold case prosecuted 30 years later)","arrest_date":"2002-10-21","incarceration_date":"2003-11-10","sentenced_date":"2003-11-10","sentence":"Life plus 10 years consecutive","convicted":"Yes - Fulton County Superior Court jury verdict, November 10, 2003"}]}' || true

# === Maliki Shakur Latine ===

php artisan prisoner:add '{"name":"Maliki Shakur Latine","first_name":"Maliki","last_name":"Latine","description":"Maliki Shakur Latine was a member of the New York chapter of the Black Panther Party who joined in 1969 and went on to participate in the Black Liberation Army underground. He was arrested in 1979 in New York and convicted in 1981 of attempted murder of a police officer. He was sentenced to 25 years to life in New York state prison. He was repeatedly denied parole based on his BPP/BLA political affiliations rather than his prison record. Following sustained organizing by the Parole Preparation Project of the New York City National Lawyers Guild and the Jericho Movement, he was paroled in November 2016 after 37 years and was released on December 6, 2016.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Black Liberation Army","Jericho Movement"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"New York Department of Corrections","institution_state":"New York","charges":"New York state attempted murder of a police officer, 1979","arrest_date":"1979-09-01","incarceration_date":"1979-09-01","release_date":"2016-12-06","sentence":"25 years to life; paroled after 37 years","convicted":"Yes - New York state conviction, 1981"}]}' || true

# === Veronza Bowers ===

php artisan prisoner:add '{"name":"Veronza Bowers","first_name":"Veronza","last_name":"Bowers","description":"Veronza Leon Bowers Jr. was a member of the Kansas City chapter of the Black Panther Party. He was arrested in 1973 in connection with the June 1973 killing of U.S. National Park Service ranger Kenneth Patrick at Point Reyes National Seashore in California. The federal prosecution rested almost entirely on the testimony of two government informants who received reduced sentences on unrelated charges in exchange for their testimony. He was convicted in 1974 of first-degree murder of a federal officer and sentenced to life with the possibility of parole.\n\nUnder the federal sentencing structure in effect at the time of his conviction he became eligible for mandatory parole on April 7, 2004 after 30 years served. The U.S. Parole Commission has repeatedly denied his release in defiance of the mandatory-parole statute, drawing federal litigation across two decades. He was finally released from the Federal Medical Center in Butner, North Carolina on May 24, 2024 — age 78, after 51 years in federal prison and ranking as the longest-held federal political prisoner in U.S. history. The Jericho Movement and the Anarchist Black Cross Federation made his case a central campaign for decades.","state":"California","race":"Black","gender":"Male","birthdate":"1946-05-29","ideologies":["Black Liberation"],"affiliation":["Black Panther Party (Kansas City chapter)","Jericho Movement"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Medical Center, Butner","institution_city":"Butner","institution_state":"North Carolina","charges":"Federal first-degree murder of National Park Service ranger Kenneth Patrick at Point Reyes National Seashore, June 1973 - conviction relied on government informant testimony","arrest_date":"1973-08-22","incarceration_date":"1974-04-15","release_date":"2024-05-24","sentence":"Life with possibility of parole; mandatory parole eligibility April 7, 2004; finally released after 51 years","convicted":"Yes - federal jury verdict, 1974"}]}' || true

# === Vieques — Ruben Berrios ===

php artisan prisoner:add '{"name":"Ruben Berrios","first_name":"Ruben","last_name":"Berrios Martinez","description":"Rubén Berríos Martínez is the longtime president of the Puerto Rican Independence Party (PIP). On May 1, 1999, less than two weeks after Puerto Rican civilian David Sanes was killed by errant U.S. Navy bombs at the Vieques training range, he led the first major civil-disobedience encampment on the bombing range. He remained on the range for nearly a year. On May 4, 2000, U.S. Navy and federal agents arrested him and other peace-camp residents for trespassing on U.S. military property. He served four months in federal prison. The four-year Vieques campaign succeeded in forcing the U.S. Navy to withdraw from the bombing range on May 1, 2003 after 60 years. Hundreds of Vieques protesters were arrested and jailed during the 1999-2003 campaign.","state":"Puerto Rico","race":"Hispanic","gender":"Male","birthdate":"1939-06-21","ideologies":["Puerto Rican Independence","Anti-imperialist","Pacifism"],"affiliation":["Puerto Rican Independence Party"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Puerto Rico","charges":"Federal trespassing on U.S. Navy property - May 4, 2000 Vieques bombing range peace camp","arrest_date":"2000-05-04","incarceration_date":"2000-05-04","release_date":"2000-09-04","sentence":"4 months federal prison","convicted":"Yes - federal court conviction, 2000"}]}' || true

echo
echo "Round 18 (RNA + BLA elders + Vieques) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
