#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_fulani_oscar.sh
set -e

php artisan prisoner:add '{"name":"Iya Fulani Sunni-Ali","first_name":"Iya","middle_name":"Fulani","last_name":"Sunni-Ali","aka":"Cynthia Boston","description":"Iya Fulani Sunni-Ali, born Cynthia Boston in New Rochelle, New York in 1948, was a singer, educator, and Minister of Information of the Provisional Government of the Republic of New Afrika. She took the citizens oath of the PGRNA under her father, Alajo Adegbalola, who served as the PGRNAs Minister of Defense in 1970 and First Vice-President from 1971 to 1972. From the late 1960s she sang professionally and toured the world for four years with the South African singer Miriam Makeba; she also worked in security for Stokely Carmichael during the same period.\n\nOn October 27, 1981 — one week after the failed Brinks armored-car robbery in Nyack, New York that killed two police officers and a Brinks guard — she was arrested at the home of fellow PGRNA citizen Jerry Gaines in Gallman, Mississippi, in a predawn raid by more than 200 federal, state, and local law enforcement agents, with tanks and helicopters. She and Gaines were arrested in front of fourteen children. Federal prosecutors initially charged her in connection with the Brinks robbery, but a New Orleans car mechanic confirmed her alibi that she had been in Louisiana on the day of the robbery and the substantive charges were dropped. The same day, she was served with a federal grand jury subpoena demanding she testify about the Brinks investigation. She refused. She was jailed for civil contempt at the Metropolitan Correctional Center in New York City and held there for approximately eighteen months until her release on October 19, 1983. Her silence — preserved at substantial personal cost — was treated by the Black liberation movement as one of the most disciplined examples of grand-jury resistance of the post-COINTELPRO era. She died on July 17, 2016.","state":"New York","race":"Black","gender":"Female","birthdate":"1948-01-01","death_date":"2016-07-17","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Provisional Government of the Republic of New Afrika"],"in_custody":false,"released":true,"cases":[{"institution_name":"Metropolitan Correctional Center","institution_city":"New York","institution_state":"New York","charges":"Civil contempt of court — refusing to testify before a federal grand jury investigating the October 20, 1981 Brinks armored-car robbery in Nyack, New York. Initially charged in connection with the robbery itself, but cleared on alibi.","arrest_date":"1981-10-27","incarceration_date":"1981-10-27","release_date":"1983-10-19","sentence":"Approximately 18 months at MCC New York for grand-jury contempt","convicted":"Civil contempt; Brinks substantive charges dropped after alibi confirmed"}]}'

php artisan prisoner:add '{"name":"Oscar Washington","first_name":"Oscar","last_name":"Washington","description":"Oscar Washington was a member of the Black Panther Party and the Black Liberation Army. He was arrested on February 15, 1973 in connection with a federal seizure of a BLA weapons cache and charged with bank robbery — one of a series of BLA-attributed expropriations during the most intense phase of federal pursuit of the BLA underground following the 1971 split of the Black Panther Party. He served substantial time in federal prison for the conviction. The Jericho Movement lists him among its ancestor political prisoners. He died in 2016.","state":"New York","race":"Black","gender":"Male","birthdate":"1950-01-01","death_date":"2016-01-01","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Black Liberation Army"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Bank robbery in connection with a federal seizure of a Black Liberation Army weapons cache, February 15, 1973","arrest_date":"1973-02-15","incarceration_date":"1973-02-15","sentence":"Federal bank-robbery conviction; full sentence and exact release date pending verification against primary source","convicted":"Yes — federal court conviction"}]}'

echo
echo "Iya Fulani Sunni-Ali and Oscar Washington adds complete."
