#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_jafrc_and_hammett.sh
set -e

php artisan prisoner:add '{"name":"Lyman R. Bradley","first_name":"Lyman","middle_name":"R.","last_name":"Bradley","description":"Lyman Richard Bradley was a professor of German literature at New York University and the longtime treasurer of the Joint Anti-Fascist Refugee Committee, the U.S. organization that raised money for Spanish Republican refugees and other anti-fascists displaced by Nazi occupation. In 1946 the House Un-American Activities Committee subpoenaed JAFRCs records; Bradley and the rest of the board refused on First Amendment grounds and were cited for contempt of Congress.\n\nConvicted at trial in 1947 along with the other JAFRC officers, Bradley exhausted his appeals and served three months in 1950 at the federal prison camp at Mill Point, West Virginia. While he was incarcerated NYU dismissed him from his tenured professorship — a firing the American Association of University Professors formally censured the university for, but which NYU did not reverse. Bradley never taught again.","state":"New York","race":"White","gender":"Male","birthdate":"1898-01-01","death_date":"1973-01-01","ideologies":["Anti-fascist","First Amendment"],"affiliation":["Joint Anti-Fascist Refugee Committee","New York University"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Prison Camp, Mill Point","institution_city":"Mill Point","institution_state":"West Virginia","charges":"Contempt of Congress — refusing on First Amendment grounds to turn over Joint Anti-Fascist Refugee Committee records to the House Un-American Activities Committee","arrest_date":"1947-04-04","incarceration_date":"1950-06-09","release_date":"1950-09-09","sentence":"3 months federal prison; subsequently dismissed from his tenured NYU professorship","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Columbia, June 1947"}]}'

php artisan prisoner:add '{"name":"Dashiell Hammett","first_name":"Samuel","middle_name":"Dashiell","last_name":"Hammett","description":"Samuel Dashiell Hammett was the most influential American detective novelist of the twentieth century — the creator of the Continental Op, Sam Spade in The Maltese Falcon (1930), and Nick and Nora Charles in The Thin Man (1934). He was also a longtime member of the Communist Party USA, a U.S. Army veteran of two world wars (he enlisted at 48 in 1942 and served in the Aleutian Islands), and the longtime companion of playwright Lillian Hellman.\n\nIn 1946 Hammett accepted the role of trustee of the bail fund of the Civil Rights Congress, the CPUSA-aligned legal defense organization that posted bond for Smith Act defendants. When four of the original Dennis 11 defendants jumped bail in July 1951, Hammett was subpoenaed before the U.S. District Court in New York and ordered to identify the contributors to the bail fund. He refused, asserting that he did not know the contributors names and that even if he did he would not provide them. He was held in civil contempt and sentenced to six months in federal prison.\n\nHammett served his sentence at the Federal Correctional Institution camp at Ashland, Kentucky in 1951, where his health collapsed. After his release the IRS pursued him for back taxes for the rest of his life. He was blacklisted from publishing, magazine, and screenwriting work and never wrote another novel. He died of lung cancer in 1961, age 66, and was buried at Arlington National Cemetery as a U.S. Army veteran over the objection of J. Edgar Hoover.","state":"New York","race":"White","gender":"Male","birthdate":"1894-05-27","death_date":"1961-01-10","ideologies":["Communism","First Amendment"],"affiliation":["Communist Party USA","Civil Rights Congress","U.S. Army (WWI and WWII)"],"in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution, Ashland","institution_city":"Ashland","institution_state":"Kentucky","charges":"Civil contempt of court — refusing to name the contributors to the Civil Rights Congress bail fund after four Smith Act defendants jumped bail in July 1951","arrest_date":"1951-07-09","incarceration_date":"1951-07-09","release_date":"1951-12-09","sentence":"6 months federal prison","convicted":"Yes — civil contempt order, U.S. District Court for the Southern District of New York, July 1951"}]}'

echo
echo "JAFRC + Hammett adds complete."
