#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_jericho_round2.sh
#
# Adds 6 more political prisoners verified against Jericho Movement
# profile pages. Skips 3 Jericho board members who are organizers, not
# themselves imprisoned (Iyaluua Ferguson, Frank Velgara, Abduljabbar
# Caliph).
set -e

# ============================================================
# Williamsburg 4 — January 18, 1973 Brooklyn case
# ============================================================

php artisan prisoner:add '{"name":"Salih Ali Abdullah","first_name":"Salih","middle_name":"Ali","last_name":"Abdullah","description":"Salih Ali Abdullah is one of the four young Sunni Muslim men who became known as the Williamsburg Four after a January 18, 1973 attempt to take guns and ammunition from John and Als Sporting Goods at Broadway and Melrose Street in the Bushwick section of Brooklyn. The four — Shuaib Abdur Raheem, Dawud Abdur Rahman, Yusuf A. Mussadiq, and Salih Ali Abdullah — entered the store with the intention of acquiring weapons to defend Sunni Muslim communities in New York after the same days murders of seven Sunni Muslims in Washington, D.C. by members of the Nation of Islam in what became known as the Hanafi Massacre.\n\nA store patron alerted police, and the New York Police Department arrived in massive force. The four men attempted to surrender almost immediately, but were fired on as they came out the back door and forced back inside. The siege lasted nearly forty-eight hours. During the police barrage one NYPD officer, Stephen Gilroy, was killed and two others were wounded — by police gunfire, the defense argued and witnesses inside the store later corroborated. The four eventually negotiated a peaceful surrender. They were convicted in June 1974 of the murder of Officer Gilroy and sentenced to twenty-five years to life.\n\nFifty-plus years later, Salih Ali Abdullah is still incarcerated at the Auburn Correctional Facility in upstate New York under New York Department of Corrections inmate number 74-A-2614 — making him one of the longest-held political prisoners in the United States. The Jericho Movement lists him among its ancestor / current political prisoners. (Co-defendant Yusuf A. Mussadiq was released on medical parole in 1998 after a stroke and died in 2003. Shuaib Abdur Raheem was released on parole in July 2010 after 35 years. Dawud Abdur Rahman was released on parole in 2017.)","state":"New York","race":"Black","gender":"Male","ideologies":["Sunni Islam","Black community self-defense"],"affiliation":["Williamsburg 4"],"inmate_number":"74-A-2614","in_custody":true,"released":false,"cases":[{"institution_name":"Auburn Correctional Facility","institution_city":"Auburn","institution_state":"New York","charges":"Murder of NYPD Officer Stephen Gilroy during a forty-eight-hour police siege of John and Als Sporting Goods, Bushwick, Brooklyn — the defense argued and witnesses inside the store later confirmed that Officer Gilroy was killed by NYPD gunfire, not by the defendants","arrest_date":"1973-01-19","incarceration_date":"1973-01-19","sentence":"25 years to life — still incarcerated more than 50 years later","convicted":"Yes — New York state jury verdict, June 1974"}]}'

php artisan prisoner:add '{"name":"Dawud Abdur Rahman","first_name":"Dawud","last_name":"Abdur Rahman","description":"Dawud Abdur Rahman is one of the four young Sunni Muslim men known as the Williamsburg Four. On January 18, 1973 — the same day that members of the Nation of Islam murdered seven Sunni Muslims, including children, at the Washington, D.C. home of Hamaas Abdul Khaalis (the Hanafi Massacre) — Dawud, Shuaib Abdur Raheem, Yusuf A. Mussadiq, and Salih Ali Abdullah entered John and Als Sporting Goods in Bushwick, Brooklyn with the intention of acquiring weapons to defend their community. A store patron alerted the NYPD, who surrounded the store in massive force. The four attempted to surrender almost immediately but were fired on and forced back inside. The siege lasted nearly forty-eight hours. NYPD Officer Stephen Gilroy was killed in the police barrage; the defense argued the fatal shot came from police, not the defendants. The four ultimately negotiated a peaceful surrender.\n\nThey were convicted in June 1974 of Officer Gilroys murder and sentenced to twenty-five years to life. Dawud Abdur Rahman was held at the Clinton Correctional Facility in Dannemora, New York under inmate number 74-A-2616. He was released on parole in October 2017, after more than forty-four years in prison. The Jericho Movement lists him among its freed political prisoners.","state":"New York","race":"Black","gender":"Male","ideologies":["Sunni Islam","Black community self-defense"],"affiliation":["Williamsburg 4"],"inmate_number":"74-A-2616","in_custody":false,"released":true,"cases":[{"institution_name":"Clinton Correctional Facility","institution_city":"Dannemora","institution_state":"New York","charges":"Murder of NYPD Officer Stephen Gilroy during the January 1973 Bushwick police siege","arrest_date":"1973-01-19","incarceration_date":"1973-01-19","release_date":"2017-10-15","sentence":"25 years to life; paroled October 2017 after 44 years","convicted":"Yes — New York state jury verdict, June 1974"}]}'

# ============================================================
# Politicized Prisoners — Jailhouse Lawyers Speak / NALC / NABPP
# ============================================================

php artisan prisoner:add '{"name":"Sundiata Jawanza","first_name":"Darvin","last_name":"Allen","aka":"Sundiata Jawanza","description":"Sundiata Jawanza, born Darvin Allen, has been imprisoned in the South Carolina state prison system since 1995, serving a life sentence for murder and accessory after the fact of armed robbery. He has expressed remorse for the offenses of his youth and during his three decades inside has become one of the most consequential prison-rights organizers in the United States.\n\nHe is a founder of Jailhouse Lawyers Speak, the prisoner-led network that since 2018 has organized national prison work strikes and the Free Alabama Movement-style campaigns against forced prison labor. He is Co-Chair of the National Lawyers Guild Mass Incarceration Committee and the Mass Defense Committee, and the Jailhouse Lawyer Vice President on the NLGs National Executive Committee. He is also an Imam who serves as the spiritual guide for the Muslim population in his facility, and a certified peer support specialist who teaches substance-use and mental-health classes inside.\n\nSouth Carolina prison authorities have responded to his organizing by holding him in closed custody. In April 2023 he was transferred to the Turbeville Correctional Institution to complete the Addiction Treatment Unit program in support of his parole eligibility. The Jericho Movement classifies him as a politicized prisoner — a person originally incarcerated for ordinary criminal charges who has become a political prisoner through subsequent organizing inside.","state":"South Carolina","race":"Black","gender":"Male","ideologies":["Prison abolition","Islam"],"affiliation":["Jailhouse Lawyers Speak","National Lawyers Guild Mass Incarceration Committee"],"inmate_number":"00233800","in_custody":true,"released":false,"cases":[{"institution_name":"Turbeville Correctional Institution","institution_city":"Turbeville","institution_state":"South Carolina","charges":"Murder; accessory after the fact of armed robbery","arrest_date":"1995-01-01","incarceration_date":"1995-01-01","sentence":"Life","convicted":"Yes — South Carolina state conviction, 1995"}]}'

php artisan prisoner:add '{"name":"Kwame Shakur","first_name":"Kwame","last_name":"Shakur","aka":"Kwame Beans Shakur","description":"Kwame Beans Shakur is the Chairman and Co-Founder of the New Afrikan Liberation Collective and National Director of the Prison Lives Matter Movement. He is held in the Indiana Department of Correction under inmate number 149677 and has been in solitary confinement for 23 to 24 hours a day for more than six years.\n\nHe was arrested in 2011 in Terre Haute, Indiana — his hometown and the city where his grandfather, Robert Joyner Sr., had been one of the leading 1960s and 1970s Black liberation organizers and a co-founder of what is now the Booker T. Washington Community Center. Indiana State Police, U.S. Marshals, and SWAT surrounded his fathers house with snipers and an armored vehicle. After a brief standoff he came out and was held for 33 days before being charged with the double homicide of two white men. He maintains his innocence; the only physical evidence seized in the warrantless search were the firearms that had belonged to his late grandfather. The prosecution introduced his street-organization (Growth and Development) affiliation extensively at trial. He was convicted and sentenced to 110 years.\n\nIn 2014, after being introduced by Comrade Shaka Shakur (also in this database) at the Pendleton Correctional Facility to the work of Sanyika Shakur and Jalil Muntaqim, he became a New Afrikan revolutionary nationalist. With Shaka Shakur he co-founded the New Afrikan Liberation Collective. The Jericho Movement classifies him as a politicized prisoner.","state":"Indiana","race":"Black","gender":"Male","ideologies":["New Afrikan Independence","Prison abolition"],"affiliation":["New Afrikan Liberation Collective","Prison Lives Matter"],"inmate_number":"149677","in_custody":true,"released":false,"cases":[{"institution_name":"Miami Correctional Facility","institution_city":"Bunker Hill","institution_state":"Indiana","charges":"Double homicide","arrest_date":"2011-01-01","incarceration_date":"2011-01-01","sentence":"110 years; held in solitary confinement 23–24 hours per day for political organizing inside","convicted":"Yes — Indiana state conviction"}]}'

php artisan prisoner:add '{"name":"Joseph Shine White Stewart","first_name":"Joseph","last_name":"Stewart","aka":"Shine White","description":"Joseph Shine White Stewart, North Carolina Department of Public Safety inmate number 0802041, has been incarcerated in the North Carolina state prison system for sixteen years. Originally entering prison as what he describes as a former street tribe member, he was politicized inside through the writings of George Jackson and the broader New Afrikan Independence Movement tradition; he became National Spokesperson of the New Afrikan Black Panther Party-Prison Chapter (NABPP-PC) and is a former leader of the White Panther Organization.\n\nHis political work inside has focused on raising the political consciousness of white prisoners in particular, attempting to counter the white-supremacist organizing that dominates U.S. prison yards and to confront the divide-and-conquer strategies that pit white, Black, and other prisoners of color against each other. In recent years he has lost much of his outside support network because of internal movement disputes — including his condemnation of another prisoner-organizer he believed to be an informant, a split inside the NABPP, and his identification with the writings of James Yaki Sayles, which some movement participants have considered taboo for a white organizer to claim. The Jericho Movement classifies him as a politicized prisoner.","state":"North Carolina","race":"White","gender":"Male","ideologies":["Prison abolition","New Afrikan Independence"],"affiliation":["New Afrikan Black Panther Party-Prison Chapter","White Panther Organization"],"inmate_number":"0802041","in_custody":true,"released":false,"cases":[{"institution_name":"Granville Correctional Institution","institution_city":"Phoenix","institution_state":"North Carolina","charges":"North Carolina state conviction (specifics pending verification); has served 16 years","arrest_date":"2008-01-01","incarceration_date":"2008-01-01","sentence":"North Carolina state prison sentence","convicted":"Yes — North Carolina state conviction"}]}'

# ============================================================
# Masai Ehehosi — former BLA prisoner of war
# ============================================================

php artisan prisoner:add '{"name":"Masai Ehehosi","first_name":"Masai","last_name":"Ehehosi","description":"Masai Ehehosi was a former Black Liberation Army prisoner of war who, after his release, became Co-Minister of Information of the Provisional Government of the Republic of New Afrika and a founding member of Critical Resistance, the abolitionist organization committed to dismantling the prison-industrial complex. A Sunni Muslim, he worked through the Prison and Gang Program of Al-Ummah and the Imam Jamil (Al-Amin) Action Network. He focused his later organizing on the federal Communications Management Units and other administrative-segregation control units, and worked with the Jericho Medical Project on behalf of state and federal political prisoners. The Jericho Movement lists him among its ancestor political prisoners. Specific case background — including his BLA-era arrest and sentence — is pending verification against primary source.","state":null,"race":"Black","gender":"Male","ideologies":["Black Liberation","New Afrikan Independence","Sunni Islam","Prison abolition"],"affiliation":["Black Liberation Army","Provisional Government of the Republic of New Afrika","Critical Resistance","Al-Ummah","Imam Jamil Action Network","Jericho Medical Project"],"in_custody":false,"released":true,"cases":[{"charges":"Black Liberation Army-era arrest and conviction; specific case background pending verification","sentence":"Federal/state prison time as a former BLA POW","convicted":"Yes — case specifics pending verification"}]}'

# ============================================================
# Skipped — Jericho leadership not themselves imprisoned:
#   Iyaluua Ferguson — wife of Herman Ferguson; lived in voluntary
#     exile in Guyana with him but never herself jailed
#   Frank Velgara — Jericho co-chair (deceased); no bio published
#   Abduljabbar Caliph — Maryland Jericho organizer; not himself imprisoned
# ============================================================

echo
echo "All 6 Jericho round-2 adds complete."
