#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round20_brandeis_weather_harris.sh
#
# Source clusters:
#   - Brandeis bank robbery (Sept 23 1970 Boston bank robbery + killing
#     of Officer Walter Schroeder by William Gilday; 5 defendants)
#   - Weather Underground surrender period (1980-81 - Bernardine Dohrn,
#     Cathy Wilkerson, Bill Ayers; Boudin and Gilbert already in DB)
#   - David Harris - principal Vietnam draft-resistance organizer; 20
#     months federal 1969-71
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Brandeis bank robbery / Boston, Sept 23 1970 ===

php artisan prisoner:add '{"name":"Susan Saxe","first_name":"Susan","middle_name":"Edith","last_name":"Saxe","description":"Susan Edith Saxe was a 21-year-old Brandeis University student in 1970 and one of the principal organizers of a small anti-war affinity group that planned to fund underground militant action through bank robberies. On September 20, 1970 she and Katherine Ann Power were among five who carried out an armed raid on the Newburyport, Massachusetts National Guard armory; on September 23, 1970 they participated in an armed robbery of a State Street Bank branch in the Brighton neighborhood of Boston in which co-defendant William Gilday shot Boston Police Officer Walter Schroeder in the back as he responded to the call.\n\nShe went underground after the robbery and was placed on the FBI Most Wanted list on October 17, 1970 — one of the first U.S. women on the list. She was captured in Philadelphia on March 27, 1975 and was convicted of bank robbery, manslaughter, and conspiracy. She served five years in Massachusetts state prison; she was released in 1982. After her release she became a longtime Philadelphia Jewish-feminist organizer and the executive director of the Bread and Roses Community Fund.","state":"Massachusetts","race":"White","gender":"Female","birthdate":"1949-10-19","ideologies":["Anti-war","Lesbian feminism","Anti-imperialist"],"affiliation":[],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Massachusetts Department of Corrections","institution_state":"Massachusetts","charges":"Massachusetts state bank robbery, manslaughter, and conspiracy - September 23, 1970 State Street Bank robbery in Boston in which Officer Walter Schroeder was killed; September 20, 1970 Newburyport armory raid","arrest_date":"1975-03-27","incarceration_date":"1975-03-27","release_date":"1982-05-15","sentence":"5 years Massachusetts state prison","convicted":"Yes - guilty plea, Massachusetts Superior Court, 1976"}]}' || true

php artisan prisoner:add '{"name":"Katherine Ann Power","first_name":"Katherine","middle_name":"Ann","last_name":"Power","description":"Katherine Ann Power was a 21-year-old Brandeis University student and Susan Saxes co-defendant in the September 1970 Brighton MA bank robbery and the September 1970 Newburyport armory raid. She went underground immediately after the robbery and lived as Alice Louise Metzinger in Lebanon, Oregon for the next 23 years — building a life as a restaurant owner, mother, and activist before she negotiated a surrender on September 15, 1993. She pleaded guilty to manslaughter and armed robbery and was sentenced to 8 to 12 years in Massachusetts state prison; she was paroled on October 6, 1999 after 6 years.","state":"Massachusetts","race":"White","gender":"Female","birthdate":"1949-04-25","ideologies":["Anti-war"],"affiliation":[],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Massachusetts Department of Corrections","institution_state":"Massachusetts","charges":"Massachusetts state manslaughter and armed robbery - September 23, 1970 State Street Bank robbery in Boston in which Officer Walter Schroeder was killed; September 20, 1970 Newburyport armory raid","arrest_date":"1993-09-15","incarceration_date":"1993-09-15","release_date":"1999-10-06","sentence":"8-12 years Massachusetts state prison; paroled after 6 years","convicted":"Yes - guilty plea, Massachusetts Superior Court, 1993"}]}' || true

# === Weather Underground (Boudin, Gilbert, Buck, Evans, Rosenberg, Whitehorn already in DB) ===

php artisan prisoner:add '{"name":"Bernardine Dohrn","first_name":"Bernardine","last_name":"Dohrn","description":"Bernardine Rae Dohrn was a leader of the Weather Underground and one of the most senior public figures of the 1970s U.S. New Left underground. She was on the FBI Most Wanted list from 1970 to 1973. She and her partner Bill Ayers turned themselves in to federal authorities on December 3, 1980 in Chicago. Most of the federal charges against her were dropped because of governmental misconduct revealed by FBI COINTELPRO disclosures (the same misconduct that destroyed the Pentagon Papers prosecution). She pleaded guilty to misdemeanor charges of aggravated battery and bail-jumping for which she was placed on probation. She has subsequently been a longtime Northwestern University Pritzker School of Law clinical professor (until 2013) and Director of the Northwestern Childrens and Family Justice Center.","state":"Illinois","race":"White","gender":"Female","birthdate":"1942-01-12","ideologies":["Anti-imperialist","Anti-racist","New Left"],"affiliation":["Weather Underground","Students for a Democratic Society","Northwestern University"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"(no extended incarceration; brief surrender custody)","charges":"Federal charges from Weather Underground 1969-77 actions - most dropped for FBI COINTELPRO misconduct; Illinois state misdemeanor aggravated battery and bail-jumping","arrest_date":"1980-12-03","incarceration_date":"1980-12-03","release_date":"1980-12-03","sentence":"Probation only","convicted":"Misdemeanor only - guilty plea, December 1980"}]}' || true

php artisan prisoner:add '{"name":"Cathy Wilkerson","first_name":"Cathlyn","middle_name":"Platt","last_name":"Wilkerson","aka":"Cathy Wilkerson","description":"Cathlyn Platt Wilkerson was a Weather Underground organizer and one of the two surviving members of the March 6, 1970 Greenwich Village townhouse explosion in which her three Weather Underground comrades — Diana Oughton, Ted Gold, and Terry Robbins — were killed while assembling a bomb. The townhouse was the home of her father James Wilkerson, an advertising executive away on a Caribbean vacation. She fled the scene and lived underground for ten years. She surrendered on July 8, 1980 in Chicago and pleaded guilty to unlawful possession of dynamite. She was sentenced to up to three years in prison and served 11 months. After release she became a longtime New York City math educator.","state":"New York","race":"White","gender":"Female","birthdate":"1945-08-25","ideologies":["Anti-imperialist","Anti-racist","New Left"],"affiliation":["Weather Underground","Students for a Democratic Society"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"New York Department of Corrections","institution_state":"New York","charges":"New York state unlawful possession of dynamite - aftermath of March 6, 1970 Greenwich Village townhouse explosion in which 3 Weather Underground members died assembling a bomb","arrest_date":"1980-07-08","incarceration_date":"1981-01-15","sentenced_date":"1980-12-19","release_date":"1981-12-15","sentence":"Up to 3 years; served 11 months","convicted":"Yes - guilty plea, New York state, December 1980"}]}' || true

# === David Harris ===

php artisan prisoner:add '{"name":"David Harris","first_name":"David","last_name":"Harris","description":"David Victor Harris was Stanford University student body president 1966-67 and the principal U.S. organizer of the Resistance, the late-1960s draft-card-turn-in movement that would also produce the Catonsville 9, Milwaukee 14, and Camden 28 actions. He was indicted in 1968 for refusing to submit to induction. After exhausting appeals he was taken into federal custody on July 16, 1969 — three days before the Apollo 11 moon landing — by federal marshals at his and his wife Joan Baezs home in the Santa Cruz Mountains. He was held briefly at the San Francisco County Jail, then for seven months at the Federal Prison Camp at Safford, Arizona, and for 12 months at FCI La Tuna, Texas.\n\nHe served 20 months of a 3-year sentence, including 3 months in solitary confinement for organizing inside, before his release in March 1971. Joan Baez was pregnant at the time of his arrest; their son Gabriel was born December 1969 while he was incarcerated. After his release he became a longtime journalist at Rolling Stone and The New York Times Magazine. He died on February 8, 2023.","state":"California","race":"White","gender":"Male","birthdate":"1946-02-03","death_date":"2023-02-08","ideologies":["Anti-war","Pacifism"],"affiliation":["The Resistance","Stanford University"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (San Francisco / Safford / La Tuna)","institution_state":"Texas","charges":"Federal refusal to submit to a lawful order of induction (Selective Service Act of 1948)","arrest_date":"1969-07-16","incarceration_date":"1969-07-16","release_date":"1971-03-15","sentence":"3 years federal prison; served 20 months","convicted":"Yes - federal conviction, Northern District of California, 1968"}]}' || true

# === Eldridge Cleaver ===

php artisan prisoner:add '{"name":"Eldridge Cleaver","first_name":"Leroy","middle_name":"Eldridge","last_name":"Cleaver","description":"Leroy Eldridge Cleaver was the Minister of Information of the Black Panther Party and the author of Soul on Ice (1968), one of the foundational texts of late-1960s Black liberation prose. He had been incarcerated in California state prison for assault and rape from 1958 to 1966 (Soledad and San Quentin), where he was politicized by Malcolm X and Black Muslim organizing inside; on parole in 1966 he became Editor of Ramparts magazine and joined the BPP at its founding. On April 6, 1968 — two days after the assassination of Martin Luther King Jr. — he was wounded and BPP Treasurer Bobby Hutton was killed in a 90-minute Oakland Police Department gunfight at the BPP Oakland office. He was rearrested for the parole violation and held at Vacaville state hospital pending parole-revocation hearings. On November 27, 1968 — the night before he was scheduled to surrender to a return to state prison — he jumped bail and fled to Cuba, then Algeria. He lived in exile in Algeria, France, and other countries for seven years before voluntarily returning to the United States in November 1975 and surrendering in San Francisco. He served brief time before pleading to assault, was sentenced to 1,200 hours of community service, and was released. He spent his last decades in evangelical Christian conservative organizing and died on May 1, 1998.","state":"California","race":"Black","gender":"Male","birthdate":"1935-08-31","death_date":"1998-05-01","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Ramparts magazine"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections / Federal Bureau of Prisons","institution_state":"California","charges":"California state 1958 assault and rape conviction (1958-66 incarceration); 1968 parole violation arising from April 6, 1968 BPP Oakland gunfight","arrest_date":"1968-04-06","incarceration_date":"1968-04-06","in_exile_since":"1968-11-27","end_of_exile":"1975-11-15","release_date":"1976-04-15","sentence":"State and federal sentences; 7 years in exile (Cuba, Algeria, France); 1976 community service","convicted":"Yes - California state convictions"}]}' || true

# === Sam Melville (Attica) ===

php artisan prisoner:add '{"name":"Sam Melville","first_name":"Sam","last_name":"Melville","aka":"Samuel Joseph Grossman","description":"Sam Melville, born Samuel Joseph Grossman in 1934, was a New York City anti-war activist who, with the small affinity group later known as the Sam Melville-Jonathan Jackson Unit, conducted a series of bombings of corporate, military, and government targets in New York City in the summer and fall of 1969 — the Marine Midland Bank, the Federal Office Building at Foley Square, the Whitehall Street Armed Forces Induction Center, the Standard Oil headquarters, the U.S. Army recruiting office in Pratt Park, the Chase Manhattan Bank, and the General Motors building. He was arrested on November 12, 1969 and pleaded guilty to federal sabotage and bombing charges; he was sentenced to 18 years in federal prison.\n\nHe was transferred to Attica Correctional Facility in New York state in 1970 and was one of the central organizers of the September 9, 1971 Attica Prison rebellion — the largest and most consequential prison uprising in U.S. history, in which 1,281 prisoners took control of the prison for four days demanding political and human-rights reforms. On September 13, 1971 New York Governor Nelson Rockefellers state police retook the prison by force. Melville was killed during the assault. He was 36. The 1971 song Sam Melville by Jeffrey Lewis is one of many cultural commemorations.","state":"New York","race":"White","gender":"Male","birthdate":"1934-11-13","death_date":"1971-09-13","ideologies":["Anti-imperialist","Anti-war","Prison abolition"],"affiliation":["Sam Melville-Jonathan Jackson Unit"],"era":"1970s","in_custody":false,"released":false,"cases":[{"institution_name":"Attica Correctional Facility","institution_city":"Attica","institution_state":"New York","charges":"Federal bombing and sabotage - 1969 New York City bombings of corporate and military targets","arrest_date":"1969-11-12","incarceration_date":"1969-11-12","death_in_custody_date":"1971-09-13","sentence":"18 years federal prison; killed in the September 13, 1971 New York State Police retaking of Attica","convicted":"Yes - federal guilty plea, U.S. District Court for the Southern District of New York, 1970"}]}' || true

echo
echo "Round 20 (Brandeis + Weather Underground + David Harris + Cleaver + Melville) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
