#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_panther_21_missing.sh
#
# Adds the 15 Panther 21 defendants who do not yet have prisoner
# records in the database. Already in DB and skipped:
#   - Afeni Shakur, Sundiata Acoli, Kuwasi Balagoon, Jamal Joseph,
#     Dhoruba bin Wahad, Sekou Odinga.
#
# History: On April 2, 1969 New York Police Department officers
# conducted predawn raids on Black Panther Party members in New York
# City and indicted 21 defendants on 156 counts of conspiracy to
# bomb police stations, the Bronx Botanical Garden, midtown
# department stores, and a railroad right-of-way. Bail was set at
# $100,000 per defendant - prohibitively high for nearly all of
# them. Most spent ~2 years in pretrial detention awaiting trial.
# After an 8-month trial the jury deliberated approximately 90
# minutes and acquitted all 13 defendants who went to trial of
# every count on May 13, 1971.
#
# Source notes: prosecution case relied on testimony of three
# undercover NYPD officers (Ralph White, Gene Roberts, Carlos
# Ashwood) who were ultimately found by jurors to have served as
# instigators rather than mere observers.
set -e

php artisan prisoner:add '{"name":"Lumumba Shakur","first_name":"Lumumba","last_name":"Shakur","aka":"Anthony Coston","description":"Lumumba Abdul Shakur, born Anthony Coston, was the section leader of the Harlem chapter of the Black Panther Party and the husband of Afeni Shakur. He was a lead defendant in the New York Panther 21 conspiracy case, arrested April 2, 1969 and held in the Manhattan House of Detention (the Tombs) on $100,000 bail through most of the pretrial period. He was acquitted along with 12 co-defendants on May 13, 1971 after a Manhattan jury rejected the conspiracy theory built largely on undercover NYPD testimony. He returned to organizing in the Northeast after the trial and later moved to North Carolina, where he died in 1986.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state conspiracy (156 counts) - charged with the other 20 defendants in the Panther 21 indictment of April 2, 1969 for an alleged plot to bomb NYPD precincts, the Bronx Botanical Garden, midtown department stores, and a railroad right-of-way. The prosecution case rested almost entirely on the testimony of three undercover NYPD officers; the jury deliberated approximately 90 minutes and acquitted all 13 defendants who went to trial of every count.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention at $100,000 bail; acquitted by jury verdict, New York Supreme Court, New York County, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Curtis Powell","first_name":"Curtis","last_name":"Powell","description":"Dr. Curtis Powell was an Oxford-trained biochemist and Black Panther Party member indicted as one of the New York Panther 21. Arrested April 2, 1969 in the predawn NYPD raids, he was held in the Manhattan House of Detention through most of the pretrial period on $100,000 bail. He was one of the 13 defendants who went to trial and was acquitted with the others on May 13, 1971. He returned to scientific research after the trial.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state conspiracy (156 counts) - Panther 21 indictment of April 2, 1969 for alleged plot to bomb NYPD precincts, the Bronx Botanical Garden, midtown department stores, and a railroad right-of-way.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury verdict, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Joan Bird","first_name":"Joan","last_name":"Bird","description":"Joan Bird was a 19-year-old nursing student and Black Panther Party member when she was arrested on January 17, 1969 in connection with a Harlem incident in which NYPD officers exchanged gunfire with three men in a car; she was beaten in custody and the photograph of her bruised face became one of the most widely circulated images of the case. She was charged in the April 2, 1969 Panther 21 indictment as one of two women among the defendants (the other was Afeni Shakur) and was held at the Womens House of Detention in Greenwich Village on $100,000 bail. She was one of the 13 defendants who went to trial and was acquitted with the others on May 13, 1971.","state":"New York","race":"Black","gender":"Female","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Womens House of Detention (Greenwich Village)","institution_city":"New York","institution_state":"New York","charges":"New York state attempted murder (Jan 17, 1969 Harlem police-shootout incident) and Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-01-17","incarceration_date":"1969-01-17","release_date":"1971-05-13","sentence":"~2 years pretrial detention at the Womens House of Detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Robert Collier","first_name":"Robert","last_name":"Collier","description":"Robert Steele Collier was a longtime Harlem-based revolutionary and one of the New York Panther 21. He had been one of the four 1965 Statue of Liberty plot defendants - a Black-Cuban solidarity action - and had served federal time before joining the Black Panther Party. He was arrested April 2, 1969, held in pretrial detention, and was one of the 13 defendants who went to trial and was acquitted on May 13, 1971. He continued tenant- and welfare-rights organizing in New York City for decades after.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation","Cuba solidarity"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Lonnie Epps","first_name":"Lonnie","last_name":"Epps","description":"Lonnie Epps was a teenage Black Panther Party member at the time of the April 2, 1969 Panther 21 raids. He was held in pretrial detention with the older defendants. The conspiracy charges against him were ultimately severed and dismissed before the case went to the jury, and he was released without conviction.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment); charges severed and ultimately dismissed without going to the jury.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"Pretrial detention; charges severed and dismissed.","convicted":"No - charges severed and dismissed without conviction"}]}' || true

php artisan prisoner:add '{"name":"Lee Berry","first_name":"Lee","last_name":"Berry","description":"Lee Berry was a Vietnam War veteran and Black Panther Party member who was hospitalized at Bronx Veterans Affairs hospital with severe epilepsy when NYPD took him into custody as one of the Panther 21 on April 2, 1969. His case was severed from the others on medical grounds, and the conspiracy charges were ultimately dismissed without his having stood trial.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment); charges severed on medical grounds and ultimately dismissed.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"Pretrial custody; charges severed and dismissed.","convicted":"No - charges severed (medical) and dismissed without conviction"}]}' || true

php artisan prisoner:add '{"name":"Thomas Berry","first_name":"Thomas","last_name":"Berry","description":"Thomas Berry was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. The charges against him were dropped before the case went to trial.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment); charges dropped before trial.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1969-12-31","sentence":"Pretrial custody; charges dropped before the case went to trial.","convicted":"No - charges dropped before trial"}]}' || true

php artisan prisoner:add '{"name":"Richard Harris","first_name":"Richard","last_name":"Harris","description":"Richard Harris was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. His case did not proceed to verdict with the 13 defendants who were acquitted on May 13, 1971; charges against him were severed or dropped earlier in the proceedings.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"Pretrial custody; case severed from the main 13-defendant trial.","convicted":"No - case severed from the main Panther 21 trial"}]}' || true

php artisan prisoner:add '{"name":"Ali Bey Hassan","first_name":"Ali","last_name":"Hassan","aka":"John J. Casson","description":"Ali Bey Hassan, born John J. Casson, was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. He was held in pretrial detention and was one of the 13 defendants who went to trial and was acquitted on May 13, 1971 after the jury rejected the prosecution case built on undercover NYPD testimony.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Michael Tabor","first_name":"Michael","last_name":"Tabor","aka":"Cetewayo","description":"Michael Cetewayo Tabor was a leading Harlem-based Black Panther Party theoretician and author of the influential 1970 BPP pamphlet Capitalism Plus Dope Equals Genocide. He was indicted as one of the New York Panther 21 on April 2, 1969 and held in pretrial detention before being released on bail. In February 1971, while the trial was still in session, he and co-defendant Richard Dhoruba Moore (later Dhoruba bin Wahad) jumped bail and fled the United States. Tabor settled in Algeria with the international section of the Black Panther Party and later in Zambia, where he died in 2010 having never returned to the U.S.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation","Pan-Africanism"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":false,"in_exile":true,"currently_in_exile":false,"death_date":"2010-10-25","cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment); fled to Algeria in February 1971 during trial.","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-02-08","in_exile_since":"1971-02-08","end_of_exile":"2010-10-25","sentence":"~22 months pretrial detention before release on bail; jumped bail Feb 1971 and fled to Algeria, then Zambia. Lived in exile until his death in Zambia, October 25, 2010.","convicted":"Convicted in absentia in New York after fleeing bail."}]}' || true

php artisan prisoner:add '{"name":"Lee Roper","first_name":"Lee","last_name":"Roper","description":"Lee Roper was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. He was one of the 13 defendants who went to trial and was acquitted on May 13, 1971.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Kwando Kinshasa","first_name":"Kwando","last_name":"Kinshasa","aka":"William King","description":"Kwando Kinshasa, born William King, was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. He was one of the 13 defendants who went to trial and was acquitted on May 13, 1971. He later became a professor of African-American studies and an author on incarceration and Black liberation.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Abayama Katara","first_name":"Abayama","last_name":"Katara","description":"Abayama Katara was the youngest of the New York Panther 21 defendants, a teenager at the time of his April 2, 1969 arrest. He was one of the 13 defendants who went to trial and was acquitted on May 13, 1971.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Baba Odinga","first_name":"Baba","last_name":"Odinga","description":"Baba Odinga was a Black Panther Party member indicted in the April 2, 1969 New York Panther 21 conspiracy case. He was one of the 13 defendants who went to trial and was acquitted on May 13, 1971.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment).","arrest_date":"1969-04-02","incarceration_date":"1969-04-02","release_date":"1971-05-13","sentence":"~2 years pretrial detention; acquitted by jury, May 13, 1971.","convicted":"No - acquitted by jury, New York Supreme Court, May 13, 1971"}]}' || true

php artisan prisoner:add '{"name":"Larry Mack","first_name":"Larry","last_name":"Mack","description":"Larry Mack was the section leader of the Queens chapter of the Black Panther Party at the time of the April 2, 1969 Panther 21 raids. He went underground rather than surrender and was a fugitive defendant in the conspiracy case.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Panther 21"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Manhattan House of Detention (the Tombs)","institution_city":"New York","institution_state":"New York","charges":"New York state Panther 21 conspiracy counts (April 2, 1969 indictment); avoided arrest in the initial sweeps and lived underground.","arrest_date":"1969-04-02","sentence":"Fugitive defendant; case did not proceed to trial against him as a present defendant.","convicted":"No - fugitive at time of trial"}]}' || true

echo
echo "Panther 21 (15 missing) add complete."
