#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round14_chicago7_rnc8_camden28.sh
#
# Source clusters:
#   - Chicago 7 / Chicago 8 (1968-1969 federal trial for crossing state
#     lines to incite a riot at the 1968 DNC; Bobby Seale severed after
#     being bound and gagged in court; convictions reversed 1972)
#   - RNC 8 (Aug 30 2008 Minneapolis raids in advance of Republican
#     National Convention; only Erik Oseland served actual jail time)
#   - Camden 28 (Aug 22 1971 Camden NJ draft board raid; brief pretrial
#     detention; jury acquittal May 20 1973 - referendum on Vietnam War)
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Chicago 7 / Chicago 8 ===

php artisan prisoner:add '{"name":"Bobby Seale","first_name":"Bobby","last_name":"Seale","description":"Bobby Seale, born Robert George Seale in Liberty, Texas in 1936, was the co-founder with Huey P. Newton of the Black Panther Party for Self-Defense in Oakland, California in October 1966 and the partys lifelong national chairman. He was the eighth defendant in what was originally the Chicago 8 federal trial — the federal prosecution under the 1968 Anti-Riot Act of organizers of the Chicago 1968 Democratic National Convention protests.\n\nSeale had spent only four hours in Chicago in August 1968, having flown in to substitute as a speaker. After being denied his choice of attorney (Charles Garry, who was undergoing surgery), he repeatedly demanded to represent himself. On October 29-30, 1969 Federal Judge Julius Hoffman ordered him bound and gagged at his courtroom seat in front of the jury — among the most disturbing images of the 1960s American legal record. On November 5, 1969 the judge severed his case from the others, sentenced him to four years for contempt of court, and declared a mistrial. He served two years on the contempt charges before the 1972 reversal. He was simultaneously prosecuted in New Haven for the May 1969 killing of Black Panther Party member Alex Rackley by other Panthers; the New Haven trial ended in a hung jury in May 1971 and the prosecution declined to retry him.","state":"Connecticut","race":"Black","gender":"Male","birthdate":"1936-10-22","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Chicago 8"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal Anti-Riot Act and contempt of court — Chicago 1968 DNC protests; bound and gagged in court October 1969","arrest_date":"1969-09-24","incarceration_date":"1969-11-05","release_date":"1972-04-01","sentence":"4 years contempt of court (later reversed on appeal); 2 years served","convicted":"Contempt only; reversed 1972"},{"institution_name":"Connecticut Correctional Center","institution_state":"Connecticut","charges":"Connecticut state murder of Alex Rackley (May 1969) — hung jury May 1971; prosecution declined to retry","arrest_date":"1969-08-19","incarceration_date":"1969-08-19","release_date":"1972-05-25","sentence":"Held in pretrial detention through the New Haven trial; no conviction","convicted":"No - hung jury, May 1971"}]}' || true

php artisan prisoner:add '{"name":"Tom Hayden","first_name":"Tom","last_name":"Hayden","description":"Thomas Emmett Hayden was a Students for a Democratic Society co-founder, the principal author of the 1962 Port Huron Statement that defined the early New Left, and one of the central organizers of the August 1968 Chicago Democratic National Convention protests. He was indicted in March 1969 along with seven other organizers in what became the Chicago 8 (later 7) prosecution. He was convicted on February 18, 1970 of crossing state lines with intent to incite a riot and sentenced to 5 years in federal prison and a $5,000 fine. The conviction was reversed by the Seventh Circuit in November 1972 on grounds of judicial bias by Judge Julius Hoffman. He served brief contempt-of-court time during the trial. He went on to a career as a California state legislator (1982-2000) and remained a public-intellectual figure of the U.S. left until his death on October 23, 2016.","state":"Illinois","race":"White","gender":"Male","birthdate":"1939-12-11","death_date":"2016-10-23","ideologies":["Anti-war","New Left","Democratic socialism"],"affiliation":["Students for a Democratic Society","Chicago 7"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act and contempt of court — 1968 Chicago DNC protests","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1972-11-21","sentence":"5 years federal prison + $5,000 fine; reversed by 7th Cir November 1972","convicted":"Yes (initial conviction February 18, 1970); reversed on appeal 1972"}]}' || true

php artisan prisoner:add '{"name":"Abbie Hoffman","first_name":"Abbie","last_name":"Hoffman","description":"Abbot Howard Abbie Hoffman was a co-founder of the Youth International Party (Yippies), a master of theatrical political protest, and one of the most prominent voices of the U.S. counterculture left. He was one of the Chicago 8 (later 7) defendants prosecuted for the 1968 Chicago DNC protests. He was convicted on February 18, 1970 of crossing state lines with intent to incite a riot and sentenced to 5 years in federal prison and a $5,000 fine. He served substantial contempt-of-court time during the 1969-70 trial proceedings. The conviction was reversed by the Seventh Circuit in 1972. He went underground in 1973 after a separate cocaine charge and lived under the alias Barry Freed for six years before voluntarily surrendering in 1980. He died of an apparent suicide on April 12, 1989, age 52.","state":"Illinois","race":"White","gender":"Male","birthdate":"1936-11-30","death_date":"1989-04-12","ideologies":["Anti-war","Counterculture","Yippie"],"affiliation":["Youth International Party","Chicago 7"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act and contempt of court — 1968 Chicago DNC protests","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1972-11-21","sentence":"5 years federal prison + $5,000 fine; reversed by 7th Cir November 1972","convicted":"Yes (initial conviction February 18, 1970); reversed on appeal 1972"}]}' || true

php artisan prisoner:add '{"name":"Jerry Rubin","first_name":"Jerry","last_name":"Rubin","description":"Jerry Clyde Rubin was a co-founder of the Youth International Party (Yippies), a leading anti-war activist, and one of the Chicago 8 (later 7) defendants. He was convicted on February 18, 1970 of crossing state lines with intent to incite a riot and sentenced to 5 years in federal prison and a $5,000 fine. He served 25 months of contempt sentences imposed by Judge Julius Hoffman during the trial proceedings. The substantive conviction was reversed by the Seventh Circuit in 1972 and the contempt convictions were reversed in 1973. He died from injuries sustained in a Los Angeles traffic accident on November 28, 1994, age 56.","state":"Illinois","race":"White","gender":"Male","birthdate":"1938-07-14","death_date":"1994-11-28","ideologies":["Anti-war","Counterculture","Yippie"],"affiliation":["Youth International Party","Chicago 7"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act and contempt of court — 1968 Chicago DNC protests","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1972-11-21","sentence":"5 years federal prison + $5,000 fine + 25 months contempt; all reversed by 7th Cir","convicted":"Yes (initial conviction February 18, 1970); reversed on appeal 1972-73"}]}' || true

php artisan prisoner:add '{"name":"David Dellinger","first_name":"David","last_name":"Dellinger","description":"David Dellinger was the senior anti-war activist of the Chicago 8 defendants, a Yale-educated, Quaker-influenced pacifist who had served three years in federal prison during World War II for refusing the draft. He was the chairman of the National Mobilization Committee to End the War in Vietnam (Mobe) and the principal coordinator of the August 1968 Chicago DNC protests. He was convicted on February 18, 1970 of crossing state lines with intent to incite a riot and sentenced to 5 years in federal prison. He served substantial contempt-of-court time during the trial. The substantive conviction was reversed by the Seventh Circuit in 1972. He died on May 25, 2004, age 88.","state":"Illinois","race":"White","gender":"Male","birthdate":"1915-08-22","death_date":"2004-05-25","ideologies":["Anti-war","Pacifism","Christian socialism"],"affiliation":["Chicago 7","National Mobilization Committee to End the War in Vietnam"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons","charges":"WWII federal draft refusal (1943); Chicago 8 federal Anti-Riot Act and contempt of court (1969-72)","arrest_date":"1943-08-15","incarceration_date":"1943-08-15","release_date":"1972-11-21","sentence":"3 years WWII draft refusal (served); 5 years Chicago 8 (reversed 1972)","convicted":"Yes for WWII draft refusal; Chicago 8 conviction reversed on appeal"}]}' || true

php artisan prisoner:add '{"name":"Rennie Davis","first_name":"Rennie","last_name":"Davis","description":"Rennard Cordon Davis was a Students for a Democratic Society organizer and the project director for the National Mobilization Committee to End the War in Vietnam at the August 1968 Chicago DNC protests. He was one of the Chicago 8 (later 7) defendants. He was convicted on February 18, 1970 of crossing state lines with intent to incite a riot and sentenced to 5 years in federal prison. He served brief contempt time during the trial. The substantive conviction was reversed by the Seventh Circuit in 1972. He died on February 2, 2021, age 80.","state":"Illinois","race":"White","gender":"Male","birthdate":"1940-05-23","death_date":"2021-02-02","ideologies":["Anti-war","New Left"],"affiliation":["Students for a Democratic Society","Chicago 7","National Mobilization Committee to End the War in Vietnam"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act and contempt of court — 1968 Chicago DNC protests","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1972-11-21","sentence":"5 years federal prison; reversed by 7th Cir November 1972","convicted":"Yes (initial conviction February 18, 1970); reversed on appeal 1972"}]}' || true

php artisan prisoner:add '{"name":"John Froines","first_name":"John","last_name":"Froines","description":"John Robert Froines was a chemistry professor at the University of Oregon and one of the Chicago 8 (later 7) defendants. He was acquitted of the substantive Anti-Riot Act charge but convicted of contempt of court. The contempt convictions were reversed by the Seventh Circuit in 1973.","state":"Illinois","race":"White","gender":"Male","birthdate":"1939-06-13","ideologies":["Anti-war","New Left"],"affiliation":["Chicago 7"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act (acquitted) and contempt of court — 1968 Chicago DNC protests","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1973-04-01","sentence":"Contempt only; reversed by 7th Cir 1973","convicted":"Acquitted on Anti-Riot Act; contempt only, reversed on appeal"}]}' || true

php artisan prisoner:add '{"name":"Lee Weiner","first_name":"Lee","last_name":"Weiner","description":"Lee Weiner was a sociology graduate student at Northwestern University and one of the Chicago 8 (later 7) defendants. He was acquitted of the substantive Anti-Riot Act charge — specifically of teaching demonstrators how to construct incendiary devices — but convicted of contempt of court. The contempt convictions were reversed by the Seventh Circuit in 1973. He was a longtime Anti-Defamation League executive and human-rights organizer in the decades following the Chicago 7 trial. He died on March 20, 2024.","state":"Illinois","race":"White","gender":"Male","death_date":"2024-03-20","ideologies":["Anti-war","New Left"],"affiliation":["Chicago 7"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (briefly during trial)","charges":"Federal Anti-Riot Act and teaching incendiary-device construction (acquitted) and contempt of court","arrest_date":"1969-03-20","incarceration_date":"1969-03-20","release_date":"1973-04-01","sentence":"Contempt only; reversed by 7th Cir 1973","convicted":"Acquitted on Anti-Riot Act and incendiary-device counts; contempt only, reversed on appeal"}]}' || true

# === RNC 8 — only Erik Oseland served jail time ===

php artisan prisoner:add '{"name":"Erik Oseland","first_name":"Erik","last_name":"Oseland","description":"Erik Oseland was a member of the RNC Welcoming Committee, an anarchist/anti-authoritarian collective that organized in advance of the September 2008 Republican National Convention in St. Paul, Minnesota. He was one of eight RNCWC members arrested in raids on August 29-30, 2008 and charged with felonies including first-degree damage to property, second-degree conspiracy to riot, and conspiracy to riot in furtherance of terrorism — the most serious charges, the terrorism enhancement, were later dropped. After the prosecution dropped the terrorism count he pleaded guilty on August 27, 2010 to gross-misdemeanor conspiracy to commit damage to property, and was sentenced to 91 days in the Ramsey County Workhouse. He was the only RNC 8 defendant to serve actual incarceration time. The case is widely cited as one of the most aggressive uses of state-terrorism statutes against U.S. protesters in the post-9/11 era.","state":"Minnesota","race":"White","gender":"Male","ideologies":["Anarchism","Anti-war"],"affiliation":["RNC Welcoming Committee","RNC 8"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Ramsey County Workhouse","institution_city":"Saint Paul","institution_state":"Minnesota","charges":"Minnesota state gross-misdemeanor conspiracy to commit damage to property — 2008 Republican National Convention; Minnesota state terrorism enhancement dropped","arrest_date":"2008-08-30","incarceration_date":"2010-10-20","sentenced_date":"2010-08-27","release_date":"2011-01-19","sentence":"91 days Ramsey County Workhouse","convicted":"Yes — guilty plea, Minnesota state gross misdemeanor, August 27, 2010"}]}' || true

# === Camden 28 — most prominent figures ===

php artisan prisoner:add '{"name":"Howard Zinn (Camden 28 expert witness)","first_name":"Howard","last_name":"Zinn","description":"Howard Zinn was a historian, World War II combat veteran (B-17 bombardier in Europe), and longtime Boston University professor whose Peoples History of the United States (1980) is one of the most widely read works of U.S. radical history. He was the principal academic expert witness for the Camden 28 defense at their 1973 federal trial in U.S. District Court in Camden, New Jersey. He was not a defendant; he is included in the database as the most public face of the political-prisoner-defense scholarly community of the 1960s-70s and as an arrest-record participant in numerous civil-disobedience actions, including a 1971 arrest at a U.S. Capitol anti-war demonstration. He died on January 27, 2010, age 87.","state":"New Jersey","race":"White","gender":"Male","birthdate":"1922-08-24","death_date":"2010-01-27","ideologies":["Anti-war","Marxist","Civil rights"],"affiliation":["Boston University","SNCC","Vietnam Veterans Against the War"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"(brief detentions; no extended incarceration)","charges":"Multiple civil-disobedience arrests including 1971 U.S. Capitol anti-war demonstration","arrest_date":"1971-05-05","sentence":"Brief detentions, never long incarceration; principal expert witness for Camden 28 (1973 acquittal)","convicted":"No major conviction"}]}' || true

php artisan prisoner:add '{"name":"Father Michael Doyle","first_name":"Michael","last_name":"Doyle","description":"Father Michael Doyle was an Irish-born Catholic priest of the Diocese of Camden, New Jersey, longtime pastor at Sacred Heart Church in South Camden, and one of the Camden 28 defendants. He was one of more than twenty defendants arrested in the early hours of August 22, 1971 during the FBI surveillance and capture of the Camden draft-board raid in progress. He spent brief pretrial detention after the arrest, and the case proceeded to trial in spring 1973 in U.S. District Court for the District of New Jersey. On May 20, 1973 a Camden federal jury acquitted all 28 defendants on all counts — the first complete legal victory for the anti-war movement after dozens of Catholic Left draft-board actions. He went on to a 50-year ministry in South Camden focused on housing, food access, and immigrant rights. He died on November 23, 2022, age 88.","state":"New Jersey","race":"White","gender":"Male","death_date":"2022-11-23","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Camden 28","Sacred Heart Church (Camden)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"(brief pretrial detention; acquitted at trial)","institution_state":"New Jersey","charges":"Federal conspiracy and destruction of government property — August 22, 1971 Camden NJ draft-board raid","arrest_date":"1971-08-22","incarceration_date":"1971-08-22","release_date":"1973-05-20","sentence":"Brief pretrial detention; acquitted at trial","convicted":"No — federal jury acquittal on all counts, U.S. District Court for the District of New Jersey, May 20, 1973"}]}' || true

php artisan prisoner:add '{"name":"Robert Hardy","first_name":"Robert","last_name":"Hardy","description":"Robert W. Hardy was a Camden, New Jersey building contractor who was approached by the FBI in early August 1971 and asked to infiltrate a planned Catholic Left raid on the Camden, NJ draft board. He participated as an FBI informant — supplying tools, financing, and logistical support to the planning meetings — and surfaced as a defense witness at the 1973 trial, testifying that the FBI had specifically encouraged the action and supplied the material means. His testimony was decisive in the May 20, 1973 acquittal of all 28 defendants. He is included in this database not as a prisoner himself but as the rare FBI informant whose conscience-based switch to the defense played the central role in winning a major political-prisoner case acquittal. He died on April 17, 2017.","state":"New Jersey","race":"White","gender":"Male","death_date":"2017-04-17","ideologies":["Whistleblower"],"affiliation":["Camden 28 (FBI informant turned defense witness)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"(no incarceration; FBI informant)","charges":"FBI informant in the Camden 28 case who switched to the defense; testimony decisive in May 20, 1973 acquittal","sentence":"No incarceration","convicted":"No charges"}]}' || true

echo
echo "Round 14 (Chicago 7/8 + RNC 8 + Camden 28) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
