#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round13_nato3_milwaukee14_pratt.sh
#
# Source clusters:
#   - NATO 3 (May 2012 Chicago) — three out-of-state Occupy organizers
#     entrapped by Chicago Police undercover Officers Nadia Chikko and
#     Mehmet Uygur in advance of the May 20-21 NATO summit
#   - Geronimo ji Jaga Pratt — Black Panther leader and decorated Vietnam
#     combat veteran wrongly convicted 1972 in COINTELPRO frame-up;
#     conviction vacated 1997 after 27 years
#   - Milwaukee 14 (Sept 24, 1968) — Catholic Left raid on Milwaukee
#     Selective Service offices; ~10,000 draft files burned with homemade
#     napalm; sentenced June 1969 to 2 years Wisconsin state prison
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === NATO 3 — Chicago, May 2012 ===

php artisan prisoner:add '{"name":"Brian Church","first_name":"Brian","last_name":"Church","description":"Brian Church was a 22-year-old Florida-based Occupy organizer at the time of his May 16, 2012 arrest in a Bridgeport, Chicago apartment, four days before the start of the NATO summit. He, Brent Vincent Betterly, and Jared Chase had traveled to Chicago to protest the summit. Two undercover Chicago Police Department officers — Nadia Chikko and Mehmet Uygur, posing as anarchist organizers — had supplied beer-bottle Molotov cocktails and encouraged escalation. The three were charged under Illinois state terrorism statutes — the first such state-terrorism prosecution in Illinois history. A Cook County jury acquitted them of the terrorism charges on February 7, 2014 but convicted them of mob action and possession of incendiary devices to commit arson. He was sentenced on April 25, 2014 to 5 years in Illinois state prison.","state":"Illinois","race":"White","gender":"Male","ideologies":["Anarchism","Anti-war","Occupy"],"affiliation":["Occupy"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Illinois Department of Corrections","institution_state":"Illinois","charges":"Illinois state mob action and possession of incendiary devices to commit arson — May 2012 Chicago, in advance of NATO summit; Illinois state terrorism charges acquitted","arrest_date":"2012-05-16","incarceration_date":"2014-04-25","sentenced_date":"2014-04-25","release_date":"2017-04-25","sentence":"5 years Illinois state prison","convicted":"Yes — Illinois state jury verdict, Cook County, February 7, 2014"}]}' || true

php artisan prisoner:add '{"name":"Brent Betterly","first_name":"Brent","middle_name":"Vincent","last_name":"Betterly","description":"Brent Vincent Betterly was a 24-year-old Florida-based Occupy organizer arrested with two co-defendants on May 16, 2012 in Chicago in advance of the NATO summit. He was acquitted of the Illinois state terrorism charges on February 7, 2014 but convicted of mob action and possession of incendiary devices to commit arson, and was sentenced on April 25, 2014 to 6 years in Illinois state prison.","state":"Illinois","race":"White","gender":"Male","ideologies":["Anarchism","Anti-war","Occupy"],"affiliation":["Occupy"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Illinois Department of Corrections","institution_state":"Illinois","charges":"Illinois state mob action and possession of incendiary devices to commit arson — May 2012 Chicago, in advance of NATO summit; Illinois state terrorism charges acquitted","arrest_date":"2012-05-16","incarceration_date":"2014-04-25","sentenced_date":"2014-04-25","release_date":"2018-04-25","sentence":"6 years Illinois state prison","convicted":"Yes — Illinois state jury verdict, Cook County, February 7, 2014"}]}' || true

php artisan prisoner:add '{"name":"Jared Chase","first_name":"Jared","last_name":"Chase","description":"Jared Chase was a 27-year-old New Hampshire-based Occupy organizer arrested with two co-defendants on May 16, 2012 in Chicago in advance of the NATO summit. He was acquitted of the Illinois state terrorism charges on February 7, 2014 but convicted of mob action and possession of incendiary devices to commit arson, and was sentenced on April 25, 2014 to 8 years in Illinois state prison — the longest of the NATO 3 sentences. He has Huntingtons disease, and his deteriorating health in custody became a major focus of post-sentencing organizing.","state":"Illinois","race":"White","gender":"Male","ideologies":["Anarchism","Anti-war","Occupy"],"affiliation":["Occupy"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Illinois Department of Corrections","institution_state":"Illinois","charges":"Illinois state mob action and possession of incendiary devices to commit arson — May 2012 Chicago, in advance of NATO summit; Illinois state terrorism charges acquitted","arrest_date":"2012-05-16","incarceration_date":"2014-04-25","sentenced_date":"2014-04-25","release_date":"2020-04-25","sentence":"8 years Illinois state prison","convicted":"Yes — Illinois state jury verdict, Cook County, February 7, 2014"}]}' || true

# === Geronimo Pratt ===

php artisan prisoner:add '{"name":"Geronimo Pratt","first_name":"Elmer","middle_name":"Gerard","last_name":"Pratt","aka":"Geronimo ji Jaga","description":"Elmer Gerard Pratt, who took the New Afrikan name Geronimo ji Jaga in prison, was a decorated U.S. Army Vietnam War combat veteran (Bronze Star, two Purple Hearts, two tours with the 82nd Airborne) who, after his discharge in 1968, became a UCLA student and the Deputy Minister of Defense of the Los Angeles chapter of the Black Panther Party. He was one of the principal targets of the FBIs COINTELPRO operation against the BPP and was singled out internally for neutralization.\n\nIn December 1970 he was arrested for the December 1968 murder of Caroline Olsen on a Santa Monica tennis court — a murder that occurred while he was 400 miles away at a Black Panther meeting in Oakland, a fact the FBIs own wiretap surveillance had recorded but withheld from the defense and from the prosecution. He was convicted in July 1972 in Los Angeles County and sentenced to life with the possibility of parole. He served 27 years in California state prison, eight of them in solitary confinement. On June 10, 1997, after a 1996 federal habeas hearing in which retired FBI agents acknowledged the COINTELPRO targeting, an Orange County Superior Court vacated the conviction on the grounds that the prosecution had concealed material exculpatory evidence (the FBI informant status of key witness Julius Butler). He was released the same day.\n\nIn 2000 he won a $4.5 million civil-rights settlement against the FBI and the Los Angeles Police Department — one of the few times the FBI was forced to settle a wrongful-conviction COINTELPRO claim. He retired to a village near Arusha, Tanzania, where he died on June 2, 2011, age 63. The Jericho Movement lists him among its ancestor political prisoners.","state":"California","race":"Black","gender":"Male","birthdate":"1947-09-13","death_date":"2011-06-02","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","U.S. Army (Vietnam, 82nd Airborne, former)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"California state murder of Caroline Olsen (Dec 1968 Santa Monica) — FBI COINTELPRO frame-up confirmed by 1996 federal habeas hearing; conviction vacated June 1997","arrest_date":"1970-12-08","incarceration_date":"1972-07-28","release_date":"1997-06-10","sentence":"Life with possibility of parole; vacated after 27 years","convicted":"Yes — Los Angeles County jury verdict, July 1972 (vacated June 10, 1997)"}]}' || true

# === Milwaukee 14 — Sept 24, 1968 Brumder Building draft-board raid ===

php artisan prisoner:add '{"name":"Don Cotton","first_name":"Don","last_name":"Cotton","description":"Don Cotton was a 24-year-old co-chairman of Students for a Democratic Society at Saint Louis University and one of the Milwaukee 14 — the Catholic Left affinity group that on September 24, 1968 entered the Brumder Building in downtown Milwaukee, removed approximately 10,000 1-A draft files from the nine Wisconsin Selective Service boards housed there, carried them to a public square, and burned them with homemade napalm in front of waiting reporters. The Milwaukee 14 were tried in Wisconsin state court for burglary, arson, and theft and convicted; on June 6, 1969 each was sentenced to 2 years state prison (with parole eligibility at 14 months).","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic","SDS"],"affiliation":["Milwaukee 14","Students for a Democratic Society"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Michael Cullen","first_name":"Michael","last_name":"Cullen","description":"Michael Cullen was a 26-year-old Irish-born director of Casa Maria House of Hospitality, the Milwaukee Catholic Worker, and one of the principal organizers of the Milwaukee 14 raid on September 24, 1968. After serving 14 months in Wisconsin state prison he was deported to Ireland in 1974 in connection with his immigration status. He continued Catholic Worker peace organizing in Ireland for the rest of his life.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic Worker"],"affiliation":["Milwaukee 14","Casa Maria Catholic Worker"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months; subsequently deported to Ireland 1974","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Robert Cunnane","first_name":"Robert","last_name":"Cunnane","description":"Father Robert Cunnane was a 36-year-old Stigmatine Catholic priest from Massachusetts and one of the Milwaukee 14. After serving 14 months in Wisconsin state prison he continued anti-war and peace organizing as a parish priest in Boston.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Milwaukee 14","Stigmatine Fathers"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"James Forest","first_name":"James","last_name":"Forest","aka":"Jim Forest","description":"James Hendrickson Forest was a 27-year-old former U.S. Navy meteorologist (he had received conscientious-objector reclassification while still on active duty), co-chairman of the Catholic Peace Fellowship in New York, and one of the Milwaukee 14. After serving 14 months in Wisconsin state prison he became one of the central American figures of the international Orthodox Christian peace movement, a longtime collaborator with Thich Nhat Hanh and Dorothy Day, and the author of biographies of Day, Thomas Merton, and Daniel Berrigan. He died in the Netherlands on January 13, 2022, age 80.","state":"Wisconsin","race":"White","gender":"Male","birthdate":"1941-11-02","death_date":"2022-01-13","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Milwaukee 14","Catholic Peace Fellowship","Orthodox Peace Fellowship"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Jerry Gardner","first_name":"Jerry","last_name":"Gardner","description":"Jerry Gardner was a 24-year-old Marquette University graduate student and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid and continued anti-war organizing in Wisconsin.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic"],"affiliation":["Milwaukee 14"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Bob Graf","first_name":"Bob","last_name":"Graf","description":"Bob Graf was a 25-year-old editor of The Catholic Radical and one of the Milwaukee 14. After serving 14 months in Wisconsin state prison he became a longtime Milwaukee Catholic Worker peace organizer and writer.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic Worker"],"affiliation":["Milwaukee 14","Catholic Radical"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"James Harney","first_name":"James","last_name":"Harney","description":"Father James Harney was a 28-year-old Catholic priest of the Boston Archdiocese and one of the Milwaukee 14. After serving 14 months in Wisconsin state prison he continued anti-war organizing through the Catholic Left.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic"],"affiliation":["Milwaukee 14","Catholic Left"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Jon Higgenbotham","first_name":"Jon","last_name":"Higgenbotham","description":"Jon Higgenbotham was a 27-year-old minister and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Pacifism"],"affiliation":["Milwaukee 14"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Alfred Janicke","first_name":"Alfred","last_name":"Janicke","description":"Father Alfred Janicke was a Catholic priest of the Saint Paul, Minnesota Archdiocese and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic"],"affiliation":["Milwaukee 14"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Doug Marvy","first_name":"Doug","last_name":"Marvy","description":"Doug Marvy was a 27-year-old draft-resistance organizer and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Pacifism"],"affiliation":["Milwaukee 14"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Anthony Mullaney","first_name":"Anthony","last_name":"Mullaney","description":"Father Anthony Mullaney was a 39-year-old Benedictine priest of St. Anselms Abbey in Manchester, New Hampshire, and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Catholic"],"affiliation":["Milwaukee 14","Order of Saint Benedict"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

php artisan prisoner:add '{"name":"Fred Ojile","first_name":"Fred","last_name":"Ojile","description":"Fred Ojile was a 23-year-old Minneapolis draft counselor and one of the Milwaukee 14. He served 14 months in Wisconsin state prison after the September 24, 1968 draft-board raid.","state":"Wisconsin","race":"White","gender":"Male","ideologies":["Anti-war","Pacifism"],"affiliation":["Milwaukee 14"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state burglary, arson, theft — September 24, 1968 Milwaukee 14 draft-board raid","arrest_date":"1968-09-24","incarceration_date":"1969-06-06","sentenced_date":"1969-06-06","release_date":"1970-08-06","sentence":"2 years Wisconsin state prison; paroled at 14 months","convicted":"Yes — Wisconsin state jury verdict, May 1969"}]}' || true

echo
echo "Round 13 (NATO 3 + Geronimo Pratt + Milwaukee 14) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
