<?php

declare(strict_types=1);

/**
 * Bulk-add Nixon-era political prisoners (1969-1974):
 *
 *   1. Pentagon Papers / whistleblowers (Tony Russo)
 *   2. Catholic Left raids (Harrisburg 7, Chicago 15, Beaver 55,
 *      Buffalo 9, Boston 8 missing names, Baltimore 4)
 *   3. Boston 5 missing (Marcus Raskin)
 *   4. Milwaukee 14 missing (Larry Rosebaugh, Basil O'Leary)
 *   5. Weather Underground (Dohrn, Ayers, Rudd, Jones, Machtinger,
 *      Stein, Diana Oughton, Ted Gold, Terry Robbins, Sam Melville
 *      ally Jane Alpert)
 *   6. Vietnam draft resisters (Muhammad Ali, Joan Baez, Bruce Beyer)
 *   7. Gainesville 8 (VVAW prosecutions)
 *   8. New York Panther 21
 *   9. New Haven Panther trials
 *  10. Soledad Brothers + San Quentin Six
 *  11. Angela Davis + Geronimo Pratt + Jonathan Jackson
 *  12. AIM / Wounded Knee 1973 / Pine Ridge / Skyhorse-Mohawk
 *  13. Alcatraz Occupation 1969-71 (Oakes, LaNada, Trudell)
 *  14. Attica (Frank "Big Black" Smith)
 *
 * Total: ~95 prisoners. Idempotent.
 *
 * Run: php scripts/add_nixon_era_prisoners.php
 */

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Institution;
use App\Models\Prisoner;
use App\Models\PrisonerCase;

function addP(array $p): array {
    $existing = Prisoner::where('name', $p['name'])->first();
    if ($existing) return [$existing, false];
    $prisoner = Prisoner::create(array_filter([
        'name' => $p['name'], 'first_name' => $p['first_name'] ?? null, 'middle_name' => $p['middle_name'] ?? null,
        'last_name' => $p['last_name'] ?? null, 'aka' => $p['aka'] ?? null,
        'gender' => $p['gender'] ?? null, 'race' => $p['race'] ?? null, 'state' => $p['state'] ?? null,
        'birthdate' => $p['birthdate'] ?? null, 'death_date' => $p['death_date'] ?? null,
        'description' => $p['description'] ?? null, 'era' => $p['era'] ?? '1970s',
        'ideologies' => $p['ideologies'] ?? null, 'affiliation' => $p['affiliation'] ?? null,
        'in_custody' => $p['in_custody'] ?? false, 'released' => $p['released'] ?? true,
    ], fn ($v) => $v !== null));
    return [$prisoner, true];
}

function attachC(Prisoner $prisoner, array $c): bool {
    if (! empty($c['arrest_date'])) {
        $exists = $prisoner->cases()->where('arrest_date', $c['arrest_date'])->first();
        if ($exists) return false;
    }
    $institution = Institution::firstOrCreate(['name' => $c['institution']['name']], ['city' => $c['institution']['city'] ?? null, 'state' => $c['institution']['state'] ?? null]);
    PrisonerCase::create([
        'prisoner_id' => $prisoner->id, 'institution_id' => $institution->id,
        'charges' => $c['charges'] ?? null, 'arrest_date' => $c['arrest_date'] ?? null,
        'incarceration_date' => $c['incarceration_date'] ?? null, 'release_date' => $c['release_date'] ?? null,
        'death_in_custody_date' => $c['death_in_custody_date'] ?? null,
        'sentenced_date' => $c['sentenced_date'] ?? null, 'convicted' => $c['convicted'] ?? null,
        'sentence' => $c['sentence'] ?? null, 'prosecutor' => $c['prosecutor'] ?? null, 'judge' => $c['judge'] ?? null,
    ]);
    return true;
}

$tot = ['created' => 0, 'existed' => 0, 'cases' => 0];

$harrisburgInst = ['name' => 'U.S. District Court, Middle District of Pennsylvania — Harrisburg 7', 'city' => 'Harrisburg', 'state' => 'Pennsylvania'];
$harrisburgCharges = 'Harrisburg 7 federal indictment Jan 12, 1971 alleging conspiracy to kidnap National Security Adviser Henry Kissinger and bomb federal heating tunnels under Washington — built on prison letters between Philip Berrigan and Elizabeth McAlister smuggled by FBI informant Boyd Douglas. Trial April 1972 before Judge R. Dixon Herman; jury hung 10-2 for acquittal; mistrial; government declined to retry. Prosecutor: William S. Lynch (DOJ Internal Security).';

$ny21Inst = ['name' => 'New York Supreme Court — Panther 21', 'city' => 'New York', 'state' => 'New York'];
$ny21Charges = 'New York Panther 21 indictment April 2, 1969: 156 counts of conspiracy to bomb police stations, department stores, and public buildings. Trial before Judge John M. Murtagh; ADA Joseph A. Phillips. Acquittal on all counts May 13, 1971 — at the time the longest trial in NY history.';

$soledadInst = ['name' => 'San Francisco / California state — Soledad Brothers', 'city' => 'San Francisco', 'state' => 'California'];
$sqsixInst = ['name' => 'Marin County / California state — San Quentin Six', 'city' => 'San Rafael', 'state' => 'California'];

$wkInst = ['name' => 'U.S. District Court / South Dakota state — Wounded Knee 1973', 'city' => 'St. Paul', 'state' => 'Minnesota'];
$wkCharges = '71-day occupation of Wounded Knee, South Dakota by AIM and traditional Oglala Lakota Feb 27 - May 8, 1973. ~1,200 federal personnel surrounded; 2 occupiers killed. Federal "Wounded Knee Leadership Trial" (U.S. v. Banks & Means) before Judge Fred J. Nichol (D. Minn.); Sept 16, 1974 Nichol dismissed all charges, declaring "the waters of justice have been polluted" by FBI misconduct.';

$people = [
    // ===== Pentagon Papers =====
    ['name' => 'Anthony Joseph Russo Jr.', 'first_name' => 'Anthony', 'middle_name' => 'Joseph', 'last_name' => 'Russo Jr.', 'aka' => 'Tony Russo', 'gender' => 'Male', 'race' => 'White', 'state' => 'California', 'birthdate' => '1936-10-14', 'death_date' => '2008-08-06', 'description' => 'RAND Corporation analyst who helped Daniel Ellsberg photocopy the Pentagon Papers in October 1969. Earlier authored RAND studies documenting systematic torture of Viet Cong prisoners by South Vietnamese and U.S. forces. Indicted with Ellsberg Dec 30, 1971 under the Espionage Act; refused immunity and spent 47 days in jail for contempt before trial. Case dismissed May 11, 1973 by Judge William Matthew Byrne Jr. after revelations of the Nixon Plumbers\' break-in at Ellsberg\'s psychiatrist\'s office.', 'affiliation' => ['RAND Corporation'], 'ideologies' => ['Anti-war', 'Whistleblower'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Central District of California — U.S. v. Russo (Pentagon Papers)', 'city' => 'Los Angeles', 'state' => 'California'], 'arrest_date' => '1971-08-15', 'sentenced_date' => null, 'release_date' => '1973-05-11', 'sentence' => 'Charges dismissed May 11, 1973 (47 days for contempt)', 'convicted' => 'No — charges dismissed', 'judge' => 'Hon. William Matthew Byrne Jr.', 'prosecutor' => 'David R. Nissen', 'charges' => 'Espionage Act violations, theft of government property, conspiracy.']]],

    // ===== Harrisburg 7 =====
    ['name' => 'Elizabeth McAlister', 'first_name' => 'Elizabeth', 'last_name' => 'McAlister', 'aka' => 'Liz McAlister; Sister Elizabeth McAlister, RSHM (former)', 'gender' => 'Female', 'race' => 'White', 'state' => 'Maryland', 'birthdate' => '1939-11-17', 'description' => 'Art historian at Marymount College and former Religious of the Sacred Heart of Mary nun who became a leader of the Catholic anti-war movement. Her smuggled correspondence with imprisoned Philip Berrigan — relayed by FBI informant Boyd Douglas — formed the basis of the 1971 Harrisburg conspiracy indictment. After the jury hung 10-2 for acquittal in April 1972, she was convicted only of smuggling letters. Married Philip Berrigan in 1973 (resulting in her excommunication); co-founded Jonah House and the Plowshares Movement; took part in the April 4, 2018 Kings Bay Plowshares 7 action.', 'affiliation' => ['Catholic Left', 'Jonah House (co-founder)', 'Plowshares Movement', 'Religious of the Sacred Heart of Mary (former)'], 'ideologies' => ['Catholic peace witness', 'Anti-war', 'Anti-nuclear'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury on conspiracy April 5, 1972; convicted only on letter-smuggling count.', 'convicted' => 'Hung jury (conspiracy); Yes (letter-smuggling)', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'Eqbal Ahmad', 'first_name' => 'Eqbal', 'last_name' => 'Ahmad', 'gender' => 'Male', 'race' => 'Asian', 'state' => 'Illinois', 'birthdate' => '1933-01-01', 'death_date' => '1999-05-11', 'description' => 'Pakistani-American political scientist born in Bihar, partition refugee, Princeton PhD 1967. Former adviser to Algerian FLN delegation in Paris under Frantz Fanon. The only non-Catholic and only South Asian among the Harrisburg Seven, indicted January 1971 as alleged "mastermind" of the Kissinger-kidnap plot. After the April 1972 mistrial he was a Senior Fellow at the Institute for Policy Studies, founding director of the Transnational Institute (1973-75), and Hampshire College professor (1982-1997). Died in Islamabad of colon cancer.', 'affiliation' => ['Institute for Policy Studies', 'Transnational Institute', 'Hampshire College', 'Algerian FLN (former)'], 'ideologies' => ['Anti-imperialism', 'Third Worldism', 'Anti-war'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury April 5, 1972; mistrial; government declined to retry.', 'convicted' => 'Hung jury — effectively acquitted', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'Joseph Wenderoth', 'first_name' => 'Joseph', 'last_name' => 'Wenderoth', 'aka' => 'Father Joseph Wenderoth', 'gender' => 'Male', 'race' => 'White', 'state' => 'Maryland', 'description' => 'Roman Catholic priest of the Archdiocese of Baltimore, member of the Baltimore "Ghetto Priests" working in inner-city parishes. Indicted January 1971 as one of the Harrisburg Seven. Trial April 1972 ended in a hung jury (10-2 for acquittal); government declined to retry.', 'affiliation' => ['Archdiocese of Baltimore', 'Catholic Left', 'Baltimore Ghetto Priests'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury April 5, 1972; mistrial; no retrial.', 'convicted' => 'Hung jury', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'Neil R. McLaughlin', 'first_name' => 'Neil', 'middle_name' => 'R.', 'last_name' => 'McLaughlin', 'aka' => 'Father Neil McLaughlin', 'gender' => 'Male', 'race' => 'White', 'state' => 'Maryland', 'description' => 'Archdiocesan priest of Baltimore active in Catholic Left anti-war organizing. Indicted January 1971 as a Harrisburg Seven defendant; April 1972 trial ended in hung jury. Note: distinct from Jesuit Neil P. McLaughlin SJ (different priest).', 'affiliation' => ['Archdiocese of Baltimore', 'Catholic Left'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury April 5, 1972; mistrial; no retrial.', 'convicted' => 'Hung jury', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'Anthony Scoblick', 'first_name' => 'Anthony', 'last_name' => 'Scoblick', 'aka' => 'Tony Scoblick', 'gender' => 'Male', 'race' => 'White', 'state' => 'Maryland', 'description' => 'Former Josephite priest from Baltimore; participated in the November 7, 1969 Boston 8 draft-board raid. Indicted January 1971 as a Harrisburg Seven defendant alongside his wife Mary Cain Scoblick. April 1972 trial ended in hung jury; no retrial.', 'affiliation' => ['Catholic Left', 'Boston 8'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury; mistrial; no retrial.', 'convicted' => 'Hung jury', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'Mary Cain Scoblick', 'first_name' => 'Mary', 'middle_name' => 'Cain', 'last_name' => 'Scoblick', 'gender' => 'Female', 'race' => 'White', 'state' => 'Maryland', 'birthdate' => '1938-01-01', 'description' => 'Former Catholic nun from Baltimore married to former priest Anthony Scoblick. Participated in the November 1969 Boston 8 raid. As one of the Harrisburg Seven, indicted January 1971 on charges of conspiring to kidnap Henry Kissinger. April 1972 mistrial freed all defendants on the conspiracy count.', 'affiliation' => ['Catholic Left', 'Boston 8'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-04-05', 'sentence' => 'Hung jury; mistrial; no retrial.', 'convicted' => 'Hung jury', 'judge' => 'Hon. R. Dixon Herman', 'prosecutor' => 'William S. Lynch', 'charges' => $harrisburgCharges]]],
    ['name' => 'John Theodore Glick', 'first_name' => 'John', 'middle_name' => 'Theodore', 'last_name' => 'Glick', 'aka' => 'Ted Glick', 'gender' => 'Male', 'race' => 'White', 'state' => 'Pennsylvania', 'birthdate' => '1949-01-01', 'description' => 'Eighth original defendant in the Harrisburg 8 indictment January 1971. Severed his case to represent himself pro se and was tried separately, becoming the only Harrisburg defendant the government later declined to try. Previously served eleven months in federal prison for draft resistance and continued participation in Catholic Left draft-board raids. Has remained a progressive organizer and climate-justice activist.', 'affiliation' => ['Catholic Left ally', 'Draft resistance'], 'ideologies' => ['Anti-war', 'Nonviolent direct action'], 'cases' => [['institution' => $harrisburgInst, 'arrest_date' => '1971-01-12', 'release_date' => '1972-12-15', 'sentence' => 'Severed; case never tried.', 'convicted' => 'No — case never tried', 'judge' => 'Hon. R. Dixon Herman', 'charges' => $harrisburgCharges]]],

    // ===== Boston 5 missing + Milwaukee 14 missing + Baltimore 4 =====
    ['name' => 'Marcus Goodman Raskin', 'first_name' => 'Marcus', 'middle_name' => 'Goodman', 'last_name' => 'Raskin', 'aka' => 'Marc Raskin', 'gender' => 'Male', 'race' => 'White', 'state' => 'District of Columbia', 'birthdate' => '1934-04-30', 'death_date' => '2017-12-24', 'description' => 'Former JFK National Security Council staffer who in 1963 co-founded the Institute for Policy Studies, the principal New Left think tank in Washington. In January 1968 indicted alongside Benjamin Spock, William Sloane Coffin, Mitchell Goodman, and Michael Ferber as one of the Boston Five for conspiracy to counsel, aid, and abet draft resistance. The only Boston Five defendant acquitted by the jury at the original Boston federal trial in June 1968.', 'affiliation' => ['Institute for Policy Studies (co-founder)', 'RESIST'], 'ideologies' => ['Anti-war', 'Democratic socialism', 'New Left'], 'cases' => [['institution' => ['name' => 'U.S. District Court, District of Massachusetts — Boston 5', 'city' => 'Boston', 'state' => 'Massachusetts'], 'arrest_date' => '1968-01-05', 'sentenced_date' => '1968-06-14', 'release_date' => '1968-06-14', 'sentence' => 'Acquitted June 14, 1968 by jury — only Boston Five defendant acquitted at original trial.', 'convicted' => 'No — acquitted', 'judge' => 'Hon. Francis J.W. Ford', 'prosecutor' => 'John Wall (AUSA, D. Mass.)', 'charges' => 'Federal conspiracy to counsel, aid, and abet violation of the Selective Service Act (18 USC 371; 50 USC App 462) — Boston Five.']]],
    ['name' => 'Lawrence Rosebaugh', 'first_name' => 'Lawrence', 'last_name' => 'Rosebaugh', 'aka' => 'Larry Rosebaugh; Lorenzo Rosebaugh, OMI', 'gender' => 'Male', 'race' => 'White', 'state' => 'Wisconsin', 'birthdate' => '1935-05-16', 'death_date' => '2009-05-18', 'description' => 'Oblate priest born in Appleton, Wisconsin, ordained 1963; co-founder of a Catholic Worker house in Milwaukee when he joined the September 24, 1968 Milwaukee 14 raid that burned ~10,000 Selective Service files. Served 14 months in Wisconsin state prison (1969-70). Spent the rest of his life as a missionary among the poor in Brazil, El Salvador, Mexico, and Guatemala. Murdered by armed robbers on a rural highway in northern Guatemala on May 18, 2009.', 'affiliation' => ['Missionary Oblates of Mary Immaculate', 'Catholic Worker', 'Milwaukee 14'], 'ideologies' => ['Catholic peace witness', 'Liberation theology'], 'cases' => [['institution' => ['name' => 'Wisconsin state prison — Milwaukee 14', 'city' => 'Milwaukee', 'state' => 'Wisconsin'], 'arrest_date' => '1968-09-24', 'sentenced_date' => '1969-05-15', 'release_date' => '1970-08-06', 'sentence' => '2 years Wisconsin state prison; paroled at 14 months.', 'convicted' => 'Yes', 'charges' => 'Wisconsin state burglary, arson, and theft — September 24, 1968 Milwaukee 14 draft-board raid on the Brumder Building.']]],
    ['name' => 'Edmund Basil O\'Leary', 'first_name' => 'Edmund', 'middle_name' => 'Basil', 'last_name' => 'O\'Leary', 'aka' => 'Brother Basil O\'Leary, FSC', 'gender' => 'Male', 'race' => 'White', 'state' => 'Wisconsin', 'description' => 'De La Salle Christian Brother and professor of economics at Saint Mary\'s College in Winona, Minnesota when he joined the September 24, 1968 Milwaukee 14 raid. Served 14 months in Wisconsin state prison after the May 1969 jury verdict. Returned to academic life and later chaired the Center for Nonviolence at Saint Mary\'s.', 'affiliation' => ['De La Salle Christian Brothers', 'Milwaukee 14'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => ['name' => 'Wisconsin state prison — Milwaukee 14', 'city' => 'Milwaukee', 'state' => 'Wisconsin'], 'arrest_date' => '1968-09-24', 'sentenced_date' => '1969-05-15', 'release_date' => '1970-08-06', 'sentence' => '2 years Wisconsin state prison; paroled at 14 months.', 'convicted' => 'Yes', 'charges' => 'Wisconsin state burglary, arson, and theft — Milwaukee 14 raid.']]],
    ['name' => 'David Mack Eberhardt', 'first_name' => 'David', 'middle_name' => 'Mack', 'last_name' => 'Eberhardt', 'aka' => 'Dave Eberhardt', 'gender' => 'Male', 'race' => 'White', 'state' => 'Maryland', 'birthdate' => '1941-03-26', 'description' => 'Oberlin-educated Baltimore poet and secretary of the Baltimore Interfaith Peace Mission. On October 27, 1967 he entered the Selective Service Board at Baltimore\'s Customs House with Father Philip Berrigan, Tom Lewis, and James Mengel and poured human and poultry blood on 1-A draft files — the first action of the Catholic Left and prototype for the Catonsville Nine seven months later. Sentenced to two years; reported to Lewisburg federal penitentiary in 1970, serving 21 months.', 'affiliation' => ['Baltimore Four', 'Baltimore Interfaith Peace Mission'], 'ideologies' => ['Pacifism', 'Catholic Left'], 'cases' => [['institution' => ['name' => 'U.S. Penitentiary, Lewisburg — Baltimore Four', 'city' => 'Lewisburg', 'state' => 'Pennsylvania'], 'arrest_date' => '1967-10-27', 'sentenced_date' => '1968-04-25', 'release_date' => '1972-04-15', 'sentence' => '2 years federal prison; served 21 months at USP Lewisburg.', 'convicted' => 'Yes', 'charges' => 'Federal mutilation of government records (18 USC 2071), interference with Selective Service System — Baltimore Four blood-pouring action.']]],

    // ===== Weather Underground =====
    ['name' => 'Bernardine Rae Dohrn', 'first_name' => 'Bernardine', 'middle_name' => 'Rae', 'last_name' => 'Dohrn', 'aka' => 'Bernardine Ohrnstein', 'gender' => 'Female', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1942-01-12', 'description' => 'University of Chicago Law School graduate who became inter-organizational secretary of SDS and a leader of the Weather Underground after the 1969 SDS split. After the March 6, 1970 Greenwich Village townhouse explosion she went underground; added to the FBI Ten Most Wanted list October 14, 1970; lived as a federal fugitive for a decade. Surrendered with Bill Ayers December 1980. Federal charges dropped due to FBI illegalities (COINTELPRO). Pleaded guilty to misdemeanor aggravated battery and bail-jumping; later served 7 months for refusing to testify in Brink\'s grand jury (1982-83).', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism', 'Anti-imperialism', 'New Left'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1980-12-03', 'release_date' => '1983-01-15', 'sentence' => 'Federal charges dropped (COINTELPRO illegalities); misdemeanor probation; 7 months contempt (1982-83 Brink\'s grand jury refusal).', 'convicted' => 'Misdemeanor (federal charges dropped)', 'charges' => 'Federal Anti-Riot Act / conspiracy (Days of Rage indictment Apr 2, 1970); bail-jumping; later contempt.']]],
    ['name' => 'William Charles Ayers', 'first_name' => 'William', 'middle_name' => 'Charles', 'last_name' => 'Ayers', 'aka' => 'Bill Ayers', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1944-12-26', 'description' => 'Son of Commonwealth Edison CEO Thomas Ayers; became Ann Arbor SDS leader and a co-founder of the Weather Underground in 1969. Went underground March 1970 following the Greenwich Village townhouse explosion that killed his then-partner Diana Oughton. Remained a fugitive over a decade; surrendered with Bernardine Dohrn December 3, 1980. All federal charges dropped due to FBI illegalities. Became Distinguished Professor of Education at the University of Illinois at Chicago.', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism', 'Anti-imperialism'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1980-12-03', 'release_date' => '1980-12-03', 'sentence' => 'All federal charges dropped due to FBI illegal surveillance.', 'convicted' => 'No — charges dropped', 'charges' => 'Federal Anti-Riot Act / conspiracy (Days of Rage indictment).']]],
    ['name' => 'Mark William Rudd', 'first_name' => 'Mark', 'middle_name' => 'William', 'last_name' => 'Rudd', 'gender' => 'Male', 'race' => 'White', 'state' => 'New Mexico', 'birthdate' => '1947-06-02', 'description' => 'Led Columbia University SDS chapter and was the public spokesperson during the April 1968 Columbia occupation. Co-author of the June 1969 "You Don\'t Need a Weatherman" manifesto and Weather Underground national secretary. Indicted 1970 on federal Anti-Riot Act charges; lived underground 1970-1977 before surrendering. All federal charges dropped due to government illegalities; pleaded to minor state charges. Now teaches mathematics in New Mexico.', 'affiliation' => ['Columbia SDS', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism', 'Anti-imperialism'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1977-09-14', 'sentenced_date' => '1977-09-14', 'release_date' => '1977-09-14', 'sentence' => 'Federal charges dropped; 2 years probation, $2,000 fine on remaining state count.', 'convicted' => 'Misdemeanor (federal dropped)', 'charges' => 'Federal Anti-Riot Act conspiracy (Days of Rage); state criminal trespass (Columbia).']]],
    ['name' => 'Jeffrey Carl Jones', 'first_name' => 'Jeffrey', 'middle_name' => 'Carl', 'last_name' => 'Jones', 'aka' => 'Jeff Jones', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1947-02-23', 'description' => 'Born in Philadelphia; SDS New York regional organizer and national interim committee member. June 1969 signer of "You Don\'t Need a Weatherman" manifesto. Went underground 1970 with Eleanor Stein (later his wife); remained a fugitive eleven years in California and the Catskills. October 22, 1981 FBI agents arrested him in his Bronx apartment during lawyer-mediated surrender. Federal charges largely dropped due to COINTELPRO illegality. Later became a New York environmental lobbyist.', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground', 'Prairie Fire Organizing Committee'], 'ideologies' => ['Revolutionary socialism', 'Anti-imperialism'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1981-10-22', 'release_date' => '1981-12-15', 'sentence' => 'Federal charges dropped due to FBI illegal surveillance; minimal time served.', 'convicted' => 'No — federal dropped', 'charges' => 'Federal Anti-Riot Act / Days of Rage conspiracy.']]],
    ['name' => 'Howard Norton Machtinger', 'first_name' => 'Howard', 'middle_name' => 'Norton', 'last_name' => 'Machtinger', 'aka' => 'Howie Machtinger', 'gender' => 'Male', 'race' => 'White', 'state' => 'North Carolina', 'birthdate' => '1946-04-23', 'death_date' => '2024-07-24', 'description' => 'Bronx-born; cum laude Columbia 1966 (sociology); SDS regional director 1968. Co-author of the June 1969 Weatherman statement, Days of Rage participant. Named in the April 2, 1970 Weatherman federal indictment. Led the West Coast Weather Underground collective in San Francisco. Surrendered May 11, 1978. Charges dismissed for lack of court-ordered electronic surveillance. Earned MA from SF State; taught high school in North Carolina; directed teacher-training program at UNC Chapel Hill until his death in Durham July 24, 2024.', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground', 'Revolutionary Youth Movement'], 'ideologies' => ['Revolutionary socialism'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1973-09-19', 'release_date' => '1978-05-11', 'sentence' => 'Federal charges dismissed for lack of court-ordered electronic surveillance.', 'convicted' => 'No — dismissed', 'charges' => 'Federal Anti-Riot Act / explosives conspiracy.']]],
    ['name' => 'Eleanor E. Stein', 'first_name' => 'Eleanor', 'last_name' => 'Stein', 'aka' => 'Eleanor Raskin', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1946-03-16', 'description' => 'Daughter of New Deal economist Arthur Stein and civil-rights organizer Annie Stein. Joined Weatherman summer 1969; co-authored "The Bust Book" with Kathy Boudin. After the March 6, 1970 townhouse explosion helped Cathy Wilkerson disguise as fugitive. Went underground with Jeff Jones; their son Thai Jones born 1977. After October 1981 Bronx apartment FBI raid federal charges were dropped due to COINTELPRO illegality. Earned JD; became longtime NY State Public Service Commission administrative law judge and adjunct professor at Albany Law School.', 'affiliation' => ['National Lawyers Guild', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism'], 'cases' => [['institution' => ['name' => 'Federal courts — Weather Underground / Days of Rage', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1981-10-22', 'release_date' => '1981-12-15', 'sentence' => 'Federal charges dropped due to FBI illegal surveillance.', 'convicted' => 'No — dropped', 'charges' => 'Federal Anti-Riot Act / Days of Rage conspiracy.']]],
    ['name' => 'Diana Oughton', 'first_name' => 'Diana', 'last_name' => 'Oughton', 'gender' => 'Female', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1942-01-26', 'death_date' => '1970-03-06', 'released' => false, 'description' => 'Bryn Mawr-educated daughter of an Illinois banker and Republican state legislator who taught with the Peace Corps in Guatemala, then organized with Jobs or Income Now in Cleveland and Ann Arbor SDS, where she became Bill Ayers\'s partner. Joined Weatherman after the June 1969 SDS split. Killed at age 28 on March 6, 1970 in the Greenwich Village townhouse explosion at 18 West 11th Street while assembling, with Terry Robbins, a nail bomb intended for an enlisted-soldiers\' dance at Fort Dix; her body was identified only by a fingertip.', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism'], 'cases' => [['institution' => ['name' => 'Greenwich Village townhouse, 18 West 11th Street — Weather Underground', 'city' => 'New York', 'state' => 'New York'], 'death_in_custody_date' => '1970-03-06', 'sentence' => 'Killed in townhouse explosion March 6, 1970.', 'convicted' => 'Killed before trial', 'charges' => 'No charges filed before death.']]],
    ['name' => 'Theodore Gold', 'first_name' => 'Theodore', 'last_name' => 'Gold', 'aka' => 'Ted Gold', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1947-12-13', 'death_date' => '1970-03-06', 'released' => false, 'description' => 'Son of two NYC physicians; vice-chair of the Columbia SDS chapter under Mark Rudd; leader of the April-May 1968 Columbia occupations. One of the students arrested when NYPD cleared the Mathematics Hall barricade. Joined Weatherman after the June 1969 SDS split. Killed age 22 on March 6, 1970 in the Greenwich Village townhouse explosion at 18 West 11th Street; he was on the ground floor when the bomb being assembled in the basement detonated.', 'affiliation' => ['Columbia SDS', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism'], 'cases' => [['institution' => ['name' => 'Greenwich Village townhouse, 18 West 11th Street — Weather Underground', 'city' => 'New York', 'state' => 'New York'], 'arrest_date' => '1968-04-30', 'death_in_custody_date' => '1970-03-06', 'sentence' => 'Killed in townhouse explosion March 6, 1970.', 'convicted' => 'Killed before trial', 'charges' => 'Trespass / criminal mischief (1968 Columbia); no Weather indictment before death.']]],
    ['name' => 'Terry Robbins', 'first_name' => 'Terry', 'last_name' => 'Robbins', 'gender' => 'Male', 'race' => 'White', 'state' => 'Ohio', 'birthdate' => '1947-10-04', 'death_date' => '1970-03-06', 'released' => false, 'description' => 'Kenyon College dropout; SDS organizer in Ohio (Kent State, Ohio State, Antioch); leading militant of the Revolutionary Youth Movement faction. Co-author of June 1969 "You Don\'t Need a Weatherman" manifesto; principal advocate of armed struggle within Weatherman, leading the New York City collective. Killed age 22 on March 6, 1970 in the basement of the Greenwich Village townhouse while assembling a nail bomb intended for a non-commissioned-officers\' dance at Fort Dix; identified only by dental records.', 'affiliation' => ['Students for a Democratic Society', 'Weather Underground'], 'ideologies' => ['Revolutionary socialism'], 'cases' => [['institution' => ['name' => 'Greenwich Village townhouse, 18 West 11th Street — Weather Underground', 'city' => 'New York', 'state' => 'New York'], 'death_in_custody_date' => '1970-03-06', 'sentence' => 'Killed in townhouse explosion March 6, 1970.', 'convicted' => 'Killed before trial', 'charges' => 'No federal indictment before death.']]],
    ['name' => 'Samuel Joseph Melville', 'first_name' => 'Samuel', 'middle_name' => 'Joseph', 'last_name' => 'Melville', 'aka' => 'Sam Melville (born Samuel Joseph Grossman)', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1934-12-14', 'death_date' => '1971-09-13', 'released' => false, 'description' => 'Principal bomber in a 1969 New York City campaign that planted explosives at eight federal, military, and corporate buildings (including the Marine Midland Building, United Fruit, and the Criminal Courts Building) in protest of the Vietnam War and U.S. imperialism. Arrested November 12, 1969 placing dynamite in National Guard trucks at the 69th Regiment Armory; pleaded guilty May 1970 and received an 18-year sentence. Helped organize the September 9-13, 1971 Attica prison uprising and was killed by NY State Police gunfire when Governor Rockefeller ordered the assault on D-Yard September 13, 1971; survivors said he was unarmed with hands raised.', 'affiliation' => ['Anti-imperialist underground', 'Attica Liberation Faction'], 'ideologies' => ['Anti-imperialism', 'Revolutionary anti-war militancy'], 'cases' => [['institution' => ['name' => 'Attica Correctional Facility — 1969 NYC bombings + 1971 uprising', 'city' => 'Attica', 'state' => 'New York'], 'arrest_date' => '1969-11-12', 'sentenced_date' => '1970-05-15', 'death_in_custody_date' => '1971-09-13', 'sentence' => '18 years federal prison; killed during state retaking of Attica D-Yard.', 'convicted' => 'Yes — guilty plea', 'charges' => 'Conspiracy; bombing federal property; assault on a federal marshal.']]],
    ['name' => 'Jane Lauren Alpert', 'first_name' => 'Jane', 'middle_name' => 'Lauren', 'last_name' => 'Alpert', 'gender' => 'Female', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1947-01-01', 'description' => 'Swarthmore graduate and Columbia journalism student who became Sam Melville\'s partner and helped him plan and carry out the eight 1969 NYC bombings. Arrested November 12, 1969; pled guilty to conspiracy; jumped bail May 13, 1970 just before sentencing; underground for four and a half years. While underground wrote influential 1973 essay "Mother Right" repudiating Melville and the male New Left. Surrendered November 1974 and served 27 months at the Federal Reformatory for Women, Alderson. Memoir: "Growing Up Underground" (1981).', 'affiliation' => ['Sam Melville bombing collective', 'Underground feminist movement'], 'ideologies' => ['Anti-war', 'Anti-imperialism', 'Radical feminism'], 'cases' => [['institution' => ['name' => 'Federal Reformatory for Women, Alderson', 'city' => 'Alderson', 'state' => 'West Virginia'], 'arrest_date' => '1969-11-12', 'sentenced_date' => '1975-01-15', 'release_date' => '1977-04-15', 'sentence' => '27 months federal prison.', 'convicted' => 'Yes — guilty plea', 'charges' => 'Federal conspiracy to bomb military and corporate buildings in Manhattan (1969); bail-jumping.']]],

    // ===== Vietnam draft resisters =====
    ['name' => 'Muhammad Ali', 'first_name' => 'Muhammad', 'last_name' => 'Ali', 'aka' => 'Cassius Marcellus Clay Jr.', 'gender' => 'Male', 'race' => 'Black', 'state' => 'Texas', 'birthdate' => '1942-01-17', 'death_date' => '2016-06-03', 'description' => 'Heavyweight champion who refused induction into the U.S. Army at the Houston Armed Forces Examining Station on April 28, 1967, citing his Nation of Islam ministry and religious opposition to the Vietnam War: "I ain\'t got no quarrel with them Viet Cong." Stripped of his title same day; barred from boxing 1967-1970. Convicted June 20, 1967 in S.D. Tex. by Judge Joe Ingraham; sentenced to maximum 5 years federal prison and $10,000 fine. June 28, 1971 SCOTUS unanimously reversed in Clay v. United States, 403 U.S. 698 (8-0, Marshall recused). Never served prison time.', 'affiliation' => ['Nation of Islam'], 'ideologies' => ['Black nationalism', 'Conscientious objection', 'Anti-war'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Southern District of Texas — U.S. v. Clay', 'city' => 'Houston', 'state' => 'Texas'], 'arrest_date' => '1967-05-08', 'sentenced_date' => '1967-06-20', 'release_date' => '1971-06-28', 'sentence' => '5 years federal prison + $10,000 fine; reversed unanimously by SCOTUS June 28, 1971; no prison time served.', 'convicted' => 'Yes; reversed by SCOTUS', 'judge' => 'Hon. Joe Ingraham', 'prosecutor' => 'Morton L. Susman (U.S. Atty., S.D. Tex.)', 'charges' => 'Federal violation of the Universal Military Training and Service Act — refusing induction (50 U.S.C. App. § 462). Reversed Clay v. United States, 403 U.S. 698 (1971).']]],
    ['name' => 'Joan Chandos Baez', 'first_name' => 'Joan', 'middle_name' => 'Chandos', 'last_name' => 'Baez', 'gender' => 'Female', 'race' => 'White', 'state' => 'California', 'birthdate' => '1941-01-09', 'description' => 'Folk singer who began withholding 60 percent of her federal income taxes in 1964 to protest U.S. military spending; co-founded the Institute for the Study of Nonviolence. October 16, 1967 she, her mother, sister Mimi Fariña, and ~70 other women were arrested at the Oakland Armed Forces Induction Center for blocking the doors in support of draft resisters; served 10 days at Santa Rita. Rearrested December 1967 for the same action and served 45 days, where Martin Luther King Jr. visited her. There she met draft resister David Harris, whom she married in March 1968.', 'affiliation' => ['The Resistance', 'War Resisters League', 'Institute for the Study of Nonviolence'], 'ideologies' => ['Pacifism', 'Anti-war', 'Tax resistance'], 'cases' => [['institution' => ['name' => 'Santa Rita Rehabilitation Center, Oakland', 'city' => 'Dublin', 'state' => 'California'], 'arrest_date' => '1967-10-16', 'release_date' => '1968-02-15', 'sentence' => '10 days (Oct 1967); 45 days (Dec 1967 - Feb 1968).', 'convicted' => 'Yes — misdemeanor', 'charges' => 'California state misdemeanor — unlawful blocking of access to a federal facility (Oakland Induction Center).']]],
    ['name' => 'Bruce E. Beyer', 'first_name' => 'Bruce', 'middle_name' => 'E.', 'last_name' => 'Beyer', 'gender' => 'Male', 'race' => 'White', 'state' => 'New York', 'birthdate' => '1947-01-01', 'death_date' => '2017-08-23', 'description' => '21-year-old University of Buffalo student and Buffalo Draft Resistance Union organizer who, refusing induction, took public sanctuary in Buffalo\'s Unitarian Universalist Church on August 7, 1968. After twelve days of negotiations, U.S. marshals and FBI agents stormed the church August 19, 1968, beating supporters with blackjacks; Beyer and seven companions were arrested as the Buffalo Nine. Convicted of assaulting federal officers and sentenced March 19, 1969 to 3 years federal prison. Fled to Sweden; granted humanitarian asylum; returned under Carter\'s amnesty October 1977. Sentence reduced to 30 days time-served.', 'affiliation' => ['Buffalo Draft Resistance Union', 'Buffalo Nine'], 'ideologies' => ['Anti-war', 'Pacifism'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Western District of New York — Buffalo Nine', 'city' => 'Buffalo', 'state' => 'New York'], 'arrest_date' => '1968-08-19', 'sentenced_date' => '1969-03-19', 'release_date' => '1977-11-15', 'sentence' => '3 years federal prison (sentenced 1969-03-19); fled to Sweden / Canada; reduced to 30 days time-served on 1977 return.', 'convicted' => 'Yes', 'judge' => 'Hon. John T. Curtin', 'charges' => 'Federal — refusal of induction (50 USC App 462) and assault on federal officers (18 USC 111).']]],
    ['name' => 'Jane Kennedy', 'first_name' => 'Jane', 'last_name' => 'Kennedy', 'gender' => 'Female', 'race' => 'White', 'state' => 'Indiana', 'description' => 'Hospital nursing-administration director from Chicago and one of the eight members of the Catholic Left affinity group calling itself the Beaver 55. October 31, 1969 helped shred files of 44 Indianapolis Selective Service draft boards; November 7, 1969 helped scramble magnetic computer tapes containing biological- and chemical-warfare research at the Dow Chemical Computer Center in Midland, Michigan. Sentenced to 3 years federal prison; served at Federal Reformatory for Women, Alderson, WV.', 'affiliation' => ['Beaver 55', 'Catholic Left'], 'ideologies' => ['Catholic peace witness', 'Anti-war'], 'cases' => [['institution' => ['name' => 'Federal Reformatory for Women, Alderson — Beaver 55', 'city' => 'Alderson', 'state' => 'West Virginia'], 'arrest_date' => '1969-11-07', 'sentenced_date' => '1970-06-15', 'release_date' => '1972-12-15', 'sentence' => '3 years federal prison.', 'convicted' => 'Yes', 'charges' => 'Federal sabotage / destruction of government records — Indianapolis draft-board files; Michigan state malicious destruction — Dow Chemical Midland.']]],
    ['name' => 'Joseph E. Mulligan', 'first_name' => 'Joseph', 'middle_name' => 'E.', 'last_name' => 'Mulligan', 'aka' => 'Father Joe Mulligan, SJ', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1942-01-01', 'description' => 'Jesuit seminarian who, on May 25, 1969, with fourteen others (Chicago 15) entered the Selective Service office at 2355 W. 63rd Street, Chicago and removed and burned more than 40,000 1-A draft files from the 34 South Side draft boards. Sentenced 1970 to 5 years federal prison plus 5 years probation; paroled 1972. Ordained a Jesuit priest 1973; has lived in Managua, Nicaragua since shortly after the Sandinista revolution.', 'affiliation' => ['Society of Jesus', 'Chicago 15', 'Witness for Peace'], 'ideologies' => ['Catholic peace witness', 'Liberation theology', 'Anti-war'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago 15', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1969-05-25', 'sentenced_date' => '1970-06-15', 'release_date' => '1972-06-15', 'sentence' => '5 years federal prison + 5 years probation; paroled 1972.', 'convicted' => 'Yes', 'charges' => 'Federal destruction of Selective Service records (50 USC App 462); 18 USC 2071 (mutilation of government records).']]],
    ['name' => 'Nicholas J. Riddell', 'first_name' => 'Nicholas', 'middle_name' => 'J.', 'last_name' => 'Riddell', 'aka' => 'Father Nick Riddell, O.Carm.', 'gender' => 'Male', 'race' => 'White', 'state' => 'Illinois', 'birthdate' => '1931-01-01', 'description' => 'Carmelite priest active in Milwaukee civil-rights organizing alongside Father James Groppi. On May 25, 1969 was one of the Chicago 15 who entered the Selective Service office on Chicago\'s South Side and burned more than 40,000 draft records.', 'affiliation' => ['Order of Carmelites', 'Chicago 15'], 'ideologies' => ['Catholic peace witness', 'Civil rights', 'Anti-war'], 'cases' => [['institution' => ['name' => 'U.S. District Court, Northern District of Illinois — Chicago 15', 'city' => 'Chicago', 'state' => 'Illinois'], 'arrest_date' => '1969-05-25', 'sentenced_date' => '1970-06-15', 'sentence' => 'Federal prison term (~5 years range).', 'convicted' => 'Yes', 'charges' => 'Federal destruction of Selective Service records — Chicago 15 raid.']]],
];

// ===== Gainesville 8 (8 figures) =====
$g8Inst = ['name' => 'U.S. District Court, Northern District of Florida — Gainesville Eight', 'city' => 'Gainesville', 'state' => 'Florida'];
$g8Charges = 'Federal conspiracy to riot (18 USC 2101) and conspiracy to use destructive devices — alleged plot to violently disrupt the August 1972 Republican National Convention in Miami Beach. Acquitted unanimously by jury August 31, 1973 after just 4 hours of deliberation; FBI informants Emerson Poe and William Lemmer discredited.';
foreach ([
    ['Scott Camil', '1946-05-19', null, 'Florida', 'U.S. Marine Corps Vietnam veteran with 2 Purple Hearts and combat-action ribbon. Florida coordinator and Southeast regional coordinator of Vietnam Veterans Against the War; gave one of the most-quoted testimonies at the January 1971 Winter Soldier Investigation in Detroit. Placed on Nixon\'s enemies list. Lives in Gainesville.', 'White', 'Male'],
    ['Donald Perdue', null, null, 'Florida', 'Former combat Marine and Vietnam veteran active in VVAW after his discharge. Long career in emergency-response management in Broward County, Florida.', 'White', 'Male'],
    ['John W. Briggs', null, null, 'Florida', 'The only non-veteran among the Gainesville Eight; VVAW associate from the Gainesville chapter.', 'White', 'Male'],
    ['Stanley K. Michelsen', null, null, 'Florida', 'Vietnam veteran and VVAW chapter member.', 'White', 'Male'],
    ['William J. Patterson', null, '2013-06-15', 'Florida', 'Vietnam veteran and VVAW member; deceased before the 2013 40th-anniversary reunion.', 'White', 'Male'],
    ['Peter P. Mahoney', null, null, 'New York', 'Vietnam veteran and VVAW national/regional organizer; attended the 2013 40th-anniversary reunion.', 'White', 'Male'],
    ['John K. Kniffin', null, '2013-06-15', 'Texas', 'Vietnam veteran and VVAW member; deceased before the 2013 40th-anniversary reunion.', 'White', 'Male'],
    ['Alton C. Foss', null, null, 'Florida', 'Vietnam veteran and VVAW chapter member from south Florida.', 'White', 'Male'],
] as $row) {
    [$name, $bd, $dd, $state, $bio, $race, $gender] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts); $middle = count($parts) >= 3 ? $parts[1] : null;
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => $gender, 'race' => $race, 'state' => $state,
        'birthdate' => $bd, 'death_date' => $dd,
        'description' => $bio . ' Indicted July 1972 as one of the Gainesville Eight; acquitted unanimously August 31, 1973.',
        'affiliation' => ['Vietnam Veterans Against the War', 'Gainesville Eight'],
        'ideologies' => ['Anti-war', 'Veterans peace'],
        'cases' => [['institution' => $g8Inst, 'arrest_date' => '1972-07-13', 'sentenced_date' => '1973-08-31', 'release_date' => '1973-08-31', 'sentence' => 'Acquitted by jury August 31, 1973.', 'convicted' => 'No — acquitted', 'judge' => 'Hon. Winston E. Arnow', 'prosecutor' => 'Guy L. Goodwin (DOJ Internal Security Division)', 'charges' => $g8Charges]],
    ];
}

// ===== NY Panther 21 (16 figures) =====
foreach ([
    ['Afeni Shakur', 'Female', '1947-01-10', '2016-05-02', 'Born Alice Faye Williams in Lumberton, NC; joined Harlem BPP 1968 and became section leader. Arrested April 2, 1969 in the Panther 21 case, conducted her own legal defense while pregnant with her son Tupac. Facing 300+ years, she cross-examined witnesses and helped secure acquittal of all 13 defendants. Tupac born one month later June 16, 1971.'],
    ['Lumumba Abdul Shakur', 'Male', '1943-01-09', '1986-02-03', 'Born Anthony Coston in Atlantic City, NJ; led the Harlem chapter of the BPP and was lead defendant in the Panther 21 case. Spent two years on Rikers Island awaiting trial. After being acquitted on all 156 counts May 13, 1971, distanced himself from post-split party. Found dead in Louisiana 1986.'],
    ['Dhoruba al-Mujahid bin Wahad', 'Male', '1944-06-30', null, 'Born Richard Earl Moore in the South Bronx; joined the BPP August 1968 and rose to NY State Field Secretary. Acquitted Panther 21 May 1971; soon after went underground with the BLA. June 1971 arrested for attempted murder of two NYPD officers; wrongfully convicted 1973. Released 1990 after FBI COINTELPRO files revealed exculpatory evidence had been withheld.'],
    ['Joan Victoria Bird', 'Female', '1949-03-09', null, 'Bronx Community College nursing student when she joined the BPP in 1968. Headed the NY chapter\'s medical care program and free health clinics. Held under high bail; one of two women among the original 21 defendants.'],
    ['Robert Steele Collier', 'Male', '1936-01-01', '2010-02-12', 'Founder of the New York chapter of the BPP. Earlier had been entrapped in a 1965 government-set-up plot to bomb the Statue of Liberty. Later moved to Poughkeepsie and served as adjunct professor at Marist College.'],
    ['Curtis Powell', 'Male', '1935-01-01', '2002-12-15', 'Born in Orange, NJ; PhD in biochemistry from University of Stockholm 1968; worked at Columbia Presbyterian Medical Center. After joining the NY BPP, arrested in the Panther 21 case. Following acquittal, moved to Africa and developed a vaccine for trypanosomiasis (sleeping sickness). Returned to NY and died in Queens.'],
    ['Ali Bey Hassan', 'Male', null, null, 'Born John J. Casson; U.S. Navy veteran (enlisted 1955) who served in the Gunnery division. Joined the BPP in 1968 after hearing Bobby Seale speak. His writings appear in the collective Panther 21 autobiography "Look for Me in the Whirlwind."'],
    ['Lee Berry', 'Male', null, null, 'Vietnam War veteran being treated for epilepsy at the Manhattan VA Hospital when arrested April 2, 1969. Went without medical care for three months in custody and underwent a contested appendectomy at Bellevue. Case was severed and tried separately due to his medical condition.'],
    ['Kwando Mbiassi Kinshasa', 'Male', null, null, 'Born William King Jr. After acquittal he became a scholar of African American Studies and professor at John Jay College of Criminal Justice (CUNY).'],
    ['Lonnie Epps', 'Male', null, null, 'At 17, one of the youngest of the Panther 21 defendants; granted youthful offender status. Released on $10,000 bail; rearrested during the trial for courtroom altercation. Acquitted of original conspiracy counts May 1971.'],
    ['Lee Roper', 'Male', null, null, 'Later changed his name to Shaba Om. Acquitted with the rest of the defendants on all 156 counts.'],
    ['Michael Tabor', 'Male', '1946-12-13', '2010-10-17', 'Took the name Cetewayo after the 19th-century Zulu king. Authored the influential 1970 BPP pamphlet "Capitalism Plus Dope Equals Genocide." Jumped bail during the trial, fleeing to Algeria; acquitted in absentia. In 1972 moved to Lusaka, Zambia, where he became a popular jazz radio DJ on 5 FM.'],
    ['Jamal Joseph', 'Male', '1953-01-01', null, 'Born Edward L. Joseph in NYC; joined the BPP in September 1968 at age 15 — the youngest member of the Panther 21. In 1981 convicted of harboring a fugitive; served 5.5 years of a 12-year sentence, earning college degrees while inside. Now professor of professional practice and former chair of Columbia University\'s Graduate Film Division; author of the 2012 memoir "Panther Baby."'],
    ['Abayama Katara', 'Male', null, null, 'Born Alex McKiever; 17 at arrest April 2, 1969. Detained on Rikers Island at the Adolescent Remand Shelter; held political education classes for fellow detainees alongside Jamal Joseph.'],
    ['Baba Odinga', 'Male', null, null, 'Born Walter Johnson. Continued participating in the post-Panther political prisoner support and Pan-African organizing networks. (Not to be confused with Sekou Odinga.)'],
    ['Richard Harris', 'Male', null, null, 'Inspired to political activism after hearing Malcolm X speak at the Newark Mosque.'],
] as $row) {
    [$name, $gender, $bd, $dd, $bio] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts);
    $people[] = [
        'name' => $name, 'first_name' => $first, 'last_name' => $last,
        'gender' => $gender, 'race' => 'Black', 'state' => 'New York',
        'birthdate' => $bd, 'death_date' => $dd,
        'description' => $bio . ' One of the New York Panther 21; acquitted on all 156 counts on May 13, 1971.',
        'affiliation' => ['Black Panther Party', 'New York Panther 21'],
        'ideologies' => ['Black liberation', 'Revolutionary socialism'],
        'cases' => [['institution' => $ny21Inst, 'arrest_date' => '1969-04-02', 'sentenced_date' => '1971-05-13', 'release_date' => '1971-05-13', 'sentence' => 'Acquitted on all 156 counts.', 'convicted' => 'No — acquitted', 'judge' => 'Hon. John M. Murtagh', 'prosecutor' => 'Joseph A. Phillips (ADA Manhattan)', 'charges' => $ny21Charges]],
    ];
}

// ===== New Haven Panther + Soledad/SQ6 + Angela Davis + Geronimo Pratt =====
$nhInst = ['name' => 'Connecticut state courts — New Haven Panther trials', 'city' => 'New Haven', 'state' => 'Connecticut'];
$nhCharges = 'New Haven Black Panther trials (1970-71): May 21, 1969 killing of suspected informant Alex Rackley in Middlefield, CT. Trial before Judge Harold M. Mulvey; Connecticut State\'s Attorney Arnold Markle.';

$nhSqsl = [];
foreach ([
    ['Bobby George Seale', 'Male', '1936-10-22', null, 'California', 'Co-founded the Black Panther Party with Huey P. Newton in Oakland October 1966 and served as Chairman. As Chicago Eight defendant, bound and gagged in court by Judge Julius Hoffman. Indicted in the New Haven case; jury deadlocked 11-1 for acquittal; charges dismissed May 25, 1971.', ['Black Panther Party (co-founder, Chairman)'], 'New Haven Panther trial', '1970-08-15', '1971-05-25', 'New Haven charges dismissed (jury 11-1 for acquittal); separately served 4 years contempt for Chicago 8 trial.'],
    ['Ericka Huggins', 'Female', '1948-01-05', null, 'Connecticut', 'Born Ericka Jenkins in Washington DC; widow of John Huggins (assassinated UCLA campus Jan 17, 1969). Founded New Haven BPP chapter 1969. Held with her infant daughter for two years on Niantic Prison; charges dismissed May 25, 1971 (jury 10-2 for acquittal). Later directed Oakland Community School (1973-1981).', ['Black Panther Party'], 'New Haven Panther trial', '1969-05-22', '1971-05-25', 'Charges dismissed after hung jury.'],
    ['Lonnie McLucas', 'Male', '1945-01-01', '2016-12-15', 'Connecticut', 'Bridgeport BPP member who admitted firing the chest shot that killed Alex Rackley but refused to plead guilty in exchange for testimony. The first of the New Haven trials began May 1970 and ended September 1, 1970 with conviction on the lesser charge of conspiracy to commit murder; sentenced 12-15 years.', ['Black Panther Party (Bridgeport)'], 'New Haven Panther trial', '1969-05-21', '1974-12-15', '12-15 years (conviction on conspiracy only); released on appeal bond 1974.'],
    ['Warren Aloysious Kimbro', 'Male', '1934-04-29', '2009-02-03', 'Connecticut', 'New Haven BPP member who fired the first shot into Alex Rackley\'s head in Middlefield, CT May 21, 1969. Pleaded guilty to second-degree murder and turned state\'s evidence; sentenced to mandatory life term, paroled after four years. After release attended Harvard\'s Graduate School of Education and led Project MORE for over 20 years.', ['Black Panther Party'], 'New Haven Panther trial', '1969-05-22', '1974-06-15', 'Life sentence; served 4 years.'],
] as $row) {
    [$name, $gender, $bd, $dd, $state, $bio, $affiliation, $caseInst, $arrest, $release, $sentence] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts); $middle = count($parts) >= 3 ? $parts[1] : null;
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => $gender, 'race' => 'Black', 'state' => $state,
        'birthdate' => $bd, 'death_date' => $dd, 'description' => $bio,
        'affiliation' => $affiliation, 'ideologies' => ['Black liberation', 'Revolutionary socialism'],
        'cases' => [['institution' => $nhInst, 'arrest_date' => $arrest, 'release_date' => $release, 'sentence' => $sentence, 'convicted' => str_contains($sentence, 'dismissed') || str_contains($sentence, 'acquittal') ? 'Charges dismissed' : 'Yes', 'judge' => 'Hon. Harold M. Mulvey', 'prosecutor' => 'Arnold Markle (CT State\'s Attorney)', 'charges' => $nhCharges]],
    ];
}

// ===== Soledad Brothers / San Quentin Six =====
foreach ([
    ['George Lester Jackson', 'Male', '1941-09-23', '1971-08-21', 'California', 'Sentenced at age 18 to one-year-to-life for stealing $71 from a gas station; spent the rest of his life imprisoned, ten years in solitary. Became a BPP Field Marshal and co-founded the Black Guerrilla Family. Indicted Feb 1970 with Drumgo and Clutchette for murder of guard John V. Mills (the Soledad Brothers case). His 1970 prison-letters book "Soledad Brother" became an international bestseller. Killed by San Quentin guards August 21, 1971; his death helped trigger the Attica uprising three weeks later.', ['Black Panther Party (Field Marshal)', 'Black Guerrilla Family (founder)'], '1960-12-15', '1971-08-21', 'Held pending trial when killed', false, 'death_in_custody'],
    ['Fleeta Drumgo', 'Male', '1945-05-31', '1979-11-24', 'California', 'One of the three Soledad Brothers charged with the January 16, 1970 murder of correctional officer John V. Mills. After George Jackson\'s death, tried with Clutchette in 1972; acquitted March 27, 1972 by a San Francisco jury. Then charged as one of the San Quentin Six; acquitted again August 12, 1976. Shot to death in Oakland November 24, 1979 by unknown assailants.', ['Black Guerrilla Family', 'Soledad Brothers'], '1970-02-14', '1976-08-12', 'Acquitted in both Soledad Brothers and San Quentin Six trials.', true, null],
    ['John Wesley Clutchette', 'Male', '1944-01-01', null, 'California', 'Third Soledad Brother charged with the January 16, 1970 killing of guard John V. Mills at Soledad State Prison. The Soledad Brothers Defense Committee (which included Angela Davis) organized worldwide solidarity. Acquitted by a San Francisco jury March 27, 1972 after three days of deliberation; granted parole November 13, 1972.', ['Soledad Brothers'], '1970-02-14', '1972-11-13', 'Acquitted; paroled Nov 13, 1972.', true, null],
    ['Hugo Antonio Pinell', 'Male', '1944-03-10', '2015-08-12', 'California', 'Born in Nicaragua; brought to California age 12. Pleaded guilty to a 1964 rape charge expecting parole in six months but received a 3-years-to-life sentence; became a key prison organizer alongside George Jackson. Charged as one of the San Quentin Six for the August 21, 1971 incident; convicted in 1976 of two counts of felony assault on a guard for cutting throats of two officers (both survived) and held in solitary confinement for 43 years. Killed in a prison riot August 12, 2015.', ['Black Guerrilla Family'], '1971-08-21', null, 'Life; killed in custody by Aryan Brotherhood-associated inmates.', false, 'death_in_custody'],
    ['Johnny Larry Spain', 'Male', '1949-09-30', null, 'California', 'Born Larry Michael Armstrong in Jackson, Mississippi to white mother and Black father; sent at age six to be raised by Black foster family in LA. Imprisoned at 17 for a fatal robbery; became a follower of George Jackson and the only San Quentin Six defendant convicted of murder August 12, 1976 — for the deaths of guards Frank DeLeon and Jere P. Graham. Conviction overturned by federal Judge Thelton Henderson because Spain had been shackled in 25-pound chains throughout trial. Paroled 1988 after 21 years incarceration.', ['Black Panther Party', 'Black Guerrilla Family'], '1971-08-21', '1988-12-15', 'Two life terms (overturned on appeal); paroled 1988.', true, null],
    ['Stephen Mitchell Bingham', 'Male', '1942-01-01', null, 'California', 'Civil rights attorney accused of smuggling a 9mm Astra pistol concealed in a tape recorder to George Jackson on August 21, 1971. Fled the United States, living underground in Eastern Europe and France for 13 years. With assistance from former Attorney General Ramsey Clark, surrendered in 1984. Tried in Marin County Superior Court 1986; found not guilty of conspiracy and murder on the jury\'s first ballot.', ['Movement attorney; allied with BPP/BGF defense'], '1984-12-15', '1986-12-15', 'Acquitted on first ballot.', true, null],
    ['Willie Tate', 'Male', '1944-01-01', null, 'California', 'Born in Selma, Alabama; raised in El Paso and Fresno. Charged as one of the San Quentin Six. After the 16-month longest-in-California-history trial, acquitted of all charges August 12, 1976; paroled 1976.', ['Black Guerrilla Family'], '1971-08-21', '1976-12-15', 'Acquitted on all counts.', true, null],
    ['David Johnson', 'Male', null, null, 'California', 'One of the six prisoners charged in the August 21, 1971 San Quentin Adjustment Center incident. After the longest trial in California history, convicted August 12, 1976 of one count of felony assault on a guard, drawing additional concurrent life sentence. Released on parole 1993.', ['Black Guerrilla Family'], '1971-08-21', '1993-12-15', 'Life sentence concurrent (one count assault).', true, null],
    ['Luis Talamantez', 'Male', null, null, 'California', 'One of the six men charged in the August 21, 1971 San Quentin uprising. After the 16-month trial, acquitted on all charges August 12, 1976; paroled. Went on to become a key organizer against control-unit prisons in California.', ['Black Guerrilla Family'], '1971-08-21', '1976-12-15', 'Acquitted on all counts.', true, null],
    ['Jonathan Peter Jackson', 'Male', '1953-06-23', '1970-08-07', 'California', '17-year-old younger brother of George Jackson. On August 7, 1970 carried a satchel of three firearms (registered to Angela Davis) into the Marin County Hall of Justice during the trial of San Quentin inmate James McClain. Took Judge Harold Haley, prosecutor Gary Thomas, and three jurors hostage demanding release of the Soledad Brothers. Killed in the ensuing shootout along with Judge Haley, James McClain, and William Christmas. Triggered the federal kidnapping/murder/conspiracy charges against Angela Davis.', ['Soledad Brothers Defense Committee'], null, '1970-08-07', 'Killed during incident.', false, 'death_in_custody'],
] as $row) {
    [$name, $gender, $bd, $dd, $state, $bio, $affiliation, $arrest, $release, $sentence, $released, $deathFlag] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts); $middle = count($parts) >= 3 ? $parts[1] : null;
    $caseFields = ['institution' => $soledadInst, 'arrest_date' => $arrest, 'release_date' => $release, 'sentence' => $sentence, 'convicted' => str_contains($sentence, 'cquitted') ? 'No — acquitted' : (str_contains($sentence, 'killed') ? 'Killed before verdict' : 'Yes'), 'charges' => 'Soledad Brothers / San Quentin Six prosecutions: murder of correctional officers, conspiracy, assault.'];
    if ($deathFlag === 'death_in_custody') $caseFields['death_in_custody_date'] = $dd;
    $isBlack = $name === 'Stephen Mitchell Bingham' ? 'White' : ($name === 'Hugo Antonio Pinell' ? 'Latino/Hispanic' : ($name === 'Luis Talamantez' ? 'Latino/Hispanic' : 'Black'));
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => $gender, 'race' => $isBlack, 'state' => $state,
        'birthdate' => $bd, 'death_date' => $dd, 'released' => $released, 'description' => $bio,
        'affiliation' => $affiliation, 'ideologies' => ['Black liberation', 'Revolutionary socialism', 'Prisoner liberation'],
        'cases' => [$caseFields],
    ];
}

// Angela Davis + Geronimo Pratt + Frank "Big Black" Smith
$people[] = ['name' => 'Angela Yvonne Davis', 'first_name' => 'Angela', 'middle_name' => 'Yvonne', 'last_name' => 'Davis', 'gender' => 'Female', 'race' => 'Black', 'state' => 'California', 'birthdate' => '1944-01-26', 'description' => 'Born in Birmingham, Alabama\'s "Dynamite Hill" neighborhood; UCLA philosophy professor twice fired by UC Regents at Governor Ronald Reagan\'s direction over her Communist Party membership. After Jonathan Jackson\'s August 7, 1970 raid on the Marin County Civic Center used firearms registered in her name, she went underground. Placed on the FBI Ten Most Wanted Fugitives list (the third woman ever); arrested at a Manhattan motel October 13, 1970. After 16 months in jail and a 13-week trial, acquitted by an all-white-and-Latino jury June 4, 1972 in San Jose.', 'affiliation' => ['Communist Party USA', 'Black Panther Party (allied)', 'Soledad Brothers Defense Committee', 'Che-Lumumba Club'], 'ideologies' => ['Marxism', 'Black feminism', 'Communism', 'Prison abolition'], 'cases' => [['institution' => ['name' => 'Santa Clara County Superior Court — People v. Davis', 'city' => 'San Jose', 'state' => 'California'], 'arrest_date' => '1970-10-13', 'release_date' => '1972-06-04', 'sentence' => 'Acquitted on all counts June 4, 1972.', 'convicted' => 'No — acquitted', 'judge' => 'Hon. Richard E. Arnason', 'prosecutor' => 'Albert Harris', 'charges' => 'California state: murder, kidnapping, conspiracy (related to August 7, 1970 Marin County Civic Center hostage-taking by Jonathan Jackson; Judge Harold Haley killed; firearms registered in Davis\'s name).']]];

$people[] = ['name' => 'Elmer Gerard Pratt', 'first_name' => 'Elmer', 'middle_name' => 'Gerard', 'last_name' => 'Pratt', 'aka' => 'Geronimo Pratt; Geronimo ji-Jaga', 'gender' => 'Male', 'race' => 'Black', 'state' => 'California', 'birthdate' => '1947-09-13', 'death_date' => '2011-06-02', 'description' => 'Born in Morgan City, Louisiana; decorated two-tour Vietnam War paratrooper (82nd Airborne; Purple Heart, Silver Star). Enrolled at UCLA 1968 where Alprentice "Bunchy" Carter recruited him into the BPP. Became Deputy Minister of Defense of the LA chapter after the December 1969 LAPD assault on Panther HQ. Targeted by FBI COINTELPRO; convicted 1972 for the December 18, 1968 Santa Monica tennis-court murder of teacher Caroline Olsen. Served 27 years (8 in solitary), maintaining FBI wiretaps proved he was 400 miles away in Oakland that day. June 10, 1997 Judge Everett Dickey vacated his conviction after finding the prosecution\'s key witness Julius Butler was an undisclosed paid informant. Died in Tanzania 2011.', 'affiliation' => ['Black Panther Party (Deputy Minister of Defense, LA chapter)'], 'ideologies' => ['Black revolutionary', 'Anti-imperialism'], 'cases' => [['institution' => ['name' => 'Orange County Superior Court — Pratt habeas vacatur', 'city' => 'Santa Ana', 'state' => 'California'], 'arrest_date' => '1970-12-08', 'sentenced_date' => '1972-07-15', 'release_date' => '1997-06-10', 'sentence' => 'Life imprisonment (vacated June 10, 1997).', 'convicted' => 'Yes; vacated 1997', 'judge' => 'Hon. Kathleen Parker (1972 trial); Hon. Everett W. Dickey (1997 vacatur)', 'prosecutor' => 'Richard Kalustian (1972)', 'charges' => 'Murder, robbery, kidnapping (Santa Monica tennis-court murder of Caroline Olsen, December 18, 1968).']]];

$people[] = ['name' => 'Frank "Big Black" Smith', 'first_name' => 'Frank', 'last_name' => 'Smith', 'aka' => 'Big Black', 'gender' => 'Male', 'race' => 'Black', 'state' => 'New York', 'birthdate' => '1933-09-11', 'death_date' => '2004-07-29', 'description' => 'Born to cotton farmers in Bennettsville, SC; raised in Brooklyn. Serving 10-15 years at Attica for robbing an after-hours dice game when the September 1971 uprising broke out. As prison football coach, elected by acclamation to lead D-Yard security for both inmates and civilian observers. After the state retook the prison, singled out for prolonged torture: forced to lie naked on a table holding a football for hours under threat of castration. Paroled 1973 after 8.5 years; became leader of the Attica Defense Committee and lead plaintiff in the prisoner reparations lawsuit, which won a $12 million settlement in 2000.', 'affiliation' => ['Attica Brothers', 'Attica Defense Committee'], 'ideologies' => ['Prisoner rights', 'Black liberation'], 'cases' => [['institution' => ['name' => 'Attica Correctional Facility — Attica Brothers prisoner uprising 1971', 'city' => 'Attica', 'state' => 'New York'], 'arrest_date' => '1965-06-15', 'release_date' => '1973-12-15', 'sentence' => '10-15 years (original robbery); paroled 1973; no successful state charge from uprising.', 'convicted' => 'Yes (original robbery); no charge stemming from uprising stuck', 'charges' => 'Robbery (original); state filed no successful charge from uprising — Smith led D-Yard security and was severely tortured by guards during state retaking.']]];

// ===== AIM / Wounded Knee 1973 =====
foreach ([
    ['Carter Augustus Camp', 'Ponca', 'Oklahoma', '1941-08-18', '2013-12-27', 'Ponca AIM leader from Pawnee, Oklahoma; Haskell Institute graduate; U.S. Army veteran (Berlin 1960-63). One of the primary organizers of the 1973 Wounded Knee occupation alongside Russell Means and Dennis Banks; led the first group of AIM members who seized the trading post. Elected national chair of AIM 1973. Pleaded guilty to one count and served 3 years federal prison.', '1973-04-15', '1976-12-15', '3 years federal prison (pleaded guilty to one count).'],
    ['Clyde Howard Bellecourt', 'Ojibwe', 'Minnesota', '1936-05-08', '2022-01-11', 'Co-founder and first chairman of AIM, born on White Earth Reservation in Minnesota. Helped organize AIM Patrol, Heart of the Earth Survival School, and 1972 Trail of Broken Treaties. Indicted on federal charges related to the Wounded Knee occupation; charges dismissed/dropped. Last surviving co-founder at his 2022 death.', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['Vernon Franklin Bellecourt', 'Ojibwe', 'Minnesota', '1931-10-17', '2007-10-13', 'Older brother of AIM co-founder Clyde Bellecourt; emerged as AIM\'s national director and chief international spokesperson. Briefly present at Wounded Knee 1973; served principally as occupation\'s outside fundraiser and press liaison. Indicted for related federal offenses. Led AIM\'s international diplomacy with Sandinista Nicaragua, Libya, and the PLO; headed National Coalition on Racism in Sports and Media.', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['Stanley Robert Holder', 'Wichita', 'Oklahoma', null, null, 'Wichita Vietnam War veteran; head of security and warrior society commander during the 1973 Wounded Knee occupation; senior AIM organizer in Oklahoma and Texas. Indicted along with the rest of the Wounded Knee leadership on multiple federal felonies. Prosecution affected by the September 1974 dismissals; later participated in BIA building takeover prosecutions and the 1978 Longest Walk.', '1973-04-15', '1974-12-15', 'Charges dismissed/reduced.'],
    ['Pedro Aloysius Bissonette', 'Oglala Lakota', 'South Dakota', '1944-04-20', '1973-10-17', 'Co-founder of the Oglala Sioux Civil Rights Organization (OSCRO) and the principal Pine Ridge organizer who invited AIM onto the reservation in February 1973 to confront tribal chairman Dick Wilson. Key leader inside Wounded Knee. Arrested August 1973; offered probation in exchange for cooperative testimony against Banks and Means; threatened with 99 years if he refused. Refused. October 17, 1973 BIA police shotgunned him to death at point-blank range on Pine Ridge — AIM and family witnesses called it an assassination to silence the defense\'s key witness.', '1973-08-27', null, 'Killed by BIA police October 17, 1973 before trial.'],
    ['Anna Mae Pictou Aquash', 'Mi\'kmaq', 'South Dakota', '1945-03-27', '1975-12-12', 'Born near Shubenacadie, Nova Scotia; one of AIM\'s most prominent women organizers. Participated in the 1972 Trail of Broken Treaties and 1973 Wounded Knee occupation; worked in AIM\'s St. Paul office in early 1974 and led AIM\'s Los Angeles office later that year. Suspected by some AIM members of being an FBI informant (which she denied); kidnapped and murdered execution-style on Pine Ridge December 1975; body found February 24, 1976. Arlo Looking Cloud (2003) and John Graham (2010) later convicted of her murder.', '1973-04-15', null, 'Murdered execution-style December 1975 on Pine Ridge.'],
    ['Madonna Thunder Hawk', 'Lakota', 'South Dakota', null, null, 'Joined AIM in 1968. Participated in Alcatraz, BIA HQ, Custer Courthouse, and Wounded Knee occupations. During the 71-day Wounded Knee siege served as a medic and was a member of the "Pie Patrol" alongside Lorelei DeCora Means, Thelma Rios, Theda Nelson Clarke, and Mary Crow Dog. In 1974 co-founded Women of All Red Nations (WARN) and the Black Hills Alliance.', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['Phyllis Young', 'Lakota', 'South Dakota', '1949-02-24', null, 'Born on the Standing Rock Reservation; central role in AIM and as a founding member of Women of All Red Nations (WARN) in 1974. WARN\'s signature campaign exposed the forced sterilization of 3,406 American Indian women between 1973-1976. Helped coordinate the first UN conference on Indians of the Americas in Geneva (1977); led the 2016-17 anti-Dakota Access Pipeline struggle.', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['William Means', 'Oglala Lakota', 'South Dakota', null, null, 'Twin brother of Ted Means and younger brother of Russell Means. Participated in the Wounded Knee 1973 occupation. In 1974 co-founded the International Indian Treaty Council (IITC), AIM\'s UN-recognized international diplomatic arm; has led IITC for decades.', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['Severt Young Bear', 'Oglala Lakota', 'South Dakota', '1934-01-01', '1993-12-15', 'Of Porcupine District, Pine Ridge Reservation; descendant of chiefs and Wounded Knee 1890 survivors who supported AIM during Wounded Knee II. Founder and lead singer of the Porcupine Singers; credited with composing/popularizing the AIM Song. Music/dance consultant for "Dances with Wolves" and "Thunderheart."', '1973-04-15', '1974-12-15', 'Charges dismissed/dropped.'],
    ['Sarah Bad Heart Bull', 'Oglala Lakota', 'South Dakota', '1929-01-01', '2013-02-18', 'Mother of Wesley Bad Heart Bull who was stabbed to death January 21, 1973 by Darrell Schmitz in Buffalo Gap, SD. The prosecutor\'s decision to charge Schmitz only with second-degree manslaughter prompted her to ask AIM to organize a rally at the Custer County courthouse February 6, 1973. When police struck her in the face with a baton on the courthouse steps, the riot began. Convicted of inciting a riot; received indeterminate 1-5 year sentence; served 5 months. Her son\'s killer served no prison time.', '1973-02-06', '1973-07-15', '1-5 year indeterminate (fixed at 1 year); served 5 months.'],
    ['Robert Eugene Robideau', 'Ojibwe', 'Oregon', '1946-11-11', '2009-02-17', 'Born in Portland, Oregon; Leonard Peltier\'s cousin. Held degrees from Portland State and the Institute of American Indian Arts. Present at the June 26, 1975 Jumping Bull Compound shootout. September 10, 1975 ammunition exploded in Peltier\'s station wagon on the Kansas Turnpike, seriously injuring Robideau and exposing Agent Coler\'s revolver. Tried with Darrelle Butler in Cedar Rapids 1976; both acquitted on self-defense grounds. Died in Barcelona 2009 from complications of shrapnel.', '1975-09-15', '1976-09-15', 'Acquitted (Cedar Rapids 1976).'],
    ['Darrelle Dean Butler', 'Native American', 'South Dakota', null, null, 'AIM member present at the Jumping Bull Compound on June 26, 1975, when FBI agents Coler and Williams and AIM\'s Joe Stuntz were killed. Charged November 17, 1975 with two counts of first-degree murder; tried jointly with Bob Robideau in U.S. District Court Cedar Rapids, Iowa. Acquitted summer 1976 after their defense argued the agents\' approach in unmarked cars amid Pine Ridge\'s GOON-squad violence justified self-defense.', '1975-11-17', '1976-09-15', 'Acquitted (Cedar Rapids 1976).'],
    ['Joseph Killsright Stuntz Sr.', 'Coeur d\'Alene', 'Idaho', '1951-10-22', '1975-06-26', 'Born Joseph George on the Lapwai Reservation in Idaho; at age seven placed in a federal Indian boarding school in Indiana and later adopted by a white couple named Stuntz. AIM member at the Jumping Bull Compound on Pine Ridge June 26, 1975. Killed by a long-range shot through the head — presumably by an FBI sniper — body found wearing an FBI jacket from Agent Coler\'s trunk. His death was never investigated.', null, null, 'Killed before charges; the FBI never investigated his death.'],
    ['James Theodore Eagle', 'Oglala Lakota', 'South Dakota', null, null, 'AIM-affiliated Oglala Lakota teenager whose alleged theft of cowboy boots became the pretext for FBI Agents Coler and Williams to enter the Jumping Bull Compound June 26, 1975. Charged November 17, 1975 with two counts of first-degree murder along with Peltier, Robideau, and Butler. Charges voluntarily dismissed when prosecutors admitted he had not been on the reservation that day; FBI memo stated charges were dropped to focus prosecution on Peltier.', '1975-11-17', '1976-12-15', 'Charges dismissed.'],
    ['Paul Skyhorse Durant', 'Native American', 'California', null, null, 'AIM organizer arrested with Richard Mohawk Billings for the October 10, 1974 murder of Los Angeles taxi driver George Aird at the Box Canyon AIM campsite. Spent about four years incarcerated awaiting trial. Acquitted May 24, 1978 after defense established that the campsite had been set up by FBI/COINTELPRO informant Douglas Durham and that informant Virginia Blue Dove De Luce had lured them to the site as part of an effort to discredit AIM.', '1974-10-15', '1978-05-24', 'Acquitted May 24, 1978 after ~4 years pretrial detention.'],
    ['Richard Mohawk Billings', 'Native American', 'California', null, null, 'AIM organizer arrested with Paul Skyhorse Durant for the October 10, 1974 murder of taxi driver George Aird in Los Angeles. Held about four years awaiting trial; acquitted May 24, 1978 by a Los Angeles jury that accepted the defense argument that COINTELPRO informants had set up the Box Canyon campsite and framed both men.', '1974-10-15', '1978-05-24', 'Acquitted May 24, 1978 after ~4 years pretrial detention.'],
    ['Richard Oakes', 'Mohawk', 'California', '1942-05-22', '1972-09-20', 'Born at the Akwesasne Mohawk Reservation; left school at 16 for ironworking; attended San Francisco State University where he helped create one of the first American Indian Studies programs. With LaNada Boyer led the November 20, 1969 occupation of Alcatraz Island by Indians of All Tribes, lasting 19 months. Left the island after his stepdaughter Yvonne died in a fall January 5, 1970. Unarmed when shot and killed September 20, 1972 in Sonoma County; his killer was acquitted of voluntary manslaughter on a self-defense claim.', '1969-11-20', null, 'Killed September 20, 1972; killer acquitted.'],
    ['LaNada Vernae War Jack', 'Shoshone-Bannock', 'Idaho', '1947-01-01', null, 'Born on Fort Hall Indian Reservation; one of the first Native students admitted to UC Berkeley 1968. Founded Native American Student Organization; leader of the 1969 Third World Strike. Co-led the 19-month Alcatraz Occupation (Nov 1969 - June 1971) with Richard Oakes. PhD Idaho State 1999; Distinguished Professor at Boise State teaching federal Indian law.', '1969-11-20', '1971-06-15', 'Trespass / conspiracy at Alcatraz.'],
    ['John Trudell', 'Santee Dakota', 'Nevada', '1946-02-15', '2015-12-08', 'Santee Dakota; broadcast voice of Radio Free Alcatraz during the 1969-71 occupation. AIM\'s National Chairman from 1973 to 1979. February 11, 1979 burned an American flag during a demonstration at FBI headquarters in Washington DC. Less than 12 hours later, his pregnant wife Tina Manning, their three children, and his mother-in-law died in a fire at their home on the Duck Valley Reservation in Nevada. BIA police ruled it accidental; Trudell believed it was arson. Became a poet, musician, and actor before his death from cancer 2015. His FBI file ran to 17,000 pages.', '1969-11-20', '1971-06-15', 'Various AIM-related federal charges.'],
    ['Leonard Crow Dog', 'Sicangu Lakota', 'South Dakota', '1942-08-18', '2021-06-06', 'Sicangu Lakota medicine man from Rosebud Reservation; AIM\'s principal spiritual leader during the 1972 Trail of Broken Treaties and 1973 Wounded Knee occupation. Revived the banned Ghost Dance and hosted intertribal Sun Dances at Crow Dog\'s Paradise. Convicted at three subsequent trials with sentences totaling 23 years. September 1975, 185 FBI/marshals/SWAT raided his property looking for Leonard Peltier and arrested him; held in solitary at Leavenworth.', '1973-04-15', '1977-12-15', 'Suspended sentence (Wounded Knee); 23 years total across 3 trials.'],
    ['Mary Brave Bird', 'Sicangu Lakota', 'South Dakota', '1954-09-26', '2013-02-14', 'Sicangu Lakota writer and activist who joined AIM at age 18. Participated in 1972 Trail of Broken Treaties and 1973 Wounded Knee occupation, where, eight months pregnant, she gave birth to her son Pedro during a firefight. Married Leonard Crow Dog. Memoirs "Lakota Woman" (1990) and "Ohitika Woman" (1993) are foundational AIM-era texts.', '1973-04-15', '1974-12-15', 'Multiple AIM arrests.'],
] as $row) {
    [$name, $tribe, $state, $bd, $dd, $bio, $arrest, $release, $sentence] = $row;
    $parts = explode(' ', $name); $first = $parts[0]; $last = end($parts); $middle = count($parts) >= 3 ? $parts[1] : null;
    $convicted = str_contains($sentence ?? '', 'cquitted') || str_contains($sentence ?? '', 'dismissed') ? 'No — charges dismissed/acquitted' : (str_contains($sentence ?? '', 'illed') ? 'Killed before trial' : 'Yes');
    $caseFields = ['institution' => $wkInst, 'arrest_date' => $arrest, 'release_date' => $release, 'sentence' => $sentence, 'convicted' => $convicted, 'judge' => 'Hon. Fred J. Nichol (D. Minn., for Wounded Knee Leadership Trial)', 'prosecutor' => 'R. D. Hurd (federal)', 'charges' => $wkCharges];
    if (str_contains($sentence ?? '', 'illed') || $name === 'Pedro Aloysius Bissonette' || $name === 'Anna Mae Pictou Aquash' || $name === 'Joseph Killsright Stuntz Sr.' || $name === 'Richard Oakes') {
        $caseFields['death_in_custody_date'] = $dd;
    }
    $people[] = [
        'name' => $name, 'first_name' => $first, 'middle_name' => $middle, 'last_name' => $last,
        'gender' => str_contains($name, 'Mary Brave') || str_contains($name, 'Madonna') || str_contains($name, 'Phyllis') || str_contains($name, 'Sarah') || str_contains($name, 'LaNada') || str_contains($name, 'Anna Mae') ? 'Female' : 'Male',
        'race' => 'Native American', 'state' => $state,
        'birthdate' => $bd, 'death_date' => $dd,
        'released' => ! str_contains($sentence ?? '', 'illed'),
        'description' => $bio,
        'affiliation' => str_contains($name, 'Bissonette') ? ['Oglala Sioux Civil Rights Organization (OSCRO)', 'AIM supporter'] : (str_contains($name, 'Oakes') || str_contains($name, 'War Jack') ? ['Indians of All Tribes (Alcatraz Occupation)'] : ['American Indian Movement (AIM)']),
        'ideologies' => ['Indigenous sovereignty', 'Treaty rights', 'Red Power'],
        'cases' => [$caseFields],
    ];
}

// ===== Apply =====
foreach ($people as $p) {
    $p['era'] = $p['era'] ?? '1970s';
    [$prisoner, $created] = addP($p);
    echo ($created ? '  CREATED' : '  EXISTS ') . " {$p['name']} (id={$prisoner->id})\n";
    $created ? $tot['created']++ : $tot['existed']++;
    foreach ($p['cases'] ?? [] as $c) {
        if (attachC($prisoner, $c)) { echo "    + case ({$c['arrest_date']})\n"; $tot['cases']++; }
    }
}

echo "\nDone.\n";
echo "  prisoners created:        {$tot['created']}\n";
echo "  prisoners already existed: {$tot['existed']}\n";
echo "  cases added:              {$tot['cases']}\n";
