#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round16_panther21_sla_huggins.sh
#
# Source clusters:
#   - Dhoruba bin Wahad (Richard Moore) - Panther 21 + 1971 BLA-attributed
#     attempted murder of NYPD officers; 19 years in NY state prison; 1990
#     release after COINTELPRO Brady evidence revealed
#   - Ericka Huggins + New Haven Black Panther trial (1969 Alex Rackley
#     case; jury hung 10-2 for acquittal May 1971)
#   - SLA non-Olson (James Kilgore, Bill Harris, Emily Harris/Montague,
#     Michael Bortin) - 2003 plea on the April 1975 Carmichael bank
#     robbery in which Myrna Opsahl was killed
#   - Russell Means - AIM co-founder; multiple South Dakota state and
#     federal prosecutions; Wounded Knee 1973 federal charges dismissed
#     for FBI misconduct September 1974
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Dhoruba Bin Wahad ===

php artisan prisoner:add '{"name":"Dhoruba Bin Wahad","first_name":"Richard","last_name":"Moore","aka":"Dhoruba al-Mujahid bin Wahad","description":"Dhoruba al-Mujahid bin Wahad, born Richard Moore in The Bronx in 1944, was a leader of the New York chapter of the Black Panther Party, one of the original Panther 21 defendants acquitted in May 1971, a co-founder of the Black Liberation Army after the 1971 BPP split, and one of the longest-litigated U.S. COINTELPRO cases.\n\nIn June 1971, while still a fugitive after the BPP-East/West split, he was arrested for the May 19, 1971 attempted murder of two NYPD officers in a Manhattan attack he and his defense have always argued he did not commit. He was convicted in March 1973 in New York State Supreme Court and sentenced to 25 years to life. He served 19 years in the Auburn, Attica, and other New York state prisons. In 1990 New York State Supreme Court Justice Peter J. McQuillan vacated his conviction after federal litigation forced disclosure of more than 300,000 pages of FBI COINTELPRO file material that had not been provided to the defense at trial — including evidence that the principal prosecution witness had been pressured by the FBI to identify him. He was released on March 22, 1990 after 19 years. He won monetary settlements from the FBI in 1995 and from the New York City Police Department in 2000. He has lived in Ghana for many years; he co-edited Look for Me in the Whirlwind (PM Press, 2017) about the Panther 21.","state":"New York","race":"Black","gender":"Male","birthdate":"1944-09-11","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Panther 21","Black Liberation Army"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"New York Department of Corrections (Auburn, Attica, etc.)","institution_state":"New York","charges":"New York state attempted murder of two NYPD officers, May 19, 1971; conviction vacated 1990 after FBI COINTELPRO Brady-evidence disclosure","arrest_date":"1971-06-05","incarceration_date":"1971-06-05","release_date":"1990-03-22","sentence":"25 years to life; vacated after 19 years","convicted":"Yes - New York state jury verdict, March 1973 (vacated March 1990)"}]}' || true

# === Ericka Huggins ===

php artisan prisoner:add '{"name":"Ericka Huggins","first_name":"Ericka","last_name":"Huggins","description":"Ericka Huggins was a leader of the New Haven, Connecticut chapter of the Black Panther Party. After the May 21, 1969 killing of Alex Rackley in a New Haven Panthers safe house — Rackley had been suspected internally of being a police informant — she was arrested with seven other Panthers. The federal prosecution charged Bobby Seale (who was not in New Haven at the time of the killing) and Huggins with the murder, kidnapping, and conspiracy. The trial of Seale and Huggins began in November 1970 and ran into May 1971. The jury deadlocked 10-2 for her acquittal and 11-1 for Seale s; Judge Harold Mulvey dismissed all charges with prejudice on May 25, 1971. She had been held in pretrial detention at the Niantic State Farm for Women in Connecticut for two years; her infant daughter Mai was raised in the Panther community during her detention.\n\nAfter the trial she returned to Oakland and became the Director of the Oakland Community School from 1973 to 1981 — the BPP-founded K-6 school in East Oakland that won state and national education awards under her leadership. She has been a longtime educator and writer in the years since.","state":"Connecticut","race":"Black","gender":"Female","birthdate":"1948-01-05","ideologies":["Black Liberation"],"affiliation":["Black Panther Party","Oakland Community School"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Niantic State Farm for Women","institution_state":"Connecticut","charges":"Connecticut state murder, kidnapping, and conspiracy - May 1969 killing of Alex Rackley in New Haven","arrest_date":"1969-05-22","incarceration_date":"1969-05-22","release_date":"1971-05-25","sentence":"Held in pretrial detention 2 years","convicted":"No - jury deadlocked 10-2 for acquittal; charges dismissed with prejudice May 25, 1971"}]}' || true

# === SLA - non-Olson ===

php artisan prisoner:add '{"name":"James Kilgore","first_name":"James","last_name":"Kilgore","description":"James William Kilgore was a member of the Symbionese Liberation Army from 1974. After the May 17, 1974 LAPD-FBI raid that killed six SLA members in South Central Los Angeles, he and the surviving members went underground. He left the United States in 1975, lived under various assumed identities for 27 years, and from the late 1980s built a life in Cape Town, South Africa, where he became an academic and lecturer at the University of Cape Town. He was identified and arrested in Cape Town on November 8, 2002.\n\nHe was extradited to the United States and pleaded guilty in May 2003 to second-degree murder in connection with the April 21, 1975 SLA bank robbery in Carmichael, California in which a customer named Myrna Opsahl was killed. He was sentenced to 6 years in California state prison and was released on parole in May 2009. He has since become a leading academic on U.S. mass incarceration and the author of several books, including the prison-abolition introduction Understanding Mass Incarceration (2015).","state":"California","race":"White","gender":"Male","birthdate":"1947-12-26","ideologies":["Anti-imperialist","Symbionese Liberation Army"],"affiliation":["Symbionese Liberation Army"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"California state second-degree murder - April 21, 1975 SLA bank robbery in Carmichael, California","arrest_date":"2002-11-08","incarceration_date":"2003-05-12","sentenced_date":"2003-05-12","release_date":"2009-05-12","sentence":"6 years California state prison","convicted":"Yes - guilty plea, Sacramento County Superior Court, May 2003"}]}' || true

php artisan prisoner:add '{"name":"Bill Harris","first_name":"William","last_name":"Harris","description":"William Taylor Harris was a co-founder and one of the most senior members of the Symbionese Liberation Army. He was a U.S. Marine Corps Vietnam War veteran. He was arrested with his wife Emily in San Francisco on September 18, 1975, ending the SLA underground period that had begun with the February 4, 1974 kidnapping of Patty Hearst. He was convicted in 1978 of kidnapping Hearst and sentenced to 11 years; he was paroled in 1983.\n\nIn 2002 he and Emily Harris were re-indicted along with James Kilgore, Sara Jane Olson, and Michael Bortin for the April 21, 1975 SLA bank robbery in Carmichael, California in which a customer named Myrna Opsahl was killed. He pleaded guilty in February 2003 to second-degree murder and was sentenced to 7 years in California state prison. He was released in 2011.","state":"California","race":"White","gender":"Male","birthdate":"1945-01-22","ideologies":["Anti-imperialist","Symbionese Liberation Army"],"affiliation":["Symbionese Liberation Army","U.S. Marine Corps (Vietnam, former)"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"California state kidnapping (1978 Patty Hearst conviction); 2003 second-degree murder plea on the April 1975 SLA Carmichael bank robbery","arrest_date":"1975-09-18","incarceration_date":"1975-09-18","release_date":"2011-03-10","sentence":"11 years (1978) + 7 years (2003) consecutive","convicted":"Yes - 1978 California state kidnapping conviction; 2003 California state second-degree murder plea"}]}' || true

php artisan prisoner:add '{"name":"Emily Harris","first_name":"Emily","last_name":"Harris","aka":"Emily Montague","description":"Emily Harris (later Emily Montague) was a co-founder of the Symbionese Liberation Army with her then-husband William Harris. She was arrested with him in San Francisco on September 18, 1975, ending the SLA underground. She was convicted in 1978 of kidnapping Patty Hearst and sentenced to 11 years; she was paroled in 1983. In 2002 she was re-indicted along with William Harris, James Kilgore, Sara Jane Olson, and Michael Bortin for the April 21, 1975 Carmichael bank robbery in which Myrna Opsahl was killed. She pleaded guilty in February 2003 to second-degree murder and was sentenced to 8 years in California state prison. She was released in early 2011.","state":"California","race":"White","gender":"Female","birthdate":"1947-02-11","ideologies":["Anti-imperialist","Symbionese Liberation Army"],"affiliation":["Symbionese Liberation Army"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"California state kidnapping (1978 Patty Hearst conviction); 2003 second-degree murder plea on the April 1975 SLA Carmichael bank robbery","arrest_date":"1975-09-18","incarceration_date":"1975-09-18","release_date":"2011-02-15","sentence":"11 years (1978) + 8 years (2003) consecutive","convicted":"Yes - 1978 California state kidnapping conviction; 2003 California state second-degree murder plea"}]}' || true

php artisan prisoner:add '{"name":"Michael Bortin","first_name":"Michael","last_name":"Bortin","description":"Michael Bortin was a Berkeley student in 1974 and a peripheral SLA recruit. He was named in the 2002 California Attorney Generals re-indictment of SLA survivors for the April 21, 1975 SLA bank robbery in Carmichael, California in which Myrna Opsahl was killed. He pleaded guilty in February 2003 to second-degree murder and was sentenced to 6 years in California state prison. He was released in 2009.","state":"California","race":"White","gender":"Male","birthdate":"1948-09-09","ideologies":["Anti-imperialist","Symbionese Liberation Army"],"affiliation":["Symbionese Liberation Army"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"California state second-degree murder - April 21, 1975 SLA Carmichael bank robbery","arrest_date":"2003-02-15","incarceration_date":"2003-02-15","release_date":"2009-02-15","sentence":"6 years California state prison","convicted":"Yes - guilty plea, Sacramento County Superior Court, February 2003"}]}' || true

# === Russell Means ===

php artisan prisoner:add '{"name":"Russell Means","first_name":"Russell","middle_name":"Charles","last_name":"Means","description":"Russell Charles Means (Oglala Lakota name Wanbli Ohitika, Brave Eagle) was a co-founder of the American Indian Movement, the principal spokesperson of the 71-day February-May 1973 occupation of Wounded Knee, South Dakota with Dennis Banks, and one of the most public Native American activists of the twentieth century.\n\nFederal charges against him and Banks for the Wounded Knee occupation were dismissed by U.S. District Judge Fred J. Nichols on September 16, 1974 on the grounds of governmental misconduct - FBI false witness testimony, illegal surveillance, and an attempted cover-up of military involvement in the 71-day siege. He was subsequently prosecuted in South Dakota state court for the 1974 Sioux Falls Courthouse riot (acquitted on appeal) and the 1975 Wounded Knee II shooting incident on the Pine Ridge Reservation; he served approximately one year in South Dakota state prison in 1979-80. He was a Libertarian Party candidate for U.S. President in 1988 and starred as Chingachgook in the 1992 film The Last of the Mohicans. He died on October 22, 2012, age 72.","state":"South Dakota","race":"Native American","gender":"Male","birthdate":"1939-11-10","death_date":"2012-10-22","ideologies":["Indigenous sovereignty","American Indian Movement"],"affiliation":["American Indian Movement","Oglala Lakota"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"South Dakota Department of Corrections","institution_state":"South Dakota","charges":"South Dakota state riot and assault charges (1974 Sioux Falls Courthouse and 1975 Wounded Knee II); Wounded Knee 1973 federal charges dismissed September 1974 for FBI misconduct","arrest_date":"1979-08-15","incarceration_date":"1979-08-15","release_date":"1980-08-15","sentence":"~1 year South Dakota state prison","convicted":"Yes - South Dakota state convictions; Wounded Knee federal charges dismissed for misconduct"}]}' || true

# === Patty Hearst (controversial inclusion) ===

php artisan prisoner:add '{"name":"Patty Hearst","first_name":"Patricia","middle_name":"Campbell","last_name":"Hearst","description":"Patricia Campbell Hearst, granddaughter of newspaper magnate William Randolph Hearst, was kidnapped from her Berkeley apartment on February 4, 1974 by members of the Symbionese Liberation Army. She was held in a closet for 57 days, sexually abused, and on April 15, 1974 took part — under the SLA name Tania — in the SLA armed robbery of the Hibernia Bank in San Francisco. She was apprehended on September 18, 1975 in San Francisco. She was convicted on March 20, 1976 in U.S. District Court of armed bank robbery and use of a firearm in commission of a felony, and sentenced to 7 years in federal prison. The defense had argued that her actions were the product of coercion and Stockholm-syndrome conditions of her captivity.\n\nPresident Carter commuted her sentence on January 29, 1979 after she had served 22 months at the Federal Reformatory for Women at Pleasanton, California. President Clinton granted her a full pardon on his last day in office, January 20, 2001. Her case is included in this database with the qualification that her status as a political prisoner is contested - the federal prosecution treated her as a willing SLA participant; the SLA treated her as a captive.","state":"California","race":"White","gender":"Female","birthdate":"1954-02-20","ideologies":["Symbionese Liberation Army (under captivity)"],"affiliation":["Symbionese Liberation Army (under captivity)"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Reformatory for Women, Pleasanton","institution_city":"Pleasanton","institution_state":"California","charges":"Federal armed bank robbery and use of a firearm in commission of a felony - April 15, 1974 SLA Hibernia Bank robbery in San Francisco (defense: action under captivity coercion)","arrest_date":"1975-09-18","incarceration_date":"1976-03-20","sentenced_date":"1976-09-24","release_date":"1979-01-29","sentence":"7 years federal prison; commuted by President Carter January 29, 1979 after 22 months; full pardon by President Clinton January 20, 2001","convicted":"Yes - federal jury verdict, U.S. District Court for the Northern District of California, March 20, 1976"}]}' || true

echo
echo "Round 16 (Dhoruba bin Wahad + Ericka Huggins + SLA + Russell Means + Patty Hearst) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
