#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round9_more_post911_aim.sh
#
# Source clusters:
#   - Tarek Mehanna (Boston federal jury 2011) — 17.5 yrs federal for
#     translating al-Qaida media, widely considered a First Amendment case
#   - Newburgh Four (May 2009 FBI sting in Newburgh NY, 25-yr federal
#     sentences; 3 of 4 had sentences reduced to time served July 2023 by
#     U.S. District Judge Colleen McMahon, who called the FBI's role the
#     "real lead conspirator")
#   - Holy Land Foundation 5 (Dallas federal jury 2008) — material support
#     to Hamas via Palestinian zakat committees; 15-65 yr federal sentences
#   - American Indian Movement (Pine Ridge / RESMURS) — Dennis Banks
#     (Wounded Knee 1973 occupation, served 14 months 1985-86 in custody)
#     and the two RESMURS defendants acquitted in 1976 (Robideau, Butler);
#     Leonard Peltier likely already in DB
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Tarek Mehanna ===

php artisan prisoner:add '{"name":"Tarek Mehanna","first_name":"Tarek","last_name":"Mehanna","description":"Tarek Mehanna is an Egyptian-American pharmacist from Sudbury, Massachusetts who became one of the most contested First Amendment political-prisoner cases of the post-9/11 era. He was arrested in October 2009 on federal charges arising from his translation of al-Qaida media into English on the internet and a 2004 trip to Yemen with a friend. The prosecution alleged he had sought military training abroad; the defense argued that no such training was sought or received and that the prosecution was punishing protected speech. He was convicted by a Boston federal jury on December 20, 2011 of conspiracy to provide material support to al-Qaida, conspiracy to commit murder abroad, providing material support to terrorists, and lying to federal investigators.\n\nOn April 12, 2012 he was sentenced to 17.5 years in federal prison; his 20-minute sentencing statement to the court — defending the right of an American Muslim to believe that U.S. wars in Muslim countries are unjust — became one of the most widely circulated political statements from a U.S. federal courtroom in the post-9/11 era. The American Civil Liberties Union and dozens of First Amendment organizations have argued that his prosecution criminalized translation and protected speech. He is held at the federal Communications Management Unit at Marion, Illinois.","state":"Massachusetts","race":"Arab","gender":"Male","birthdate":"1982-09-24","ideologies":["Islam","First Amendment","Anti-imperialist"],"affiliation":[],"era":"2010s","in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal conspiracy to provide material support to al-Qaida, conspiracy to commit murder abroad, providing material support to terrorists, and lying to federal investigators — translation of al-Qaida media and 2004 trip to Yemen","arrest_date":"2009-10-21","incarceration_date":"2009-10-21","sentenced_date":"2012-04-12","sentence":"17.5 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Massachusetts, December 20, 2011"}]}' || true

# === Newburgh Four ===

php artisan prisoner:add '{"name":"James Cromitie","first_name":"James","last_name":"Cromitie","description":"James Cromitie was a Newburgh, New York Walmart employee and convicted petty criminal at the time he was approached in June 2008 by FBI informant Shahed Hussein — the same informant who had run the Albany pizzeria sting against Yassin Aref and Mohammed Mosharref Hossain. Hussein, posing as a Pakistani jihadist with access to weapons and money, offered Cromitie up to $250,000 to participate in a fictional plot to bomb Riverdale-area Bronx synagogues and shoot Stinger missiles at military aircraft. Over eight months Cromitie recruited three Newburgh acquaintances — Onta Williams, David Williams, and Laguerre Payen.\n\nU.S. District Judge Colleen McMahon found at trial in 2010 that the entire plot had been provided by the FBI: Hussein chose the targets, paid for groceries, bought the (fake) bombs and missile, assembled the devices, and drove the defendants to and from the May 20, 2009 staged action in the Bronx. She nonetheless convicted under federal law and sentenced all four men to the 25-year mandatory minimum. In a 2023 ruling she granted compassionate release to three of the four, writing that the real lead conspirator was the United States. Cromitie completed his 25-year sentence and was released on April 17, 2024 from FCI Allenwood Medium.","state":"New York","race":"Black","gender":"Male","ideologies":["Islam"],"affiliation":[],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"FCI Allenwood Medium","institution_state":"Pennsylvania","charges":"Federal conspiracy to use weapons of mass destruction and conspiracy to acquire and use anti-aircraft missiles — May 20, 2009 FBI sting in Newburgh, New York","arrest_date":"2009-05-20","incarceration_date":"2009-05-20","release_date":"2024-04-17","sentence":"25 years federal prison (mandatory minimum)","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, October 2010"}]}' || true

php artisan prisoner:add '{"name":"Onta Williams","first_name":"Onta","last_name":"Williams","description":"Onta Williams was one of the four men recruited by FBI informant Shahed Hussein into the May 20, 2009 fictional FBI sting plot to bomb Riverdale Bronx synagogues. U.S. District Judge Colleen McMahon called him and his three co-defendants hapless, easily manipulated and penurious petty criminals. He was sentenced in June 2011 to 25 years in federal prison. In a July 27, 2023 ruling, Judge McMahon granted him compassionate release, reducing his sentence to time served plus 90 days; he was released on August 4, 2023.","state":"New York","race":"Black","gender":"Male","ideologies":["Islam"],"affiliation":[],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal conspiracy to use weapons of mass destruction and conspiracy to acquire and use anti-aircraft missiles — May 20, 2009 FBI sting in Newburgh, New York","arrest_date":"2009-05-20","incarceration_date":"2009-05-20","release_date":"2023-08-04","sentence":"25 years federal prison; reduced to time served plus 90 days by Judge McMahon, July 27, 2023","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, October 2010"}]}' || true

php artisan prisoner:add '{"name":"David Williams","first_name":"David","last_name":"Williams","description":"David Williams was one of the four men recruited by FBI informant Shahed Hussein into the May 20, 2009 fictional FBI sting plot to bomb Riverdale Bronx synagogues — at the time of his recruitment he was caring for his terminally ill mother and a brother with kidney disease. He was sentenced in June 2011 to 25 years in federal prison. In a July 27, 2023 ruling, U.S. District Judge Colleen McMahon granted him compassionate release, reducing his sentence to time served plus 90 days; he was released on August 4, 2023.","state":"New York","race":"Black","gender":"Male","ideologies":["Islam"],"affiliation":[],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal conspiracy to use weapons of mass destruction and conspiracy to acquire and use anti-aircraft missiles — May 20, 2009 FBI sting in Newburgh, New York","arrest_date":"2009-05-20","incarceration_date":"2009-05-20","release_date":"2023-08-04","sentence":"25 years federal prison; reduced to time served plus 90 days by Judge McMahon, July 27, 2023","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, October 2010"}]}' || true

php artisan prisoner:add '{"name":"Laguerre Payen","first_name":"Laguerre","last_name":"Payen","description":"Laguerre Payen was a Haitian-born Newburgh, New York resident with documented schizophrenia and severe cognitive impairments at the time he was recruited by FBI informant Shahed Hussein into the May 20, 2009 fictional FBI sting plot. The defense argued and U.S. District Judge Colleen McMahon ultimately accepted that he had been particularly vulnerable to the informants manipulation. He was sentenced in June 2011 to 25 years in federal prison. In a July 27, 2023 ruling, Judge McMahon granted him compassionate release, reducing his sentence to time served plus 90 days; he was released on August 4, 2023.","state":"New York","race":"Black","gender":"Male","ideologies":["Islam"],"affiliation":[],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal conspiracy to use weapons of mass destruction and conspiracy to acquire and use anti-aircraft missiles — May 20, 2009 FBI sting in Newburgh, New York","arrest_date":"2009-05-20","incarceration_date":"2009-05-20","release_date":"2023-08-04","sentence":"25 years federal prison; reduced to time served plus 90 days by Judge McMahon, July 27, 2023","convicted":"Yes — federal jury verdict, U.S. District Court for the Southern District of New York, October 2010"}]}' || true

# === Holy Land Foundation 5 — Dallas federal jury, November 2008 ===

php artisan prisoner:add '{"name":"Ghassan Elashi","first_name":"Ghassan","last_name":"Elashi","description":"Ghassan Elashi was the chairman of the board of the Holy Land Foundation for Relief and Development, the largest Muslim charity in the United States until its assets were frozen by the Bush administration in December 2001. He was indicted in July 2004 along with his fellow HLF officers on charges that the charitys donations to Palestinian zakat (charitable distribution) committees in the West Bank and Gaza had constituted material support to Hamas. The first 2007 federal trial ended in a hung jury on most counts. At a 2008 retrial, the jury convicted on all counts on November 24, 2008. He was sentenced on May 27, 2009 by U.S. District Judge Jorge Solis in Dallas to 65 years in federal prison — among the longest sentences ever imposed for a U.S. nonviolent material-support conviction. He is held at the federal Communications Management Unit at Marion, Illinois.","state":"Texas","race":"Arab","gender":"Male","birthdate":"1953-12-19","ideologies":["Islam","Palestine solidarity","First Amendment"],"affiliation":["Holy Land Foundation for Relief and Development"],"era":"2000s","in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal material support to Hamas, money laundering, tax fraud — Holy Land Foundation donations to Palestinian zakat committees","arrest_date":"2004-07-27","incarceration_date":"2009-05-27","sentenced_date":"2009-05-27","sentence":"65 years federal prison","convicted":"Yes — federal jury verdict (retrial), U.S. District Court for the Northern District of Texas, November 24, 2008"}]}' || true

php artisan prisoner:add '{"name":"Shukri Abu-Baker","first_name":"Shukri","last_name":"Abu-Baker","description":"Shukri Abu-Baker was the founder, president, and chief executive officer of the Holy Land Foundation for Relief and Development. He was indicted in July 2004 along with HLFs officers and convicted at the 2008 retrial of material support to Hamas through HLF donations to Palestinian zakat committees. He was sentenced on May 27, 2009 by U.S. District Judge Jorge Solis in Dallas to 65 years in federal prison. The Holy Land Foundation defendants are widely cited as the most consequential Palestine-solidarity political-prisoner case in U.S. federal court history.","state":"Texas","race":"Arab","gender":"Male","ideologies":["Islam","Palestine solidarity"],"affiliation":["Holy Land Foundation for Relief and Development"],"era":"2000s","in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Units)","institution_state":"Texas","charges":"Federal material support to Hamas, money laundering, tax fraud — Holy Land Foundation donations to Palestinian zakat committees","arrest_date":"2004-07-27","incarceration_date":"2009-05-27","sentenced_date":"2009-05-27","sentence":"65 years federal prison","convicted":"Yes — federal jury verdict (retrial), U.S. District Court for the Northern District of Texas, November 24, 2008"}]}' || true

php artisan prisoner:add '{"name":"Mufid Abdulqader","first_name":"Mufid","last_name":"Abdulqader","description":"Mufid Abdulqader was a fundraiser for the Holy Land Foundation for Relief and Development. He was convicted at the 2008 retrial of material support to Hamas through HLF donations to Palestinian zakat committees. He was sentenced on May 27, 2009 by U.S. District Judge Jorge Solis in Dallas to 20 years in federal prison.","state":"Texas","race":"Arab","gender":"Male","ideologies":["Islam","Palestine solidarity"],"affiliation":["Holy Land Foundation for Relief and Development"],"era":"2000s","in_custody":true,"released":false,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Texas","charges":"Federal material support to Hamas — Holy Land Foundation donations to Palestinian zakat committees","arrest_date":"2004-07-27","incarceration_date":"2009-05-27","sentenced_date":"2009-05-27","sentence":"20 years federal prison","convicted":"Yes — federal jury verdict (retrial), U.S. District Court for the Northern District of Texas, November 24, 2008"}]}' || true

php artisan prisoner:add '{"name":"Mohammad El-Mezain","first_name":"Mohammad","last_name":"El-Mezain","description":"Mohammad El-Mezain was a co-founder of the Holy Land Foundation for Relief and Development and one of the original founders of the U.S. Muslim charitable infrastructure of the 1980s. He was convicted at the 2008 retrial of material support to Hamas through HLF donations to Palestinian zakat committees. He was sentenced on May 27, 2009 by U.S. District Judge Jorge Solis in Dallas to 15 years in federal prison.","state":"Texas","race":"Arab","gender":"Male","ideologies":["Islam","Palestine solidarity"],"affiliation":["Holy Land Foundation for Relief and Development"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Texas","charges":"Federal material support to Hamas — Holy Land Foundation donations to Palestinian zakat committees","arrest_date":"2004-07-27","incarceration_date":"2009-05-27","sentenced_date":"2009-05-27","release_date":"2022-05-27","sentence":"15 years federal prison","convicted":"Yes — federal jury verdict (retrial), U.S. District Court for the Northern District of Texas, November 24, 2008"}]}' || true

php artisan prisoner:add '{"name":"Abdulrahman Odeh","first_name":"Abdulrahman","last_name":"Odeh","description":"Abdulrahman Odeh was the New Jersey representative of the Holy Land Foundation for Relief and Development. He was convicted at the 2008 retrial of material support to Hamas through HLF donations to Palestinian zakat committees. He was sentenced on May 27, 2009 by U.S. District Judge Jorge Solis in Dallas to 15 years in federal prison.","state":"New Jersey","race":"Arab","gender":"Male","ideologies":["Islam","Palestine solidarity"],"affiliation":["Holy Land Foundation for Relief and Development"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Texas","charges":"Federal material support to Hamas — Holy Land Foundation donations to Palestinian zakat committees","arrest_date":"2004-07-27","incarceration_date":"2009-05-27","sentenced_date":"2009-05-27","release_date":"2022-05-27","sentence":"15 years federal prison","convicted":"Yes — federal jury verdict (retrial), U.S. District Court for the Northern District of Texas, November 24, 2008"}]}' || true

# === American Indian Movement / Pine Ridge ===

php artisan prisoner:add '{"name":"Dennis Banks","first_name":"Dennis","last_name":"Banks","aka":"Nowa Cumig","description":"Dennis Banks (Anishinaabe, Ojibwe name Nowa Cumig) was a co-founder of the American Indian Movement in Minneapolis in 1968 and one of the principal organizers of the 71-day occupation of Wounded Knee, South Dakota in February-May 1973, in which AIM and the Oglala Lakota traditional council seized the historic site of the 1890 massacre to demand a federal investigation of the Pine Ridge tribal government and a renegotiation of the 1868 Fort Laramie Treaty.\n\nFederal charges against Banks and co-defendant Russell Means in connection with Wounded Knee were dismissed in September 1974 by U.S. District Judge Fred J. Nichols on the grounds of governmental misconduct, including FBI false witness testimony, illegal surveillance, and an attempt to cover up military involvement in the 71-day siege. In a separate prosecution arising from the 1973 Custer County Courthouse riot — also part of AIMs 1973 organizing — Banks was convicted in South Dakota state court. Rather than report, he fled and lived underground for nine years, sheltered first in California (under sanctuary by Governor Jerry Brown) and then in New York (under sanctuary by the Onondaga Nation). On September 13, 1984 he turned himself in, served 14 months in South Dakota state prison, and was released. He died on October 29, 2017.","state":"South Dakota","race":"Native American","gender":"Male","birthdate":"1937-04-12","death_date":"2017-10-29","ideologies":["Indigenous sovereignty","American Indian Movement"],"affiliation":["American Indian Movement","Lakota Sioux"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"South Dakota Department of Corrections","institution_state":"South Dakota","charges":"South Dakota state riot and assault — 1973 Custer County Courthouse confrontation; Wounded Knee federal charges dismissed September 1974 for FBI misconduct","arrest_date":"1984-09-13","incarceration_date":"1984-09-13","release_date":"1985-12-15","sentence":"3 years South Dakota state prison; served 14 months","convicted":"Yes — South Dakota state court, 1975 (sentence served 1984-85 after 9 years underground)"}]}' || true

php artisan prisoner:add '{"name":"Robert Robideau","first_name":"Robert","middle_name":"Eugene","last_name":"Robideau","description":"Robert Eugene Robideau was an American Indian Movement organizer and a member of the AIM spiritual encampment at the Jumping Bull family compound on the Pine Ridge Reservation on June 26, 1975, when FBI agents Jack Coler and Ronald Williams entered the compound in unmarked cars looking for an alleged stolen-boots suspect and were killed in the firefight that followed. He, Darrelle Dean Butler, Leonard Peltier, and Jimmy Eagle were federally indicted for the agents murders. He was held in pretrial detention from his September 1975 arrest until his July 1976 acquittal at trial in U.S. District Court in Cedar Rapids, Iowa, where the jury accepted the defense argument that the defendants had fired in self-defense in the climate of the Pine Ridge reign of terror.\n\nAfter his acquittal he became one of the principal organizers of the international Free Leonard Peltier campaign and a longtime spokesperson for AIM. He died on February 17, 2009 at age 62.","state":"South Dakota","race":"Native American","gender":"Male","birthdate":"1946-11-11","death_date":"2009-02-17","ideologies":["Indigenous sovereignty","American Indian Movement"],"affiliation":["American Indian Movement","Leonard Peltier Defense Committee"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (pretrial)","charges":"Federal first-degree murder of FBI agents Jack Coler and Ronald Williams — June 26, 1975 firefight at the Jumping Bull compound, Pine Ridge Reservation","arrest_date":"1975-09-10","incarceration_date":"1975-09-10","release_date":"1976-07-16","sentence":"Held in pretrial detention 10 months; acquitted on self-defense grounds","convicted":"No — acquitted, U.S. District Court for the Northern District of Iowa, July 1976"}]}' || true

php artisan prisoner:add '{"name":"Darrelle Dean Butler","first_name":"Darrelle","middle_name":"Dean","last_name":"Butler","aka":"Dino Butler","description":"Darrelle Dean (Dino) Butler was an American Indian Movement organizer present at the Jumping Bull family compound on the Pine Ridge Reservation on June 26, 1975 when FBI agents Jack Coler and Ronald Williams were killed in the firefight that followed their entry into the compound. He, Robert Robideau, Leonard Peltier, and Jimmy Eagle were federally indicted for the agents murders. He was held in pretrial detention from his September 1975 arrest until his July 1976 acquittal alongside Robideau in U.S. District Court in Cedar Rapids, Iowa, where the jury accepted the defense argument of self-defense in the climate of the Pine Ridge reign of terror.\n\nAfter his acquittal he became a longtime AIM and Free Leonard Peltier organizer, and lived for many years in Oregon. He died on June 6, 2024.","state":"South Dakota","race":"Native American","gender":"Male","death_date":"2024-06-06","ideologies":["Indigenous sovereignty","American Indian Movement"],"affiliation":["American Indian Movement","Leonard Peltier Defense Committee"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (pretrial)","charges":"Federal first-degree murder of FBI agents Jack Coler and Ronald Williams — June 26, 1975 firefight at the Jumping Bull compound, Pine Ridge Reservation","arrest_date":"1975-09-10","incarceration_date":"1975-09-10","release_date":"1976-07-16","sentence":"Held in pretrial detention 10 months; acquitted on self-defense grounds","convicted":"No — acquitted, U.S. District Court for the Northern District of Iowa, July 1976"}]}' || true

echo
echo "Round 9 (Mehanna + Newburgh 4 + HLF 5 + AIM Pine Ridge) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
