#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_palestine_2025_minnesota.sh
#
# Two more 2025-wave Palestine-solidarity ICE detentions identified via the
# Forward's ICE detention tracker. Both released by federal court orders
# specifically finding First Amendment violations.
set -e

# === Mohammed Hoque — Minnesota State Mankato (March 2025) ===

php artisan prisoner:add '{"name":"Mohammed Hoque","first_name":"Mohammed","last_name":"Hoque","description":"Mohammed Hoque is a 20-year-old Bangladeshi international student at Minnesota State University, Mankato. On March 28, 2025, plainclothes ICE officers followed his car as he returned home from a coding class and surrounded him at his home, telling him his student visa had been revoked. He was held in ICE custody for over a month. He had no criminal record; the only basis the government cited was social-media activity, including Instagram posts about violence against Palestinians in Gaza and a #FreePalestine hashtag in his Instagram bio.\n\nHis attorneys filed a habeas petition arguing his detention was First Amendment retaliation for his support of Palestinian human rights. On May 7, 2025, U.S. District Judge Jerry Blackwell of the District of Minnesota ordered his immediate release, finding that Hoques arrest aligns with the publicly stated executive policy of targeting social media users who express support for Palestinian human rights and criticize violence in Gaza. He was released on a $7,500 bond.","state":"Minnesota","race":"Asian","gender":"Male","ideologies":["Palestine solidarity","First Amendment"],"affiliation":["Minnesota State University, Mankato"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"ICE detention (Minnesota and Texas facilities)","institution_state":"Minnesota","charges":"INA visa revocation; no criminal charges; basis cited was social-media support for Palestinian human rights","arrest_date":"2025-03-28","incarceration_date":"2025-03-28","release_date":"2025-05-07","sentence":"~40 days ICE detention; released by U.S. District Court order finding First Amendment violation","convicted":"No - civil immigration detention; federal court found retaliation against protected speech"}]}' || true

# === Aditya Wahyu Harsono — Southwest Minnesota State (March 2025) ===

php artisan prisoner:add '{"name":"Aditya Wahyu Harsono","first_name":"Aditya","middle_name":"Wahyu","last_name":"Harsono","description":"Aditya Wahyu Harsono is an Indonesian citizen, recent Southwest Minnesota State University graduate, and supply-chain manager at the Avera Marshall hospital in Marshall, Minnesota. On March 27, 2025, ICE officers arrested him at the hospital where he worked. He was first detained in the hospital basement, then transferred to the Kandiyohi County Jail. The government cited a 2023 misdemeanor conviction for property damage and a dismissed citation from his presence at a 2021 Daunte Wright protest in Brooklyn Center, Minnesota. The actual basis, his lawsuit argued, was social-media speech: BLM and Free Palestine posts.\n\nHe was held for 49 days. On May 14, 2025, U.S. District Judge Katherine Menendez of the District of Minnesota issued a 34-page habeas ruling that his detention violated the First Amendment and that the courts finding is more reasonable to infer that Respondents have detained Harsono in retaliation for his speech than because of any professed public-safety concern. He was ordered released and was freed the same day.","state":"Minnesota","race":"Asian","gender":"Male","ideologies":["Palestine solidarity","Black Lives Matter","First Amendment"],"affiliation":["Southwest Minnesota State University","Avera Marshall Regional Medical Center"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Kandiyohi County Jail","institution_city":"Willmar","institution_state":"Minnesota","charges":"INA visa revocation; cited 2023 misdemeanor property-damage conviction and dismissed 2021 Daunte Wright protest citation; defense argued retaliation for BLM and Free Palestine social-media speech","arrest_date":"2025-03-27","incarceration_date":"2025-03-27","release_date":"2025-05-14","sentence":"49 days ICE detention; released by U.S. District Court order finding First Amendment violation","convicted":"No - civil immigration detention; federal court found retaliation against protected speech"}]}' || true

echo
echo "Minnesota Palestine-2025 wave adds complete."
