#!/usr/bin/env bash
# Run on the production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_dashboard_prisoner_gaps.sh
#
# Adds prisoner records for individuals who appear as dashboard "case" markers
# (dashboard:add-*-cases) but were missing from the prisoner database. The
# prisoner:add command refuses duplicates by name, so this is SAFE to re-run and
# will simply skip anyone already present (incl. anyone already imported via
# Airtable/admin that isn't visible in the committed scripts).
#
# Deliberately NOT included here (editorial calls -- add separately if desired):
#   - Tyler Robinson (accused Charlie Kirk assassin)
#   - Luigi Mangione (accused in the UnitedHealthcare CEO killing)
#
# Do NOT use `set -e`: prisoner:add returns non-zero on a duplicate, and we want
# the script to continue to the next person.

php artisan prisoner:add '{"name":"Timothy Martin","first_name":"Timothy","last_name":"Martin","gender":"Male","state":"District of Columbia","era":"2020s","ideologies":["Environmental Activism"],"affiliation":["Declare Emergency"],"in_custody":true,"released":false,"description":"Timothy Martin, an architect from North Carolina with the climate group Declare Emergency, smeared red and black paint on the protective case and base of the Edgar Degas sculpture \"Little Dancer Aged Fourteen\" at the National Gallery of Art on April 27, 2023 (with co-defendant Joanna Smith) to demand a presidential climate-emergency declaration; the sculpture itself was unharmed. A federal jury convicted him in April 2025 of conspiracy against the United States and injuring a National Gallery exhibit, and on October 27, 2025 he was sentenced to 18 months in federal prison, among the harshest U.S. sentences for a nonviolent climate protest.","cases":[{"institution_name":"Federal Bureau of Prisons","institution_state":"District of Columbia","charges":"18 USC 371 conspiracy against the United States; 40 USC 6303 and 6307 injury to National Gallery of Art property (2023 Little Dancer paint action)","convicted":"Yes (federal jury trial)","sentence":"18 months federal prison","incarceration_date":"2025-04-07"}]}'

php artisan prisoner:add '{"name":"Briana Boston","first_name":"Briana","last_name":"Boston","gender":"Female","state":"Florida","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Briana Boston, a 42-year-old mother from Lakeland, Florida, was arrested in December 2024 after telling a Blue Cross Blue Shield representative \"delay, deny, depose; you people are next\" during a recorded call about a denied health-insurance claim, echoing words found on the casings in the UnitedHealthcare CEO killing. She was charged with a second-degree felony of making a threat of terrorism, with bond set at 100,000 dollars. State prosecutors dropped the charge on February 25, 2025.","cases":[{"institution_name":"Polk County Jail","institution_city":"Bartow","institution_state":"Florida","charges":"Making a threat of terrorism (second-degree felony)","arrest_date":"2024-12-11","convicted":"No (charge dropped)","sentence":"Bond 100,000 dollars; charge dropped Feb 25, 2025"}]}'

php artisan prisoner:add '{"name":"Xaelyn Dunbar","first_name":"Xaelyn","last_name":"Dunbar","gender":"Male","state":"Texas","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Xaelyn Dunbar, 19, was arrested in September 2025 and charged with making a terroristic threat over Facebook comments about a Charlie Kirk memorial vigil at the University of Texas at San Antonio, referencing his truck. He told police he was joking and was held in the Bexar County Jail on a 40,000-dollar bond.","cases":[{"institution_name":"Bexar County Jail","institution_city":"San Antonio","institution_state":"Texas","charges":"Making a terroristic threat","arrest_date":"2025-09-23","convicted":"Pending","sentence":"Bond 40,000 dollars"}]}'

php artisan prisoner:add '{"name":"Kolton Krottinger","first_name":"Kolton","last_name":"Krottinger","gender":"Male","state":"Texas","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Kolton Krottinger, a U.S. Navy veteran from Granbury, Texas, was arrested on November 5, 2025 on a third-degree felony charge of online impersonation after posting what his lawyer called a satirical political meme on Facebook that appeared to show a local activist endorsing a school-board candidate. A special prosecutor formally declined the charge on December 22, 2025.","cases":[{"institution_name":"Hood County Jail","institution_city":"Granbury","institution_state":"Texas","charges":"Online impersonation (third-degree felony)","arrest_date":"2025-11-05","convicted":"No (charge declined)","sentence":"Bond 10,000 dollars; charge declined Dec 22, 2025"}]}'

php artisan prisoner:add '{"name":"Arden Wells","first_name":"Arden","last_name":"Wells","gender":"Male","state":"Louisiana","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Arden Wells, a frequent Facebook critic of the Tangipahoa Parish sheriff, was arrested in July 2025 in Amite City, Louisiana and charged with felony terrorizing plus two counts of cyberstalking over a June 2025 Facebook post suggesting a prisoner had escaped the parish jail. The district attorney refused all three charges in February 2026.","cases":[{"institution_name":"Tangipahoa Parish Jail","institution_city":"Amite City","institution_state":"Louisiana","charges":"Terrorizing (felony); two counts of cyberstalking","arrest_date":"2025-07-25","convicted":"No (charges refused)","sentence":"Charges refused Feb 2026"}]}'

php artisan prisoner:add '{"name":"Alejandro Orellana","first_name":"Alejandro","last_name":"Orellana","gender":"Male","state":"California","era":"2020s","ideologies":["Immigrant Rights"],"in_custody":false,"released":true,"description":"Alejandro Orellana, an East Los Angeles activist, was arrested on June 12, 2025 and federally charged with conspiracy and aiding and abetting civil disorder for handing out face shields and water to demonstrators at a June 9 anti-ICE protest in Los Angeles. Federal prosecutors moved to dismiss the case on July 30, 2025.","cases":[{"institution_name":"Metropolitan Detention Center Los Angeles","institution_city":"Los Angeles","institution_state":"California","charges":"Conspiracy and aiding and abetting civil disorder (federal)","arrest_date":"2025-06-12","convicted":"No (dismissed)","sentence":"Dismissed July 30, 2025"}]}'

php artisan prisoner:add '{"name":"Lucas Griffith","first_name":"Lucas","last_name":"Griffith","gender":"Male","state":"Kentucky","era":"2020s","ideologies":["Press Freedom"],"in_custody":false,"released":true,"description":"Lucas Griffith, a student journalist interning for Cincinnati CityBeat, was arrested on July 17, 2025 while covering an anti-ICE march in Covington, Kentucky. Initially charged with felony rioting plus misdemeanors, he had the felony dropped and in October 2025 was convicted of one count of failure to disperse and acquitted of the others.","cases":[{"institution_name":"Kenton County Detention Center","institution_city":"Covington","institution_state":"Kentucky","charges":"Failure to disperse; disorderly conduct; obstructing (felony rioting count dropped)","arrest_date":"2025-07-17","convicted":"Yes (one count, failure to disperse)","sentence":"50-dollar fine plus court costs"}]}'

php artisan prisoner:add '{"name":"Jeana Gamble","first_name":"Jeana","last_name":"Gamble","gender":"Female","state":"Alabama","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Jeana Gamble, 62, was arrested in October 2025 at a No Kings anti-Trump protest in Fairhope, Alabama while wearing an inflatable costume and carrying a sign. Charged with disorderly conduct, resisting arrest, disturbing the peace, and giving a false name, she was acquitted of all charges in April 2026.","cases":[{"institution_name":"Fairhope City Jail","institution_city":"Fairhope","institution_state":"Alabama","charges":"Disorderly conduct; resisting arrest; disturbing the peace; giving a false name","arrest_date":"2025-10-18","convicted":"No (acquitted)","sentence":"Acquitted April 2026"}]}'

php artisan prisoner:add '{"name":"Sami Hamdi","first_name":"Sami","last_name":"Hamdi","gender":"Male","state":"California","era":"2020s","ideologies":["Free Speech","Pro-Palestinian"],"in_custody":false,"released":true,"description":"Sami Hamdi, a British political commentator and managing director of the consultancy The International Interest, was detained by ICE at San Francisco International Airport on October 26, 2025, a day after speaking at a CAIR gala, after the State Department revoked his visa. He and supporters say he was targeted for his criticism of Israel and the war in Gaza. He was held about 18 days and returned to the United Kingdom on November 13, 2025.","cases":[{"institution_name":"ICE detention","institution_state":"California","charges":"Civil immigration detention after a State Department visa revocation (no criminal charge)","arrest_date":"2025-10-26","convicted":"No (civil immigration detention)","sentence":"Held ~18 days; departed the U.S. Nov 13, 2025"}]}'

php artisan prisoner:add '{"name":"Salah Sarsour","first_name":"Salah","last_name":"Sarsour","gender":"Male","state":"Wisconsin","era":"2020s","ideologies":["Pro-Palestinian"],"in_custody":true,"released":false,"description":"Salah Sarsour, a Palestinian-American lawful permanent resident and board president of the Islamic Society of Milwaukee, was detained by ICE in Milwaukee, Wisconsin on March 30, 2026. Rights groups and local officials say the detention targets his pro-Palestinian advocacy and Muslim faith, while the Department of Homeland Security cites a decades-old conviction from his teenage years in the West Bank and an alleged green-card application omission. He has remained in immigration detention.","cases":[{"institution_name":"ICE detention","institution_state":"Wisconsin","charges":"Civil immigration detention and removal proceedings (no U.S. criminal charge)","arrest_date":"2026-03-30","convicted":"No (civil immigration detention)","sentence":"Ongoing detention"}]}'
