<?php

declare(strict_types=1);

/**
 * Bulk-add 92 Summer 2020 / George Floyd uprising defendants from
 * the user-supplied dataset (the 100-row spreadsheet identifying
 * federal and state prosecutions for protest-related conduct in May
 * 2020 - Sept 2023). Six rows already in the database were skipped
 * by the audit before this script was written:
 *   - Mujera Benjamin Lung'aho
 *   - Margaret Aislinn Channon
 *   - Khalif Miller
 *   - Raekwon Dac Blankenship
 *   - Shamar N. Betts
 *   - Lore-Elisabeth Blumenthal
 *
 * Each row creates one Prisoner and one PrisonerCase. The case
 * release_date is computed as arrest_date + sentence_months (today =
 * May 9, 2026; if release_date is in the future the prisoner is
 * marked in_custody=true, otherwise released=true).
 *
 * Idempotent: prisoners are matched by name and skipped if they
 * already exist.
 */

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Prisoner;
use App\Models\PrisonerCase;
use App\Models\Institution;
use Carbon\Carbon;

// Tab-separated columns:
// name | first | last | aka | state | city | age | race | gender | arrest_date(Y-m-d) | sentence_months | jurisdiction(Federal|Non-Federal) | charges | narrative | extra_ideologies (comma-sep, optional) | extra_affiliations (comma-sep, optional)
$DATA = <<<'TSV'
Henry Parker	Henry	Parker		Kansas	Wichita	30	Black	Male	2020-06-02	300	Non-Federal	Aggravated battery on LEO (2 counts); aggravated assault of LEO; use of a deadly weapon (19 counts); criminal possession of weapon by felon (Kansas state).	Henry Parker, 30, of Wichita, KS was sentenced to 25 years in prison for firing multiple gunshots at police officers during a June 2, 2020 protest in north Wichita following the death of George Floyd. To disperse the crowd, SWAT officers fired tear gas; Parker fired on the officers, striking 1-2 officers' riot helmets. He was found guilty July 22, 2022 and sentenced in March 2023. According to court records, Parker "was upset when a woman he called his sister was hit with a rubber bullet while she held a baby."
Keyondre Robinson	Keyondre	Robinson		New York	Buffalo	18	Black	Male	2020-05-30	228	Federal	18 U.S.C. § 111(a)(1) — Forcibly interfering with a federal employee/officer while performing official duties.	Keyondre Robinson, 18, of Buffalo, NY was charged with assaulting a federal officer for his alleged role in throwing a bottle that struck a Deputy United States Marshal in the face during a Black Lives Matter protest outside the federal courthouse in Buffalo on May 30, 2020. The incident was recorded on the officer's body camera. He was sentenced to 19 years in prison followed by five years of post-release supervision.
Montez Terriel Lee Jr.	Montez Terriel	Lee	Tez, Montez Terrill Lee	Minnesota	Minneapolis	25	Black	Male	2020-05-28	120	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Montez Terriel Lee Jr., 25, was charged with arson in Minneapolis, MN, after maliciously damaging and destroying by means of fire and explosive materials the Max It Pawn Shop on May 28, 2020 during the George Floyd uprising. A man inside the shop died; the death was ruled a homicide after the cause of death was determined to be smoke inhalation. Lee was sentenced to 10 years federal prison plus three years supervised release.
Cody Michael Tarner	Cody Michael	Tarner	Cody Turner	District of Columbia	Washington	23	White	Male	2020-07-15	120	Federal	18 U.S.C. § 844(i) — Arson; 18 U.S.C. § 1361 — Destruction of Government Property.	Cody Michael Tarner, 23, of Hagerstown, MD, was indicted by a federal grand jury for burning two Supreme Court Police vehicles and attempting to burn a third on July 15, 2020. Tarner poured gasoline from a can into three Supreme Court Police vehicles, igniting two; he himself was engulfed in flames and suffered severe burns before a Supreme Court Police officer rendered first aid. One vehicle was destroyed, one damaged, the third did not catch fire. He was held without bond pending trial; tried unsuccessfully to plead insanity.
Leroy Lemonte Perry Williams	Leroy Lemonte Perry	Williams		Minnesota	Minneapolis	34	Black	Male	2020-08-26	120	Federal	18 U.S.C. § 371 — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson affecting interstate commerce.	Leroy L.P. Williams, 34, of Minneapolis was charged in conspiracy with Shador T.C. Jackson and Victor D. Edwards for fires set inside Target's world headquarters in downtown Minneapolis on August 26, 2020 amid rioting over a false rumor that police had killed a Black man (the rumor sprang from Eddie Frank Sole Jr.'s on-camera suicide on Nicollet Mall). Williams allegedly returned to the building after the initial fires and attempted to start a second fire near the entrance. He was sentenced to 10 years federal prison plus 3 years supervised release.
Malik Fard Muhammed	Malik Fard	Muhammed	Malik Fard Muhammad	Oregon	Portland	24	Black	Male	2020-09-23	120	Federal	18 U.S.C. § 231(a)(3) — Civil disorder (2 counts); 18 U.S.C. § 844(h)(1) — Using an explosive to commit a felony (2 counts); 26 U.S.C. §§ 5841, 5861(d), 5871 — Unlawful possession of a destructive device (2 counts).	Malik Fard Muhammed, 24, was arrested on October 11, 2020 in Portland, OR after police saw him smashing windows with a metal baton. On two September 2020 nights he used growlers as Molotov cocktails thrown at police; one officer's leg caught fire when a flaming bottle exploded into a fireball at the Multnomah County Justice Center on September 23, 2020. DNA analysis linked him to a Molotov cocktail thrown at another September protest. He was sentenced to 10 years federal prison and 3 years supervised release.
Matthew Lee Rupert	Matthew Lee	Rupert		Minnesota	Minneapolis	28	White	Male	2020-05-30	105	Federal	18 U.S.C. § 231(a)(3) — Interfering with law enforcement; 18 U.S.C. § 2101(a) — Interstate travel to riot; 18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Matthew Lee Rupert, 28, was charged with civil disorder, rioting, and arson after posting on social media that he was going to attend the protests over George Floyd's death in Minneapolis, then being caught on video using explosives, damaging property, and threatening law enforcement officers. Sentenced to 8 years 9 months federal prison.
Victor Devon Edwards	Victor Devon	Edwards		Minnesota	Minneapolis	31	Black	Male	2020-08-26	100	Federal	18 U.S.C. § 2101(a) — Riot; 18 U.S.C. § 2 — Aiding and abetting arson; 18 U.S.C. § 844(i) — Arson affecting interstate commerce.	Victor D. Edwards, 31, of St. Paul was charged in conspiracy with Shador T.C. Jackson and Leroy L.P. Williams for fires set inside Target's world headquarters in Minneapolis on August 26, 2020. Inside the mailroom Edwards added liquid accelerant to a fire intentionally started by Jackson. Sentenced to 60 months on count 1 and 100 months on count 2, served concurrently.
John Fitzgerald Johnson	John Fitzgerald	Johnson	Grand Master Jay, Grandmaster Jay, Grandmaster J	Kentucky	Louisville	57	Black	Male	2020-09-04	86	Federal	18 U.S.C. § 111(b) and § 1114 — Assaulting/resisting federal officers; 18 U.S.C. § 924(c)(1)(A) — Brandishing a firearm in relation to a crime of violence.	John "Grandmaster Jay" Johnson, 57, of Cincinnati, OH, leader of the Black militia Not Fucking Around Coalition (NFAC), was charged after he brandished/aimed an AR-15 rifle toward a roof holding two federal agents and three Louisville Metro PD officers during protests over the police killing of Breonna Taylor. Johnson is a former U.S. Army Active Duty service member. Sentenced to 86 months federal prison and concurrent state charges.	Black militia	Not Fucking Around Coalition (NFAC)
Fornandous Cortez Henderson	Fornandous Cortez	Henderson		Minnesota	Apple Valley	32	Black	Male	2020-05-29	78	Federal	18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 844(i) — Arson in interstate commerce; 26 U.S.C. § 5861(d) — Unlawful possession of an unregistered destructive device (2 counts).	Fornandous Cortez Henderson, 32, was charged with arson and possession of a Molotov cocktail after setting fire to the Dakota County Western Service Center in Apple Valley, MN on May 29, 2020 — a government building housing state and local agencies and a U.S. Passport center. Co-defendant Garrett Patrick Ziegler, registered owner of a vehicle parked nearby, was identified by car keys found at the scene. Sentenced to 78 months federal prison plus 3 years supervised release and $205,872.53 restitution.
Jose Angel Felan	Jose Angel	Felan		Minnesota	St. Paul	34	Latino	Male	2020-05-28	78	Federal	18 U.S.C. § 844(i) — Arson (3 counts).	On May 28, 2020 Jose Felan was observed on CCTV setting fires in and around a Goodwill and Napa Auto Parts in St. Paul, MN. His wife Mena Yousif accompanied him. The couple, originally from New York, were in Minnesota for protests after the death of George Floyd. Identified via facial recognition and tracked by U.S. Marshals to Mexico, where they were arrested. Sentenced to 78 months federal prison plus 3 years supervised release and $39,028 restitution.
Samantha Shader	Samantha	Shader		New York	Brooklyn	27	White	Female	2020-05-31	72	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; § 844(f)(1), (h)(1), (n) — Use/conspiracy of explosives; § 924(c)(1)(B)(ii) — Use of a destructive device; § 231(a)(3) — Civil disorder; 26 U.S.C. § 5861(d), (f) — Possessing/making a destructive device.	Samantha Shader, 27, of Brooklyn, NY was arrested on May 31, 2020 after attempting to use Molotov cocktails to damage NYPD vehicles during George Floyd protests. Faced four counts of attempted murder since the targeted NYPD van contained multiple officers; no one was harmed when the device failed to explode. Friend Timothy Amerman was indicted weeks later for providing the bottles. Sentenced to 6 years federal prison plus 3 years supervised release and a mandatory mental health program.
Matthew Scott White	Matthew Scott	White		Minnesota	Minneapolis	31	White	Male	2020-05-28	72	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce (2 counts); 18 U.S.C. § 371 — Conspiracy.	Matthew Scott White, 31, was arrested in connection with a fire set at an Enterprise Rent-A-Car building in St. Paul, MN on May 28, 2020 amid Twin Cities unrest after George Floyd's death. Surveillance video showed White and co-conspirator Jessica White (whose case was dismissed) outside the business; White entered for several minutes; flames were visible behind him as he exited. Pleaded guilty; sentenced to 72 months federal prison.
Garrett Patrick Ziegler	Garrett Patrick	Ziegler		Minnesota	Apple Valley	24	White	Male	2020-05-29	60	Federal	18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 844(i) — Arson in interstate commerce; 26 U.S.C. § 5861(d) — Unlawful possession of an unregistered destructive device (2 counts).	Garrett Patrick Ziegler, 24, of Apple Valley, MN was charged with arson and possession of a Molotov cocktail with co-defendant Fornandous Cortez Henderson for the May 29, 2020 fire at the Dakota County Western Service Center. Officers found Ziegler's car keys in grass near the scene; a search of the registered vehicle recovered Molotov-related items. Sentenced to 60 months federal prison plus 3 years supervised release and $205,872.53 restitution.
Wesley Somers	Wesley	Somers		Tennessee	Nashville	25	White	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Wesley Somers, 25, was charged with malicious destruction of property using fire after taking part in smashing windows, vandalism, and fire setting at the Nashville City Hall in June 2020 following a protest. Somers specifically was seen smashing windows and lighting objects on fire then tossing them into the courthouse. Co-defendant Jesse Lee Clark was later identified as helping. Sentenced to 60 months federal prison.
Carlos A. Matchett	Carlos A.	Matchett	Carlos Matchett, Carlito Matchett, Carlito's Way	New Jersey	Atlantic City	30	Latino	Male	2020-05-30	60	Federal	18 U.S.C. § 2101 — Use of a facility of interstate commerce to incite a riot.	Carlos Matchett, 30, of Atlantic City, NJ pleaded guilty to obstructing law enforcement during civil disorder and trying to start a riot, including setting police cars on fire. Police arrested Matchett at the scene with a folding knife, a hatchet, and a jar containing what appeared to be gasoline. He had a social media page with a post stating "LETS START a RIOT" and a video urging people to enter a store. Sentenced to 60 months federal prison.
Courtland Renford	Courtland	Renford		New York	Buffalo	20	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; New York Penal Law — Burglary 3rd degree.	Courtland Renford, 20, was charged with arson after throwing a burning basket into Buffalo City Hall during weekend protests in Buffalo, NY in 2020. The government argued in detention pleadings that "Congress determines Renford setting fire to an empty building [is] an act of terrorism." Sentenced to 60 months federal prison.
Terrance Lee Hester	Terrance Lee	Hester		Florida	Tampa	20	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 844(h) — Explosives used in commission of a felony.	Terrance Lee Hester Jr., 20, of Tampa, FL was charged with arson after a May 30-31, 2020 protest near a shopping plaza on East Fowler Avenue devolved into civil unrest, looting, and destruction. Video showed Hester tossing a flaming piece of cloth through a broken window of the Champs Sports store; the building was fully engulfed and the plaza suffered ~$1.25 million in damage. Sentenced to 60 months federal prison plus 36 months supervised release.
Charles Anthony Pittman	Charles Anthony	Pittman	Charles KingCappo Pittman	North Carolina	Fayetteville	32	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(f)(1), (f)(2) and § 2 — Aiding and abetting malicious damage of a building owned/possessed by an institution receiving federal assistance, by fire; 18 U.S.C. § 2101(a) — Promote, encourage, participate in and carry on a riot.	Charles Anthony Pittman, 32, was charged in Fayetteville, NC for the burning of the Market House on May 30, 2020 following peaceful protests. Pittman was filmed carrying around a container of gasoline on the second floor; co-defendant Andrew Salvarani Garcia-Smith was caught on video as he threw a bottle of burning liquid. Prior to protests Pittman posted a video discussing his plans to bring the Market House down. Sentenced to 60 months federal prison.
Gavaughn Gaquez Streeter-Hillerich	Gavaughn Gaquez	Streeter-Hillerich		Oregon	Portland	22	Black	Male	2020-06-26	60	Federal	18 U.S.C. § 844(i), § 844(f)(1) — Arson and attempted arson.	Gavaughn Gaquez Streeter-Hillerich, 22, was charged for two counts of using fire to maliciously damage a building housing the Portland Police Bureau's North Precinct on June 26, 2020. Approximately 19 people were inside PPB's North Precinct. He was seen on video setting a large dumpster on fire near the building's NW exterior corner; the fire was set on top of the dumpster, which had been pushed against plywood affixed to the building. Officers used extinguishers to contain the fire. Sentenced to 60 months federal prison.
Carlos Espriu	Carlos	Espriu		California	La Quinta	23	Latino	Male	2020-05-31	60	Federal	18 U.S.C. § 844(i) — Attempted arson of a building used in interstate and foreign commerce.	Carlos Espriu, 23, of Palm Desert, CA was charged with attempted arson in the May 31, 2020 firebombing of the East Valley Republican Women Federated (EVRWF) office in La Quinta, CA. Espriu used a metal baseball bat to break windows at the EVRWF headquarters, then lit an improvised incendiary device of three bottles and tossed them through the windows before fleeing. He returned twice — once to retrieve the Molotovs, once to throw them, igniting a fire. Sentenced to 60 months federal prison plus $5,426 restitution.	Anti-fascism
Tyre Wayne Means	Tyre Wayne	Means		Washington	Seattle	25	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(f)(1) and § 844(i) — Arson; 18 U.S.C. § 922(j) — Possession of a stolen firearm; 18 U.S.C. § 922(g)(1) — Unlawful possession of a firearm (2 counts).	Tyre Wayne Means Jr., 25, of Seattle, WA was charged with one count of arson, one count of possession of a stolen firearm, and two counts of unlawful possession of a firearm. He was caught lighting a police car on fire and tried to grab a rifle from a bag inside the car before fleeing. He had a previous criminal record that prevented him from owning a firearm. Sentenced to 60 months federal prison.
John Boampong	John	Boampong		Massachusetts	Boston	37	Black	Male	2020-06-01	60	Federal	18 U.S.C. § 231(a)(3) — Civil disorder; 18 U.S.C. § 922(n) — Felon in possession of a firearm; 18 U.S.C. § 111 — Forcibly interfering with federal employee/officer.	On June 1, 2020 around 3 a.m., Boampong was driving near Arlington & Boylston in Boston in front of a store that had been looted that evening. After officers told him to leave, Boampong returned to the area, parked, and shot at least 11 times toward officers — including a deputized federal officer. A Sig Sauer P230 9mm with Boampong's fingerprint was recovered from his car; he was prohibited from possessing firearms due to pending state charges. Sentenced to 60 months federal prison.
Sean Cardenas	Sean	Cardenas		Illinois	Rockford	20	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson.	Sean Cardenas, 20, of Rockford, IL was indicted by a federal grand jury on January 12, 2021 on one count of maliciously damaging and destroying, and attempting to damage and destroy, by means of fire, a building. The alleged arson occurred on May 30, 2020, hours after a march protesting the death of George Floyd turned violent. Sentenced to 60 months federal prison plus $965,000 restitution.
Ashton L. Howard	Ashton L.	Howard		Wisconsin	Kenosha	27	Black	Male	2020-08-23	60	Federal	18 U.S.C. § 231(a)(3) — Obstructing a law enforcement officer during a civil disorder; 18 U.S.C. § 922(g)(1) — Possession of ammunition by a felon.	Ashton L. Howard, 27, was indicted on federal charges of obstructing a law enforcement officer during a civil disorder and of possessing ammunition despite being a felon. Howard was arrested during a protest in Kenosha, WI held in response to the police shooting of Jacob Blake in August 2020; he allegedly threw a brick at an officer's head. Sentenced to 60 months federal prison plus 3 years supervised release.
Shabazz A. Watson	Shabazz A.	Watson		South Carolina	Charleston	24	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson.	Shabazz A. Watson, 24 (27 at sentencing), pled guilty in U.S. District Court in March 2023 to a single count of arson; additional arson counts were dismissed by federal prosecutors in exchange for the plea. Watson is accused of setting several fires during the George Floyd protests in Charleston, SC on May 30, 2020 — at a wine bar, clothing store, paint store, and Family Dollar. Estimates place the damage at $2.28 million; ~20 fires were intentionally set that night per the Charleston PD. Sentenced to 60 months federal prison.
Adion Bryn Mallett	Adion Bryn	Mallett		Oklahoma	Oklahoma City	22	Unknown	Male	2020-06-30	60	Non-Federal	21 O.S. §§ 1262-1377, 1379, 1379.1 — Rioting; 21 O.S. § 1287 — Possession of a firearm while in the commission of a felony.	Adion Mallett, 22, was charged with rioting and possession of a firearm in the commission of a felony after he allegedly used a rock to hit a police officer in the shoulder when an Oklahoma City protest turned violent. Mallett admitted throwing rocks at officers but said he did not intend to hit them. He was found with a loaded pistol on his person and told officers he had it for protection from looting. Sentenced to 60 months in Oklahoma state prison.
Melquan Barnett	Melquan	Barnett		Pennsylvania	Erie	28	Black	Male	2020-05-30	60	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Melquan Barnett, 28, was charged in Erie, PA with malicious destruction of property by fire/explosives to a building used in interstate commerce. When a group of protestors in Erie turned to violence, Barnett was caught on Facebook Live setting fire to a local coffee shop. His defense said: "Mr. Barnett peacefully participated in a demonstration in Erie to protest what he and other members of the African American community in Erie County see as an unjust system." Sentenced to 60 months federal prison plus $3,295 restitution.
Ivan Harrison Hunter	Ivan Harrison	Hunter		Minnesota	Minneapolis	26	White	Male	2020-05-28	52	Federal	18 U.S.C. § 2101(a)(1)-(d) — Traveling in interstate commerce with intent to incite a riot; organize, participate in, and carry on a riot; commit acts of violence in furtherance of a riot; aid and abet rioters.	Ivan Harrison Hunter, 28 (at sentencing in 2022), of Boerne, TX, traveled from Texas to Minnesota in May 2020 and met up with other Boogaloo movement members mobilizing in Minneapolis after George Floyd's murder. On May 28, 2020 during rioting near the Minneapolis Police Department's Third Precinct, Hunter fired 13 rounds from an AK-47 into the entryway of the building. He continued to communicate with fellow Boogaloo members including Steven Carrillo (who shot two federal officers in Oakland the same day). Sentenced to 52 months federal prison.	Boogaloo Bois, Accelerationism	Boogaloo Bois
Tandre Buchanan	Tandre	Buchanan Jr.		Ohio	Cleveland	22	Black	Male	2020-05-30	48	Federal	18 U.S.C. § 1951 — Interference with commerce by threats or violence (Hobbs Act robbery).	Tandre Buchanan Jr., 22, of Cleveland, OH was charged with interference with commerce by robbery after being identified through surveillance footage as participating in damaging businesses. He was seen breaking a glass window with a stool. The indictment alleges that on May 30, 2020 he aided and abetted others in unlawfully obstructing commerce by means of robbery against Colossal Cupcakes employees in downtown Cleveland against the will of the employees by means of actual and threatened force. Sentenced to 48 months federal prison plus 3 years supervised release.
Christopher Alan West	Christopher Alan	West		Pennsylvania	Pittsburgh	35	Black	Male	2020-05-30	48	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 231(a)(3) — Interfering with law enforcement.	Da'Jon Lengyel and Christopher Alan West damaged and destroyed by fire a Pittsburgh police vehicle and damaged a police officer's vehicle by hitting, kicking, and stomping on its parts and joining others in setting it on fire. Sentenced to 48 months federal prison.
Dylan Shakespeare Robinson	Dylan Shakespeare	Robinson		Minnesota	Minneapolis	23	White	Male	2020-05-28	48	Federal	18 U.S.C. § 844(i) — Arson; 18 U.S.C. § 2 — Aiding and abetting arson; 18 U.S.C. § 371 — Conspiracy to commit arson.	Dylan Shakespeare Robinson and three co-defendants (Davon De-Andre Turner, Branden Michael Wolfe, Bryce Michael Williams) were indicted on arson charges for setting fire to the Minneapolis Police Department's Third Precinct during the protests after George Floyd's death on May 28, 2020. Sentenced to 48 months federal prison and ordered to pay $12 million in restitution (joint and several with co-defendants).
Devin Montgomery	Devin	Montgomery		Pennsylvania	Pittsburgh	24	Black	Male	2020-05-30	48	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 2113(a) — Bank burglary; 18 U.S.C. § 2 — Aiding and abetting.	Devin Montgomery, 24, was charged in Pittsburgh, PA with malicious damage to property of an organization receiving federal financial assistance after he and another individual were seen on video lighting things on fire and tossing them into the back of a Pittsburgh Bureau of Police vehicle. The grand jury also charged Montgomery and Brandon Benson with bank burglary at the Dollar Bank, 537 Smithfield Street. Sentenced to 48 months federal prison and 3 years supervised release plus restitution.
Tondrique J. Fitzgerald	Tondrique J.	Fitzgerald		Tennessee	Nashville	23	Black	Male	2020-06-01	48	Non-Federal	Tenn. Code § 39-17-303 — Aggravated riot; § 39-14-408 — Vandalism.	Tondrique Fitzgerald, 23, was arrested on June 1, 2020 and charged with aggravated rioting and vandalism for engaging with others to pull a granite civil rights plaque off the Historic Metro Courthouse (Nashville City Hall) wall. The plaque was smashed; pieces were used to break courthouse windows. Investigators watched Fitzgerald rip off the memorial in a Facebook Live video while encouraging others to participate. Sentenced to 48 months in Tennessee state prison.
Cyan Waters Bass	Cyan Waters	Bass		Oregon	Portland	21	White	Male	2020-09-23	48	Non-Federal	ORS 164.365 — Criminal mischief I; ORS 164.325 — Arson I; ORS 161.405(2)(b) — Attempt to commit a Class A felony; ORS 166.382 — Unlawful possession of a destructive device; ORS 166.015 — Riot.	Cyan Bass, 21, and Hannah Lilly, 21, were indicted in Portland, OR on charges of arson, rioting, and criminal mischief for their roles in setting fires at the Multnomah County Justice Center during a protest against police brutality and the murder of George Floyd. Bass allegedly started two separate fires and used a slingshot/wrist-rocket to shoot projectiles through the windows of the Portland Police Bureau portion of the Justice Center, and threw a destructive device at a police officer (which did not explode). Bass was also facing federal charges. Sentenced to 48 months Oregon state prison.
Emmanuel Quinones	Emmanuel	Quinones		Texas	Lubbock	25	Latino	Male	2020-05-30	46	Federal	18 U.S.C. § 875(c) — Interstate threatening communications.	Emmanuel Quinones, 25, was arrested on May 30, 2020 in Lubbock, TX after brandishing a semi-automatic firearm at a Black Lives Matter protest at "low ready" position, causing the crowd to panic. He refused police commands to drop the rifle until officers drew their own guns and another protestor tackled him. He yelled statements like "This is a revolution" and "President Trump must die"; he admitted threatening Trump supporters and MAGA people on social media, claiming he would shoot them on sight. Sentenced to 46 months federal prison.	Anti-Trump
Jacob Michael Gaines	Jacob Michael	Gaines		Oregon	Portland	23	White	Male	2020-07-12	46	Federal	18 U.S.C. § 111(a)(1)(b) — Forcibly interfering with federal employee/officer while performing official duties with a weapon causing bodily harm.	During ongoing protests in Portland, OR, Jacob Michael Gaines used a hammer to damage a barricaded entrance at the Hatfield Federal Courthouse on July 12, 2020 while federal law enforcement personnel were inside. While attempting to detain him, Gaines struck a U.S. Marshals Service deputy three times with the hammer; the deputy deflected the blows but was struck in the left shoulder, lower neck, and upper back. Sentenced to 46 months federal prison.
Denzal Stewart	Denzal	Stewart		Illinois	Chicago	24	Black	Male	2020-05-30	45	Federal	Arson; civil disorder.	Denzal Stewart, 24, was charged with arson after allegedly setting fire to a Chicago Transit Authority van during a 2020 protest in response to the death of George Floyd. Sentenced to 45 months federal prison.
Branden Michael Wolfe	Branden Michael	Wolfe		Minnesota	Minneapolis	23	White	Male	2020-05-28	42	Federal	18 U.S.C. § 844(i) and § 2 — Aided and abetted the commission of arson; 18 U.S.C. § 371 and § 844(i) — Conspiracy to commit arson.	Branden Michael Wolfe, 23, was indicted with co-defendants for arson at the MPD Third Precinct on May 28, 2020 during George Floyd protests. Wolfe additionally took several items from the precinct including a police vest, duty belt, handcuffs, baton, knife, and ammunition. Sentenced to 42 months federal prison plus 2 years supervised release and $12 million in restitution to the Third Precinct.
Martino Jamel Andrews	Martino Jamel	Andrews		Ohio	Cleveland	22	Black	Male	2020-05-30	41	Federal	18 U.S.C. § 844(f)(1), (2) — Arson.	Martino Andrews, 22, of Cleveland, OH was charged with aggravated arson for setting a Cuyahoga County-owned van on fire during the May 30, 2020 protests in downtown Cleveland over the police killing of George Floyd in Minneapolis. Sentenced to 41 months federal prison plus $3,721.88 restitution.
Andrew Augustyniak-Duncan	Andrew	Augustyniak-Duncan		Pennsylvania	Pittsburgh	25	White	Male	2020-05-30	41	Federal	18 U.S.C. § 231(a)(3) — Obstruction of law enforcement during civil disorder; 18 U.S.C. § 2 — Aiding and abetting.	On May 30, 2020 during ongoing protests after George Floyd's murder, Andrew Augustyniak-Duncan was part of a civil disorder in Pittsburgh, PA that obstructed and adversely affected the interstate commerce of nearby businesses. He is accused of throwing projectiles which struck and injured several police officers. Sentenced to 41 months federal prison followed by 3 years of supervised release.
Kelly Thomas Jackson	Kelly Thomas	Jackson		Washington	Seattle	20	White	Male	2020-05-30	40	Federal	26 U.S.C. § 5861(d), § 5845(a)(8) — Unlawful possession of a destructive device (2 counts); 18 U.S.C. § 844(f)(1), § 844(i) — Arson (2 counts).	Kelly Thomas Jackson, 20, was indicted in U.S. District Court on 2 counts of arson and 2 counts of possessing a destructive device for acts on May 30, 2020. Surveillance and cell records placed him at the scene; agents say he accessed web-based information on how to construct Molotov cocktails, and his iCloud account had files documenting his protest participation. Jackson stole a gas mask from his employer (a Mountlake Terrace plumbing company). Sentenced to 40 months federal prison plus 3 years supervised release.
Tyvarh Nicholson	Tyvarh	Nicholson		Pennsylvania	Erie	29	Black	Male	2020-05-30	40	Federal	18 U.S.C. § 231(a)(3) and § 2 — Obstruction of law enforcement during civil disorder; 26 U.S.C. § 5861(d) — Possession of an unregistered destructive device.	Tyvarh Nicholson, 29, was indicted in Erie on charges of obstruction of law enforcement during civil disorder and possession of an unregistered firearm/destructive device. He threw objects and projectiles at Erie police officers during the May 30, 2020 disturbance downtown. Count One was dismissed; he was sentenced to 40 months federal prison plus 3 years supervised release.
Devon Vaughn	Devon	Vaughn		Wisconsin	Kenosha	23	White	Male	2020-08-23	40	Federal	18 U.S.C. § 844(i) — Arson; 18 U.S.C. § 371 — Conspiracy to commit offense or to defraud the United States.	Devon Vaughn, 23, was indicted on July 7, 2021 for setting fire to a furniture store at a Kenosha, WI protest in 2020. Sentenced to 40 months federal prison.
Justin Christopher Moore	Justin Christopher	Moore		Washington	Seattle	34	White	Male	2020-09-07	40	Federal	26 U.S.C. § 5861(d), § 5845(a)(8) — Unlawful possession of destructive devices.	On September 7, 2020 during a racial justice protest in Seattle, WA sparked by George Floyd's murder, Justin Christopher Moore was carrying a Corona box containing 12 Molotov cocktails — glass beer bottles filled with gasoline with bandanas as wicks. He abandoned the box near the Seattle Police Officers' Guild as Seattle PD moved in to disperse the crowd. Arrested December 9, 2021 from video evidence and electronic-device records of co-conspirators. Sentenced to 40 months federal prison.
Darion Lindsey	Darion	Lindsey		Illinois	Chicago	19	Black	Male	2020-05-30	38	Federal	Arson conspiracy; civil disorder.	Darion Lindsey, 19, was charged with arson after allegedly setting fire to a Chicago Transit Authority van during a 2020 protest in response to the death of George Floyd. Sentenced to 38 months federal prison.
Marc Bell Gonzales	Marc Bell	Gonzales		Minnesota	Minneapolis	29	Biracial	Male	2020-05-28	37	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 371 — Conspiracy.	On May 28, 2020 as part of ongoing protests sparked by George Floyd's murder, Marc Bell Gonzales engaged with other individuals in conduct designed to accelerate a fire in the Wells Fargo Bank building in south Minneapolis. Sentenced to 37 months federal prison plus 3 years supervised release.
Jeanette Renee Wallace	Jeanette Renee	Wallace		Nevada	Las Vegas	24	Black	Female	2020-05-30	36	Federal	18 U.S.C. § 1361 and § 2 — Depredation against property of the United States and aiding and abetting.	Jeanette Wallace, 24, was charged with depredation against U.S. property after the May 30, 2020 protest in Las Vegas, NV (initially decrying George Floyd's death) turned tense. Some demonstrators vandalized buildings and threw bottles, fireworks, and rocks at officers in riot gear; later some gathered at the federal building, kicking and throwing items to gain entry. A federal security guard was threatened. Damage exceeded $70,000. Wallace was identified via facial recognition and Facebook. Sentenced to 36 months federal prison.
Nicholas L. Scaglione	Nicholas L.	Scaglione		Rhode Island	Providence	30	White	Male	2020-06-02	36	Federal	18 U.S.C. § 844(f)(1) — Attempted malicious destruction of a vehicle by fire.	Nicholas L. Scaglione, 30, of Cranston, RI was charged for his alleged involvement in burning a Providence Police cruiser in downtown Providence in the early hours of June 2, 2020. He was the second Rhode Island resident charged in the case (alongside Luis Joel Sierra); both shared information with others about their roles in the burning, including text messages and Snapchat. Sentenced to 36 months federal prison.
Davon De-Andre Turner	Davon De-Andre	Turner		Minnesota	Minneapolis	24	Black	Male	2020-05-28	36	Federal	18 U.S.C. § 844(i) — Conspiracy to commit arson.	On the night of May 28, 2020 after a group of citizens tore down the fence around Minneapolis MPD Third Precinct, Davon De-Andre Turner and Bryce Michael Williams worked together to light an incendiary device. Turner brought the device into the Third Precinct headquarters, where it was used to start a fire. Sentenced to 36 months federal prison and $12 million restitution (joint and several with co-defendants).
Craig Michael Digangi	Craig Michael	Digangi		Pennsylvania	Erie	27	White	Male	2020-05-30	36	Non-Federal	18 Pa. § 2702(a)(6) — Aggravated assault; § 5501(1) — Riot, intent to commit felony; § 2707(b) — Propulsion of missiles; § 2705 — Recklessly endangering another person; § 3304(a)(5) — Criminal mischief; § 5503(a)(4) — Disorderly conduct.	Craig Michael Digangi, 27, of Erie, PA was sentenced to 16-36 months in state prison after pleading guilty to felony rioting and two misdemeanors for participation in the May 2020 Black Lives Matter protests in Erie. He is accused of throwing bricks at — and injuring — officers in the 500 block of State Street and smashing tables outside the Ember and Forge coffee shop.
Timothy O'Donnell	Timothy	O'Donnell		Illinois	Chicago	31	White	Male	2020-05-30	34	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	Timothy O'Donnell, 31, of Chicago, IL was charged with arson after allegedly setting fire to a Chicago Police Department vehicle during the George Floyd protests on May 30, 2020. Sentenced to 34 months federal prison plus 3 years supervised release.
Zachary Alexander Karas	Zachary Alexander	Karas		California	La Mesa	28	Black	Male	2020-05-30	33	Federal	26 U.S.C. § 5861 — Unlawful possession of an unregistered destructive device.	Zachary Alexander Karas, 28, was charged in La Mesa, CA with possession of an unregistered destructive device after he was arrested during a protest with two Molotov cocktails and fireworks. Several fires had been set damaging buildings; Karas failed to leave when officers gave the dispersal order. Sentenced to 33 months federal prison.
Shador Tommie Cortez Jackson	Shador Tommie Cortez	Jackson		Minnesota	Minneapolis	24	Black	Male	2020-08-26	33	Federal	18 U.S.C. § 371 — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson affecting interstate commerce.	Shador T.C. Jackson, 24, was charged with conspiracy to commit arson with co-defendants Victor D. Edwards and Leroy L.P. Williams for fires set inside Target's world headquarters in Minneapolis on August 26, 2020. Jackson used a construction sign to break through a glass door, then set a fire on a counter in the mailroom. He attempted to light a second fire with cardboard boxes and a bottle of ignitable liquid. Sentenced to 33 months federal prison plus 2 years supervised release.
John Michael Santiago	John Michael	Santiago		New York	Rochester	24	White	Male	2020-09-04	33	Federal	18 U.S.C. § 231(a)(3) — Civil disorder; 18 U.S.C. § 111(a)(1) and (b) — Assaulting a federal officer (2 counts).	During 2020 protests in Rochester, NY over the killing of Daniel Prude, John Michael Santiago, 24, threw fireworks at police officers and participated in blockading. He was arrested later for civil disorder; while in custody he assaulted two corrections officers. Sentenced to 33 months federal prison.
Antonio Wooden	Antonio	Wooden	Pablo Le Tony Cushe	Indiana	Indianapolis	23	Black	Male	2020-05-30	32	Federal	18 U.S.C. § 922(g)(2) and (3) — Felon and drug user in possession of a firearm.	Antonio Wooden, 23, was charged in Indianapolis with unlawful possession of a firearm by a fugitive from justice and as an unlawful user of a controlled substance after he was seen firing an AR-15 style rifle towards officers during the protests/riots in downtown Indianapolis. Sentenced to 32 months federal prison.
Richard Tyler Hunsinger	Richard Tyler	Hunsinger	@dickophrenic (Twitter)	Georgia	Atlanta	28	White	Male	2020-07-25	32	Federal	18 U.S.C. § 111 — Assault on a federal official; 18 U.S.C. § 844(f) — Maliciously damaging by fire a building/vehicle owned by the United States; 18 U.S.C. § 1361 — Depredation of government property.	On July 25, 2020 around 11:30 p.m. several protesters including Richard Tyler Hunsinger, 28, wearing dark clothing and covering their faces vandalized the DHS Building in Atlanta, GA. They used rocks, cinder blocks, modified fireworks, Molotov cocktails, and hammers to cause extensive damage. At least one Federal Protective Service Inspector was inside performing official duties; protesters shined lasers at his eyes. Hunsinger was tracked down after agents found blood at the scene and contacted nearby hospitals. Sentenced to 32 months federal prison.
Earlja J. Dudley	Earlja J.	Dudley		New Jersey	Trenton	27	Black	Male	2020-05-31	30	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting (2 counts).	Earlja J. Dudley, 27, was charged with attempt to damage government property by fire and attempt to damage property in commerce by fire on June 17, 2020 for setting a Trenton Police vehicle on fire on May 31, 2020. Dudley was identified through bystander video showing him placing a burning object into the engine well of the vehicle and moving away, plus publicly posted social media photos. Sentenced to 30 months federal prison plus 3 years supervised release.
Dyshika McFadden	Dyshika	McFadden	Dyshieka	New York	Rochester	26	Black	Male	2020-05-30	30	Federal	18 U.S.C. § 231(a)(3) — Civil disorder; 18 U.S.C. § 844(n) — Conspiracy to commit arson; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	Dyshika McFadden, Miguel Ramos, and Tindal are accused of using an aerosol can and open flame to set fire to a Rochester PD vehicle during May 30, 2020 demonstrations in Rochester, NY in response to the death of George Floyd. The car was destroyed; the burning was broadcast on Facebook Live in real-time. Sentenced to 30 months federal prison plus 3 years supervised release and $4,287 restitution.
Alexander Steven Heil	Alexander Steven	Heil		Minnesota	Minneapolis	24	White	Male	2020-05-28	30	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce.	On May 28, 2020 as part of ongoing protests sparked by George Floyd's murder, Alexander Steven Heil, 24, joined and engaged with others to accelerate a fire in the Wells Fargo Bank building in south Minneapolis. Per defense filings, Heil "went to the Lake Street area to be part of the protest, drank too much and in a senseless, impulsive act while clearly under the influence of alcohol, threw a traffic cone into the existing fire." Sentenced to 30 months federal prison.
Jabari Devon Davis	Jabari Devon	Davis		North Carolina	Raleigh	21	Black	Male	2020-05-30	30	Federal	18 U.S.C. § 844(f) — Damaging government property by fire.	Jabari Devon Davis, 21, of Raleigh, NC was charged with attempting to damage by fire a vehicle owned by an institution receiving federal financial assistance and for attempting to set fire to a marked police vehicle in Raleigh after a demonstration over George Floyd's death. Caused ~$5,000 in damage. Arrested by ATF special agents on June 4, 2020. Sentenced to 30 months federal prison.
Ayoub Tabri	Ayoub	Tabri		Pennsylvania	Philadelphia	24	Middle Eastern	Male	2020-05-30	30	Federal	18 U.S.C. § 844(f)(1), (f)(2) — Arson of property belonging to a federally-funded agency; 18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 844(i) — Arson affecting interstate commerce; 18 U.S.C. § 231(a)(3) — Obstruction of law enforcement during civil disorder.	Ayoub Tabri, 24, of Arlington, VA was charged for the arson of a Pennsylvania State Police SUV during civil unrest in Philadelphia on May 30, 2020. PSP placed two patrol SUVs at the on-ramp for I-676 to prevent protestors from accessing the highway; a group attacked the vehicles, shattering windows and stealing road flares, fire extinguishers, and "riot bags" of PSP-issued equipment. Tabri allegedly threw a lit road flare into K1-17, igniting a fire that engulfed the SUV. Tabri was wanted by the FBI Philadelphia Joint Terrorism Task Force prior to capture. Sentenced to 30 months federal prison.
Cortez Lamont Edwards	Cortez Lamont	Edwards		Kentucky	Louisville	29	Black	Male	2020-09-23	30	Federal	18 U.S.C. § 922(g)(1) — Possession of a firearm by a convicted felon.	Cortez Lamont Edwards, 29, of Louisville, KY was charged as a felon in possession of a firearm. On September 23, 2020 Edwards went live on Facebook with an AR variant pistol with a non-extendible support brace and extended magazine. He stated he was requesting payment of $30,000 to shoot Louisville Metro PD officers responding to a disturbance in front of his residence. He had a 2019 felony conviction for trafficking in a controlled substance. ATF, HSI, U.S. Marshals, FPS, and LMPD executed a search warrant at his residence and recovered a Glock 19 9mm pistol. Sentenced to 30 months federal prison plus 2 years supervised release.
Killian F. Melecio	Killian F.	Melecio		New Jersey	Trenton	20	Unknown	Male	2020-05-31	28	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	On May 31, 2020 following protests in Trenton, NJ, Killian Melecio, Kadeem Dockery, and Justin Spry were seen on video attempting to set fire to a police car. Dockery threw an explosive device through the open driver's window; Melecio attempted to put a shirt in the gas tank and light it on fire. Sentenced to 28 months federal prison plus 3 years supervised release.
Andrew Salvarani Garcia-Smith	Andrew Salvarani	Garcia-Smith		North Carolina	Fayetteville	32	Black	Male	2020-05-30	27	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; § 844(f)(2) — Created a substantial risk of injury to any person; 18 U.S.C. § 2 — Aiding and abetting.	Andrew Salvarani Garcia-Smith, 32, was charged for the burning of the Market House in Fayetteville, NC on May 30, 2020. He was caught on video throwing a bottle of burning liquid into the Market House and the burning liquid spilled back onto him, setting his hair and clothes ablaze. Sentenced to 27 months federal prison.
Da'Jon Lengyel	Da'Jon	Lengyel		Pennsylvania	Pittsburgh	22	Black	Male	2020-05-30	27	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 2 — Aiding and abetting; 18 U.S.C. § 231(a)(3) — Interfering with law enforcement.	Da'Jon Lengyel, 22, and Christopher Alan West damaged and destroyed by fire a Pittsburgh police vehicle and damaged a police officer's vehicle by hitting, kicking and stomping on its parts and joining others to destroy it by fire on May 30, 2020. Sentenced to 27 months federal prison.
Samuel Elliott Frey	Samuel Elliott	Frey		Minnesota	St. Paul	19	White	Male	2020-05-28	27	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	On the night of May 28, 2020 Samuel Elliot Frey, 19, Mckenzy Ann Degidio Dunn, 19, and Bailey Marie Baldus, 19, were caught on surveillance camera setting fire at a St. Paul, MN health and nutrition store during the unrest after George Floyd's death. The three named defendants were charged with one count of conspiracy to commit arson; charges against Baldus were dropped. Sentenced to 27 months federal prison plus 2 years supervised release and $33,826.64 restitution.
Kadeem A. Dockery	Kadeem A.	Dockery		New Jersey	Trenton	29	Black	Male	2020-05-31	27	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	On May 31, 2020 following protests in Trenton, NJ, Kadeem Dockery, 29, threw an explosive device through the open driver's window of a police car. While Justin Spry was being arrested, Dockery lit an explosive device and threw it at the arresting officers, which exploded at their feet. Sentenced to 27 months federal prison plus 3 years supervised release.
Bryce Michael Williams	Bryce Michael	Williams		Minnesota	Minneapolis	26	Black	Male	2020-05-28	27	Federal	18 U.S.C. § 844(i) — Arson; 18 U.S.C. § 2 — Aided and abetted; 18 U.S.C. § 371 — Conspiracy.	On August 25, 2020 Bryce Michael Williams was indicted with co-defendants Robinson, Turner, and Wolfe on arson charges for setting fire to the Minneapolis Police Department Third Precinct on May 28, 2020 during the George Floyd protests. Surveillance video showed Williams holding and throwing a Molotov cocktail into the Precinct. Sentenced to 27 months federal prison plus 2 years supervised release and $12 million in restitution (joint and several with co-defendants).
Nautica Turner	Nautica	Turner		Missouri	St. Louis	27	Black	Female	2020-06-01	27	Federal	18 U.S.C. § 844(i) — Conspiracy to commit arson.	On June 1, 2020 Nautica Turner, 27, took lighter fluid and began pouring it on the 7-Eleven at 201 N. 17th Street in St. Louis, MO as the store was being looted. The looting was sparked by the killing of George Floyd. She pleaded guilty to a felony charge of conspiracy to commit arson. Sentenced to 27 months federal prison.
Lamar Taylor	Lamar	Taylor		Illinois	Chicago	23	Black	Male	2020-05-30	26	Federal	Arson conspiracy; civil disorder.	Lamar Taylor, 23, was charged with arson after allegedly setting fire to a Chicago Transit Authority van during a 2020 protest in response to the death of George Floyd. Sentenced to 26 months federal prison.
Dominic D. Brown	Dominic D.	Brown	Dominic Brown	Tennessee	Knoxville	18	Biracial	Male	2020-05-30	24	Federal	18 U.S.C. § 2101 — Use of a facility of interstate commerce to incite a riot; 18 U.S.C. § 231(a)(3) — Civil disorder.	Dominic D. Brown, 18, of Knoxville, TN was charged with riots and civil disorder after posting profane Snapchat messages calling for a riot and after he was observed picking up a trash can lid filled with an unclear liquid and striking an officer who was sitting in a vehicle. Sentenced to 24 months federal prison plus a $100 fine.
Tyree Walker	Tyree	Walker		Nevada	Las Vegas	23	Black	Male	2020-05-30	24	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson (2 counts); 18 U.S.C. § 844(i) and § 2 — Arson in interstate commerce; 18 U.S.C. § 844(f)(1) and § 2 — Attempt to damage government property by fire.	Tyree Walker, 23, was charged in Las Vegas, NV with conspiracy to commit arson and arson with co-defendants Devarian Haynes, 23, and Ricardo Densmore, 24, after they were identified on video (taken by Densmore) of Walker and Haynes setting a police car on fire on May 30, 2020. Sentenced to 24 months federal prison.
Devarian Haynes	Devarian	Haynes		Nevada	Las Vegas	23	Black	Male	2020-05-30	24	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson (2 counts); 18 U.S.C. § 844(i) and § 2 — Arson in interstate commerce; 18 U.S.C. § 844(f)(1) and § 2 — Attempt to damage government property by fire.	Devarian Haynes, 23, of Las Vegas was charged with co-defendants Tyree Walker and Ricardo Densmore for conspiracy to commit arson and arson after a May 30, 2020 video showed Walker and Haynes setting a police car on fire during protests over the death of George Floyd. Sentenced to 24 months federal prison.
Ricardo Densmore	Ricardo	Densmore		Nevada	Las Vegas	24	Latino	Male	2020-05-30	24	Federal	18 U.S.C. § 844(n) — Conspiracy to commit arson (2 counts); 18 U.S.C. § 844(i) and § 2 — Arson in interstate commerce; 18 U.S.C. § 844(f)(1) and § 2 — Attempt to damage government property by fire.	Ricardo Densmore, 24, of Las Vegas was charged with co-defendants Tyree Walker and Devarian Haynes for conspiracy to commit arson and arson after he filmed Walker and Haynes setting a police car on fire on May 30, 2020. Sentenced to 24 months federal prison.
Nicholas Lucia	Nicholas	Lucia		Pennsylvania	Pittsburgh	25	White	Male	2020-05-30	24	Federal	18 U.S.C. § 2 and § 231(a)(3) — Obstruction of law enforcement during civil disorder.	Nicholas Lucia, 25, of Pittsburgh, PA was charged with obstruction of law enforcement during civil disorder. On May 30, 2020 Lucia willfully threw an object at uniformed police officers that appeared to be an explosive device, which landed on an officer's vest, was quickly pulled off by another officer, and exploded when it hit the ground. Sentenced to 24 months federal prison.
Devinare Antwan Parker	Devinare Antwan	Parker		Washington	Seattle	25	Black	Male	2020-05-31	24	Federal	26 U.S.C. § 5861(d) — Unlawful possession of a destructive device.	Devinare Antwan Parker, 25, was charged in Seattle, WA with unlawful possession of a destructive device after he threw a 16-ounce can of beer through the window of a Seattle PD car, striking an officer in the face on May 31, 2020. When arrested he possessed an improvised firearm capable of firing shotgun shells. While being arrested he yelled that he had brought the firearm to kill police officers. Sentenced to 24 months federal prison.
Jackson Stuart Tamowski Patton	Jackson Stuart Tamowski	Patton		Utah	Salt Lake City	26	White	Male	2020-05-30	24	Federal	18 U.S.C. § 844(i) — Arson in interstate commerce; civil disorder.	Jackson Stuart Tamowski Patton, 26, of Salt Lake City, UT was charged with one count of arson in interstate commerce for setting fire to a Salt Lake City PD vehicle during May 30, 2020 protests. Sentenced to 24 months federal prison plus 3 years supervised release and $2,500 restitution.
Al M. Talaga	Al M.	Talaga		Washington	Seattle	32	Native Hawaiian/Pacific Islander	Male	2020-06-01	24	Federal	18 U.S.C. § 922(g)(1) — Felon in possession of a firearm.	Al M. Talaga, 32, of Auburn, WA was arrested and charged federally as a felon in possession of a firearm. On June 1, 2020 Seattle PD responded to reports of a break-in at the Sneaker City store on Pike Street; suspects fled. Police impounded a Dodge Magnum traced to Talaga and found two loaded handguns inside (a .40 Glock and a stolen .40 pistol from a 2019 Tacoma home invasion). Talaga was prohibited from possessing firearms due to a 2005 King County Second Degree Robbery conviction. Sentenced to 24 months federal prison.
Justin D. Spry	Justin D.	Spry		New Jersey	Trenton	21	White	Male	2020-05-31	24	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	On May 31, 2020 following protests in Trenton, NJ, Justin Spry, 21, was seen on video with Killian Melecio and Kadeem Dockery attempting to set fire to a police car. Spry was arrested at the scene; Melecio and Dockery fled. Sentenced to 24 months federal prison plus 3 years supervised release.
Isaiah Thomas Willoughby	Isaiah Thomas	Willoughby		Washington	Seattle	35	Black	Male	2020-06-12	24	Federal	18 U.S.C. § 844(f)(1) — Attempt to damage government property by fire; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Isaiah Thomas Willoughby, 35, of Seattle, WA was arrested on a federal arson charge after his family recognized him by his distinctive yellow hoodie in surveillance video. He was seen on June 12, 2020 starting a small fire at the Seattle PD East Precinct, then within the protester-occupied zone on Capitol Hill (CHAZ/CHOP). Sentenced to 24 months federal prison.
Dakotah Ray Horton	Dakotah Ray	Horton		Oregon	Portland	24	White	Male	2020-07-27	24	Federal	18 U.S.C. § 111(b) — Assault on a federal agent.	In June and July 2020 the Hatfield Federal Courthouse in Portland, OR was the site of large protests and repeated vandalism. On July 27, 2020 rioters attempted to destroy a security fence with power tools and threw hard objects, glass bottles, and explosive devices at officers. As a U.S. Marshal knelt to assist with an arrest, Dakotah Ray Horton, 24, struck the deputy in the upper back, neck, and shoulder with a wooden baseball bat. Sentenced to 24 months federal prison.
Felix Missael Alva	Felix Missael	Alva		Colorado	Denver	29	Latino	Male	2020-05-30	24	Federal	18 U.S.C. § 922(g)(5)(a) — Knowingly possessed a firearm while being illegally or unlawfully in the United States; 8 U.S.C. § 1326(a) — Illegal reentry.	On May 30, 2020 a Denver detective working downtown saw a white Jeep stop nearby with a male passenger producing a black semi-automatic handgun and saying "This ain't no peaceful protest" before firing approximately 6-10 rounds into the air while a DPD helicopter and a news helicopter were overhead. Felix Missael Alva, 29, was identified as the shooter; an Aurora SWAT search of his residence found firearms in a shed. Alva was a previously deported foreign national. Sentenced to 24 months federal prison.
Kelsey Donnel Jackson	Kelsey Donnel	Jackson		South Carolina	Charleston	28	Black	Male	2020-05-30	24	Federal	18 U.S.C. § 844(i) — Actual or attempted damage by fire of any building, vehicle, or other property used in interstate commerce; 18 U.S.C. § 2 — Aiding and abetting.	Kelsey Jackson, 28, of Charleston, SC pled guilty to arson of a Charleston Police Department patrol car on May 30, 2020. Sentenced to 24 months federal prison plus $1,224.06 restitution (joint and several with Guthrie and Jenkins) and 3 years supervised release.
Orlando Shalrocko King	Orlando Shalrocko	King		South Carolina	Charleston	31	Black	Male	2020-05-30	24	Federal	18 U.S.C. § 2 — Civil disorder; 18 U.S.C. § 2101 — Carrying on a riot; 18 U.S.C. § 922(g)(1) — Possession of a firearm by a convicted felon.	Orlando King, 31, of North Charleston, SC was indicted on charges of violating the Anti-Riot Act on May 30, 2020 and felon in possession of a firearm (from an unrelated April 25, 2020 incident). King livestreamed the looting and destruction of a store, the College Market, on Facebook. Sentenced to 24 months federal prison plus 3 years supervised release.
Jonathan Montanez	Jonathan	Montanez	Montanezage	North Dakota	Fargo	31	Latino	Male	2020-05-30	24	Federal	18 U.S.C. § 231(a)(3) — Civil disorder.	Jonathan Montanez was charged by grand jury indictment with one count of civil disorder for knowingly committing an act to obstruct, impede, and interfere with any fireman or law enforcement officer lawfully engaged in official duties on May 30, 2020. During the May 30 riots in Fargo, ND, he jumped on a police squad car and possibly damaged it while inciting a crowd. Sentenced to 24 months federal prison.
Thomas Wilder Moseley	Thomas Wilder	Moseley	Tom Moseley	Minnesota	Minneapolis	29	Asian	Male	2021-03-23	24	Federal	18 U.S.C. § 922(g)(3) — Possessing firearms and ammunition while being an unlawful user of controlled substances; Minn. Stat. § 609.66.1g(a)(1) — Dangerous weapon - possess in courthouse.	Thomas Wilder Moseley, 29, was charged in Minneapolis, MN with possessing firearms and ammunition while being an unlawful user of controlled substances. He resisted arrest after being seen reaching for his waistband, which held a loaded handgun. The protest was held outside the Government Center and was part of the Summer 2020 wave of protests after George Floyd's murder. Sentenced to time served plus 2 years supervised release.
David Bermudez	David	Bermudez		California	Los Angeles	33	Latino	Male	2020-05-30	24	Non-Federal	Cal. Penal Code § 451(c) — Arson.	On March 24, 2022 David Bermudez, 33, of Los Angeles, CA pled "no contest" to a charge of looting. Bermudez was arrested in Los Angeles by the Safe LA Task Force after the George Floyd Protests. Sentenced to 2 years in county jail.
Nathan Joseph Waller	Nathan Joseph	Waller		Pennsylvania	Erie	25	White	Male	2020-05-30	21	Non-Federal	18 Pa. § 2702(a)(6) — Aggravated assault; § 5501(2) — Riot; § 2701(a)(3) — Simple assault; § 3921(a) — Theft by unlawful taking; § 3925A — Receiving stolen property; § 2705 — Recklessly endangering another person; § 5502 — Failure to disperse.	Nathan Joseph Waller, 25, of Erie, PA was sentenced to 9 to 21.5 months in state prison and 60 days on electronic monitoring after pleading guilty to three criminal charges following a series of Black Lives Matter protests in May 2020. He was accused of throwing objects at police officers on a roof at Erie City Hall as they tried to disperse a large crowd outside of the city police station and of carrying the top of a broken parking meter into an apartment building.
Jesse James Smallwood	Jesse James	Smallwood		Georgia	Gainesville	21	White	Male	2020-05-30	21	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Jesse James Smallwood, 21, was indicted in Gainesville, GA in June 2020 with co-defendants Delveccho Waller Jr., Bruce Thompson, Judah Coleman Bailey, and Dashun Martin for conspiring to commit and committing arson of a police car after a protest sparked by George Floyd's death. The defendants allegedly sought out and burned the police vehicle using the protests as cover. Sentenced to 21 months federal prison plus 3 years supervised release and $3,678.17 restitution.
Judah Coleman Bailey	Judah Coleman	Bailey		Georgia	Gainesville	20	Black	Male	2020-05-30	21	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Judah Coleman Bailey, 20, was indicted in Gainesville, GA with co-defendants Smallwood, Waller, Thompson, and Martin for conspiring to commit and committing arson of a police car after a protest sparked by George Floyd's death in May 2020. Sentenced to 21 months federal prison plus 3 years supervised release and $3,678.17 restitution.
Delveccho Waller	Delveccho	Waller Jr.		Georgia	Gainesville	21	Black	Male	2020-05-30	21	Federal	18 U.S.C. § 371 — Conspiracy; 18 U.S.C. § 844(i) — Arson in interstate commerce.	Delveccho Waller Jr., 21, was indicted in Gainesville, GA with co-defendants Smallwood, Bailey, Thompson, and Martin for conspiring to commit and committing arson of a police car after a protest sparked by George Floyd's death in May 2020. Sentenced to 21 months federal prison plus 3 years supervised release and $3,678.17 restitution.
TSV;

$rows = array_filter(array_map('trim', explode("\n", $DATA)));

$today = Carbon::today();
$created = 0;
$skipped = 0;

foreach ($rows as $line) {
    $parts = explode("\t", $line);
    if (count($parts) < 14) continue;
    [$name, $first, $last, $aka, $state, $city, $age, $race, $gender,
     $arrest, $months, $jurisdiction, $charges, $narrative] = array_pad($parts, 16, '');
    $extraIdeologies   = $parts[14] ?? '';
    $extraAffiliations = $parts[15] ?? '';

    if (Prisoner::where('name', $name)->exists()) {
        echo "  [skip] {$name} — already in DB\n";
        $skipped++;
        continue;
    }

    $arrestC  = Carbon::parse($arrest);
    $releaseC = $arrestC->copy()->addMonths((int) $months);
    $inCustody = $releaseC->gt($today);

    $sentenceText = ((int) $months) . ' months ' . ($jurisdiction === 'Federal' ? 'federal' : 'state') . ' prison'
                  . ' (incarceration ' . $arrestC->format('Y-m-d') . ' → projected release ' . $releaseC->format('Y-m-d') . ').';

    $instName = ($jurisdiction === 'Federal' ? 'Federal Bureau of Prisons' : 'State prison')
              . ' (' . $state . ')';

    $ideologies = ['Black Lives Matter', 'Anti-police violence', 'Summer 2020 protests'];
    if ($extraIdeologies) {
        foreach (preg_split('/\s*,\s*/', $extraIdeologies) as $i) {
            if ($i !== '') $ideologies[] = $i;
        }
    }
    $ideologies = array_values(array_unique($ideologies));

    $affiliations = [];
    if ($extraAffiliations) {
        foreach (preg_split('/\s*,\s*/', $extraAffiliations) as $a) {
            if ($a !== '') $affiliations[] = $a;
        }
    }

    $birth = $today->copy()->subYears((int) $age)->format('Y-m-d');

    $prisoner = Prisoner::create([
        'name'                => $name,
        'first_name'          => $first,
        'last_name'           => $last,
        'aka'                 => $aka ?: null,
        'description'         => $narrative,
        'state'               => $state,
        'race'                => $race ?: null,
        'gender'              => $gender,
        'birthdate'           => $birth,
        'ideologies'          => $ideologies,
        'affiliation'         => $affiliations ?: null,
        'era'                 => '2020s',
        'in_custody'          => $inCustody,
        'released'            => ! $inCustody,
    ]);

    $inst = Institution::firstOrCreate(
        ['name' => $instName],
        ['city' => $city, 'state' => $state]
    );

    PrisonerCase::create([
        'prisoner_id'        => $prisoner->id,
        'institution_id'     => $inst->id,
        'charges'            => $charges,
        'arrest_date'        => $arrestC->format('Y-m-d'),
        'incarceration_date' => $arrestC->format('Y-m-d'),
        'release_date'       => $inCustody ? null : $releaseC->format('Y-m-d'),
        'sentence'           => $sentenceText,
        'convicted'          => 'Yes',
    ]);

    echo "  [add]  {$name}  ({$months} mo, {$jurisdiction})\n";
    $created++;
}

echo "\nDone. created={$created}, skipped={$skipped}\n";
