#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round15_brinks_bla_sla_forthood_alamin.sh
#
# Source clusters:
#   - Brink's 1981 robbery co-defendants beyond what's already in DB
#     (Kuwasi Balagoon, Mutulu Shakur, Sekou Odinga, Marilyn Buck, Iya
#     Fulani Sunni-Ali, Alan Berkman are already covered)
#   - Jalil Muntaqim - 1971 NYPD officer killing; released October 7, 2020
#     after 49 years
#   - Sara Jane Olson / Kathleen Soliah - Symbionese Liberation Army;
#     1999 capture after 20+ years underground; released 2009
#   - Fort Hood Three (June 30, 1966 first public refusal of Vietnam
#     orders by US soldiers; September 1966 court-martial)
#   - Imam Jamil Al-Amin (H. Rap Brown) - 2002 conviction of Fulton
#     County deputy killing; died in federal prison November 23, 2025
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Brink's 1981 co-defendants ===

php artisan prisoner:add '{"name":"David Gilbert","first_name":"David","last_name":"Gilbert","description":"David Gilbert was a former Students for a Democratic Society organizer at Columbia University, a co-founder of the Weather Underground, and one of the four May 19th Communist Organization members who served as getaway drivers in the October 20, 1981 Brink s armored-car expropriation in Nyack, New York, in support of the Black Liberation Army. He was arrested at the scene on October 20, 1981, convicted on September 14, 1983 in Rockland County, New York state court of two counts of first-degree armed robbery and three counts of second-degree murder, and sentenced to 75 years to life. He spent 40 years at the Auburn Correctional Facility, where he became a leading inside organizer on AIDS education and the partner of Kathy Boudin in raising their son Chesa Boudin in absentia. After Governor Andrew Cuomo commuted his sentence in August 2021 he was paroled on October 26, 2021 at age 76. His memoir Love and Struggle was published in 2012 by PM Press.","state":"New York","race":"White","gender":"Male","birthdate":"1944-10-06","ideologies":["Anti-imperialist","Communist","Anti-racist"],"affiliation":["Weather Underground","May 19th Communist Organization","Students for a Democratic Society"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Auburn Correctional Facility","institution_city":"Auburn","institution_state":"New York","charges":"New York state two counts first-degree armed robbery and three counts second-degree murder - October 20, 1981 Brink s armored-car expropriation in Nyack, New York","arrest_date":"1981-10-20","incarceration_date":"1981-10-20","release_date":"2021-10-26","sentence":"75 years to life; sentence commuted by Governor Andrew Cuomo August 2021; paroled after 40 years","convicted":"Yes - New York state jury verdict, Rockland County, September 14, 1983"}]}' || true

php artisan prisoner:add '{"name":"Judith Clark","first_name":"Judith","middle_name":"Alice","last_name":"Clark","description":"Judith Alice Clark was a former Weather Underground organizer and one of the four May 19th Communist Organization members who served as getaway drivers in the October 20, 1981 Brink s armored-car expropriation in Nyack, New York. She was arrested at the scene, convicted on September 14, 1983 in Rockland County, New York state court of two counts of first-degree armed robbery and three counts of second-degree murder, and sentenced to 75 years to life. She spent 38 years at the Bedford Hills Correctional Facility for Women, where she became a leading inside organizer for the Bedford Hills Family Center and the partner program for incarcerated mothers. Governor Andrew Cuomo commuted her sentence in December 2016; she was paroled in April 2019.","state":"New York","race":"White","gender":"Female","birthdate":"1949-11-23","ideologies":["Anti-imperialist","Communist","Anti-racist"],"affiliation":["Weather Underground","May 19th Communist Organization"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Bedford Hills Correctional Facility","institution_city":"Bedford Hills","institution_state":"New York","charges":"New York state two counts first-degree armed robbery and three counts second-degree murder - October 20, 1981 Brink s armored-car expropriation in Nyack, New York","arrest_date":"1981-10-20","incarceration_date":"1981-10-20","release_date":"2019-04-25","sentence":"75 years to life; sentence commuted by Governor Andrew Cuomo December 2016; paroled after 38 years","convicted":"Yes - New York state jury verdict, Rockland County, September 14, 1983"}]}' || true

php artisan prisoner:add '{"name":"Kathy Boudin","first_name":"Kathy","last_name":"Boudin","description":"Katherine Boudin was a former Weather Underground organizer and one of the four May 19th Communist Organization members who served as getaway drivers in the October 20, 1981 Brink s armored-car expropriation in Nyack, New York. After her arrest at the scene she pleaded guilty in May 1984 to a single count of felony murder and was sentenced to 20 years to life. She served 22 years at the Bedford Hills Correctional Facility for Women, where she completed a doctorate in education and helped create the prisons HIV/AIDS peer-education program. She was paroled on September 17, 2003. After her release she taught at Columbia University and at the New York University Silver School of Social Work, and co-directed the Center for Justice at Columbia. She died of complications from cancer on May 1, 2022, age 78. Her son Chesa Boudin, raised by Bill Ayers and Bernardine Dohrn while she was incarcerated, was the elected District Attorney of San Francisco from 2020 to 2022.","state":"New York","race":"White","gender":"Female","birthdate":"1943-05-19","death_date":"2022-05-01","ideologies":["Anti-imperialist","Communist","Anti-racist"],"affiliation":["Weather Underground","May 19th Communist Organization","Columbia University Center for Justice"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Bedford Hills Correctional Facility","institution_city":"Bedford Hills","institution_state":"New York","charges":"New York state felony murder - October 20, 1981 Brink s armored-car expropriation in Nyack, New York","arrest_date":"1981-10-20","incarceration_date":"1981-10-20","release_date":"2003-09-17","sentence":"20 years to life; paroled September 2003 after 22 years","convicted":"Yes - guilty plea, Rockland County, May 1984"}]}' || true

php artisan prisoner:add '{"name":"Sam Brown","first_name":"Sam","last_name":"Brown","aka":"Sekou Abdullah Mtetezi","description":"Samuel Brown, who took the New Afrikan name Sekou Abdullah Mtetezi in prison, was a Black Liberation Army member arrested in connection with the October 20, 1981 Brink s armored-car expropriation in Nyack, New York. He was apprehended in late 1981, convicted on June 14, 1984 in Rockland County, New York state court of murder and armed robbery, and on June 26, 1984 sentenced to three consecutive prison terms of 25 years to life. He has been held in the New York state prison system for more than four decades. The Jericho Movement lists him among its current political prisoners.","state":"New York","race":"Black","gender":"Male","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Liberation Army","Republic of New Afrika"],"era":"1980s","in_custody":true,"released":false,"cases":[{"institution_name":"New York Department of Corrections","institution_state":"New York","charges":"New York state murder and armed robbery - October 20, 1981 Brink s armored-car expropriation in Nyack, New York","arrest_date":"1981-12-01","incarceration_date":"1981-12-01","sentence":"75 years (three consecutive 25-to-life sentences)","convicted":"Yes - New York state jury verdict, Rockland County, June 14, 1984"}]}' || true

php artisan prisoner:add '{"name":"Jamal Joseph","first_name":"Jamal","last_name":"Joseph","description":"Jamal Joseph, born Eddie Joseph in The Bronx in 1953, was at age 16 the youngest defendant in the 1969 Panther 21 case (acquitted with the rest of the Panther 21 in May 1971). He was convicted in U.S. District Court in 1983 as an accessory after the fact in connection with the October 20, 1981 Brink s expropriation in Nyack, New York and the alleged 1979 liberation of Assata Shakur. He served eight years at the federal penitentiary in Leavenworth, Kansas, where he completed two college degrees and began the writing career that has made him a major American figure since release. He has been a tenured professor of film at the Columbia University School of the Arts since 2005 and chaired the schools Graduate Film MFA program.","state":"New York","race":"Black","gender":"Male","birthdate":"1953-04-12","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Panther 21","Black Liberation Army","Columbia University"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Leavenworth","institution_city":"Leavenworth","institution_state":"Kansas","charges":"Federal accessory after the fact - October 20, 1981 Brink s expropriation and 1979 alleged liberation of Assata Shakur","arrest_date":"1982-09-15","incarceration_date":"1983-04-01","release_date":"1991-03-15","sentence":"Federal prison; served 8 years","convicted":"Yes - federal court conviction, U.S. District Court for the Southern District of New York, 1983"}]}' || true

php artisan prisoner:add '{"name":"Mtayari Sundiata","first_name":"Mtayari","last_name":"Sundiata","aka":"Samuel Smith","description":"Mtayari Shabaka Sundiata, born Samuel Smith, was a Black Liberation Army member who participated in the October 20, 1981 Brink s armored-car expropriation in Nyack, New York. He fled the scene after the gunfight that killed Brink s guard Peter Paige and Nyack police officers Edward O Grady and Waverly Brown, and was killed three days later by NYPD detectives in a confrontation in Queens, New York on October 23, 1981.","state":"New York","race":"Black","gender":"Male","death_date":"1981-10-23","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Liberation Army","Republic of New Afrika"],"era":"1980s","in_custody":false,"released":false,"cases":[{"institution_name":"(killed by police three days after the action)","institution_state":"New York","charges":"Black Liberation Army participation in the October 20, 1981 Brink s armored-car expropriation in Nyack, New York; killed by NYPD October 23, 1981","death_in_custody_date":"1981-10-23","sentence":"Killed by NYPD October 23, 1981","convicted":"No - killed before any prosecution"}]}' || true

php artisan prisoner:add '{"name":"Silvia Baraldini","first_name":"Silvia","last_name":"Baraldini","description":"Silvia Baraldini was an Italian-born May 19th Communist Organization member who lived and organized in New York City beginning in the late 1970s. She was convicted in U.S. District Court in 1984 of conspiracy and racketeering in connection with the October 20, 1981 Brink s expropriation and the 1979 liberation of Assata Shakur, and sentenced to 43 years in federal prison. After two decades of Italian government and international campaigns for her transfer, she was repatriated to Italy on August 24, 1999 to serve the remainder of her U.S. sentence under Italian custody. The Italian courts paroled her in October 2006. She has lived in Rome since.","state":"New York","race":"White","gender":"Female","birthdate":"1947-12-12","ideologies":["Anti-imperialist","Communist","Anti-racist"],"affiliation":["May 19th Communist Organization"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (transferred to Italian custody 1999)","charges":"Federal conspiracy and racketeering - October 20, 1981 Brink s expropriation and 1979 liberation of Assata Shakur","arrest_date":"1982-11-09","incarceration_date":"1982-11-09","release_date":"2006-10-26","sentence":"43 years federal prison; transferred to Italy August 24, 1999; paroled in Italy October 2006","convicted":"Yes - federal jury verdict, U.S. District Court for the Southern District of New York, 1984"}]}' || true

# === Jalil Muntaqim (Anthony Bottom) ===

php artisan prisoner:add '{"name":"Jalil Muntaqim","first_name":"Jalil","last_name":"Muntaqim","aka":"Anthony Bottom","description":"Jalil Muntaqim, born Anthony Jalil Bottom in Oakland, California in 1951, joined the Black Panther Party at age 18 after the assassination of Martin Luther King Jr. and went underground with the Black Liberation Army by 1971. He was arrested at age 19 in San Francisco on August 28, 1971, in connection with the May 21, 1971 ambush killing of New York Police Department officers Joseph Piagentini and Waverly Jones in Harlem. He was convicted in 1975 of two counts of first-degree murder and sentenced to two consecutive 25-years-to-life sentences. He served his time across the New York and California state systems.\n\nHe was repeatedly denied parole — eleven times over four decades. He was a co-founder, with Safiya Bukhari and others, of the 1998 Jericho Movement for amnesty for U.S. political prisoners. After hospitalization for COVID-19 in June 2020 his case became a national focus; on September 23, 2020 the New York State Parole Board granted him release. He was paroled on October 7, 2020, age 69, after 49 years and three months in prison. The state of New York still knows him by the name Anthony Bottom.","state":"New York","race":"Black","gender":"Male","birthdate":"1951-10-18","ideologies":["Black Liberation","New Afrikan Independence"],"affiliation":["Black Panther Party","Black Liberation Army","Jericho Movement"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"New York Department of Corrections (Sullivan, Attica, Auburn)","institution_state":"New York","charges":"New York state two counts first-degree murder - May 21, 1971 ambush killing of NYPD officers Joseph Piagentini and Waverly Jones in Harlem","arrest_date":"1971-08-28","incarceration_date":"1971-08-28","release_date":"2020-10-07","sentence":"Two consecutive 25-years-to-life sentences; paroled after 49 years 3 months","convicted":"Yes - New York state jury verdict, 1975"}]}' || true

# === Sara Jane Olson / Kathleen Soliah - SLA ===

php artisan prisoner:add '{"name":"Sara Jane Olson","first_name":"Kathleen","middle_name":"Ann","last_name":"Soliah","aka":"Sara Jane Olson","description":"Kathleen Ann Soliah, who lived under the name Sara Jane Olson for more than two decades, was a member of the Symbionese Liberation Army who participated in the August 1975 attempted bombing of two Los Angeles Police Department squad cars in retaliation for the May 17, 1974 LAPD-FBI raid that killed six SLA members. She fled California in 1975 and lived as Sara Jane Olson in Saint Paul, Minnesota for 24 years — marrying a doctor, raising three daughters, becoming active in her local Methodist church, and acting in community theatre. She was arrested in Saint Paul on June 16, 1999.\n\nIn October 2002 she pleaded no contest to two counts of attempted murder for the LAPD car-bomb action and was sentenced to two consecutive 10-years-to-life terms; the Board of Prison Terms set her sentence at 14 years. She also pleaded guilty in 2003 to second-degree murder for the April 21, 1975 SLA bank robbery in Carmichael, California in which a customer named Myrna Opsahl was killed; she was sentenced to an additional 6 years to run concurrently. She was released on parole on March 17, 2009.","state":"California","race":"White","gender":"Female","birthdate":"1947-01-16","ideologies":["Anti-imperialist","Symbionese Liberation Army"],"affiliation":["Symbionese Liberation Army"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Central California Womens Facility","institution_city":"Chowchilla","institution_state":"California","charges":"California state two counts attempted murder (1975 LAPD car bombings) and second-degree murder (April 1975 SLA bank robbery in Carmichael)","arrest_date":"1999-06-16","incarceration_date":"2002-10-04","sentenced_date":"2002-10-04","release_date":"2009-03-17","sentence":"14 years California state prison","convicted":"Yes - no-contest plea, Los Angeles Superior Court, October 2002; 2003 guilty plea on Carmichael bank robbery"}]}' || true

# === Fort Hood Three ===

php artisan prisoner:add '{"name":"James Johnson Jr.","first_name":"James","last_name":"Johnson","description":"Private First Class James Johnson Jr. was an African-American U.S. Army soldier stationed at Fort Hood, Texas in 1966. On June 30, 1966 he, with fellow soldiers Dennis Mora and David Samas, became the first U.S. service members to publicly refuse orders to deploy to Vietnam — a refusal they announced at a press conference in New York organized with the help of attorneys Stanley Faulkner and David Rein and read by Mora. They denounced the war as immoral, illegal and unjust. They filed a federal suit against Secretary of Defense Robert McNamara to prevent their deployment, lost in the Second Circuit, and were court-martialed for insubordination at Fort Dix, New Jersey in late September 1966. He was sentenced to five years at hard labor; in July 1967 his sentence was reduced to three years on review. He was released in 1968.","state":"Texas","race":"Black","gender":"Male","ideologies":["Anti-war","Civil rights"],"affiliation":["Fort Hood Three","U.S. Army (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Fort Leavenworth Disciplinary Barracks","institution_city":"Fort Leavenworth","institution_state":"Kansas","charges":"Military insubordination - June 30, 1966 public refusal to deploy to Vietnam","arrest_date":"1966-07-07","incarceration_date":"1966-09-28","sentenced_date":"1966-09-28","release_date":"1968-09-28","sentence":"5 years military prison; reduced to 3 years on July 1967 review","convicted":"Yes - military court-martial conviction, Fort Dix, September 1966"}]}' || true

php artisan prisoner:add '{"name":"Dennis Mora","first_name":"Dennis","last_name":"Mora","description":"Private Dennis Mora was a Puerto Rican U.S. Army soldier from New York stationed at Fort Hood, Texas in 1966. He was the most politically experienced of the Fort Hood Three (a member of the W.E.B. DuBois Clubs and a Communist Party-aligned youth organizer in his civilian life), and read the public refusal statement at the June 30, 1966 New York press conference at which he, James Johnson Jr., and David Samas announced they would not deploy to Vietnam. He was court-martialed at Fort Dix in late September 1966 and sentenced to three years at hard labor. He died on July 14, 2014.","state":"Texas","race":"Hispanic","gender":"Male","death_date":"2014-07-14","ideologies":["Anti-war","Communist","Anti-racist"],"affiliation":["Fort Hood Three","W.E.B. DuBois Clubs","U.S. Army (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Fort Leavenworth Disciplinary Barracks","institution_city":"Fort Leavenworth","institution_state":"Kansas","charges":"Military insubordination - June 30, 1966 public refusal to deploy to Vietnam","arrest_date":"1966-07-07","incarceration_date":"1966-09-28","sentenced_date":"1966-09-28","release_date":"1968-09-28","sentence":"3 years military prison","convicted":"Yes - military court-martial conviction, Fort Dix, September 1966"}]}' || true

php artisan prisoner:add '{"name":"David Samas","first_name":"David","last_name":"Samas","description":"Private David A. Samas was an Italian-Lithuanian-American U.S. Army soldier stationed at Fort Hood, Texas in 1966. With James Johnson Jr. and Dennis Mora — the Fort Hood Three — he announced public refusal of orders to Vietnam at a New York press conference on June 30, 1966. He was court-martialed at Fort Dix in late September 1966 and sentenced to five years at hard labor; in July 1967 his sentence was reduced to three years on review. He was released in 1968.","state":"Texas","race":"White","gender":"Male","ideologies":["Anti-war"],"affiliation":["Fort Hood Three","U.S. Army (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Fort Leavenworth Disciplinary Barracks","institution_city":"Fort Leavenworth","institution_state":"Kansas","charges":"Military insubordination - June 30, 1966 public refusal to deploy to Vietnam","arrest_date":"1966-07-07","incarceration_date":"1966-09-28","sentenced_date":"1966-09-28","release_date":"1968-09-28","sentence":"5 years military prison; reduced to 3 years on July 1967 review","convicted":"Yes - military court-martial conviction, Fort Dix, September 1966"}]}' || true

# === Imam Jamil Al-Amin (H. Rap Brown) ===

php artisan prisoner:add '{"name":"Imam Jamil Al-Amin","first_name":"Hubert","middle_name":"Gerold","last_name":"Brown","aka":"H. Rap Brown / Jamil Abdullah Al-Amin","description":"Hubert Gerold Brown, known as H. Rap Brown in the late 1960s and as Imam Jamil Abdullah Al-Amin after his 1971 conversion to Islam, was the fifth chairman of the Student Nonviolent Coordinating Committee (1967-68), the Minister of Justice of the Black Panther Party in 1968, the author of Die Nigger Die! (1969), and one of the most prominent Black Power figures of the late 1960s. After his prison conversion to Sunni Islam he became the imam of the Atlanta Community Mosque and a leading figure in the Imam Jamil Action Network and Dar ul-Islam mosque movement. The Atlanta community mosque he led at the West End drew thousands and was widely credited with reducing drug-related crime in the neighborhood.\n\nOn March 16, 2000, Fulton County Sheriffs Deputies Ricky Kinchen and Aldranon English approached him outside his West End store to execute a warrant. Gunfire was exchanged; Kinchen was killed and English was wounded. He fled and was apprehended four days later in White Hall, Alabama. On March 9, 2002 he was convicted by a Fulton County jury and on March 14, 2002 sentenced to life without the possibility of parole.\n\nHis defense and supporters consistently maintained that the conviction relied on disputed eyewitness identifications and that another man — federal inmate Otis Jackson — had repeatedly confessed under oath to having committed the killings. The Council on American-Islamic Relations, the Imam Jamil Action Network, and other Muslim civil rights organizations called for the case to be reopened. He died at FMC Butner in North Carolina on November 23, 2025, age 82, while still serving the life sentence.","state":"Georgia","race":"Black","gender":"Male","birthdate":"1943-10-04","death_date":"2025-11-23","ideologies":["Black Liberation","Sunni Islam","Pan-African"],"affiliation":["Student Nonviolent Coordinating Committee","Black Panther Party","Atlanta Community Mosque","Dar ul-Islam"],"era":"2000s","in_custody":false,"released":false,"cases":[{"institution_name":"Federal Medical Center, Butner (transferred from Georgia state custody)","institution_city":"Butner","institution_state":"North Carolina","charges":"Georgia state murder of Fulton County Sheriff Deputy Ricky Kinchen, March 16, 2000","arrest_date":"2000-03-20","incarceration_date":"2002-03-14","sentenced_date":"2002-03-14","death_in_custody_date":"2025-11-23","sentence":"Life without the possibility of parole; transferred to federal Bureau of Prisons custody","convicted":"Yes - Georgia state jury verdict, Fulton County Superior Court, March 9, 2002"}]}' || true

echo
echo "Round 15 (Brink s 1981 + BLA elders + SLA + Fort Hood Three + Al-Amin) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
