#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round10_plowshares_whistleblowers_iraq.sh
#
# Source clusters:
#   - Transform Now Plowshares (July 28, 2012) — Y-12 National Security
#     Complex, Oak Ridge TN; nun (age 82) and 2 Catholic Worker veterans
#     entered the high-enriched-uranium storage facility, hammered the
#     wall, poured blood; Sabotage Act convictions vacated by 6th Cir 2015
#   - Espionage Act whistleblowers (Daniel Hale drone warfare; Reality
#     Winner Russian-interference report)
#   - Cleveland 4 (April 30, 2012 FBI sting in Cuyahoga Valley)
#   - Iraq War resisters (Camilo Mejia, Stephen Funk)
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Transform Now Plowshares — Y-12, Oak Ridge TN, July 28, 2012 ===

php artisan prisoner:add '{"name":"Megan Rice","first_name":"Megan","last_name":"Rice","description":"Sister Megan Rice was a Sister of the Holy Child Jesus, decades-long missionary in Africa, and a longtime Plowshares anti-nuclear activist. On July 28, 2012, at age 82, she and fellow Catholic Worker peace activists Greg Boertje-Obed and Michael Walli — Transform Now Plowshares — cut through three security fences and entered the Y-12 National Security Complex at Oak Ridge, Tennessee, the U.S. governments principal high-enriched-uranium storage facility. They walked unhindered to the building wall, hammered the wall with household hammers, painted on it, and poured human blood. They were arrested at the scene and held in federal custody.\n\nIn 2013 they were convicted of sabotage of national defense premises and depredation of government property in U.S. District Court for the Eastern District of Tennessee. She was sentenced to 35 months in federal prison; her co-defendants received 62 months each, with the longer sentences reflecting their previous Plowshares convictions. On May 8, 2015 the Sixth Circuit Court of Appeals vacated the sabotage convictions, ruling that the government had failed to prove the activists intended to injure the national defense; the depredation convictions were upheld. The three were released on May 16, 2015. Sister Megan died on October 10, 2021, age 91.","state":"Tennessee","race":"White","gender":"Female","birthdate":"1930-01-31","death_date":"2021-10-10","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Society of the Holy Child Jesus","Transform Now Plowshares"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Tennessee","charges":"Federal sabotage of national defense premises (vacated 2015) and depredation of government property — July 28, 2012 Y-12 National Security Complex breach at Oak Ridge, Tennessee","arrest_date":"2012-07-28","incarceration_date":"2014-02-18","sentenced_date":"2014-02-18","release_date":"2015-05-16","sentence":"35 months federal prison; sabotage conviction vacated by 6th Circuit May 2015","convicted":"Yes — federal jury verdict, U.S. District Court for the Eastern District of Tennessee, May 2013"}]}' || true

php artisan prisoner:add '{"name":"Greg Boertje-Obed","first_name":"Greg","last_name":"Boertje-Obed","description":"Greg Boertje-Obed was a Catholic Worker peace activist, U.S. Army veteran (West Point graduate, paratrooper), and longtime Plowshares activist with multiple prior actions before the July 28, 2012 Transform Now Plowshares breach of the Y-12 National Security Complex at Oak Ridge, Tennessee. With Sister Megan Rice and Michael Walli he cut through three security fences and entered the U.S. governments principal high-enriched-uranium storage facility, where they hammered the building wall and poured blood. He was sentenced in 2014 to 62 months in federal prison; the Sixth Circuit Court of Appeals vacated the sabotage conviction in May 2015 and he was released on May 16, 2015.","state":"Minnesota","race":"White","gender":"Male","ideologies":["Anti-nuclear","Catholic Worker","Plowshares"],"affiliation":["Catholic Worker","Transform Now Plowshares","U.S. Army (West Point/paratrooper, former)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Tennessee","charges":"Federal sabotage of national defense premises (vacated 2015) and depredation of government property — July 28, 2012 Y-12 breach at Oak Ridge, Tennessee","arrest_date":"2012-07-28","incarceration_date":"2014-02-18","sentenced_date":"2014-02-18","release_date":"2015-05-16","sentence":"62 months federal prison; sabotage conviction vacated by 6th Circuit May 2015","convicted":"Yes — federal jury verdict, U.S. District Court for the Eastern District of Tennessee, May 2013"}]}' || true

php artisan prisoner:add '{"name":"Michael Walli","first_name":"Michael","last_name":"Walli","description":"Michael Walli was a Catholic Worker peace activist, U.S. Army Vietnam War veteran with two combat tours, and longtime Plowshares activist. On July 28, 2012, with Sister Megan Rice and Greg Boertje-Obed — Transform Now Plowshares — he cut through three security fences and entered the Y-12 National Security Complex at Oak Ridge, Tennessee, where they hammered the high-enriched-uranium storage building and poured blood. He was sentenced in 2014 to 62 months in federal prison; the Sixth Circuit Court of Appeals vacated the sabotage conviction in May 2015 and he was released on May 16, 2015.","state":"Washington DC","race":"White","gender":"Male","ideologies":["Anti-nuclear","Catholic Worker","Plowshares"],"affiliation":["Catholic Worker","Transform Now Plowshares","U.S. Army (Vietnam, former)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Tennessee","charges":"Federal sabotage of national defense premises (vacated 2015) and depredation of government property — July 28, 2012 Y-12 breach at Oak Ridge, Tennessee","arrest_date":"2012-07-28","incarceration_date":"2014-02-18","sentenced_date":"2014-02-18","release_date":"2015-05-16","sentence":"62 months federal prison; sabotage conviction vacated by 6th Circuit May 2015","convicted":"Yes — federal jury verdict, U.S. District Court for the Eastern District of Tennessee, May 2013"}]}' || true

# === Espionage Act whistleblowers ===

php artisan prisoner:add '{"name":"Daniel Hale","first_name":"Daniel","last_name":"Hale","description":"Daniel Hale is a former U.S. Air Force intelligence analyst and former contractor at the National Geospatial-Intelligence Agency. He was assigned to the U.S. drone program at Bagram Air Base in Afghanistan in 2012-2013, where his work in target identification gave him direct knowledge of how U.S. drone strikes designated and killed people who were not on any approved kill list. Beginning in 2014 he provided classified documents to journalist Jeremy Scahill, which formed the basis of The Intercepts 2015 Drone Papers — the most consequential public disclosure of the U.S. drone-warfare apparatus.\n\nHe was charged in May 2019 under the Espionage Act of 1917, pleaded guilty in March 2021, and was sentenced on July 27, 2021 by U.S. District Judge Liam OGrady in Alexandria, Virginia to 45 months in federal prison — the second-longest sentence ever imposed on a U.S. civilian whistleblower. He served at the federal Communications Management Unit at Marion, Illinois, and was released in July 2024.","state":"Virginia","race":"White","gender":"Male","birthdate":"1987-12-05","ideologies":["Anti-war","Whistleblower","First Amendment"],"affiliation":["U.S. Air Force (former)","National Geospatial-Intelligence Agency (former contractor)"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal Espionage Act of 1917 — disclosure of classified U.S. drone-warfare program documents to The Intercept (the Drone Papers)","arrest_date":"2019-05-09","incarceration_date":"2021-07-27","sentenced_date":"2021-07-27","release_date":"2024-07-15","sentence":"45 months federal prison","convicted":"Yes — guilty plea, U.S. District Court for the Eastern District of Virginia, March 2021"}]}' || true

php artisan prisoner:add '{"name":"Reality Winner","first_name":"Reality","middle_name":"Leigh","last_name":"Winner","description":"Reality Leigh Winner is a former U.S. Air Force linguist (Pashto) and a federal contractor at Pluribus International in Augusta, Georgia at the time of her June 2017 arrest. She had printed and mailed to The Intercept a classified National Security Agency report describing Russian military-intelligence cyber operations targeting U.S. voter-registration systems and election-software vendors in the months before the November 2016 U.S. presidential election. The Intercept published the report on June 5, 2017; she was arrested the same day.\n\nShe was charged under the Espionage Act of 1917. She pleaded guilty on June 26, 2018 in U.S. District Court for the Southern District of Georgia and was sentenced on August 23, 2018 to 63 months in federal prison — the longest federal sentence ever imposed at the time on a civilian whistleblower for leaks to the press. She was released to home confinement in June 2021 and to full liberty in November 2021.","state":"Georgia","race":"White","gender":"Female","birthdate":"1991-12-04","ideologies":["Whistleblower","First Amendment"],"affiliation":["U.S. Air Force (former)","Pluribus International (former contractor)"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (FMC Carswell)","institution_state":"Texas","charges":"Federal Espionage Act of 1917 — disclosure of NSA report on Russian cyber operations targeting 2016 U.S. election infrastructure to The Intercept","arrest_date":"2017-06-03","incarceration_date":"2018-08-23","sentenced_date":"2018-08-23","release_date":"2021-06-02","sentence":"63 months federal prison; released to home confinement June 2021, full liberty November 2021","convicted":"Yes — guilty plea, U.S. District Court for the Southern District of Georgia, June 26, 2018"}]}' || true

# === Cleveland 4 — April 30, 2012 FBI sting in Cuyahoga Valley ===

php artisan prisoner:add '{"name":"Douglas Wright","first_name":"Douglas","last_name":"Wright","description":"Douglas L. Wright was a Cleveland, Ohio Occupy Wall Street and anti-fracking organizer who, with four other young anarchists from the Cleveland Occupy encampment, was approached in fall 2011 by an FBI undercover informant named Shaquille Azir. Over the next six months Azir directed and financed a fictional plot to bomb the Brecksville-Northfield High Level Bridge over the Cuyahoga Valley National Park; the explosives Azir provided were inert. Wright and four others — Brandon Baxter, Connor Stevens, Joshua Stafford, and Anthony Hayne — were arrested on April 30, 2012 in what the FBI called a sting. Hayne broke from the four others and accepted a plea deal in exchange for testimony, which is why the four convicted at trial — Wright, Baxter, Stevens, Stafford — became known as the Cleveland 4.\n\nWright accepted a non-cooperating plea agreement in fall 2012 and was sentenced on November 20, 2012 to 11.5 years in federal prison — the longest of the Cleveland 4 sentences. He served the bulk of his sentence at the federal Communications Management Unit at Marion, Illinois.","state":"Ohio","race":"White","gender":"Male","ideologies":["Anarchism","Occupy"],"affiliation":["Occupy Cleveland"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Marion)","institution_state":"Illinois","charges":"Federal use of weapons of mass destruction and conspiracy to use explosives — April 30, 2012 FBI sting in the Cuyahoga Valley, Ohio","arrest_date":"2012-04-30","incarceration_date":"2012-11-20","sentenced_date":"2012-11-20","release_date":"2022-11-20","sentence":"11.5 years federal prison","convicted":"Yes — federal guilty plea, U.S. District Court for the Northern District of Ohio, fall 2012"}]}' || true

php artisan prisoner:add '{"name":"Brandon Baxter","first_name":"Brandon","middle_name":"L","last_name":"Baxter","description":"Brandon L. Baxter was a 20-year-old Occupy Cleveland organizer at the time of his April 30, 2012 arrest in the FBI sting against four young anarchists from the Cleveland Occupy encampment. Over six months, FBI undercover informant Shaquille Azir had financed and directed the fictional plot to bomb the Brecksville-Northfield High Level Bridge over the Cuyahoga Valley National Park. The explosives Azir provided were inert. Baxter accepted a non-cooperating plea agreement in fall 2012 and was sentenced on November 20, 2012 to 10 years in federal prison.","state":"Ohio","race":"White","gender":"Male","ideologies":["Anarchism","Occupy"],"affiliation":["Occupy Cleveland"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Ohio","charges":"Federal use of weapons of mass destruction and conspiracy to use explosives — April 30, 2012 FBI sting in the Cuyahoga Valley, Ohio","arrest_date":"2012-04-30","incarceration_date":"2012-11-20","sentenced_date":"2012-11-20","release_date":"2021-11-20","sentence":"10 years federal prison","convicted":"Yes — federal guilty plea, U.S. District Court for the Northern District of Ohio, fall 2012"}]}' || true

php artisan prisoner:add '{"name":"Connor Stevens","first_name":"Connor","middle_name":"C","last_name":"Stevens","description":"Connor C. Stevens was an Occupy Cleveland organizer arrested with three other young anarchists from the Cleveland Occupy encampment on April 30, 2012, in the FBI sting that ran for six months under undercover informant Shaquille Azir. The explosives Azir provided in the alleged plot to bomb the Brecksville-Northfield High Level Bridge were inert. Stevens accepted a non-cooperating plea agreement in fall 2012 and was sentenced on November 20, 2012 to 8 years in federal prison.","state":"Ohio","race":"White","gender":"Male","ideologies":["Anarchism","Occupy"],"affiliation":["Occupy Cleveland"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Ohio","charges":"Federal use of weapons of mass destruction and conspiracy to use explosives — April 30, 2012 FBI sting in the Cuyahoga Valley, Ohio","arrest_date":"2012-04-30","incarceration_date":"2012-11-20","sentenced_date":"2012-11-20","release_date":"2019-11-20","sentence":"8 years federal prison","convicted":"Yes — federal guilty plea, U.S. District Court for the Northern District of Ohio, fall 2012"}]}' || true

php artisan prisoner:add '{"name":"Joshua Stafford","first_name":"Joshua","last_name":"Stafford","aka":"Skelly","description":"Joshua \"Skelly\" Stafford was an Occupy Cleveland organizer with documented mental-health vulnerabilities arrested with three other young anarchists from the Cleveland Occupy encampment on April 30, 2012 in the FBI sting that ran for six months under undercover informant Shaquille Azir. Unlike his three Cleveland 4 co-defendants, he refused to plead and went to trial. He was found guilty on all counts in 2013 and sentenced on October 4, 2013 to 10 years in federal prison.","state":"Ohio","race":"White","gender":"Male","ideologies":["Anarchism","Occupy"],"affiliation":["Occupy Cleveland"],"era":"2010s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Ohio","charges":"Federal use of weapons of mass destruction and conspiracy to use explosives — April 30, 2012 FBI sting in the Cuyahoga Valley, Ohio","arrest_date":"2012-04-30","incarceration_date":"2013-10-04","sentenced_date":"2013-10-04","release_date":"2022-10-04","sentence":"10 years federal prison","convicted":"Yes — federal jury verdict (no plea), U.S. District Court for the Northern District of Ohio, 2013"}]}' || true

# === Iraq War resisters ===

php artisan prisoner:add '{"name":"Camilo Mejia","first_name":"Camilo","middle_name":"Ernesto","last_name":"Mejia","description":"Camilo Ernesto Mejía Castillo is a Nicaraguan-American who served nearly nine years in the U.S. Army, including a six-month combat tour in Iraq beginning in April 2003. After returning to the United States on a two-week home leave in October 2003, he refused to return to Iraq and went into hiding. On March 15, 2004 he turned himself in and applied for discharge as a conscientious objector, citing the killing of civilians and the abuse of detainees he had witnessed in Iraq. He was the first known Iraq War combat veteran to publicly refuse to redeploy.\n\nThe Army denied his conscientious-objector application. He was court-martialed at Fort Stewart, Georgia and on May 21, 2004 was convicted of desertion by a military jury and sentenced to one year in military prison and a bad-conduct discharge. He served his sentence at the Fort Sill military prison in Lawton, Oklahoma. After his release in 2005 he became one of the central public figures of the Iraq Veterans Against the War, serving as its national chair. His memoir Road from Ar Ramadi was published in 2007.","state":"Florida","race":"Hispanic","gender":"Male","birthdate":"1975-08-28","ideologies":["Anti-war","Conscientious objector"],"affiliation":["U.S. Army (former)","Iraq Veterans Against the War"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Fort Sill Military Prison","institution_city":"Lawton","institution_state":"Oklahoma","charges":"Military desertion — refusal to redeploy to Iraq after October 2003 home leave; Army denied his conscientious-objector application","arrest_date":"2004-03-15","incarceration_date":"2004-05-21","sentenced_date":"2004-05-21","release_date":"2005-02-15","sentence":"1 year military prison + bad-conduct discharge","convicted":"Yes — military court-martial conviction, May 21, 2004"}]}' || true

php artisan prisoner:add '{"name":"Stephen Funk","first_name":"Stephen","middle_name":"Eagle","last_name":"Funk","description":"Stephen Eagle Funk is a Filipino-American Marine Corps reservist (Lance Corporal, Landing Support Specialist) who, on February 9, 2003 — six weeks before the U.S. invasion of Iraq began — became the first U.S. military service member to publicly refuse deployment. He went absent without leave from his unit while preparing his application for conscientious-objector status, and at the same time came out publicly as a gay man. He turned himself in on April 1, 2003 after 47 days AWOL and read his statement of conscientious objection on the steps of the federal building in San Francisco.\n\nA military jury at Camp Lejeune, North Carolina acquitted him on September 6, 2003 of desertion but convicted him of unauthorized absence and sentenced him to six months military imprisonment, reduction in rank from E-3 to E-1, and a bad-conduct discharge. He served his sentence at the brig at Camp Lejeune.","state":"California","race":"Asian","gender":"Male","ideologies":["Anti-war","Conscientious objector","LGBTQ"],"affiliation":["U.S. Marine Corps (former)"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Marine Corps Brig, Camp Lejeune","institution_state":"North Carolina","charges":"Military unauthorized absence — 47 days AWOL preparing conscientious-objector application before Iraq invasion","arrest_date":"2003-04-01","incarceration_date":"2003-09-06","sentenced_date":"2003-09-06","release_date":"2004-03-06","sentence":"6 months military prison + bad-conduct discharge","convicted":"Yes — military court-martial conviction, September 6, 2003"}]}' || true

echo
echo "Round 10 (Y-12 Plowshares + whistleblowers + Cleveland 4 + Iraq War resisters) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
