#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round19_more_plowshares_gjb.sh
#
# Source clusters:
#   - Helen Woodson - longest-jailed U.S. anti-nuclear resister; 27 yrs
#     across multiple Plowshares actions and other actions
#   - Silo Pruning Hooks (Nov 12, 1984 Whiteman AFB Minuteman II silo;
#     Carl Kabat already in DB from round 8) - other co-defendants
#   - Sacred Earth and Space Plowshares II (Oct 6, 2002 Colorado N-8
#     Minuteman III ICBM silo) - three Dominican Sisters
#   - Mark Cook - George Jackson Brigade member; longest-incarcerated of
#     the brigadiers (24 yrs)
#   - Frank Cordaro - Iowa Catholic Worker founder; 5+ years in jail
#     across decades of anti-nuclear civil disobedience
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Helen Woodson ===

php artisan prisoner:add '{"name":"Helen Woodson","first_name":"Helen","middle_name":"Dery","last_name":"Woodson","description":"Helen Dery Woodson was a Catholic Worker peace activist from Madison, Wisconsin and the longest-jailed U.S. anti-nuclear resister of the late twentieth century. On November 12, 1984 she joined Father Carl Kabat, Father Paul Kabat, and Larry Cloud Morgan in the Silo Pruning Hooks action — the four entered the access compound of a Minuteman II missile silo near Knob Noster, Missouri (controlled by Whiteman Air Force Base), poured blood, and used a jackhammer on the concrete platform protecting the silo. She was sentenced to 18 years in federal prison.\n\nFollowing additional civil-disobedience actions during work-release periods between sentences — including a 1993 sabotage of a transformer at the federal prison camp at Pekin, Illinois, and a 1996 Bank of America armed robbery in which she returned the money to the bank in exchange for the right to read an anti-money statement — she accumulated a total of 27 years of federal prison time. She was finally released from federal prison in September 2011, age 68. She died on December 2, 2023, age 80. None of the people arrested for U.S. anti-nuclear civil disobedience has spent more time in prison than she did.","state":"Missouri","race":"White","gender":"Female","birthdate":"1943-01-31","death_date":"2023-12-02","ideologies":["Anti-nuclear","Catholic Worker","Plowshares","Pacifism"],"affiliation":["Catholic Worker","Silo Pruning Hooks"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (FCI Pekin and others)","institution_state":"Missouri","charges":"Federal sabotage and depredation of government property - November 12, 1984 Silo Pruning Hooks at Whiteman AFB Minuteman II silo; subsequent federal sabotage of FCI Pekin transformer (1993); 1996 Bank of America armed robbery action","arrest_date":"1984-11-12","incarceration_date":"1984-11-12","release_date":"2011-09-15","sentence":"18 years for Silo Pruning Hooks plus subsequent sentences; 27 years total federal prison time","convicted":"Yes - federal court convictions across multiple actions"}]}' || true

# === Silo Pruning Hooks co-defendants beyond Carl Kabat ===

php artisan prisoner:add '{"name":"Paul Kabat","first_name":"Paul","last_name":"Kabat","description":"Father Paul Kabat was an Oblate Catholic priest and the older brother of Plowshares activist Father Carl Kabat. On November 12, 1984 he joined his brother, Helen Woodson, and Larry Cloud Morgan in the Silo Pruning Hooks action at a Minuteman II missile silo near Knob Noster, Missouri. He was sentenced to 8 years in federal prison; he served until 1989. He died on June 22, 2007, age 72.","state":"Missouri","race":"White","gender":"Male","death_date":"2007-06-22","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Missionary Oblates of Mary Immaculate","Silo Pruning Hooks"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Missouri","charges":"Federal sabotage and depredation of government property - November 12, 1984 Silo Pruning Hooks at Whiteman AFB Minuteman II silo","arrest_date":"1984-11-12","incarceration_date":"1984-11-12","release_date":"1989-04-15","sentence":"8 years federal prison","convicted":"Yes - federal jury verdict, U.S. District Court for the Western District of Missouri, 1985"}]}' || true

php artisan prisoner:add '{"name":"Larry Cloud Morgan","first_name":"Larry","last_name":"Cloud Morgan","description":"Larry Cloud Morgan was an Anishinaabe Catholic peace activist from Minnesota. On November 12, 1984 he joined Carl Kabat, Paul Kabat, and Helen Woodson in the Silo Pruning Hooks action at a Minuteman II missile silo near Knob Noster, Missouri. He was sentenced to 8 years in federal prison; he served until 1989. He died on May 22, 1999.","state":"Missouri","race":"Native American","gender":"Male","death_date":"1999-05-22","ideologies":["Anti-nuclear","Catholic","Indigenous","Plowshares"],"affiliation":["Silo Pruning Hooks"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Missouri","charges":"Federal sabotage and depredation of government property - November 12, 1984 Silo Pruning Hooks at Whiteman AFB Minuteman II silo","arrest_date":"1984-11-12","incarceration_date":"1984-11-12","release_date":"1989-04-15","sentence":"8 years federal prison","convicted":"Yes - federal jury verdict, U.S. District Court for the Western District of Missouri, 1985"}]}' || true

# === Sacred Earth and Space Plowshares II — October 6, 2002 ===

php artisan prisoner:add '{"name":"Ardeth Platte","first_name":"Ardeth","last_name":"Platte","description":"Sister Ardeth Platte was a Dominican Sister of Grand Rapids, Michigan, and a Plowshares activist for more than three decades. On October 6, 2002 — six months before the U.S. invasion of Iraq — she, Sister Carol Gilbert, and Sister Jackie Hudson cut through the perimeter fence of Minuteman III missile silo N-8 in northeastern Colorado, climbed onto the silo cap, hammered on it, and poured human blood in the shape of a cross to remember victims of war. They named the action Sacred Earth and Space Plowshares II. They were tried in U.S. District Court in Denver in 2003. She was convicted of obstructing the national defense and damaging government property and sentenced to 41 months in federal prison. Her grandniece in The Handmaids Tale, the character Sister Mary Aquinas, was named for her. She died on September 30, 2020, age 84.","state":"Colorado","race":"White","gender":"Female","birthdate":"1936-04-10","death_date":"2020-09-30","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Dominican Sisters of Grand Rapids","Sacred Earth and Space Plowshares II","Jonah House"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Colorado","charges":"Federal obstruction of the national defense and damage to government property - October 6, 2002 Sacred Earth and Space Plowshares II action at the N-8 Minuteman III missile silo in northeastern Colorado","arrest_date":"2002-10-06","incarceration_date":"2003-07-25","sentenced_date":"2003-07-25","release_date":"2007-01-25","sentence":"41 months federal prison","convicted":"Yes - federal jury verdict, U.S. District Court for the District of Colorado, April 2003"}]}' || true

php artisan prisoner:add '{"name":"Carol Gilbert","first_name":"Carol","last_name":"Gilbert","description":"Sister Carol Gilbert is a Dominican Sister of Grand Rapids, Michigan, and a longtime Plowshares activist. On October 6, 2002 she joined Sisters Ardeth Platte and Jackie Hudson in the Sacred Earth and Space Plowshares II action at Minuteman III missile silo N-8 in northeastern Colorado. She was convicted in U.S. District Court in Denver in April 2003 of obstructing the national defense and damaging government property and sentenced to 33 months in federal prison.","state":"Colorado","race":"White","gender":"Female","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Dominican Sisters of Grand Rapids","Sacred Earth and Space Plowshares II","Jonah House"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Colorado","charges":"Federal obstruction of the national defense and damage to government property - October 6, 2002 Sacred Earth and Space Plowshares II action at the N-8 Minuteman III missile silo in northeastern Colorado","arrest_date":"2002-10-06","incarceration_date":"2003-07-25","sentenced_date":"2003-07-25","release_date":"2006-04-25","sentence":"33 months federal prison","convicted":"Yes - federal jury verdict, U.S. District Court for the District of Colorado, April 2003"}]}' || true

php artisan prisoner:add '{"name":"Jackie Hudson","first_name":"Jackie","last_name":"Hudson","description":"Sister Jackie Hudson was a Dominican Sister of Grand Rapids, Michigan, and a longtime Plowshares activist. On October 6, 2002 she joined Sisters Ardeth Platte and Carol Gilbert in the Sacred Earth and Space Plowshares II action at Minuteman III missile silo N-8 in northeastern Colorado. She was convicted in U.S. District Court in Denver in April 2003 of obstructing the national defense and damaging government property and sentenced to 30 months in federal prison. She died on August 3, 2011.","state":"Colorado","race":"White","gender":"Female","death_date":"2011-08-03","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Dominican Sisters of Grand Rapids","Sacred Earth and Space Plowshares II","Ground Zero Center for Nonviolent Action"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","institution_state":"Colorado","charges":"Federal obstruction of the national defense and damage to government property - October 6, 2002 Sacred Earth and Space Plowshares II action at the N-8 Minuteman III missile silo in northeastern Colorado","arrest_date":"2002-10-06","incarceration_date":"2003-07-25","sentenced_date":"2003-07-25","release_date":"2005-10-25","sentence":"30 months federal prison","convicted":"Yes - federal jury verdict, U.S. District Court for the District of Colorado, April 2003"}]}' || true

# === Mark Cook — George Jackson Brigade ===

php artisan prisoner:add '{"name":"Mark Cook","first_name":"Mark","last_name":"Cook","description":"Mark Cook was the only African-American member of the George Jackson Brigade and the last to join the Pacific Northwest militant prisoner-solidarity formation. He participated in the January 23, 1976 Tukwila bank robbery that killed Brigade member Bruce Seidel and led to the arrest of Ed Mead and John Sherman; he avoided arrest at the scene. Days later, he carried out the armed liberation of John Sherman from Harborview Medical Center in Seattle, where Sherman was being held under guard for medical treatment of her bank-robbery wounds; a King County deputy was wounded in the operation. Cook was arrested shortly afterward and convicted in Washington state court. He served 24 years in the Washington State Penitentiary at Walla Walla — the longest of any of the Brigades members.\n\nInside, he organized a chapter of the Black Panther Party at Walla Walla, founded the PIVOT post-release re-entry program, and organized the long-running CONvention prison-organizing seminar. He was released in 2000.","state":"Washington","race":"Black","gender":"Male","ideologies":["Black Liberation","Anarchism","Prison abolition"],"affiliation":["George Jackson Brigade","Black Panther Party","PIVOT","Walla Walla CONvention"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Washington State Penitentiary","institution_city":"Walla Walla","institution_state":"Washington","charges":"Washington state armed assault on a King County deputy and prison liberation - 1976 armed liberation of John Sherman from Harborview Medical Center","arrest_date":"1976-03-10","incarceration_date":"1976-03-10","release_date":"2000-08-15","sentence":"24 years Washington state prison","convicted":"Yes - Washington state conviction, 1976"}]}' || true

# === Frank Cordaro ===

php artisan prisoner:add '{"name":"Frank Cordaro","first_name":"Frank","last_name":"Cordaro","description":"Frank Cordaro is a Catholic peace activist, former Roman Catholic priest (ordained 1985, left the priesthood in 2003 over the celibacy requirement), and the principal co-founder of the Des Moines, Iowa Catholic Worker community in 1976. He has been arrested more than seventy times in nonviolent civil-disobedience actions against U.S. nuclear weapons, the U.S. Strategic Command at Offutt Air Force Base, U.S. Air Force drone operations, and the U.S. School of the Americas. Across some four decades of arrests he has accumulated more than five years total in federal jails and prisons across at least eight separate six-month federal sentences.","state":"Iowa","race":"White","gender":"Male","birthdate":"1951-09-21","ideologies":["Anti-nuclear","Anti-war","Catholic Worker","Pacifism"],"affiliation":["Des Moines Catholic Worker","Catholic Worker"],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied across multiple sentences)","institution_state":"Nebraska","charges":"Federal trespassing on military bases - more than 70 arrests across four decades, primarily at Strategic Command headquarters at Offutt Air Force Base","arrest_date":"1980-01-01","incarceration_date":"1994-05-01","release_date":"2015-12-15","sentence":"More than 5 years total federal time across at least 8 six-month sentences","convicted":"Yes - federal court convictions across multiple actions"}]}' || true

echo
echo "Round 19 (Helen Woodson + Silo Pruning Hooks + Sacred Earth and Space + Mark Cook + Frank Cordaro) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
