#!/usr/bin/env bash
# Run on the production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_more_prisoner_gaps.sh
#
# Second round of prisoner records for dashboard people who were missing from the
# prisoner database:
#   - Tyler Robinson and Luigi Mangione: previously left out as editorial calls
#     (accused in high-profile killings); added here at the site owner's request,
#     written strictly factually with a presumption of innocence and no advocacy.
#   - Mario Guevara and Jay Carey: appeared only inside Article commands, not as
#     prisoner records.
#
# prisoner:add refuses duplicates by name, so this is safe to re-run and will skip
# anyone already present. Do NOT use `set -e` (a duplicate returns non-zero).

php artisan prisoner:add '{"name":"Tyler Robinson","first_name":"Tyler","last_name":"Robinson","gender":"Male","state":"Utah","era":"2020s","in_custody":true,"released":false,"description":"Tyler Robinson, 22, of Washington, Utah, is the man accused of fatally shooting conservative activist Charlie Kirk at Utah Valley University in Orem on September 10, 2025. He was charged on September 16, 2025 with aggravated murder, felony discharge of a firearm, obstruction of justice, and witness tampering; Utah prosecutors are seeking the death penalty, alleging a politically motivated killing. He remains in custody and is presumed innocent unless proven guilty.","cases":[{"institution_name":"Utah County Jail","institution_city":"Spanish Fork","institution_state":"Utah","charges":"Aggravated murder; felony discharge of a firearm; two counts obstruction of justice; two counts witness tampering; violence in the presence of a child","arrest_date":"2025-09-12","convicted":"Pending (death penalty sought)","incarceration_date":"2025-09-12"}]}'

php artisan prisoner:add '{"name":"Luigi Mangione","first_name":"Luigi","last_name":"Mangione","gender":"Male","state":"New York","era":"2020s","in_custody":true,"released":false,"description":"Luigi Mangione, 26 at the time of his arrest and originally of Maryland, is accused of fatally shooting UnitedHealthcare CEO Brian Thompson in Manhattan on December 4, 2024. He was arrested on December 9, 2024 at a McDonald in Altoona, Pennsylvania and faces New York state, federal, and Pennsylvania charges. A New York judge dismissed the state terrorism-related murder counts in September 2025, and a federal judge dismissed the death-eligible federal counts in January 2026. He remains in federal custody and is presumed innocent unless proven guilty.","cases":[{"institution_name":"Metropolitan Detention Center Brooklyn","institution_city":"Brooklyn","institution_state":"New York","charges":"New York second-degree murder (state terrorism counts dismissed Sept 2025); federal stalking and firearms counts (death-eligible counts dismissed Jan 2026)","arrest_date":"2024-12-09","convicted":"Pending","incarceration_date":"2024-12-09"}]}'

php artisan prisoner:add '{"name":"Mario Guevara","first_name":"Mario","last_name":"Guevara","gender":"Male","state":"Georgia","era":"2020s","ideologies":["Press Freedom","Immigrant Rights"],"in_custody":false,"released":true,"description":"Mario Guevara, a Salvadoran journalist who covered immigration for a large Spanish-language audience in the Atlanta area, was arrested on June 14, 2025 while livestreaming a No Kings protest in DeKalb County, Georgia. Prosecutors dropped the misdemeanor charges within days, but ICE kept him in immigration detention and deported him to El Salvador on October 3, 2025, in a case press-freedom groups called an alarming attack on journalism.","cases":[{"institution_name":"ICE detention","institution_state":"Georgia","charges":"Obstruction; unlawful assembly; improperly entering a roadway (charges dropped); held in ICE custody and deported","arrest_date":"2025-06-14","convicted":"No (charges dropped)","sentence":"Charges dropped; deported to El Salvador Oct 3, 2025"}]}'

php artisan prisoner:add '{"name":"Jay Carey","first_name":"Jay","last_name":"Carey","gender":"Male","state":"District of Columbia","era":"2020s","ideologies":["Free Speech"],"in_custody":false,"released":true,"description":"Jay Carey, a U.S. Army veteran from Arden, North Carolina who served in Iraq and Afghanistan, was arrested on August 25, 2025 in Lafayette Park near the White House after burning a U.S. flag in protest on the day President Trump signed an executive order directing prosecution of flag burning. He was charged with two fire-related misdemeanors (not flag burning); the Justice Department moved to drop the charges in March 2026.","cases":[{"institution_name":"U.S. Park Police","institution_state":"District of Columbia","charges":"Igniting a fire in an undesignated area; lighting a fire causing damage to property or park resources","arrest_date":"2025-08-25","convicted":"No (charges dropped)","sentence":"DOJ moved to dismiss March 2026"}]}'
