#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round21_attica_backiel.sh
#
# Source clusters:
#   - Attica prison rebellion (Sept 9-13 1971; 43 dead in Rockefeller s
#     retaking) - Frank "Big Black" Smith was the central organizer; Sam
#     Melville already in DB from round 20 (killed in retaking)
#   - Attorney-client privilege grand-jury contempt (Linda Backiel 1990-91)
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === Frank "Big Black" Smith ===

php artisan prisoner:add '{"name":"Frank Big Black Smith","first_name":"Frank","last_name":"Smith","aka":"Big Black","description":"Frank Big Black Smith was a 300-pound African-American prisoner at Attica Correctional Facility in upstate New York who became the principal internal security organizer of the September 9-13, 1971 Attica prison rebellion — still the bloodiest prison uprising in U.S. history. With 1,281 of Atticas approximately 2,200 prisoners, he took control of the prison and held 42 prison staff as hostages over four days, demanding political and human-rights reforms. After negotiations broke down, New York State Police retook the prison on Governor Nelson Rockefellers orders on September 13, 1971; 43 people died — 10 prison staff and 33 prisoners — almost all by state-police gunfire.\n\nIn the immediate aftermath he was singled out for retaliatory torture by guards: he was stripped naked, forced to lie on a table for hours with a football placed under his chin and was told that if he dropped the football he would be killed. He was burned with cigarettes and beaten. He was held in solitary confinement for six months. He was released on parole in 1973 after 8.5 years of a 10-15 year sentence for an unrelated New York City dice-game robbery. After his release he became a longtime substance-abuse counselor and the lead plaintiff in the 26-year class-action civil-rights lawsuit by Attica survivors that eventually settled for $12 million in 2000. He died in 2004, age 70.","state":"New York","race":"Black","gender":"Male","birthdate":"1933-12-08","death_date":"2004-07-25","ideologies":["Black Liberation","Prison abolition"],"affiliation":["Attica Brothers"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Attica Correctional Facility","institution_city":"Attica","institution_state":"New York","charges":"Underlying NYC dice-game robbery (10-15 yrs); central organizer of the September 9-13, 1971 Attica rebellion; tortured by guards in the aftermath","arrest_date":"1965-04-15","incarceration_date":"1965-04-15","release_date":"1973-10-15","sentence":"10-15 years; paroled 1973 after 8.5 years","convicted":"Yes - New York state robbery conviction"}]}' || true

# === Linda Backiel ===

php artisan prisoner:add '{"name":"Linda Backiel","first_name":"Linda","last_name":"Backiel","description":"Linda Backiel was a Philadelphia civil-rights and movement-defense attorney whose clients included Puerto Rican independentistas, the Resistance Conspiracy defendants, the May 19th Communist Organization, and Elizabeth Ann Duke (the M19CO defendant who jumped bail in October 1985 while awaiting trial on weapons-and-explosives charges and lived underground for the rest of her life). After Duke jumped bail, federal prosecutors subpoenaed Backiel to testify before a grand jury about her last conversation with Duke. She refused on attorney-client privilege grounds and was held in civil contempt by U.S. District Judge Marvin Katz of the Eastern District of Pennsylvania.\n\nShe served the first six months of 1991 at the Bucks County Prison. The Third Circuit ultimately vacated the contempt adjudication on procedural grounds in 1990 (the district court had erroneously denied her a public contempt hearing), but the time had already been served. She subsequently relocated to Puerto Rico, where she has practiced as a movement-defense attorney since.","state":"Pennsylvania","race":"White","gender":"Female","ideologies":["Attorney-client privilege","Civil rights law","First Amendment"],"affiliation":["National Lawyers Guild"],"era":"1990s","in_custody":false,"released":true,"cases":[{"institution_name":"Bucks County Prison","institution_city":"Doylestown","institution_state":"Pennsylvania","charges":"Federal civil contempt of grand jury - refusing to testify about her last conversation with M19CO client Elizabeth Ann Duke after Duke jumped bail in October 1985","arrest_date":"1990-12-01","incarceration_date":"1991-01-01","release_date":"1991-06-30","sentence":"6 months civil contempt; contempt adjudication vacated by 3rd Circuit on procedural grounds","convicted":"Civil contempt only; vacated"}]}' || true

# === Elizabeth Duke ===

php artisan prisoner:add '{"name":"Elizabeth Ann Duke","first_name":"Elizabeth","middle_name":"Ann","last_name":"Duke","description":"Elizabeth Ann Duke was a member of the May 19th Communist Organization who in 1985 was indicted in Doylestown, Pennsylvania for storing explosives and weapons. She was originally one of the six Resistance Conspiracy Case defendants but was severed from that case. While awaiting trial in October 1985 she jumped bail and went underground; she was a fugitive for the next 24 years. The U.S. Marshals Service formally dropped pursuit of her in October 2009. Her whereabouts were never publicly determined; she is presumed to have died in exile under an assumed identity in the United States or abroad. The federal grand-jury subpoena of attorney Linda Backiel about her departure produced one of the foundational federal attorney-client-privilege contempt cases of the 1990s.","state":"Pennsylvania","race":"White","gender":"Female","ideologies":["Anti-imperialist","Communist","Anti-racist"],"affiliation":["May 19th Communist Organization"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"(jumped bail October 1985; never recaptured)","institution_state":"Pennsylvania","charges":"Federal weapons and explosives possession (Doylestown PA) and Resistance Conspiracy Case - jumped bail October 1985","arrest_date":"1985-05-12","incarceration_date":"1985-05-12","in_exile_since":"1985-10-15","sentence":"Held in pretrial detention May-October 1985; jumped bail and lived underground for the next 24 years; warrant dropped 2009","convicted":"No - case dismissed after fugitive status"}]}' || true

echo
echo "Round 21 (Attica + Linda Backiel + Elizabeth Duke) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
