#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_palestine_solidarity_extra.sh
#
# Additional Palestine-solidarity political prisoners not yet in the DB.
# Casey Goonan, Alireza Doroudi, Leqaa Kordia, and the Holy Land Foundation
# Five are already in the database from earlier rounds.
#
# This script adds the four most prominent post-October-7 2025 ICE-detention
# campus cases plus Sami Al-Arian, the central pre-9/11/post-9/11 academic
# Palestine-solidarity prosecution.
#
# Each php artisan call is wrapped in `|| true` so a duplicate-name failure
# does not halt the script.
set -e

# === Mahmoud Khalil — Columbia (March 2025) ===

php artisan prisoner:add '{"name":"Mahmoud Khalil","first_name":"Mahmoud","last_name":"Khalil","description":"Mahmoud Khalil is a Palestinian-Syrian Columbia University graduate student in international affairs, a green-card holder, and one of the principal organizers of the 2024 Columbia pro-Palestine protests against Israels war in Gaza. On the night of March 8, 2025, Department of Homeland Security agents without a warrant entered his Columbia residential apartment building and detained him in front of his pregnant wife, Noor Abdalla, and transported him to the LaSalle ICE Processing Center in Jena, Louisiana the next day.\n\nHe was held under a determination by Secretary of State Marco Rubio, citing the rarely-invoked 8 USC 1227(a)(4)(C) provision, that his presence or activities would compromise a compelling U.S. foreign policy interest. About a week into his detention the government added a fraud-on-the-green-card-application charge. He was held in Jena for over three months — through the birth of his son — until U.S. District Judge Michael Farbiarz of the District of New Jersey ordered his release on bail on June 20, 2025, ruling that his continued detention was highly unusual and that he posed no threat or flight risk. Removal proceedings against him remained ongoing after release. His detention is the leading test case of the Trump administrations 2025 effort to deport non-citizen pro-Palestine campus organizers.","state":"New York","race":"Arab","gender":"Male","ideologies":["Palestine solidarity","Anti-war","First Amendment"],"affiliation":["Columbia University","Columbia University Apartheid Divest"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"LaSalle ICE Processing Center","institution_city":"Jena","institution_state":"Louisiana","charges":"INA 8 USC 1227(a)(4)(C) - U.S. Secretary of State foreign-policy designation; subsequent green-card-application fraud charge","arrest_date":"2025-03-08","incarceration_date":"2025-03-08","release_date":"2025-06-20","sentence":"Held in immigration detention 104 days; released on bail by federal court order, removal proceedings continuing","convicted":"No - civil immigration detention, no criminal conviction"}]}' || true

# === Rumeysa Ozturk — Tufts (March 2025) ===

php artisan prisoner:add '{"name":"Rumeysa Ozturk","first_name":"Rumeysa","last_name":"Ozturk","description":"Rumeysa Ozturk is a Turkish-born child-development PhD student at Tufts University and a former Fulbright scholar. The previous March, she had co-authored an op-ed in the Tufts Daily student newspaper urging the university to listen to undergraduate-government resolutions in support of Palestinian rights. On the evening of March 25, 2025 — as she left her Somerville, Massachusetts home to break the Ramadan fast with friends — six masked plainclothes ICE officers arrested her on the sidewalk. ICE then transported her south through several intermediate facilities to the South Louisiana ICE Processing Center in Basile, Louisiana. The basis for the detention was the State Departments determination that she was deportable; the only documented activity cited by the government was the op-ed.\n\nU.S. District Judge William Sessions III in Vermont ordered her released on May 9, 2025 after 45 days in detention, ruling that the detention cannot stand. She was released on bail. She received her PhD from Tufts in February 2026 and returned to Turkey on her own timeline in April 2026; an immigration judge subsequently terminated removal proceedings.","state":"Massachusetts","race":"White","gender":"Female","ideologies":["Palestine solidarity","First Amendment"],"affiliation":["Tufts University","Tufts Daily (op-ed contributor)"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"South Louisiana ICE Processing Center","institution_city":"Basile","institution_state":"Louisiana","charges":"INA 8 USC 1227(a)(4)(C) - U.S. Secretary of State foreign-policy designation, based on a March 2024 co-authored op-ed in the Tufts Daily","arrest_date":"2025-03-25","incarceration_date":"2025-03-25","release_date":"2025-05-09","sentence":"Held in immigration detention 45 days; released on bail by federal court order; removal proceedings later terminated","convicted":"No - civil immigration detention, no criminal conviction"}]}' || true

# === Mohsen Mahdawi — Columbia (April 2025) ===

php artisan prisoner:add '{"name":"Mohsen Mahdawi","first_name":"Mohsen","last_name":"Mahdawi","description":"Mohsen Mahdawi is a Palestinian-American Columbia University philosophy student, longtime Vermont resident, green-card holder, and one of the principal organizers of the 2024 Columbia pro-Palestine protests. On April 14, 2025 he reported to the U.S. Citizenship and Immigration Services office in Colchester, Vermont for his scheduled citizenship interview. After the interview, masked plainclothes ICE officers handcuffed him and put him in an unmarked vehicle. He was held at the Northwest State Correctional Facility in Vermont.\n\nU.S. District Judge Geoffrey W. Crawford ordered his release on April 30, 2025 — sixteen days after his arrest — writing that the two weeks of detention so far demonstrate great harm to a person who has been charged with no crime. He was released to home confinement in Vermont, with permission to travel to Columbia for school and to attorney meetings. Removal proceedings continuing. His detention at a citizenship interview was widely cited as one of the most aggressive U.S. attempts to use the immigration system as retaliation for protected political speech.","state":"Vermont","race":"Arab","gender":"Male","ideologies":["Palestine solidarity","First Amendment"],"affiliation":["Columbia University","Columbia University Apartheid Divest"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Northwest State Correctional Facility (ICE hold)","institution_city":"Swanton","institution_state":"Vermont","charges":"INA 8 USC 1227(a)(4)(C) - U.S. Secretary of State foreign-policy designation","arrest_date":"2025-04-14","incarceration_date":"2025-04-14","release_date":"2025-04-30","sentence":"Held in immigration detention 16 days; released by federal court order, removal proceedings continuing","convicted":"No - civil immigration detention, no criminal conviction"}]}' || true

# === Badar Khan Suri — Georgetown (March 2025) ===

php artisan prisoner:add '{"name":"Badar Khan Suri","first_name":"Badar","middle_name":"Khan","last_name":"Suri","description":"Dr. Badar Khan Suri is an Indian-national postdoctoral researcher at the Alwaleed Bin Talal Center for Muslim-Christian Understanding at Georgetown Universitys School of Foreign Service, where his research focused on peace and conflict resolution. On March 17, 2025 ICE agents arrested him near his northern-Virginia home as he walked toward his apartment. Secretary of State Marco Rubio had determined on March 15 that Suris activities and presence in the U.S. rendered him deportable under the Immigration and Nationality Act, citing his social-media posts about the war in Gaza. He was transported to a Texas immigration-detention facility.\n\nHis wife, Mapheze Saleh, a Palestinian American, is the daughter of Ahmed Yousef, a former adviser to slain Hamas political leader Ismail Haniyeh; the government cited that family connection alongside Suris own social-media posts. Federal Judge Patricia Tolliver Giles in the Eastern District of Virginia ordered his release on May 14, 2025 after about 58 days, ruling that the government had presented no evidence to refute his claim that he was being punished for protected speech. He was released to Virginia and returned to his work; removal proceedings continued.","state":"Virginia","race":"Asian","gender":"Male","ideologies":["Palestine solidarity","First Amendment","Peace studies"],"affiliation":["Georgetown University","Alwaleed Bin Talal Center for Muslim-Christian Understanding"],"era":"2020s","in_custody":false,"released":true,"cases":[{"institution_name":"Prairieland Detention Facility","institution_city":"Alvarado","institution_state":"Texas","charges":"INA 8 USC 1227(a)(4)(C) - U.S. Secretary of State foreign-policy designation","arrest_date":"2025-03-17","incarceration_date":"2025-03-17","release_date":"2025-05-14","sentence":"Held in immigration detention 58 days; released by federal court order, removal proceedings continuing","convicted":"No - civil immigration detention, no criminal conviction"}]}' || true

# === Sami Al-Arian — University of South Florida ===

php artisan prisoner:add '{"name":"Sami Al-Arian","first_name":"Sami","last_name":"Al-Arian","description":"Dr. Sami Al-Arian was a Kuwaiti-born Palestinian computer-engineering professor at the University of South Florida and one of the most prominent Palestinian-American academic and civil-rights organizers of the 1990s and 2000s. He was arrested on February 20, 2003 along with seven co-defendants by federal agents in Tampa and charged in a 50-count indictment under the post-9/11 Patriot Act with conspiracy to provide material support to Palestinian Islamic Jihad, a U.S. designated foreign terrorist organization, through his work with the World and Islam Studies Enterprise think tank.\n\nA five-month federal trial in Tampa in 2005 ended on December 6, 2005 with the jury acquitting him on 8 counts and deadlocking on the remaining 9. Rather than face retrial — and after his colleague Sameeh Hammoudeh and the WISE think tank were acquitted on all counts — he signed a plea agreement on February 28, 2006 in which he pleaded guilty to one count of conspiring to contribute services to Palestinian Islamic Jihad and accepted deportation. On May 1, 2006 U.S. District Judge James S. Moody sentenced him to 57 months in federal prison.\n\nAfter completing the federal sentence in 2008 he was placed in immigration detention. He was repeatedly subpoenaed before federal grand juries in Virginia and held on civil contempt charges for refusing to testify; he spent additional years in immigration detention and house arrest before federal prosecutors dropped the case on June 27, 2014. He was deported to Turkey on February 4, 2015 — the longest-detained academic Palestine-solidarity figure in post-9/11 U.S. history.","state":"Florida","race":"Arab","gender":"Male","birthdate":"1958-01-14","ideologies":["Palestine solidarity","Civil rights","Academic freedom"],"affiliation":["University of South Florida","World and Islam Studies Enterprise","National Coalition to Protect Political Freedom"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Coleman, FL and others); ICE detention","institution_state":"Florida","charges":"Federal conspiracy to provide material support to Palestinian Islamic Jihad (Patriot Act / Antiterrorism and Effective Death Penalty Act of 1996)","arrest_date":"2003-02-20","incarceration_date":"2003-02-20","sentenced_date":"2006-05-01","release_date":"2015-02-04","sentence":"57 months federal prison + ~5 years subsequent immigration detention and civil contempt + house arrest; total ~12 years confinement; case dismissed June 27, 2014; deported to Turkey February 4, 2015","convicted":"Partial - 8 counts acquitted Dec 6, 2005, 9 hung; February 28, 2006 plea to one count of conspiring to contribute services to PIJ"}]}' || true

echo
echo "Palestine-solidarity additions complete."
