#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round17_sq6_gjb_sterling.sh
#
# Source clusters:
#   - San Quentin Six (Aug 21 1971 escape attempt and killing of George
#     Jackson; six prisoners charged - Drumgo already in DB from round 6)
#   - George Jackson Brigade (Seattle, 1975-78 - militant solidarity
#     formation including former and active prisoners; Jan 23 1976
#     Tukwila bank robbery + Bruce Seidel killed)
#   - Sterling Hall bombing (Aug 24 1970 UW-Madison - the New Years
#     Gang ammonium-nitrate truck bomb against the Army Mathematics
#     Research Center; researcher Robert Fassnacht killed)
#
# All adds wrapped in `|| true` so duplicates do not halt the script.

# === San Quentin Six ===

php artisan prisoner:add '{"name":"Hugo Pinell","first_name":"Hugo","last_name":"Pinell","aka":"Yogi Bear","description":"Hugo Lyon Antonio Pinell, known to fellow prisoners as Yogi Bear, was a Nicaraguan-born former Marine and California state prisoner whose 1965 conviction for armed rape brought him into the California state prison system at age 19. Inside he was politicized through George Jackson and the Black Guerrilla Family. He was one of the San Quentin Six prosecuted for the events of August 21, 1971 — the day George Jackson was killed by guards at San Quentin in an alleged escape attempt during which two other prisoners and three guards also died. He was convicted of cutting the throats of two guards (both survived). He served 46 years almost entirely in solitary confinement at San Quentin and Pelican Bay; he was the longest-held continuous solitary-confinement prisoner in California history at the time of his death. He was finally released to general population at New Folsom in 2014 after the 2011-13 California Pelican Bay hunger strikes; he was killed there on August 12, 2015 by Aryan Brotherhood inmates, three days after his transfer from segregation. The Jericho Movement listed him among its current political prisoners.","state":"California","race":"Hispanic","gender":"Male","birthdate":"1944-12-10","death_date":"2015-08-12","ideologies":["Black Liberation","Prison abolition"],"affiliation":["Black Guerrilla Family","San Quentin Six"],"era":"1970s","in_custody":false,"released":false,"cases":[{"institution_name":"California Department of Corrections (San Quentin, Pelican Bay, New Folsom)","institution_state":"California","charges":"Underlying 1965 rape conviction; San Quentin Six trial for August 21, 1971 events at San Quentin","arrest_date":"1971-08-21","incarceration_date":"1971-08-21","death_in_custody_date":"2015-08-12","sentence":"Life; 46 years in California state prison, almost all in solitary confinement; killed at New Folsom Aug 12, 2015","convicted":"Yes - California state convictions including 1976 San Quentin Six trial"}]}' || true

php artisan prisoner:add '{"name":"Johnny Spain","first_name":"Larry","middle_name":"Michael","last_name":"Spain","aka":"Johnny Spain","description":"Larry Michael Spain, known as Johnny Spain, was the only one of the San Quentin Six convicted of murder for the events of August 21, 1971. Born to a white mother and Black father in 1949 in Mississippi, raised in California after his mother sent him north to escape rural anti-Black violence, he was sentenced to life in 1967 at age 17 for murder during a robbery. Inside he became close to George Jackson and a member of the Black Guerrilla Family. He was convicted in 1976 of two counts of murder of guards Frank DeLeon and Jere Graham at San Quentin during the August 21, 1971 incident. The conviction was overturned by the Ninth Circuit in 1985 on the grounds that the trial judge had unconstitutionally ordered him chained to his courtroom seat. The state declined to retry. He was paroled in 1988 and lived in California until his death on March 6, 2008.","state":"California","race":"Black","gender":"Male","birthdate":"1949-12-19","death_date":"2008-03-06","ideologies":["Black Liberation","Prison abolition"],"affiliation":["Black Guerrilla Family","San Quentin Six"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"Underlying 1967 California state murder conviction (life); 1976 San Quentin Six conviction of two counts of murder of guards Frank DeLeon and Jere Graham (overturned 9th Cir 1985)","arrest_date":"1967-04-01","incarceration_date":"1967-04-01","release_date":"1988-03-15","sentence":"Life; San Quentin Six conviction overturned 1985; paroled 1988","convicted":"Yes - 1976 California state conviction (overturned 1985)"}]}' || true

php artisan prisoner:add '{"name":"David Johnson","first_name":"David","last_name":"Johnson","description":"David Johnson was one of the San Quentin Six prosecuted for the events of August 21, 1971 at San Quentin. He was acquitted of murder but convicted of assault on correctional officers and sentenced to additional time on top of his prior California state sentence. He served his sentence and was released.","state":"California","race":"Black","gender":"Male","ideologies":["Black Liberation","Prison abolition"],"affiliation":["San Quentin Six"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections","institution_state":"California","charges":"San Quentin Six trial - acquitted of murder, convicted of assault on correctional officers","arrest_date":"1971-08-21","incarceration_date":"1971-08-21","sentence":"Conviction added to prior state sentence","convicted":"Partial - acquitted of murder, convicted of assault on correctional officers"}]}' || true

php artisan prisoner:add '{"name":"Willie Tate","first_name":"Willie","last_name":"Tate","description":"Willie Tate was one of the San Quentin Six prosecuted for the events of August 21, 1971 at San Quentin. He was acquitted on all counts at the 1976 trial. The Jericho Movement lists him among its ancestor political prisoners.","state":"California","race":"Black","gender":"Male","ideologies":["Black Liberation","Prison abolition"],"affiliation":["San Quentin Six"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections (pretrial detention only on SQ6 charges)","institution_state":"California","charges":"San Quentin Six trial (1976) - acquitted on all counts","arrest_date":"1971-08-21","incarceration_date":"1971-08-21","release_date":"1976-08-12","sentence":"Held in pretrial detention; acquitted at 1976 trial","convicted":"No - acquitted on all counts at the 1976 San Quentin Six trial"}]}' || true

php artisan prisoner:add '{"name":"Luis Talamantez","first_name":"Luis","last_name":"Talamantez","description":"Luis Bato Talamantez was one of the San Quentin Six prosecuted for the events of August 21, 1971 at San Quentin. He was acquitted on all counts at the 1976 trial. After his release he became a longtime California prison-abolition organizer and a co-founder of the All of Us or None network of formerly incarcerated organizers.","state":"California","race":"Hispanic","gender":"Male","ideologies":["Prison abolition"],"affiliation":["San Quentin Six","All of Us or None"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"California Department of Corrections (pretrial detention on SQ6 charges)","institution_state":"California","charges":"San Quentin Six trial (1976) - acquitted on all counts","arrest_date":"1971-08-21","incarceration_date":"1971-08-21","release_date":"1976-08-12","sentence":"Held in pretrial detention; acquitted at 1976 trial","convicted":"No - acquitted on all counts at the 1976 San Quentin Six trial"}]}' || true

# === George Jackson Brigade — Seattle, 1975-1978 ===

php artisan prisoner:add '{"name":"Ed Mead","first_name":"Ed","last_name":"Mead","description":"Ed Mead was the principal theorist of the George Jackson Brigade, a Seattle-based militant prison-solidarity formation that conducted a series of bombings of state and corporate targets and bank expropriations in the Pacific Northwest from 1975 to 1978. He was arrested on January 23, 1976, after an attempted bank robbery at the Pacific National Bank in Tukwila, Washington in which Brigade member Bruce Seidel was killed and Mead was wounded. He was convicted of attempted bank robbery and conspiracy and sentenced to 30 years at the Walla Walla State Penitentiary in Washington.\n\nInside, he founded Men Against Sexism, the prisoners gay-and-anti-rape organization that confronted the white-supremacist gang structures running 1970s Walla Walla, and edited Prison Legal News for many years. He was released in 1993 after 17 years and has continued to be a major figure in U.S. anarchist and prison-abolition writing.","state":"Washington","race":"White","gender":"Male","ideologies":["Anarchism","Prison abolition","Anti-imperialist"],"affiliation":["George Jackson Brigade","Men Against Sexism","Prison Legal News"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Washington State Penitentiary","institution_city":"Walla Walla","institution_state":"Washington","charges":"Washington state attempted bank robbery and conspiracy - January 23, 1976 Tukwila bank robbery; one Brigade member (Bruce Seidel) killed","arrest_date":"1976-01-23","incarceration_date":"1976-01-23","release_date":"1993-08-15","sentence":"30 years Washington state prison; served 17 years","convicted":"Yes - Washington state conviction, 1976"}]}' || true

php artisan prisoner:add '{"name":"John Sherman","first_name":"John","last_name":"Sherman","description":"John Sherman was a member of the George Jackson Brigade arrested on January 23, 1976 in the failed Tukwila, Washington bank robbery in which fellow Brigade member Bruce Seidel was killed and Ed Mead was wounded. Sherman was wounded in the same exchange. After her arrest she was incarcerated in the Washington state prison system for 8 years and was released in 1987.","state":"Washington","race":"White","gender":"Female","ideologies":["Anarchism","Prison abolition","Anti-imperialist"],"affiliation":["George Jackson Brigade"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Washington State Department of Corrections","institution_state":"Washington","charges":"Washington state attempted bank robbery and conspiracy - January 23, 1976 Tukwila bank robbery","arrest_date":"1976-01-23","incarceration_date":"1976-01-23","release_date":"1987-03-15","sentence":"8 years Washington state prison","convicted":"Yes - Washington state conviction, 1976"}]}' || true

php artisan prisoner:add '{"name":"Bo Brown","first_name":"Rita","last_name":"Brown","aka":"Bo","description":"Rita Bo Brown was a working-class lesbian and George Jackson Brigade member from rural Oregon. She was arrested in November 1977 in San Francisco and convicted of bank expropriations conducted by the Brigade. She was sentenced to 25 years federal prison; she served eight years before her parole in 1985. After release she became a longtime San Francisco anti-violence and prison-abolition organizer with Out of Control: Lesbian Committee to Support Women Political Prisoners and similar projects. She died on January 8, 2024.","state":"Oregon","race":"White","gender":"Female","death_date":"2024-01-08","ideologies":["Anarchism","Lesbian liberation","Prison abolition"],"affiliation":["George Jackson Brigade","Out of Control"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal bank robbery and conspiracy - George Jackson Brigade bank expropriations 1975-77","arrest_date":"1977-11-05","incarceration_date":"1977-11-05","release_date":"1985-11-15","sentence":"25 years federal prison; paroled after 8 years","convicted":"Yes - federal court conviction, 1978"}]}' || true

# === Sterling Hall Bombing — UW-Madison, August 24, 1970 ===

php artisan prisoner:add '{"name":"Karleton Armstrong","first_name":"Karleton","last_name":"Armstrong","description":"Karleton Lewis Karl Armstrong was a 23-year-old University of Wisconsin-Madison student in 1970 and the principal organizer of the August 24, 1970 ammonium-nitrate truck bombing of Sterling Hall on the UW-Madison campus. The four-man New Years Gang — Karl, his younger brother Dwight Armstrong, David Fine, and Leo Burt — had identified the Army Mathematics Research Center on the second through fourth floors of Sterling Hall as the principal U.S. academic provider of strategic-bombing target analysis for the Vietnam War. The 2,000-pound ANFO truck bomb detonated at 3:42 a.m.; the building was largely empty but a graduate-student researcher, Robert Fassnacht, was working in a basement laboratory and was killed. Three other people were injured.\n\nKarl fled to Canada and lived underground for nearly two years before being arrested in Toronto in February 1972. He was extradited to the United States, pleaded guilty in September 1973 to second-degree murder and other charges, and was sentenced to 23 years in Wisconsin state prison. He served 7 years and was paroled in 1980. He has spent his life since in Madison.","state":"Wisconsin","race":"White","gender":"Male","birthdate":"1947-04-19","ideologies":["Anti-war","New Left"],"affiliation":["New Years Gang"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state second-degree murder of researcher Robert Fassnacht and federal destruction of government property - August 24, 1970 Sterling Hall ammonium-nitrate truck bombing of the UW-Madison Army Mathematics Research Center","arrest_date":"1972-02-16","incarceration_date":"1973-09-28","sentenced_date":"1973-09-28","release_date":"1980-04-15","sentence":"23 years Wisconsin state prison; paroled after 7 years","convicted":"Yes - guilty plea, Wisconsin state court, September 28, 1973"}]}' || true

php artisan prisoner:add '{"name":"Dwight Armstrong","first_name":"Dwight","last_name":"Armstrong","description":"Dwight Allan Armstrong was 19 years old at the time he and his older brother Karleton Armstrong, with David Fine and Leo Burt, detonated the August 24, 1970 ammonium-nitrate truck bomb at Sterling Hall on the UW-Madison campus, killing graduate-student researcher Robert Fassnacht. He fled to Canada and lived underground for nearly seven years before being arrested in Toronto in April 1977. He was extradited to the United States, pleaded guilty, and was sentenced to 7 years in Wisconsin state prison. He served 3 years and was paroled in 1980. He died on June 20, 2010.","state":"Wisconsin","race":"White","gender":"Male","death_date":"2010-06-20","ideologies":["Anti-war","New Left"],"affiliation":["New Years Gang"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Wisconsin Department of Corrections","institution_state":"Wisconsin","charges":"Wisconsin state and federal charges - August 24, 1970 Sterling Hall bombing","arrest_date":"1977-04-10","incarceration_date":"1977-04-10","release_date":"1980-04-10","sentence":"7 years Wisconsin state prison; served 3 years","convicted":"Yes - guilty plea, Wisconsin state court, 1977"}]}' || true

php artisan prisoner:add '{"name":"David Fine","first_name":"David","last_name":"Fine","description":"David Sylvan Fine was an 18-year-old University of Wisconsin-Madison student in 1970 and one of the four-man New Years Gang who carried out the August 24, 1970 ammonium-nitrate truck bombing of Sterling Hall on the UW-Madison campus, killing researcher Robert Fassnacht. He fled to Canada with co-defendant Leo Burt and lived underground for over five years. He was arrested on January 7, 1976 in San Rafael, California. He pleaded guilty in U.S. District Court in Wisconsin and was sentenced to 7 years in federal prison. He served 3 years and was released in 1979. (Leo Burt remains a fugitive as of 2025 — the longest-held FBI Most Wanted listing in U.S. history.)","state":"Wisconsin","race":"White","gender":"Male","birthdate":"1952-04-15","ideologies":["Anti-war","New Left"],"affiliation":["New Years Gang"],"era":"1970s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal destruction of government property and Wisconsin state charges - August 24, 1970 Sterling Hall bombing","arrest_date":"1976-01-07","incarceration_date":"1976-04-15","sentenced_date":"1976-04-15","release_date":"1979-04-15","sentence":"7 years federal prison; served 3 years","convicted":"Yes - guilty plea, U.S. District Court for the Western District of Wisconsin, 1976"}]}' || true

echo
echo "Round 17 (San Quentin 6 + George Jackson Brigade + Sterling Hall) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
