#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/add_round8_catholic_left_muslim.sh
#
# Source clusters:
#   - Catonsville 9 (May 17, 1968) — Catholic Left raid on Catonsville MD
#     draft board; 378 draft files burned with napalm; 2-3.5 yr federal
#     sentences from Judge Northrop on Nov 8, 1968
#   - Plowshares 8 (Sept 9, 1980) — Catholic Left action at GE Re-Entry
#     Division in King of Prussia PA; nose cones for Mark 12A nuclear
#     warheads damaged with hammers and blood; convicted Feb 1981
#   - Post-9/11 Muslim political prisoners — sting-operation prosecutions
#     under federal material-support and conspiracy statutes
#
# The Berrigan brothers were in both Catonsville 9 and Plowshares 8 and
# get one entry with both cases. All adds wrapped in `|| true` so duplicates
# do not halt the script.

# === Catonsville 9 / Plowshares 8 — Berrigan brothers (both cases) ===

php artisan prisoner:add '{"name":"Daniel Berrigan","first_name":"Daniel","last_name":"Berrigan","description":"Daniel Berrigan was a Jesuit priest, poet, and one of the most prominent peace activists in U.S. history. On May 17, 1968 he and eight others — the Catonsville 9 — entered the draft board office in Catonsville, Maryland, removed 378 draft files, and burned them in the parking lot with homemade napalm in protest of the Vietnam War. He was convicted in October 1968 and sentenced on November 8 to three years in federal prison. He went underground rather than report to prison, was the first priest ever placed on the FBI Most Wanted list, and was arrested at Block Island, Rhode Island in August 1970; he served 18 months at the federal prison camp at Danbury, Connecticut.\n\nOn September 9, 1980, with his brother Philip Berrigan and six others — the Plowshares 8 — he entered the General Electric Re-Entry Division in King of Prussia, Pennsylvania, damaged nose cones for the Mark 12A nuclear warhead with household hammers, and poured blood on weapons documents. He was convicted in February 1981 and sentenced to 3-10 years in Pennsylvania state prison; the conviction was reduced to time served on appeal in April 1990. He died on April 30, 2016, age 94.","state":"Maryland","race":"White","gender":"Male","birthdate":"1921-05-09","death_date":"2016-04-30","ideologies":["Anti-war","Catholic","Plowshares","Pacifism"],"affiliation":["Society of Jesus","Catonsville 9","Plowshares 8","Catholic Worker"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Correctional Institution Danbury","institution_city":"Danbury","institution_state":"Connecticut","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board burning of 378 draft files with homemade napalm","arrest_date":"1968-05-17","incarceration_date":"1970-08-11","release_date":"1972-02-24","sentence":"3 years federal prison; served 18 months at FCI Danbury after underground period","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"},{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, criminal mischief — September 9, 1980 Plowshares 8 hammering of Mark 12A nuclear warhead nose cones at the GE Re-Entry Division in King of Prussia","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"3-10 years state prison; reduced to time served on appeal April 1990","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

php artisan prisoner:add '{"name":"Philip Berrigan","first_name":"Philip","last_name":"Berrigan","description":"Philip Berrigan was a former Josephite priest, decorated U.S. Army Second World War combat veteran, and one of the central organizers of the Catholic Left peace movement of the 1960s through 2000s. With his brother Daniel he led the May 17, 1968 Catonsville 9 raid on the Catonsville, Maryland draft board, in which 378 draft files were taken and burned with homemade napalm. Already under federal sentence for the October 1967 Baltimore Custom House blood pouring (the Baltimore 4), he received the longest Catonsville 9 sentence — 3.5 years — reflecting his prior conviction. He was arrested in 1970 after going underground and served years at the federal prison at Lewisburg, Pennsylvania.\n\nOn September 9, 1980 he was one of the eight Plowshares 8 activists who hammered Mark 12A nose cones at the GE Re-Entry Division in King of Prussia, Pennsylvania. He was a co-founder of Jonah House and the Plowshares Movement and continued symbolic disarmament actions until shortly before his death. He was married to fellow peace activist Elizabeth McAlister (also in this database). He died on December 6, 2002, age 79.","state":"Maryland","race":"White","gender":"Male","birthdate":"1923-10-05","death_date":"2002-12-06","ideologies":["Anti-war","Catholic","Plowshares","Pacifism","Anti-nuclear"],"affiliation":["Society of St. Joseph (Josephites)","Catonsville 9","Plowshares 8","Jonah House","U.S. Army (WWII)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"United States Penitentiary, Lewisburg","institution_city":"Lewisburg","institution_state":"Pennsylvania","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board burning of 378 draft files with homemade napalm","arrest_date":"1968-05-17","incarceration_date":"1970-04-21","release_date":"1972-12-20","sentence":"3.5 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"},{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, criminal mischief — September 9, 1980 Plowshares 8 hammering of Mark 12A nuclear warhead nose cones at the GE Re-Entry Division in King of Prussia","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"3-10 years state prison; reduced to time served on appeal April 1990","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

# === Catonsville 9 — other 7 ===

php artisan prisoner:add '{"name":"George Mische","first_name":"George","last_name":"Mische","description":"George Mische was a Catholic peace activist and one of the principal organizers of the May 17, 1968 Catonsville 9 raid on the Catonsville, Maryland draft board, in which 378 draft files were taken from the office and burned in the parking lot with homemade napalm. He was convicted in federal court on October 10, 1968 and sentenced to 3 years in federal prison. He died on June 24, 2020.","state":"Maryland","race":"White","gender":"Male","death_date":"2020-06-24","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Catonsville 9"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1969-04-09","release_date":"1972-04-09","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

php artisan prisoner:add '{"name":"Thomas Lewis","first_name":"Thomas","last_name":"Lewis","description":"Thomas Lewis was a Catholic Worker artist and peace activist, one of the Baltimore 4 (Oct 27, 1967 blood pouring on draft files at the Baltimore Custom House) and one of the Catonsville 9 (May 17, 1968 burning of 378 draft files at the Catonsville Maryland draft board with homemade napalm). He was convicted in October 1968 and sentenced to 3.5 years in federal prison. He served his sentence and continued decades of nonviolent direct action against U.S. militarism. He died on April 4, 2008.","state":"Maryland","race":"White","gender":"Male","death_date":"2008-04-04","ideologies":["Anti-war","Catholic Worker","Pacifism"],"affiliation":["Catonsville 9","Baltimore 4","Catholic Worker"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal destruction of government property — Oct 27, 1967 Baltimore Custom House blood pouring (Baltimore 4) and May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1969-04-09","release_date":"1972-10-09","sentence":"3.5 years federal prison","convicted":"Yes — federal jury verdicts, U.S. District Court for the District of Maryland, 1968"}]}' || true

php artisan prisoner:add '{"name":"Mary Moylan","first_name":"Mary","last_name":"Moylan","description":"Mary Moylan was a Catholic missionary nurse who had served in Uganda before joining the Catholic Left in the United States. She was one of the Catonsville 9 — the May 17, 1968 raid on the Catonsville, Maryland draft board in which 378 draft files were burned with homemade napalm. She was convicted in October 1968 and sentenced to 2 years in federal prison. Rather than report, she went underground in 1970 and lived in clandestinity for nearly ten years before voluntarily surrendering in 1979. She served 18 months at the Alderson Federal Reformatory for Women in West Virginia. She died on August 6, 1995.","state":"Maryland","race":"White","gender":"Female","death_date":"1995-08-06","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Catonsville 9","Women Volunteers Association"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Reformatory for Women, Alderson","institution_city":"Alderson","institution_state":"West Virginia","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1979-08-15","release_date":"1981-02-15","sentence":"2 years federal prison; surrendered after nearly 10 years underground","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

php artisan prisoner:add '{"name":"Marjorie Melville","first_name":"Marjorie","last_name":"Melville","description":"Marjorie Melville was a former Maryknoll missionary who had been expelled from Guatemala along with her future husband Thomas Melville for solidarity with Indigenous peasant land struggle. Both joined the Catholic Left in the United States and were among the Catonsville 9 — the May 17, 1968 raid on the Catonsville, Maryland draft board in which 378 draft files were burned with homemade napalm. She was convicted in October 1968 and sentenced to 2 years in federal prison. She and Thomas Melville married after the action.","state":"Maryland","race":"White","gender":"Female","ideologies":["Anti-war","Catholic","Latin America solidarity"],"affiliation":["Catonsville 9","Maryknoll Sisters (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Reformatory for Women, Alderson","institution_city":"Alderson","institution_state":"West Virginia","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1969-04-09","release_date":"1970-10-09","sentence":"2 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

php artisan prisoner:add '{"name":"Thomas Melville","first_name":"Thomas","last_name":"Melville","description":"Thomas Melville was a former Maryknoll missionary priest expelled from Guatemala for solidarity with Indigenous peasant land struggle. He joined the Catholic Left in the United States and was one of the Catonsville 9 — the May 17, 1968 raid on the Catonsville, Maryland draft board. He was convicted in October 1968 and sentenced to 3 years in federal prison. He and Marjorie Melville married after the action.","state":"Maryland","race":"White","gender":"Male","ideologies":["Anti-war","Catholic","Latin America solidarity"],"affiliation":["Catonsville 9","Maryknoll Society (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1969-04-09","release_date":"1972-04-09","sentence":"3 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

php artisan prisoner:add '{"name":"John Hogan","first_name":"John","last_name":"Hogan","description":"John Hogan was a former Maryknoll missionary brother who had served in Guatemala and was one of the Catonsville 9 — the May 17, 1968 raid on the Catonsville, Maryland draft board in which 378 draft files were burned with homemade napalm. He was convicted in October 1968 and sentenced to 2 years in federal prison.","state":"Maryland","race":"White","gender":"Male","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Catonsville 9","Maryknoll Brothers (former)"],"era":"1960s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","incarceration_date":"1969-04-09","release_date":"1971-04-09","sentence":"2 years federal prison","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

php artisan prisoner:add '{"name":"David Darst","first_name":"David","last_name":"Darst","description":"David Darst was a Christian Brothers seminarian who, with eight others — the Catonsville 9 — entered the draft board office in Catonsville, Maryland on May 17, 1968 and burned 378 draft files with homemade napalm. He was convicted in October 1968 and sentenced to 2 years in federal prison. He died in an automobile accident in October 1969 before beginning his sentence.","state":"Maryland","race":"White","gender":"Male","death_date":"1969-10-30","ideologies":["Anti-war","Catholic","Pacifism"],"affiliation":["Catonsville 9","Christian Brothers"],"era":"1960s","in_custody":false,"released":false,"cases":[{"institution_name":"(died before incarceration)","charges":"Federal destruction of government property — May 17, 1968 Catonsville draft-board raid","arrest_date":"1968-05-17","sentence":"2 years federal prison; died in automobile accident October 1969 before reporting","convicted":"Yes — federal jury verdict, U.S. District Court for the District of Maryland, October 10, 1968"}]}' || true

# === Plowshares 8 — other 6 ===

php artisan prisoner:add '{"name":"John Schuchardt","first_name":"John","last_name":"Schuchardt","description":"John Schuchardt was a former U.S. Marine Corps officer turned anti-war attorney who became one of the Plowshares 8 — the Catholic Left activists who on September 9, 1980 entered the General Electric Re-Entry Division in King of Prussia, Pennsylvania, hammered nose cones for the Mark 12A nuclear warhead, and poured blood on weapons documents. He was convicted in February 1981 of burglary, conspiracy, trespass, and criminal mischief and sentenced to 3-10 years in Pennsylvania state prison; the sentence was reduced to time served on appeal in April 1990. He went on to co-found the House of Peace community in Ipswich, Massachusetts.","state":"Pennsylvania","race":"White","gender":"Male","ideologies":["Anti-war","Anti-nuclear","Plowshares","Catholic"],"affiliation":["Plowshares 8","U.S. Marine Corps (former)"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8 hammering of Mark 12A nuclear warhead nose cones at the GE Re-Entry Division in King of Prussia","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"3-10 years state prison; reduced to time served on appeal April 1990","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

php artisan prisoner:add '{"name":"Carl Kabat","first_name":"Carl","last_name":"Kabat","description":"Carl Kabat was an Oblate Catholic priest who became one of the most consistently imprisoned U.S. Plowshares activists, serving an estimated 17 years in federal and state prisons across more than 30 years of symbolic disarmament actions. He was one of the Plowshares 8 — the Catholic Left activists who on September 9, 1980 entered the General Electric Re-Entry Division in King of Prussia, Pennsylvania, hammered nose cones for the Mark 12A nuclear warhead, and poured blood on weapons documents. He was convicted in February 1981 and sentenced to 5-10 years in Pennsylvania state prison. After his release he continued Plowshares actions including the 1984 Silo Pruning Hooks (Minuteman II missile silo, 18 years federal), and the 2009 Disarm Now Plowshares at Bangor Submarine Base. He died on August 4, 2022, age 88.","state":"Pennsylvania","race":"White","gender":"Male","death_date":"2022-08-04","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Missionary Oblates of Mary Immaculate","Plowshares 8","Silo Pruning Hooks"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"5-10 years state prison; reduced on appeal","convicted":"Yes — Pennsylvania state conviction, February 1981"},{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal sabotage and destruction of government property — November 12, 1984 Silo Pruning Hooks action at a Minuteman II missile silo near Whiteman AFB, Missouri","arrest_date":"1984-11-12","incarceration_date":"1984-11-12","sentence":"18 years federal prison (Silo Pruning Hooks)","convicted":"Yes — federal court conviction, 1985"}]}' || true

php artisan prisoner:add '{"name":"Anne Montgomery","first_name":"Anne","last_name":"Montgomery","description":"Anne Montgomery was a Roman Catholic Sacred Heart sister and longtime Plowshares activist. She was one of the Plowshares 8 — the September 9, 1980 King of Prussia, Pennsylvania action against the GE Re-Entry Division and the Mark 12A nuclear warhead. She was convicted in February 1981 and sentenced to 2-5 years in Pennsylvania state prison. She participated in many subsequent Plowshares actions, including the 2009 Disarm Now Plowshares at Bangor Submarine Base in Washington state for which she served 2 months. She died on August 27, 2012, age 86.","state":"Pennsylvania","race":"White","gender":"Female","death_date":"2012-08-27","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Society of the Sacred Heart","Plowshares 8"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"2-5 years state prison","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

php artisan prisoner:add '{"name":"Elmer Maas","first_name":"Elmer","last_name":"Maas","description":"Elmer Maas was a music professor and Catholic peace activist, one of the Plowshares 8 who on September 9, 1980 entered the General Electric Re-Entry Division in King of Prussia, Pennsylvania, hammered nose cones for the Mark 12A nuclear warhead, and poured blood on weapons documents. He was convicted in February 1981 and sentenced to 5-10 years in Pennsylvania state prison. He continued Plowshares actions for two more decades. He died on October 30, 2002.","state":"Pennsylvania","race":"White","gender":"Male","death_date":"2002-10-30","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Plowshares 8"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"5-10 years state prison; reduced on appeal","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

php artisan prisoner:add '{"name":"Dean Hammer","first_name":"Dean","last_name":"Hammer","description":"Dean Hammer was a Catholic peace activist and one of the Plowshares 8 — the September 9, 1980 action at the GE Re-Entry Division in King of Prussia, Pennsylvania. He was convicted in February 1981 of burglary, conspiracy, trespass, and criminal mischief and sentenced to a Pennsylvania state prison term that was reduced to time served on appeal in April 1990.","state":"Pennsylvania","race":"White","gender":"Male","ideologies":["Anti-nuclear","Catholic","Plowshares"],"affiliation":["Plowshares 8"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"Pennsylvania state prison; reduced to time served on appeal April 1990","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

php artisan prisoner:add '{"name":"Molly Rush","first_name":"Molly","last_name":"Rush","description":"Molly Rush was a Pittsburgh-based Catholic Worker peace activist, founder of the Thomas Merton Center for Peace and Social Justice in Pittsburgh, and grandmother. She was one of the Plowshares 8 who on September 9, 1980 entered the GE Re-Entry Division in King of Prussia, Pennsylvania, hammered nose cones for the Mark 12A nuclear warhead, and poured blood on weapons documents. She was convicted in February 1981 and sentenced to a Pennsylvania state prison term that was reduced to time served on appeal in April 1990.","state":"Pennsylvania","race":"White","gender":"Female","ideologies":["Anti-nuclear","Catholic Worker","Plowshares"],"affiliation":["Plowshares 8","Thomas Merton Center for Peace and Social Justice"],"era":"1980s","in_custody":false,"released":true,"cases":[{"institution_name":"Pennsylvania Department of Corrections","institution_state":"Pennsylvania","charges":"Pennsylvania state burglary, conspiracy, trespass, criminal mischief — September 9, 1980 Plowshares 8","arrest_date":"1980-09-09","incarceration_date":"1980-09-09","sentence":"Pennsylvania state prison; reduced to time served on appeal April 1990","convicted":"Yes — Pennsylvania state conviction, February 1981"}]}' || true

# === Post-9/11 Muslim political prisoners ===

php artisan prisoner:add '{"name":"Yassin Aref","first_name":"Yassin","middle_name":"M","last_name":"Aref","description":"Yassin Aref is a Kurdish Iraqi imam who came to the United States as a UN refugee in 1999. He was the imam of Masjid As-Salam in Albany, New York at the time of his arrest on August 5, 2004 in an FBI sting operation. The FBI informant Shahed Hussein, posing as an arms dealer, asked pizzeria owner Mohammed Mosharref Hossain to launder money allegedly from the sale of a surface-to-air missile to Jaish-e-Mohammed; Aref was brought in solely as a religious witness to the loan transaction, in accordance with Islamic law on financial agreements.\n\nHe was convicted in October 2006 of conspiracy and money-laundering charges and sentenced in March 2007 to 15 years in federal prison. The 2023 ruling by U.S. District Judge Thomas McAvoy that the FBI informant Shahed Hussein had been a villain whose testimony in unrelated cases warranted relief came too late for Aref, who had already completed his sentence. He was deported to the Iraqi Kurdistan Region after release.","state":"New York","race":"Arab","gender":"Male","ideologies":["Islam","First Amendment"],"affiliation":["Masjid As-Salam (Albany)"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Unit, Terre Haute and Marion)","charges":"Federal conspiracy and money-laundering — Albany pizzeria FBI sting operation, August 2004","arrest_date":"2004-08-05","incarceration_date":"2007-03-08","sentenced_date":"2007-03-08","release_date":"2018-04-15","sentence":"15 years federal prison; subsequently deported to Iraqi Kurdistan","convicted":"Yes — federal jury verdict, U.S. District Court for the Northern District of New York, October 2006"}]}' || true

php artisan prisoner:add '{"name":"Mohammed Mosharref Hossain","first_name":"Mohammed","middle_name":"Mosharref","last_name":"Hossain","description":"Mohammed Mosharref Hossain was the Bangladeshi-American owner of an Albany, New York pizzeria and a founder of the Masjid As-Salam mosque in Albany. He was arrested on August 6, 2004 in an FBI sting operation in which informant Shahed Hussein, posing as an arms dealer, offered him a $50,000 cash loan to be repaid in $45,000 of pizza-shop business checks, with the loaned money allegedly proceeds from the sale of a Chinese surface-to-air missile to Jaish-e-Mohammed for use against the Pakistani Ambassador in New York. Hossain pulled imam Yassin Aref into the transaction solely as a religious witness.\n\nHe was convicted in October 2006 and sentenced in March 2007 to 15 years in federal prison. He was granted compassionate release in June 2020 because of advanced medical risk during the COVID-19 pandemic.","state":"New York","race":"Asian","gender":"Male","ideologies":["Islam","First Amendment"],"affiliation":["Masjid As-Salam (Albany)"],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (location varied)","charges":"Federal conspiracy and money-laundering — Albany pizzeria FBI sting operation, August 2004","arrest_date":"2004-08-06","incarceration_date":"2007-03-08","sentenced_date":"2007-03-08","release_date":"2020-06-30","sentence":"15 years federal prison; compassionate release June 2020","convicted":"Yes — federal jury verdict, U.S. District Court for the Northern District of New York, October 2006"}]}' || true

php artisan prisoner:add '{"name":"Syed Fahad Hashmi","first_name":"Syed","middle_name":"Fahad","last_name":"Hashmi","description":"Syed Fahad Hashmi is a Pakistani-American student of Brooklyn College and the London School of Economics. He was arrested on June 6, 2006 at Heathrow Airport on a U.S. federal indictment charging that he had allowed an acquaintance, Junaid Babar, to stay in his London apartment for two weeks in 2004; Babar had brought a suitcase containing socks, ponchos, and waterproof clothing that the indictment characterized as military gear destined for al Qaeda.\n\nHashmi was extradited to the United States in 2007 and held in 23-hour-a-day solitary confinement at the Metropolitan Correctional Center in Manhattan under Special Administrative Measures for nearly three years before trial. The conditions of his pretrial detention drew international condemnation as torture; the case was a foundational one for the Center for Constitutional Rights post-9/11 detention litigation. On April 27, 2010, days before trial, he pleaded guilty to one count of providing material support to al Qaeda and was sentenced to 15 years in federal prison. Most of his sentence was served at the federal Communications Management Units. He was released on July 19, 2019.","state":"New York","race":"Asian","gender":"Male","ideologies":["Islam","First Amendment"],"affiliation":[],"era":"2000s","in_custody":false,"released":true,"cases":[{"institution_name":"Federal Bureau of Prisons (Communications Management Units)","charges":"Federal conspiracy to provide material support to al Qaeda — alleged 2004 logistical support to Junaid Babar in London","arrest_date":"2006-06-06","incarceration_date":"2007-05-25","sentenced_date":"2010-06-09","release_date":"2019-07-19","sentence":"15 years federal prison","convicted":"Yes — guilty plea, U.S. District Court for the Southern District of New York, April 27, 2010"}]}' || true

echo
echo "Round 8 (Catonsville 9 + Plowshares 8 + post-9/11 Muslim) adds attempted."
echo "Duplicates were skipped via '|| true'; check output above for which rows actually inserted."
