#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_4.sh
#
# Fourth batch (rows 301-400). Per the projects U.S.-nexus scope
# rule, ~50 of the 100 source rows are FARC defendants who were
# charged but not tried (still fugitives or killed in Colombian
# military operations) and are NOT created by this script. The
# defendants who WERE created are: 13 U.S. domestic defendants
# (Vinh Tan Nguyen, Matthew DePalma, Bradley Crowder, David McKay,
# Kyle Shaw, Christopher Monfort, Asheville 11 (5 defendants),
# Daniel Kruk, Jared Lee Loughner, Carlos Montes, Martin Kimber,
# Anthony Hayne, Roberto Rivera, Jeremy Hammond), the 7 RNC 8
# defendants not already in the DB (Bicking, Czernik, Fitzgerald,
# Guillen-Givins, Secor, Specktor, Trimmer), and the FARC / arms-
# dealer defendants who were extradited and served U.S. federal
# time (Corredor-Ibague, Rodriguez-Acevedo, the Salamanca sting
# cluster, the Al-Kassar arms-dealer trio, Conde Rubio, Pena
# Arevalo, Gutierrez Vergara, Ibarguen-Palacio, Banol-Ramos,
# Cordoba-Bermudez, Orobio Lobon, Berrio Ortiz, Palacios Rengifo,
# Dogirama, Beltran Herrera, Navarrete Beltran, Smulian, Viglakis).
#
# Apostrophes pre-stripped from all string content to avoid the
# bash-quoting bug seen in batch 3.
set -e

php artisan tinker --execute='
$rows = [
    // ---- U.S. domestic defendants ----
    ["name"=>"Vinh Tan Nguyen","first_name"=>"Vinh Tan","last_name"=>"Nguyen","aka"=>"Armando Gile Laut, Van Duc Vo","gender"=>"Male","race"=>"Asian/South Asian","state"=>"California","era"=>"2000s","ideologies"=>["Anti-government"],"affiliation"=>["Government of Free Vietnam"],"in_custody"=>false,"released"=>true,"description"=>"Vinh Tan Nguyen, a Vietnamese-American age 63, was convicted of misuse of a passport to facilitate an act of international terrorism for his role in a plot to bomb the Vietnam Embassy in the Philippines. He admitted storing explosives and testing bombs in Manila. Sentenced to 14 months federal prison plus 2 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 1544, 2331 misuse of a passport to facilitate an act of international terrorism - 2006 plot to bomb Vietnam Embassy in the Philippines","arrest_date"=>"2006-12-20","incarceration_date"=>"2006-12-20","convicted"=>"Yes - guilty plea","sentence"=>"14 months federal prison + 2 years supervised release"]]],
    ["name"=>"Matthew Bradley DePalma","first_name"=>"Matthew","middle_name"=>"Bradley","last_name"=>"DePalma","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2000s","ideologies"=>["Anarchism"],"in_custody"=>false,"released"=>true,"description"=>"Matthew Bradley DePalma, age 24, an anarchist, was charged with possession of an unregistered destructive device for preparing Molotov cocktails to be used at the 2008 Republican National Convention in Minneapolis. He unwittingly told his plan to an FBI informant. Pleaded guilty; 42 months federal prison plus 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Minnesota","charges"=>"26 USC 5861(d) prohibited acts (possession of an unregistered destructive device) - 2008 RNC Molotov-cocktail plot","arrest_date"=>"2008-08-29","incarceration_date"=>"2008-08-29","convicted"=>"Yes - guilty plea","sentence"=>"42 months federal prison + 3 years supervised release"]]],
    ["name"=>"Bradley Neil Crowder","first_name"=>"Bradley","middle_name"=>"Neil","last_name"=>"Crowder","gender"=>"Male","state"=>"Texas","era"=>"2000s","ideologies"=>["Anarchism"],"affiliation"=>["Austin Affinity Group"],"in_custody"=>false,"released"=>true,"description"=>"Bradley Neil Crowder, age 23, was one of two Austin Affinity Group members caught making Molotov cocktails before the 2008 Republican National Convention in Minneapolis. They had planned to light the cocktails in tunnels near the event venue to cause a power failure. Pleaded guilty to possession of a destructive device; 24 months federal prison plus 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Minnesota","charges"=>"26 USC 5861(d) and 18 USC 2 possession of a destructive device - 2008 RNC Molotov-cocktail plot in Minneapolis","arrest_date"=>"2008-09-28","incarceration_date"=>"2008-09-28","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison + 36 months supervised release"]]],
    ["name"=>"David Guy McKay","first_name"=>"David","middle_name"=>"Guy","last_name"=>"McKay","gender"=>"Male","state"=>"Texas","era"=>"2000s","ideologies"=>["Anarchism"],"affiliation"=>["Austin Affinity Group"],"in_custody"=>false,"released"=>true,"description"=>"David Guy McKay, age 22, was one of two Austin Affinity Group members caught making Molotov cocktails before the 2008 Republican National Convention. Pleaded guilty to weapons charges; 48 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Minnesota","charges"=>"26 USC 5861(d), 18 USC 2, plus three federal firearm charges - 2008 RNC Molotov-cocktail plot","arrest_date"=>"2008-09-28","incarceration_date"=>"2008-09-28","convicted"=>"Yes - guilty plea","sentence"=>"48 months federal prison"]]],
    ["name"=>"Kyle Shaw","first_name"=>"Kyle","last_name"=>"Shaw","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2000s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Kyle Shaw, age 19, bombed a Starbucks on the Upper East Side of Manhattan in 2009 and was planning a second bombing when arrested. No one was injured. Sentenced to 42 months federal prison.","cases"=>[["institution_name"=>"New York state Department of Corrections","institution_state"=>"New York","charges"=>"NY state arson, criminal possession of a weapon, criminal mischief - 2009 Upper East Side Starbucks bombing (juvenile-status sealed counts)","arrest_date"=>"2009-05-29","incarceration_date"=>"2009-05-29","convicted"=>"Yes - guilty plea","sentence"=>"42 months federal prison"]]],
    ["name"=>"Christopher Monfort","first_name"=>"Christopher","last_name"=>"Monfort","gender"=>"Male","state"=>"Washington","era"=>"2000s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Christopher Monfort, age 49, killed Seattle Officer Timothy Brenton and injured a trainee officer while they were seated in a parked patrol car in 2009. When confronted at his apartment he allegedly tried to shoot a third officer. Police found an arsenal, explosives, and a manifesto opposing police brutality. He was convicted of aggravated murder, three counts of attempted first-degree murder, and first-degree arson; described in coverage as left-wing constitutionalist. He died in custody in 2017.","cases"=>[["institution_name"=>"Washington state Department of Corrections","institution_state"=>"Washington","charges"=>"Washington state aggravated murder; attempted first-degree murder [3 counts]; first-degree arson - 2009 Seattle police shootings and police-vehicle firebombings","arrest_date"=>"2009-11-07","incarceration_date"=>"2009-11-07","death_in_custody_date"=>"2017-09-01","convicted"=>"Yes - jury verdict","sentence"=>"Life in Washington state prison; died in custody"]]],

    // ---- Asheville 11 (May 1, 2010 vandalism, all charges dismissed) ----
    ["name"=>"Jordan Magde Ferrand-Sapsis","first_name"=>"Jordan","middle_name"=>"Magde","last_name"=>"Ferrand-Sapsis","gender"=>"Female","race"=>"White","state"=>"Oklahoma","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["May Day Movement"],"in_custody"=>false,"released"=>true,"description"=>"Jordan Magde Ferrand-Sapsis, age 24, of Oklahoma City, was indicted in September 2010 alongside ten other Asheville 11 defendants for the May 1, 2010 anti-capitalist May Day vandalism in downtown Asheville, NC (~$20,000 in damage to businesses and cars). Charges were dismissed without leave by the DA in 2011-2012.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-2.4(a) conspiracy to commit a felony; 14-144(2) injuring houses, churches, fences, walls; 14-288.2 felony inciting to riot - May 1, 2010 Asheville May Day vandalism","arrest_date"=>"2010-09-13","convicted"=>"No - charges dismissed by DA","sentence"=>"Charges dismissed without leave"]]],
    ["name"=>"Randall Duncan Stezer","first_name"=>"Randall","middle_name"=>"Duncan","last_name"=>"Stezer","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["May Day Movement"],"in_custody"=>false,"released"=>true,"description"=>"Randall Duncan Stezer, age 17, of Graham NC, was one of the Asheville 11 indicted for the May 1, 2010 May Day vandalism. Charges dismissed.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-2.4(a) conspiracy; 14-144(2) injuring buildings; 14-288.2 inciting to riot - May 1, 2010 Asheville May Day vandalism","arrest_date"=>"2010-09-13","convicted"=>"No - charges dismissed","sentence"=>"Charges dismissed without leave"]]],
    ["name"=>"Wyatt Sherman Allgeier","first_name"=>"Wyatt","middle_name"=>"Sherman","last_name"=>"Allgeier","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["May Day Movement"],"in_custody"=>false,"released"=>true,"description"=>"Wyatt Sherman Allgeier, age 19, of Mount Pleasant NC, was one of the Asheville 11 indicted for the May 1, 2010 May Day vandalism. Charges dismissed.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-2.4(a) conspiracy; 14-144(2) injuring buildings; 14-288.2 inciting to riot","arrest_date"=>"2010-09-13","convicted"=>"No - charges dismissed","sentence"=>"Charges dismissed without leave"]]],
    ["name"=>"Cailin Elizabeth Major","first_name"=>"Cailin","middle_name"=>"Elizabeth","last_name"=>"Major","gender"=>"Female","race"=>"White","state"=>"Wisconsin","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["May Day Movement"],"in_custody"=>false,"released"=>true,"description"=>"Cailin Elizabeth Major, age 25, of Milwaukee, was one of the Asheville 11 indicted for the May 1, 2010 May Day vandalism. Charges dismissed.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-2.4(a) conspiracy; 14-144(2) injuring buildings; 14-288.2 inciting to riot","arrest_date"=>"2010-09-13","convicted"=>"No - charges dismissed","sentence"=>"Charges dismissed without leave"]]],
    ["name"=>"Nicholas Ryan Entwistle","first_name"=>"Nicholas","middle_name"=>"Ryan","last_name"=>"Entwistle","gender"=>"Male","race"=>"White","state"=>"Missouri","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["May Day Movement"],"in_custody"=>false,"released"=>true,"description"=>"Nicholas Ryan Entwistle, age 19, of Kansas City, was one of the Asheville 11 indicted for the May 1, 2010 May Day vandalism. Charges dismissed.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-2.4(a) conspiracy; 14-144(2) injuring buildings; 14-288.2 inciting to riot","arrest_date"=>"2010-09-13","convicted"=>"No - charges dismissed","sentence"=>"Charges dismissed without leave"]]],

    ["name"=>"Daniel Kruk","first_name"=>"Daniel","last_name"=>"Kruk","gender"=>"Male","race"=>"White","state"=>"Indiana","era"=>"2010s","ideologies"=>["Anarchism"],"in_custody"=>false,"released"=>true,"description"=>"Daniel Kruk, age 31, was indicted in 2010 in connection with the September 2000 arson of the RNC national headquarters in Bloomington, Indiana. Court records were sealed in 2012 after the indictment was dismissed in exchange for cooperation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Indiana","charges"=>"18 USC 81 federal arson - September 2000 Bloomington Indiana RNC headquarters arson","arrest_date"=>"2010-09-14","convicted"=>"No - sealed dismissal in exchange for cooperation","sentence"=>"Sealed; cooperator"]]],

    // ---- RNC 8 (Republican National Convention Welcoming Committee, 2008-2010) ----
    ["name"=>"Monica Bicking","first_name"=>"Monica","last_name"=>"Bicking","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Monica Bicking was one of the RNC 8 indicted for organizing affinity-group disruption of the 2008 Republican National Convention in St. Paul. Initial charges included conspiracy to riot in furtherance of terrorism (later dismissed). All felonies were ultimately dropped.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy to riot in the second degree in furtherance of terrorism (dismissed); conspiracy to commit riot 2nd degree; conspiracy to commit criminal damage to property in furtherance of terrorism; conspiracy to commit criminal damage to property - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"No - all charges dropped","sentence"=>"All charges dropped"]]],
    ["name"=>"Robert Czernik","first_name"=>"Robert","last_name"=>"Czernik","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Robert Czernik, age 35, was one of the RNC 8 indicted for organizing affinity-group disruption of the 2008 RNC. Pleaded guilty to a misdemeanor; terrorism enhancement dropped, all felonies dropped, probation plus $200 fine.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy to riot 2nd degree (felony, dropped); related criminal damage conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"Yes - misdemeanor plea","sentence"=>"Probation + $200 fine; all felonies dropped"]]],
    ["name"=>"Garrett Fitzgerald","first_name"=>"Garrett","last_name"=>"Fitzgerald","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Garrett Fitzgerald, age 27, was one of the RNC 8. Pleaded to a misdemeanor; probation plus $200 fine.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"Yes - misdemeanor plea","sentence"=>"Probation + $200 fine"]]],
    ["name"=>"Luce Guillen-Givins","first_name"=>"Luce","last_name"=>"Guillen-Givins","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Luce Guillen-Givins, age 24, was one of the RNC 8. All charges dropped.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"No - all charges dropped","sentence"=>"All charges dropped"]]],
    ["name"=>"Nathanael Secor","first_name"=>"Nathanael","last_name"=>"Secor","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Nathanael Secor, age 28, was one of the RNC 8. Pleaded to a misdemeanor; probation plus $200 fine.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"Yes - misdemeanor plea","sentence"=>"Probation + $200 fine"]]],
    ["name"=>"Max Specktor","first_name"=>"Max","last_name"=>"Specktor","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Max Specktor, age 21, was one of the RNC 8. Pleaded to a misdemeanor; probation plus $200 fine.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"Yes - misdemeanor plea","sentence"=>"Probation + $200 fine"]]],
    ["name"=>"Eryn Trimmer","first_name"=>"Eryn","last_name"=>"Trimmer","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Anarchism"],"affiliation"=>["RNC Welcoming Committee"],"in_custody"=>false,"released"=>true,"description"=>"Eryn Trimmer was one of the RNC 8. All charges dropped.","cases"=>[["institution_name"=>"Ramsey County District Court","institution_city"=>"St. Paul","institution_state"=>"Minnesota","charges"=>"Minnesota state conspiracy charges - 2008 RNC organizing","arrest_date"=>"2010-10-19","convicted"=>"No - all charges dropped","sentence"=>"All charges dropped"]]],

    // ---- Loughner, Montes, Kimber, Hayne, Rivera, Hammond ----
    ["name"=>"Jared Lee Loughner","first_name"=>"Jared","middle_name"=>"Lee","last_name"=>"Loughner","gender"=>"Male","race"=>"White","state"=>"Arizona","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Jared Lee Loughner, age 23, attempted to assassinate Representative Gabrielle Giffords in Tucson, Arizona on January 8, 2011, killing six people and wounding 13 including Rep. Giffords. Initially deemed incompetent due to paranoid schizophrenia, he was later found competent and pleaded guilty to 19 counts. Sentenced to 1,680 months (140 years) federal prison.","cases"=>[["institution_name"=>"Federal Medical Center, Rochester","institution_city"=>"Rochester","institution_state"=>"Minnesota","charges"=>"Federal attempted assassination of a member of Congress; murder of a federal employee [2 counts]; attempting to murder a federal employee [2 counts] - 2011 Tucson mass shooting","arrest_date"=>"2011-01-08","incarceration_date"=>"2011-01-08","convicted"=>"Yes - guilty plea","sentence"=>"1,680 months (140 years) federal prison"]]],
    ["name"=>"Carlos Montes","first_name"=>"Carlos","last_name"=>"Montes","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"2010s","ideologies"=>["Anti-Imperialism"],"affiliation"=>["Brown Berets","Committee to Stop FBI Repression"],"in_custody"=>false,"released"=>true,"description"=>"Carlos Montes, age 64, a longtime Chicano activist and Brown Berets member, had his Alhambra home raided by the LA Sheriffs SWAT Team and FBI on May 17, 2011 in connection with the Committee to Stop FBI Repression investigation. He was charged with felon-in-possession of firearms based on a 1969 conviction for throwing a soda can at a police officer during a civil rights demonstration; despite having registered his weapons for decades. Took a no-contest plea on a single count; three perjury counts dismissed; 3 years probation, 180 hours community service, prohibited from possessing weapons.","cases"=>[["institution_name"=>"Los Angeles County Superior Court","institution_state"=>"California","charges"=>"18 USC 922(g)(1) felon in possession of firearm and ammunition; perjury [3 counts dismissed] - 2011 Committee to Stop FBI Repression-linked raid","arrest_date"=>"2011-05-17","convicted"=>"Yes - no-contest plea","sentence"=>"3 years probation + 180 hours community service"]]],
    ["name"=>"Martin S. Kimber","first_name"=>"Martin","last_name"=>"Kimber","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Martin S. Kimber, age 59, was arrested for planting two pounds of mercury in several locations inside an Albany, New York hospital, including on food served to patients. Pleaded guilty to chemical-weapon and consumer-product-tampering charges; 168 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 229(a)(1) use and possession of a chemical weapon; 18 USC 1365(a) consumer product tampering - 2012 Albany NY hospital mercury contamination","arrest_date"=>"2012-03-14","incarceration_date"=>"2012-03-14","convicted"=>"Yes - guilty plea","sentence"=>"168 months federal prison"]]],
    ["name"=>"Anthony Hayne","first_name"=>"Anthony","last_name"=>"Hayne","aka"=>"Tony, Billy","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2010s","ideologies"=>["Anarchism"],"in_custody"=>false,"released"=>true,"description"=>"Anthony Hayne, age 35, was the fifth defendant (cooperator) in the 2012 Cleveland 5 / May Day Bombers case in which five self-proclaimed anarchists attempted to bomb a bridge in Cuyahoga Valley National Park on the eve of May Day 2012. The plot involved an FBI confidential informant who supplied a dummy bomb. Hayne pleaded guilty and was sentenced to 72 months federal prison in exchange for cooperation against the four others.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Ohio","charges"=>"18 USC 2332a use of weapons of mass destruction [2 counts]; 18 USC 844(h) use of explosive materials and aiding and abetting - 2012 Cleveland 5 May Day bridge-bombing plot","arrest_date"=>"2012-05-13","incarceration_date"=>"2012-05-13","convicted"=>"Yes - guilty plea (cooperator)","sentence"=>"72 months federal prison"]]],
    ["name"=>"Roberto Rivera","first_name"=>"Roberto","last_name"=>"Rivera","gender"=>"Male","race"=>"White","state"=>"New Jersey","era"=>"2010s","ideologies"=>["Anti-Capitalism"],"affiliation"=>["Occupy Wall Street"],"in_custody"=>false,"released"=>true,"death_date"=>"2020-04-22","description"=>"Roberto Rivera, age 66, an emergency-room physician, was radicalized by the Occupy Wall Street movement in August 2011 and accumulated nitric acid, glycerin, potassium perchlorate, and 10 detonators along with unregistered assault firearms. He stated he intended to topple the Charging Bull statue in Manhattans financial district. After three trials, he was convicted on multiple counts; 25 years New Jersey state prison with parole eligibility after 7 years. Died in state prison April 22, 2020.","cases"=>[["institution_name"=>"New Jersey State Prison","institution_city"=>"Trenton","institution_state"=>"New Jersey","charges"=>"NJ state risk of widespread injury; unlicensed possession of assault firearms; possession of a destructive device; failure to mitigate widespread injury; possession of a stun gun; large-capacity ammunition magazine","arrest_date"=>"2012-11-16","incarceration_date"=>"2012-11-16","death_in_custody_date"=>"2020-04-22","convicted"=>"Yes - jury verdict (third trial)","sentence"=>"300 months (25 years) NJ state prison; died in custody April 22, 2020"]]],
    ["name"=>"Jeremy Hammond","first_name"=>"Jeremy","last_name"=>"Hammond","aka"=>"Anarchaos","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2010s","ideologies"=>["Anarchism","Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Jeremy Hammond, age 33, a self-described hacktivist, hacked into the global intelligence firm Stratfor (Strategic Forecasting) in December 2011, releasing client data via WikiLeaks. Pleaded guilty in 2013 to a single count of hacking-related conspiracy; 120 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal hacking-related criminal charges [12 counts] - 2011 Stratfor breach","arrest_date"=>"2013-11-26","incarceration_date"=>"2013-11-26","convicted"=>"Yes - guilty plea","sentence"=>"120 months federal prison"]]],

    // ---- FARC / Sendero / Al-Kassar arms-dealer extradited cluster (positive sentence months) ----
    ["name"=>"Jose Maria Corredor-Ibague","first_name"=>"Jose Maria","last_name"=>"Corredor-Ibague","aka"=>"Boyaco","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Jose Maria Corredor-Ibague (Boyaco), age 46, ran a Colombian cocaine-manufacturing and -transportation network that paid taxes to the FARC in U.S. currency and weapons. Pleaded guilty in U.S. federal court under the federal narco-terrorism statute; 194 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","charges"=>"21 USC 963 conspiracy to manufacture and distribute cocaine; 18 USC 2 aiding and abetting; 21 USC 960a federal narco-terrorism statute","arrest_date"=>"2005-05-14","incarceration_date"=>"2005-05-14","convicted"=>"Yes - guilty plea","sentence"=>"194 months federal prison"]]],
    ["name"=>"Hector Rodriguez-Acevedo","first_name"=>"Hector","last_name"=>"Rodriguez-Acevedo","aka"=>"Nacho Rodriguez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Right-Wing"],"affiliation"=>["AUC"],"in_custody"=>false,"released"=>true,"description"=>"Hector Ignacio Rodriguez-Acevedo (Nacho Rodriguez), age 49, conspired to send weapons to the United Self-Defense Forces of Colombia (AUC). Pleaded guilty; 50 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B providing material support to terrorists; 18 USC 963 narcotics import conspiracy; 21 USC 846 cocaine-distribution conspiracy; 18 USC 924 firearms in furtherance","arrest_date"=>"2005-05-17","incarceration_date"=>"2005-05-17","convicted"=>"Yes - guilty plea","sentence"=>"50 months federal prison"]]],

    // Salamanca cluster (Bogota-airport ICE sting; tried in S.D. Florida)
    ["name"=>"Jorge De Los Reyes Bautista Martinez","first_name"=>"Jorge","last_name"=>"Bautista Martinez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Jorge De Los Reyes Bautista Martinez, age 48, was caught in a 2005 Immigration and Customs Enforcement sting in which he and nine co-defendants helped undercover informants posing as FARC members travel through Bogota airport. 36 months federal prison + 24 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 371 conspiracy to commit alien smuggling; 8 USC 1324 alien smuggling - 2005 Bogota airport ICE sting","arrest_date"=>"2005-12-27","incarceration_date"=>"2005-12-27","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison + 24 months supervised release"]]],
    ["name"=>"Bernardo Valdes Londono","first_name"=>"Bernardo","last_name"=>"Valdes Londono","aka"=>"Don Beny","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Bernardo Valdes Londono (Don Beny), age 48, Salamanca-cluster defendant. 30 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B conspiracy to provide material support to a foreign terrorist organization; 18 USC 371 conspiracy to commit alien smuggling - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-01","incarceration_date"=>"2006-01-01","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison + 36 months supervised release"]]],
    ["name"=>"Luis Alfredo Daza Morales","first_name"=>"Luis Alfredo","last_name"=>"Daza Morales","aka"=>"Fernando","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Luis Alfredo Daza Morales, age 48, Salamanca-cluster defendant. 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support; 18 USC 371 conspiracy to commit alien smuggling - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-02","incarceration_date"=>"2006-01-02","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],
    ["name"=>"Victor Daniel Salamanca","first_name"=>"Victor Daniel","last_name"=>"Salamanca","aka"=>"El Viejito, Don Daniel","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Victor Daniel Salamanca (El Viejito), age 63, lead defendant in the Salamanca cluster - the FARC ICE-sting case in which he helped undercover informants get fake IDs, passports, and contacts including a money launderer. 70 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support; 18 USC 371 alien smuggling; 18 USC 1956 money-laundering conspiracy - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-02","incarceration_date"=>"2006-01-02","convicted"=>"Yes - guilty plea","sentence"=>"70 months federal prison + 36 months supervised release"]]],
    ["name"=>"Julio Cesar Lopez","first_name"=>"Julio Cesar","last_name"=>"Lopez","aka"=>"Hernan Medina Ochoa","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Julio Cesar Lopez, Salamanca-cluster money-launderer who oversaw the operations $4-5 million laundering arm. 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support; 18 USC 1956 money-laundering conspiracy - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-02","incarceration_date"=>"2006-01-02","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],
    ["name"=>"Jose Tito Libio Ulloa Melo","first_name"=>"Jose","last_name"=>"Ulloa Melo","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Jose Tito Libio Ulloa Melo, age 46, Salamanca-cluster defendant; airport-security contact. 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support; 18 USC 371 alien smuggling - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-02","incarceration_date"=>"2006-01-02","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],
    ["name"=>"Carmen Maria Ponton Caro","first_name"=>"Carmen Maria","last_name"=>"Ponton Caro","aka"=>"La Negra","gender"=>"Female","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Carmen Maria Ponton Caro (La Negra), age 38, Salamanca-cluster defendant. 70 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support; 18 USC 371 alien smuggling - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-02","incarceration_date"=>"2006-01-02","convicted"=>"Yes - guilty plea","sentence"=>"70 months federal prison + 36 months supervised release"]]],
    ["name"=>"Edizon Ramirez Gamboa","first_name"=>"Edizon","last_name"=>"Ramirez Gamboa","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Edizon Ramirez Gamboa, age 40, an immigration inspector who helped Salamanca-cluster informants get through Bogota airport. 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","charges"=>"18 USC 371 alien-smuggling conspiracy - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-03","incarceration_date"=>"2006-01-03","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison"]]],
    ["name"=>"Nicolas Ricardo Tapasco Romero","first_name"=>"Nicolas","last_name"=>"Tapasco Romero","gender"=>"Male","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Nicolas Ricardo Tapasco Romero, age 45, a former detective with the Colombian Department of Administrative Security; Salamanca-cluster defendant. 36 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 371 alien-smuggling conspiracy - 2005 Bogota airport ICE sting","arrest_date"=>"2006-01-03","incarceration_date"=>"2006-01-03","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison + 36 months supervised release"]]],

    // Al-Kassar arms-dealer trio
    ["name"=>"Monzer Al Kassar","first_name"=>"Monzer","last_name"=>"Al Kassar","gender"=>"Male","race"=>"Arab","state"=>"New York","era"=>"2000s","ideologies"=>["Arms Trafficking"],"in_custody"=>true,"released"=>false,"description"=>"Monzer Al Kassar, a Syrian arms dealer, age 63, was caught in a 2007 sting by DEA agents posing as FARC rebels seeking weapons to kill Americans. Convicted of conspiracy to kill U.S. citizens and officers, conspiracy to acquire and export surface-to-air missiles, material-support conspiracy, and money laundering. Sentenced to 360 months federal prison.","cases"=>[["institution_name"=>"USP Marion","institution_city"=>"Marion","institution_state"=>"Illinois","charges"=>"18 USC 2332(b) conspiracy to kill U.S. citizens; 18 USC 1114, 1117 conspiracy to kill U.S. officers/employees; 18 USC 2332g conspiracy to acquire and export SAMs; 18 USC 2339B material support; 18 USC 1956 money laundering","arrest_date"=>"2007-06-22","incarceration_date"=>"2007-06-22","convicted"=>"Yes - jury verdict","sentence"=>"360 months federal prison"]]],
    ["name"=>"Luis Felipe Moreno Godoy","first_name"=>"Luis Felipe","last_name"=>"Moreno Godoy","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2000s","ideologies"=>["Arms Trafficking"],"in_custody"=>true,"released"=>false,"description"=>"Luis Felipe Moreno Godoy, a Chilean national age 60, was Monzer Al Kassars associate in the 2007 DEA-FARC arms-dealer sting. Convicted at trial; 300 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2332(b) conspiracy; 18 USC 2332g SAMs conspiracy; 18 USC 2339B material support; 18 USC 1956 money laundering","arrest_date"=>"2007-06-22","incarceration_date"=>"2007-06-22","convicted"=>"Yes - jury verdict","sentence"=>"300 months federal prison"]]],
    ["name"=>"Tareq Mousa Al Ghazi","first_name"=>"Tareq","last_name"=>"Al Ghazi","gender"=>"Male","race"=>"Arab","state"=>"New York","era"=>"2000s","ideologies"=>["Arms Trafficking"],"in_custody"=>true,"released"=>false,"description"=>"Tareq Mousa Al Ghazi, age 62, was Monzer Al Kassars associate in the 2007 DEA-FARC arms-dealer sting. Convicted at trial; 300 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2332(b) conspiracy; 18 USC 2332g SAMs conspiracy; 18 USC 2339B material support","arrest_date"=>"2007-06-22","incarceration_date"=>"2007-06-22","convicted"=>"Yes - jury verdict","sentence"=>"300 months federal prison"]]],

    // GAAR cluster - extradited
    ["name"=>"Nancy Conde Rubio","first_name"=>"Nancy","last_name"=>"Conde Rubio","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Nancy Conde Rubio, age 37, a high-ranking FARC member who oversaw the FARCs logistics and communications network used to transport three American hostages in 2003. Extradited to the U.S.; convicted of conspiracy and material-support charges; 138 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B conspiracy to provide material support to a designated foreign terrorist organization; 18 USC 2 aiding and abetting","arrest_date"=>"2007-09-25","incarceration_date"=>"2007-09-25","convicted"=>"Yes - guilty plea","sentence"=>"138 months federal prison + 36 months supervised release"]]],
    ["name"=>"Ana Isabel Pena Arevalo","first_name"=>"Ana Isabel","last_name"=>"Pena Arevalo","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Ana Isabel Pena Arevalo, age 47, GAAR-cluster defendant. 31 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support and conspiracy","arrest_date"=>"2007-09-25","incarceration_date"=>"2007-09-25","convicted"=>"Yes - guilty plea","sentence"=>"31 months federal prison + 36 months supervised release"]]],
    ["name"=>"Luz Mery Gutierrez Vergara","first_name"=>"Luz Mery","last_name"=>"Gutierrez Vergara","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Luz Mery Gutierrez Vergara, age 32, GAAR-cluster defendant. 31 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339B material support and conspiracy","arrest_date"=>"2007-09-25","incarceration_date"=>"2007-09-25","convicted"=>"Yes - guilty plea","sentence"=>"31 months federal prison + 36 months supervised release"]]],
    ["name"=>"Andrew Smulian","first_name"=>"Andrew","last_name"=>"Smulian","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2000s","ideologies"=>["Arms Trafficking"],"in_custody"=>false,"released"=>true,"description"=>"Andrew Smulian, age 67, a South African pilot, was the cooperating co-conspirator who helped DEA agents charge Russian arms dealer Viktor Bout. Pleaded guilty in 2008; 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2332b conspiracy to kill U.S. nationals; 18 USC 1114, 1117 conspiracy to kill U.S. officers; 18 USC 2332g conspiracy to acquire and use anti-aircraft missiles; 18 USC 2339B material support - 2007-2008 Viktor Bout sting","arrest_date"=>"2008-07-30","incarceration_date"=>"2008-07-30","convicted"=>"Yes - guilty plea (cooperator)","sentence"=>"60 months federal prison"]]],

    // Ibarguen-Palacio + Banol-Ramos (Panama firefight)
    ["name"=>"Jorge Abel Ibarguen-Palacio","first_name"=>"Jorge Abel","last_name"=>"Ibarguen-Palacio","aka"=>"Turbo","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Jorge Abel Ibarguen-Palacio (Turbo), age 40, was captured in a boat off the coast of Panama in 2009 following a firefight with Panamanian police while attempting to provide weapons to FARC. 130 months federal prison + 2 years specialized release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339 conspiring to provide material support to a foreign terrorist organization","arrest_date"=>"2009-05-14","incarceration_date"=>"2009-05-14","convicted"=>"Yes - guilty plea","sentence"=>"130 months federal prison + 2 years supervised release"]]],
    ["name"=>"Yarlei Banol-Ramos","first_name"=>"Yarlei","last_name"=>"Banol-Ramos","aka"=>"Diana","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Yarlei Banol-Ramos (Diana), age 35, was captured with Ibarguen-Palacio off Panama in 2009 during a firefight with Panamanian police while attempting to provide weapons to FARC. 180 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 2339 conspiring to provide material support to a foreign terrorist organization","arrest_date"=>"2009-05-14","incarceration_date"=>"2009-05-14","convicted"=>"Yes - guilty plea","sentence"=>"180 months federal prison"]]],

    // MORAPESTANA cluster - extradited
    ["name"=>"Juanito Cordoba-Bermudez","first_name"=>"Juanito","last_name"=>"Cordoba-Bermudez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Juanito Cordoba-Bermudez, FARC 57th Front member, was extradited and pleaded guilty to material-support conspiracy. 180 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Conspiracy to provide material support; conspiracy to murder, kidnap, or maim overseas","arrest_date"=>"2009-09-28","incarceration_date"=>"2009-09-28","convicted"=>"Yes - guilty plea","sentence"=>"180 months federal prison"]]],
    ["name"=>"Roque Orobio Lobon","first_name"=>"Roque","last_name"=>"Orobio Lobon","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Roque Orobio Lobon, age 46, FARC 57th Front member; pleaded guilty to hostage taking. 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal hostage-taking - 2007 hostage-taking of a U.S. citizen in Panama by FARC 57th Front","arrest_date"=>"2009-09-28","incarceration_date"=>"2009-09-28","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison"]]],
    ["name"=>"Edilberto Berrio Ortiz","first_name"=>"Edilberto","last_name"=>"Berrio Ortiz","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Edilberto Berrio Ortiz, age 34, FARC 57th Front member; convicted at trial. 204 months federal prison + supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal hostage-taking - 2007 FARC 57th Front hostage-taking in Panama","arrest_date"=>"2009-09-28","incarceration_date"=>"2009-09-28","convicted"=>"Yes - jury verdict","sentence"=>"204 months federal prison"]]],
    ["name"=>"Alejandro Palacios Rengifo","first_name"=>"Alejandro","last_name"=>"Palacios Rengifo","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Alejandro Palacios Rengifo, age 32, FARC 57th Front member; convicted at trial. 180 months federal prison + supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal hostage-taking - 2007 FARC 57th Front hostage-taking in Panama","arrest_date"=>"2009-09-28","incarceration_date"=>"2009-09-28","convicted"=>"Yes - jury verdict","sentence"=>"180 months federal prison"]]],
    ["name"=>"Anderson Chamapuro Dogirama","first_name"=>"Anderson","last_name"=>"Chamapuro Dogirama","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Anderson Chamapuro Dogirama, age 28, FARC 57th Front member; convicted at trial. 120 months federal prison + supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Conspiracy to murder, kidnap, or maim overseas - 2007 FARC 57th Front hostage-taking in Panama","arrest_date"=>"2009-09-28","incarceration_date"=>"2009-09-28","convicted"=>"Yes - jury verdict","sentence"=>"120 months federal prison"]]],

    // GARCIA cluster - extradited
    ["name"=>"Alexander Beltran Herrera","first_name"=>"Alexander","last_name"=>"Beltran Herrera","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"District of Columbia","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Alexander Beltran Herrera, age 39, FARC member; extradited and pleaded guilty in connection with the 2003-2008 hostage-taking of three American citizens (Marc Gonsalves, Keith Stansell, Thomas Howes) in Colombia. 324 months federal prison + 2 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 1203 conspiracy to commit hostage-taking; 18 USC 924(c) using and carrying a firearm during a crime of violence; 18 USC 2339A, 2339B material support","arrest_date"=>"2010-12-14","incarceration_date"=>"2010-12-14","convicted"=>"Yes - guilty plea","sentence"=>"324 months federal prison + 2 years supervised release"]]],
    ["name"=>"Diego Alfonso Navarrete Beltran","first_name"=>"Diego Alfonso","last_name"=>"Navarrete Beltran","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"District of Columbia","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Diego Alfonso Navarrete Beltran, age 44, FARC member; extradited and pleaded guilty in connection with the 2003-2008 hostage-taking of three Americans. 324 months federal prison + 2 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 1203 conspiracy to commit hostage-taking; 18 USC 924(c); 18 USC 2339A, 2339B material support","arrest_date"=>"2010-12-14","incarceration_date"=>"2010-12-14","convicted"=>"Yes - guilty plea","sentence"=>"324 months federal prison + 2 years supervised release"]]],

    // Ioannis Viglakis (Greek, sold weapons to FARC)
    ["name"=>"Ioannis Viglakis","first_name"=>"Ioannis","last_name"=>"Viglakis","aka"=>"Pablo","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2010s","ideologies"=>["Arms Trafficking"],"in_custody"=>false,"released"=>true,"description"=>"Ioannis Viglakis (Pablo), a Greek arms dealer age 52, was arrested in Panama for attempting to sell rocket-propelled grenade launchers and other weapons to a DEA informant posing as a FARC representative. Pleaded guilty; 120 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal conspiracy to provide material support to a foreign terrorist organization","arrest_date"=>"2012-08-01","incarceration_date"=>"2012-08-01","convicted"=>"Yes - guilty plea","sentence"=>"120 months federal prison"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";

echo "\nNote: ~50 FARC defendants from this batch (rows 301-302, 318-320, 324-328, 337-347, 367-384, 399-400) who are charged but not tried (still fugitives, killed by Colombian military, or serving sentences in their home countries) were NOT created - they fall outside the projects U.S.-nexus scope rule.\n";
'

echo
echo "Prosecution Project rows 301-400 import complete."
