#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_blm_2020.sh
#
# 2020 George Floyd / BLM protest federal prosecutions (rows 101-144
# of the TPP BLM subset). Mostly arson / civil disorder / threats /
# Molotov-cocktail charges from late May - early August 2020 protests
# nationwide.
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"Jordan Coyne","first_name"=>"Jordan","last_name"=>"Coyne","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Jordan Coyne, 25, threw rocks, bricks, pieces of concrete, and a tear gas canister at police officers and a police vehicle during the May 30, 2020 Pittsburgh protests after the murder of George Floyd. The tear gas canister struck an officer in the hand. Pleaded guilty; 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder - May 30 2020 Pittsburgh BLM protest","arrest_date"=>"2020-08-26","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    ["name"=>"Marcello Earle Woods","first_name"=>"Marcello","middle_name"=>"Earle","last_name"=>"Woods","gender"=>"Male","race"=>"Black","state"=>"South Carolina","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Marcello Earle Woods, 28, of Columbia SC, was charged September 1, 2020 with destroying a Columbia Police Department vehicle by fire on May 30, 2020. Pleaded guilty; 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"South Carolina","charges"=>"18 USC 844(f) Arson of Federally Funded Property - May 30 2020 Columbia SC CPD vehicle arson","arrest_date"=>"2020-09-01","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    ["name"=>"Abraham Elijah Jenkins","first_name"=>"Abraham","middle_name"=>"Elijah","last_name"=>"Jenkins","aka"=>"AJ","gender"=>"Male","race"=>"Black","state"=>"South Carolina","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Abraham Elijah Jenkins, 26, of Charleston SC, was charged September 8, 2020 with civil disorder for the May 30, 2020 Charleston BLM protest. Pleaded guilty; 18 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"South Carolina","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder; 18 USC 2 Aiding and Abetting - May 30 2020 Charleston BLM protest","arrest_date"=>"2020-09-08","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    ["name"=>"Emily Nowlin","first_name"=>"Emily","last_name"=>"Nowlin","gender"=>"Female","state"=>"Arkansas","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter","Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Emily Nowlin, 27, of Little Rock AR, was indicted December 14, 2020 in the Jeffrey et al. case for August 2020 Molotov-cocktail attacks on police vehicles at the Little Rock PD 12th Street Substation and Arkansas State Police Headquarters. Pleaded guilty; 18 months federal prison + $35,956.31 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arkansas","charges"=>"18 USC 844(f) Malicious Destruction of Federally Funded Property; 18 USC 844(n) Conspiracy; 26 USC 5861(d) Possession of Destructive Devices - August 2020 Little Rock PD/ASP Molotov attacks","arrest_date"=>"2020-12-14","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison + $35,956 restitution"]]],

    ["name"=>"Renea Goddard","first_name"=>"Renea","last_name"=>"Goddard","gender"=>"Female","race"=>"South Asian","state"=>"Arkansas","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter","Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Renea Goddard, 22, of Little Rock AR, Jeffrey et al. co-defendant for the August 2020 Molotov attacks on Little Rock and ASP police vehicles. Pleaded guilty; 18 months federal prison + $35,956.31 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arkansas","charges"=>"18 USC 844(f); 18 USC 844(n); 26 USC 5861(d) - August 2020 LRPD/ASP Molotov attacks","arrest_date"=>"2020-12-14","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison + $35,956 restitution"]]],

    ["name"=>"Aline A. Espinosa-Villegas","first_name"=>"Aline","middle_name"=>"A.","last_name"=>"Espinosa-Villegas","aka"=>"Loba Espinoza-Villegas","gender"=>"Other","race"=>"Latino/Hispanic","state"=>"Arkansas","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter","Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Aline A. Espinosa-Villegas, 24, of Little Rock AR, Jeffrey et al. co-defendant for the August 2020 Molotov attacks on Little Rock police vehicles. Pleaded guilty; 18 months federal prison + $34,356.31 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arkansas","charges"=>"18 USC 844(f); 18 USC 844(n); 26 USC 5861(d) - August 2020 LRPD/ASP Molotov attacks","arrest_date"=>"2020-12-14","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison + $34,356 restitution"]]],

    ["name"=>"Brittany Dawn Jeffrey","first_name"=>"Brittany","middle_name"=>"Dawn","last_name"=>"Jeffrey","aka"=>"Dawn","gender"=>"Female","race"=>"Black","state"=>"Arkansas","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter","Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Brittany Dawn Jeffrey, 31, of Little Rock AR, lead defendant in Jeffrey et al.; the Molotov cocktails were assembled at her residence. Pleaded guilty; 17 months federal prison + $529.30 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arkansas","charges"=>"18 USC 844(f); 18 USC 844(n); 26 USC 5861(d) - August 2020 LRPD/ASP Molotov attacks","arrest_date"=>"2020-12-14","convicted"=>"Yes - guilty plea","sentence"=>"17 months federal prison + $529 restitution"]]],

    ["name"=>"Dashun Martin","first_name"=>"Dashun","last_name"=>"Martin","gender"=>"Male","race"=>"Black","state"=>"Georgia","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Dashun Martin, 23, was indicted June 17, 2020 in Gainesville GA along with co-defendants Jesse James Smallwood, Delveccho Waller Jr., Bruce Thompson, and Judah Coleman Bailey for conspiring to and committing arson of a police vehicle during the post-George Floyd protests. Pleaded guilty; 17 months federal prison + 3 years supervised release + $3,678.17 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"18 USC 371 Conspiracy; 18 USC 844(i) Arson in Interstate Commerce - May/June 2020 Gainesville GA police vehicle arson","arrest_date"=>"2020-06-17","convicted"=>"Yes - guilty plea","sentence"=>"17 months federal prison + 3 yr supervised release + $3,678 restitution"]]],

    ["name"=>"Bruce Thompson","first_name"=>"Bruce","last_name"=>"Thompson","gender"=>"Male","race"=>"Black","state"=>"Georgia","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Bruce Thompson, 22, Gainesville GA Smallwood et al. co-defendant for the May/June 2020 police vehicle arson. Pleaded guilty; 14 months federal prison + 3 years supervised release + $3,678.17 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"18 USC 371 Conspiracy; 18 USC 844(i) Arson in Interstate Commerce - May/June 2020 Gainesville GA police vehicle arson","arrest_date"=>"2020-06-17","convicted"=>"Yes - guilty plea","sentence"=>"14 months federal prison + 3 yr supervised release + $3,678 restitution"]]],

    ["name"=>"Miguel Ramos","first_name"=>"Miguel","last_name"=>"Ramos","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Miguel Ramos, 26, with Dyshika McFadden and Tindal, used an aerosol can and open flame to set fire to an RPD vehicle during the May 30, 2020 Rochester NY BLM protests. The burning was broadcast on Facebook Live. Convicted at trial; 16 months federal prison + $4,287 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(n) Conspiracy to Commit Arson; 18 USC 844(i) Arson in Interstate Commerce; 18 USC 2 Aiding and Abetting - May 30 2020 Rochester RPD vehicle arson","arrest_date"=>"2020-06-20","convicted"=>"Yes - jury verdict","sentence"=>"16 months federal prison + $4,287 restitution"]]],

    ["name"=>"Jacob D. Little","first_name"=>"Jacob","middle_name"=>"D.","last_name"=>"Little","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Jacob D. Little, 24, was charged September 10, 2020 with possession of a stolen firearm after stealing a Colt M4 rifle with suppressor from a Seattle PD photo-unit patrol vehicle abandoned during the May 30, 2020 Seattle BLM protest. Pleaded guilty; 16 months federal prison + 3 years supervised release + $4,446.12 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"18 USC 922(j) Possession of a Stolen Firearm - May 30 2020 Seattle SPD M4 rifle theft","arrest_date"=>"2020-09-10","convicted"=>"Yes - guilty plea","sentence"=>"16 months federal prison"]]],

    ["name"=>"Edward Thomas Schinzing","first_name"=>"Edward","middle_name"=>"Thomas","last_name"=>"Schinzing","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Edward Thomas Schinzing, 32, was charged July 28, 2020 with using fire to maliciously damage the Justice Center in downtown Portland on May 29, 2020. Identified by a distinctive last-name back tattoo. Pleaded guilty; 15 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"18 USC 844(f)(1) Damaging Government Property by Fire - May 29 2020 Portland Justice Center fire","arrest_date"=>"2020-07-28","convicted"=>"Yes - guilty plea","sentence"=>"15 months federal prison"]]],

    ["name"=>"Alexander Charles Pridgen","first_name"=>"Alexander","middle_name"=>"Charles","last_name"=>"Pridgen","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Alexander Charles Pridgen, 18, of Greenville NC, threw a brick through a ground-floor window of the federal bankruptcy court during the May 31, 2020 BLM protest, then later vandalized the Greenville Police Station. Firearm charge added while indicted. Convicted; 15 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Carolina","charges"=>"18 USC 1361 Destruction of Government Property; 18 USC 922(n) Receipt of a Firearm While Under Felony Indictment - May 31 2020 Greenville NC bankruptcy court vandalism","arrest_date"=>"2020-12-16","convicted"=>"Yes - jury verdict","sentence"=>"15 months federal prison"]]],

    ["name"=>"Peter James Yeager","first_name"=>"Peter","middle_name"=>"James","last_name"=>"Yeager","gender"=>"Male","state"=>"Washington","era"=>"2020s","ideologies"=>["Anti-Democratic-Party"],"in_custody"=>false,"released"=>true,"description"=>"Peter James Yeager, 45, USMC veteran, drove from Grand Coulee WA to Spokane on December 9, 2020 with a preconceived plan to burn down the Spokane County Democrats office in the Teamsters Building, telling people he had a bomb. Possessed staged-bomb props but no actual completed device. Found not guilty by reason of insanity in March 2024 in federal court.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"18 USC 844(i) Damage by Fire to Building Used in Interstate Commerce - Dec 2020 Spokane Democrats office arson attempt","arrest_date"=>"2021-01-05","convicted"=>"NGRI - found not guilty by reason of insanity","sentence"=>"NGRI committal"]]],

    ["name"=>"Urooj Rahman","first_name"=>"Urooj","last_name"=>"Rahman","gender"=>"Female","race"=>"South Asian","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Urooj Rahman, 31, attorney, with Colinford Mattis attempted to use Molotov cocktails to damage NYPD vehicles during the May 31, 2020 Brooklyn protests over the murder of George Floyd. Pleaded guilty; 15 months federal prison + 2 years probation + $30,137 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(i) Arson in Interstate Commerce; 18 USC 844(h)(1) Use of Explosive in Felony; 18 USC 844(n) Arson Conspiracy; 18 USC 924(c)(1)(B)(ii) Use of Destructive Device; 18 USC 231(a)(3) Civil Disorder - May 31 2020 Brooklyn NYPD Molotov","arrest_date"=>"2022-06-02","convicted"=>"Yes - guilty plea","sentence"=>"15 months federal prison + 2 yr probation + $30,137 restitution"]]],

    ["name"=>"Colinford Mattis","first_name"=>"Colinford","last_name"=>"Mattis","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Colinford Mattis, 32, attorney, with Urooj Rahman attempted to use Molotov cocktails to damage NYPD vehicles during the May 31, 2020 Brooklyn protests. Pleaded guilty; 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(i) Arson in Interstate Commerce; 18 USC 844(h)(1) Use of Explosive in Felony; 18 USC 844(n) Arson Conspiracy; 18 USC 924(c)(1)(B)(ii) Use of Destructive Device - May 31 2020 Brooklyn NYPD Molotov","arrest_date"=>"2022-06-02","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Latroi Devon Newbins","first_name"=>"Latroi","middle_name"=>"Devon","last_name"=>"Newbins","gender"=>"Male","race"=>"Black","state"=>"Utah","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Latroi Devon Newbins, 28, charged July 23, 2020 with arson in Salt Lake City after the May 30, 2020 BLM protest where he threw combustible material into a burning police car. Pleaded guilty; 13 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"18 USC 844(i) Arson in Interstate Commerce - May 30 2020 SLC police car arson","arrest_date"=>"2020-07-23","convicted"=>"Yes - guilty plea","sentence"=>"13 months federal prison"]]],

    ["name"=>"Christopher Isidro Rojas","first_name"=>"Christopher","middle_name"=>"Isidro","last_name"=>"Rojas","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Utah","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Christopher Isidro Rojas, 28, used a cigarette lighter to ignite a piece of fabric thrown into an overturned SLC police car during the May 30, 2020 BLM protest. Charged July 23, 2020. Pleaded guilty; 13 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"18 USC 844(i) Arson in Interstate Commerce - May 30 2020 SLC police car arson","arrest_date"=>"2020-07-23","convicted"=>"Yes - guilty plea","sentence"=>"13 months federal prison"]]],

    ["name"=>"George Allen","first_name"=>"George","last_name"=>"Allen","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"George Allen, 31, of Pittsburgh, charged July 22, 2020 with civil disorder for damaging an occupied police vehicle by throwing an object through the front passenger window during the May 30, 2020 Pittsburgh BLM protest. Pleaded guilty; 12 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 2 Aiding and Abetting - May 30 2020 Pittsburgh BLM protest","arrest_date"=>"2020-07-22","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison + 3 yr supervised release"]]],

    ["name"=>"Mackenzie Drechsler","first_name"=>"Mackenzie","last_name"=>"Drechsler","gender"=>"Female","race"=>"Biracial / Multiracial","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Mackenzie Drechsler, 19, of Ontario NY, charged June 30, 2020 with arson for the May 30, 2020 burning of two vehicles in Rochester (NY State AGs Office and City of Rochester FACIT). Pleaded guilty; 12 months and 1 day federal prison + 2 years supervised release + $8,674 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(i) Arson in Interstate Commerce; 18 USC 2 Aiding and Abetting - May 30 2020 Rochester NY AG/FACIT vehicle arson","arrest_date"=>"2020-06-30","convicted"=>"Yes - guilty plea","sentence"=>"12 months and 1 day federal prison + $8,674 restitution"]]],

    ["name"=>"Shelby Ligons","first_name"=>"Shelby","last_name"=>"Ligons","gender"=>"Female","race"=>"Black","state"=>"Tennessee","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Shelby Ligons, 22, of Nashville, charged August 3, 2020 with malicious destruction of property by fire after she set fire to a poster reading slogans against police and placed it inside a window of the Nashville Metro Courthouse on May 30, 2020. Pleaded guilty; 12 months and 1 day federal prison + 3 years supervised release + $500 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Tennessee","charges"=>"18 USC 844(i) Arson in Interstate Commerce - May 30 2020 Nashville Metro Courthouse fire","arrest_date"=>"2020-08-03","convicted"=>"Yes - guilty plea","sentence"=>"12 months and 1 day federal prison"]]],

    ["name"=>"Mario Ernesto Alvarado","first_name"=>"Mario","middle_name"=>"Ernesto","last_name"=>"Alvarado","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Mario Ernesto Alvarado, 42, charged August 4, 2020 with arson for setting fire to Pizzeria Mozza / Mozza2Go in Hollywood during the May 30, 2020 LA protests; $550,000 in damage. Pleaded guilty February 28, 2022; 12 months and 1 day federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 844(i) Arson in Interstate Commerce - May 30 2020 Hollywood Pizzeria Mozza arson","arrest_date"=>"2020-08-04","convicted"=>"Yes - guilty plea","sentence"=>"12 months and 1 day federal prison"]]],

    ["name"=>"Javon Hardy","first_name"=>"Javon","last_name"=>"Hardy","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Javon Hardy, 24, set fire to a 32-by-8-foot mobile office at the Rochester Public Safety Building during the May 30, 2020 BLM protest, captured on Facebook Live yelling Let that bitch burn. Charged December 15, 2020. Pleaded guilty; 12 months federal prison + $14,504 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(i) Arson in Interstate Commerce; 18 USC 2101 Travel to Incite Riots - May 30 2020 Rochester PSB mobile office arson","arrest_date"=>"2020-12-15","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Raphael Shaw","first_name"=>"Raphael","last_name"=>"Shaw","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Raphael Shaw, 20, broke into a Wells Fargo on West Philadelphias 52nd Street corridor on May 31, 2020 wearing a blonde wig, pointed a rifle at people inside, and used a stolen Lowes forklift to remove a $104,000 cash vault. Pleaded guilty; time served (~12 months) + 15 months supervised release + $104,000 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 2113(a) Entering a Bank With Intent to Commit a Felony; 18 USC 2113(b) Taking and Carrying Away $1,000+ From a Bank - May 31 2020 Philadelphia Wells Fargo vault theft","arrest_date"=>"2020-08-25","convicted"=>"Yes - guilty plea","sentence"=>"Time served (~12 mo) + $104,000 restitution"]]],

    ["name"=>"Anthony David Ale Smith","first_name"=>"Anthony","middle_name"=>"David Ale","last_name"=>"Smith","aka"=>"Ant","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"affiliation"=>["Philadelphia Coalition for Racial Economic and Legal Justice"],"in_custody"=>false,"released"=>true,"description"=>"Anthony David Ale Smith, 29, with co-defendants Carlos Matchett and Khalif Miller, indicted October 20, 2020 for the May 30, 2020 arson of a Philadelphia PD vehicle. Pleaded guilty June 6, 2023 to obstruction of law enforcement during civil disorder, several months after Philadelphia announced a $9.25 million police-response settlement. ~12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder - May 30 2020 Philadelphia PPD vehicle arson","arrest_date"=>"2020-10-20","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Kyle Robert Tornow","first_name"=>"Kyle","middle_name"=>"Robert","last_name"=>"Tornow","aka"=>"Chester Wildwood","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Kyle Robert Tornow, 36, of Seattle, was arrested April 22, 2021 for using the Portland Police TrackIT system on July 24, 2020 to send a threat claiming he had planted an undetectable bomb at a Portland police precinct. Pleaded guilty; time served (~11 months) + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"18 USC 875(c) Interstate Threats - July 2020 Portland PD bomb threat","arrest_date"=>"2021-04-22","convicted"=>"Yes - guilty plea","sentence"=>"Time served (~11 months) + 3 yr supervised release"]]],

    ["name"=>"Errick Steven Toa","first_name"=>"Errick","middle_name"=>"Steven","last_name"=>"Toa","gender"=>"Male","race"=>"Black","state"=>"North Dakota","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Errick Steven Toa, 33, jumped on top of an occupied police car and broke its windshield during the May 30, 2020 Fargo ND BLM protest. Charged July 15, 2020. Pleaded guilty; ~10.6 months time served + 2 years supervised release + $390 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) Civil Disorder - May 30 2020 Fargo ND police car","arrest_date"=>"2020-05-30","convicted"=>"Yes - guilty plea","sentence"=>"~10.6 months time served + 2 yr supervised release"]]],

    ["name"=>"Ronald T. Green","first_name"=>"Ronald","middle_name"=>"T.","last_name"=>"Green","gender"=>"Male","race"=>"Biracial / Multiracial","state"=>"Ohio","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Ronald T. Green, 24, of Youngstown OH, threw an object through the rear window of a Youngstown police cruiser during the May 31, 2020 BLM protest; also charged federally as a felon in possession of ammunition (prior 2015 Texas burglary conviction). Sentenced September 3, 2020 to 10 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Ohio","charges"=>"18 USC 922(g)(1) Felon in Possession of a Firearm/Ammunition - 2019 ammunition possession; concurrent OH state vandalism for May 31 2020 Youngstown protest","arrest_date"=>"2020-09-03","convicted"=>"Yes - guilty plea","sentence"=>"10 months federal prison"]]],

    ["name"=>"Ryan David Lucero","first_name"=>"Ryan","middle_name"=>"David","last_name"=>"Lucero","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Ryan David Lucero, 33, of Magna UT, charged September 9, 2020 with influencing a federal officer by threat after threatening to murder a Department of Veterans Affairs police officer following the May 30, 2020 SLC riots. The threat was found in the officers mailbox by his teenage daughter. Pleaded guilty; 9 months / time served + $100 special assessment.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"18 USC 115(a)(1)(B) Violent Threats to Federal Official Family - June 2020 VA officer death threat","arrest_date"=>"2020-09-09","convicted"=>"Yes - guilty plea","sentence"=>"9 months / time served"]]],

    ["name"=>"Jhajuan Sabb","first_name"=>"Jhajuan","last_name"=>"Sabb","aka"=>"Jhumoney Tvshow","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Jhajuan Sabb, 20, of Troy NY, made several Facebook Live videos threatening to throw bricks at the Troy PD, Troy police vehicles, and Troy City Hall during the June 2020 BLM protests, and offered instructions for making firebombs. Pleaded guilty; 8 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 875(c) Interstate Threatening Communications; 18 USC 842(p)(2)(A) Distribution of Information Relating to Explosives - June 2020 Troy NY threats","arrest_date"=>"2020-06-06","convicted"=>"Yes - guilty plea","sentence"=>"8 months federal prison"]]],

    ["name"=>"Tearra NaAsia Guthrie","first_name"=>"Tearra","middle_name"=>"NaAsia","last_name"=>"Guthrie","gender"=>"Female","race"=>"Black","state"=>"South Carolina","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>false,"death_date"=>"2022-05-01","description"=>"Tearra NaAsia Guthrie, 23, of Charleston, charged September 8, 2020 with civil disorder for the May 30, 2020 Charleston BLM protest. Pleaded guilty; 7 months federal prison (terrorism-enhancement-applied guideline cap of 5 years was avoided in plea). Died May 2022.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"South Carolina","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 2 Aiding and Abetting - May 30 2020 Charleston BLM protest","arrest_date"=>"2020-09-08","convicted"=>"Yes - guilty plea","sentence"=>"7 months federal prison"]]],

    ["name"=>"Andrew Steven Faulkner","first_name"=>"Andrew","middle_name"=>"Steven","last_name"=>"Faulkner","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Andrew Steven Faulkner, 24, of Beaverton OR, charged July 6, 2020 with assaulting federal officers using high-intensity lasers during the July 5-6, 2020 Portland federal courthouse protests. Possessed a sheathed machete at arrest. Pleaded guilty; 6 months detention + 3 years probation + 40 hours community service.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"18 USC 111(a)(1) Forcibly Interfering With Federal Officer - July 2020 Portland federal officer laser assault","arrest_date"=>"2020-07-06","convicted"=>"Yes - guilty plea","sentence"=>"6 months detention + 3 yr probation"]]],

    ["name"=>"Corey Smith","first_name"=>"Corey","last_name"=>"Smith","gender"=>"Other","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Corey Smith, 24, gender non-conforming, with co-defendant Elaine Carberry, set fire to a marked NYPD Homeless Outreach Unit van on University Place at 4:35 a.m. July 15, 2020. Charged August 11, 2020. Pleaded guilty; 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(n) Conspiracy to Commit Arson; 18 USC 844(f) Arson - July 15 2020 NYC NYPD Homeless Outreach van arson","arrest_date"=>"2020-08-11","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    ["name"=>"Elaine Carberry","first_name"=>"Elaine","last_name"=>"Carberry","gender"=>"Female","race"=>"White","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Elaine Carberry, 36, with Corey Smith set fire to an NYPD Homeless Outreach van on July 15, 2020 in NYC. Charged August 11, 2020. Pleaded guilty; 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(n) Conspiracy to Commit Arson; 18 USC 844(f) Arson - July 15 2020 NYC NYPD Homeless Outreach van arson","arrest_date"=>"2020-08-11","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    ["name"=>"Jeffrey Richard Singer","first_name"=>"Jeffrey","middle_name"=>"Richard","last_name"=>"Singer","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Jeffrey Richard Singer, 33, charged October 20, 2020 with civil disorder (charging at and shoulder-slamming officers in front of Portland City Hall on October 4, 2020) and theft of government property (stealing the US flag from the Gus Solomon Courthouse flagpole September 19, 2020). Pleaded guilty; 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 641 Theft of Government Property - Oct 2020 Portland City Hall + Sept 2020 Gus Solomon Courthouse flag theft","arrest_date"=>"2020-10-20","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    ["name"=>"Raekwon Dac Blankenship","first_name"=>"Raekwon","middle_name"=>"Dac","last_name"=>"Blankenship","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Raekwon Dac Blankenship, 24, of Pittsburgh, charged July 22, 2020 with damaging unmarked and marked police vehicles by hitting/kicking/stomping and throwing a projectile through a windshield during the May 30, 2020 Pittsburgh BLM protest; also struck multiple police horses. Pleaded guilty; ~5.3 months (time served + 3 years supervised release).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder; 18 USC 2 Aiding and Abetting - May 30 2020 Pittsburgh","arrest_date"=>"2020-07-22","convicted"=>"Yes - guilty plea","sentence"=>"~5.3 months time served + 3 yr supervised release"]]],

    ["name"=>"Shakell Sanks","first_name"=>"Shakell","last_name"=>"Sanks","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Shakell Sanks, 26, helped light a piece of fabric covered in gas thats stuffed into the gas tank of the Family Crisis Intervention Team (FACIT) car at the Rochester Public Safety Building on May 30, 2020. Charged July 8, 2020. Pleaded guilty; 5 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(i) Arson in Interstate Commerce; 18 USC 2 Aiding and Abetting - May 30 2020 Rochester FACIT car arson","arrest_date"=>"2020-07-08","convicted"=>"Yes - guilty plea","sentence"=>"5 months federal prison"]]],

    ["name"=>"Abdimanan Bana Habib","first_name"=>"Abdimanan","middle_name"=>"Bana","last_name"=>"Habib","gender"=>"Male","race"=>"Black","state"=>"North Dakota","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Abdimanan Bana Habib, 21, of Fargo ND, threw rocks at police and attempted to light a Molotov cocktail during the May 2020 BLM protests. Charged October 21, 2020. Pleaded guilty; 4 months federal prison + 3 years supervised release + $2,500 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) Civil Disorder - May 2020 Fargo ND BLM protest","arrest_date"=>"2020-10-21","convicted"=>"Yes - guilty plea","sentence"=>"4 months federal prison"]]],

    ["name"=>"Loren Reed","first_name"=>"Loren","last_name"=>"Reed","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"Arizona","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Loren Reed, 26, of Page AZ, used a private Facebook group to organize a riot and plan to burn down the Page Magistrate Courthouse and Page Police Department office. Charged June 2, 2020. Pleaded guilty; 2 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arizona","charges"=>"18 USC 844(e) Internet/Telephone Threat to Damage Building by Fire - June 2020 Page AZ courthouse threat","arrest_date"=>"2020-06-02","convicted"=>"Yes - guilty plea","sentence"=>"2 months federal prison"]]],

    ["name"=>"Christian Rea","first_name"=>"Christian","last_name"=>"Rea","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Christian Rea, 19, threw an explosive/incendiary device near a Naperville IL PD Special Response team vehicle and officers on June 1, 2020. The device exploded; 4 officers temporarily blinded and momentarily deafened. Pleaded guilty; 1 month federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"18 USC 231(a)(3) Civil Disorder - June 1 2020 Naperville IL BLM explosive","arrest_date"=>"2020-06-25","convicted"=>"Yes - guilty plea","sentence"=>"1 month federal prison"]]],

    ["name"=>"Xavier Nolley-Hall","first_name"=>"Xavier","last_name"=>"Nolley-Hall","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Xavier Nolley-Hall, 20, was with Raphael Shaw entering the West Philadelphia Wells Fargo with intent to steal money during the May 31, 2020 BLM-related civil unrest. Charged August 25, 2020. Pleaded guilty; 45 days federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 2113(a) Entering a Bank With Intent to Commit a Felony; 18 USC 1001(a)(2) False Statements - May 31 2020 Philadelphia Wells Fargo","arrest_date"=>"2020-08-25","convicted"=>"Yes - guilty plea","sentence"=>"45 days federal prison"]]],

    ["name"=>"Edward William Carubis","first_name"=>"Edward","middle_name"=>"William","last_name"=>"Carubis","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Edward William Carubis, 25, charged July 13, 2020 with assaulting federal officers in Portland by shining a green laser into three officers eyes. Pleaded guilty; 2 days time served.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"18 USC 111(a) Forcibly Interfering With Federal Officer - July 2020 Portland laser assault","arrest_date"=>"2020-07-13","convicted"=>"Yes - guilty plea","sentence"=>"2 days time served"]]],

    ["name"=>"Josie Robotin","first_name"=>"Josie","last_name"=>"Robotin","aka"=>"Jacob Dean Robotin","gender"=>"Other","race"=>"White","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Trans Liberation","Anti-police"],"in_custody"=>false,"released"=>true,"description"=>"Josie Robotin, 25, of Willow Grove PA, was charged August 18, 2022 with possessing an unregistered firearm after a Molotov cocktail was found in her backpack at a 2021 Philadelphia protest for the rights of trans prisoners; she and others were seen vandalizing buildings with spray paint and breaking windows. Pleaded guilty; time served + 3 years probation + $100 fine. Court documents use her birth name.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"26 USC 5861(d) Knowingly Possessed an Unregistered Firearm - 2021 Philadelphia trans-rights protest Molotov","arrest_date"=>"2022-08-18","convicted"=>"Yes - guilty plea","sentence"=>"Time served + 3 yr probation + $100 fine"]]],

    ["name"=>"Brian Jordan Bartels","first_name"=>"Brian","middle_name"=>"Jordan","last_name"=>"Bartels","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-police","Black Lives Matter"],"in_custody"=>false,"released"=>true,"description"=>"Brian Jordan Bartels, 20, of Pittsburgh, attacked and vandalized a police car during the May 30, 2020 BLM protest. Charged June 9, 2020. Pleaded guilty; 1 day in custody + 6 months in a halfway house.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder; 18 USC 2 Aiding and Abetting - May 30 2020 Pittsburgh police vehicle vandalism","arrest_date"=>"2020-06-09","convicted"=>"Yes - guilty plea","sentence"=>"1 day in custody + 6 months halfway house"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "TPP BLM 2020 import (rows 101-144) complete."
