#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows.sh
#
# Imports the editor-supplied 100-row Prosecution Project subset of
# eco / animal-rights defendants. For each row: looks up the
# canonical name; if the prisoner already exists, prints EXISTS and
# moves on (no overwrite); if not, creates a new prisoner + case row
# from the supplied fields. Idempotent.
#
# Skipped categories handled by per-row decisions in the array
# below: dismissed cases get a record with convicted = "No"; minors
# (under 18 at indictment) are still added because the public
# Prosecution Project entry already discloses their identity. Cases
# with a 0-month sentence and charges-dismissed or acquittal verdict
# are still recorded since the dataset documents the prosecution
# event itself.
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"Michael Glen Mathias","first_name"=>"Michael Glen","last_name"=>"Mathias","gender"=>"Male","state"=>"Nevada","era"=>"1990s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Michael Glen Mathias was indicted in March 1995 on federal charges arising from the bombing of an outhouse on a campground in Lamoille Canyon, Nevada, allegedly in retaliation against federal land management. The action damaged the outhouse with no human casualties.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Nevada","charges"=>"Federal explosives charges - Lamoille Canyon, Nevada outhouse bombing on a federal campground","arrest_date"=>"1995-03-28","incarceration_date"=>"1995-03-28","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Jamie L. Boulter","first_name"=>"Jamie","last_name"=>"Boulter","gender"=>"Female","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Jamie L. Boulter, age 18, was charged in 1995 with aggravated arson for allegedly throwing a Molotov cocktail into the Majestic Meats meatpacking plant in Salt Lake City, Utah. Charges were ultimately dismissed.","cases"=>[["institution_name"=>"Salt Lake County Detention","institution_city"=>"Salt Lake City","institution_state"=>"Utah","charges"=>"Utah state aggravated arson (Utah Code 76-6-103) - alleged Molotov-cocktail attack on Majestic Meats meatpacking plant","arrest_date"=>"1995-08-03","convicted"=>"No - charges dismissed","sentence"=>"Charges dismissed"]]],

    ["name"=>"Jason Troff","first_name"=>"Jason","last_name"=>"Troff","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jason Troff, age 19, was one of four animal-rights activists who set fire to a McDonalds under construction in West Jordan, Utah in 1996, destroying about 80 percent of the building. Sentenced to 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal use of an explosive device, arson, and possession of an explosive device - 1996 McDonalds construction-site arson, West Jordan, Utah","arrest_date"=>"1996-08-25","incarceration_date"=>"1996-08-25","sentenced_date"=>"1996-08-25","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Mark Klein","first_name"=>"Mark","last_name"=>"Klein","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Mark Klein, age 19, was one of four animal-rights activists who set fire to a McDonalds under construction in West Jordan, Utah in 1996. Sentenced to 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal arson and possession of an explosive device - 1996 McDonalds construction-site arson, West Jordan, Utah","arrest_date"=>"1996-08-25","incarceration_date"=>"1996-08-25","sentenced_date"=>"1996-08-25","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Ryan Durfee","first_name"=>"Ryan","last_name"=>"Durfee","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Ryan Durfee, age 19, was one of four animal-rights activists who set fire to a McDonalds under construction in West Jordan, Utah in 1996. Sentenced to 12 months federal prison plus 200 hours community service.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal arson and possession of an explosive device - 1996 McDonalds construction-site arson, West Jordan, Utah","arrest_date"=>"1996-08-25","incarceration_date"=>"1996-08-25","sentenced_date"=>"1996-08-25","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison + 200 hours community service"]]],

    ["name"=>"Bret G. Walton","first_name"=>"Bret","last_name"=>"Walton","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Bret G. Walton, age 18, was one of three ALF defendants charged for the attempted arson of Montgomery Fur Company in West Haven, Utah on March 18, 1997. Sentenced to 30 days home confinement.","cases"=>[["institution_name"=>"Weber County Jail","institution_city"=>"Ogden","institution_state"=>"Utah","charges"=>"Attempted aggravated arson - 1997 attempted firebombing of Montgomery Fur Company, West Haven, Utah","arrest_date"=>"1997-03-18","convicted"=>"Yes - guilty plea","sentence"=>"30 days home confinement"]]],

    ["name"=>"Cameron Michael Kraus","first_name"=>"Cameron","last_name"=>"Kraus","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Cameron Michael Kraus, age 18, was one of three ALF defendants charged for the attempted arson of Montgomery Fur Company in West Haven, Utah in 1997. Sentenced to 30 days county jail.","cases"=>[["institution_name"=>"Weber County Jail","institution_city"=>"Ogden","institution_state"=>"Utah","charges"=>"Attempted aggravated arson - 1997 attempted firebombing of Montgomery Fur Company, West Haven, Utah","arrest_date"=>"1997-03-18","incarceration_date"=>"1997-03-18","convicted"=>"Yes - guilty plea","sentence"=>"30 days county jail"]]],

    ["name"=>"Trev J. Poulson","first_name"=>"Trev","last_name"=>"Poulson","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Trev J. Poulson, age 19, was one of three ALF defendants charged for the attempted arson of Montgomery Fur Company in West Haven, Utah in 1997. 24-month sentence suspended to time served plus 36 months probation.","cases"=>[["institution_name"=>"Weber County Jail","institution_city"=>"Ogden","institution_state"=>"Utah","charges"=>"Attempted aggravated arson - 1997 attempted firebombing of Montgomery Fur Company, West Haven, Utah","arrest_date"=>"1997-03-18","incarceration_date"=>"1997-03-18","convicted"=>"Yes - bench verdict","sentence"=>"24 months county jail (suspended to time served + 36 months probation)"]]],

    ["name"=>"Jacob Lymon Kenison","first_name"=>"Jacob Lymon","last_name"=>"Kenison","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jacob Lymon Kenison, age 19, was charged in 1998 with one count aggravated arson reduced to two counts criminal mischief after firebombing a leather store in Murray, Utah, throwing a brick through its window, and spray-painting animal-rights slogans. Sentenced to 9 months county jail plus 36 months probation.","cases"=>[["institution_name"=>"Salt Lake County Jail","institution_city"=>"Salt Lake City","institution_state"=>"Utah","charges"=>"Utah state aggravated arson (reduced to two counts criminal mischief) - 1998 firebombing of a Murray, Utah leather store","arrest_date"=>"1998-05-11","incarceration_date"=>"1998-05-11","convicted"=>"Yes - guilty plea","sentence"=>"9 months county jail + 36 months probation"]]],

    ["name"=>"Clinton Colby Ellerman","first_name"=>"Clinton Colby","last_name"=>"Ellerman","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Clinton Colby Ellerman, brother of Douglas Joshua Ellerman, was charged in the 1997 pipe-bombing of the Fur Breeders Agricultural Cooperative offices in Sandy, Utah, where six pipe bombs caused approximately one million dollars in property damage with no injuries. Sentenced to 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal pipe-bomb manufacturing, malicious destruction with a bomb, and use of a bomb in an act of violence - 1997 Fur Breeders Agricultural Cooperative bombing, Sandy, Utah","arrest_date"=>"1998-09-10","incarceration_date"=>"1998-09-10","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison"]]],

    ["name"=>"Peter Schnell","first_name"=>"Peter","last_name"=>"Schnell","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Peter Schnell, age 21, was charged with attempted arson in 2001 after being found behind Capitola City Hall with plastic milk bottles, gasoline, and candles. Sentenced to 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal possession of firearms/incendiary devices and making destructive devices/unregistered firearms - 2001 attempted arson, Capitola California","arrest_date"=>"2001-01-23","incarceration_date"=>"2001-01-23","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Matthew Whyte","first_name"=>"Matthew","last_name"=>"Whyte","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Matthew Whyte, age 18, was charged with attempted arson in 2001 alongside Peter Schnell in Capitola, California. Sentenced to 14 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal possession of firearms/incendiary devices and making destructive devices/unregistered firearms - 2001 attempted arson, Capitola California","arrest_date"=>"2001-01-23","incarceration_date"=>"2001-01-23","convicted"=>"Yes - guilty plea","sentence"=>"14 months federal prison"]]],

    ["name"=>"Jared McIntyre","first_name"=>"Jared","last_name"=>"McIntyre","gender"=>"Male","state"=>"New York","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jared McIntyre, age 17, pleaded guilty in 2001 to one count of arson conspiracy related to ELF-claimed fires set at Long Island home construction sites. Sentenced to 42 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(N) Arson Conspiracy - Long Island ELF-claimed fires at home construction sites","arrest_date"=>"2001-02-09","incarceration_date"=>"2001-02-09","convicted"=>"Yes - guilty plea","sentence"=>"42 months federal prison"]]],

    ["name"=>"George Mashkow","first_name"=>"George","last_name"=>"Mashkow","gender"=>"Male","state"=>"New York","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"George Mashkow, age 17, pleaded guilty in 2001 to one count of arson conspiracy related to ELF-claimed fires at Long Island home construction sites. Sentenced to 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(N) Arson Conspiracy - Long Island ELF-claimed fires","arrest_date"=>"2001-02-14","incarceration_date"=>"2001-02-14","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Matthew Rammelkamp","first_name"=>"Matthew","last_name"=>"Rammelkamp","gender"=>"Male","state"=>"New York","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Matthew Rammelkamp, age 16, pleaded guilty in 2001 to one count of arson conspiracy related to ELF-claimed fires at Long Island home construction sites. Sentenced to 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(N) Arson Conspiracy - Long Island ELF-claimed fires","arrest_date"=>"2001-02-14","incarceration_date"=>"2001-02-14","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    ["name"=>"Jeremy David Rosenbloom","first_name"=>"Jeremy David","last_name"=>"Rosenbloom","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jeremy David Rosenbloom, age 25, was convicted of arson at an Eagle Creek Logging Company in Oregon, where ELF-claimed incendiary devices destroyed a logging truck and front loader causing more than $50,000 in damage. Sentenced to 41 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"Federal violence to interfere with commerce, use of incendiary devices, and obstruction of commodities movement - 2001 Eagle Creek Logging arson","arrest_date"=>"2001-06-01","incarceration_date"=>"2001-06-01","convicted"=>"Yes - guilty plea","sentence"=>"41 months federal prison"]]],

    ["name"=>"Jacob David Bardwell Sherman","first_name"=>"Jacob David","last_name"=>"Sherman","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jacob David Bardwell Sherman, age 20, was convicted of conspiracy to commit arson at the Ross Island Sand & Gravel and the Eagle Creek Oregon logging-company actions. Sentenced to 41 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"Conspiracy to commit arson - 2001 Oregon logging-equipment firebombings","arrest_date"=>"2001-06-01","incarceration_date"=>"2001-06-01","convicted"=>"Yes - guilty plea","sentence"=>"41 months federal prison"]]],

    ["name"=>"Angela Marie Cesario","first_name"=>"Angela","last_name"=>"Cesario","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Angela Marie Cesario, age 23, was convicted of conspiracy to commit arson at the Ross Island Sand & Gravel and Eagle Creek Oregon logging-company actions. Sentenced to 41 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"Conspiracy to commit arson - 2001 Oregon logging-equipment firebombings","arrest_date"=>"2001-06-01","incarceration_date"=>"2001-06-01","convicted"=>"Yes - guilty plea","sentence"=>"41 months federal prison"]]],

    ["name"=>"Ian Wallace","first_name"=>"Ian","last_name"=>"Wallace","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Ian Wallace, age 27, was convicted in 2001 of attempting to cause damage in excess of $1,000 to United States property at Michigan Tech in Houghton, Michigan, in connection with two ELF-claimed incendiary devices that did not detonate. Sentenced to 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Michigan","charges"=>"Attempting to cause damage in excess of $1,000 to property of the United States - 2001 ELF-claimed incendiary devices, Michigan Tech, Houghton","arrest_date"=>"2001-11-05","incarceration_date"=>"2001-11-05","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison"]]],

    ["name"=>"Mark Warren Sands","first_name"=>"Mark Warren","last_name"=>"Sands","gender"=>"Male","race"=>"White","state"=>"Arizona","era"=>"2000s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Mark Warren Sands, age 50, was convicted in 2002 of nine counts of arson and nine counts of use of fire to commit a felony for setting fires to homes built on land near Arizona national preserves. Sentenced to 96 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arizona","charges"=>"Federal arson [9 counts] and use of fire to commit a felony [9 counts] - residential arson protests against home construction near Arizona national preserves","arrest_date"=>"2002-02-11","incarceration_date"=>"2002-02-11","convicted"=>"Yes - guilty plea","sentence"=>"96 months federal prison"]]],

    ["name"=>"Aaron Labe Linas","first_name"=>"Aaron Labe","last_name"=>"Linas","gender"=>"Male","race"=>"White","state"=>"Virginia","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Aaron Labe Linas, age 19, was convicted of conspiracy to damage and destroy property by means of fire and explosives in connection with ELF-claimed actions against suburban-development sites in Richmond, Virginia. Sentenced to 42 months federal prison plus 3 years supervised release and $204,021.86 in restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"Federal conspiracy to damage and destroy property by means of fire and explosives, and aiding and abetting - ELF-claimed Richmond Virginia suburban-development arsons","arrest_date"=>"2002-09-21","incarceration_date"=>"2002-09-21","convicted"=>"Yes - guilty plea","sentence"=>"42 months federal prison + 3 years supervised release + $204,021.86 restitution"]]],

    ["name"=>"Adam Blackwell","first_name"=>"Adam","middle_name"=>"Virden","last_name"=>"Blackwell","gender"=>"Male","state"=>"Virginia","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Adam Virden Blackwell, age 20, was convicted of criminal conspiracy and aiding and abetting in connection with ELF-claimed planned actions against suburban-development sites in Richmond, Virginia. Sentenced to 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"Federal criminal conspiracy and aiding and abetting - ELF-claimed Richmond Virginia suburban-development planning","arrest_date"=>"2002-09-21","incarceration_date"=>"2002-09-21","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison"]]],

    ["name"=>"John Wade","first_name"=>"John","middle_name"=>"B.","last_name"=>"Wade","gender"=>"Male","state"=>"Virginia","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"John B. Wade, age 19, was convicted of criminal conspiracy and aiding and abetting in connection with ELF-claimed planned actions against suburban-development sites in Richmond, Virginia. Sentenced to 37 months federal prison plus 36 months supervised release and $204,021.86 in restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"Federal criminal conspiracy and aiding and abetting - ELF-claimed Richmond Virginia suburban-development planning","arrest_date"=>"2002-09-21","incarceration_date"=>"2002-09-21","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison + 36 months supervised release + $204,021.86 restitution"]]],

    ["name"=>"Robert Brooks","first_name"=>"Robert","last_name"=>"Brooks","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Robert Brooks was convicted in the Eastern District of California for making false statements to a grand jury investigating an ALF-claimed action at a Chico McDonalds in 2003. Sentenced to a $500 fine.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 1623 false declarations before grand jury; 18 USC 1001 making a false statement; criminal contempt - ALF-claimed Chico CA McDonalds 2003 arson investigation","arrest_date"=>"2003-11-05","convicted"=>"Yes - guilty plea","sentence"=>"$500 fine"]]],

    ["name"=>"Hargit Singh Gill","first_name"=>"Hargit Singh","last_name"=>"Gill","gender"=>"Male","race"=>"South Asian","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Hargit Singh Gill, age 22, was convicted in 2003 in the Eastern District of California for making false statements to a grand jury investigating an ALF-claimed action at a Chico McDonalds. Sentenced to 36 months probation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 1623 false declarations before grand jury; 18 USC 1001 making a false statement - ALF-claimed Chico CA McDonalds 2003 arson investigation","arrest_date"=>"2003-11-05","convicted"=>"Yes - guilty plea","sentence"=>"36 months probation"]]],

    ["name"=>"Christopher Kyle Salmon","first_name"=>"Christopher Kyle","last_name"=>"Salmon","gender"=>"Male","state"=>"Virginia","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Christopher Kyle Salmon was convicted of attempted arson in connection with the January 2004 ELF-claimed Molotov-cocktail attack on a Ford dealership in Henrico County, Virginia. Sentenced to 24 months federal prison plus 2 years probation and $500 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"Federal criminal conspiracy and aiding and abetting - 2004 ELF-claimed Molotov-cocktail attack on Henrico County Ford dealership","arrest_date"=>"2004-01-19","incarceration_date"=>"2004-01-19","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison + 2 years probation + $500 restitution"]]],

    ["name"=>"Timothy Ryan Kennedy","first_name"=>"Timothy Ryan","last_name"=>"Kennedy","gender"=>"Male","state"=>"Virginia","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Timothy Ryan Kennedy was convicted of attempted arson in connection with the January 2004 ELF-claimed Molotov-cocktail attack on a Ford dealership in Henrico County, Virginia. Sentenced to 25 months federal prison plus 2 years probation and $500 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"Federal criminal conspiracy - 2004 ELF-claimed Molotov-cocktail attack on Henrico County Ford dealership","arrest_date"=>"2004-01-19","incarceration_date"=>"2004-01-19","convicted"=>"Yes - guilty plea","sentence"=>"25 months federal prison + 2 years probation + $500 restitution"]]],

    ["name"=>"Harrison David Burrows","first_name"=>"Harrison David","last_name"=>"Burrows","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Harrison David Burrows, age 18, pleaded guilty to setting fire to a Brigham Young University animal-husbandry facility on behalf of the ALF in 2004. Sentenced to 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal destruction of property by fire and aiding and abetting - 2004 BYU animal-husbandry facility arson","arrest_date"=>"2004-07-28","incarceration_date"=>"2004-07-28","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],

    ["name"=>"Joshua Stephen Demmitt","first_name"=>"Joshua Stephen","last_name"=>"Demmitt","gender"=>"Male","state"=>"Utah","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Joshua Stephen Demmitt, age 18, pleaded guilty to setting fire to a Brigham Young University animal-husbandry facility on behalf of the ALF in 2004. Sentenced to 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal destruction of property by fire and aiding and abetting - 2004 BYU animal-husbandry facility arson","arrest_date"=>"2004-07-28","incarceration_date"=>"2004-07-28","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],

    ["name"=>"Christopher W. McIntosh","first_name"=>"Christopher","last_name"=>"McIntosh","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2000s","ideologies"=>["Animal Rights Activism","Environmental Activism"],"affiliation"=>["Animal Liberation Front","Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Christopher W. McIntosh, age 23, pleaded guilty to a 2003 ELF-/ALF-claimed arson on the roof of a McDonalds across from the Space Needle in Seattle. Sentenced to 96 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"Federal arson - January 2003 ELF/ALF-claimed Seattle McDonalds rooftop fire","arrest_date"=>"2005-04-06","incarceration_date"=>"2005-04-06","convicted"=>"Yes - guilty plea","sentence"=>"96 months federal prison + 36 months supervised release"]]],

    ["name"=>"Ryan Daniel Lewis","first_name"=>"Ryan Daniel","last_name"=>"Lewis","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Ryan Daniel Lewis, age 21, was convicted of conspiracy and attempted arson in connection with the December 2004 ELF-claimed firebombing attempts at Lincoln and Auburn, California housing developments. Sentenced to 72 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal conspiracy to commit arson and attempted arson - 2004 ELF-claimed firebombing attempts at Lincoln and Auburn California housing developments","arrest_date"=>"2005-05-10","incarceration_date"=>"2005-05-10","convicted"=>"Yes - guilty plea","sentence"=>"72 months federal prison"]]],

    ["name"=>"Lili Marie Holland","first_name"=>"Lili Marie","last_name"=>"Holland","gender"=>"Female","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Lili Marie Holland, age 20, was convicted of conspiracy and attempted arson in connection with the December 2004 ELF-claimed firebombing attempts at Lincoln and Auburn, California housing developments. Sentenced to 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal conspiracy to commit arson and attempted arson - 2004 ELF-claimed firebombing attempts at Lincoln and Auburn California housing developments","arrest_date"=>"2005-05-10","incarceration_date"=>"2005-05-10","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Eva Rose Holland","first_name"=>"Eva Rose","last_name"=>"Holland","gender"=>"Female","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Eva Rose Holland, age 25, was convicted of conspiracy and attempted arson in connection with the December 2004 ELF-claimed firebombing attempts at Lincoln and Auburn, California housing developments. Sentenced to 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal conspiracy to commit arson and attempted arson - 2004 ELF-claimed firebombing attempts at Lincoln and Auburn California housing developments","arrest_date"=>"2005-05-10","incarceration_date"=>"2005-05-10","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Jeremiah Dean Colcleasure","first_name"=>"Jeremiah Dean","last_name"=>"Colcleasure","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jeremiah Dean Colcleasure, age 24, was convicted of conspiracy and attempted arson in connection with the December 2004 ELF-claimed firebombing attempts at Lincoln and Auburn, California housing developments. Sentenced to 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal conspiracy to commit arson and attempted arson - 2004 ELF-claimed firebombing attempts at Lincoln and Auburn California housing developments","arrest_date"=>"2005-05-10","incarceration_date"=>"2005-05-10","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Matthew Crozier","first_name"=>"Matthew","last_name"=>"Crozier","gender"=>"Male","state"=>"Arizona","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth First!"],"in_custody"=>false,"released"=>true,"description"=>"Matthew Crozier, an Esquire Magazine writer, was charged with Rod Coronado in 2005 for entering Sabino Canyon outside Tucson, Arizona to disable mountain-lion traps the Arizona Game and Fish Department had set. Sentenced to time served, 3 years probation, $1,000 fine, and 100 hours community service.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arizona","charges"=>"Federal misdemeanor counts of interfering with a forest officer and depredation of government property; felony conspiracy to impede or injure an officer of the United States - 2004 Sabino Canyon mountain-lion-trap disabling","arrest_date"=>"2005-12-13","convicted"=>"Yes - federal jury verdict","sentence"=>"Time served + 3 years probation + $1,000 fine + 100 hours community service"]]],

    ["name"=>"Steven James Murphy","first_name"=>"Steven James","last_name"=>"Murphy","gender"=>"Male","state"=>"California","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Steven James Murphy, age 43, was charged in 2009 with attempted arson, possession of an unregistered destructive device, and conspiracy to commit arson for a 2006 attempted ELF-claimed firebombing of unfinished townhomes in Pasadena, California. Sentenced to 60 months federal prison plus 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"Federal conspiracy to commit arson, attempted arson, and possession of an unregistered destructive device - 2006 ELF-claimed Pasadena townhouse construction-site attempted firebombing","arrest_date"=>"2009-10-16","incarceration_date"=>"2009-10-16","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison + 3 years supervised release"]]],

    ["name"=>"Aaron Ellringer","first_name"=>"Aaron","last_name"=>"Ellringer","gender"=>"Male","race"=>"White","state"=>"Wisconsin","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Aaron Ellringer, age 35, pleaded guilty to a misdemeanor for his limited role in the 2009 ELF-claimed sabotage of US Forest Service tree-genetics research property near Rhinelander, Wisconsin.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"Federal conspiracy and aiding and abetting destruction of government property - 2009 ELF-claimed Rhinelander WI Forest Service tree-genetics research vandalism","arrest_date"=>"2009-07-17","convicted"=>"Yes - guilty plea (misdemeanor)","sentence"=>"Misdemeanor sentence"]]],

    ["name"=>"Bryan Rivera","first_name"=>"Bryan","last_name"=>"Rivera","gender"=>"Male","race"=>"White","state"=>"Wisconsin","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Bryan Rivera, age 27, pleaded guilty to conspiracy and aiding and abetting in the 2009 ELF-claimed sabotage of US Forest Service tree-genetics research property near Rhinelander, Wisconsin. Sentenced to 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"Federal conspiracy and aiding and abetting destruction of government property - 2009 ELF-claimed Rhinelander WI Forest Service tree-genetics research vandalism","arrest_date"=>"2009-07-17","incarceration_date"=>"2009-07-17","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison"]]],

    ["name"=>"Katherine Christianson","first_name"=>"Katherine","last_name"=>"Christianson","gender"=>"Female","race"=>"White","state"=>"Wisconsin","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Katherine Christianson, age 27, pleaded guilty to conspiracy and aiding and abetting in the 2009 ELF-claimed sabotage of US Forest Service tree-genetics research property near Rhinelander, Wisconsin. Sentenced to 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"Federal conspiracy and aiding and abetting destruction of government property - 2009 ELF-claimed Rhinelander WI Forest Service tree-genetics research vandalism","arrest_date"=>"2009-07-17","incarceration_date"=>"2009-07-17","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Alex Jason Hall","first_name"=>"Alex Jason","last_name"=>"Hall","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Alex Jason Hall, age 22, pleaded guilty to AETA charges for the 2009 release of approximately 650 mink from a fur farm in South Jordan, Utah, and the destruction of breeding records and ranch buildings. Sentenced to 21 months federal prison plus $66,753 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal damage and interference with animal enterprises (AETA) - 2009 South Jordan UT mink-farm raid","arrest_date"=>"2009-03-04","incarceration_date"=>"2009-03-04","convicted"=>"Yes - guilty plea","sentence"=>"21 months federal prison + $66,753 restitution"]]],

    ["name"=>"William James Viehl","first_name"=>"William James","last_name"=>"Viehl","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"William James Viehl, age 23, pleaded guilty to AETA charges for the 2009 release of approximately 650 mink from a fur farm in South Jordan, Utah. Sentenced to 24 months federal prison plus $66,753 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal damage and interference with animal enterprises (AETA) - 2009 South Jordan UT mink-farm raid","arrest_date"=>"2009-03-04","incarceration_date"=>"2009-03-04","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison + $66,753 restitution"]]],

    ["name"=>"Linda Faith Greene","first_name"=>"Linda Faith","last_name"=>"Greene","gender"=>"Female","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Linda Faith Greene, age 61, was indicted in 2009 for stalking and conspiracy to threaten UCLA scientists involved in animal research. Plea agreement: five years formal probation; she acknowledged being the press officer for the North American Animal Liberation Press Office.","cases"=>[["institution_name"=>"California state probation supervision","institution_state"=>"California","charges"=>"California Penal Code 646.9(a) stalking [3 counts]; 182(a)(1) conspiracy to commit a crime [5 counts]; 71 threatening a public officer or school employee [2 counts]","arrest_date"=>"2009-03-27","convicted"=>"Yes - plea agreement","sentence"=>"5 years formal probation"]]],

    ["name"=>"Gina Eleyna Wertz","first_name"=>"Gina Eleyna","last_name"=>"Wertz","aka"=>"Tiga","gender"=>"Female","race"=>"White","state"=>"Indiana","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Roadblock Earth First!"],"in_custody"=>false,"released"=>true,"description"=>"Gina Eleyna Wertz, age 24, was indicted in 2009 with four misdemeanor counts (intimidation and conversion) plus one Class C felony for involvement in protests against the I-69 highway expansion in Indiana, including tree-sits and office takeovers. The judge dismissed the felony racketeering charge in March 2010; her plea bargain was unsupervised probation for two years.","cases"=>[["institution_name"=>"Indiana state probation supervision","institution_state"=>"Indiana","charges"=>"IC 35-45-2-1 intimidation [2 counts]; 35-43-4-3 conversion [2 counts]; 35-45-6-2 (Class C felony, dismissed) - I-69 tree-sits and office takeovers","arrest_date"=>"2009-04-20","convicted"=>"Yes - plea bargain (felony dismissed)","sentence"=>"2 years unsupervised probation"]]],

    ["name"=>"Hugh F. Farrell","first_name"=>"Hugh","last_name"=>"Farrell","gender"=>"Male","race"=>"White","state"=>"Indiana","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Roadblock Earth First!"],"in_custody"=>false,"released"=>true,"description"=>"Hugh F. Farrell, age 23, was indicted in 2009 with four misdemeanor counts (intimidation and conversion) plus one Class C felony for involvement in protests against the I-69 highway expansion in Indiana. The judge dismissed the felony racketeering charge in March 2010; his plea bargain was unsupervised probation for two years.","cases"=>[["institution_name"=>"Indiana state probation supervision","institution_state"=>"Indiana","charges"=>"IC 35-45-2-1 intimidation [2 counts]; 35-43-4-3 conversion [2 counts]; 35-45-6-2 (Class C felony, dismissed) - I-69 tree-sits and office takeovers","arrest_date"=>"2009-04-20","convicted"=>"Yes - plea bargain (felony dismissed)","sentence"=>"2 years unsupervised probation"]]],

    ["name"=>"Adam Troy Peace","first_name"=>"Adam Troy","last_name"=>"Peace","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Adam Troy Peace, age 20, was indicted in 1998 alongside the Ellerman brothers for the 1997 pipe-bombing of the Fur Breeders Agricultural Cooperative offices in Sandy, Utah. He was acquitted at trial.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal explosives charges - 1997 Fur Breeders Agricultural Cooperative pipe-bombing","arrest_date"=>"1998-09-10","convicted"=>"No - acquitted by jury","sentence"=>"Acquitted"]]],

    ["name"=>"Sean Albert Gautschy","first_name"=>"Sean Albert","last_name"=>"Gautschy","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Sean Albert Gautschy, age 23, was indicted in 1998 alongside the Ellerman brothers for the 1997 pipe-bombing of the Fur Breeders Agricultural Cooperative offices in Sandy, Utah. He was acquitted at trial.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal explosives charges - 1997 Fur Breeders Agricultural Cooperative pipe-bombing","arrest_date"=>"1998-09-10","convicted"=>"No - acquitted by jury","sentence"=>"Acquitted"]]],

    ["name"=>"Andrew N. Bishop","first_name"=>"Andrew","middle_name"=>"N.","last_name"=>"Bishop","gender"=>"Male","state"=>"Utah","era"=>"1990s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Andrew N. Bishop, age 24, was indicted in 1998 alongside the Ellerman brothers for the 1997 pipe-bombing of the Fur Breeders Agricultural Cooperative offices in Sandy, Utah. He was acquitted at trial.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"Federal explosives charges - 1997 Fur Breeders Agricultural Cooperative pipe-bombing","arrest_date"=>"1998-09-10","convicted"=>"No - acquitted by jury","sentence"=>"Acquitted"]]],

    ["name"=>"Connor Cash","first_name"=>"Connor","last_name"=>"Cash","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Connor Cash, age 19, was indicted in 2001 for arson, arson conspiracy, and providing material support for terrorists in connection with the Long Island ELF-claimed home-construction-site fires. He was acquitted of all charges at trial.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 844(N) Arson Conspiracy and providing material support for terrorists - 2001 Long Island ELF-claimed fires","arrest_date"=>"2001-02-15","convicted"=>"No - acquitted by jury","sentence"=>"Acquitted of all charges"]]],

    ["name"=>"Nathan Pope","first_name"=>"Nathan","last_name"=>"Pope","aka"=>"Nathan Knoerl","gender"=>"Male","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Nathan Pope, age 26, was one of the AETA 4 - four young people indicted in 2009 under the Animal Enterprise Terrorism Act for protest activity targeting University of California researchers. The indictment was dismissed by the court for failing to specify the conduct.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 371 conspiracy and 18 USC 43 Animal Enterprise Terrorism Act - AETA 4 prosecution","arrest_date"=>"2009-02-20","convicted"=>"No - indictment dismissed","sentence"=>"Indictment dismissed"]]],

    ["name"=>"Maryam Khajavi","first_name"=>"Maryam","last_name"=>"Khajavi","gender"=>"Female","race"=>"Middle Eastern/North African","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Maryam Khajavi, age 20, was one of the AETA 4 - four young people indicted in 2009 under the Animal Enterprise Terrorism Act. The indictment was dismissed by the court for failing to specify the conduct.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 371 conspiracy and 18 USC 43 Animal Enterprise Terrorism Act - AETA 4 prosecution","arrest_date"=>"2009-02-20","convicted"=>"No - indictment dismissed","sentence"=>"Indictment dismissed"]]],

    ["name"=>"Adriana Stumpo","first_name"=>"Adriana","last_name"=>"Stumpo","gender"=>"Female","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Adriana Stumpo, age 23, was one of the AETA 4 - four young people indicted in 2009 under the Animal Enterprise Terrorism Act. The indictment was dismissed by the court for failing to specify the conduct.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 371 conspiracy and 18 USC 43 Animal Enterprise Terrorism Act - AETA 4 prosecution","arrest_date"=>"2009-02-20","convicted"=>"No - indictment dismissed","sentence"=>"Indictment dismissed"]]],

    ["name"=>"Jacob Jeremiah Ferguson","first_name"=>"Jacob Jeremiah","last_name"=>"Ferguson","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front","Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jacob Jeremiah Ferguson was the federal informant whose cooperation drove Operation Backfire, the multi-agency federal investigation that prosecuted the Eugene-area ELF/ALF cell known as The Family. Ferguson cooperated with prosecutors in exchange for probation and avoiding prison time.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"Federal Operation Backfire arson conspiracy - cooperator","arrest_date"=>"2004-09-07","convicted"=>"Yes - cooperator","sentence"=>"Probation; avoided prison via cooperation"]]],

    ["name"=>"Josephine Sunshine Overaker","first_name"=>"Josephine Sunshine","last_name"=>"Overaker","aka"=>"Maria, Lisa Quintana, Osha, Jo, China, Josie, Mo","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2000s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front","Animal Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Josephine Sunshine Overaker was indicted in the Operation Backfire ELF/ALF prosecution. She remains a fugitive and is on the FBI Most Wanted Domestic Terrorists list.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Oregon","charges"=>"Federal Operation Backfire arson conspiracy charges including conspiracy to commit arson and destruction of an energy facility, attempted arson, and arson [5 counts]","arrest_date"=>"2011-01-26","convicted"=>"No - fugitive","sentence"=>"Fugitive at large since 2006"]]],
];

$created = 0; $existing = 0; $skipped = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }

    $cases = $row["cases"] ?? [];
    unset($row["cases"]);

    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $skipped++;
        continue;
    }

    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);

        $instAttrs = ["name" => $instName];
        $instExtra = array_filter([
            "city"  => $instCity,
            "state" => $instState,
        ]);

        $inst = App\Models\Institution::firstOrCreate($instAttrs, $instExtra);

        $c["prisoner_id"]    = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }

    echo "CREATED: {$name}\n";
    $created++;
}

echo "\nSummary: created={$created}, already existing={$existing}, skipped/errors={$skipped}\n";
'

echo
echo "Prosecution Project eco/animal rows import complete."
