#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_2.sh
#
# Second batch (rows 101-200) of the editor-supplied Prosecution
# Project eco/animal-rights subset. Same idempotent semantics as
# the first batch import: create-if-missing, skip-if-exists.
#
# Skipped because already in the database (and reported EXISTS:
# at runtime): Justin Franchi Solondz, Nicole Kissane, Joseph
# Buddenberg, Ruby Montoya, Kevin Olliff (= Kevin Johnson alias),
# Wayne Hsiung (Sonoma open-rescue record). Backfill of fields on
# those existing records is in update_existing_from_tpp_2.sh.
#
# The Greenpeace 28 federal/state entries collapse to single
# prisoner records with combined charge text; only one record
# per individual is created.
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"David P. Agranoff","first_name"=>"David","last_name"=>"Agranoff","gender"=>"Male","race"=>"White","state"=>"Indiana","era"=>"2010s","ideologies"=>["Animal Rights Activism","Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"David P. Agranoff, age 31, was charged in 2011 with arson related to a 2000 ELF-claimed action at a Bloomington, Indiana poultry plant. Pleaded down to misprision of a felony and reportedly turned FBI informant; sentenced to 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Indiana","charges"=>"Federal arson and misprision of a felony - 2000 ELF-claimed Bloomington Indiana poultry-plant action","arrest_date"=>"2011-03-22","incarceration_date"=>"2011-03-22","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Jesse William Waters","first_name"=>"Jesse William","last_name"=>"Waters","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Jesse William Waters, age 30, was indicted in 2011 for his role in 1999 New Years Eve Michigan State University Agriculture Hall arson, working with Marie/Marius Mason and Frank Ambrose. Pleaded guilty to misprision; 6 months federal prison plus 1 year supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Michigan","charges"=>"18 USC 844(n) conspiracy to commit arson; 18 USC 844(i) arson; 18 USC 4 misprision of a felony - 1999 ELF-claimed Michigan State University Agriculture Hall arson","arrest_date"=>"2011-09-26","incarceration_date"=>"2011-09-26","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison + 1 year supervised release"]]],

    ["name"=>"David Eli Baghdadi","first_name"=>"David Eli","last_name"=>"Baghdadi","gender"=>"Male","state"=>"West Virginia","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Radical Action for Mountain Peoples Survival"],"in_custody"=>false,"released"=>true,"description"=>"David Eli Baghdadi, age 36, was arrested August 21, 2013 after strapping himself to a barrel of slurry outside the West Virginia governors mansion to protest coal-slurry pollution in Appalachia. Charged with trespassing and obstruction; case dispositions not publicly tracked.","cases"=>[["institution_name"=>"West Virginia state custody","institution_state"=>"West Virginia","charges"=>"West Virginia trespassing and obstruction - 2013 coal-slurry barrel protest at the West Virginia governors mansion","arrest_date"=>"2013-08-21","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Liam Mulholland","first_name"=>"Liam","last_name"=>"Mulholland","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Earth Liberation Front"],"in_custody"=>false,"released"=>true,"description"=>"Liam Mulholland, age 18 at indictment, pleaded guilty in 2013 to 18 USC 844(i) arson involving interstate commerce for a 2003 ELF-claimed firebombing of a Mystic Forest housing-development home in Ann Arbor, Michigan. Cooperated with the FBI; received 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Michigan","charges"=>"18 USC 844(i) arson involving interstate commerce - 2003 ELF-claimed Ann Arbor Mystic Forest housing-development arson","arrest_date"=>"2013-11-21","incarceration_date"=>"2013-11-21","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    ["name"=>"Barbara Carter","first_name"=>"Barbara","last_name"=>"Carter","aka"=>"Barb","gender"=>"Female","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Michigan Coalition Against Tar Sands"],"in_custody"=>false,"released"=>true,"description"=>"Barbara Carter, age 22, was one of three women who chained themselves to heavy machinery at an Enbridge pipeline worksite near Stockbridge, Michigan in July 2013 to oppose expansion of the pipeline that ruptured into the Kalamazoo River in 2010. Convicted of misdemeanor trespassing and felony obstruction; 13 months probation plus $750 fine. Necessity defense raised.","cases"=>[["institution_name"=>"Michigan state probation supervision","institution_state"=>"Michigan","charges"=>"MCL 750.479 resisting or obstructing officer; 750.552 trespass - 2013 Stockbridge MI Enbridge tar-sands pipeline blockade","arrest_date"=>"2013-07-22","convicted"=>"Yes - jury verdict","sentence"=>"13 months probation + $750 fine + time served"]]],

    ["name"=>"Lisa Leggio","first_name"=>"Lisa","last_name"=>"Leggio","gender"=>"Female","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Michigan Coalition Against Tar Sands"],"in_custody"=>false,"released"=>true,"description"=>"Lisa Leggio, age 35, was one of three women who chained themselves to heavy machinery at an Enbridge pipeline worksite near Stockbridge, Michigan in July 2013. Convicted of misdemeanor trespassing and felony obstruction; 13 months probation plus $750 fine.","cases"=>[["institution_name"=>"Michigan state probation supervision","institution_state"=>"Michigan","charges"=>"MCL 750.479 resisting or obstructing officer; 750.552 trespass - 2013 Stockbridge MI Enbridge tar-sands pipeline blockade","arrest_date"=>"2013-07-22","convicted"=>"Yes - jury verdict","sentence"=>"13 months probation + $750 fine + time served"]]],

    ["name"=>"Vicci Hamlin","first_name"=>"Vicci","last_name"=>"Hamlin","gender"=>"Female","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Michigan Coalition Against Tar Sands"],"in_custody"=>false,"released"=>true,"description"=>"Vicci Hamlin, age 60, was one of three women who chained themselves to heavy machinery at an Enbridge pipeline worksite near Stockbridge, Michigan in July 2013. Convicted of misdemeanor trespassing and felony obstruction; 13 months probation plus $750 fine.","cases"=>[["institution_name"=>"Michigan state probation supervision","institution_state"=>"Michigan","charges"=>"MCL 750.479 resisting or obstructing officer; 750.552 trespass - 2013 Stockbridge MI Enbridge tar-sands pipeline blockade","arrest_date"=>"2013-07-22","convicted"=>"Yes - jury verdict","sentence"=>"13 months probation + $750 fine + time served"]]],

    ["name"=>"Tyler Lang","first_name"=>"Tyler","last_name"=>"Lang","gender"=>"Male","race"=>"White","state"=>"Illinois","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Tyler Lang, age 27, was indicted in 2014 with Kevin Olliff (alias Kevin Johnson) under the Animal Enterprise Terrorism Act for the 2013 release of approximately 2,000 mink from a Morris, Illinois mink farm. Convicted; 3 months federal prison plus $200,000 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"18 USC 43 force, violence, and threats involving animal enterprises (AETA) [2 counts] - 2013 Morris IL mink-farm release of approximately 2,000 mink","arrest_date"=>"2014-07-08","incarceration_date"=>"2014-07-08","convicted"=>"Yes - guilty plea","sentence"=>"3 months federal prison + $200,000 restitution"]]],

    ["name"=>"Kenneth Ward","first_name"=>"Kenneth","last_name"=>"Ward","aka"=>"Ken","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["350.org","#ShutItDown"],"in_custody"=>false,"released"=>true,"description"=>"Kenneth (Ken) Ward, age 60, was a defendant in two notable climate-resistance cases. In May 2013 he and Jay O Hara blockaded the Brayton Point Shipping Channel in Somerset, Massachusetts with a small lobster boat, preventing 40,000 tons of coal from reaching the power plant; the district attorney dropped the charges before trial in exchange for $2,000 restitution each and gave a public speech in support of climate action. On October 11, 2016 Ward broke into a Trans Mountain Pipeline emergency-valve site in Burlington, Washington and shut off the pipeline as part of #ShutItDown; his Washington state trial saw a hung jury on sabotage and a conviction on second-degree burglary.","cases"=>[["institution_name"=>"Skagit County Jail","institution_city"=>"Mount Vernon","institution_state"=>"Washington","charges"=>"Washington state second-degree burglary and criminal sabotage - October 2016 Trans Mountain Pipeline #ShutItDown valve-shutoff in Burlington WA","arrest_date"=>"2016-10-11","convicted"=>"Yes - hung jury on sabotage; convicted of burglary","sentence"=>"Convicted of burglary; necessity defense denied; appeal accepted"]]],

    ["name"=>"Jay O Hara","first_name"=>"Jay","last_name"=>"O Hara","aka"=>"James O Hara","gender"=>"Male","race"=>"White","state"=>"Massachusetts","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["350.org","Coal Is Stupid"],"in_custody"=>false,"released"=>true,"description"=>"Jay (James) O Hara, age 32, a Quaker climate activist, was charged with Kenneth Ward in May 2013 for blockading the Brayton Point Shipping Channel near Somerset, Massachusetts with a small lobster boat to prevent 40,000 tons of coal from reaching the power plant. The district attorney dropped the charges before trial in exchange for $2,000 restitution each and gave a public speech supporting climate action.","cases"=>[["institution_name"=>"Bristol County District Court","institution_city"=>"Fall River","institution_state"=>"Massachusetts","charges"=>"Mass. G.L. c. 272:53 disturbing the peace; 274:7 conspiracy; 90:24 failure to act to avoid a collision; 90:24(2)(a) negligent operation of a motor vehicle - May 2013 lobster-boat blockade of the Brayton Point coal shipping channel","arrest_date"=>"2013-05-15","convicted"=>"No - charges dropped","sentence"=>"Charges dropped; $2,000 restitution"]]],

    ["name"=>"Stephen Plato McRae","first_name"=>"Stephen Plato","last_name"=>"McRae","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Stephen Plato McRae, age 59, was sentenced to 96 months federal prison after firing shots at the Buckskin Electrical Substation near Kanab, Utah on September 25, 2016. McRae told a confidential informant he was trying to destroy industrial capitalism and inflict massive damage on the fossil-fuel industry. Plea agreement also covered three additional substation shootings in San Juan County UT, Humboldt County NV, and White Pine County NV during 2015-2016.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Utah","charges"=>"18 USC 1366(a) destruction of an energy facility; 18 USC 922(g)(1) possession of a firearm/ammunition by a restricted person; 21 USC 844(a) possession of a controlled substance - 2015-2016 western-states electrical-substation shooting attacks","arrest_date"=>"2016-09-25","incarceration_date"=>"2016-09-25","convicted"=>"Yes - guilty plea","sentence"=>"96 months federal prison + 36 months supervised release + mental health treatment"]]],

    ["name"=>"Emily Nesbitt Johnston","first_name"=>"Emily","middle_name"=>"Nesbitt","last_name"=>"Johnston","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["#ShutItDown"],"in_custody"=>false,"released"=>true,"description"=>"Emily Nesbitt Johnston, age 52, was one of four defendants charged in connection with the October 11, 2016 #ShutItDown action that cut chains around the Enbridge pipeline near Leonard, Minnesota and attempted to turn off the valves. Necessity defense raised; case dismissed.","cases"=>[["institution_name"=>"Clearwater County District Court","institution_city"=>"Bagley","institution_state"=>"Minnesota","charges"=>"Minn. Stat. 609.595, 609.594, 609.6055 criminal damage and trespass on critical public-service facility/utility/pipeline - October 2016 #ShutItDown Enbridge valve action, Leonard MN","arrest_date"=>"2016-10-11","convicted"=>"No - case dismissed","sentence"=>"Case dismissed; necessity defense accepted in court"]]],

    ["name"=>"Annette Marie Klapstein","first_name"=>"Annette","middle_name"=>"Marie","last_name"=>"Klapstein","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["#ShutItDown"],"in_custody"=>false,"released"=>true,"description"=>"Annette Marie Klapstein, age 66, was one of four defendants charged in connection with the October 11, 2016 #ShutItDown action that cut chains around the Enbridge pipeline near Leonard, Minnesota. Necessity defense raised; case dismissed.","cases"=>[["institution_name"=>"Clearwater County District Court","institution_city"=>"Bagley","institution_state"=>"Minnesota","charges"=>"Minn. Stat. 609.595, 609.594, 609.6055 criminal damage and trespass on critical public-service facility/utility/pipeline - October 2016 #ShutItDown Enbridge valve action, Leonard MN","arrest_date"=>"2016-10-11","convicted"=>"No - case dismissed","sentence"=>"Case dismissed"]]],

    ["name"=>"Benjamin Gary Joldersma","first_name"=>"Benjamin","middle_name"=>"Gary","last_name"=>"Joldersma","aka"=>"Ben","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["#ShutItDown"],"in_custody"=>false,"released"=>true,"description"=>"Benjamin Gary Joldersma, age 40, called a warning into Enbridge during the October 11, 2016 #ShutItDown action at the Leonard, Minnesota Enbridge pipeline valve. Charged with criminal damage and trespass on a critical public-service pipeline. Necessity defense raised; case dismissed.","cases"=>[["institution_name"=>"Clearwater County District Court","institution_city"=>"Bagley","institution_state"=>"Minnesota","charges"=>"Minn. Stat. 609.595, 609.594, 609.6055 criminal damage and trespass on critical public-service facility/utility/pipeline - October 2016 #ShutItDown Enbridge valve action, Leonard MN","arrest_date"=>"2016-10-11","convicted"=>"No - case dismissed","sentence"=>"Case dismissed"]]],

    ["name"=>"Steven Robert Liptay","first_name"=>"Steven","middle_name"=>"Robert","last_name"=>"Liptay","gender"=>"Male","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["#ShutItDown"],"in_custody"=>false,"released"=>true,"description"=>"Steven Robert Liptay, age 37, filmed the October 11, 2016 #ShutItDown action at the Leonard, Minnesota Enbridge pipeline valve. Charged with criminal damage and trespass on a critical public-service pipeline. Necessity defense raised; case dismissed.","cases"=>[["institution_name"=>"Clearwater County District Court","institution_city"=>"Bagley","institution_state"=>"Minnesota","charges"=>"Minn. Stat. 609.595, 609.594, 609.6055 criminal damage and trespass on critical public-service facility/utility/pipeline - October 2016 #ShutItDown Enbridge valve action, Leonard MN","arrest_date"=>"2016-10-11","convicted"=>"No - case dismissed","sentence"=>"Case dismissed"]]],

    ["name"=>"Michael Markus","first_name"=>"Michael","middle_name"=>"Mateo","last_name"=>"Markus","aka"=>"Rattler, Mato Tanka","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Michael Mateo Markus (Rattler), former US Marine Corps, age 45, was one of five Standing Rock NoDAPL Water Protectors federally charged for setting fire to a barricade on Backwater Bridge to delay law enforcement reaching the protest camp. Sentenced to 36 months federal prison plus 2 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 844(h) use of fire to commit a federal felony - October 27, 2016 Backwater Bridge barricade fire, NoDAPL Standing Rock","arrest_date"=>"2017-03-01","incarceration_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison + 2 years supervised release + $100 special assessment"]]],

    ["name"=>"Michael Giron","first_name"=>"Michael","last_name"=>"Giron","aka"=>"Little Feather","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Michael (Little Feather) Giron, age 45, was one of five Standing Rock NoDAPL Water Protectors federally charged in connection with the October 27, 2016 Backwater Bridge barricade fire. Sentenced to 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 844(h) and 18 USC 2 arson by aiding and abetting - October 27, 2016 Backwater Bridge barricade fire, NoDAPL Standing Rock","arrest_date"=>"2017-03-01","incarceration_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison"]]],

    ["name"=>"Vanessa Castle","first_name"=>"Vanessa","last_name"=>"Castle","gender"=>"Female","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Vanessa Castle, age 28, was charged with felony inciting a riot and misdemeanor criminal trespass for participating in the Dakota Access Pipeline NoDAPL camp. Case dispositions not publicly tracked.","cases"=>[["institution_name"=>"Morton County District Court","institution_city"=>"Mandan","institution_state"=>"North Dakota","charges"=>"18 USC 2101 inciting a riot - NoDAPL Standing Rock camp action","arrest_date"=>"2017-02-02","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Chase Iron Eyes","first_name"=>"Chase","middle_name"=>"A.","last_name"=>"Iron Eyes","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Chase A. Iron Eyes, age 39, was charged with felony inciting a riot and misdemeanor criminal trespass for erecting a NoDAPL camp on pipeline land in southern Morton County, North Dakota in early 2017. The felony was dropped to a misdemeanor disorderly conduct under a deferred-imposition plea: 12-month deferred imposition plus $1,500 fine; case to be removed from his record after compliance.","cases"=>[["institution_name"=>"Morton County District Court","institution_city"=>"Mandan","institution_state"=>"North Dakota","charges"=>"Inciting a riot (reduced to misdemeanor disorderly conduct) - NoDAPL Standing Rock camp on pipeline land","arrest_date"=>"2017-02-01","convicted"=>"Yes - plea agreement","sentence"=>"12 months deferred imposition + $1,500 fine"]]],

    ["name"=>"Brennon J. Nastacio","first_name"=>"Brennon","last_name"=>"Nastacio","aka"=>"Bravo One","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Brennon J. Nastacio (Bravo One), age 36, was one of five Standing Rock NoDAPL Water Protectors federally charged in connection with the October 27, 2016 Backwater Bridge barricade fire. Held in pretrial custody from February 13, 2017 until judgment September 28, 2020; sentenced to 43 months credited as time served plus 18 months supervised release, 100 hours community service, and $100 special assessment.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder [2 counts]; 18 USC 844(h) use of fire to commit a federal felony [2 counts] - October 27, 2016 Backwater Bridge barricade fire","arrest_date"=>"2017-02-13","incarceration_date"=>"2017-02-13","sentenced_date"=>"2020-09-28","release_date"=>"2020-09-28","convicted"=>"Yes - guilty plea","sentence"=>"43 months credited as time served + 18 months supervised release + 100 hours community service"]]],

    ["name"=>"James White","first_name"=>"James","last_name"=>"White","aka"=>"Angry Bird","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"James (Angry Bird) White was one of five Standing Rock NoDAPL Water Protectors federally charged in connection with the October 27, 2016 Backwater Bridge barricade fire. Sentenced to time served plus 12-month period of home confinement and 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 844(h) use of fire to commit a federal felony - October 27, 2016 Backwater Bridge barricade fire","arrest_date"=>"2017-03-01","incarceration_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"Time served + 12 months home confinement + 3 years supervised release"]]],

    ["name"=>"Brandon Aaron Miller-Castillo","first_name"=>"Brandon","middle_name"=>"Aaron","last_name"=>"Miller-Castillo","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Brandon Aaron Miller-Castillo, age 22, was one of five Standing Rock NoDAPL Water Protectors federally charged in connection with the October 27, 2016 Backwater Bridge barricade fire. Charged but not tried.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 844(h) use of fire to commit a federal felony - October 27, 2016 Backwater Bridge barricade fire","arrest_date"=>"2017-03-01","convicted"=>"No - charged but not tried","sentence"=>"Charged but not tried"]]],

    ["name"=>"Dion Ortiz","first_name"=>"Dion","last_name"=>"Ortiz","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Dion Ortiz, age 20, was one of five Standing Rock NoDAPL Water Protectors federally charged in connection with the October 27, 2016 Backwater Bridge barricade fire. Sentenced to 16 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 844(h) use of fire to commit a federal felony - October 27, 2016 Backwater Bridge barricade fire","arrest_date"=>"2017-03-01","incarceration_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"16 months federal prison"]]],

    ["name"=>"Andrew Sharo","first_name"=>"Andrew","last_name"=>"Sharo","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Direct Action Everywhere"],"in_custody"=>false,"released"=>true,"description"=>"Andrew Sharo, age 24, was charged in 2018 in two Utah cases brought by State prosecutors against Direct Action Everywhere (DxE) open-rescue actions: a Manti turkey-farm investigation and a Milford pig-farm investigation. Pleaded to felony theft in the turkey case (36 months probation); pig-case disposition not publicly tracked.","cases"=>[["institution_name"=>"Sanpete County District Court","institution_city"=>"Manti","institution_state"=>"Utah","charges"=>"Utah Code 76-6-412 felony theft [2 counts] (Manti turkey farm); pattern of unlawful activity, burglary committed against an animal enterprise [2 counts], theft of livestock property committed against an animal enterprise, riot (Milford pig farm)","arrest_date"=>"2018-05-04","convicted"=>"Yes - guilty plea on turkey case; pig case disposition not publicly tracked","sentence"=>"36 months probation"]]],

    ["name"=>"Paul Picklesimer","first_name"=>"Paul","last_name"=>"Picklesimer","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Direct Action Everywhere"],"in_custody"=>false,"released"=>true,"description"=>"Paul Picklesimer, age 40, was charged with Wayne Hsiung in two Utah cases brought against DxE open-rescue actions. Acquitted in the 2018 St. George Smithfield Farms piglet-rescue case alongside Hsiung in 2022.","cases"=>[["institution_name"=>"Washington County District Court","institution_city"=>"St. George","institution_state"=>"Utah","charges"=>"Utah state burglary (felony) [2 counts] - 2018 St. George Smithfield Farms piglet rescue with Wayne Hsiung","arrest_date"=>"2018-08-06","convicted"=>"No - acquitted by jury, 2022","sentence"=>"Acquitted"]]],

    ["name"=>"Samer Masterson","first_name"=>"Samer","last_name"=>"Masterson","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Direct Action Everywhere"],"in_custody"=>false,"released"=>true,"description"=>"Samer Masterson, age 24, was charged in 2018 in two Utah cases brought against DxE open-rescue actions. Pleaded to reduced charges and received 36 months probation.","cases"=>[["institution_name"=>"Sanpete County District Court","institution_city"=>"Manti","institution_state"=>"Utah","charges"=>"Utah Code 76-6-412 felony theft [2 counts] (Manti turkey farm); pattern of unlawful activity, burglary committed against an animal enterprise [2 counts], theft of livestock property committed against an animal enterprise (Milford pig farm)","arrest_date"=>"2018-05-04","convicted"=>"Yes - guilty plea","sentence"=>"36 months probation"]]],

    ["name"=>"Jonathan Frohnmayer","first_name"=>"Jonathan","last_name"=>"Frohnmayer","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Direct Action Everywhere"],"in_custody"=>false,"released"=>true,"description"=>"Jonathan Frohnmayer, age 33, was charged in 2018 in two Utah cases brought against DxE open-rescue actions. Pleaded to reduced charges and received 36 months probation.","cases"=>[["institution_name"=>"Sanpete County District Court","institution_city"=>"Manti","institution_state"=>"Utah","charges"=>"Utah Code 76-6-412 felony theft [2 counts] (Manti turkey farm); pattern of unlawful activity, burglary committed against an animal enterprise [2 counts], theft of livestock property committed against an animal enterprise, riot (Milford pig farm)","arrest_date"=>"2018-05-04","convicted"=>"Yes - guilty plea","sentence"=>"36 months probation"]]],

    ["name"=>"Diane Gandee Sorbi","first_name"=>"Diane","middle_name"=>"Gandee","last_name"=>"Sorbi","gender"=>"Female","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"affiliation"=>["Direct Action Everywhere"],"in_custody"=>false,"released"=>false,"death_date"=>"2020-03-01","description"=>"Diane Gandee Sorbi, age 63, was charged in 2018 with two counts of felony theft for a Manti, Utah turkey-farm DxE open-rescue. She died in March 2020; case disposition prior to death is not publicly clear.","cases"=>[["institution_name"=>"Sanpete County District Court","institution_city"=>"Manti","institution_state"=>"Utah","charges"=>"Utah Code 76-6-412 felony theft [2 counts] - Manti turkey farm DxE open-rescue","arrest_date"=>"2018-05-04","convicted"=>"Data not available - died before resolution","sentence"=>"Died March 2020 before resolution"]]],

    ["name"=>"Red Fawn Fallis","first_name"=>"Red Fawn","last_name"=>"Fallis","gender"=>"Female","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Red Fawn Fallis, age 39, an Oglala Lakota Water Protector at Standing Rock, was federally charged after she discharged a firearm during her arrest at a NoDAPL action on October 27, 2016. The firearm had been provided to her by an FBI confidential informant who had infiltrated the camp. Sentenced in 2018 to 57 months federal prison plus 2 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) civil disorder; 18 USC 922(g)(1) and 924(a)(2) possession of a firearm and ammunition by a convicted felon - October 27, 2016 NoDAPL arrest at Standing Rock","arrest_date"=>"2016-10-27","incarceration_date"=>"2016-10-27","sentenced_date"=>"2018-07-11","convicted"=>"Yes - guilty plea","sentence"=>"57 months federal prison + 2 years supervised release"]]],

    ["name"=>"Holden Dometrius","first_name"=>"Holden","last_name"=>"Dometrius","gender"=>"Male","race"=>"White","state"=>"West Virginia","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Appalachians Against Pipelines"],"in_custody"=>false,"released"=>true,"description"=>"Holden Dometrius, age 22, was charged in West Virginia in April 2019 with felony threats of terrorist acts plus three misdemeanors after locking himself to equipment at a natural-gas pipeline worksite in Monroe County to oppose the pipeline. The case was dismissed November 10, 2020.","cases"=>[["institution_name"=>"Monroe County Magistrate Court","institution_city"=>"Union","institution_state"=>"West Virginia","charges"=>"WV Code 61-6-24(b) threats of terrorist acts (felony); 61-3B-3(a) trespass; 17A-8-6(b) tampering with special mobile equipment; 61-5-17(a) obstructing officer - April 2019 Monroe County WV pipeline blockade","arrest_date"=>"2019-04-25","convicted"=>"No - case dismissed","sentence"=>"Case dismissed Nov 10, 2020"]]],

    ["name"=>"Kaden Cicily Fralick","first_name"=>"Kaden","middle_name"=>"Cicily","last_name"=>"Fralick","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Kaden Cicily Fralick, age 21, was one of ten people charged in connection with a September 26, 2019 protest in the Utah commerce building over the Salt Lake City Inland Port. Five protesters used \"sleeping dragon\" lockboxes in the building lobby. Fralick was charged with third-degree felony rioting and misdemeanor criminal trespass; sentencing not publicly tracked.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-6-206(2)(a) criminal trespass (class B misdemeanor) - September 26, 2019 Utah commerce-building Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Joshua Macrae Baker-Cooper","first_name"=>"Joshua","middle_name"=>"Macrae","last_name"=>"Baker-Cooper","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Joshua Macrae Baker-Cooper, age 34, was charged with rioting and misdemeanor assault for involvement in the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-5-102 assault (class A misdemeanor) - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Randy Navarette","first_name"=>"Randy","last_name"=>"Navarette","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Randy Navarette, age 20, was one of ten people charged in connection with the September 26, 2019 Salt Lake City Inland Port protest at the Utah commerce building.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-6-206(2)(a) criminal trespass (class B misdemeanor) - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Rosemarie Zoe Obrien","first_name"=>"Rosemarie","middle_name"=>"Zoe","last_name"=>"Obrien","gender"=>"Female","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Rosemarie Zoe Obrien, age 25, was one of five protesters who used \"sleeping dragon\" lockboxes in the Utah commerce-building lobby during the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-6-206(2)(a) criminal trespass (class B misdemeanor) - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Hannah Kelman Zivolich","first_name"=>"Hannah","middle_name"=>"Kelman","last_name"=>"Zivolich","gender"=>"Female","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Hannah Kelman Zivolich, age 24, was one of five protesters who used \"sleeping dragon\" lockboxes in the Utah commerce-building lobby during the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-6-206(2)(a) criminal trespass (class B misdemeanor) - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    // Greenpeace 28 - condensed entries (one per person, federal+state collapsed)
    ["name"=>"Brianna LaTrell Gibson","first_name"=>"Brianna","middle_name"=>"LaTrell","last_name"=>"Gibson","gender"=>"Female","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Brianna LaTrell Gibson, age 28, of Brooklyn, was one of 28 Greenpeace USA activists who rappelled off a Houston bridge in September 2019 to challenge Democratic presidential candidates on climate change. Charged on both federal and Texas state level; the Texas grand jury declined to give felony indictments.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters (federal); Texas Penal Code 424.052 impairing or interrupting operation of critical infrastructure facility (state) - September 2019 Greenpeace Houston Ship Channel bridge rappel","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried; state grand jury declined to indict","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Cole Asher Taylor-Martin","first_name"=>"Cole","middle_name"=>"Asher","last_name"=>"Taylor-Martin","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Cole Asher Taylor-Martin, age 35, of Fullerton CA, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; Texas Penal Code 424.052 impairing critical infrastructure - Greenpeace Houston Ship Channel rappel","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Richard Alexander Sisney","first_name"=>"Richard","middle_name"=>"Alexander","last_name"=>"Sisney","gender"=>"Male","race"=>"Black","state"=>"California","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Richard Alexander Sisney, age 32, of Oakland, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Ryan Harris","first_name"=>"Ryan","last_name"=>"Harris","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Ryan Harris, age 41, of Olympia WA, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Sarah Francis Newman","first_name"=>"Sarah","middle_name"=>"Francis","last_name"=>"Newman","gender"=>"Female","race"=>"White","state"=>"Kentucky","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Sarah Francis Newman, age 42, of Lexington KY, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Sydney Leanne Clifford","first_name"=>"Sydney","middle_name"=>"Leanne","last_name"=>"Clifford","gender"=>"Other","state"=>"Oregon","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Sydney Leanne Clifford, age 21, of Portland OR, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Shavone Torres","first_name"=>"Shavone","last_name"=>"Torres","gender"=>"Female","race"=>"Black","state"=>"New Jersey","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Shavone Torres, age 39, of Pennsauken NJ, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Tyler N. McFarland","first_name"=>"Tyler","middle_name"=>"N.","last_name"=>"McFarland","gender"=>"Female","race"=>"White","state"=>"New Hampshire","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Tyler N. McFarland, age 27, of Dover NH, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Tracye Redd","first_name"=>"Tracye","last_name"=>"Redd","gender"=>"Male","race"=>"Black","state"=>"District of Columbia","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Tracye Redd, age 28, of Washington DC, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Tamura Russell Seiji","first_name"=>"Tamura","middle_name"=>"Russell","last_name"=>"Seiji","gender"=>"Male","race"=>"Asian","state"=>"California","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Tamura Russell Seiji, age 29, of Oakland, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Zeph Fishlyn","first_name"=>"Zeph","last_name"=>"Fishlyn","gender"=>"Female","race"=>"White","state"=>"California","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Zeph Fishlyn, age 52, of Oakland, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Heather Glasgow Doyle","first_name"=>"Heather","middle_name"=>"Glasgow","last_name"=>"Doyle","gender"=>"Female","race"=>"White","state"=>"New Mexico","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Heather Glasgow Doyle, age 35, of Albuquerque NM, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Christian Deshawn Bufford","first_name"=>"Christian","middle_name"=>"Deshawn","last_name"=>"Bufford","gender"=>"Male","race"=>"Black","state"=>"Georgia","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Christian Deshawn Bufford, age 32, of Ellerwood GA, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Chelcee Price","first_name"=>"Chelcee","last_name"=>"Price","gender"=>"Female","race"=>"Black","state"=>"Colorado","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Chelcee Price, age 23, of Denver, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Dakota Paige Schee","first_name"=>"Dakota","middle_name"=>"Paige","last_name"=>"Schee","gender"=>"Female","race"=>"White","state"=>"Missouri","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Dakota Paige Schee, age 25, of Kansas City MO, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Heidi Nybroten","first_name"=>"Heidi","last_name"=>"Nybroten","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Heidi Nybroten, age 26, of Minneapolis, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Julie Ann McElvain","first_name"=>"Julie","middle_name"=>"Ann","last_name"=>"McElvain","gender"=>"Female","race"=>"White","state"=>"Colorado","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Julie Ann McElvain, age 36, of Steamboat Springs CO, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Jonathan Butler","first_name"=>"Jonathan","last_name"=>"Butler","gender"=>"Male","race"=>"Black","state"=>"District of Columbia","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Jonathan Butler, age 29, of Washington DC, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Jayden Chayanne Allen","first_name"=>"Jayden","middle_name"=>"Chayanne","last_name"=>"Allen","gender"=>"Other","race"=>"White","state"=>"Missouri","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Jayden Chayanne Allen, age 20, of Warrensburg MO, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Kim Irene","first_name"=>"Kim","last_name"=>"Irene","gender"=>"Female","race"=>"Asian","state"=>"New York","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Kim Irene, age 26, of Jericho NY, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Michael Anton Herbert","first_name"=>"Michael","middle_name"=>"Anton","last_name"=>"Herbert","gender"=>"Male","race"=>"White","state"=>"Maryland","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Michael Anton Herbert, age 36, of Hyattsville MD, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Piper Werle","first_name"=>"Piper","last_name"=>"Werle","gender"=>"Female","race"=>"White","state"=>"Washington","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Piper Werle, age 29, of Port Orchard WA, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel.","cases"=>[["institution_name"=>"US District Court SD Texas / Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"33 USC 403 obstruction of navigable waters; TX 424.052 impairing critical infrastructure","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
    ["name"=>"Mariah De Los Santos","first_name"=>"Mariah","last_name"=>"De Los Santos","gender"=>"Female","race"=>"White","state"=>"Texas","era"=>"2010s","ideologies"=>["Environmental Activism"],"affiliation"=>["Greenpeace"],"in_custody"=>false,"released"=>true,"description"=>"Mariah De Los Santos, age 23, Greenpeace 28 - September 2019 Houston Ship Channel bridge rappel; charged on Texas state level only.","cases"=>[["institution_name"=>"Harris County District Court","institution_city"=>"Houston","institution_state"=>"Texas","charges"=>"Texas Penal Code 424.052 impairing or interrupting operation of critical infrastructure facility","arrest_date"=>"2019-09-13","convicted"=>"No - charged but not tried","sentence"=>"Charges did not proceed to trial"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }

    $cases = $row["cases"] ?? [];
    unset($row["cases"]);

    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }

    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "Prosecution Project rows 101-200 import complete."
