#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_misc_batch.sh
#
# Misc batch covering rows 5401, 5424-5447, 5494-5495 of TPP:
# - Brian Okum (Hanscom Field protest)
# - Bryant/Rojas/Colwell (1995 Lancaster Nazi Low Riders Walker murder)
# - Beebe/Hatch/Sanford (2010 Farmington NM Navajo branding)
# - Roy Alen Clyde (2015 Riverton WY shooting)
# - James Donald Walker (2018 WA Native American vehicle ramming)
# - Donald Jose David Zepeda (Kinder Morgan necessity-defense)
# - NoDAPL: Michael Giron Little Feather, Chase Iron Eyes, James
#   White Angry Bird, Dion Ortiz (Markus, Nastacio, Miller-Castillo,
#   Reznicek, Montoya, Kaczynski already in DB)
# - I-69 Tree Sit: Wertz, Farrell
# - Trinity Shockley (Mooresville IN school plot)
# - Daniel Jongyon Park (Palm Springs IVF clinic VBIED material support)
# - Jay Smith and Herb Geraghty (DC Nine additional defendants)
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"Brian Okum","first_name"=>"Brian","last_name"=>"Okum","gender"=>"Male","race"=>"White","state"=>"Massachusetts","era"=>"2020s","ideologies"=>["Environmental Activism","Climate Activism"],"affiliation"=>["Extinction Rebellion"],"in_custody"=>false,"released"=>true,"description"=>"Brian Okum, climate activist with Extinction Rebellion, was charged with a rare felony in connection with an April 2024 protest at Hanscom Field opposing a jet hangar expansion. Acquitted of felony malicious destruction of property over $1,200 and disorderly conduct; convicted of trespassing on May 13, 2025; sentenced to 1 year probation.","cases"=>[["institution_name"=>"Massachusetts state court","institution_state"=>"Massachusetts","charges"=>"Mass GL ch 266 sec 127 Malicious Destruction of Property Over $1,200 (acquitted); ch 272 sec 53 Disorderly Conduct (acquitted); ch 266 sec 120 Trespassing (convicted) - April 2024 Hanscom Field jet hangar protest","arrest_date"=>"2024-04-01","sentenced_date"=>"2025-05-13","convicted"=>"Yes on trespassing; acquitted on felony","sentence"=>"1 year probation"]]],

    ["name"=>"Ritch Bryant","first_name"=>"Ritch","last_name"=>"Bryant","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"1990s","ideologies"=>["White Supremacy","Anti-Black"],"affiliation"=>["Nazi Low Riders (NLR)"],"in_custody"=>true,"released"=>false,"description"=>"Ritch Bryant, 18, member of the Nazi Low Riders, with Randall Lee Rojas and Michael Thornton attacked Milton Walker Jr., a Black homeless man, in Lancaster CA on November 25, 1995. After Rojas struck Walker with a 2x4, Bryant returned later that night with Jessica Colwell to ensure he was dead and beat him with a 2x4 and metal pipe. Convicted of first-degree murder, hate crime, and assault; sentenced to life without parole. At indictment was already serving 8 years for a Sept 1995 Antelope Valley HS attack on a Black man.","cases"=>[["institution_name"=>"California Department of Corrections and Rehabilitation","institution_state"=>"California","charges"=>"California PC 187 First-Degree Murder; PC 422.55 Hate Crime; PC 264.1 Acting in Concert; PC 245 Assault With a Deadly Weapon - Nov 1995 Lancaster CA Walker murder","arrest_date"=>"1997-10-28","convicted"=>"Yes - jury verdict","sentence"=>"Life without parole"]]],

    ["name"=>"Randall Lee Rojas","first_name"=>"Randall","middle_name"=>"Lee","last_name"=>"Rojas","aka"=>"Randy","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"1990s","ideologies"=>["White Supremacy","Anti-Black"],"affiliation"=>["Nazi Low Riders (NLR)"],"in_custody"=>true,"released"=>false,"description"=>"Randall Lee Rojas, 20, NLR member, attacked Milton Walker Jr. with a 2x4 in Lancaster CA on November 25, 1995. Convicted of first-degree murder and hate crime; life without parole. Previously served 2 years for the Dec 1995 beating of a Latino outside an Antelope Valley 7-Eleven.","cases"=>[["institution_name"=>"California Department of Corrections and Rehabilitation","institution_state"=>"California","charges"=>"California PC 187 First-Degree Murder; PC 422.55 Hate Crime; PC 264.1 Acting in Concert; PC 245 Assault With Deadly Weapon - Nov 1995 Lancaster CA Walker murder","arrest_date"=>"1997-10-28","convicted"=>"Yes - jury verdict","sentence"=>"Life without parole"]]],

    ["name"=>"Jessica Colwell","first_name"=>"Jessica","last_name"=>"Colwell","gender"=>"Female","race"=>"Biracial / Multiracial","state"=>"California","era"=>"1990s","ideologies"=>["White Supremacy","Anti-Black"],"affiliation"=>["Nazi Low Riders (NLR)"],"in_custody"=>false,"released"=>true,"description"=>"Jessica Colwell, 16, NLR member (Hispanic and Native American), returned with Bryant to the scene of the Walker beating later that night and beat the victim with a 2x4 and metal pipe; allegedly gouged out his eyes with the pipe. Convicted of involuntary manslaughter and hate crime; 108 months (9 years) state prison. Earlier in 1995 was among NLR members who threatened to blow up a Lancaster coffee shop for serving Black customers.","cases"=>[["institution_name"=>"California Department of Corrections and Rehabilitation","institution_state"=>"California","charges"=>"California PC 192(b) Involuntary Manslaughter; PC 422.55 Hate Crime - Nov 1995 Lancaster CA Walker murder","arrest_date"=>"1997-10-28","convicted"=>"Yes - jury verdict","sentence"=>"108 months California state prison"]]],

    ["name"=>"Paul William Beebe","first_name"=>"Paul","middle_name"=>"William","last_name"=>"Beebe","aka"=>"Beebe","gender"=>"Male","race"=>"White","state"=>"New Mexico","era"=>"2010s","ideologies"=>["White Supremacy","Anti-Native"],"in_custody"=>false,"released"=>true,"description"=>"Paul William Beebe, 27, with William Hatch and Jesse Sanford took a Navajo man to an apartment in Farmington NM and used a coat hanger and markers to brand him with hate symbols (swastika); attackers wore a Nazi flag and a swastika dream catcher. Convicted of federal hate-crime conspiracy; 102 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New Mexico","charges"=>"18 USC 371 Conspiracy to Commit Offense; 18 USC 249 Hate Crime; 18 USC 2 Aiding and Abetting - 2010 Farmington NM Navajo branding","arrest_date"=>"2010-11-12","convicted"=>"Yes - guilty plea","sentence"=>"102 months federal prison"]]],

    ["name"=>"William Hatch","first_name"=>"William","last_name"=>"Hatch","aka"=>"Hatch","gender"=>"Male","race"=>"White","state"=>"New Mexico","era"=>"2010s","ideologies"=>["White Supremacy","Anti-Native"],"in_custody"=>false,"released"=>true,"description"=>"William Hatch, 29, Beebe co-defendant in the 2010 Farmington NM Navajo-branding hate crime. Pleaded guilty; 14 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New Mexico","charges"=>"18 USC 371 Conspiracy to Commit Offense; 18 USC 249 Hate Crime; 18 USC 2 Aiding and Abetting - 2010 Farmington NM Navajo branding","arrest_date"=>"2010-11-12","convicted"=>"Yes - guilty plea","sentence"=>"14 months federal prison"]]],

    ["name"=>"Jesse Alan Sanford","first_name"=>"Jesse","middle_name"=>"Alan","last_name"=>"Sanford","gender"=>"Male","race"=>"White","state"=>"New Mexico","era"=>"2010s","ideologies"=>["White Supremacy","Anti-Native"],"in_custody"=>false,"released"=>true,"description"=>"Jesse Alan Sanford, 25, Beebe/Hatch co-defendant in the 2010 Farmington NM Navajo-branding hate crime. Pleaded guilty; 60 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New Mexico","charges"=>"18 USC 371 Conspiracy to Commit Offense; 18 USC 249 Hate Crime; 18 USC 2 Aiding and Abetting - 2010 Farmington NM Navajo branding","arrest_date"=>"2010-11-12","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison"]]],

    ["name"=>"Roy Alen Clyde","first_name"=>"Roy","middle_name"=>"Alen","last_name"=>"Clyde","gender"=>"Male","race"=>"White","state"=>"Wyoming","era"=>"2010s","ideologies"=>["Anti-homeless"],"in_custody"=>true,"released"=>false,"description"=>"Roy Alen Clyde, 32, pleaded guilty October 1, 2015 to the murder of Stallone Trosper and attempted murder of James Goggles in Riverton WY. Both victims were of Native American descent; Clyde claimed he targeted them as homeless rather than for race. Sentenced to life.","cases"=>[["institution_name"=>"Wyoming Department of Corrections","institution_state"=>"Wyoming","charges"=>"Wyoming First-Degree Murder; Attempted Murder - 2015 Riverton WY shooting","arrest_date"=>"2015-10-01","convicted"=>"Yes - guilty plea","sentence"=>"Life sentence"]]],

    ["name"=>"James Donald Walker","first_name"=>"James","middle_name"=>"Donald","last_name"=>"Walker","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2010s","ideologies"=>["Anti-Native"],"in_custody"=>true,"released"=>false,"description"=>"James Donald Walker, 32, ran over campers near Donkey Creek campgrounds in Montesano WA on April 30, 2018, killing 20-year-old Jimmy Smith-Kramer of Taholah and critically injuring a 19-year-old. Quinault Nation said he yelled racial slurs; sheriffs report disputed that. Walker claimed Cherokee heritage. Pleaded guilty; 90 months WA state prison.","cases"=>[["institution_name"=>"Washington State Department of Corrections","institution_state"=>"Washington","charges"=>"RCW 9A.32.070 Manslaughter Second Degree; RCW 46.61.522 Vehicular Assault [2 counts]; RCW 46.52.020 Hit and Run - April 2018 Montesano WA vehicular killing","arrest_date"=>"2018-04-30","convicted"=>"Yes - guilty plea","sentence"=>"90 months Washington state prison"]]],

    ["name"=>"Donald Jose David Zepeda","first_name"=>"Donald","middle_name"=>"Jose David","last_name"=>"Zepeda","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Washington","era"=>"2010s","ideologies"=>["Environmental Activism","Anti-pipeline"],"in_custody"=>false,"released"=>true,"description"=>"Donald Jose David Zepeda, 30, attempted sabotage of the Kinder Morgan Tar Sands Pipeline in Mt. Vernon WA. Used a necessity defense (unsuccessful); sentenced October 16, 2019 to 60 days in jail.","cases"=>[["institution_name"=>"Skagit County Jail","institution_state"=>"Washington","charges"=>"RCW 9.05.060 Attempted Criminal Sabotage; RCW 9A.52.030 Burglary II; RCW 9A.48.090 Malicious Mischief III - Kinder Morgan pipeline sabotage","arrest_date"=>"2019-10-16","convicted"=>"Yes - jury verdict (necessity defense rejected)","sentence"=>"60 days jail"]]],

    ["name"=>"Michael A. Giron","first_name"=>"Michael","middle_name"=>"A.","last_name"=>"Giron","aka"=>"Little Feather","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Anti-pipeline"],"in_custody"=>false,"released"=>true,"description"=>"Michael Little Feather Giron, 45, was one of six federally charged for the October 27, 2016 NoDAPL Backwater Bridge barricade-fire civil disorder at Standing Rock. Pleaded guilty (non-cooperating); 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 844(h) + 18 USC 2 Use of Fire/Aiding and Abetting - October 2016 Standing Rock Backwater Bridge barricade","arrest_date"=>"2016-10-27","convicted"=>"Yes - guilty plea","sentence"=>"36 months federal prison"]]],

    ["name"=>"Chase A. Iron Eyes","first_name"=>"Chase","middle_name"=>"A.","last_name"=>"Iron Eyes","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Anti-pipeline"],"in_custody"=>false,"released"=>true,"description"=>"Chase A. Iron Eyes, 39, was charged February 1, 2017 with felony inciting a riot and misdemeanor criminal trespass for erecting a NoDAPL camp on pipeline land in southern Morton County ND. Plea deal reduced to misdemeanor disorderly conduct; 360-day deferred imposition + $1,500 fine, after which the case is removed from his record.","cases"=>[["institution_name"=>"Morton County District Court","institution_state"=>"North Dakota","charges"=>"ND Inciting a Riot (Felony, reduced to Disorderly Conduct misdemeanor) - 2017 NoDAPL Standing Rock camp","arrest_date"=>"2017-02-01","convicted"=>"Yes - guilty plea (reduced)","sentence"=>"360-day deferred imposition + $1,500 fine"]]],

    ["name"=>"James A. White","first_name"=>"James","middle_name"=>"A.","last_name"=>"White","aka"=>"Angry Bird","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Anti-pipeline"],"affiliation"=>["NoDAPL"],"in_custody"=>false,"released"=>true,"description"=>"James A. Angry Bird White, NoDAPL Water Protector, indicted March 1, 2017 with Markus, Nastacio, Miller-Castillo, and Ortiz for the October 27, 2016 Backwater Bridge barricade fire at Standing Rock. Pleaded guilty; time served + 12-month home confinement + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 844(h) Use of Fire to Commit a Federal Felony - October 2016 Standing Rock Backwater Bridge barricade","arrest_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"Time served + 12 mo home + 3 yr supervised release"]]],

    ["name"=>"Dion Ortiz","first_name"=>"Dion","last_name"=>"Ortiz","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Anti-pipeline"],"affiliation"=>["NoDAPL"],"in_custody"=>false,"released"=>true,"description"=>"Dion Ortiz, 20, NoDAPL Water Protector, indicted March 1, 2017 in the Markus et al. case for the October 27, 2016 Backwater Bridge barricade fire. Pleaded guilty; 16 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 231(a)(3) Civil Disorder; 18 USC 844(h) Use of Fire to Commit a Federal Felony - October 2016 Standing Rock Backwater Bridge barricade","arrest_date"=>"2017-03-01","convicted"=>"Yes - guilty plea","sentence"=>"16 months federal prison"]]],

    ["name"=>"Gina Eleyna Wertz","first_name"=>"Gina","middle_name"=>"Eleyna","last_name"=>"Wertz","aka"=>"Tiga","gender"=>"Female","race"=>"White","state"=>"Indiana","era"=>"2000s","ideologies"=>["Environmental Activism","Anti-development"],"affiliation"=>["Roadblock Earthfirst"],"in_custody"=>false,"released"=>true,"description"=>"Gina Eleyna Wertz, 24, with Hugh Farrell was indicted April 20, 2009 with 4 misdemeanor counts and 1 felony racketeering count for I-69 highway-expansion protests in 2007-2008 (tree sits, office takeovers, public-meeting confrontations). Felony racketeering dismissed March 2010; misdemeanors resolved via plea bargain to 2 years unsupervised probation.","cases"=>[["institution_name"=>"Indiana state court","institution_state"=>"Indiana","charges"=>"IC 35-45-2-1(a)(1)(2) Intimidation [misdemeanors]; IC 35-43-4-3(a) Conversion [2 misdemeanor counts]; IC 35-45-6-2(3) Racketeering (Felony, dismissed) - I-69 tree sits","arrest_date"=>"2009-04-20","convicted"=>"Yes - guilty plea on misdemeanors","sentence"=>"2 years unsupervised probation"]]],

    ["name"=>"Hugh F. Farrell","first_name"=>"Hugh","middle_name"=>"F.","last_name"=>"Farrell","gender"=>"Male","race"=>"White","state"=>"Indiana","era"=>"2000s","ideologies"=>["Environmental Activism","Anti-development"],"affiliation"=>["Roadblock Earthfirst"],"in_custody"=>false,"released"=>true,"description"=>"Hugh F. Farrell, 23, Wertz co-defendant in the 2009 I-69 expansion-protest indictment. Felony racketeering dismissed; 2 years unsupervised probation.","cases"=>[["institution_name"=>"Indiana state court","institution_state"=>"Indiana","charges"=>"IC 35-45-2-1(a)(1)(2) Intimidation [misdemeanors]; IC 35-43-4-3(a) Conversion [2 misdemeanor counts]; IC 35-45-6-2(3) Racketeering (Felony, dismissed) - I-69 tree sits","arrest_date"=>"2009-04-20","convicted"=>"Yes - guilty plea on misdemeanors","sentence"=>"2 years unsupervised probation"]]],

    ["name"=>"Trinity Shockley","first_name"=>"Trinity","last_name"=>"Shockley","aka"=>"Jamie Shockley, Dex Shockley","gender"=>"Other","race"=>"White","state"=>"Indiana","era"=>"2020s","ideologies"=>["NVE","Accelerationism"],"in_custody"=>true,"released"=>false,"description"=>"Trinity Shockley (also Jamie/Dex Shockley), 18, of Mooresville IN, was charged February 13, 2025 with conspiracy to commit murder, threat to commit terrorism, and conspiracy to commit intimidation. Allegedly planned a Valentines Day school shooting timed to the seventh anniversary of the Parkland shooting; idolized mass shooters including Cruz and Rodger. Police found bullets, vest, AR-15 magazines, and swastikas in their home. Pleaded guilty to conspiracy to commit murder; terroristic threats dropped. Sentenced to 144 months (12 years) imprisonment + 5 years supervised probationary release.","cases"=>[["institution_name"=>"Indiana Department of Correction","institution_state"=>"Indiana","charges"=>"IC 35-41-5-2 Conspiracy to Commit Murder; IC 35-45-2-1(a)(4) Intimidation: Threat to Commit Terrorism (dropped) - Feb 2025 Mooresville IN school plot","arrest_date"=>"2025-02-13","convicted"=>"Yes - guilty plea","sentence"=>"144 months Indiana state prison"]]],

    ["name"=>"Daniel Jongyon Park","first_name"=>"Daniel","middle_name"=>"Jongyon","last_name"=>"Park","gender"=>"Male","race"=>"Asian / South Asian","state"=>"California","era"=>"2020s","ideologies"=>["NVE","Efilism","Anti-natalism"],"in_custody"=>false,"released"=>false,"death_date"=>"2025-08-01","description"=>"Daniel Jongyon Park, 32, was arrested June 4, 2025 at JFK Airport, charged in the Central District of California with providing and attempting to provide material support to a terrorist. Park purchased explosive components used by co-conspirator Guy Bartkus to manufacture a VBIED that detonated outside an IVF clinic in Palm Springs, killing the bomber and injuring 4. The attack was planned for over a year and linked to the anti-natalist Efilism movement. Park died in custody by suicide (jumping from a prison balcony) before legal proceedings concluded.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 2339A Providing Material Support to Terrorists - May 2025 Palm Springs IVF clinic VBIED","arrest_date"=>"2025-06-04","death_in_custody_date"=>"2025-08-01","convicted"=>"No - died in custody","sentence"=>"Suicide in pretrial custody"]]],

    ["name"=>"Jay Smith","first_name"=>"Jay","last_name"=>"Smith","aka"=>"Juanito Pichardo","gender"=>"Male","race"=>"White","state"=>"District of Columbia","era"=>"2020s","ideologies"=>["Anti-abortion","Christian Right"],"affiliation"=>["Progressive Anti-Abortion Uprising"],"in_custody"=>false,"released"=>true,"description"=>"Jay Smith, 32, of Freeport NY, DC Nine co-defendant in the October 22, 2020 Washington Surgi-Clinic blockade. Convicted; 10 months federal prison. Pardoned by Trump January 2025.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 241 Conspiracy Against Rights; 18 USC 248(a)(1) FACE Act - Oct 22 2020 DC clinic blockade","arrest_date"=>"2022-10-14","convicted"=>"Yes - guilty plea","sentence"=>"10 months federal prison; pardoned by Trump January 2025"]]],

    ["name"=>"Herb Geraghty","first_name"=>"Herb","last_name"=>"Geraghty","aka"=>"Rosemary Geraghty","gender"=>"Male","race"=>"White","state"=>"District of Columbia","era"=>"2020s","ideologies"=>["Anti-abortion"],"affiliation"=>["Progressive Anti-Abortion Uprising"],"in_custody"=>false,"released"=>true,"description"=>"Herb Geraghty, 25, of Pittsburgh PA, gender dysphoric and non-religious atheist, DC Nine co-defendant in the October 22, 2020 Washington Surgi-Clinic blockade. Convicted at trial; 27 months federal prison. Pardoned by Trump January 2025.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 241 Conspiracy Against Rights; 18 USC 248(a)(1) FACE Act - Oct 22 2020 DC clinic blockade","arrest_date"=>"2022-10-14","convicted"=>"Yes - jury verdict","sentence"=>"27 months federal prison; pardoned by Trump January 2025"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "Misc batch import complete."
