#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_6.sh
#
# Sixth batch (rows 407, 622-700). Mix of U.S. domestic anti-
# government / threats / Portland-Asheville riot prosecutions plus
# extradited FARC/ELN narco-terrorism defendants. Skipped per the
# U.S.-nexus scope rule: SOLARTE row 625 (Hernandez-Solarte, died
# May 2021 pending extradition); SOLARTE row 626 Marlon Marin (DEA
# informant, sealed); COLOMBIA fugitives rows 651-653 (Wilver
# Villegas-Palomino, Jaime Picon-Rodriguez, Diomedes Barbosa-
# Montano); all MADURO indictments rows 654-659 (Venezuelan
# officials never tried + Hernandez-Solarte and Marin Arango
# duplicates). Apostrophes pre-stripped from string content.
set -e

php artisan tinker --execute='
$rows = [
    // Row 407 - Wilcoxson
    ["name"=>"Damoine Wilcoxson","first_name"=>"Damoine","last_name"=>"Wilcoxson","gender"=>"Male","race"=>"Black","state"=>"Indiana","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Damoine Wilcoxson, age 23, of Indianapolis, fired at two Indianapolis-area police stations on October 4 and October 13, 2016 in what he described as anti-government protest. Convicted at trial of two counts of attempted murder and one count of felony criminal recklessness; 65 years (780 months) in Indiana state prison.","cases"=>[["institution_name"=>"Indiana Department of Corrections","institution_state"=>"Indiana","charges"=>"Indiana state attempted murder [2 counts]; felony criminal recklessness - October 2016 Indianapolis police-station shootings","arrest_date"=>"2016-10-31","incarceration_date"=>"2016-10-31","convicted"=>"Yes - jury verdict","sentence"=>"780 months Indiana state prison"]]],

    // Row 622 - Faouzi Jaber
    ["name"=>"Faouzi Jaber","first_name"=>"Faouzi","last_name"=>"Jaber","aka"=>"Excellence","gender"=>"Male","race"=>"Middle Eastern/North African","state"=>"New York","era"=>"2010s","ideologies"=>["Arms Trafficking"],"in_custody"=>false,"released"=>true,"description"=>"Faouzi Jaber, age 61, of Ivory Coast, was caught in a 2017 DEA narco-terrorism sting in which informants posed as FARC members seeking $8 million in weapons to attack U.S. personnel in Colombia. Arrested in Prague; extradited to the U.S.; 180 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal conspiracy to provide material support and resources to a designated foreign terrorist organization - 2017 DEA-FARC weapons sting","arrest_date"=>"2017-04-06","incarceration_date"=>"2017-04-06","convicted"=>"Yes - guilty plea","sentence"=>"180 months federal prison"]]],

    // Row 623 - Gloria Merriweather
    ["name"=>"Gloria Merriweather","first_name"=>"Gloria","last_name"=>"Merriweather","aka"=>"Glo Merriweather","gender"=>"Other","race"=>"Black","state"=>"North Carolina","era"=>"2010s","ideologies"=>["Black Liberation","Anti-Police"],"in_custody"=>false,"released"=>true,"description"=>"Gloria (Glo) Merriweather, a Charlotte activist, age 25, was charged with inciting a riot for alleged participation in damage to police vehicles and rock-throwing during the 2016 protests following the police killing of Keith Lamont Scott. Charges dropped two weeks before trial due to lack of evidence.","cases"=>[["institution_name"=>"Mecklenburg County District Court","institution_state"=>"North Carolina","charges"=>"North Carolina state inciting a riot - 2016 Charlotte Uprising protests","arrest_date"=>"2017-11-28","convicted"=>"No - charges dropped","sentence"=>"Charges dropped"]]],

    // Row 624 - David Campbell
    ["name"=>"David Campbell","first_name"=>"David","last_name"=>"Campbell","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2010s","ideologies"=>["Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"David Campbell, age 32, was arrested in 2018 outside a Manhattan event in connection with an antifascist counter-protest brawl that left two party-goers hospitalized. Pleaded guilty to attempted gang assault; 18 months New York state prison.","cases"=>[["institution_name"=>"New York state Department of Corrections","institution_state"=>"New York","charges"=>"NY state attempted assault, attempted gang assault [1st and 2nd degree], assault with intent to cause physical injury with weapon, assault on a peace officer - 2018 antifascist counter-protest brawl","arrest_date"=>"2018-03-21","incarceration_date"=>"2018-03-21","convicted"=>"Yes - guilty plea","sentence"=>"18 months NY state prison"]]],

    // SOLARTE3 + SOLARTE4 (extradited)
    ["name"=>"Armando Gomez","first_name"=>"Armando","last_name"=>"Gomez","aka"=>"El Doctor","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Armando Gomez (El Doctor), age 70, FARC associate; extradited from Colombia and pleaded guilty to conspiring to import cocaine into the United States. 120 months federal prison + 3 years supervised release; credit for time served in Colombia.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"21 USC 959 conspiring to and attempting to import cocaine into the United States - 2017-2018 FARC cocaine production and distribution scheme","arrest_date"=>"2018-04-12","incarceration_date"=>"2018-04-12","convicted"=>"Yes - guilty plea","sentence"=>"120 months federal prison + 3 years supervised release"]]],
    ["name"=>"Fabio Simon Younes Arboleda","first_name"=>"Fabio","last_name"=>"Younes Arboleda","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Fabio Simon Younes Arboleda, age 72, FARC associate; extradited from Colombia and pleaded guilty to conspiring to import cocaine into the United States. 120 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"21 USC 959 conspiring to and attempting to import cocaine into the United States - 2017-2018 FARC cocaine scheme","arrest_date"=>"2018-04-13","incarceration_date"=>"2018-04-13","convicted"=>"Yes - guilty plea","sentence"=>"120 months federal prison + 3 years supervised release"]]],

    // Row 636 - Wil Casey Floyd
    ["name"=>"Wil Casey Floyd","first_name"=>"Wil","middle_name"=>"Casey","last_name"=>"Floyd","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2010s","ideologies"=>["Anarchism"],"in_custody"=>false,"released"=>true,"description"=>"Wil Casey Floyd, age 33, of Elkhart Lake WI, was sentenced to 37 months federal prison for unlawful possession of a destructive device; he made and threw Molotov cocktails at police officers during the May 1, 2016 Black Bloc May Day parade in Seattle, igniting one officers trousers and burning his legs.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"26 USC 5861(d) and 5845(a)(8) unlawful possession of a destructive device - 2016 May Day Seattle Black Bloc Molotov-cocktail attack on police","arrest_date"=>"2018-06-01","incarceration_date"=>"2018-06-01","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison + 2 years supervised release + 80 hours community service"]]],

    // Row 637 - Therese Okoumou
    ["name"=>"Therese Patricia Okoumou","first_name"=>"Therese","middle_name"=>"Patricia","last_name"=>"Okoumou","gender"=>"Female","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Immigrant Rights"],"in_custody"=>false,"released"=>true,"description"=>"Therese Patricia Okoumou, age 45, scaled the Statue of Liberty pedestal on July 4, 2018 in protest of the Trump administrations family-separation immigration policy, prompting the evacuation of Liberty Island. Convicted of trespassing, disorderly conduct, and interference with agency functions; sentenced to 5 years probation and 200 hours community service.","cases"=>[["institution_name"=>"U.S. District Court for the Southern District of New York","institution_city"=>"New York","institution_state"=>"New York","charges"=>"18 USC 1752(a)(1) trespassing; 18 USC 1752(a)(3) interference with agency functions; 18 USC 1752(a)(2) disorderly conduct - July 4, 2018 Statue of Liberty climb","arrest_date"=>"2018-07-05","convicted"=>"Yes - bench verdict","sentence"=>"5 years probation + 200 hours community service"]]],

    // Row 638 - Carlos Bayon
    ["name"=>"Carlos Bayon","first_name"=>"Carlos","last_name"=>"Bayon","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Carlos Bayon, age 63, of Buffalo NY, was charged with interstate communication of threats for calling the offices of two members of Congress in Washington and Louisiana and threatening to harm them and their families. 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 115 assault/threat to assault federal officer or family [2 counts]; 18 USC 875 interstate communications threats [2 counts] - 2018 calls threatening members of Congress","arrest_date"=>"2018-08-02","incarceration_date"=>"2018-08-02","convicted"=>"Yes - jury verdict","sentence"=>"60 months federal prison"]]],

    // Row 639 - Ronald DeRisi
    ["name"=>"Ronald DeRisi","first_name"=>"Ronald","last_name"=>"DeRisi","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Ronald DeRisi, age 74, of Smithtown NY, was arrested in 2018 for threatening to murder and assault two U.S. Senators in retaliation for their support of Justice Brett Kavanaughs Supreme Court confirmation. He made over 12 calls including threats to shoot the senators with a 12mm handgun. 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"Federal threatening to murder and assault two U.S. Senators - 2018 calls during the Kavanaugh confirmation","arrest_date"=>"2018-10-19","incarceration_date"=>"2018-10-19","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    // Row 640/641 - James Robinson (single person, two duplicate rows)
    ["name"=>"James E. Robinson","first_name"=>"James","middle_name"=>"E.","last_name"=>"Robinson","aka"=>"AkronPhoenix420","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2010s","ideologies"=>["Anti-Police","Anti-government"],"affiliation"=>["Anonymous"],"in_custody"=>false,"released"=>true,"description"=>"James E. Robinson, age 33, of Akron OH, used the Twitter handle AkronPhoenix420 to claim DDoS attacks on multiple government and police websites including the Akron Police Department, City of Akron, Ohio Department of Public Safety, NIH, the Defense Information Security Agency, and DOD between 2017-2018, citing Anonymous and TangoDown hashtags. Sentenced October 3, 2019 to 72 months federal prison plus $668,684 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Ohio","charges"=>"18 USC 1030(a)(5)(A) and (c)(4)(B) damaging protected computers - 2017-2018 Anonymous-claimed DDoS attacks on government and police websites","arrest_date"=>"2018-10-24","incarceration_date"=>"2018-10-24","convicted"=>"Yes - guilty plea","sentence"=>"72 months federal prison + $668,684 restitution"]]],

    // Row 643 - Francisco Joseph Arcila Ramirez
    ["name"=>"Francisco Joseph Arcila Ramirez","first_name"=>"Francisco","middle_name"=>"Joseph","last_name"=>"Arcila Ramirez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2010s","ideologies"=>["Communism"],"affiliation"=>["ELN"],"in_custody"=>false,"released"=>true,"description"=>"Francisco Joseph Arcila Ramirez, age 36, an ELN (National Liberation Army) member, supplied weapons shipments to the Colombian terrorist organization. Pleaded guilty in U.S. federal court; 240 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 371 conspiracy to illegally deal firearms; 18 USC 922(a)(6) false statements in connection with firearm acquisition [4 counts]; 18 USC 922(a)(1)(A) dealing in firearms without a license; 18 USC 2339B conspiracy to provide and provision of material support to a foreign terrorist organization","arrest_date"=>"2019-03-29","incarceration_date"=>"2019-03-29","convicted"=>"Yes - guilty plea","sentence"=>"240 months federal prison"]]],

    // Row 644 - Suzanne Muscara
    ["name"=>"Suzanne Muscara","first_name"=>"Suzanne","last_name"=>"Muscara","gender"=>"Female","race"=>"White","state"=>"Maine","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Suzanne Muscara, age 37, mailed a threatening letter containing fake anthrax to Republican Senator Susan Collins along with a stick-figure drawing of the senator with X eyes. Convicted at trial; 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maine","charges"=>"Federal mailing a threatening communication - 2019 fake-anthrax letter to Sen. Susan Collins","arrest_date"=>"2019-04-17","incarceration_date"=>"2019-04-17","convicted"=>"Yes - jury verdict","sentence"=>"30 months federal prison"]]],

    // Row 645 - Mickael Gedlu
    ["name"=>"Mickael Gedlu","first_name"=>"Mickael","last_name"=>"Gedlu","gender"=>"Male","race"=>"Black","state"=>"Texas","era"=>"2010s","ideologies"=>["Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Mickael Gedlu, age 36, a former Marine Corps service member, was indicted in 2019 for threats against the President. Detained in Dallas in May 2018 carrying a Kill Trump sign 30 minutes before then-President Trumps arrival at the Adolphus Hotel; admitted YouTube posts including I am waiting for Trump to visit Dallas before I attempt to assassinate him. 18 months federal prison plus 6 additional months for supervised-release violations.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 871 threats against the President - 2018 Dallas Trump-rally threats and YouTube postings","arrest_date"=>"2019-07-09","incarceration_date"=>"2019-07-09","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison + 6 additional months for supervised-release violations"]]],

    // Row 646 - Cellicia Hunt
    ["name"=>"Cellicia Latoya Hunt","first_name"=>"Cellicia","middle_name"=>"Latoya","last_name"=>"Hunt","gender"=>"Female","race"=>"Black","state"=>"Florida","era"=>"2010s","ideologies"=>["Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Cellicia Latoya Hunt, age 35, attempted to throw a Molotov cocktail at a federal CSI building in Oakland Park FL on September 5, 2019. The wick extinguished mid-air. Indicted but committed to psychiatric evaluation and treatment; case closed administratively.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 844(f)(1) malicious attempted damage to a federal building by fire; 26 USC 5861(d) possession of an unregistered firearm","arrest_date"=>"2019-09-17","convicted"=>"No - committed to psychiatric treatment","sentence"=>"Civil commitment for treatment"]]],

    // Row 647 - Eric Patrick Brandt
    ["name"=>"Eric Patrick Brandt","first_name"=>"Eric","middle_name"=>"Patrick","last_name"=>"Brandt","aka"=>"Chilled Speaker","gender"=>"Male","race"=>"White","state"=>"Colorado","era"=>"2010s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Eric Patrick Brandt, age 49, an anti-government Denver protester, was arrested December 26, 2019 for posting threatening videos against a Denver judge including the judges address and threats to harm the judge and family. Pleaded guilty to felony retaliation against a judge and misdemeanor harassment; sentenced to three concurrent 4-year terms (48 months effective) Colorado state prison.","cases"=>[["institution_name"=>"Colorado Department of Corrections","institution_state"=>"Colorado","charges"=>"Colorado state retaliation against a judge (felony); harassment (misdemeanor) - 2019 Denver judge harassment","arrest_date"=>"2019-12-26","incarceration_date"=>"2019-12-26","convicted"=>"Yes - guilty plea","sentence"=>"48 months Colorado state prison"]]],

    // Rows 648-650 - Detained ELN cocaine traffickers
    ["name"=>"Yamit Picon-Rodriguez","first_name"=>"Yamit","last_name"=>"Picon-Rodriguez","aka"=>"Concha","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2020s","ideologies"=>["Communism"],"affiliation"=>["ELN"],"in_custody"=>false,"released"=>true,"description"=>"Yamit Picon-Rodriguez, age 36, ELN member; detained in September 2020 in connection with a 20-year ELN cocaine-trafficking conspiracy from Colombia to the United States. Extradited and prosecuted in the Southern District of New York.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"21 USC 960a federal narco-terrorism; 21 USC 963, 959(a), 960(a)(3), 960(b)(1) international cocaine distribution conspiracy","arrest_date"=>"2020-02-12","incarceration_date"=>"2020-09-01","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Jose Gabriel Alvarez-Ortiz","first_name"=>"Jose Gabriel","last_name"=>"Alvarez-Ortiz","aka"=>"Alex","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2020s","ideologies"=>["Communism"],"affiliation"=>["ELN"],"in_custody"=>false,"released"=>true,"description"=>"Jose Gabriel Alvarez-Ortiz, age 26, ELN member; detained in late 2020. Extradited and prosecuted in the Southern District of New York for the ELN cocaine-trafficking conspiracy.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"21 USC 960a narco-terrorism; international cocaine distribution conspiracy","arrest_date"=>"2020-02-12","incarceration_date"=>"2020-10-01","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Henry Trigos-Celon","first_name"=>"Henry","last_name"=>"Trigos-Celon","aka"=>"Moncho Picada","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2020s","ideologies"=>["Communism"],"affiliation"=>["ELN"],"in_custody"=>false,"released"=>true,"description"=>"Henry Trigos-Celon, age 43, ELN member; detained in September 2020. Pleaded guilty in U.S. federal court to the ELN cocaine-trafficking conspiracy.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"21 USC 960a narco-terrorism; international cocaine distribution conspiracy","arrest_date"=>"2020-02-12","incarceration_date"=>"2020-09-01","convicted"=>"Yes - guilty plea","sentence"=>"Data not available"]]],

    // Rows 660-661 - Wolf & Frazee
    ["name"=>"Amanda R. Wolf","first_name"=>"Amanda","last_name"=>"Wolf","gender"=>"Female","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-Police"],"in_custody"=>false,"released"=>true,"description"=>"Amanda R. Wolf, age 23, of Lombard IL, was arrested June 1, 2020 and charged with attempted terrorism and possession of an incendiary device after helping co-defendant Christian Frazee approach Lombard police squad cars with a Molotov cocktail, lighters, butane torches, and a bat. Pleaded guilty; 48 months Illinois state prison.","cases"=>[["institution_name"=>"DuPage County Jail","institution_city"=>"Wheaton","institution_state"=>"Illinois","charges"=>"Illinois state attempted terrorism; possession of explosives or incendiary device - June 2020 Lombard IL police-station Molotov plot","arrest_date"=>"2020-06-01","incarceration_date"=>"2020-06-01","convicted"=>"Yes - guilty plea","sentence"=>"48 months Illinois state prison"]]],
    ["name"=>"Christian Frazee","first_name"=>"Christian","last_name"=>"Frazee","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-Police"],"in_custody"=>true,"released"=>false,"description"=>"Christian Frazee, age 25, of Lombard IL, was arrested June 1, 2020 near the Lombard Municipal Complex and charged with attempted terrorism, possession of incendiary devices, and conspiracy to commit terrorism. Pleaded guilty; 120 months Illinois state prison.","cases"=>[["institution_name"=>"Illinois Department of Corrections","institution_state"=>"Illinois","charges"=>"Illinois state attempted terrorism; possession of explosive or incendiary device [2 counts]; conspiracy to commit terrorism - June 2020 Lombard IL police Molotov plot","arrest_date"=>"2020-06-01","incarceration_date"=>"2020-06-01","convicted"=>"Yes - guilty plea","sentence"=>"120 months Illinois state prison"]]],

    // Row 662 - Bracamonte
    ["name"=>"Rene Christopher Bracamonte","first_name"=>"Rene","middle_name"=>"Christopher","last_name"=>"Bracamonte","gender"=>"Male","state"=>"Arizona","era"=>"2020s","ideologies"=>["Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Rene Christopher Bracamonte, age 34, threatened the life of former Vice President Mike Pence at the Westin La Paloma Hotel in Tucson AZ on August 11, 2020. He pulled a handgun and waved it in the air after departing the resort. Pleaded guilty; 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Arizona","charges"=>"18 USC 871(a) threats against the President and successors to the Presidency - August 2020 Tucson Pence rally","arrest_date"=>"2020-11-23","incarceration_date"=>"2020-11-23","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    // Row 663 - Patrick Gerola
    ["name"=>"Patrick Michael Gerola","first_name"=>"Patrick","middle_name"=>"Michael","last_name"=>"Gerola","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Arizona","era"=>"2020s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Patrick Michael Gerola, age 56, was arrested 100 yards from a Florence AZ ICE prison parking lot on December 31, 2020 after honking and claiming he had a bomb. No explosives were found. Charged with state terrorism, disorderly conduct, and trespass; case dismissed without prejudice on the same day as the indictment, January 6, 2021.","cases"=>[["institution_name"=>"Pinal County Jail","institution_state"=>"Arizona","charges"=>"Arizona state 13-2308.01 terrorism; 13-2904 disorderly conduct; 13-1503 criminal trespass 2nd degree - 2020 Florence AZ ICE-prison incident","arrest_date"=>"2021-01-06","convicted"=>"No - dismissed without prejudice","sentence"=>"Charges dismissed"]]],

    // Row 664 - Thomas Starks
    ["name"=>"Thomas Alexander Starks","first_name"=>"Thomas","middle_name"=>"Alexander","last_name"=>"Starks","gender"=>"Male","race"=>"White","state"=>"North Dakota","era"=>"2020s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Alexander Starks, age 30, of Lisbon ND, used an axe to smash the entrance window of a Republican U.S. Senators Fargo office in late 2020 in frustration over the lack of a Covid-19 relief vote. Pleaded guilty; sentenced to time served (~7.8 months).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 1361 injury to government property - 2020 Fargo ND Senate-office axe attack","arrest_date"=>"2021-01-13","incarceration_date"=>"2021-01-13","convicted"=>"Yes - guilty plea","sentence"=>"Time served (~7.8 months)"]]],

    // Row 665 - Davis Beeman
    ["name"=>"Davis Alan Beeman","first_name"=>"Davis","middle_name"=>"Alan","last_name"=>"Beeman","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism"],"in_custody"=>false,"released"=>true,"description"=>"Davis Alan Beeman, age 38, was one of 15 people arrested in Portland on January 20, 2021 in connection with protests-turned-riots in which the Oregon Democratic Party headquarters was damaged. No formal complaint filed.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.025 disorderly conduct II; 166.015 riot - January 20, 2021 Portland inauguration-day protest","arrest_date"=>"2021-01-20","convicted"=>"No - charged but no complaint filed","sentence"=>"No complaint"]]],

    // Row 666 - Daniel Baker
    ["name"=>"Daniel Alan Baker","first_name"=>"Daniel","middle_name"=>"Alan","last_name"=>"Baker","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anarchism","Anti-Fascism"],"affiliation"=>["YPG (former)"],"in_custody"=>false,"released"=>true,"description"=>"Daniel Alan Baker, age 33, a former U.S. Army soldier who went AWOL pre-Iraq deployment and joined the Peoples Protection Units (YPG) in Syria fighting ISIS, was charged with transmitting interstate threats after his January 2021 Call to Arms post urging armed resistance to anticipated armed-mob attacks on the Florida Capitol following the January 6 events. Convicted at trial; 44 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 875(c) interstate threats to kidnap or injure - January 2021 Call to Arms social-media post","arrest_date"=>"2021-02-18","incarceration_date"=>"2021-02-18","convicted"=>"Yes - jury verdict","sentence"=>"44 months federal prison"]]],

    // Row 667 - John Subleski
    ["name"=>"John Subleski","first_name"=>"John","last_name"=>"Subleski","aka"=>"BigBoog","gender"=>"Male","state"=>"Kentucky","era"=>"2020s","ideologies"=>["Boogaloo"],"affiliation"=>["United Pharaohs Guard"],"in_custody"=>false,"released"=>true,"description"=>"John Subleski, age 32, of Louisville KY, a member of the United Pharaohs Guard Boogaloo militia, was charged with using social media to incite a riot in downtown Louisville on January 6, 2021 contemporaneous with the U.S. Capitol riot, posting Time to storm LMPD and similar messages. Pleaded guilty; sentenced to time served (5 months) and 3 years probation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Kentucky","charges"=>"18 USC 924(d) Riot Act; 18 USC 2101 incitement; 28 USC 2461(c) forfeiture - January 6, 2021 Louisville Boogaloo riot incitement","arrest_date"=>"2021-02-23","incarceration_date"=>"2021-02-23","convicted"=>"Yes - guilty plea","sentence"=>"Time served (5 months) + 3 years probation"]]],

    // Row 668 - Rickey Johnson
    ["name"=>"Rickey Johnson","first_name"=>"Rickey","last_name"=>"Johnson","aka"=>"Nigel Dawn Defarren","gender"=>"Male","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-Republican"],"in_custody"=>false,"released"=>true,"description"=>"Rickey Johnson, age 47, of New York, sent threatening messages on January 30, 2021 to U.S. Senator Joe Manchin and Fox News hosts Laura Ingraham and Greg Gutfeld. Convicted at trial; 72 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 875(c)(2) threatening interstate communications [2 counts]; 18 USC 115(a)(1)(b) threatening a U.S. official [2 counts] - 2021 threats against Sen. Manchin and Fox News hosts","arrest_date"=>"2021-03-22","incarceration_date"=>"2021-03-22","convicted"=>"Yes - jury verdict","sentence"=>"72 months federal prison"]]],

    // Row 669 - Christopher Podlesnik
    ["name"=>"Christopher Kent Podlesnik","first_name"=>"Christopher","middle_name"=>"Kent","last_name"=>"Podlesnik","gender"=>"Male","race"=>"White","state"=>"Wyoming","era"=>"2020s","ideologies"=>["Anti-Republican"],"in_custody"=>false,"released"=>true,"description"=>"Christopher Kent Podlesnik, age 52, of Laramie WY, left threatening voicemails for Senators Cynthia Lummis, John Barrasso, Rep. Matt Gaetz, and a state senator on January 28, 2021, calling them traitors and threatening to shoot them. Pleaded guilty to four counts; 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wyoming","charges"=>"18 USC 875(c) threats in interstate commerce [7 counts] - 2021 threatening voicemails to elected officials","arrest_date"=>"2021-03-24","incarceration_date"=>"2021-03-24","convicted"=>"Yes - guilty plea","sentence"=>"18 months federal prison"]]],

    // Row 670 - Hunter Mattin
    ["name"=>"Hunter Mattin","first_name"=>"Hunter","last_name"=>"Mattin","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Black Liberation","Anti-Police"],"in_custody"=>false,"released"=>true,"description"=>"Hunter Mattin, age 20, an Ohio State University student, was arrested April 15, 2021 for aggravated burglary during a Daunte Wright BLM protest at Columbus Police Department headquarters; he allegedly broke in and hit an officer with a club. Pleaded guilty to one count of assault and one of obstructing official business; 1 year community control plus 2 days time served.","cases"=>[["institution_name"=>"Franklin County Municipal Court","institution_state"=>"Ohio","charges"=>"Ohio Rev. Code 2911.11(A)(1) aggravated burglary - April 13, 2021 Columbus Police HQ Daunte Wright BLM protest","arrest_date"=>"2021-04-15","convicted"=>"Yes - guilty plea on assault and obstruction","sentence"=>"1 year community control + 2 days time served"]]],

    // Row 671 - Gregory Timm
    ["name"=>"Gregory William Loel Timm","first_name"=>"Gregory","middle_name"=>"William Loel","last_name"=>"Timm","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Gregory William Loel Timm, age 27, drove a minivan into a tent of Republican volunteers running a voter-registration booth in Jacksonville FL on April 16, 2021. He stated someone had to take a stand against Donald Trump. Convicted of criminal mischief only (acquitted on aggravated assault); 2 months Florida state prison.","cases"=>[["institution_name"=>"Duval County Jail","institution_state"=>"Florida","charges"=>"Florida state 784.08(2)(b) aggravated assault on a person 65+ [2 counts] (acquitted); 806.13(1)(a) criminal mischief - April 2021 Jacksonville Republican voter-tent vehicle ramming","arrest_date"=>"2021-04-16","incarceration_date"=>"2021-04-16","convicted"=>"Yes - guilty on criminal mischief; acquitted on aggravated assault","sentence"=>"2 months Florida state prison"]]],

    // Row 672 - Eugene Huelsman
    ["name"=>"Eugene Huelsman","first_name"=>"Eugene","last_name"=>"Huelsman","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2020s","ideologies"=>["Anti-Republican"],"in_custody"=>false,"released"=>true,"description"=>"Eugene Huelsman, age 58, of Thousand Oaks CA, a longtime CNN/ABC/NBC camera operator and seven-time Primetime Emmy nominee, called the office of Rep. Matt Gaetz on January 9, 2021 and threatened to shoot Gaetz and his children. Pleaded guilty; sentenced to 6 months home confinement.","cases"=>[["institution_name"=>"U.S. District Court for the Central District of California","institution_state"=>"California","charges"=>"18 USC 875(c) interstate communication threat to kidnap or injure - January 2021 Gaetz-office threat","arrest_date"=>"2021-05-18","convicted"=>"Yes - guilty plea","sentence"=>"6 months home confinement"]]],

    // DOUVIA cluster (Portland riots, January 20, 2021) - rows 673-678
    ["name"=>"Kai-Ave James Douvia","first_name"=>"Kai-Ave","middle_name"=>"James","last_name"=>"Douvia","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Kai-Ave James Douvia, age 23, was indicted in June 2021 for January 20, 2021 inauguration-day rioting that damaged the Democratic Party of Oregon building in Portland. 18 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot [2 counts]; 164.365 criminal mischief 1st degree [2 counts]; 164.354 criminal mischief 2nd degree [2 counts]","arrest_date"=>"2021-06-02","convicted"=>"Yes - guilty plea on some","sentence"=>"18 months probation"]]],
    ["name"=>"Austin Nathaniel Nuchraksa","first_name"=>"Austin","middle_name"=>"Nathaniel","last_name"=>"Nuchraksa","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Austin Nathaniel Nuchraksa, age 25, of McMinnville OR, indicted June 2021 for January 20, 2021 Portland Democratic Party HQ rioting. 2 years probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd; 166.382 unlawful possession of a destructive device [4 counts]","arrest_date"=>"2021-06-02","convicted"=>"Yes - guilty plea on some","sentence"=>"2 years probation"]]],
    ["name"=>"Nicole Aria Rose","first_name"=>"Nicole","middle_name"=>"Aria","last_name"=>"Rose","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Nicole Aria Rose, age 25, of McMinnville OR, indicted June 2021 for January 20, 2021 Portland Democratic Party HQ rioting. 12 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd","arrest_date"=>"2021-06-02","convicted"=>"Yes - guilty plea on some","sentence"=>"12 months probation"]]],
    ["name"=>"Jean V. Paris","first_name"=>"Jean","last_name"=>"Paris","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Jean V. Paris, age 19, of Albany OR, indicted June 2021 for January 20, 2021 Portland Democratic Party HQ rioting. No-contest plea; 18 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd","arrest_date"=>"2021-06-02","convicted"=>"Yes - no contest","sentence"=>"18 months probation"]]],
    ["name"=>"Kyle Martin Romstad","first_name"=>"Kyle","middle_name"=>"Martin","last_name"=>"Romstad","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Kyle Martin Romstad, age 22, of Portland OR, indicted June 2021 for January 20, 2021 Portland Democratic Party HQ rioting. Acquitted at trial.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd","arrest_date"=>"2021-06-02","convicted"=>"No - acquitted","sentence"=>"Acquitted"]]],

    // MAXIMILIAN cluster - rows 679-681 (Multnomah Dem HQ Nov 8, 2020)
    ["name"=>"Maximilian Jennings","first_name"=>"Maximilian","last_name"=>"Jennings","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Maximilian Jennings, age 23, indicted June 2021 for damaging the Multnomah County Democrats headquarters in Northeast Portland on November 8, 2020. No-contest plea; 12 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st [2 counts]; 164.354 criminal mischief 2nd","arrest_date"=>"2021-06-02","convicted"=>"Yes - no contest","sentence"=>"12 months probation"]]],
    ["name"=>"Thomas Moll-Rocek","first_name"=>"Thomas","last_name"=>"Moll-Rocek","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Moll-Rocek, age 34, indicted June 2021 for the Nov 8 2020 Multnomah Democrats HQ rioting in Northeast Portland. No-contest plea; 18 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd [2 counts]; 162.145 escape 3rd degree","arrest_date"=>"2021-06-02","convicted"=>"Yes - no contest","sentence"=>"18 months probation"]]],
    ["name"=>"James Walker Prettyman","first_name"=>"James","middle_name"=>"Walker","last_name"=>"Prettyman","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Capitalism","Anti-Fascism"],"in_custody"=>false,"released"=>true,"description"=>"James Walker Prettyman, age 25, indicted June 2021 for the Nov 8 2020 Multnomah Democrats HQ rioting in Northeast Portland. Pleaded guilty; 18 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.365 criminal mischief 1st; 164.354 criminal mischief 2nd [2 counts]","arrest_date"=>"2021-06-02","convicted"=>"Yes - guilty plea","sentence"=>"18 months probation"]]],

    // Row 682 - Darrell Anthony Kimberlin (separate Portland case, multi-target)
    ["name"=>"Darrell Anthony Kimberlin","first_name"=>"Darrell","middle_name"=>"Anthony","last_name"=>"Kimberlin","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anarchism","Anti-Capitalism"],"in_custody"=>false,"released"=>true,"description"=>"Darrell Anthony Kimberlin, age 31-33, was indicted on rioting and criminal-mischief charges in two separate Portland cases (June 2021 Democratic Party of Oregon HQ + June 2021 multi-target spree at Chipotle, Umpqua Bank, and a security companys property). Plea deal Nov 23, 2022; 18 months probation.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 166.015 riot; 164.354 criminal mischief 2nd; 164.365 criminal mischief 1st (dismissed) - 2020-2021 Portland anarchist demonstrations against Democratic Party HQ and corporate targets","arrest_date"=>"2021-06-04","convicted"=>"Yes - guilty plea","sentence"=>"18 months probation"]]],

    // Row 683 - Theodore Matthee-OBrien
    ["name"=>"Theodore Adrian Matthee-O Brien","first_name"=>"Theodore","middle_name"=>"Adrian","last_name"=>"Matthee-O Brien","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Police"],"in_custody"=>false,"released"=>true,"description"=>"Theodore Adrian Matthee-O Brien, age 22, a Reed College student, was charged in June 2021 with breaking windows at the Oregon Historical Society during an April 16, 2021 protest over a deadly police shooting at Lent Park. Riot charges dropped; 80 hours community service for separate 2020 interference with a police officer.","cases"=>[["institution_name"=>"Multnomah County District Court","institution_state"=>"Oregon","charges"=>"Oregon state 164.365 criminal mischief 1st [2 counts]; 166.015 riot [2 counts] - April 2021 Portland Lent Park police-shooting protest","arrest_date"=>"2021-06-19","convicted"=>"No - riot charges dropped","sentence"=>"80 hours community service for separate 2020 charge"]]],

    // Row 684 - Thomas Welnicki
    ["name"=>"Thomas Welnicki","first_name"=>"Thomas","last_name"=>"Welnicki","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Welnicki, age 71, of Rockaway Beach NY, made multiple statements to U.S. Capitol Police and Secret Service in 2021 about a desire to kill former President Donald Trump and 12 unnamed members of Congress, citing a $350,000 reward. Federal prosecutors agreed in December 2022 to defer prosecution for one year and dismiss if Welnicki stays out of trouble.","cases"=>[["institution_name"=>"U.S. District Court for the Eastern District of New York","institution_state"=>"New York","charges"=>"18 USC 879(a) threats against former Presidents and other persons - 2021 voicemails to Secret Service","arrest_date"=>"2022-01-07","convicted"=>"No - deferred prosecution","sentence"=>"Deferred prosecution; case to be dismissed on good behavior"]]],

    // Row 685 - Anna Kochakian
    ["name"=>"Anna N. Kochakian","first_name"=>"Anna","last_name"=>"Kochakian","gender"=>"Female","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-Police"],"in_custody"=>false,"released"=>true,"description"=>"Anna Kochakian, age 26, was arrested for tearing a memorial photograph of slain Chicago Officer Ella French from a memorial display at the James R. Thompson Center on August 19, 2021 and discarding it in CTA platform garbage. Pleaded guilty; 2 years probation.","cases"=>[["institution_name"=>"Cook County Circuit Court","institution_state"=>"Illinois","charges"=>"Illinois state criminal damage (felony and misdemeanor) - 2021 desecration of fallen-officer memorial","arrest_date"=>"2022-02-09","convicted"=>"Yes - guilty plea","sentence"=>"2 years probation"]]],

    // Row 686 - Rowan McManigal
    ["name"=>"Rowan McManigal","first_name"=>"Rowan","last_name"=>"McManigal","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-government","Immigrant Rights"],"in_custody"=>false,"released"=>true,"description"=>"Rowan McManigal, age 19, was sentenced April 15, 2022 to 3 years probation under a guilty plea for possession of a hoax destructive device (a self-igniting Molotov cocktail) at a protest outside a Portland ICE facility.","cases"=>[["institution_name"=>"U.S. District Court for the District of Oregon","institution_state"=>"Oregon","charges"=>"18 USC 1038 possession of a hoax destructive device - Portland ICE facility protest","arrest_date"=>"2022-04-15","convicted"=>"Yes - guilty plea","sentence"=>"3 years probation"]]],

    // Row 687 - Matthew Comiskey
    ["name"=>"Matthew Lee Comiskey","first_name"=>"Matthew","middle_name"=>"Lee","last_name"=>"Comiskey","gender"=>"Male","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-Republican"],"in_custody"=>false,"released"=>true,"description"=>"Matthew Lee Comiskey, age 38, of Palm Beach County FL, posted five tweets between August and September 2021 threatening Rep. Lauren Boebert. Pleaded guilty to one count; 15 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 875(c) interstate communications threats [5 counts] - 2021 tweets threatening Rep. Boebert","arrest_date"=>"2022-05-26","incarceration_date"=>"2022-05-26","convicted"=>"Yes - guilty plea","sentence"=>"15 months federal prison"]]],

    // VILLAGRAN cluster (Asheville Aston Park homeless protest, December 2021)
    ["name"=>"Elsa Ann Larson Enstrom","first_name"=>"Elsa","middle_name"=>"Ann Larson","last_name"=>"Enstrom","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Elsa Ann Larson Enstrom, age 35, was indicted in June 2022 with 15 others for a December 2021 Aston Park rally in Asheville NC protesting police removals of homeless people. Pleaded guilty; 45 days community service.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-56 aid and abet a felony; 14-399(E) littering >500 lbs - December 2021 Asheville Aston Park homeless-rights rally","arrest_date"=>"2022-06-27","convicted"=>"Yes - guilty plea","sentence"=>"45 days community service"]]],
    ["name"=>"Elizabeth Ann Flickinger","first_name"=>"Elizabeth","middle_name"=>"Ann","last_name"=>"Flickinger","aka"=>"Pip Flickinger","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Pip Flickinger, indicted June 2022 in the Asheville Aston Park homeless-rights rally case. Voluntary dismissal due to prosecutorial discretion.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Julia Rose Weber","first_name"=>"Julia","middle_name"=>"Rose","last_name"=>"Weber","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Julia Rose Weber, age 21, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Kathryn Anne Hudson","first_name"=>"Kathryn","middle_name"=>"Anne","last_name"=>"Hudson","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Kathryn Anne Hudson, age 29, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Pageant Quinn Nevel","first_name"=>"Pageant","middle_name"=>"Quinn","last_name"=>"Nevel","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Pageant Quinn Nevel, age 28, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-56 aid and abet a felony; 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Amy Elizabeth Hamilton-Thibert","first_name"=>"Amy","middle_name"=>"Elizabeth","last_name"=>"Hamilton-Thibert","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Amy Elizabeth Hamilton-Thibert, age 47, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-56 aid and abet a felony; 14-399(E) littering - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Alexander Jory Bergdahl","first_name"=>"Alexander","middle_name"=>"Jory","last_name"=>"Bergdahl","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Alexander Jory Bergdahl, age 32, indicted June 2022 in the Asheville Aston Park rally case. Pleaded guilty; 30 days community service.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-56 aid and abet a felony; 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"Yes - guilty plea","sentence"=>"30 days community service"]]],
    ["name"=>"Gina Marie Dickhaus","first_name"=>"Gina","middle_name"=>"Marie","last_name"=>"Dickhaus","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Gina Marie Dickhaus, age 30, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-56 aid and abet a felony; 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Sarah Jackson Boddy Norris","first_name"=>"Sarah","middle_name"=>"Jackson Boddy","last_name"=>"Norris","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Sarah Jackson Boddy Norris, age 42, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Erica Jan Deaton","first_name"=>"Erica","middle_name"=>"Jan","last_name"=>"Deaton","gender"=>"Female","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Erica Jan Deaton, age 43, indicted June 2022 in the Asheville Aston Park rally case. Voluntary dismissal.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-27","convicted"=>"No - voluntary dismissal","sentence"=>"Charges dismissed"]]],
    ["name"=>"Nicole A. Matute Villagran","first_name"=>"Nicole","middle_name"=>"A. Matute","last_name"=>"Villagran","gender"=>"Female","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Housing Rights"],"in_custody"=>false,"released"=>true,"description"=>"Nicole A. Matute Villagran, age 21, indicted June 2022 in the Asheville Aston Park rally case.","cases"=>[["institution_name"=>"Buncombe County Superior Court","institution_state"=>"North Carolina","charges"=>"NCGS 14-399(E) littering >500 lbs - Asheville Aston Park rally","arrest_date"=>"2022-06-28","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    // Row 699 - Tiffani Gish
    ["name"=>"Tiffani Shea Gish","first_name"=>"Tiffani","middle_name"=>"Shea","last_name"=>"Gish","aka"=>"Evelyn Salt","gender"=>"Female","state"=>"Texas","era"=>"2020s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Tiffani Shea Gish, age 49, of Houston TX, called a federal judge in Florida three times in 2022 threatening to shoot the judge, send a bomb to the judges house, and shoot and kill the judge in front of her family, claiming to be Evelyn Salt and a federal nuclear agent. Pleaded guilty; 37 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 115(a)(1)(B) influencing federal official by threat; 18 USC 875(c) interstate communications with a threat to kidnap or injure - 2022 calls to a U.S. District Judge","arrest_date"=>"2022-09-27","incarceration_date"=>"2022-09-27","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison"]]],

    // Row 700 - Richard Hernandez
    ["name"=>"Richard Timothy Hernandez","first_name"=>"Richard","middle_name"=>"Timothy","last_name"=>"Hernandez","gender"=>"Male","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-government","Immigrant Rights"],"in_custody"=>false,"released"=>true,"description"=>"Richard Timothy Hernandez, age 56, was sentenced October 4, 2022 to time served on one count of destroying government property during 2020 Portland protests at ICE facilities and federal courthouses; three original counts were reduced to one under a guilty plea.","cases"=>[["institution_name"=>"U.S. District Court for the District of Oregon","institution_state"=>"Oregon","charges"=>"18 USC 1361(3) destruction of government property - 2020 Portland ICE-facility and courthouse protests","arrest_date"=>"2022-10-04","incarceration_date"=>"2022-10-04","convicted"=>"Yes - guilty plea","sentence"=>"Time served"]]],

    // Row 642 - Eric Charron
    ["name"=>"Eric Leonardo Charron","first_name"=>"Eric","middle_name"=>"Leonardo","last_name"=>"Charron","gender"=>"Male","race"=>"White","state"=>"West Virginia","era"=>"2010s","ideologies"=>["Election2020"],"in_custody"=>false,"released"=>true,"description"=>"Eric Leonardo Charron, age 42, of Kansas City, was clocked driving 130 mph near Bruceton Mills WV; he told police he was running late to a dinner he was invited to by President Trump. Pleaded guilty in Preston County Magistrate Court to reckless driving and being a prohibited person in possession of a firearm; given credit for 36 days served (~3 months total).","cases"=>[["institution_name"=>"Preston County Magistrate Court","institution_state"=>"West Virginia","charges"=>"WV Code 61-7-7 prohibited person in possession of a firearm; 17C-5-3 reckless driving","arrest_date"=>"2019-03-27","incarceration_date"=>"2019-03-27","convicted"=>"Yes - guilty plea","sentence"=>"~3 months credited (time served)"]]],

    // KBP7 - rows 629-635 (Kings Bay Plowshares - likely in DB already, will EXISTS)
    // Listed here so the script attempts and reports them
    ["name"=>"Stephen Michael Kelly","first_name"=>"Stephen","middle_name"=>"Michael","last_name"=>"Kelly","gender"=>"Male","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Stephen Michael Kelly, age 69, was one of the Kings Bay Plowshares 7 (KBP7) Catholic anti-nuclear activists who broke into Kings Bay Naval Submarine Base in St. Marys GA on April 4-5, 2018 to protest Trident-class nuclear weapons. Convicted on all four counts; 33 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"18 USC 371 conspiracy; 18 USC 1363 destruction of property on a naval installation; 18 USC 1361 depredation of government property; 18 USC 1382 trespass - April 2018 KBP7 Kings Bay Naval Submarine Base action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","sentenced_date"=>"2020-10-15","convicted"=>"Yes - jury verdict","sentence"=>"33 months federal prison"]]],
    ["name"=>"Mark Peter Colville","first_name"=>"Mark","middle_name"=>"Peter","last_name"=>"Colville","gender"=>"Male","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Mark Peter Colville, age 56, KBP7 defendant; 18 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"KBP7 charges - 18 USC 371, 1363, 1361, 1382 - April 2018 Kings Bay Naval Submarine Base action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","convicted"=>"Yes - jury verdict","sentence"=>"18 months federal prison"]]],
    ["name"=>"Clare Therese Grady","first_name"=>"Clare","middle_name"=>"Therese","last_name"=>"Grady","gender"=>"Female","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Clare Therese Grady, age 59, KBP7 defendant; 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"KBP7 charges - 18 USC 371, 1363, 1361, 1382 - April 2018 Kings Bay Naval Submarine Base action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","convicted"=>"Yes - jury verdict","sentence"=>"12 months federal prison"]]],
    ["name"=>"Martha Hennessy","first_name"=>"Martha","last_name"=>"Hennessy","gender"=>"Female","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Martha Hennessy, age 62, KBP7 defendant; 10 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"KBP7 charges - 18 USC 371, 1363, 1361, 1382 - April 2018 Kings Bay action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","convicted"=>"Yes - jury verdict","sentence"=>"10 months federal prison"]]],
    ["name"=>"Patrick M. O Neill","first_name"=>"Patrick","last_name"=>"O Neill","gender"=>"Male","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Patrick M. O Neill, age 62, KBP7 defendant; 14 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"KBP7 charges - April 2018 Kings Bay action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","convicted"=>"Yes - jury verdict","sentence"=>"14 months federal prison"]]],
    ["name"=>"Carmen Trotta","first_name"=>"Carmen","last_name"=>"Trotta","gender"=>"Male","race"=>"White","state"=>"Georgia","era"=>"2010s","ideologies"=>["Anti-Nuclear","Anti-War"],"affiliation"=>["Plowshares Movement"],"in_custody"=>false,"released"=>true,"description"=>"Carmen Trotta, age 55, KBP7 defendant; 14 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Georgia","charges"=>"KBP7 charges - April 2018 Kings Bay action","arrest_date"=>"2018-05-02","incarceration_date"=>"2018-05-02","convicted"=>"Yes - jury verdict","sentence"=>"14 months federal prison"]]],
    // Elizabeth McAlister already in DB
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "Prosecution Project rows 407, 622-700 import complete."
