#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_7.sh
#
# Seventh batch (rows 701-800). Mostly 2022-2025 leftist/identity-
# focused prosecutions: Israel-Gaza War campus actions, Riverside
# courthouse vandals, Asheville Vance Monument explosives, Pittsburgh
# DiPippas, Ohio Boeing blockade, UMich TAHRIR cluster, Streetvendor
# Justice8, plus older entries (Kaczynski, Colin Ferguson, Westerman
# 4, Floyd Corkins, NBPP Ferguson, Alcoff). Will report EXISTS for
# already-in-DB entries (Kaczynski, Ferguson, Ferrier likely).
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"Kevin C. Butler","first_name"=>"Kevin","middle_name"=>"C.","last_name"=>"Butler","aka"=>"Kevin A. Butler","gender"=>"Male","race"=>"Black","state"=>"Virginia","era"=>"2020s","ideologies"=>["Anarchism","Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Kevin C. Butler, 44, was indicted December 15, 2022 on seven counts of threatening the President while a patient at Catawba Hospital, a Virginia state mental health facility. He made phone calls to a state probation/parole office threatening to kill then-President Biden and then-VP Harris. He had a prior 2014 conviction for similar threats against Obama and Biden. Insanity defense rejected; sentenced to 60 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Virginia","charges"=>"18 USC 871 Threats Against the President of the United States and Successors to the Presidency [7 counts]","arrest_date"=>"2022-12-15","convicted"=>"Yes - jury verdict","sentence"=>"60 months federal prison"]]],

    ["name"=>"Aida Yagmur Aston","first_name"=>"Aida Yagmur","last_name"=>"Aston","gender"=>"Female","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Aida Yagmur Aston, 32, was one of six pro-abortion demonstrators charged for a July 30, 2022 action in which they painted green handprints on the Riverside Historic Courthouse following the overturning of Roe v. Wade. Felony vandalism reduced to misdemeanor; entered diversion program with 10-page essay requirement.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism (Felony, reduced to misdemeanor) - July 30 2022 Historic Courthouse green-handprint action","arrest_date"=>"2023-01-12","convicted"=>"Yes - guilty after blind plea","sentence"=>"Diversion program, no jail"]]],

    ["name"=>"Alexander Jacob Castro","first_name"=>"Alexander","middle_name"=>"Jacob","last_name"=>"Castro","gender"=>"Male","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Alexander Jacob Castro, 23, Riverside Historic Courthouse green-handprint defendant, July 30 2022. Felony reduced to misdemeanor; diversion program.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism","arrest_date"=>"2023-01-12","convicted"=>"Yes - guilty after blind plea","sentence"=>"Diversion program, no jail"]]],

    ["name"=>"Kamile Dincsoy","first_name"=>"Kamile","last_name"=>"Dincsoy","gender"=>"Female","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Kamile Dincsoy, 48, Riverside Historic Courthouse green-handprint defendant, July 30 2022. Failed to appear for trial; bench warrant issued.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism","arrest_date"=>"2023-01-12","convicted"=>"No - charged but not tried, fugitive","sentence"=>"Bench warrant issued"]]],

    ["name"=>"Alexandria Ty Fite","first_name"=>"Alexandria","middle_name"=>"Ty","last_name"=>"Fite","gender"=>"Female","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Alexandria Ty Fite, 32, Riverside Historic Courthouse green-handprint defendant, July 30 2022.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism","arrest_date"=>"2023-01-12","convicted"=>"Yes - guilty after blind plea","sentence"=>"Diversion program, no jail"]]],

    ["name"=>"Elise Saramarielle Kelder","first_name"=>"Elise","middle_name"=>"Saramarielle","last_name"=>"Kelder","gender"=>"Female","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Elise Saramarielle Kelder, 28, Riverside Historic Courthouse green-handprint defendant, July 30 2022.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism","arrest_date"=>"2023-01-12","convicted"=>"Yes - guilty after blind plea","sentence"=>"Diversion program, no jail"]]],

    ["name"=>"Oliver Edu Solares Herrera","first_name"=>"Oliver","middle_name"=>"Edu Solares","last_name"=>"Herrera","gender"=>"Male","state"=>"California","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Rise Up 4 Abortion Rights"],"in_custody"=>false,"released"=>true,"description"=>"Oliver Edu Solares Herrera, 24, Riverside Historic Courthouse green-handprint defendant, July 30 2022.","cases"=>[["institution_name"=>"Riverside County Superior Court","institution_state"=>"California","charges"=>"California PC 594(a) Vandalism","arrest_date"=>"2023-01-12","convicted"=>"Yes - guilty after blind plea","sentence"=>"Diversion program, no jail"]]],

    ["name"=>"Chioke Auden Fugate","first_name"=>"Chioke","middle_name"=>"Auden","last_name"=>"Fugate","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Chioke Auden Fugate, 23, was indicted March 6, 2023 with co-defendant Duncan Andrew Small after they allegedly lit and threw two explosive devices at the former Vance Monument in downtown Asheville on July 4, 2022 as fireworks-show crowds dispersed. Pleaded guilty; sentenced to roughly 70 days.","cases"=>[["institution_name"=>"North Carolina state prison (location varied)","institution_state"=>"North Carolina","charges"=>"NC state Possession of Pyrotechnics Without License; Going Armed to the Terror of the People; Attempted Damage to Real Property With an Explosive Device - July 4 2022 Vance Monument explosive throwing","arrest_date"=>"2023-03-06","convicted"=>"Yes - guilty plea","sentence"=>"Approximately 70 days (2.3 months)"]]],

    ["name"=>"Duncan Andrew Small","first_name"=>"Duncan","middle_name"=>"Andrew","last_name"=>"Small","gender"=>"Male","race"=>"White","state"=>"North Carolina","era"=>"2020s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Duncan Andrew Small, 30, Asheville co-defendant of Chioke Fugate; lit and threw explosive devices at the former Vance Monument July 4, 2022. Also charged with discharging a weapon within city limits at a June 26, 2022 protest. Pleaded guilty; no prison time.","cases"=>[["institution_name"=>"North Carolina state court","institution_state"=>"North Carolina","charges"=>"NC state Possession of Pyrotechnics Without License; Going Armed to the Terror of the People; Attempted Damage to Real Property With an Explosive Device - July 4 2022","arrest_date"=>"2023-03-06","convicted"=>"Yes - guilty plea","sentence"=>"No prison time"]]],

    ["name"=>"Brian DiPippa","first_name"=>"Brian","last_name"=>"DiPippa","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-fascism","Trans Liberation"],"in_custody"=>true,"released"=>false,"description"=>"Brian DiPippa, 36, of Pittsburgh, with wife Krystal DiPippa, ignited and threw two smoke devices and one firework into a crowd of police officers during a University of Pittsburgh protest against a debate featuring Michael Knowles on transgender issues. Three officers injured. Pleaded guilty; sentenced to 60 months federal prison; ordered to pay $1,400 to the University and $47,284 to an injured officer (joint with Krystal).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3) Obstruction of Law Enforcement During Civil Disorder; 18 USC 371 Conspiracy; 18 USC 844(h)(1) Use of an Explosive to Commit a Federal Felony - University of Pittsburgh anti-Knowles protest","arrest_date"=>"2023-06-28","convicted"=>"Yes - guilty plea","sentence"=>"60 months federal prison; joint restitution"]]],

    ["name"=>"Krystal DiPippa","first_name"=>"Krystal","last_name"=>"DiPippa","gender"=>"Female","race"=>"White","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Anti-fascism","Trans Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Krystal DiPippa, 40, of Pittsburgh, wife of Brian DiPippa; co-defendant in the June 2023 University of Pittsburgh protest explosive-throwing case. Sentenced to three years probation; joint $48,684 restitution with husband.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"18 USC 231(a)(3); 18 USC 371; 18 USC 844(h)(1) - University of Pittsburgh anti-Knowles protest","arrest_date"=>"2023-06-28","convicted"=>"Yes - guilty plea","sentence"=>"3 years probation; joint restitution"]]],

    ["name"=>"Pascale Cecile Veronique Ferrier","first_name"=>"Pascale","middle_name"=>"Cecile Veronique","last_name"=>"Ferrier","aka"=>"Free Rebel Spirit","gender"=>"Female","race"=>"White","state"=>"New York","era"=>"2020s","ideologies"=>["Anti-Trump"],"in_custody"=>true,"released"=>false,"description"=>"Pascale Cecile Veronique Ferrier, a 55-year-old dual citizen of Canada and France, was sentenced August 17, 2023 to 262 months federal prison plus lifetime supervised release for sending homemade-ricin letters in September 2020 to then-President Trump at the White House and to eight Texas state law enforcement officials. Detained at Buffalo, NY port of entry with a loaded firearm and a knife.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 175(a) Prohibitions With Respect to Biological Weapons [9 charges]; 18 USC 871(a) Threatening to Kill or Injure the President - September 2020 ricin letters","arrest_date"=>"2020-09-20","sentenced_date"=>"2023-08-17","convicted"=>"Yes - guilty plea","sentence"=>"262 months federal prison + lifetime supervised release"]]],

    ["name"=>"Sophie Marika Ross","first_name"=>"Sophie","middle_name"=>"Marika","last_name"=>"Ross","gender"=>"Female","race"=>"White","state"=>"New Hampshire","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"affiliation"=>["Palestine Action US"],"in_custody"=>false,"released"=>true,"description"=>"Sophie Marika Ross, 22, co-founder of Palestine Action US, was indicted February 23, 2024 for the November 20, 2023 Elbit Systems of America vandalism in Merrimack NH (smashed skylight, ventilation system, paint on building; ~$95,645 damage). Pleaded guilty to misdemeanor charges November 14, 2024; sentenced to 12 months at Valley Street House of Corrections, all but 60 days deferred.","cases"=>[["institution_name"=>"Valley Street House of Corrections","institution_city"=>"Manchester","institution_state"=>"New Hampshire","charges"=>"NH RSA 634:2 Conspiracy to Commit Criminal Mischief; NH RSA 635:2 Criminal Trespass [misdemeanors] - Nov 20 2023 Elbit Systems vandalism","arrest_date"=>"2024-02-23","sentenced_date"=>"2024-11-14","convicted"=>"Yes - guilty plea","sentence"=>"12 months (60 days served, balance deferred)"]]],

    ["name"=>"Calla Mairead Walsh","first_name"=>"Calla","middle_name"=>"Mairead","last_name"=>"Walsh","gender"=>"Female","race"=>"White","state"=>"New Hampshire","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"affiliation"=>["Palestine Action US"],"in_custody"=>false,"released"=>true,"description"=>"Calla Mairead Walsh, 19, of Cambridge MA, Palestine Action US member; co-defendant in the November 2023 Elbit Systems of America vandalism in Merrimack NH. Sentenced November 14, 2024 to 12 months (60 days served, balance deferred).","cases"=>[["institution_name"=>"Valley Street House of Corrections","institution_city"=>"Manchester","institution_state"=>"New Hampshire","charges"=>"NH RSA 634:2 Conspiracy to Commit Criminal Mischief; NH RSA 635:2 Criminal Trespass - Nov 2023 Elbit vandalism","arrest_date"=>"2024-02-23","sentenced_date"=>"2024-11-14","convicted"=>"Yes - guilty plea","sentence"=>"12 months (60 days served, balance deferred)"]]],

    ["name"=>"Bridget Irene Shergalis","first_name"=>"Bridget","middle_name"=>"Irene","last_name"=>"Shergalis","gender"=>"Female","state"=>"New Hampshire","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"affiliation"=>["Palestine Action US"],"in_custody"=>false,"released"=>true,"description"=>"Bridget Irene Shergalis, 27, of Dayville CT, Palestine Action US member; co-defendant in the November 2023 Elbit Systems vandalism in Merrimack NH. Sentenced November 14, 2024 to 12 months (60 days served, balance deferred).","cases"=>[["institution_name"=>"Valley Street House of Corrections","institution_city"=>"Manchester","institution_state"=>"New Hampshire","charges"=>"NH RSA 634:2 Conspiracy to Commit Criminal Mischief; NH RSA 635:2 Criminal Trespass - Nov 2023 Elbit vandalism","arrest_date"=>"2024-02-23","sentenced_date"=>"2024-11-14","convicted"=>"Yes - guilty plea","sentence"=>"12 months (60 days served, balance deferred)"]]],

    ["name"=>"Paige Belanger","first_name"=>"Paige","last_name"=>"Belanger","gender"=>"Female","race"=>"White","state"=>"New Hampshire","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"affiliation"=>["Palestine Action US"],"in_custody"=>false,"released"=>true,"description"=>"Paige Belanger, 33, co-founder of Palestine Action US, of Alford MA; co-defendant in the November 2023 Elbit Systems vandalism in Merrimack NH. Threw paint and smashed windows/glass door at ground level. Sentenced November 14, 2024 to 12 months (60 days served, balance deferred).","cases"=>[["institution_name"=>"Valley Street House of Corrections","institution_city"=>"Manchester","institution_state"=>"New Hampshire","charges"=>"NH RSA 634:2 Conspiracy to Commit Criminal Mischief; NH RSA 635:2 Criminal Trespass - Nov 2023 Elbit vandalism","arrest_date"=>"2024-05-21","sentenced_date"=>"2024-11-14","convicted"=>"Yes - guilty plea","sentence"=>"12 months (60 days served, balance deferred)"]]],

    ["name"=>"John Robert Mazurek","first_name"=>"John","middle_name"=>"Robert","last_name"=>"Mazurek","aka"=>"Jack","gender"=>"Male","race"=>"White","state"=>"Georgia","era"=>"2020s","ideologies"=>["Anti-police","Environmental Activism"],"affiliation"=>["Defend the Atlanta Forest"],"in_custody"=>false,"released"=>true,"description"=>"John Robert Mazurek, 30, was arrested February 2, 2024 in Atlanta GA and charged with first-degree arson for allegedly torching eight police vehicles in July 2023 as a protest against the proposed Atlanta Police training facility (Cop City). In March 2026, took an Alford plea to a reduced charge of criminal damage to property; sentenced to 10 years probation.","cases"=>[["institution_name"=>"Georgia state court","institution_state"=>"Georgia","charges"=>"OCGA 16-7-60 Arson First-degree (reduced); criminal damage to property - July 2023 APD vehicle arson","arrest_date"=>"2024-02-02","convicted"=>"Yes - Alford plea","sentence"=>"10 years probation"]]],

    ["name"=>"Nancy Jane Epling","first_name"=>"Nancy","middle_name"=>"Jane","last_name"=>"Epling","gender"=>"Female","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>false,"released"=>true,"description"=>"Nancy Jane Epling, 32, was one of five protesters who blocked access roads to a Boeing facility in Heath OH on March 11, 2024 using sleeping-dragon lockboxes. No-contest plea; sentenced to ~30 days (1 month).","cases"=>[["institution_name"=>"Licking County Jail","institution_state"=>"Ohio","charges"=>"ORC 2917.14 Unlawfully Impeding Passage of an Emergency Response Vehicle - March 2024 Boeing Heath blockade","arrest_date"=>"2024-03-11","convicted"=>"Yes - no contest","sentence"=>"~30 days"]]],

    ["name"=>"Joel Atkinson","first_name"=>"Joel","last_name"=>"Atkinson","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>false,"released"=>true,"description"=>"Joel Atkinson, 34, March 2024 Boeing Heath OH blockade defendant. Pleaded guilty; ~30 days.","cases"=>[["institution_name"=>"Licking County Jail","institution_state"=>"Ohio","charges"=>"ORC 2917.14 Unlawfully Impeding Passage of an Emergency Response Vehicle - March 2024 Boeing Heath blockade","arrest_date"=>"2024-03-11","convicted"=>"Yes - guilty plea","sentence"=>"~30 days"]]],

    ["name"=>"Samuel Holman-Smith","first_name"=>"Samuel","last_name"=>"Holman-Smith","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>false,"released"=>true,"description"=>"Samuel Holman-Smith, 27, March 2024 Boeing Heath OH blockade defendant. Pleaded guilty; ~30 days.","cases"=>[["institution_name"=>"Licking County Jail","institution_state"=>"Ohio","charges"=>"ORC 2917.14 Unlawfully Impeding Passage - March 2024 Boeing Heath blockade","arrest_date"=>"2024-03-11","convicted"=>"Yes - guilty plea","sentence"=>"~30 days"]]],

    ["name"=>"Graham Ball","first_name"=>"Graham","last_name"=>"Ball","gender"=>"Male","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>false,"released"=>true,"description"=>"Graham Ball, 26, March 2024 Boeing Heath OH blockade defendant. Pleaded guilty; ~30 days.","cases"=>[["institution_name"=>"Licking County Jail","institution_state"=>"Ohio","charges"=>"ORC 2917.14 Unlawfully Impeding Passage - March 2024 Boeing Heath blockade","arrest_date"=>"2024-03-11","convicted"=>"Yes - guilty plea","sentence"=>"~30 days"]]],

    ["name"=>"Melissa Brunn","first_name"=>"Melissa","last_name"=>"Brunn","gender"=>"Female","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>false,"released"=>true,"description"=>"Melissa Brunn, 39, March 2024 Boeing Heath OH blockade defendant. No-contest plea on Failure to Comply; ~30 days.","cases"=>[["institution_name"=>"Licking County Jail","institution_state"=>"Ohio","charges"=>"ORC 2921.331 Failure to Comply - March 2024 Boeing Heath blockade","arrest_date"=>"2024-03-11","convicted"=>"Yes - no contest","sentence"=>"~30 days"]]],

    ["name"=>"Kyle Benjamin Douglas Calvert","first_name"=>"Kyle","middle_name"=>"Benjamin Douglas","last_name"=>"Calvert","gender"=>"Male","race"=>"White","state"=>"Alabama","era"=>"2020s","ideologies"=>["Anti-fascism"],"affiliation"=>["Antifa"],"in_custody"=>true,"released"=>false,"description"=>"Kyle Benjamin Douglas Calvert, 26, of Ironside AL, placed and detonated an explosive device outside the Alabama Attorney Generals Office in Montgomery on February 24, 2024. CCTV captured him placing Support Your Local Antifa stickers around the area before the bombing. Pleaded guilty; sentenced to 108 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Alabama","charges"=>"18 USC 844(i) Malicious Use of an Explosive; 26 USC 5861(d) Possession of an Unregistered Firearm/Destructive Device; 18 USC 844(i) Arson - Feb 2024 Alabama AG Office bombing","arrest_date"=>"2024-04-09","incarceration_date"=>"2024-04-09","convicted"=>"Yes - guilty plea","sentence"=>"108 months federal prison"]]],

    ["name"=>"Leo A. Randle","first_name"=>"Leo","middle_name"=>"A.","last_name"=>"Randle","gender"=>"Male","race"=>"White","state"=>"Wisconsin","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Leo A. Randle, 19, was arrested May 1, 2024 at the University of Wisconsin Madison Palestine encampment for hitting a state trooper in the face with a skateboard. Charges dismissed.","cases"=>[["institution_name"=>"Dane County Circuit Court","institution_state"=>"Wisconsin","charges"=>"Wis Stat 940.203(2) Battery or Threat to Judge, Prosecutor, or Law Enforcement Officer - May 2024 UW Madison Gaza encampment","arrest_date"=>"2024-05-03","convicted"=>"No - charges dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Trevor H. Carter","first_name"=>"Trevor","middle_name"=>"H.","last_name"=>"Carter","gender"=>"Male","race"=>"Black","state"=>"Wisconsin","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Trevor H. Carter, 23, was arrested May 1, 2024 at the UW Madison Palestine encampment for spitting on a Madison Police officers boot. Charges dropped.","cases"=>[["institution_name"=>"Dane County Circuit Court","institution_state"=>"Wisconsin","charges"=>"Wis Stat 947.01(1) Disorderly Conduct - May 2024 UW Madison Gaza encampment","arrest_date"=>"2024-05-03","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Caleb A. Brown","first_name"=>"Caleb","middle_name"=>"A.","last_name"=>"Brown","gender"=>"Male","race"=>"White","state"=>"Wisconsin","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Caleb A. Brown, 24, was arrested May 1, 2024 at the UW Madison Palestine encampment after grabbing a Madison police officers baton and trying to wrestle it away. Disarming charge dismissed; charged for obstructing/resisting.","cases"=>[["institution_name"=>"Dane County Circuit Court","institution_state"=>"Wisconsin","charges"=>"Wis Stat 941.21 Attempt Disarming Peace Officer (dismissed); Wis Stat 946.41(1) Obstructing/Resisting an Officer - May 2024 UW Madison Gaza encampment","arrest_date"=>"2024-05-03","convicted"=>"Yes on resisting; disarming dismissed","sentence"=>"Local sentence"]]],

    ["name"=>"Elijah Michael Lane","first_name"=>"Elijah","middle_name"=>"Michael","last_name"=>"Lane","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Elijah Michael Lane, 29, was charged May 3, 2024 with first-degree burglary, assaulting a public safety officer, fourth-degree assault, ESG/tear gas/mace use, and misdemeanors stemming from the Portland State University anti-Boeing/Israel-Gaza protest. All charges dismissed at disposition March 10, 2025.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 164.225 Burglary I; 163.208 Assaulting a Public Safety Officer; 163.213 Use of ESG/Tear Gas/Mace I; 163.160(2) Assault IV; 162.315 Resisting Arrest; 163.195 Recklessly Endangering [4 counts] - May 2024 PSU anti-Boeing protest","arrest_date"=>"2024-05-03","convicted"=>"No - all charges dismissed","sentence"=>"Dismissed 03/10/2025"]]],

    ["name"=>"Will Parzybok","first_name"=>"Will","last_name"=>"Parzybok","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Will Parzybok, 23, was charged May 3, 2024 with assaulting a public safety officer, unlawful use of a weapon, and interfering with a peace officer at the Portland State University anti-Boeing/Israel-Gaza protest. All charges dismissed February 10, 2025; paid $20 to Defense Fund PDX.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 163.208 Assaulting a Public Safety Officer; 166.220 Unlawful Use of a Weapon; 162.247 Interfering w/ Peace/Parole Officer - May 2024 PSU anti-Boeing protest","arrest_date"=>"2024-05-03","convicted"=>"No - all charges dismissed","sentence"=>"Dismissed 02/10/2025"]]],

    ["name"=>"Maysoun Batley","first_name"=>"Maysoun","last_name"=>"Batley","gender"=>"Female","state"=>"Massachusetts","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["Students for Justice in Palestine (SJP)"],"in_custody"=>false,"released"=>true,"description"=>"Maysoun Batley, co-president of UMass Amherst Students for Justice in Palestine, was target of a UMass Amherst PD criminal-complaint application in August 2024 for inciting to riot and assault on a police officer (alleged spitting) related to the May 7, 2024 Gaza protest encampment. UMass PD later rescinded the application; no charges officially brought.","cases"=>[["institution_name"=>"Hampshire County District Court","institution_state"=>"Massachusetts","charges"=>"MGLc 264:11 Incite to Riot; MGLc 265:13D Assault and Battery on a Police Officer - May 2024 UMass Gaza encampment","arrest_date"=>"2024-05-07","convicted"=>"No - charges rescinded","sentence"=>"Application withdrawn"]]],

    ["name"=>"Ruya Hayezen","first_name"=>"Ruya","last_name"=>"Hayezen","gender"=>"Female","state"=>"Massachusetts","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["Students for Justice in Palestine (SJP)"],"in_custody"=>false,"released"=>true,"description"=>"Ruya Hayezen, co-president of UMass Amherst Students for Justice in Palestine, was target of a UMass Amherst PD criminal-complaint application in August 2024 for inciting to riot related to the May 7, 2024 Gaza protest encampment. UMass PD later rescinded the application.","cases"=>[["institution_name"=>"Hampshire County District Court","institution_state"=>"Massachusetts","charges"=>"MGLc 264:11 Incite to Riot - May 2024 UMass Gaza encampment","arrest_date"=>"2024-05-07","convicted"=>"No - rescinded","sentence"=>"Application withdrawn"]]],

    ["name"=>"James Jones","first_name"=>"James","last_name"=>"Jones","gender"=>"Male","race"=>"White","state"=>"Indiana","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"James Jones, 21, was arrested April 25, 2024 at Indiana University Bloomington Dunn Meadow Gaza protests for allegedly biting a police officer. Only felony charge from the IU Gaza Protest; charges dropped after fine paid.","cases"=>[["institution_name"=>"Monroe County Circuit Court","institution_state"=>"Indiana","charges"=>"IN Code 35-42-2-1(c)(1)/F6 Battery Against a Public Safety Official - April 2024 IU Bloomington Gaza protest","arrest_date"=>"2024-04-25","convicted"=>"No - dropped after fine","sentence"=>"Dropped"]]],

    ["name"=>"Donald Mark Johnson","first_name"=>"Donald","middle_name"=>"Mark","last_name"=>"Johnson","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Donald Mark Johnson, 33, was arrested June 26, 2024 at the University of Pittsburgh Gaza divestment protest for aggravated assault and related charges. Pleaded guilty to lesser charges; 24 months probation.","cases"=>[["institution_name"=>"Allegheny County Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"18 Pa.C.S. 2702:A3 Aggravated Assault (lesser); 18 Pa.C.S. 5104 Resisting Arrest; 18 Pa.C.S. 2705 Recklessly Endangering Another Person - June 2024 Pitt Gaza protest","arrest_date"=>"2024-07-26","convicted"=>"Yes - guilty plea","sentence"=>"24 months probation"]]],

    ["name"=>"Julia Lankisch","first_name"=>"Julia","last_name"=>"Lankisch","gender"=>"Female","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["XU Free Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Julia Lankisch, 22, of Cincinnati, was charged May 11, 2024 with felony conspiracy while wearing a disguise (medical face masks) and misdemeanor disorderly conduct/trespass during a Xavier University Palestine protest. Felony count ignored by grand jury; misdemeanor proceeded.","cases"=>[["institution_name"=>"Hamilton County Court","institution_state"=>"Ohio","charges"=>"ORC 3761.12 Conspiracy While Wearing Disguise (no-billed); ORC 2917.11 Disorderly Conduct - May 2024 Xavier Gaza protest","arrest_date"=>"2024-08-15","convicted"=>"Yes on misdemeanor","sentence"=>"No prison"]]],

    ["name"=>"Sophia Dempsey","first_name"=>"Sophia","last_name"=>"Dempsey","aka"=>"Soup","gender"=>"Female","race"=>"White","state"=>"Ohio","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["XU Free Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Sophia Dempsey, 22, of Cincinnati, co-defendant of Julia Lankisch in the May 2024 Xavier University Palestine protest. Felony conspiracy-while-disguised count no-billed; misdemeanor proceeded.","cases"=>[["institution_name"=>"Hamilton County Court","institution_state"=>"Ohio","charges"=>"ORC 3761.12 (no-billed); ORC 2917.11 Disorderly Conduct - May 2024 Xavier Gaza protest","arrest_date"=>"2024-08-15","convicted"=>"Yes on misdemeanor","sentence"=>"No prison"]]],

    ["name"=>"Asad Ahmed Siddiqui","first_name"=>"Asad","middle_name"=>"Ahmed","last_name"=>"Siddiqui","gender"=>"Male","race"=>"South Asian","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Asad Ahmed Siddiqui, 26, was charged in November 2024 with felony resisting arrest and trespassing for participation in May 2024 University of Michigan Gaza protests; the encampment was organized by the TAHRIR Coalition. All charges dropped by Michigan AG May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1) Assaulting/Resisting/Obstructing Police Officer; MCL 750.552 Trespassing - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed 05/05/2025"]]],

    ["name"=>"Michael David Mueller","first_name"=>"Michael","middle_name"=>"David","last_name"=>"Mueller","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Michael David Mueller, 28, charged Nov 2024 with felony resisting arrest and trespassing for May 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Oliver Kozler","first_name"=>"Oliver","last_name"=>"Kozler","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Oliver Kozler, 22, UMich student, charged Nov 2024 with felony resisting arrest and trespassing for May 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Avi Benjamin Tachna-Fram","first_name"=>"Avi","middle_name"=>"Benjamin","last_name"=>"Tachna-Fram","gender"=>"Male","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Avi Benjamin Tachna-Fram, 25, charged Nov 2024 with felony resisting arrest and trespassing for May 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Henry David Mackeen-Shapiro","first_name"=>"Henry","middle_name"=>"David","last_name"=>"Mackeen-Shapiro","gender"=>"Male","race"=>"White","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Henry David Mackeen-Shapiro, 21, charged Nov 2024 with felony resisting arrest and trespassing for May 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Rhiannon Willow","first_name"=>"Rhiannon","last_name"=>"Willow","gender"=>"Female","race"=>"White","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Rhiannon Willow, 29, UMich PhD student and physics research assistant, charged Nov 2024 with felony resisting arrest and trespassing for May 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - May 2024 UMich Gaza encampment","arrest_date"=>"2024-09-11","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Samantha Rose Lewis","first_name"=>"Samantha","middle_name"=>"Rose","last_name"=>"Lewis","aka"=>"Sammie Lewis","gender"=>"Female","race"=>"Black","state"=>"Michigan","era"=>"2020s","ideologies"=>["Pro-Palestine"],"affiliation"=>["TAHRIR Coalition"],"in_custody"=>false,"released"=>true,"description"=>"Samantha Lewis, 28, charged December 2024 with felony resisting arrest and trespassing for August 2024 UMich Gaza protests. Charges dismissed May 5, 2025.","cases"=>[["institution_name"=>"Washtenaw County Circuit Court","institution_state"=>"Michigan","charges"=>"MCL 750.81d(1); MCL 750.552 - Aug 2024 UMich Gaza encampment","arrest_date"=>"2024-12-27","convicted"=>"No - dismissed","sentence"=>"Dismissed"]]],

    ["name"=>"Zaid Mohammed Mahdawi","first_name"=>"Zaid","middle_name"=>"Mohammed","last_name"=>"Mahdawi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"District of Columbia","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Zaid Mohammed Mahdawi, 26, climbed the Christopher Columbus statue in DCs Columbus Circle on July 24, 2024 and spray-painted HAMAS IS COMIN with an inverted red triangle. Pleaded guilty; sentenced to 10 days, 6 months supervision, 80 hours community service, $1,500 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 1361 Destruction of Government Property - July 2024 Columbus statue vandalism","arrest_date"=>"2024-10-02","convicted"=>"Yes - guilty plea","sentence"=>"10 days; 6 months supervision; 80 hours community service; $1,500 restitution"]]],

    ["name"=>"Van L. Mayes","first_name"=>"Van","middle_name"=>"L.","last_name"=>"Mayes","aka"=>"Vaun L. Mayes","gender"=>"Male","race"=>"Black","state"=>"Wisconsin","era"=>"2010s","ideologies"=>["Anti-police","Black Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Van L. Mayes, 37, of Milwaukee, allegedly planned to firebomb the Milwaukee PD District 7 station during the August 2016 Sherman Park rioting (sparked by the fatal police shooting of Sylville Smith). The firebombing did not occur. Faced 2018-2019 indictments for arson, firearms, and civil disorder; pleaded guilty in 2024 Bill of Information to using interstate facility to organize a riot. Sentenced October 2024 to time served (92 months).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"18 USC 844(i) Arson; 18 USC 922(g) Felon in Possession of a Firearm; 18 USC 924(c)(1)(B)(ii) Possession of a Destructive Device; 18 USC 844(m) Conspiracy to Commit Arson; 18 USC 2101 Use of Interstate Facility to Organize a Riot - 2016 Sherman Park firebombing plot","arrest_date"=>"2018-07-02","convicted"=>"Yes - guilty plea","sentence"=>"92 months federal prison (time served)"]]],

    ["name"=>"Victor H. Smith","first_name"=>"Victor","middle_name"=>"H.","last_name"=>"Smith","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Victor H. Smith, 22, was sentenced November 18, 2024 to 12 months conditional release and 100 hours community service via guilty plea, for locking arms with other protesters to protect the UIUC Gaza Solidarity encampment from destruction by university police.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action; 720 ILCS 5/31-1(a)(2) Obstructing a Peace Officer - UIUC Gaza encampment","arrest_date"=>"2024-11-18","sentenced_date"=>"2024-11-18","convicted"=>"Yes - guilty plea","sentence"=>"12 months conditional release; 100 hours community service"]]],

    ["name"=>"Martin Leonel Perez Castro","first_name"=>"Martin","middle_name"=>"Leonel","last_name"=>"Perez Castro","aka"=>"Richard","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"New York","era"=>"2020s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>true,"released"=>false,"description"=>"Martin Leonel Perez Castro alias Richard, 53, commander of the FARC 30th Front in Colombia, was sentenced November 21, 2024 to 252 months federal prison after his guilty plea to international cocaine distribution conspiracy and related narco-terrorism / firearms charges.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"21 USC 963 International Cocaine Distribution Conspiracy; 21 USC 848 Continuing Criminal Enterprise [2 counts]; 18 USC 924(c) Firearms in Furtherance of Drug Trafficking - FARC 30th Front commander","sentenced_date"=>"2024-11-21","convicted"=>"Yes - guilty plea","sentence"=>"252 months federal prison"]]],

    ["name"=>"Joseph M. Kleckner","first_name"=>"Joseph","middle_name"=>"M.","last_name"=>"Kleckner","gender"=>"Male","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Joseph M. Kleckner, 25, was sentenced January 9, 2025 to 12 months conditional release and 100 hours community service via guilty plea for locking arms to protect the UIUC Gaza Solidarity encampment.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action; 720 ILCS 5/31-1(a)(2) Obstructing a Peace Officer - UIUC Gaza encampment","arrest_date"=>"2025-01-09","sentenced_date"=>"2025-01-09","convicted"=>"Yes - guilty plea","sentence"=>"12 months conditional release; 100 hours community service"]]],

    ["name"=>"Davis Loren Nafshun","first_name"=>"Davis","middle_name"=>"Loren","last_name"=>"Nafshun","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-Tesla","Anti-Trump"],"in_custody"=>false,"released"=>true,"description"=>"Davis Loren Nafshun, 27, was arrested March 29, 2025 for shining a Class IIIa laser inside a Tesla dealership in Portland during an anti-Musk/Trump protest, allegedly hitting three employees in the eyes. Pleaded guilty; 2 days jail and 18 months probation.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.220 Unlawful Use of a Weapon [2 counts]; 163.190 Menacing [2 counts]; 163.195 Recklessly Endangering Another Person [2 counts]; 163.709 Unlawful Directing of Light from a Laser Pointer - March 2025 Portland Tesla anti-Musk protest","arrest_date"=>"2025-04-21","convicted"=>"Yes - guilty plea","sentence"=>"2 days jail; 18 months probation"]]],

    ["name"=>"Colin Ferguson","first_name"=>"Colin","last_name"=>"Ferguson","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"1990s","ideologies"=>["Black Liberation"],"in_custody"=>true,"released"=>false,"description"=>"Colin Ferguson, 36, a Black Jamaican-born US permanent resident, boarded a Long Island Rail Road train on December 7, 1993 and shot 25 passengers with a handgun, killing 6 and injuring 19. Notes in his pocket indicated hatred of whites, Asians, and Uncle Tom Negroes. Acted as his own attorney at trial; convicted on 6 murder counts and dozens of related counts. Sentenced to 315 years and 8 months (~3,788 months) in New York state prison.","cases"=>[["institution_name"=>"New York State Department of Corrections","institution_state"=>"New York","charges"=>"NY PEN 125.27 Intentional Murder [6 counts]; PEN 125.25(2) Depraved Indifference; PEN 125.25 Attempted Murder [19 counts]; PEN 120.10 Assault [24 counts]; PEN 265.01 Criminal Possession of a Weapon; PEN 290 Violation of Civil Rights [25 counts] - December 1993 Long Island Rail Road shooting","arrest_date"=>"1993-12-07","sentenced_date"=>"1995-03-22","convicted"=>"Yes - jury verdict","sentence"=>"315 years 8 months (~3,788 months) NY state prison"]]],

    ["name"=>"Freddie Morrow","first_name"=>"Freddie","last_name"=>"Morrow","aka"=>"Freddy Morrow","gender"=>"Male","race"=>"Black","state"=>"Tennessee","era"=>"1990s","ideologies"=>["Black Liberation"],"in_custody"=>true,"released"=>false,"description"=>"Freddie Morrow, 17, with co-defendants Damien Darden, Marcus Merriweather, and Tony Andrews, followed and shot Michael Westerman near Guthrie KY on January 14, 1995 after seeing a Confederate flag flying from his pickup. Westerman died. Morrow pulled the trigger. Convicted of first-degree murder, civil-rights intimidation, and attempted aggravated kidnapping; sentenced to life plus consecutive 4 + 5 = 9 years.","cases"=>[["institution_name"=>"Tennessee Department of Correction","institution_state"=>"Tennessee","charges"=>"TN First-Degree Murder; Civil Rights Intimidation; Attempted Aggravated Kidnapping - January 1995 Westerman shooting","arrest_date"=>"1995-01-15","convicted"=>"Yes - jury verdict","sentence"=>"Life + 108 months consecutive"]]],

    ["name"=>"Charles Damien Darden","first_name"=>"Charles","middle_name"=>"Damien","last_name"=>"Darden","aka"=>"Damien Darden","gender"=>"Male","race"=>"Black","state"=>"Tennessee","era"=>"1990s","ideologies"=>["Black Liberation"],"in_custody"=>true,"released"=>false,"description"=>"Charles Damien Darden, 17, drove the car in the January 14, 1995 Westerman shooting (Morrow shot from passenger seat). Convicted of first-degree murder, civil rights intimidation, and attempted aggravated kidnapping. Life sentence plus 3+4 years concurrent with each other but consecutive to life.","cases"=>[["institution_name"=>"Tennessee Department of Correction","institution_state"=>"Tennessee","charges"=>"TN First-Degree Murder; Civil Rights Intimidation; Attempted Aggravated Kidnapping - January 1995 Westerman shooting","arrest_date"=>"1995-01-15","convicted"=>"Yes - jury verdict","sentence"=>"Life + 84 months"]]],

    ["name"=>"Marcus Merriweather","first_name"=>"Marcus","last_name"=>"Merriweather","gender"=>"Male","race"=>"Black","state"=>"Tennessee","era"=>"1990s","ideologies"=>["Black Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Marcus Merriweather, 15, passenger in the January 14, 1995 Westerman shooting car. Found not guilty on all charges.","cases"=>[["institution_name"=>"Robertson County Circuit Court","institution_state"=>"Tennessee","charges"=>"TN First-Degree Murder; Civil Rights Intimidation; Attempted Aggravated Kidnapping - January 1995 Westerman shooting","arrest_date"=>"1995-01-15","convicted"=>"No - acquitted","sentence"=>"Acquitted"]]],

    ["name"=>"Tony Andrews","first_name"=>"Tony","last_name"=>"Andrews","gender"=>"Male","race"=>"Black","state"=>"Tennessee","era"=>"1990s","ideologies"=>["Black Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Tony Andrews, 17, passenger in the January 14, 1995 Westerman shooting car. Pleaded guilty and testified against co-defendants in return for 24 months probation.","cases"=>[["institution_name"=>"Robertson County Circuit Court","institution_state"=>"Tennessee","charges"=>"TN First-Degree Murder; Civil Rights Intimidation; Attempted Aggravated Kidnapping - January 1995 Westerman shooting","arrest_date"=>"1995-01-15","convicted"=>"Yes - guilty plea (cooperator)","sentence"=>"24 months probation"]]],

    ["name"=>"Theodore Kaczynski","first_name"=>"Theodore","last_name"=>"Kaczynski","aka"=>"The Unabomber","gender"=>"Male","race"=>"White","state"=>"Multiple states","era"=>"1990s","ideologies"=>["Anti-technology","Eco-extremism"],"affiliation"=>["Freedom Club (FC)"],"in_custody"=>false,"released"=>false,"death_date"=>"2023-06-10","description"=>"Theodore Kaczynski, the Unabomber, conducted a 1978-1995 mail-bombing campaign that killed 3 and injured 23. Published the 30,000-word Unabomber Manifesto. Arrested April 3, 1996 after his brother turned him in. Pleaded guilty; sentenced to four life sentences plus 30 years (no parole) and held in ADX Florence CMU. Died by suicide June 10, 2023 at FMC Butner.","cases"=>[["institution_name"=>"ADX Florence","institution_city"=>"Florence","institution_state"=>"Colorado","charges"=>"18 USC 844(d) Transporting an Explosive in Interstate Commerce With Intent to Kill or Injure [4 counts]; 18 USC 1716 Mailing an Explosive Device [3 counts]; 18 USC 924(c) Use of a Destructive Device During a Crime of Violence [3 counts] - 1978-1995 Unabomber mail-bombing campaign","arrest_date"=>"1996-04-03","convicted"=>"Yes - guilty plea","sentence"=>"Four life sentences plus 30 years; no parole"]]],

    ["name"=>"Ronald Taylor","first_name"=>"Ronald","last_name"=>"Taylor","gender"=>"Male","race"=>"Black","state"=>"Pennsylvania","era"=>"2000s","ideologies"=>["Black Liberation","Anti-white"],"in_custody"=>true,"released"=>false,"description"=>"Ronald Taylor, 39, set fire to his Wilkinsburg PA apartment on March 1, 2000 and went on a shooting rampage with a pistol, killing three white men and critically wounding two. Told a Black woman he wouldnt hurt her because he was out to get all white people. Convicted on 3 counts of first-degree murder, ethnic intimidation, arson, and 5 aggravated assault counts; death sentence imposed.","cases"=>[["institution_name"=>"Pennsylvania DOC death row","institution_state"=>"Pennsylvania","charges"=>"PA First-Degree Murder [3 counts]; Ethnic Intimidation; Arson; Aggravated Assault [5 counts]; Firearms Violation; Causing a Catastrophe - March 2000 Wilkinsburg shooting rampage","arrest_date"=>"2000-03-01","convicted"=>"Yes - jury verdict","sentence"=>"Death sentence"]]],

    ["name"=>"Thomas Keenan (LOVE Park 2007)","first_name"=>"Thomas","last_name"=>"Keenan","aka"=>"Tom Keenan","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2000s","ideologies"=>["Anti-fascism"],"affiliation"=>["Anti-Racist Action (ARA)"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Keenan, 24, ARA/Antifa member, arrested July 23, 2007 near LOVE Park in Philadelphia during a counter-protest against a planned (but never-held) KKK rally. The group followed undercover FBI antiterrorism task-force officers dressed as skinheads and damaged their FBI SUV. Most felonies dropped via plea bargain; convicted only of disorderly conduct.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Possession of Instrument of Crime; Conspiracy; Institutional Vandalism; Reckless Endangering; Resisting Arrest; Criminal Mischief; Disorderly Conduct - July 2007 LOVE Park FBI vehicle damage","arrest_date"=>"2007-07-23","convicted"=>"Yes - guilty plea on disorderly conduct","sentence"=>"No prison time"]]],

    ["name"=>"Jared Schultz","first_name"=>"Jared","last_name"=>"Schultz","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2000s","ideologies"=>["Anti-fascism"],"affiliation"=>["Anti-Racist Action (ARA)"],"in_custody"=>false,"released"=>true,"description"=>"Jared Schultz, 30, ARA/Antifa member; LOVE Park 4 co-defendant in the July 23, 2007 FBI SUV damage. Felonies dropped via plea bargain; convicted only of disorderly conduct.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Possession of Instrument of Crime; Conspiracy; Disorderly Conduct - July 2007 LOVE Park","arrest_date"=>"2007-07-23","convicted"=>"Yes - guilty plea on disorderly conduct","sentence"=>"No prison time"]]],

    ["name"=>"Jason Robbins","first_name"=>"Jason","last_name"=>"Robbins","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2000s","ideologies"=>["Anti-fascism"],"affiliation"=>["Anti-Racist Action (ARA)"],"in_custody"=>false,"released"=>true,"description"=>"Jason Robbins, 30, ARA/Antifa member; LOVE Park 4 co-defendant in the July 23, 2007 FBI SUV damage. Convicted only of disorderly conduct via plea bargain.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA disorderly conduct (felonies dropped) - July 2007 LOVE Park","arrest_date"=>"2007-07-23","convicted"=>"Yes - guilty plea","sentence"=>"No prison time"]]],

    ["name"=>"James McGovern Jr.","first_name"=>"James","last_name"=>"McGovern","aka"=>"Jr.","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2000s","ideologies"=>["Anti-fascism"],"affiliation"=>["Anti-Racist Action (ARA)"],"in_custody"=>false,"released"=>true,"description"=>"James McGovern Jr., 59, ARA/Antifa member; LOVE Park 4 co-defendant in the July 23, 2007 FBI SUV damage. No-contest plea to lesser charges; 12 months probation, anger management therapy, $600 restitution.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Criminal Mischief; Conspiracy; Harassment; Disorderly Conduct - July 2007 LOVE Park","arrest_date"=>"2007-07-23","convicted"=>"Yes - no contest","sentence"=>"12 months probation"]]],

    ["name"=>"Floyd Lee Corkins II","first_name"=>"Floyd","middle_name"=>"Lee II","last_name"=>"Corkins","gender"=>"Male","race"=>"White","state"=>"District of Columbia","era"=>"2010s","ideologies"=>["LGBTQ rights","Anti-conservative"],"in_custody"=>true,"released"=>false,"description"=>"Floyd Lee Corkins II, 29, walked into the Family Research Council offices in DC on August 15, 2012 with a gun and Chick-fil-A sandwiches he planned to smear in victims faces as a political statement opposing the FRCs anti-LGBTQ stances. He shot and wounded a building manager before being subdued. Pleaded guilty to interstate transport of a firearm, assault with intent to kill, and committing an act of terrorism while armed (DC Anti-Terrorism Act of 2002). Sentenced to 300 months federal prison + 5 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"DC Committing an Act of Terrorism While Armed; Assault With Intent to Kill While Armed; 18 USC 922 Interstate Transportation of a Firearm and Ammunition - August 2012 FRC shooting","arrest_date"=>"2012-08-15","convicted"=>"Yes - guilty plea","sentence"=>"300 months federal prison + 5 years supervised release"]]],

    ["name"=>"Brandon Orlando Baldwin","first_name"=>"Brandon","middle_name"=>"Orlando","last_name"=>"Baldwin","aka"=>"Brandon Muhammad","gender"=>"Male","race"=>"Black","state"=>"Missouri","era"=>"2010s","ideologies"=>["Black Liberation"],"affiliation"=>["New Black Panther Party"],"in_custody"=>false,"released"=>true,"description"=>"Brandon Orlando Baldwin, 22, NBPP leader; with co-defendant Olajuwon Davis, conspired during the November 2014 Ferguson protests to ignite explosive devices and provide firearms to felons. Pleaded guilty; 84 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Missouri","charges"=>"18 USC 844 Conspiracy to Damage Property With Explosives; 18 USC 922(a)(6) Conspiracy to Make False Statements in Firearms Purchase; 18 USC 922(d) Transfer of Firearms to a Felon - November 2014 Ferguson plot","arrest_date"=>"2014-11-19","convicted"=>"Yes - guilty plea","sentence"=>"84 months federal prison"]]],

    ["name"=>"Olajuwon Davis","first_name"=>"Olajuwon","last_name"=>"Davis","aka"=>"Brother Ali","gender"=>"Male","race"=>"Black","state"=>"Missouri","era"=>"2010s","ideologies"=>["Black Liberation"],"affiliation"=>["New Black Panther Party"],"in_custody"=>false,"released"=>true,"description"=>"Olajuwon Davis, 22, NBPP leader; co-defendant of Brandon Baldwin in the November 2014 Ferguson explosive-device / firearms conspiracy. Pleaded guilty; 84 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Missouri","charges"=>"18 USC 844 Conspiracy to Damage Property With Explosives; 18 USC 922 Firearms Conspiracy - November 2014 Ferguson plot","arrest_date"=>"2014-11-19","convicted"=>"Yes - guilty plea","sentence"=>"84 months federal prison"]]],

    ["name"=>"Jasmine Richards","first_name"=>"Jasmine","last_name"=>"Richards","aka"=>"BLMDena, Abdullah","gender"=>"Female","race"=>"Black","state"=>"California","era"=>"2010s","ideologies"=>["Black Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Jasmine Richards, 28, was charged June 3, 2016 with felony lynching (CA PC 405a, attempting to take a person from lawful police custody by means of a riot) for trying to physically pull a woman from arrest near a Pasadena park. First African American ever charged with and convicted of felony lynching. Sentenced to 90 days (~3 months).","cases"=>[["institution_name"=>"Los Angeles County Jail","institution_state"=>"California","charges"=>"California PC 405a Felony Lynching; Inciting a Riot; Child Endangerment; Delaying/Obstructing Police - 2015 Pasadena","arrest_date"=>"2016-06-03","convicted"=>"Yes - jury verdict","sentence"=>"90 days (~3 months)"]]],

    ["name"=>"Emanuel Kidega Samson","first_name"=>"Emanuel","middle_name"=>"Kidega","last_name"=>"Samson","gender"=>"Male","race"=>"Black","state"=>"Tennessee","era"=>"2010s","ideologies"=>["Black Liberation","Anti-white"],"in_custody"=>true,"released"=>false,"description"=>"Emanuel Kidega Samson, 27, fatally shot one woman and wounded seven others at the Burnette Chapel Church of Christ in Antioch TN on September 24, 2017. Cited the 2015 Charleston AME shooting as inspiration; aimed to kill at least 10 white churchgoers. Convicted on first-degree murder + civil rights intimidation; sentenced to life without parole.","cases"=>[["institution_name"=>"Tennessee Department of Correction","institution_state"=>"Tennessee","charges"=>"TN Civil Rights Intimidation; Murder First-Degree; Attempted Murder First-Degree; Employing a Firearm During a Dangerous Felony; Aggravated Assault; Reckless Endangerment - September 2017 Antioch church shooting","arrest_date"=>"2017-09-24","convicted"=>"Yes - jury verdict","sentence"=>"Life without parole"]]],

    ["name"=>"Lacy MacAuley","first_name"=>"Lacy","last_name"=>"MacAuley","gender"=>"Female","race"=>"White","state"=>"Michigan","era"=>"2010s","ideologies"=>["Anti-fascism"],"in_custody"=>false,"released"=>true,"description"=>"Lacy MacAuley, 28, was arrested at a March 5, 2018 disruption of a white-nationalist speaker event at Michigan State University. Charged with resisting and obstruction of a police officer. Outcome unknown; Ingham County records not publicly accessible.","cases"=>[["institution_name"=>"Ingham County Court","institution_state"=>"Michigan","charges"=>"Michigan resisting and obstruction - March 2018 Michigan State white-nationalist event disruption","arrest_date"=>"2018-07-03","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Joseph Alcoff","first_name"=>"Joseph","last_name"=>"Alcoff","aka"=>"Chepe, Jose","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2010s","ideologies"=>["Anti-fascism"],"affiliation"=>["Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Joseph Alcoff, 40, alleged Antifa leader in DC, with co-defendants Tom Keenan and Thomas Massey, beat two USMC reservists (Alejandro Godinez and Luis Torres) in Philadelphia on November 17, 2018 after mistaking them for We the People rally participants. Charged with aggravated assault, ethnic intimidation, conspiracy, theft, terroristic threats. Took plea deal.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Aggravated Assault; Ethnic Intimidation; Conspiracy; Theft; Terroristic Threats - Nov 2018 Philadelphia attack on USMC reservists","arrest_date"=>"2018-11-17","convicted"=>"Yes - guilty plea","sentence"=>"No prison time"]]],

    ["name"=>"Thomas Massey","first_name"=>"Thomas","last_name"=>"Massey","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2010s","ideologies"=>["Anti-fascism"],"affiliation"=>["Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Massey, 37, Antifa member; co-defendant of Alcoff and Keenan in the November 2018 Philadelphia attack on two USMC reservists. Took plea deal.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Aggravated Assault; Conspiracy; Ethnic Intimidation - Nov 2018 Philadelphia attack","arrest_date"=>"2018-11-17","convicted"=>"Yes - guilty plea","sentence"=>"No prison time"]]],

    ["name"=>"Thomas Keenan (Alcoff 2018)","first_name"=>"Thomas","last_name"=>"Keenan","aka"=>"Tom Keenan","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"2010s","ideologies"=>["Anti-fascism"],"affiliation"=>["Antifa"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Keenan, 33, Antifa member; co-defendant of Alcoff and Massey in the November 2018 Philadelphia attack on two USMC reservists (separate from the 2007 LOVE Park case). Took plea deal.","cases"=>[["institution_name"=>"Philadelphia Court of Common Pleas","institution_state"=>"Pennsylvania","charges"=>"PA Aggravated Assault; Conspiracy; Ethnic Intimidation - Nov 2018 Philadelphia attack","arrest_date"=>"2018-11-17","convicted"=>"Yes - guilty plea","sentence"=>"No prison time"]]],

    ["name"=>"Thomas Heard","first_name"=>"Thomas","last_name"=>"Heard","aka"=>"Tasha Heard","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Black Liberation","Anti-white"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Heard (also known as Tasha Heard, identified as transgender), 37, was indicted in March 2019 (one count) and May 2019 (multi-borough series) for hate-crime pepper-spray attacks targeting white pedestrians across New York City the week of March 11, 2019, plus kicking some victims. Sentencing not publicly available in NY court records.","cases"=>[["institution_name"=>"New York State Department of Corrections","institution_state"=>"New York","charges"=>"NY PEN 120.10 Hate Crime Assault; PEN 120.00(1H) Assault Causing Injury as Hate Crime; PEN 265.02(01) Criminal Possession of Weapon; PEN 120.14(01) Second-Degree Menacing With a Weapon - March 2019 NYC pepper-spray attacks","arrest_date"=>"2019-03-20","convicted"=>"Yes (per March 2019 indictment); May 2019 disposition data not available","sentence"=>"Data not available"]]],

    ["name"=>"Chase A. Davis","first_name"=>"Chase","middle_name"=>"A.","last_name"=>"Davis","gender"=>"Male","race"=>"White","state"=>"Mississippi","era"=>"2010s","ideologies"=>["LGBTQ rights","Anti-conservative"],"in_custody"=>false,"released"=>true,"description"=>"Chase A. Davis, 21, was arrested in Florida on Mississippi charges alleging he sent Facebook death threats to the American Family Association, an anti-LGBTQ organization. PACER records sealed. 6 months federal prison + 2 years supervised release + $1,440 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Mississippi","charges"=>"18 USC 875(c) Threatening Interstate Communications - 2019 AFA Facebook threats","arrest_date"=>"2019-08-20","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison + 2 years supervised release + $1,440 restitution"]]],

    ["name"=>"Todd Lyons","first_name"=>"Todd","last_name"=>"Lyons","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2010s","ideologies"=>["Black Liberation","Anti-white"],"in_custody"=>false,"released"=>true,"description"=>"Todd Lyons, 33, of Manhattan, was charged September 9, 2019 in a 12-count indictment for seven random hate-crime attacks on white pedestrians in lower Manhattan. Used fists, a brick, and wood from a broken chair. Disposition not publicly available.","cases"=>[["institution_name"=>"New York State Department of Corrections","institution_state"=>"New York","charges"=>"NY PEN 120.00(01) Assault With Intent [4 counts]; 120.05(12) Assault on Victim 65+ [2 counts]; 110-120.05 Attempted Assault With Weapon [2 counts]; 265.01(02) Criminal Possession of Weapon - Sept 2019 NYC hate-crime spree","arrest_date"=>"2019-09-09","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Zachary Lange","first_name"=>"Zachary","last_name"=>"Lange","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2010s","ideologies"=>["Anti-fascism","Accelerationism"],"in_custody"=>false,"released"=>true,"description"=>"Zachary Lange, 21, was indicted September 29, 2019 on felony riot for the August 17, 2019 antifascist counter-protest against the Proud Boys in Portland. Disposition data not available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Riot; 164.354 Criminal Mischief II; 164.055 Theft I - August 2019 Portland Proud Boys counter-protest","arrest_date"=>"2019-09-29","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Richard Joseph Klimek","first_name"=>"Richard","middle_name"=>"Joseph","last_name"=>"Klimek","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2010s","ideologies"=>["Anti-fascism","Accelerationism"],"in_custody"=>false,"released"=>true,"description"=>"Richard Joseph Klimek, 51, indicted Sept 29, 2019 on felony riot, attempted assault, criminal mischief, unlawful entry into a motor vehicle, and theft for the Aug 17, 2019 Portland antifa-Proud Boys counter-protest. Data not available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Riot; 161.405; 164.354; 164.272; 164.055 - August 2019 Portland counter-protest","arrest_date"=>"2019-09-29","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Evan Kirk Duke","first_name"=>"Evan","middle_name"=>"Kirk","last_name"=>"Duke","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2010s","ideologies"=>["Anti-fascism","Accelerationism"],"in_custody"=>false,"released"=>true,"description"=>"Evan Kirk Duke, 48, indicted Sept 29, 2019 on felony riot, attempted assault, criminal mischief for the Aug 17, 2019 Portland antifa-Proud Boys counter-protest. Data not available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Riot; 161.405; 164.354 - August 2019 Portland counter-protest","arrest_date"=>"2019-09-29","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Antonio Scott Zamora","first_name"=>"Antonio","middle_name"=>"Scott","last_name"=>"Zamora","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Oregon","era"=>"2010s","ideologies"=>["Anti-fascism","Accelerationism"],"in_custody"=>false,"released"=>true,"description"=>"Antonio Scott Zamora, 33, indicted Sept 29, 2019 on felony riot for the Aug 17, 2019 Portland antifa-Proud Boys counter-protest. Data not available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Riot; 164.354; 161.405; 166.025 - August 2019 Portland counter-protest","arrest_date"=>"2019-09-29","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Alexander Gorman Dial","first_name"=>"Alexander","middle_name"=>"Gorman","last_name"=>"Dial","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2010s","ideologies"=>["Anti-fascism"],"in_custody"=>false,"released"=>true,"description"=>"Alexander Gorman Dial, 37, indicted Sept 29, 2019 on felony riot, second-degree assault, third-degree assault, and criminal mischief for the Aug 17, 2019 Portland antifa-Proud Boys counter-protest. 6 victims injured. Took plea July 2018 (per source); details data not available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Riot; 163.175 Assault II; 163.165 Assault III; 164.354 Criminal Mischief II - August 2019 Portland counter-protest","arrest_date"=>"2019-09-29","convicted"=>"Yes - guilty plea (July 2018, per source)","sentence"=>"Data not available"]]],

    ["name"=>"Nimo Jire Kalinle","first_name"=>"Nimo","middle_name"=>"Jire","last_name"=>"Kalinle","gender"=>"Female","race"=>"Black","state"=>"Oregon","era"=>"2020s","ideologies"=>["Black Liberation","Anti-white"],"in_custody"=>false,"released"=>true,"description"=>"Nimo Jire Kalinle, 42, charged February 24, 2020 in North Portland with fourth-degree felony assault, first-degree bias crime, second-degree bias crime, and 2 counts of interfering with public transportation after she beat a white woman on a bus, telling her its because youre white and I hate white people. Case closed but sentencing data not publicly available.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS Fourth-Degree Felony Assault; First-Degree Bias Crime; Second-Degree Bias Crime; Interfering With Public Transportation [2 counts] - Feb 2020 Portland bus attack","arrest_date"=>"2020-02-24","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Nancy Sweeney","first_name"=>"Nancy","last_name"=>"Sweeney","gender"=>"Female","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-immigrant"],"in_custody"=>false,"released"=>true,"description"=>"Nancy Sweeney, 45, was charged February 28, 2020 in Niles IL with felony hate crime and aggravated battery against a person over 60. Approached an 87-year-old neighbor exercising in her parking garage, called her a Nazi based on her immigration status, and struck her with a purse. Case data not publicly available.","cases"=>[["institution_name"=>"Cook County Circuit Court","institution_state"=>"Illinois","charges"=>"IL Aggravated Battery of Person Over 60; Hate Crime - Feb 2020 Niles IL","arrest_date"=>"2020-02-28","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Timothy Hummel","first_name"=>"Timothy","last_name"=>"Hummel","gender"=>"Male","race"=>"White","state"=>"Colorado","era"=>"2020s","ideologies"=>["Anti-ICE"],"in_custody"=>false,"released"=>true,"description"=>"Timothy Hummel, 26, of Denver, sent threatening messages in 2019 to a U.S. Customs and Immigration Enforcement office threatening ICE agents and their families. Pleaded guilty August 10, 2020 to threatening to murder federal law enforcement officers; 3 years supervised release, no prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Colorado","charges"=>"18 USC 115(a)(1)(A)/(B) Influencing or Retaliating Against a Federal Official by Threat; 18 USC 875(c) Interstate Communication of a Threat - 2019 ICE threats","arrest_date"=>"2020-03-11","convicted"=>"Yes - guilty plea","sentence"=>"3 years supervised release"]]],

    ["name"=>"Daniel D. Navarro","first_name"=>"Daniel","middle_name"=>"D.","last_name"=>"Navarro","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Wisconsin","era"=>"2020s","ideologies"=>["Anti-white"],"in_custody"=>true,"released"=>false,"description"=>"Daniel D. Navarro, 27, swerved into the path of a motorcyclist on July 3, 2020, killing 55-year-old Phillip Thiessen, a former Virginia police officer and retired Wisconsin DOJ DCI agent. Told investigators he was targeting a white person and picked a motorcycle because he wanted the person to die, citing white people drive motorcycles. Found not guilty by reason of insanity; committed to state institutional care for life.","cases"=>[["institution_name"=>"Wisconsin Department of Health Services / Mendota Mental Health Institute","institution_state"=>"Wisconsin","charges"=>"Wis Stat 940.01(1)(a) First-Degree Intentional Homicide with hate-crime and dangerous-weapon enhancers; 941.30(1) First-Degree Recklessly Endangering Safety - July 2020 Taycheedah motorcycle ramming","arrest_date"=>"2020-07-09","convicted"=>"NGRI - committed to state care","sentence"=>"State institutional care for life"]]],

    ["name"=>"Haley Rainwater","first_name"=>"Haley","last_name"=>"Rainwater","gender"=>"Female","race"=>"White","state"=>"Tennessee","era"=>"2020s","ideologies"=>["Anti-Confederate"],"in_custody"=>false,"released"=>true,"description"=>"Haley Rainwater was one of six people arrested October 9, 2020 in Collierville TN after spray-painting and throwing adhesive and feathers on a Confederate statue. Charges dropped prior to trial.","cases"=>[["institution_name"=>"Shelby County Circuit Court","institution_state"=>"Tennessee","charges"=>"TN Vandalism Over $1,000 - Oct 2020 Collierville Confederate statue action","arrest_date"=>"2020-10-09","convicted"=>"No - charges dropped","sentence"=>"Dismissed"]]],

    ["name"=>"Emily Keppler","first_name"=>"Emily","last_name"=>"Keppler","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Black Liberation","Anti-police"],"in_custody"=>false,"released"=>true,"description"=>"Emily Keppler, 27, was charged June 25, 2021 with felony rioting and first-degree criminal mischief for an April 20, 2021 Portland action during the Derek Chauvin trial. With Emma Lightstone, entered a Bank of America with hammers to damage an ATM and break windows.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Rioting; 164.365 Criminal Mischief I - April 2021 Portland Bank of America attack","arrest_date"=>"2021-06-05","convicted"=>"No - charged but not tried","sentence"=>"Pending/dropped"]]],

    ["name"=>"Emma Lightstone","first_name"=>"Emma","last_name"=>"Lightstone","gender"=>"Female","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Black Liberation","Anti-police"],"in_custody"=>false,"released"=>true,"description"=>"Emma Lightstone, 27, co-defendant of Emily Keppler in the April 20, 2021 Portland Bank of America hammer attack during the Derek Chauvin trial. No-contest plea; convicted.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"ORS 166.015 Felony Rioting; 164.365 Criminal Mischief I; Criminal Mischief II - April 2021 Portland Bank of America attack","arrest_date"=>"2021-06-05","convicted"=>"Yes - no contest","sentence"=>"Local sentence"]]],

    ["name"=>"Cortez Aaron Rice","first_name"=>"Cortez","middle_name"=>"Aaron","last_name"=>"Rice","gender"=>"Male","race"=>"Black","state"=>"Minnesota","era"=>"2020s","ideologies"=>["Black Liberation"],"in_custody"=>false,"released"=>true,"description"=>"Cortez Aaron Rice, 32, was charged November 24, 2021 in Minneapolis with felony harassment / retaliation against a judicial officer for livestreaming demands at a home he believed belonged to the judge presiding over Kim Potters trial (Daunte Wright case). Charges dismissed without prejudice.","cases"=>[["institution_name"=>"Hennepin County District Court","institution_state"=>"Minnesota","charges"=>"MN Stat 609.749.3(a)(4) Harassment - Aggravated; Retaliate Against Judicial Officer - Nov 2021 Potter trial protest","arrest_date"=>"2021-11-24","convicted"=>"No - dismissed without prejudice","sentence"=>"Dismissed"]]],

    ["name"=>"Damian Smith-Birge","first_name"=>"Damian","last_name"=>"Smith-Birge","gender"=>"Male","state"=>"Missouri","era"=>"2020s","ideologies"=>["Anti-police"],"in_custody"=>false,"released"=>true,"description"=>"Damian Smith-Birge, 26, of Neosho MO, called the Pennsylvania State Police on November 18, 2021 and made threats against law enforcement, referencing a December 2020 Hamilton Township PA officer-involved shooting. Pleaded guilty; sentenced to time served (~7 months).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Missouri","charges"=>"18 USC 875(c) Interstate Threats - Nov 2021 PSP threats","arrest_date"=>"2021-11-24","convicted"=>"Yes - guilty plea","sentence"=>"~7 months time served"]]],

    ["name"=>"Sayed A. Quraishi","first_name"=>"Sayed","middle_name"=>"A.","last_name"=>"Quraishi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Illinois","era"=>"2020s","ideologies"=>["Anti-Israel"],"in_custody"=>false,"released"=>true,"description"=>"Sayed A. Quraishi, 23, was charged with hate crime for throwing a rock at Jewish protesters at the University of Illinois on April 18, 2022. Case dismissed.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/12-7.1(b-5)(6) Class 3 Hate Crime / 1000 Feet of Property - April 2022 UIUC","arrest_date"=>"2022-04-18","convicted"=>"No - acquitted","sentence"=>"Dismissed"]]],

    ["name"=>"Erich Louis Yach","first_name"=>"Erich","middle_name"=>"Louis","last_name"=>"Yach","aka"=>"Nikki","gender"=>"Other","race"=>"White","state"=>"California","era"=>"2020s","ideologies"=>["Anti-fascism"],"affiliation"=>["Antifa"],"in_custody"=>true,"released"=>false,"description"=>"Erich Louis Yach, 37, gender non-conforming, was indicted June 7, 2022 for the January 9, 2021 SD-Antifa-10 attack on Trump supporters at a Pacific Beach demonstration; the antifa counter-protest involved tear gas and assaults injuring 4. Pleaded guilty; sentenced to 56 months.","cases"=>[["institution_name"=>"San Diego County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1) Conspiracy; 245(a)(4) Assault by GBI Force; 22810(g)(1) Use of Tear Gas [3 counts]; 245(a)(1) Assault With a Deadly Weapon; 244.5(b) Assault With Stun Gun - January 2021 Pacific Beach attack","arrest_date"=>"2022-06-07","convicted"=>"Yes - guilty plea","sentence"=>"56 months California state prison"]]],

    ["name"=>"Bryn Taylor","first_name"=>"Bryn","last_name"=>"Taylor","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"in_custody"=>false,"released"=>true,"description"=>"Bryn Taylor, 26, University of Florida PhD candidate, was arraigned May 16, 2023 for allegedly battering an officer and resisting arrest with violence at a UF reproductive rights demonstration in Gainesville. Took pre-trial diversion; charges dropped 2025 after community service.","cases"=>[["institution_name"=>"Alachua County Circuit Court","institution_state"=>"Florida","charges"=>"Florida Stat 784.07 Aggravated Battery on LEO; 843.01 Resisting Officer With Violence; 843.02 Resisting Without Violence - May 2023 UF reproductive rights demonstration","arrest_date"=>"2023-05-16","convicted"=>"No - diversion completed, dismissed","sentence"=>"Diversion / 2 yr probation"]]],

    ["name"=>"Ian Dinkla","first_name"=>"Ian","last_name"=>"Dinkla","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"in_custody"=>false,"released"=>true,"description"=>"Ian Dinkla, 21, was arraigned May 16, 2023 for stealing an anti-abortion sign and resisting arrest at a UF reproductive rights demonstration in Gainesville. No-contest plea; 2 years probation.","cases"=>[["institution_name"=>"Alachua County Circuit Court","institution_state"=>"Florida","charges"=>"Florida Stat 843.01 Resisting Officer With Violence; 812.13 Robbery - May 2023 UF reproductive rights demonstration","arrest_date"=>"2023-05-16","convicted"=>"Yes - no contest","sentence"=>"2 years probation"]]],

    ["name"=>"Whitney M. Durant","first_name"=>"Whitney","middle_name"=>"M.","last_name"=>"Durant","aka"=>"Soren Monroe","gender"=>"Female","race"=>"Black","state"=>"Ohio","era"=>"2020s","ideologies"=>["Reproductive Rights"],"in_custody"=>false,"released"=>true,"description"=>"Whitney M. Durant, 20, vandalized HerChoice pregnancy care center in Bowling Green OH on April 15, 2023 with spray paint because the clinic provides reproductive health services. 2 years probation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Ohio","charges"=>"18 USC 248(a)(3) Freedom of Access to Clinic Entrances Act (FACE Act) - April 2023 HerChoice vandalism","arrest_date"=>"2023-07-05","convicted"=>"Yes - guilty after blind plea","sentence"=>"2 years probation"]]],

    ["name"=>"Wendy Lujan","first_name"=>"Wendy","last_name"=>"Lujan","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"Wendy Lujan, 40, one of the Justice 8 (Edin Alex Enamorado et al.) defendants for a September 24, 2023 Victorville CA protest where the group surrounded a vehicle, assaulted, and pepper-sprayed people perceived as anti-street-vendor. Pleaded guilty; 12 months California state prison.","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1) Conspiracy; 422(a) Criminal Threats; 236 False Imprisonment; 207(a) Kidnapping; 245(a)(4) Assault by GBI Force; 22810(g)(1) Tear Gas - Sept 2023 Victorville street-vendor protest","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"12 months California state prison"]]],

    ["name"=>"David Chavez","first_name"=>"David","last_name"=>"Chavez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"David Chavez, 28, Justice 8 defendant; September 2023 Victorville street-vendor protest. 24 months California state prison (12 months credit).","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1); 422(a); 236; 207(a); 245(a)(4); 22810(g)(1) - Sept 2023 Victorville","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"24 months California state prison; 12 mo credit"]]],

    ["name"=>"Stephanie Amesquita","first_name"=>"Stephanie","last_name"=>"Amesquita","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"Stephanie Amesquita, 33, Justice 8 defendant; September 2023 Victorville street-vendor protest. 12 months California state prison.","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1); 422(a); 236; 207(a); 245(a)(4); 22810(g)(1) - Sept 2023 Victorville","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"12 months California state prison"]]],

    ["name"=>"Edwin Pena","first_name"=>"Edwin","last_name"=>"Pena","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"Edwin Pena, 26, Justice 8 defendant; September 2023 Victorville street-vendor protest. 24 months California state prison (12 mo credit).","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1); 422(a); 236; 207(a); 245(a)(4); 22810(g)(1) - Sept 2023 Victorville","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"24 months California state prison; 12 mo credit"]]],

    ["name"=>"Fernando Lopez","first_name"=>"Fernando","last_name"=>"Lopez","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"Fernando Lopez, 44, Justice 8 defendant; September 2023 Victorville street-vendor protest. 24 months California state prison (12 mo credit).","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1); 422(a); 236; 207(a); 245(a)(4); 22810(g)(1) - Sept 2023 Victorville","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"24 months California state prison; 12 mo credit"]]],

    ["name"=>"Vanessa Carrasco","first_name"=>"Vanessa","last_name"=>"Carrasco","gender"=>"Female","race"=>"Latino/Hispanic","state"=>"California","era"=>"2020s","ideologies"=>["Street Vendor Rights"],"affiliation"=>["#Justice8"],"in_custody"=>false,"released"=>true,"description"=>"Vanessa Carrasco, 40, Justice 8 defendant; September 2023 Victorville street-vendor protest. 12 months California state prison.","cases"=>[["institution_name"=>"San Bernardino County Superior Court","institution_state"=>"California","charges"=>"California PC 182(a)(1); 422(a); 236; 207(a); 245(a)(4); 22810(g)(1) - Sept 2023 Victorville","arrest_date"=>"2023-09-24","convicted"=>"Yes - guilty plea","sentence"=>"12 months California state prison"]]],

    ["name"=>"Patrick Dai","first_name"=>"Patrick","last_name"=>"Dai","gender"=>"Male","race"=>"Asian / South Asian","state"=>"New York","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-Israel"],"in_custody"=>true,"released"=>false,"description"=>"Patrick Dai, 21, junior at Cornell University, was arrested October 31, 2023 for posting threatening messages on a Cornell discussion site, including threats to shoot up 104 West (Cornell Jewish dining hall), stab/slit the throats of Jewish males, rape and throw off a cliff Jewish females, and behead Jewish babies. Pleaded guilty; 21 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 875(c) Threatening Interstate Communications - Oct 2023 Cornell antisemitic threats","arrest_date"=>"2023-10-31","convicted"=>"Yes - guilty plea","sentence"=>"21 months federal prison"]]],

    ["name"=>"Deep Alpesh Kumar Patel","first_name"=>"Deep","middle_name"=>"Alpesh Kumar","last_name"=>"Patel","gender"=>"Male","race"=>"Asian / South Asian","state"=>"Florida","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-Israel"],"in_custody"=>false,"released"=>true,"description"=>"Deep Alpesh Kumar Patel, 21, of Sarasota FL, called the World Jewish Congress in NYC and left a threatening voicemail (If I had a chance, I would kill every single one of you Israelis). Pleaded guilty; 6 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 875(c) Transmitting Interstate Threat to Injure - Nov 2023 WJC voicemail","arrest_date"=>"2023-11-29","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison"]]],

    ["name"=>"Casey Robert Goonan","first_name"=>"Casey","middle_name"=>"Robert","last_name"=>"Goonan","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2020s","ideologies"=>["Pro-Palestine","Anti-imperialism"],"in_custody"=>true,"released"=>false,"description"=>"Casey Robert Goonan, 34, of Oakland and Pleasant Hill CA, ignited six Molotov cocktails inside a UC Berkeley UCPD patrol vehicle on June 1, 2024, attempted to firebomb the Ronald V. Dellums Federal Building/U.S. Courthouse in Oakland on June 11, 2024, and set additional fires on the UCB campus June 1/13/16 2024. Blogged photos under Student Intifada banner; admitted inspiration from Hamas Oct 7, 2023 attack. DOJ called him a domestic terrorist. Pleaded guilty; 235 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 844(f)(1) Maliciously Damaging Property of Federally Funded Institution by Fire/Explosive; 18 USC 844(i) Maliciously Damaging Property in Interstate Commerce by Fire/Explosive; 26 USC 5861(d) Possession of an Unregistered Firearm - June 2024 UC Berkeley/Oakland Federal Building Molotov spree","arrest_date"=>"2024-07-24","convicted"=>"Yes - guilty plea","sentence"=>"235 months federal prison"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "Prosecution Project rows 701-800 import complete."
