#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_3.sh
#
# Third batch (rows 201-300). Rows 201-221 cover the remaining
# Salt Lake City Inland Port riot defendants, the rest of the
# 2019-2024 climate-defender prosecutions (Reiche/Brooks rail
# shunt, Reznicek/Montoya's Reznicek entry, Vialard, Joanna Smith,
# Cameron Monte Smith, Jackson Green, Zepeda, Brian Okum), and
# rows 222-300 cover the late-1990s to mid-2000s anti-government
# / anti-IRS / militia-adjacent prosecutions plus the massive
# FARC indictments (AGUABLANCA, CARACAS, SILVA, MARIN) where most
# defendants were Colombian nationals indicted in U.S. court but
# never captured.
#
# Skipped because already in DB: Tsutomu Shirosaki, James Dalton
# Bell (Jim Bell), Sara Jane Olson, Simon Trinidad, Jessica
# Reznicek, Jorge Enrique Rodriguez Mendieta, Ruby Montoya.
# Skipped because no U.S. nexus per scope rule: none auto-skipped,
# but FARC fugitives are added with fugitive status flagged in
# their case row.
set -e

php artisan tinker --execute='
$rows = [
    // ---- Rows 201-205: SLC Inland Port riot continuation ----
    ["name"=>"Ethan Merrill Petersen","first_name"=>"Ethan","middle_name"=>"Merrill","last_name"=>"Petersen","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Ethan Merrill Petersen, age 25, was one of ten people charged in connection with the September 26, 2019 Salt Lake City Inland Port protest at the Utah commerce building lobby.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting (3rd-degree felony); 76-6-206(2)(a) criminal trespass - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Amy Kathleen Kovac","first_name"=>"Amy","middle_name"=>"Kathleen","last_name"=>"Kovac","gender"=>"Female","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Amy Kathleen Kovac, age 28, was one of ten people charged in connection with the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting; interference with arresting officer; 76-6-206(2)(a) criminal trespass - September 26, 2019 Utah Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Richard Anderson Jr.","first_name"=>"Richard","last_name"=>"Anderson","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Richard Anderson Jr., age 31, was one of five protesters who used \"sleeping dragon\" lockboxes in the Utah commerce-building lobby during the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting; 76-6-206(2)(a) criminal trespass - Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Nicholas Evert Jones","first_name"=>"Nicholas","middle_name"=>"Evert","last_name"=>"Jones","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Nicholas Evert Jones, age 30, was charged with assault on a peace officer plus rioting and criminal trespass for involvement in the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-5-102.4 assault on a peace officer; 76-9-101 rioting; 76-6-206(2)(a) criminal trespass - Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],
    ["name"=>"Jackson Richman","first_name"=>"Jackson","last_name"=>"Richman","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Jackson Richman, age 18, was charged with rioting, propelling a bodily substance, and trespassing for spitting on an officer attempting to arrest him during the September 26, 2019 Salt Lake City Inland Port protest.","cases"=>[["institution_name"=>"Salt Lake County District Court","institution_state"=>"Utah","charges"=>"Utah Code 76-9-101 rioting; 76-5-S102.9 propelling bodily substance; 76-6-206(2)(a) criminal trespass - Inland Port protest","arrest_date"=>"2019-09-26","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    // ---- Rows 206-221: Climate / pipeline / NGA / substation prosecutions ----
    ["name"=>"Donald Jose David Zepeda","first_name"=>"Donald","last_name"=>"Zepeda","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Washington","era"=>"2010s","ideologies"=>["Environmental Activism"],"in_custody"=>false,"released"=>true,"description"=>"Donald Jose David Zepeda, age 30, was sentenced October 16, 2019 to 60 days in jail (necessity defense unsuccessful) for attempted sabotage of the Kinder Morgan Tar Sands Pipeline at Mt. Vernon, Washington.","cases"=>[["institution_name"=>"Skagit County Jail","institution_city"=>"Mount Vernon","institution_state"=>"Washington","charges"=>"RCW 9.05.060 attempted criminal sabotage; RCW 9A.52.030 burglary 2nd degree; RCW 9A.48.090 malicious mischief 3rd degree - 2019 Mt. Vernon Kinder Morgan Tar Sands Pipeline action","arrest_date"=>"2019-10-16","incarceration_date"=>"2019-10-16","convicted"=>"Yes - jury verdict","sentence"=>"60 days county jail; necessity defense denied"]]],
    ["name"=>"Meredith Lowell","first_name"=>"Meredith","last_name"=>"Lowell","gender"=>"Female","race"=>"White","state"=>"Ohio","era"=>"2010s","ideologies"=>["Animal Rights Activism"],"in_custody"=>false,"released"=>true,"description"=>"Meredith Lowell, age 35, was charged in 2019 with attempted murder, two counts felonious assault, and aggravated burglary for stabbing a woman in a Cleveland Heights church because she was wearing fur boots (the boots were synthetic). Found not guilty by reason of insanity; the defense established autism-spectrum-disorder grounds. She had been previously charged in 2012 with attempting to hire a hitman to kill someone for wearing fur.","cases"=>[["institution_name"=>"Cuyahoga County Jail","institution_city"=>"Cleveland","institution_state"=>"Ohio","charges"=>"Ohio Rev. Code 2923.02/2903.02(A) attempted murder; 2903.11(A)(1) felonious assault [2 counts]; 2911.11(A) aggravated burglary [2 counts]; 2911.12(A)(1) burglary - 2019 Cleveland Heights church stabbing","arrest_date"=>"2019-11-25","convicted"=>"No - not guilty by reason of insanity","sentence"=>"NGRI; civil commitment for treatment"]]],
    ["name"=>"Galen Sol Shireman-Grabowski","first_name"=>"Galen","middle_name"=>"Sol","last_name"=>"Shireman-Grabowski","gender"=>"Male","race"=>"White","state"=>"Virginia","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Appalachians Against Pipelines"],"in_custody"=>false,"released"=>true,"description"=>"Galen Sol Shireman-Grabowski, age 24, locked himself to a helicopter used by Mountain Valley Pipeline crews in Ellison, Virginia in October 2019, damaging the helicopter. Charged with multiple felonies and misdemeanors; pleaded guilty to four counts and received a 12-month suspended sentence plus $14,030.41 in restitution.","cases"=>[["institution_name"=>"Bland County Circuit Court","institution_state"=>"Virginia","charges"=>"Va. Code 18.2-121 entering property to damage; 5.1-22 interference with operation of aircraft; 18.2-137 destruction of property/monument; 18.2-422 wearing of masks; 18.2-460 obstructing justice; 18.2-404 obstructing free passage; 18.2-146 tampering with vehicle/aircraft - 2019 MVP helicopter lock-on action, Ellison VA","arrest_date"=>"2020-04-28","convicted"=>"Yes - guilty plea","sentence"=>"12-month suspended sentence + $14,030.41 restitution + community service"]]],
    ["name"=>"Anne Rolfes","first_name"=>"Anne","last_name"=>"Rolfes","gender"=>"Female","race"=>"White","state"=>"Louisiana","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Louisiana Bucket Brigade"],"in_custody"=>false,"released"=>true,"description"=>"Anne Rolfes, age 52, executive director of the Louisiana Bucket Brigade, was arrested June 25, 2020 and charged with felony \"terrorizing\" for delivering a box of plastic pellets to an oil-and-gas lobbyists home in Baton Rouge to protest a proposed petrochemical and plastics facility. Louisiana prosecutors later announced they would not prosecute.","cases"=>[["institution_name"=>"East Baton Rouge Parish Prison","institution_city"=>"Baton Rouge","institution_state"=>"Louisiana","charges"=>"La. Rev. Stat. 14:40.1 terrorizing - June 2020 plastic-pellets delivery to oil-and-gas lobbyist","arrest_date"=>"2020-06-25","convicted"=>"No - charges declined by prosecutors","sentence"=>"Charges declined"]]],
    ["name"=>"Kate McIntosh","first_name"=>"Kate","last_name"=>"McIntosh","gender"=>"Female","race"=>"White","state"=>"Louisiana","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Louisiana Bucket Brigade"],"in_custody"=>false,"released"=>true,"description"=>"Kate McIntosh, age 26, of the Louisiana Bucket Brigade, was arrested June 25, 2020 and booked with \"principal to terrorizing\" for delivering a box of plastic pellets to an oil-and-gas lobbyists home in Baton Rouge. Charges later declined.","cases"=>[["institution_name"=>"East Baton Rouge Parish Prison","institution_city"=>"Baton Rouge","institution_state"=>"Louisiana","charges"=>"La. Rev. Stat. 14:40.1 terrorizing (principal) - June 2020 plastic-pellets delivery","arrest_date"=>"2020-06-25","convicted"=>"No - charges declined","sentence"=>"Charges declined"]]],
    ["name"=>"Ellen Brennan Reiche","first_name"=>"Ellen","middle_name"=>"Brennan","last_name"=>"Reiche","gender"=>"Female","race"=>"White","state"=>"Washington","era"=>"2020s","ideologies"=>["Environmental Activism","Indigenous Sovereignty"],"in_custody"=>false,"released"=>true,"description"=>"Ellen Brennan Reiche, age 28, of Bellingham WA, was indicted December 2020 under the federal anti-railroad-violence statute for placing a shunt on BNSF Railway tracks near Bellingham on November 28, 2020 in solidarity with the Wetsuweten pipeline-resistance struggle. Sentenced to 12 months and 1 day federal prison plus 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"18 USC 1992(a)(5) terrorist attacks and other violence against railroad carriers - 2020 BNSF Railway track shunt action near Bellingham WA in Wetsuweten solidarity","arrest_date"=>"2020-11-28","incarceration_date"=>"2020-12-09","convicted"=>"Yes - guilty plea","sentence"=>"12 months + 1 day federal prison + 3 years supervised release"]]],
    ["name"=>"Samantha Frances Brooks","first_name"=>"Samantha","middle_name"=>"Frances","last_name"=>"Brooks","gender"=>"Female","race"=>"White","state"=>"Washington","era"=>"2020s","ideologies"=>["Environmental Activism","Indigenous Sovereignty"],"in_custody"=>false,"released"=>true,"description"=>"Samantha Frances Brooks, age 24, was indicted December 2020 alongside Ellen Reiche for the November 28, 2020 BNSF Railway track shunt action near Bellingham WA in Wetsuweten solidarity. Sentenced to 6 months federal prison plus 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"18 USC 1992(a)(5) terrorist attacks and other violence against railroad carriers - 2020 Bellingham WA BNSF shunt action","arrest_date"=>"2020-11-28","incarceration_date"=>"2020-12-09","convicted"=>"Yes - guilty plea","sentence"=>"6 months federal prison + 3 years supervised release"]]],
    ["name"=>"Mylene Vialard","first_name"=>"Mylene","last_name"=>"Vialard","gender"=>"Female","race"=>"White","state"=>"Minnesota","era"=>"2020s","ideologies"=>["Environmental Activism","Indigenous Sovereignty"],"in_custody"=>false,"released"=>true,"description"=>"Mylene Vialard, age 54, attached herself to a 25-foot bamboo tower blocking a Line 3 pipeline pumping station in Aitkin County, Minnesota on August 21, 2021 in support of the water-protector resistance to the pipeline through Indigenous territory. Convicted of felony obstruction; 2 days county jail plus 1 year probation.","cases"=>[["institution_name"=>"Itasca County District Court","institution_state"=>"Minnesota","charges"=>"Minn. Stat. 609.50.1(2) obstructing legal process (felony); 609.6055.2(a)(3) gross misdemeanor trespass on critical public-service facility (dropped) - August 2021 Line 3 pipeline pumping-station blockade","arrest_date"=>"2021-08-21","convicted"=>"Yes - jury verdict","sentence"=>"2 days county jail + 1 year probation"]]],
    ["name"=>"Joanna Smith","first_name"=>"Joanna","last_name"=>"Smith","gender"=>"Female","race"=>"White","state"=>"District of Columbia","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Declare Emergency"],"in_custody"=>false,"released"=>true,"description"=>"Joanna Smith, age 53, of Declare Emergency, smeared black and red paint on the case and pedestal of Edgar Degas \"Little Dancer Aged Fourteen\" sculpture at the National Gallery of Art on April 27, 2023 to demand a presidential climate emergency declaration. Pleaded guilty to injuring NGA property; 60-day federal sentence.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 371 conspiracy to commit an offense against the United States; 40 USC 6303, 6307 injury to National Gallery of Art property - 2023 Little Dancer paint action","arrest_date"=>"2023-05-24","incarceration_date"=>"2023-05-24","convicted"=>"Yes - guilty plea","sentence"=>"60 days federal prison"]]],
    ["name"=>"Cameron Monte Smith","first_name"=>"Cameron","middle_name"=>"Monte","last_name"=>"Smith","gender"=>"Male","race"=>"White","state"=>"North Dakota","era"=>"2020s","ideologies"=>["Environmental Activism","Indigenous Sovereignty"],"in_custody"=>true,"released"=>false,"description"=>"Cameron Monte Smith, a Canadian national in the U.S. illegally, age 49, fired shots into the Wheelock Substation near Ray, North Dakota in May 2023, knocking out power for 240+ people and causing $1.2 million in damage. He had previously fired shots at a Keystone Pipeline transformer and pump station near Carpenter, South Dakota in July 2022. Documents indicated DAPL spray-painted near the substation. Pleaded guilty in both districts to one count each of destruction of an energy facility; 25 years federal prison total (consecutive 150-month sentences). The federal judge found his crimes met the definition of terrorism; the case was prosecuted by the National Security Division Counterterrorism Section.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"North Dakota","charges"=>"18 USC 922(g)(5)(A) possession of firearm by an illegal alien; 18 USC 924(a)(8) possession of ammunition by an illegal alien; 18 USC 1366(a) destruction of an energy facility - 2022 Keystone Pipeline (Carpenter SD) and 2023 Wheelock Substation (Ray ND) attacks","arrest_date"=>"2023-07-12","incarceration_date"=>"2023-07-12","convicted"=>"Yes - guilty plea","sentence"=>"300 months federal prison total (150 ND + 150 SD consecutive); terrorism enhancement applied"]]],
    ["name"=>"Jackson George Green","first_name"=>"Jackson","middle_name"=>"George","last_name"=>"Green","gender"=>"Male","race"=>"White","state"=>"Utah","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Declare Emergency"],"in_custody"=>false,"released"=>true,"description"=>"Jackson George Green, age 27, of Declare Emergency, painted \"Honor Them\" on the wall next to Augustus Saint-Gaudens Shaw 54th Regiment Memorial in the National Gallery of Art on November 14, 2023, causing over $700 in damage. Sentenced to 21 months federal prison. Co-charged in February 2024 with Donald Jose-David Zepeda for the November 25, 2024 red-powder action at the U.S. Constitution display in the National Archives Rotunda; sentenced to 18 months for that case (concurrent).","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"40 USC 6303, 6307 destruction of National Gallery of Art property - 2023 Honor Them paint action; 22 DC 3312.01, 22 DC 303 defacing/destroying public property - 2024 National Archives red-powder Constitution action","arrest_date"=>"2024-02-01","incarceration_date"=>"2024-02-01","convicted"=>"Yes - guilty plea","sentence"=>"21 months federal prison (NGA action) + 18 months (Archives action) + ~$58,600 restitution"]]],
    ["name"=>"Donald Jose-David Zepeda","first_name"=>"Donald","middle_name"=>"Jose-David","last_name"=>"Zepeda","gender"=>"Male","race"=>"White","state"=>"Maryland","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Declare Emergency"],"in_custody"=>false,"released"=>true,"description"=>"Donald Jose-David Zepeda, age 35, of Maryland and Declare Emergency, was charged with co-defendant Jackson Green for dumping red powder over a display case containing the U.S. Constitution in the National Archives Rotunda on November 25, 2024 (note: TPP records the action year as 2024 though sentencing came shortly after). Sentenced to 24 months federal prison plus $58,600 restitution.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"22 DC 3312.01 defacing public/private property; 22 DC 303 destroying property - 2024 National Archives red-powder Constitution action","arrest_date"=>"2024-02-15","incarceration_date"=>"2024-02-15","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison + $58,600 restitution"]]],
    ["name"=>"Brian Okum","first_name"=>"Brian","last_name"=>"Okum","gender"=>"Male","race"=>"White","state"=>"Massachusetts","era"=>"2020s","ideologies"=>["Environmental Activism"],"affiliation"=>["Extinction Rebellion"],"in_custody"=>false,"released"=>true,"description"=>"Brian Okum, an Extinction Rebellion climate activist, was charged with felony malicious destruction of property over $1,200, disorderly conduct, and trespass for an April 2024 protest at Hanscom Field opposing a private-jet hangar expansion. Acquitted of the felony and the disorderly conduct counts; convicted of misdemeanor trespass; sentenced to 1 year probation in May 2025.","cases"=>[["institution_name"=>"Concord District Court","institution_state"=>"Massachusetts","charges"=>"Mass. Gen. Laws ch. 266:127 malicious destruction of property over $1,200 (acquitted); 272:53 disorderly conduct (acquitted); 266:120 trespassing (convicted) - April 2024 Hanscom Field private-jet hangar protest","arrest_date"=>"2024-04-01","convicted"=>"Yes on trespassing; acquitted on felony and disorderly","sentence"=>"1 year probation"]]],

    // ---- Rows 223-228: Anti-government / militia-adjacent ----
    ["name"=>"Frederick Urban","first_name"=>"Frederick","last_name"=>"Urban","gender"=>"Male","race"=>"White","state"=>"Pennsylvania","era"=>"1990s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Frederick Urban, age 46, was arrested April 1995 in Scranton, Pennsylvania while driving a van containing explosive devices; statements he made indicated intent to use the explosives against the federal government and a right-wing anti-government ideology. Convicted at trial of possession of an unregistered destructive device with a special-skill enhancement.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Pennsylvania","charges"=>"Federal possession of an unregistered destructive device (with special-skill enhancement) - 1995 Scranton PA arrest","arrest_date"=>"1995-04-18","incarceration_date"=>"1995-04-18","convicted"=>"Yes - jury verdict","sentence"=>"Data not available"]]],
    ["name"=>"John J. Ford","first_name"=>"John","last_name"=>"Ford","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"1990s","ideologies"=>["Anti-government"],"affiliation"=>["Long Island UFO Network"],"in_custody"=>false,"released"=>true,"description"=>"John J. Ford, age 47, was president of the Long Island UFO Network. He and two co-conspirators were arrested in June 1996 over a plot to use radium-laced canisters to murder Suffolk County Republican leader John Powell and two county officials, accusing the local government of covering up UFO sightings. Found incompetent to stand trial.","cases"=>[["institution_name"=>"Suffolk County jail / state psychiatric facility","institution_state"=>"New York","charges"=>"New York state conspiracy and possession charges related to plot to deploy radium against Suffolk County officials","arrest_date"=>"1997-06-11","convicted"=>"No - found incompetent to stand trial","sentence"=>"Charged but not tried; civil commitment"]]],
    ["name"=>"Joseph Mazzuchelli","first_name"=>"Joseph","last_name"=>"Mazzuchelli","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"1990s","ideologies"=>["Anti-government"],"affiliation"=>["Long Island UFO Network"],"in_custody"=>false,"released"=>true,"description"=>"Joseph Mazzuchelli, age 42, was a co-conspirator with John Ford and Edward Zabo in a 1996 plot to use radium-laced canisters to murder Suffolk County Republican leader John Powell and two county officials. Pleaded guilty to second-degree conspiracy and related charges; 36 months state prison.","cases"=>[["institution_name"=>"New York state Department of Corrections","institution_state"=>"New York","charges"=>"NY state second-degree conspiracy; criminal solicitation; illegal possession of radioactive materials; reckless endangerment - 1996 Suffolk County radium-canister plot","arrest_date"=>"1997-06-11","incarceration_date"=>"1997-06-11","convicted"=>"Yes - guilty plea","sentence"=>"36 months state prison"]]],
    ["name"=>"Edward Zabo","first_name"=>"Edward","last_name"=>"Zabo","gender"=>"Male","race"=>"White","state"=>"New York","era"=>"1990s","ideologies"=>["Anti-government"],"affiliation"=>["Long Island UFO Network"],"in_custody"=>false,"released"=>true,"description"=>"Edward Zabo, age 49, was a co-conspirator with John Ford and Joseph Mazzuchelli in the 1996 Long Island UFO Network plot to use radium against Suffolk County officials. Pleaded guilty to supplying radioactive materials; 12 months state prison.","cases"=>[["institution_name"=>"New York state Department of Corrections","institution_state"=>"New York","charges"=>"NY state supplying radioactive materials - 1996 Suffolk County radium-canister plot","arrest_date"=>"1997-06-11","incarceration_date"=>"1997-06-11","convicted"=>"Yes - guilty plea","sentence"=>"12 months state prison"]]],
    ["name"=>"James Kenneth Gluck","first_name"=>"James","middle_name"=>"Kenneth","last_name"=>"Gluck","gender"=>"Male","state"=>"Colorado","era"=>"1990s","ideologies"=>["Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"James Kenneth Gluck, age 53, was arrested in Tampa, Florida in November 1999 for threatening to use ricin and explosives against judicial officials in Jefferson County, Colorado. Investigators found anti-government literature, The Anarchist Cookbook, and a makeshift laboratory with ricin precursors at his home. Charged with two counts of threatening court officers.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Colorado","charges"=>"Federal issuing threats against court officers [2 counts] - November 1999 Jefferson County CO ricin-threat plot","arrest_date"=>"1999-11-05","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    // ---- Sherman Austin (raisethefist), Konopka (Dr. Chaos), Revak ----
    ["name"=>"Sherman Martin Austin","first_name"=>"Sherman","middle_name"=>"Martin","last_name"=>"Austin","gender"=>"Male","race"=>"Black","state"=>"California","era"=>"2000s","ideologies"=>["Anarchism"],"in_custody"=>false,"released"=>true,"description"=>"Sherman Martin Austin, age 18, was the founder and webmaster of the anarchist website raisethefist.com. Pleaded guilty in 2002 to distribution of information about making or using explosives with intent that the information be used in furtherance of a federal crime of violence. Sentenced to 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"California","charges"=>"18 USC 842(p) distribution of bomb-making information with intent that it be used for a federal crime of violence - raisethefist.com","arrest_date"=>"2002-02-05","incarceration_date"=>"2002-02-05","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],
    ["name"=>"Joseph Konopka","first_name"=>"Joseph","last_name"=>"Konopka","aka"=>"Dr. Chaos","gender"=>"Male","race"=>"White","state"=>"Illinois","era"=>"2000s","ideologies"=>["Anarchism","Anti-government"],"affiliation"=>["The Realm of Chaos"],"in_custody"=>false,"released"=>true,"description"=>"Joseph Konopka (Dr. Chaos), age 25, was sentenced March 12, 2003 to 156 months federal prison for hiding cyanide in a Chicago subway tunnel along with multiple counts of vandalism and attacks on infrastructure under the banner of his \"Realm of Chaos\" group.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"Federal possession of a chemical weapon and conspiracy to commit terrorism - cyanide hidden in Chicago subway tunnel and related infrastructure attacks","arrest_date"=>"2003-03-12","incarceration_date"=>"2003-03-12","convicted"=>"Yes - guilty plea","sentence"=>"156 months federal prison"]]],
    ["name"=>"Paul Douglas Revak","first_name"=>"Paul","middle_name"=>"Douglas","last_name"=>"Revak","gender"=>"Male","race"=>"White","state"=>"Washington","era"=>"2000s","ideologies"=>["Anarchism","Anti-government"],"in_custody"=>false,"released"=>true,"description"=>"Paul Douglas Revak, age 20, an anarchist, was arrested after attempting to purchase explosives from an undercover FBI agent and plotting to bomb a U.S. Coast Guard facility in Bellingham, Washington in 2003. Pleaded guilty to threats to use a weapon of mass destruction and solicitation to commit a crime of violence; sentenced to probation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Washington","charges"=>"Federal threats to use a WMD and solicitation to commit a crime of violence - 2003 plot against Coast Guard facility, Bellingham WA","arrest_date"=>"2003-06-09","convicted"=>"Yes - guilty plea","sentence"=>"Probation"]]],

    // ---- Wade Lay & Chris Lay (anti-Waco bank robbery, OK death row) ----
    ["name"=>"Wade Greely Lay","first_name"=>"Wade","middle_name"=>"Greely","last_name"=>"Lay","gender"=>"Male","race"=>"White","state"=>"Oklahoma","era"=>"2000s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Wade Greely Lay, age 44, and his son Christopher Lay attempted to rob a Tulsa, Oklahoma bank on May 24, 2004 to fund what they described as a vendetta against the federal government in retribution for the 1993 Waco siege. A bank security guard was killed during the failed robbery. Lay was convicted of first-degree murder and attempted robbery; sentenced to death.","cases"=>[["institution_name"=>"Oklahoma State Penitentiary","institution_city"=>"McAlester","institution_state"=>"Oklahoma","charges"=>"Oklahoma state first-degree murder; attempted robbery with a firearm - 2004 Tulsa bank-robbery attempt with anti-government Waco motivation","arrest_date"=>"2004-05-24","incarceration_date"=>"2004-05-24","convicted"=>"Yes - jury verdict","sentence"=>"Death sentence"]]],
    ["name"=>"Christopher Lay","first_name"=>"Christopher","last_name"=>"Lay","aka"=>"Chris Lay","gender"=>"Male","race"=>"White","state"=>"Oklahoma","era"=>"2000s","ideologies"=>["Anti-government"],"in_custody"=>true,"released"=>false,"description"=>"Christopher Lay, age 20, son of Wade Lay, participated in the May 24, 2004 Tulsa bank-robbery attempt motivated by anti-federal-government grievance over the 1993 Waco siege. A bank security guard was killed. Convicted of first-degree murder and attempted robbery; sentenced to life in Oklahoma state prison.","cases"=>[["institution_name"=>"Oklahoma Department of Corrections","institution_state"=>"Oklahoma","charges"=>"Oklahoma state first-degree murder; attempted robbery with a firearm - 2004 Tulsa bank-robbery attempt","arrest_date"=>"2004-05-24","incarceration_date"=>"2004-05-24","convicted"=>"Yes - jury verdict","sentence"=>"Life in Oklahoma state prison"]]],

    // ---- Carlos Gamarra-Murillo (FARC weapons broker, served US time) ----
    ["name"=>"Carlos Gamarra-Murillo","first_name"=>"Carlos","last_name"=>"Gamarra-Murillo","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2000s","ideologies"=>["Communism"],"affiliation"=>["FARC"],"in_custody"=>false,"released"=>true,"description"=>"Carlos Gamarra-Murillo, age 54, U.S. citizen, worked as a weapons broker for FARC and was caught in an Immigration and Customs Enforcement sting in 2005. He had attempted to trade 4,400 pounds of cocaine for M-60 machine guns, grenade launchers, M-16 rifles, and other weapons in a $4 million deal with undercover agents in Tampa, Florida. Pleaded guilty in 2005; 300 months federal prison plus 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"22 USC 2778(a) exportation of munitions; federal drug, material-support, and firearms violations - 2005 FARC weapons-for-cocaine ICE sting in Tampa","arrest_date"=>"2005-02-11","incarceration_date"=>"2005-02-11","convicted"=>"Yes - guilty plea","sentence"=>"300 months federal prison + 3 years supervised release"]]],
];

// ---- FARC defendants from MARIN, AGUABLANCA, CARACAS, SILVA, TORRES ----
// Most never captured. Add only those with positive sentence months
// (extradited and served U.S. federal time) per the projects
// U.S.-nexus scope rule. Includes the Bogota-grenade defendants
// who remain fugitives but are listed as U.S.-indicted defendants.

$farc_extradited = [
    ["name"=>"Daniel Barrera Barrera","aka"=>"El Loco","sentence_months"=>420,"summary"=>"Daniel Barrera Barrera (El Loco) was extradited to the U.S. and pleaded guilty to conspiracy to import cocaine in connection with the the FARCs 16th Front cocaine-trafficking network operating from an airstrip near Barranco Minas, Colombia. Sentenced to 420 months federal prison plus a $10 million fine.","arrest_date"=>"2002-10-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida","age"=>48],
    ["name"=>"Juvenal Ovidio Ricardo Palmera Pineda","aka"=>"Simon Trinidad","sentence_months"=>720,"summary"=>"Juvenal Ovidio Ricardo Palmera Pineda (Simon Trinidad) was a high-ranking FARC member extradited to the U.S. for the kidnapping of three Americans in Colombia. Convicted at trial of hostage-taking and providing material support to terrorists; sentenced to 720 months federal prison.","arrest_date"=>"2004-05-13","institution"=>"ADX Florence","city"=>"Florence","state"=>"Colorado","age"=>56],
    ["name"=>"Jorge Enrique Rodriguez Mendieta","aka"=>"Ivan Vargas","sentence_months"=>244,"summary"=>"Jorge Enrique Rodriguez Mendieta (Ivan Vargas) was extradited from Colombia and pleaded guilty to FARC narcotics conspiracy. Sentenced to 244 months federal prison plus 60 months supervised release.","arrest_date"=>"2005-04-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida","age"=>57],
    ["name"=>"Gerardo Aguilar Ramirez","aka"=>"Cesar","sentence_months"=>324,"summary"=>"Gerardo Aguilar Ramirez (Cesar) was extradited from Colombia and pleaded guilty to FARC narcotics conspiracy; sentenced to 324 months federal prison with 24 months credit for time served.","arrest_date"=>"2005-04-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida"],
    ["name"=>"Ignacio Leal Garcia","aka"=>"Camilo, Tuerto","sentence_months"=>294,"summary"=>"Ignacio Leal Garcia (Camilo, Tuerto) was extradited from Colombia, tried, and convicted of FARC narcotics conspiracy; sentenced to 294 months federal prison plus 60 months supervised release.","arrest_date"=>"2005-04-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida"],
    ["name"=>"Erminso Cuevas Cabrera","aka"=>"Mincho","sentence_months"=>348,"summary"=>"Erminso Cuevas Cabrera (Mincho) was extradited from Colombia, tried, and convicted of FARC narcotics conspiracy; sentenced to 348 months federal prison plus 60 months supervised release.","arrest_date"=>"2005-04-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida"],
    ["name"=>"Juan Jose Martinez Vega","aka"=>"Gentil Alvis Patino, Chiguiro","sentence_months"=>330,"summary"=>"Juan Jose Martinez Vega (Chiguiro) was extradited from Colombia, tried, and convicted of FARC narcotics conspiracy; sentenced to 330 months federal prison plus a required English educational/vocational training program.","arrest_date"=>"2005-04-29","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"Florida"],
    ["name"=>"German Briceno Suarez","aka"=>"Granobles","sentence_months"=>480,"summary"=>"German Briceno Suarez (Granobles) was a FARC commander charged in the AGUABLANCA prosecution for the 1999 kidnapping and murder of three U.S. citizens in Colombia. Convicted in absentia; 480 months federal prison. Has not been captured.","arrest_date"=>"2002-04-30","institution"=>"Federal Bureau of Prisons (location varied)","state"=>"District of Columbia"],
];

foreach ($farc_extradited as $f) {
    $rows[] = [
        "name" => $f["name"],
        "first_name" => explode(" ", $f["name"])[0],
        "last_name" => array_slice(explode(" ", $f["name"]), -1)[0],
        "aka" => $f["aka"] ?? null,
        "gender" => "Male",
        "race" => "Latino/Hispanic",
        "state" => $f["state"] ?? "Florida",
        "era" => "2000s",
        "ideologies" => ["Communism"],
        "affiliation" => ["FARC"],
        "in_custody" => false,
        "released" => true,
        "description" => $f["summary"],
        "cases" => [[
            "institution_name" => $f["institution"],
            "institution_city" => $f["city"] ?? null,
            "institution_state" => $f["state"] ?? null,
            "charges" => "Federal FARC-related charges (narcotics conspiracy, hostage-taking, material support to terrorists, or weapons-export violations) following extradition from Colombia or in-absentia conviction",
            "arrest_date" => $f["arrest_date"],
            "incarceration_date" => $f["arrest_date"],
            "convicted" => "Yes - guilty plea or jury verdict",
            "sentence" => $f["sentence_months"] . " months federal prison",
        ]],
    ];
}

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";

echo "\nNote: rows 232-300 from the source dataset that are FARC defendants \"charged but not tried\" (still fugitives or killed in Colombian military operations) were NOT created - they fall outside the projects stated scope (\"prisoners held in U.S. custody or whose imprisonment is the direct result of U.S. action\"). The 8 FARC defendants who were extradited and served U.S. federal time WERE created.\n";
'

echo
echo "Prosecution Project rows 201-300 import complete."
