#!/usr/bin/env bash
# Run on production server (104.238.162.40):
#   cd /var/www/NPPC-Website && bash scripts/import_tpp_eco_animal_rows_8.sh
#
# Eighth batch (rows 801-900). Skipped per established U.S.-nexus
# scope rule:
#   - 801-806: UMich MUELLER cluster already imported in batch 7
#   - 813-817: 5 unnamed RAMINC Raytheon defendants (no real names)
#   - 833-834: Kleckner / Victor H. Smith already in DB from batch 7
#   - Foreign-national fugitives never tried in U.S. court: Mousa
#     Abu Marzook, Nadia Elashi (HAMAS); Haitham Maghawri, Akram
#     Mishal (HLF); Mohammed Tasir Hassan Al-Khatib, Abd Al-Aziz
#     Awda, Bashir Musa Mohammed Nafi, Ramadan Abdullah Mohammad
#     Shallah (PIJ; Shallah died Lebanon 2020); Gaspar Raj Maria
#     Paulian, Namasivaya Viswanathan (LTTE); Yaser Khareddin
#     Bushnaq (IAP)
#   - Anthonius Wamang: tried in Indonesia, never in U.S. custody
set -e

php artisan tinker --execute='
$rows = [
    ["name"=>"Lucas Jensen Griffith","first_name"=>"Lucas","middle_name"=>"Jensen","last_name"=>"Griffith","gender"=>"Male","race"=>"White","state"=>"Kentucky","era"=>"2020s","ideologies"=>["Pro-immigrant","Anti-ICE"],"in_custody"=>false,"released"=>true,"description"=>"Lucas Jensen Griffith, 21, photo intern for Cincinnati alt-weekly CityBeat, was charged July 18, 2025 with 15 others in connection with a July 17, 2025 protest on the Roebling Suspension Bridge between Cincinnati OH and Covington KY against ICEs detention of Imam Ayman Soliman. Griffith was covering the protest as press when arrested. Felony riot charge dismissed with prejudice; misdemeanors via plea.","cases"=>[["institution_name"=>"Kenton County Detention Center","institution_state"=>"Kentucky","charges"=>"KRS 525.020 Riot in the First Degree (Class D felony, dismissed with prejudice); 525.050 Unlawful Assembly; 525.160 Failure to Disperse; 525.140 Obstructing a Highway; 520.090 Resisting Arrest - July 2025 Roebling Bridge ICE-detention protest","arrest_date"=>"2025-07-18","convicted"=>"Yes - guilty plea on misdemeanors; felony dismissed with prejudice","sentence"=>"Local sentence"]]],

    ["name"=>"Madeline Rose Fening","first_name"=>"Madeline","middle_name"=>"Rose","last_name"=>"Fening","gender"=>"Female","race"=>"White","state"=>"Kentucky","era"=>"2020s","ideologies"=>["Pro-immigrant","Anti-ICE"],"in_custody"=>false,"released"=>true,"description"=>"Madeline Rose Fening, 33, investigative reporter for CityBeat, charged July 18, 2025 in connection with the July 17, 2025 Roebling Suspension Bridge ICE-detention protest. Felony riot charge dismissed with prejudice.","cases"=>[["institution_name"=>"Kenton County Detention Center","institution_state"=>"Kentucky","charges"=>"KRS 525.020 Riot I (dismissed with prejudice); 525.050 Unlawful Assembly; 525.160 Failure to Disperse; 525.140 Obstructing a Highway - July 2025 Roebling Bridge protest","arrest_date"=>"2025-07-18","convicted"=>"No - charged but not tried","sentence"=>"Felony dismissed"]]],

    ["name"=>"Brennon J. Nastacio","first_name"=>"Brennon","middle_name"=>"J.","last_name"=>"Nastacio","aka"=>"Bravo One","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"affiliation"=>["NoDAPL"],"in_custody"=>false,"released"=>true,"description"=>"Brennon J. Nastacio, 36, NoDAPL Water Protector, was indicted November 23, 2016 in Bismarck ND for an alleged October 2016 confrontation with a contractor near Standing Rock; the contractors vehicle was rammed and burned, and Nastacio was accused of pointing at him with a rifle. Charges dropped due to inconsistent statements from the contractor.","cases"=>[["institution_name"=>"Burleigh-Morton Detention Center","institution_state"=>"North Dakota","charges"=>"ND Cent Code 12.1-17-04 Terrorizing; Criminal Mischief - Oct 2016 Standing Rock contractor confrontation","arrest_date"=>"2016-11-23","convicted"=>"No - charges dropped","sentence"=>"Dismissed"]]],

    ["name"=>"Michael Fasig","first_name"=>"Michael","last_name"=>"Fasig","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"affiliation"=>["NoDAPL"],"in_custody"=>false,"released"=>true,"description"=>"Michael Fasig, 46, NoDAPL Water Protector, charged Nov 23, 2016 with reckless endangerment and criminal mischief related to ramming a security guards truck near Standing Rock. Charges reduced to misdemeanor; $2,000 fines, one year supervised release.","cases"=>[["institution_name"=>"Burleigh-Morton Detention Center","institution_state"=>"North Dakota","charges"=>"ND Class C Felony Reckless Endangerment; Criminal Mischief (reduced to misdemeanor) - Oct 2016 Standing Rock","arrest_date"=>"2016-11-23","convicted"=>"Yes - guilty plea","sentence"=>"$2,000 fines + 1 year supervised release"]]],

    ["name"=>"Israel L. Hernandez","first_name"=>"Israel","middle_name"=>"L.","last_name"=>"Hernandez","gender"=>"Male","race"=>"American Indian / Alaska Native","state"=>"North Dakota","era"=>"2010s","ideologies"=>["Indigenous Sovereignty","Environmental Activism"],"affiliation"=>["NoDAPL"],"in_custody"=>false,"released"=>true,"description"=>"Israel L. Hernandez, 22, NoDAPL Water Protector, charged Nov 23, 2016 with reckless endangerment and criminal mischief at Standing Rock. Charges reduced to misdemeanor; $325 fees, community service, 9 months supervised release.","cases"=>[["institution_name"=>"Burleigh-Morton Detention Center","institution_state"=>"North Dakota","charges"=>"ND Reckless Endangerment; Criminal Mischief (misdemeanor) - Oct 2016 Standing Rock","arrest_date"=>"2016-11-23","convicted"=>"Yes - guilty plea","sentence"=>"$325 fees + community service + 9 mo supervised release"]]],

    ["name"=>"Anthony Ladd","first_name"=>"Anthony","last_name"=>"Ladd","gender"=>"Male","race"=>"White","state"=>"Nebraska","era"=>"2020s","ideologies"=>["Reproductive Rights"],"in_custody"=>false,"released"=>true,"description"=>"Anthony Ladd, 45, was arrested January 12, 2022 after threatening a pro-life advocate with a section of rebar outside a Lincoln NE Planned Parenthood. Charged with terroristic threats. Sentence not publicly available (records page removed for privacy).","cases"=>[["institution_name"=>"Lancaster County District Court","institution_state"=>"Nebraska","charges"=>"Nebraska Making Terroristic Threats - Jan 2022 Lincoln Planned Parenthood","arrest_date"=>"2022-01-12","convicted"=>"Data not available","sentence"=>"Data not available"]]],

    ["name"=>"Caleb Hunter Freestone","first_name"=>"Caleb","middle_name"=>"Hunter","last_name"=>"Freestone","aka"=>"Kya","gender"=>"Male","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Janes Revenge"],"in_custody"=>false,"released"=>true,"description"=>"Caleb Hunter Freestone, 27, was indicted January 18, 2023 (and superseding March 22, 2023) for FACE Act conspiracy: spray-painting threats on Florida crisis pregnancy centers in summer 2022 after the Dobbs decision (If abortions arent safe than either are you, YOURE TIME IS UP, WERE COMING for U). Pleaded guilty; 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 241 Conspiracy Against Rights; 18 USC 248 Freedom of Access to Clinic Entrances - 2022 FL crisis pregnancy center vandalism","arrest_date"=>"2023-01-18","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Amber Marie Smith-Stewart","first_name"=>"Amber","middle_name"=>"Marie","last_name"=>"Smith-Stewart","aka"=>"Ae, 16inches","gender"=>"Other","race"=>"Latino/Hispanic","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Janes Revenge"],"in_custody"=>false,"released"=>true,"description"=>"Amber Marie Smith-Stewart, 23, gender non-conforming, co-defendant of Caleb Freestone in the Janes Revenge Florida crisis pregnancy center vandalism case. Pleaded guilty; 1 month federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 241; 18 USC 248 FACE Act - 2022 FL CPC vandalism","arrest_date"=>"2023-01-18","convicted"=>"Yes - guilty plea","sentence"=>"1 month federal prison"]]],

    ["name"=>"Annarella Rivera","first_name"=>"Annarella","last_name"=>"Rivera","aka"=>"Rivers","gender"=>"Other","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Janes Revenge"],"in_custody"=>false,"released"=>true,"description"=>"Annarella Rivera, co-defendant added in the March 22, 2023 superseding indictment in the Janes Revenge Florida CPC case. Pleaded guilty; 1 month federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 241; 18 USC 248 FACE Act - 2022 FL CPC vandalism","arrest_date"=>"2023-03-22","convicted"=>"Yes - guilty plea","sentence"=>"1 month federal prison"]]],

    ["name"=>"Gabriella Victoria Oropesa","first_name"=>"Gabriella","middle_name"=>"Victoria","last_name"=>"Oropesa","aka"=>"Gabs, Gaby, Gummy","gender"=>"Other","state"=>"Florida","era"=>"2020s","ideologies"=>["Reproductive Rights"],"affiliation"=>["Janes Revenge"],"in_custody"=>false,"released"=>true,"description"=>"Gabriella Victoria Oropesa, gender non-conforming, co-defendant added in the March 2023 superseding indictment in the Janes Revenge Florida CPC case. Convicted at trial; sentencing pending.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 241; 18 USC 248 FACE Act - 2022 FL CPC vandalism","arrest_date"=>"2023-03-22","convicted"=>"Yes - jury verdict","sentence"=>"Pending"]]],

    ["name"=>"Hridindu Sankar Roychowdhury","first_name"=>"Hridindu","middle_name"=>"Sankar","last_name"=>"Roychowdhury","gender"=>"Male","race"=>"South Asian","state"=>"Wisconsin","era"=>"2020s","ideologies"=>["Reproductive Rights","Anarchism"],"in_custody"=>true,"released"=>false,"description"=>"Hridindu Sankar Roychowdhury, 30, of Madison WI, was arrested March 28, 2023 for the May 8, 2022 arson attack on Wisconsin Family Action, a Madison crisis pregnancy center, using mason-jar Molotovs. Spray-painted If abortions arent safe then you arent either and a circle-A with 1312 outside the building. Pleaded guilty; sentenced to 90 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"18 USC 844(i) Destruction of Building Used in Interstate Commerce by Fire - May 8 2022 Wisconsin Family Action arson","arrest_date"=>"2023-03-28","convicted"=>"Yes - guilty plea","sentence"=>"90 months federal prison"]]],

    ["name"=>"Chrisley Marie Solidum Carpio","first_name"=>"Chrisley","middle_name"=>"Marie Solidum","last_name"=>"Carpio","gender"=>"Female","race"=>"South Asian","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-DeSantis","Anti-DEI-Repeal"],"in_custody"=>false,"released"=>true,"description"=>"Chrisley Marie Solidum Carpio, 31, was one of the Tampa Five charged March 6, 2023 with battery on a LEO, disrupting a school function, and resisting an officer at a USF protest against Ron DeSantiss HB 999 (anti-DEI legislation). Charges dropped December 5, 2023; entered diversion program.","cases"=>[["institution_name"=>"Hillsborough County Sheriffs Office","institution_state"=>"Florida","charges"=>"FL Battery on a Law Enforcement Officer; Disrupting School Campus or Function; Resisting Officer Without Violence - March 2023 USF anti-HB-999 protest","arrest_date"=>"2023-03-06","convicted"=>"No - dismissed via diversion","sentence"=>"Diversion + community service + 1 yr campus ban"]]],

    ["name"=>"Gia Marie Davila","first_name"=>"Gia","middle_name"=>"Marie","last_name"=>"Davila","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-DeSantis","Anti-DEI-Repeal"],"in_custody"=>false,"released"=>true,"description"=>"Gia Marie Davila, 21, USF student, Tampa Five defendant; charged March 6, 2023 at the USF anti-HB-999 protest. Charges dropped December 5, 2023; diversion program.","cases"=>[["institution_name"=>"Hillsborough County Sheriffs Office","institution_state"=>"Florida","charges"=>"FL Battery on a LEO; Disrupting School Campus; Trespass in Occupied Structure; Resisting Officer Without Violence - March 2023 USF","arrest_date"=>"2023-03-06","convicted"=>"No - dismissed via diversion","sentence"=>"Diversion"]]],

    ["name"=>"Jeanie Kida","first_name"=>"Jeanie","last_name"=>"Kida","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-DeSantis","Anti-DEI-Repeal"],"in_custody"=>false,"released"=>true,"description"=>"Jeanie Kida, 26, Tampa Five defendant; charged March 6, 2023 at the USF anti-HB-999 protest. Charges dropped December 5, 2023; diversion program.","cases"=>[["institution_name"=>"Hillsborough County Sheriffs Office","institution_state"=>"Florida","charges"=>"FL Battery on a LEO; Disrupting School Campus; Resisting Officer Without Violence - March 2023 USF","arrest_date"=>"2023-03-06","convicted"=>"No - dismissed via diversion","sentence"=>"Diversion"]]],

    ["name"=>"Lauren Lynn Pineiro","first_name"=>"Lauren","middle_name"=>"Lynn","last_name"=>"Pineiro","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-DeSantis","Anti-DEI-Repeal"],"in_custody"=>false,"released"=>true,"description"=>"Lauren Lynn Pineiro, 23, Tampa Five defendant; turned herself in May 3, 2023 on the USF anti-HB-999 charges. Charges dropped December 5, 2023; diversion program.","cases"=>[["institution_name"=>"Hillsborough County Sheriffs Office","institution_state"=>"Florida","charges"=>"FL Battery on a LEO; Disrupting School Campus; Resisting Officer Without Violence - March 2023 USF","arrest_date"=>"2023-05-03","convicted"=>"No - dismissed via diversion","sentence"=>"Diversion"]]],

    ["name"=>"Laura Raquel Rodriguez","first_name"=>"Laura","middle_name"=>"Raquel","last_name"=>"Rodriguez","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"2020s","ideologies"=>["Anti-DeSantis","Anti-DEI-Repeal"],"in_custody"=>false,"released"=>true,"description"=>"Laura Raquel Rodriguez, 23, Tampa Five defendant; charged March 6, 2023 at the USF anti-HB-999 protest. Charges dropped December 5, 2023; diversion program.","cases"=>[["institution_name"=>"Hillsborough County Sheriffs Office","institution_state"=>"Florida","charges"=>"FL Battery on a LEO; Disrupting School Campus; Resisting Officer Without Violence - March 2023 USF","arrest_date"=>"2023-03-06","convicted"=>"No - dismissed via diversion","sentence"=>"Diversion"]]],

    ["name"=>"Hicham Talal","first_name"=>"Hicham","last_name"=>"Talal","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Connecticut","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Hicham Talal, 24, was arrested February 26, 2024 for vandalizing a Webster Bank in West Hartford CT for its investments in Israeli weapons manufacturing. Charged with hate-crime-enhanced criminal mischief; charges dropped July 29, 2024 after public protest pressure.","cases"=>[["institution_name"=>"Connecticut Superior Court","institution_state"=>"Connecticut","charges"=>"CT 53-181l(a)(2) Intimidation Based on Bigotry/Bias III; 53a-116 Criminal Mischief II - Feb 2024 Webster Bank vandalism","arrest_date"=>"2024-03-07","convicted"=>"No - charges dropped","sentence"=>"Dismissed"]]],

    ["name"=>"Yafa K. Issa","first_name"=>"Yafa","middle_name"=>"K.","last_name"=>"Issa","gender"=>"Female","race"=>"Middle Eastern / North African","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Yafa K. Issa, 18, was indicted May 16, 2024 with felony Mob Action and misdemeanor obstructing-a-peace-officer for the May 2024 UIUC Gaza encampment defense. Felony dismissed; convicted on misdemeanor obstruction. 12 months conditional discharge + 30 hours community service.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action (dismissed); 720 ILCS 5/31-1(a)(2) Resisting/Obstructing - May 2024 UIUC Gaza encampment","arrest_date"=>"2024-05-16","convicted"=>"Yes on misdemeanor","sentence"=>"12 months conditional discharge + 30 hours community service"]]],

    ["name"=>"George A. Vassilatos","first_name"=>"George","middle_name"=>"A.","last_name"=>"Vassilatos","gender"=>"Male","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"George A. Vassilatos, 25, indicted May 16, 2024 with felony Mob Action and misdemeanor obstructing for the UIUC Gaza encampment defense. Felony dismissed; misdemeanor guilty plea. 12 mo conditional discharge + 30 hrs community service.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action (dismissed); 720 ILCS 5/31-1(a)(2) Resisting - May 2024 UIUC","arrest_date"=>"2024-05-16","convicted"=>"Yes on misdemeanor","sentence"=>"12 mo conditional discharge + 30 hrs community service"]]],

    ["name"=>"Christopher K. Zelle","first_name"=>"Christopher","middle_name"=>"K.","last_name"=>"Zelle","aka"=>"Chris Zelle","gender"=>"Male","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Christopher K. Zelle, 37, indicted May 16, 2024 with two counts of Mob Action and felony aggravated battery for the UIUC Gaza encampment defense. Pleaded guilty to lesser; 4 days time served + 12 mo conditional discharge + 100 hours public service.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action [2 counts]; 720 ILCS 5/12-3.05 Aggravated Battery - May 2024 UIUC","arrest_date"=>"2024-05-16","convicted"=>"Yes - guilty plea","sentence"=>"4 days time served + 12 mo conditional discharge + 100 hrs public service"]]],

    ["name"=>"Elizabeth A. Sotiropoulos","first_name"=>"Elizabeth","middle_name"=>"A.","last_name"=>"Sotiropoulos","gender"=>"Female","race"=>"White","state"=>"Illinois","era"=>"2020s","ideologies"=>["Pro-Palestine"],"in_custody"=>false,"released"=>true,"description"=>"Elizabeth A. Sotiropoulos, 35, indicted May 16, 2024 with felony Mob Action and misdemeanor obstructing for the UIUC Gaza encampment defense. Pleaded guilty.","cases"=>[["institution_name"=>"Champaign County Circuit Court","institution_state"=>"Illinois","charges"=>"720 ILCS 5/25-1(a)(1) Mob Action; 720 ILCS 5/31-1(a)(2) Resisting - May 2024 UIUC","arrest_date"=>"2024-05-16","convicted"=>"Yes - guilty plea","sentence"=>"Local sentence"]]],

    ["name"=>"Jarrid Bailey Huber","first_name"=>"Jarrid","middle_name"=>"Bailey","last_name"=>"Huber","gender"=>"Male","race"=>"White","state"=>"Oregon","era"=>"2020s","ideologies"=>["Anti-police","Defend the Atlanta Forest"],"in_custody"=>false,"released"=>true,"description"=>"Jarrid Bailey Huber, 23, was arrested May 2, 2024 in Portland for starting a fire at a UPS distribution facility, stating UPS was financially supporting the Atlanta police training facility. Pleaded guilty January 14, 2025 to arson and criminal mischief; 10 days jail + 3 years probation.","cases"=>[["institution_name"=>"Multnomah County Circuit Court","institution_state"=>"Oregon","charges"=>"Oregon Arson; Reckless Burning; Criminal Mischief - May 2024 Portland UPS facility fire","arrest_date"=>"2024-05-02","sentenced_date"=>"2025-01-14","convicted"=>"Yes - guilty plea","sentence"=>"10 days jail + 3 years probation"]]],

    ["name"=>"Artur Tchibassa","first_name"=>"Artur","last_name"=>"Tchibassa","gender"=>"Male","race"=>"Black","state"=>"District of Columbia","era"=>"1990s","ideologies"=>["Nationalism","Separatism"],"affiliation"=>["Front de Liberation de lEtat du Cabinda (FLEC)"],"in_custody"=>false,"released"=>true,"description"=>"Artur Tchibassa, 47, FLEC member, was indicted September 25, 1991 in DC for the kidnapping of a Chevron employee in Angola; acted as negotiator/spokesperson for the kidnappers. Pleaded guilty; 293 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"District of Columbia","charges"=>"18 USC 371 Conspiracy to Defraud the United States; Conspiracy to Commit Hostage Taking; 18 USC 1203 Hostage Taking - Angola Chevron-employee kidnapping","arrest_date"=>"1991-09-25","convicted"=>"Yes - guilty plea","sentence"=>"293 months federal prison"]]],

    ["name"=>"Lafi Khalil","first_name"=>"Lafi","last_name"=>"Khalil","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"New York","era"=>"1990s","ideologies"=>["Nationalism","Anti-Israel"],"in_custody"=>false,"released"=>true,"description"=>"Lafi Khalil, 25, foreign national, was indicted August 28, 1997 with co-defendant Gazi Ibrahim Abu Mezer for a plot to detonate pipe bombs in the NYC subway during rush hour. Acquitted on conspiracy/WMD count; convicted on immigration-related charges. 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 1546(a) Fraud and Misuse of Visas/Permits - 1997 NYC subway pipe-bomb plot (acquitted on WMD count)","arrest_date"=>"1997-07-31","convicted"=>"Yes on visa fraud; acquitted on WMD","sentence"=>"36 months federal prison"]]],

    ["name"=>"Gazi Ibrahim Abu Mezer","first_name"=>"Gazi","middle_name"=>"Ibrahim","last_name"=>"Abu Mezer","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"New York","era"=>"1990s","ideologies"=>["Nationalism","Anti-Israel"],"in_custody"=>true,"released"=>false,"description"=>"Gazi Ibrahim Abu Mezer, 25, Palestinian foreign national, was indicted August 28, 1997 for plotting to detonate pipe bombs in the NYC subway in an attempted suicide attack to kill as many Jews as possible in protest of the Israeli/Palestinian conflict. Convicted; life without parole.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2332a(a)(2) Conspiracy to Use a Weapon of Mass Destruction; 18 USC 924(c)(1) Use of a Firearm (pipe bomb) During a Crime of Violence - 1997 NYC subway pipe-bomb plot","arrest_date"=>"1997-07-31","convicted"=>"Yes - guilty plea","sentence"=>"Life without parole"]]],

    ["name"=>"Jose Solis Jordan","first_name"=>"Jose Solis","last_name"=>"Jordan","gender"=>"Male","race"=>"Latino/Hispanic","state"=>"Illinois","era"=>"1990s","ideologies"=>["Nationalism","Puerto Rican Independence"],"affiliation"=>["Frente Revolucionario Boricua"],"in_custody"=>false,"released"=>true,"description"=>"Jose Solis Jordan, 46, Puerto Rican separatist, was indicted in 1999 in Chicago for a 1992 plot in which two bombs were placed near a US military recruiting facility (one detonated). Convicted; 51 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"18 USC 371 Conspiracy; 18 USC 844(f) Attempted Destruction of Government Property [2 counts]; 26 USC 5861(d) Illegal Possession of Explosives - 1992 Chicago military recruiting facility bombing","arrest_date"=>"1999-07-07","convicted"=>"Yes - jury verdict","sentence"=>"51 months federal prison"]]],

    ["name"=>"Conor Claxton","first_name"=>"Conor","last_name"=>"Claxton","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"1990s","ideologies"=>["Nationalism","Irish Republicanism"],"affiliation"=>["Irish Republican Army (IRA)"],"in_custody"=>false,"released"=>true,"description"=>"Conor Claxton, 27, Irish foreign national, was indicted July 26, 1999 in Florida along with co-defendants Anthony Smyth, Martin Mullen, and Siobhan Browne for IRA gun-running: purchasing weapons and ammunition in Florida and mailing them to Northern Ireland. Convicted; 56 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"22 USC 2778 Arms Export Control Act; 18 USC 371 Conspiracy - 1999 IRA gun-running","arrest_date"=>"1999-07-26","convicted"=>"Yes - jury verdict","sentence"=>"56 months federal prison"]]],

    ["name"=>"Martin Mullen","first_name"=>"Martin","last_name"=>"Mullen","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"1990s","ideologies"=>["Nationalism","Irish Republicanism"],"affiliation"=>["Irish Republican Army (IRA)"],"in_custody"=>false,"released"=>true,"description"=>"Martin Mullen, 30, Irish foreign national, IRA gun-running co-defendant; convicted; 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"22 USC 2778 Arms Export Control Act; 18 USC 371 Conspiracy - 1999 IRA gun-running","arrest_date"=>"1999-07-26","convicted"=>"Yes - jury verdict","sentence"=>"36 months federal prison"]]],

    ["name"=>"Anthony Smyth","first_name"=>"Anthony","last_name"=>"Smyth","gender"=>"Male","race"=>"White","state"=>"Florida","era"=>"1990s","ideologies"=>["Nationalism","Irish Republicanism"],"affiliation"=>["Irish Republican Army (IRA)"],"in_custody"=>false,"released"=>true,"description"=>"Anthony Smyth, 43, US citizen, IRA gun-running co-defendant; convicted; 36 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"22 USC 2778 Arms Export Control Act; 18 USC 371 Conspiracy - 1999 IRA gun-running","arrest_date"=>"1999-07-26","convicted"=>"Yes - jury verdict","sentence"=>"36 months federal prison"]]],

    ["name"=>"Siobhan Browne","first_name"=>"Siobhan","last_name"=>"Browne","gender"=>"Female","race"=>"White","state"=>"Florida","era"=>"1990s","ideologies"=>["Nationalism","Irish Republicanism"],"affiliation"=>["Irish Republican Army (IRA)"],"in_custody"=>false,"released"=>true,"description"=>"Siobhan Browne, 37, US citizen, was charged July 26, 1999 with conspiracy to mail weapons and Arms Export Control Act violations after buying 27 guns in Florida to support the IRA. Pleaded guilty; 20 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"22 USC 2778 Arms Export Control Act; 18 USC 371 Conspiracy to Mail Weapons - 1999 IRA gun purchase","arrest_date"=>"1999-07-26","convicted"=>"Yes - guilty plea","sentence"=>"20 months federal prison"]]],

    ["name"=>"Thomas Chism","first_name"=>"Thomas","last_name"=>"Chism","gender"=>"Male","race"=>"Black","state"=>"Georgia","era"=>"2000s","ideologies"=>["Nationalism","Black Indigenous Sovereignty"],"affiliation"=>["United Nuwaubian Nation of Moors"],"in_custody"=>false,"released"=>true,"description"=>"Thomas Chism, agent for the United Nuwaubian Nation of Moors in Eatonton GA, was convicted April 26, 2000 of knowingly passing a forged document to county authorities. Sentenced to several months in jail and a $1,000 fine.","cases"=>[["institution_name"=>"Putnam County jail","institution_state"=>"Georgia","charges"=>"Georgia state Knowingly Passing a Forged Document - 2000 Eatonton","arrest_date"=>"2000-04-26","convicted"=>"Yes - jury verdict","sentence"=>"~3 months + $1,000 fine"]]],

    ["name"=>"Tony Alexander Hamilton","first_name"=>"Tony","middle_name"=>"Alexander","last_name"=>"Hamilton","gender"=>"Male","state"=>"Utah","era"=>"2000s","ideologies"=>["Anti-government","Religious-separatism"],"affiliation"=>["Immanuel Foundation"],"in_custody"=>false,"released"=>true,"description"=>"Tony Alexander Hamilton, 58, of Beaver UT, leader of the Immanuel Foundation / Fraternity of Preparation, shot at a Beaver County sheriffs deputy during a 1999 standoff over property taxes the group refused to pay. Convicted of attempted aggravated murder, aggravated assault, criminal trespass, killing a police service dog, and interference. Sentenced to 5 years to life + ~5 years on each other count, all consecutive (~240 months minimum).","cases"=>[["institution_name"=>"Utah Department of Corrections","institution_state"=>"Utah","charges"=>"UCA 76-5-202 Attempted Aggravated Murder; 76-5-103 Aggravated Assault; 76-9-306 Killing a Police Service Dog; 76-8-305 Interference; 76-6-206 Criminal Trespass - 1999 Beaver County deputy shooting","arrest_date"=>"1999-09-09","convicted"=>"Yes - jury verdict","sentence"=>"~240 months minimum (5 years to life)"]]],

    ["name"=>"Mourad Topalian","first_name"=>"Mourad","last_name"=>"Topalian","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Ohio","era"=>"2000s","ideologies"=>["Nationalism","Armenian"],"affiliation"=>["Justice Commandos of the Armenian Genocide (JCAG)"],"in_custody"=>false,"released"=>true,"description"=>"Mourad Topalian, 57, suspected leader of the Justice Commandos of the Armenian Genocide (JCAG), was sentenced January 24, 2001 in Bedford OH after pleading guilty to conspiracy, possession of explosives and machine guns, possession of firearms with defaced serial numbers, and interstate transportation. He had stored weapons for distribution to JCAG members for use against Turkish targets. 37 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Ohio","charges"=>"18 USC Conspiracy; Possession of Machine Guns; Possession of Firearms With Defaced Serial Numbers; Interstate Transportation - JCAG weapons cache","arrest_date"=>"2001-01-24","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison"]]],

    ["name"=>"Irving David Rubin","first_name"=>"Irving","middle_name"=>"David","last_name"=>"Rubin","gender"=>"Male","race"=>"White","state"=>"California","era"=>"2000s","ideologies"=>["Jewish Defense","Nationalism"],"affiliation"=>["Jewish Defense League (JDL)"],"in_custody"=>false,"released"=>false,"death_date"=>"2002-11-13","description"=>"Irving David Rubin, 74, JDL Chairman and former Air Force serviceman, was indicted December 12, 2001 with Earl Krugel for conspiring to bomb the King Fahd Mosque in Culver City CA and the office of US Rep Darrell Issa. Caught in an FBI sting via informant Danny Gillis. While imprisoned at MDC Los Angeles awaiting trial, Rubin cut his own throat and jumped off a balcony November 4, 2002; died of injuries November 13, 2002.","cases"=>[["institution_name"=>"Metropolitan Detention Center Los Angeles","institution_city"=>"Los Angeles","institution_state"=>"California","charges"=>"18 USC 371 Conspiracy; 18 USC 844(i) Use of Explosive; 18 USC 924(c)(1) Firearm in Furtherance - 2001 King Fahd Mosque / Issa office bomb plot","arrest_date"=>"2001-12-12","death_in_custody_date"=>"2002-11-13","convicted"=>"No - died awaiting trial","sentence"=>"Suicide in pretrial custody"]]],

    ["name"=>"Hazim Elashi","first_name"=>"Hazim","last_name"=>"Elashi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation","Infocom"],"in_custody"=>false,"released"=>true,"description"=>"Hazim Elashi, 56, was indicted December 17, 2002 in the Infocom case along with brothers Bayan, Ghassan, Basman, and Ihsan, plus cousins Mousa Abu Marzook and Nadia Elashi. Manager of personal computer systems for Infocom; from 1997-2000 illegally shipped computers to Libya and Syria. Sentenced January 2006 to 66 months federal prison + deportation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 371 Conspiracy to Violate Export Administration Regulations and Libyan Sanctions; 50 USC 1701-1706 Libyan/Syrian Export Violations; 18 USC 1956(h) Money Laundering Conspiracy; 18 USC 1957 Money Laundering - Dec 2002 Infocom indictment","arrest_date"=>"2002-12-17","convicted"=>"Yes - jury verdict","sentence"=>"66 months federal prison + deportation"]]],

    ["name"=>"Ihsan Elashi","first_name"=>"Ihsan","last_name"=>"Elashi","aka"=>"Sammy Elashi, Sammy Elashyi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation","Infocom"],"in_custody"=>false,"released"=>true,"description"=>"Ihsan Elashi, 46, Infocom systems consultant/sales rep, sentenced January 2006 to 72 months federal prison consecutive to a 48-month federal sentence on unrelated charges.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 371 Conspiracy to Violate Export Regs; 50 USC 1701-1706 Libyan/Syrian Export Violations; 18 USC 1957 Money Laundering - Dec 2002 Infocom","arrest_date"=>"2002-12-17","convicted"=>"Yes - jury verdict","sentence"=>"72 months federal prison consecutive"]]],

    ["name"=>"Basman Elashi","first_name"=>"Basman","last_name"=>"Elashi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation","Infocom"],"in_custody"=>false,"released"=>true,"description"=>"Basman Elashi, 50, Infocom logistics and credit manager. Sentenced October 2006 to 80 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 371 Conspiracy to Violate Export Regs; 50 USC 1701-1706 Libyan/Syrian Export; Dealing in the Property of a Specially Designated Terrorist - Dec 2002 Infocom","arrest_date"=>"2002-12-17","convicted"=>"Yes - jury verdict","sentence"=>"80 months federal prison"]]],

    ["name"=>"Ghassan Elashi","first_name"=>"Ghassan","last_name"=>"Elashi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation","Infocom"],"in_custody"=>true,"released"=>false,"description"=>"Ghassan Elashi, 52, Infocom VP of marketing and HLF founding member; convicted in two separate prosecutions: the December 2002 Infocom export-violations case (80 months) and the July 2004 Holy Land Foundation material-support-to-HAMAS case (780 months). HLF funneled $12 million in claimed humanitarian aid to Palestine.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"Dec 2002 Infocom case: 18 USC 371 Conspiracy to Violate Export Regs; 50 USC 1701-1706 Libyan/Syrian Export Violations; Dealing in the Property of a Specially Designated Terrorist","arrest_date"=>"2002-12-17","convicted"=>"Yes - jury verdict","sentence"=>"80 months federal prison (Infocom)"],["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"July 2004 HLF case: 18 USC 2339B Material Support to a Foreign Terrorist Organization (HAMAS); 50 USC 1701-1706 IEEPA; 18 USC 1956 Money Laundering - HLF $12M to HAMAS via charitable fronts","arrest_date"=>"2004-07-27","convicted"=>"Yes - jury verdict (after mistrial/retrial)","sentence"=>"780 months federal prison (HLF)"]]],

    ["name"=>"Bayan Elashi","first_name"=>"Bayan","last_name"=>"Elashi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation","Infocom"],"in_custody"=>false,"released"=>true,"description"=>"Bayan Elashi, 51, Infocom CEO. Sentenced October 2006 to 84 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 371 Conspiracy to Violate Export Regs; Libyan/Syrian Export Violations; Dealing in the Property of a Specially Designated Terrorist; 18 USC 1957 Money Laundering - Dec 2002 Infocom","arrest_date"=>"2002-12-17","convicted"=>"Yes - jury verdict","sentence"=>"84 months federal prison"]]],

    ["name"=>"John Earl Johnson","first_name"=>"John","middle_name"=>"Earl","last_name"=>"Johnson","aka"=>"Yaya","gender"=>"Male","race"=>"Black","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS"],"in_custody"=>false,"released"=>true,"description"=>"John Earl Johnson, 26, was found with CDs containing terrorism information / explosive-making instructions and was connected to the Albany pizzeria case (Yassin Aref). Pleaded guilty; 46 months federal prison + supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 922 Illegal Possession of Firearms - Jan 2003 Albany","arrest_date"=>"2003-01-21","convicted"=>"Yes - guilty plea","sentence"=>"46 months federal prison"]]],

    ["name"=>"Jamil Salem Sarsour","first_name"=>"Jamil","middle_name"=>"Salem","last_name"=>"Sarsour","aka"=>"Jim Salem, Abi Salem","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Wisconsin","era"=>"2000s","ideologies"=>["Pro-Palestine"],"affiliation"=>["HAMAS"],"in_custody"=>false,"released"=>true,"description"=>"Jamil Salem Sarsour, 53, pleaded guilty in Israel in 1998 to aiding Hamas; deported to the US and charged in 2002 with currency structuring (sending $25,000 to Israel evading transaction reporting). Probation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Wisconsin","charges"=>"31 USC 5324 Currency Structuring - 2002 Milwaukee","arrest_date"=>"2003-01-21","convicted"=>"Yes - guilty plea","sentence"=>"Probation"]]],

    ["name"=>"Sami Amin Al-Arian","first_name"=>"Sami","middle_name"=>"Amin","last_name"=>"Al-Arian","aka"=>"Amin, The Secretary, Abu Abdullah","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Florida","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["Palestinian Islamic Jihad (PIJ)"],"in_custody"=>false,"released"=>true,"description"=>"Sami Amin Al-Arian, 61, US permanent resident and former University of South Florida professor, was indicted February 19, 2003 in Tampa on 17 racketeering / material support / money laundering / immigration counts. Pleaded guilty; 57 months federal prison + 36 months supervised release + deportation.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 1962 Racketeering; 18 USC 2339B Material Support to PIJ; 50 USC 1701-1706 IEEPA; 18 USC 1956 Money Laundering; 8 USC 1425 Procurement of Citizenship Fraud - PIJ Tampa case","arrest_date"=>"2003-02-19","convicted"=>"Yes - guilty plea","sentence"=>"57 months federal prison + deportation"]]],

    ["name"=>"Sameeh Taha Hammoudeh","first_name"=>"Sameeh","middle_name"=>"Taha","last_name"=>"Hammoudeh","aka"=>"Sameeh Hamouda, Abu Anas","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Florida","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["Palestinian Islamic Jihad (PIJ)"],"in_custody"=>false,"released"=>true,"description"=>"Sameeh Taha Hammoudeh, PIJ Tampa co-defendant indicted Feb 19, 2003. Found not guilty on 10 counts; remaining 10 dismissed.","cases"=>[["institution_name"=>"US District Court Middle District of Florida","institution_state"=>"Florida","charges"=>"18 USC 1962 Racketeering; 18 USC 2339B Material Support to PIJ - PIJ Tampa case","arrest_date"=>"2003-02-19","convicted"=>"No - acquitted on all counts","sentence"=>"Acquitted"]]],

    ["name"=>"Ghassan Zayed Ballut","first_name"=>"Ghassan","middle_name"=>"Zayed","last_name"=>"Ballut","aka"=>"Abu Fadi","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Florida","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["Palestinian Islamic Jihad (PIJ)"],"in_custody"=>false,"released"=>true,"description"=>"Ghassan Zayed Ballut, 47, PIJ Tampa co-defendant; found not guilty on all 27 counts that went to verdict; 7 dismissed.","cases"=>[["institution_name"=>"US District Court Middle District of Florida","institution_state"=>"Florida","charges"=>"18 USC 1962 Racketeering; 18 USC 2339B Material Support to PIJ - PIJ Tampa case","arrest_date"=>"2003-02-19","convicted"=>"No - acquitted on all","sentence"=>"Acquitted"]]],

    ["name"=>"Hatem Naji Fariz","first_name"=>"Hatem","middle_name"=>"Naji","last_name"=>"Fariz","aka"=>"Abu Obayada, Abu Obaida","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Florida","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["Palestinian Islamic Jihad (PIJ)"],"in_custody"=>false,"released"=>true,"description"=>"Hatem Naji Fariz, 36, PIJ Tampa co-defendant; convicted on some counts; 37 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Florida","charges"=>"18 USC 1962 Racketeering; 18 USC 2339B Material Support to PIJ; 18 USC 1956 Money Laundering - PIJ Tampa case","arrest_date"=>"2003-02-19","convicted"=>"Yes on some counts","sentence"=>"37 months federal prison"]]],

    ["name"=>"Mazen Al-Najjar","first_name"=>"Mazen","last_name"=>"Al-Najjar","aka"=>"Mukhtar","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Florida","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["Palestinian Islamic Jihad (PIJ)"],"in_custody"=>false,"released"=>true,"description"=>"Mazen Al-Najjar, 62, PIJ Tampa co-defendant on a visa overstay; deported on visa overstay rather than serving prison time on the substantive charges.","cases"=>[["institution_name"=>"US District Court Middle District of Florida","institution_state"=>"Florida","charges"=>"18 USC 1962 Racketeering; 18 USC 2339B Material Support to PIJ; 18 USC 1546 Visa Fraud - PIJ Tampa case","arrest_date"=>"2003-02-19","convicted"=>"Yes on some counts","sentence"=>"Deported"]]],

    ["name"=>"Soliman S. Biheiri","first_name"=>"Soliman","middle_name"=>"S.","last_name"=>"Biheiri","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"New Jersey","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS"],"in_custody"=>false,"released"=>true,"description"=>"Soliman S. Biheiri, 66, ran an Islamic-principles investment company; lied on his US citizenship application and to the FBI about connections to Hamas and Sami Al-Arian. 12 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New Jersey","charges"=>"18 USC 1425(a) Unlawful Procurement of Naturalization; 18 USC 1001 Materially False Statements; 18 USC 1015 False Statement Relating to Naturalization - 2003 NJ","arrest_date"=>"2003-08-03","convicted"=>"Yes - jury verdict","sentence"=>"12 months federal prison"]]],

    ["name"=>"Mufid Abdel Abdulqader","first_name"=>"Mufid","middle_name"=>"Abdel","last_name"=>"Abdulqader","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation"],"in_custody"=>true,"released"=>false,"description"=>"Mufid Abdel Abdulqader, 49, HLF defendant indicted July 26, 2004; convicted at trial on material support to HAMAS counts. 240 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 2339B Material Support to FTO (HAMAS); 50 USC 1701-1706 IEEPA; 18 USC 1956 Money Laundering Conspiracy - HLF case","arrest_date"=>"2004-07-26","convicted"=>"Yes - jury verdict","sentence"=>"240 months federal prison"]]],

    ["name"=>"Shukri Abu-Baker","first_name"=>"Shukri","last_name"=>"Abu-Baker","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation"],"in_custody"=>true,"released"=>false,"description"=>"Shukri Abu-Baker, 44, HLF founder/CEO; convicted at trial on material support to HAMAS. 1,020 months (85 years) federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 2339B Material Support to FTO (HAMAS); 50 USC 1701-1706 IEEPA; 18 USC 1956 Money Laundering Conspiracy - HLF case","arrest_date"=>"2004-07-26","convicted"=>"Yes - jury verdict","sentence"=>"1,020 months federal prison"]]],

    ["name"=>"Mohamed El-Mezain","first_name"=>"Mohamed","last_name"=>"El-Mezain","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation"],"in_custody"=>false,"released"=>true,"description"=>"Mohamed El-Mezain, 55, HLF defendant; convicted at trial; 180 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 2339B Material Support to FTO (HAMAS); 50 USC 1701-1706 IEEPA; 26 USC 7206 Filing False Tax Returns - HLF case","arrest_date"=>"2004-07-26","convicted"=>"Yes - jury verdict","sentence"=>"180 months federal prison"]]],

    ["name"=>"Abdulrahman Odeh","first_name"=>"Abdulrahman","last_name"=>"Odeh","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Texas","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS","Holy Land Foundation"],"in_custody"=>false,"released"=>true,"description"=>"Abdulrahman Odeh, 49, NJ representative of HLF; assisted in funneling $12 million in claimed humanitarian aid to Palestine. Convicted at trial; 180 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Texas","charges"=>"18 USC 2339B Material Support to FTO (HAMAS); 50 USC 1701-1706 IEEPA; 18 USC 1956 Money Laundering Conspiracy - HLF case","arrest_date"=>"2004-07-26","convicted"=>"Yes - jury verdict","sentence"=>"180 months federal prison"]]],

    ["name"=>"Abdelhaleem Hasan Abdelraziq Ashqar","first_name"=>"Abdelhaleem","middle_name"=>"Hasan Abdelraziq","last_name"=>"Ashqar","aka"=>"Abu Hasan, Abu Ali Hasan, Samir","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Illinois","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS"],"in_custody"=>false,"released"=>true,"description"=>"Abdelhaleem Hasan Abdelraziq Ashqar, 46, was arrested August 19, 2004 in Chicago for HAMAS recruitment activity. Convicted on criminal contempt and obstruction of justice (with terrorism enhancement) plus racketeering conspiracy. 135 months federal prison + $5,000.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"18 USC 401(3) Criminal Contempt; 18 USC 1503 Obstruction of Justice; 18 USC 1962(d) Racketeering Conspiracy with USSG 3A1.4 Terrorism Enhancement - 2004 Chicago HAMAS recruitment","arrest_date"=>"2004-08-19","convicted"=>"Yes - jury verdict","sentence"=>"135 months federal prison"]]],

    ["name"=>"Muhammad Hamid Khalil Salah","first_name"=>"Muhammad","middle_name"=>"Hamid Khalil","last_name"=>"Salah","aka"=>"Abu Ahmad","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Illinois","era"=>"2000s","ideologies"=>["Nationalism","Pro-Palestine"],"affiliation"=>["HAMAS"],"in_custody"=>false,"released"=>true,"description"=>"Muhammad Hamid Khalil Salah, 51, was indicted August 19, 2004 in Chicago for HAMAS recruitment / material support / racketeering conspiracy. 21 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Illinois","charges"=>"18 USC 2339B Material Support to FTO (HAMAS); 18 USC 1962(d) Racketeering Conspiracy - 2004 Chicago","arrest_date"=>"2004-08-19","convicted"=>"Yes - jury verdict","sentence"=>"21 months federal prison"]]],

    ["name"=>"Naveed Afzal Haq","first_name"=>"Naveed","middle_name"=>"Afzal","last_name"=>"Haq","gender"=>"Male","race"=>"Middle Eastern / North African","state"=>"Washington","era"=>"2000s","ideologies"=>["Nationalism","Anti-Israel","Anti-Jewish"],"in_custody"=>true,"released"=>false,"description"=>"Naveed Afzal Haq, 31, Pakistani-American, fatally shot one woman and wounded five at the Jewish Federation of Greater Seattle on July 28, 2006, citing the Israel-Palestine conflict. Convicted of first-degree aggravated murder, 3 counts of first-degree attempted murder, 2 counts of second-degree attempted murder, unlawful imprisonment, and malicious harassment. Sentenced to life without parole.","cases"=>[["institution_name"=>"Washington State Department of Corrections","institution_state"=>"Washington","charges"=>"WA First-Degree Aggravated Murder; First-Degree Attempted Murder [3 counts]; Second-Degree Attempted Murder [2 counts]; Unlawful Imprisonment; Malicious Harassment - July 2006 Jewish Federation Seattle shooting","arrest_date"=>"2006-07-28","convicted"=>"Yes - jury verdict","sentence"=>"Life without parole"]]],

    ["name"=>"Sathajhan Sarachandran","first_name"=>"Sathajhan","last_name"=>"Sarachandran","aka"=>"Satha","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Sathajhan Sarachandran, 29, Tamil Tigers material-support defendant indicted September 12, 2006 in Brooklyn for purchasing weapons from an undercover FBI agent. 132 months federal prison + 60 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to LTTE Conspiracy - 2006 NY weapons-purchase sting","arrest_date"=>"2006-09-12","convicted"=>"Yes - guilty plea","sentence"=>"132 months federal prison"]]],

    ["name"=>"Thiruthanikan Thanigasalam","first_name"=>"Thiruthanikan","last_name"=>"Thanigasalam","aka"=>"Thani","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>true,"released"=>false,"description"=>"Thiruthanikan Thanigasalam, 38, LTTE material-support defendant; 312 months federal prison + 60 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to LTTE Conspiracy - 2006 NY weapons-purchase sting","arrest_date"=>"2006-09-13","convicted"=>"Yes - guilty plea","sentence"=>"312 months federal prison"]]],

    ["name"=>"Sahilal Sabaratnam","first_name"=>"Sahilal","last_name"=>"Sabaratnam","aka"=>"Sahil","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>true,"released"=>false,"description"=>"Sahilal Sabaratnam, 29, LTTE material-support defendant; 300 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to LTTE Conspiracy - 2006 NY weapons-purchase sting","arrest_date"=>"2006-09-13","convicted"=>"Yes - guilty plea","sentence"=>"300 months federal prison"]]],

    ["name"=>"Piratheepan Nadarajah","first_name"=>"Piratheepan","last_name"=>"Nadarajah","aka"=>"Peter","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Piratheepan Nadarajah, 29, conspired with co-defendant Suresh Sriskandarajah to purchase $1 million worth of weapons for the Tamil Tigers from an undercover FBI agent. Extradited from Canada. 24 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to LTTE Conspiracy - LTTE arms procurement","arrest_date"=>"2006-09-13","convicted"=>"Yes - guilty plea","sentence"=>"24 months federal prison"]]],

    ["name"=>"Nadarasa Yograrasa","first_name"=>"Nadarasa","last_name"=>"Yograrasa","aka"=>"Yoga","gender"=>"Female","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Nadarasa Yograrasa, 55, LTTE material-support defendant in the Long Island weapons-purchase conspiracy. 168 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to LTTE Conspiracy - 2006 LTTE arms purchase","arrest_date"=>"2006-09-14","convicted"=>"Yes - guilty plea","sentence"=>"168 months federal prison"]]],

    ["name"=>"Erick Wotulo","first_name"=>"Erick","last_name"=>"Wotulo","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Erick Wotulo, 60, retired Indonesian military general, was caught in an ICE/FBI sting along with Subandi, Osman, Soedirdja, Rusli, and Varatharasa for arranging arms sales to the Tamil Tigers. 30 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 371 Conspiracy to Export Arms; 18 USC 2339B Material Support to FTO; 18 USC 1956 Money Laundering - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-09-17","convicted"=>"Yes - guilty plea","sentence"=>"30 months federal prison"]]],

    ["name"=>"Haji Subandi","first_name"=>"Haji","last_name"=>"Subandi","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Haji Subandi, 69, Tamil Tigers ICE-sting defendant; emailed an FBI undercover business inquiring about weapons and sent a list of 53 military weapons. 37 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 371 Conspiracy to Export Arms; 18 USC 2339B Material Support to FTO; 18 USC 1956 Money Laundering - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-09-17","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison"]]],

    ["name"=>"Haniffa Bin Osman","first_name"=>"Haniffa","middle_name"=>"Bin","last_name"=>"Osman","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Haniffa Bin Osman, 57, retired Indonesian Marine Corps general, Tamil Tigers ICE-sting defendant; wired $752,000 down payment for the weapons. 37 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 2339B Material Support to FTO; 18 USC 1956 Money Laundering - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-09-17","convicted"=>"Yes - guilty plea","sentence"=>"37 months federal prison"]]],

    ["name"=>"Helmi Soedirdja","first_name"=>"Helmi","last_name"=>"Soedirdja","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Helmi Soedirdja, 33, Tamil Tigers ICE-sting defendant. 12 months federal prison + 24 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 371 Conspiracy to Export Defense Articles; 22 USC 2778 Arms Export Control Act - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-09-29","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Reinhard Rusli","first_name"=>"Reinhard","last_name"=>"Rusli","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Reinhard Rusli, 35, Tamil Tigers ICE-sting defendant. 12 months federal prison + 24 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 371 Conspiracy to Export Defense Articles; 22 USC 2778 Arms Export Control Act - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-09-29","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison"]]],

    ["name"=>"Thirunavukkarasu Varatharasa","first_name"=>"Thirunavukkarasu","last_name"=>"Varatharasa","gender"=>"Male","race"=>"South Asian","state"=>"Maryland","era"=>"2000s","ideologies"=>["Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Thirunavukkarasu Varatharasa, 36, Tamil Tigers ICE-sting defendant. 57 months federal prison + 36 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"Maryland","charges"=>"18 USC 371 Conspiracy to Export Defense Articles; 22 USC 2778 Arms Export Control Act - 2006 ICE Tamil Tigers sting","arrest_date"=>"2006-10-02","convicted"=>"Yes - guilty plea","sentence"=>"57 months federal prison"]]],

    ["name"=>"Khalid Awan","first_name"=>"Khalid","last_name"=>"Awan","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Sikh Khalistan"],"affiliation"=>["Khalistan Commando Force (KCF)"],"in_custody"=>false,"released"=>true,"description"=>"Khalid Awan, 50, Pakistani foreign national, was indicted October 25, 2006 for providing material support to KCF (Sikh militants seeking a separate Sikh state). At trial, prison phone calls captured him recruiting for KCF and admitting sending hundreds of thousands of dollars to Paramjit Sing Panjwar in Pakistan. 168 months federal prison + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339A Conspiring to Provide Material Support to Murder/Kidnap/Maim Outside US; 18 USC 956(a) Conspiracy; 18 USC 1956 Money Laundering - 2006 KCF support","arrest_date"=>"2006-10-25","convicted"=>"Yes - jury verdict","sentence"=>"168 months federal prison"]]],

    ["name"=>"Pratheepan Thavaraja","first_name"=>"Pratheepan","last_name"=>"Thavaraja","aka"=>"Raja Pratheepan, Thambi Sampras, Steeban","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Pratheepan Thavaraja, 37, senior LTTE procurement agent involved in worldwide purchases of IEDs, missiles, machine guns, artillery, radar from countries including the US. With Murugesu Vinayagamoorthy, attempted to bribe an undercover State Department official to remove LTTE from the FTO list. 108 months federal prison + 60 months supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO (LTTE); 18 USC 371 Conspiracy to Bribe Public Officials; 18 USC 371 Conspiracy to Defraud the United States - 2007 LTTE bribery / arms procurement","arrest_date"=>"2007-05-21","convicted"=>"Yes - guilty plea","sentence"=>"108 months federal prison"]]],

    ["name"=>"Nachimuthu Socrates","first_name"=>"Nachimuthu","last_name"=>"Socrates","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Nachimuthu Socrates, 58, conspired to provide resources, currency, training, and false documents to the Tamil Tigers; wrote a $500 check and gave $5,000 to FBI agents posing as State Dept officials. 12 months federal prison + 36 months supervised release + community service + $20,000 fine.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 371 Conspiracy to Defraud the United States [2 counts]; 18 USC 2339B Material Support to FTO [2 counts]; 18 USC 371 Conspiracy to Bribe Public Officials [2 counts] - 2007 LTTE bribery sting","arrest_date"=>"2007-05-21","convicted"=>"Yes - guilty plea","sentence"=>"12 months federal prison + $20,000 fine"]]],

    ["name"=>"Murugesu Vinayagamoorthy","first_name"=>"Murugesu","last_name"=>"Vinayagamoorthy","aka"=>"Dr. Moorthy","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Murugesu Vinayagamoorthy, 62, helped launder LTTE money through a Swiss bank to cover a Sri Lanka congressional trip; with Pratheepan Thavaraja, attempted to bribe an undercover State Dept official to remove LTTE from the FTO list. 54 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO; 18 USC 371 Conspiracy to Bribe Public Officials; 50 USC 1705 IEEPA - 2007 LTTE bribery / money laundering","arrest_date"=>"2007-05-21","convicted"=>"Yes - guilty plea","sentence"=>"54 months federal prison"]]],

    ["name"=>"Vijayshanthar Patpanathan","first_name"=>"Vijayshanthar","last_name"=>"Patpanathan","aka"=>"Chandru","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Vijayshanthar Patpanathan, 43, assisted Kandasamy in fundraising and money laundering for LTTE. Time served + 3 years supervised release.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO; 18 USC 371 Conspiracy to Bribe Public Officials - 2007 LTTE","arrest_date"=>"2007-05-21","convicted"=>"Yes - guilty plea","sentence"=>"Time served + 3 years supervised release"]]],

    ["name"=>"Karunakaran Kandasamy","first_name"=>"Karunakaran","last_name"=>"Kandasamy","aka"=>"Karuna","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Karunakaran Kandasamy, 55, director of the American branch of LTTE, oversaw fundraising of millions of dollars laundered through the Tamil Rehabilitation Organization (TRO). Sentenced to 240 months federal prison; time served.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO (LTTE); 18 USC 1956 Money Laundering - LTTE US branch","arrest_date"=>"2009-06-09","convicted"=>"Yes - guilty plea","sentence"=>"240 months federal prison (time served)"]]],

    ["name"=>"Ramanan Mylvaganam","first_name"=>"Ramanan","last_name"=>"Mylvaganam","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Ramanan Mylvaganam, 29, conspired to purchase ~$22,000 in submarine design software for LTTE from a UK company, and night vision equipment from a Canadian company; assisted in computer/electronics/communications procurement. Time served.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO (LTTE) - LTTE software/electronics procurement","arrest_date"=>"2009-12-29","convicted"=>"Yes - guilty plea","sentence"=>"Time served"]]],

    ["name"=>"Suresh Sriskandarajah","first_name"=>"Suresh","last_name"=>"Sriskandarajah","aka"=>"Waterloo Suresh","gender"=>"Male","race"=>"South Asian","state"=>"New York","era"=>"2000s","ideologies"=>["Nationalism","Tamil Eelam"],"affiliation"=>["LTTE"],"in_custody"=>false,"released"=>true,"description"=>"Suresh Sriskandarajah, 32, Canadian foreign national, conspired with Piratheepan Nadarajah to purchase $1 million in weapons for the LTTE from an undercover FBI agent. Extradited from Canada. 10 months federal prison.","cases"=>[["institution_name"=>"Federal Bureau of Prisons (location varied)","institution_state"=>"New York","charges"=>"18 USC 2339B Material Support to FTO (LTTE); 50 USC 1705 IEEPA - LTTE arms procurement","arrest_date"=>"2009-12-29","convicted"=>"Yes - guilty plea","sentence"=>"10 months federal prison"]]],
];

$created = 0; $existing = 0; $errors = 0;
foreach ($rows as $row) {
    $name = $row["name"];
    $existsP = App\Models\Prisoner::where("name", $name)
        ->orWhere("name", "like", "%" . $name . "%")
        ->first();
    if ($existsP) {
        echo "EXISTS: {$name}\n";
        $existing++;
        continue;
    }
    $cases = $row["cases"] ?? [];
    unset($row["cases"]);
    try {
        $prisoner = App\Models\Prisoner::create($row);
    } catch (\Throwable $e) {
        echo "ERROR creating {$name}: {$e->getMessage()}\n";
        $errors++;
        continue;
    }
    foreach ($cases as $c) {
        $instName  = $c["institution_name"]  ?? "Federal Bureau of Prisons (location varied)";
        $instCity  = $c["institution_city"]  ?? null;
        $instState = $c["institution_state"] ?? null;
        unset($c["institution_name"], $c["institution_city"], $c["institution_state"]);
        $inst = App\Models\Institution::firstOrCreate(
            ["name" => $instName],
            array_filter(["city" => $instCity, "state" => $instState])
        );
        $c["prisoner_id"] = $prisoner->id;
        $c["institution_id"] = $inst->id;
        try {
            App\Models\PrisonerCase::create($c);
        } catch (\Throwable $e) {
            echo "  case-create error for {$name}: {$e->getMessage()}\n";
        }
    }
    echo "CREATED: {$name}\n";
    $created++;
}
echo "\nSummary: created={$created}, existing={$existing}, errors={$errors}\n";
'

echo
echo "Prosecution Project rows 801-900 import complete."
